### ISSUE TITLE
BlenderBIM IFC Import Issue

### ISSUE THREAD

**Issue by AlexPlenty** [IfcOpenShell/IfcOpenShell#1002]
Hi!

I've tried importing an Ifc which I know works in Solibri but doesn't seem to work here (Happy to provide the ifc)

Thanks :)

LOG:

Traceback (most recent call last):
  File "C:\Users\alexp\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 91, in execute
    logger = logging.getLogger('ExportIFC')
  File "C:\Users\alexp\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 325, in execute
    self.profile_code('Create constraints')
  File "C:\Users\alexp\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 1495, in create_spatial_hierarchy
    
  File "C:\Users\alexp\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 1515, in add_related_objects
    }
  File "C:\Users\alexp\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 1509, in add_related_objects
    'last_revision_time': 'LastRevisionTime',
  File "C:\Users\alexp\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 854, in create_product
    self.add_element_document_relations(element, obj)
  File "C:\Users\alexp\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 1723, in get_element_matrix
    self.ifc_import_settings.logger.warning('Warning: this object is outside the spatial hierarchy {}'.format(element))
  File "C:\Users\alexp\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 1961, in get_local_placement
    bm.verts.index_update()
  File "C:\Users\alexp\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 1936, in get_axis2placement
    polyline.points[-1].co = v2
AttributeError: 'str' object has no attribute 'DirectionRatios'

location: <unknown location>:-1

**Comment by Moult** [comment]
Can you provide the IFC please?

If it is private, send to dion@thinkmoult.com

**Comment by AlexPlenty** [comment]
> Can you provide the IFC please?
> 
> If it is private, send to [dion@thinkmoult.com](mailto:dion@thinkmoult.com)

Thanks Dion, I've just emailed it through! :)

**Comment by Moult** [comment]
@AlexPlenty the IFC file you provided is invalid, so this is not a bug in the BlenderBIM Add-on, it contains this line:

```
#31= IFCAXIS2PLACEMENT3D(#6,'Test5','Test6');
```

Did somebody try to edit this file by hand? I can't imagine Revit outputting this.

**Comment by AlexPlenty** [comment]
> @AlexPlenty the IFC file you provided is invalid, so this is not a bug in the BlenderBIM Add-on, it contains this line:
> 
> ```
> #31= IFCAXIS2PLACEMENT3D(#6,'Test5','Test6');
> ```
> 
> Did somebody try to edit this file by hand? I can't imagine Revit outputting this.

Apologies, you're right, I'd messed around with the file to see what Solibri would and wouldn't read, I shouldn't have tried that version or sent it through. It's working now! I will now do some testing with the file and report back any ACTUAL issues I find :)
![image](https://user-images.githubusercontent.com/69241247/93468303-aa352e80-f8e6-11ea-82e9-505e8d18355b.png)
