### ISSUE TITLE
BlenderBIM: don't hardcode collection location of Views, to allow flexibility of drawing location

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1006]
Video: https://www.dropbox.com/s/5fx1yh8yxa63pxo/2020-09-19_10-59-51.mp4?dl=0

Files: https://github.com/OpeningDesign/OD_Library/tree/9ddd1a560afd395a8af374321475610c812d49c0/BIM/BlenderBIM

Version: 0.0.200912

```
Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 2121, in execute
    bpy.ops.bim.activate_view(drawing_index=bpy.context.scene.DocProperties.drawings.find(camera.name.split('/')[1]))
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 2393, in execute
    bpy.context.view_layer.layer_collection.children['Views'].children[collection.name].hide_viewport = True
KeyError: 'bpy_prop_collection[key]: key "Views" not found'

location: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py:201



location: <unknown location>:-1

```

**Comment by Moult** [comment]
At the moment, the drawing system is a little fussy that it expects the drawing collections to be in a collection called "Views", which is at the top level in the tree. See below. Perhaps you moved it?

![image](https://user-images.githubusercontent.com/88302/93707993-36a95080-fb76-11ea-83d6-f706eee2af63.png)

**Comment by Moult** [comment]
This is now resolved since the location of views is now in the IFC project.
