### ISSUE TITLE
Is it possible to set model-offset or rotation to the geometry iterator in Python?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1047]
I tried:

```
self.settings = ifcopenshell.geom.settings()
self.settings.offset = [5.0,5.0,5.0]
```

... and got ...

```
Traceback (most recent call last):
  File "/home/dion/.config/blender/2.90/scripts/addons/blenderbim/bim/operator.py", line 130, in execute
    ifc_importer = import_ifc.IfcImporter(ifc_import_settings)
  File "/home/dion/.config/blender/2.90/scripts/addons/blenderbim/bim/import_ifc.py", line 298, in __init__
    self.settings.offset = [5.0,5.0,5.0]
  File "/home/dion/.config/blender/2.90/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 102, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, settings, name, value)
  File "/home/dion/.config/blender/2.90/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 71, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/home/dion/.config/blender/2.90/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 60, in _swig_setattr_nondynamic
    return method(self, value)
TypeError: in method 'settings_offset_set', argument 2 of type 'std::array< double,3 >'
```

**Comment by aothms** [comment]
I added a commit to wrap array by swig. Not sure what it would look like in Python...

**Comment by Moult** [comment]
Awesome! Will try out when the bot wakes up :)

**Comment by Moult** [comment]
So I tried again with a variety of numpy calls with similar error message:

```
>>> s.offset = numpy.array([[5.,5.,5.]])[0]
Traceback (most recent call last):
  File "/home/dion/drive/blender/blender-2.93/2.93/python/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/2.93/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 166, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, settings, name, value)
  File "/home/dion/.config/blender/2.93/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 71, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/home/dion/.config/blender/2.93/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 60, in _swig_setattr_nondynamic
    return method(self, value)
TypeError: in method 'settings_offset_set', argument 2 of type 'std::array< double,3 > *'
```

The reason I was looking for this feature is that often vertical construction files are incorrectly geolocated in two possible ways, sometimes mixing the two.

The first way is that they put the object placement in grid coordinates. The second way is that they put the cartesian points themselves of the representation items in grid coordinates. Sometimes, within the same file, they use the first way on some objects, and the second way on other objects. Crazy stuff. I was hoping that using this .offset feature would help, but maybe not, because if they mix the first and second ways in the same file, I need to check on an element by element basis. In any case, I've implemented an alternative case by case check which applies an offset either to the transformation matrix or to the verts themselves. So no rush to get this fixed but who knows where it might be useful in the future.

**Comment by aothms** [comment]
ok, seems we both had too high expectations of SWIG. Inclusion of the header wasn't sufficient I also needed to supply the template signatures.

You cannot pass a numpy array you need to instantiate the precise SWIG template:

```
arr = ifcopenshell.ifcopenshell_wrapper.float_array_3
arr[0], arr[1], arr[2] = (1,2,3)
```

Does it work now?

**Comment by aothms** [comment]
https://github.com/IfcOpenBot/IfcOpenShell/commit/b149f4f56de993c664e1dda7310072b6ab50cd19#comments
