### ISSUE TITLE
BlenderBIM: error during export

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1050]
This file doesn't export.
https://www.dropbox.com/s/oh7qz18g1tqtr8z/20201027-BED.blend?dl=1

Not sure what the problem is.

```
Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 107, in execute
    ifc_exporter.export(context.selected_objects)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 1350, in export
    self.ifc_parser.parse(selected_objects)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 105, in parse
    self.classification_references = self.get_classification_references()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 668, in get_classification_references
    'raw_element': self.classification_reference_maps[reference.referenced_source][reference.name]
KeyError: 'beds-Uniformat'

location: <unknown location>:-1


```

**Comment by Moult** [comment]
In prior versions, the classification tree was saved to an external file. This had some disadvantages, the primary issue being that you couldn't share just the blend file and export it on another computer.

The latest version completely revamps the way classifications are stored, now storing it within the Blend file, breaking compatibility with the older versions. In the long run, though, it's a better way to go.

So, a few ways forward:

 1. Reimport the IFC with the latest BlenderBIM Add-on version, and it should export. If it doesn't, it's a bug.
 2. Just purge the classification data from the file. If it's a lot of elements, I can help with this.
 3. If classifications are important, I can do a little hacky patch to revive this file for you, but I might need to grab a few files from you to do this.
 4. Use the older version temporarily for this file

So, where to from here?

**Comment by theoryshaw** [comment]
I just deleted that object from the project. :)
