### ISSUE TITLE
BlenderBIM: a running log of IFC import/export errors

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1052]
I spend a lot of time troubleshooting a file that has some isolated object that causes an error during IFC export.

Is it possible to develop some way to highlight the offending object in the viewer?  Would save a ton of time troubleshooting a file.

**Comment by Moult** [comment]
Hmmm... there are lots of possible reasons, and I don't really want to put catchall error statements juuuust yet given the alpha state of the add-on.

Maybe we can use this issue to keep a log of issues that you find, and I will 1) if it is a valid error, provide better reporting, 2) if it is something that we can avoid the error altogether, make it happen

**Comment by theoryshaw** [comment]
Here's one file, I'm having trouble isolating the reason
https://gitlab.com/openingdesign/223_randolph_st__atlanta/-/commit/8cbedf3a11ced55f5edba05f05d2f304664c70fa

Also, I'm having problems creating drawings. There's an error there too.  

Have been doing a lot of 'half splitting' to figure it out, but sometimes that doesn't work. :\

**Comment by theoryshaw** [comment]
You'll also notice, that those IfcSpaces are not located corrected when exported, as well.

**Comment by Moult** [comment]
Thanks - I can work with that!

**Comment by Moult** [comment]
The error in export has been fixed. Maybe we can have a screenshare to figure out how to improve a few things?

**Comment by theoryshaw** [comment]
Get the following error exporting [this](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/7728c133682bab0fd0df8adcfe1ed46ea2d197c9/Random%20Tests/Stair/Stair_03.blend) file.

```
Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 107, in execute
    ifc_exporter.export(context.selected_objects)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 1381, in export
    self.relate_objects_to_objects()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 1873, in relate_objects_to_objects
    relating_object['ifc'], related_objects)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 88, in create_entity
    e[idx] = arg
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 127, in __setitem__
    self.wrapped_data.setArgumentAsNull(idx)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1588, in setArgumentAsNull
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsNull(self, i)
RuntimeError: Attribute not set

location: <unknown location>:-1

```

**Comment by Moult** [comment]
@theoryshaw a good thing to watch out for is for any errors in the error log / console. When I run it, I see these three error lines:

```
2020-11-01 23:28:33,807    ERROR export_ifc.py 2184 The product "IfcStairFlight/Cast-In-Place Stair:Stair:152996 Run 1" could not be created: ('Attribute index out of bounds',)
2020-11-01 23:28:33,810    ERROR export_ifc.py 2184 The product "IfcStair/Cast-In-Place Stair:Stair:152996" could not be created: ('Attribute index out of bounds',)
2020-11-01 23:28:33,811    ERROR export_ifc.py 2184 The product "IfcStairFlight/Cast-In-Place Stair:Stair:152996 Run 1" could not be created: ('Attribute index out of bounds',)
```

Those lines appear prior to the error you've quoted, and will provide the hint you need to fix it. For example, it says "attribute index out of bounds" which means that those objects contain an attribute that they're not allowed to. In particular, the stair flight contains `NumberOfRiser` which is valid IFC2X3 but invalid IFC4, so it should be changed to `NumberOfRisers`, and the stair contains `ShapeType` which is valid IFC2X3 but invalid IFC4 (just remove it).

I've noticed this issue a few times now - where people import IFC2X3 and expect it to export to IFC4. This is not an unreasonable expectation, I guess... maybe I need to build an IFC2X3 to IFC4 conversion feature...

**Comment by theoryshaw** [comment]
Good to know.  Thx.

---

As you can see from [these](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/tree/ebcba308e1461603c18fa02ec0f9f481cd59946d/Random%20Tests/Stair) following test files, when I imported/exported via IFC4, it worked, but got [this](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/raw/ebcba308e1461603c18fa02ec0f9f481cd59946d/Random%20Tests/Stair/IFC2x3/Stair_04_blend.ifc_error.png) error via import/export with IFC2x3.

Probably a Revit issue.

**Comment by Moult** [comment]
Yes, that is a related issue. Basically, upon import classifications are upgraded to IFC4. Then, it can't be downgraded since there is no support for downgrading. I'll add a bug.

**Comment by Moult** [comment]
Closing, as the foundations to fix most future errors are now there. In the future with specific bug reports this can be polished over time.
