### ISSUE TITLE
Issue running ifccsv.py

### ISSUE THREAD

**Issue by tpaviot** [IfcOpenShell/IfcOpenShell#1107]
I'm testing the ifccsv.py script, using for instance:
```bash
./ifccsv.py -i ../../test/input/revit2011_wall1.ifc --export
```
However I can't get done with any of the test files.
```bash
Traceback (most recent call last):
  File "./ifccsv.py", line 182, in <module>
    results = selector.parse(ifc_file, args.query)
  File "/home/thomas/miniconda3/envs/occt750/lib/python3.7/site-packages/ifcopenshell/util/selector.py", line 119, in parse
    start = l.parse(query)
  File "/home/thomas/miniconda3/envs/occt750/lib/python3.7/site-packages/lark/lark.py", line 438, in parse
    return self.parser.parse(text, start=start)
  File "/home/thomas/miniconda3/envs/occt750/lib/python3.7/site-packages/lark/parser_frontends.py", line 215, in parse
    return self._parse(text, start)
  File "/home/thomas/miniconda3/envs/occt750/lib/python3.7/site-packages/lark/parser_frontends.py", line 58, in _parse
    return self.parser.parse(input, start, *args)
  File "/home/thomas/miniconda3/envs/occt750/lib/python3.7/site-packages/lark/parsers/earley.py", line 313, in parse
    raise UnexpectedEOF(expected_tokens)
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: 
	* LPAR
	* DOT
	* AT
	* STAR
	* HASH
	* LPAR
	* DOT
```
python 3.7, latest v0.6.0 branch, lark-parser 0.10.0 from the conda-forge channel. I'm not sure whether or not I've been using this script in the right way, maybe I'm doing something wrong ?

**Comment by Moult** [comment]
@tpaviot IFCCSV exports out a subset of rooted elements that is specified via a query syntax [documented here](https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples#IFC_Query_Syntax).

```
# Export all IfcElement classes. This by default spits out data.csv with a single column of GlobalIds
$ ./ifccsv.py -i ~/test.ifc -q ".IfcElement" --export
# Export all IfcElement classes with the Name and Description attribute and a defined csv file output
$ ./ifccsv.py -i ~/test.ifc -q ".IfcElement" -a "Name" "Description" --export -c out.csv
```

You can see its behaviour through a UI here: https://www.youtube.com/watch?v=ZeMkG6jTzAg

Hope it helps :)

**Comment by tpaviot** [comment]
Ok, great, that works!

Maybe the https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples#IFC_Query_Syntax and  https://www.youtube.com/watch?v=ZeMkG6jTzAg links could be added to the ifccsv.py help string, that would prevent future rtfm issues :)
