### ISSUE TITLE
IfcGeometricRepresentationContext raises "invalid real" 

### ISSUE THREAD

**Issue by spl1inter** [IfcOpenShell/IfcOpenShell#1139]
IfcOpenHouse.ifc line 48:
```
#41=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#39,#40);
```
raises:
```
RuntimeError: Token #39 at 2267 invalid real
```
in create_shape function, IfcOpenShell-0.5.0rc0 for python2.7 mingw64
(0.6 branch incompatible with my OCE libraries)

Any ideas for a work-around?

**Comment by Moult** [comment]
At a glance I don't spot anything wrong. On v0.6.0 branch I can view ifcopenhouse just fine.

If you're having incompatibility issues, try install the BlenderBIM Add-on (https://blenderbim.org/) it packages OCE, PythonOCC, IfcOpenShell v0.6.0 for Python 3.7. It comes with a built in Python with a python shell in the Blender UI (or you can just rip out the libs and use it with your own system's Python 3.7).

**Comment by spl1inter** [comment]
Thanks Moult but no, the whole point of the exercise was to compile the compatible branch of IfcOpenShell with the set of tools and libraries I set up mid last year and have no immediate intent to run through all of that again. I am aware of the "don't bother just use binary X" but again, that isn't the point.

Since there still seems to be commits to the 0.5 branch I was fishing around for adjustments that could possibly be made there, nothing more.

Thanks for your views Moult.

**Comment by aothms** [comment]
I checked with https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-27-master-491dc57-win64.zip (that's 0.5.0rc0) and the following script and couldn't reproduce any issue. What version of IfcOpenHouse are you using precisely? There's a lot of versions floating around and some had invalid real serializations (but not in the representation context)

```
import ifcopenshell
import ifcopenshell.geom

fn = "IfcOpenHouse_IFC2x3.ifc"
f = ifcopenshell.open(fn)
s = ifcopenshell.geom.settings()

for elem in f.by_type("IfcBuildingElement"):
    if elem.Representation:
        ifcopenshell.geom.create_shape(s, elem)

print('done')

```

**Comment by spl1inter** [comment]
aothms: Hi and thank you for addressing this :) I am using the 0.5.0rc0 tar.gz package from the release history - nothing "unusual".

Here are my results:
```
Python 2.7.15 (default, Feb 22 2019, 09:15:49)  [GCC 8.2.0 64 bit (AMD64)] on wi
n32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> import ifcopenshell.geom
>>>
>>> fn = "IfcOpenHouse.ifc"
>>> f = ifcopenshell.open(fn)
>>> s = ifcopenshell.geom.settings()
>>>
>>> for elem in f.by_type("IfcBuildingElement"):
...     if elem.Representation:
...         ifcopenshell.geom.create_shape(s, elem)
...
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "D:\MSYS2\mingw64\lib\python2.7\site-packages/ifcopenshell/geom/main.py",
 line 168, in create_shape
    repr.wrapped_data if repr is not None else None
  File "D:\MSYS2\mingw64\lib\python2.7\site-packages/ifcopenshell/ifcopenshell_w
rapper.py", line 478, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation
)
RuntimeError: Token #39 at 2267 invalid real
>>> print('done')
```

Also:
```
>>> ifcopenshell.version
'0.5.0-rc1'
```

Likewise, MinGW has a few different repos - I am using the semi-official MSYS2 MinGW64 from Christoph Reiter, because of its vastly superior release packaging and management.

I am hoping for some guidance to at least find the root in the different results.

**Comment by aothms** [comment]
Can you sure your copy of `"IfcOpenHouse.ifc"` just to be sure.

Come to think of it, there is something specific to mingw in the code base regarding parsing reals: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcParse.cpp#L67 but I can't figure out what's happening here.

What's the result of:

```
for rc in f.by_type("IfcGeometricRepresentationContext"):
    for i, val in enumerate(rc):
        print i, val
```

**Comment by spl1inter** [comment]
yup. fyi github is even raising hell with ungoogled zip uploads (in someone's pocket much??), so rename to ifc:

[IfcOpenHouse.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/5629402/IfcOpenHouse.txt)

results as requested:

```
0 None
1 Model
2 3
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "D:\MSYS2\mingw64\lib\python2.7\site-packages/ifcopenshell/entity_instanc
e.py", line 108, in __getitem__
    return entity_instance.wrap_value(self.wrapped_data.get_argument(key))
  File "D:\MSYS2\mingw64\lib\python2.7\site-packages/ifcopenshell/ifcopenshell_w
rapper.py", line 1944, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Token #39 at 2267 invalid real
```

**Comment by spl1inter** [comment]
Thanks for the hint, started me thinking. Seems as suspected the MINGW support is for a different (maybe older?) distribution. This update:

```
#ifdef __MINGW32__
#include <locale>
#include <sstream>
void init_locale() {}

#ifdef __MINGW64__
using locale_t = _locale_t;
static locale_t locale = (locale_t)0;

#define  strtod_l  _strtod_l
#else
typedef void* locale_t;

double strtod_l(const char* start, char** end, locale_t loc) {
  double d;
  std::stringstream ss;
  ss.imbue(std::locale::classic());
  ss << start;
  ss >> d;
  size_t nread = ss.tellg();
  *end = const_cast<char*>(start) + nread;
  return d;
}
#endif
#else
...
```
Creates this result:

![mingw64-ifcopenshell](https://user-images.githubusercontent.com/41893923/100942697-ed02bc00-354f-11eb-9053-0c8c35c1ba1a.png)

**Comment by aothms** [comment]
Thanks @spl1inter. But in your code on MINGW64 the `init_locale()` is not defined meaningfully, shouldn't the static locale get assigned the C locale?

How about this:

```
#if defined(_MSC_VER)

static _locale_t locale = (_locale_t) 0;
void init_locale() {
	if (locale == (_locale_t) 0) {
		locale = _create_locale(LC_NUMERIC, "C");
	}
}

#else

#ifdef __APPLE__
#include <xlocale.h>
#endif
#include <locale.h>

#ifdef __MINGW64__
using locale_t = _locale_t;
#endif

static locale_t locale = (locale_t)0;
void init_locale() {
	if (locale == (locale_t)0) {
		locale = newlocale(LC_NUMERIC_MASK, "C", (locale_t)0);
	}
}

#endif
```

If it works it'd be great if you can wrap this in a Pull Request :)

**Comment by spl1inter** [comment]
>  in your code on MINGW64 the init_locale() is not defined meaningfully
Because that's how it was originally.

The larger problem with this idea would be total abandoment for legacy MinGW32. If that's your intent fine, but If not Ill post a new version with a proper locale def.

**Comment by aothms** [comment]
> > in your code on MINGW64 the init_locale() is not defined meaningfully
> 
> Because that's how it was originally.

Yes, but because there was a C++ fallback using stringstream where the locale was imbued. But in your case the non-initialized locale is now fed to strtod_l().

> But the larger problem with this idea would be total abandoment for legacy MinGW32. If that's your intent fine, but If not Ill post a new version with a proper locale def.

Yes, that's true. But to me that's still an improvement over the current version where a recent MinGW64 cannot parse a simple file. Sure, if we can test legacy MinGW32 (`#if defined(__MINGW32__) && !defined(__MINGW64__)`?) and have a working code path for it that would be even better, but I was implicitly already making the trade off with invested time.

>  (0.6 branch incompatible with my OCE libraries)

This might also need to be something to fix btw. While most of the developers don't test with OCE anymore (specifically OCCT below 7) we still try to remain compatible. See for example the PR https://github.com/IfcOpenShell/IfcOpenShell/pull/1090 25 days ago. You might want to double check the current v0.6.0 head.

**Comment by spl1inter** [comment]
> Yes, but because there was a C++ fallback using stringstream where the locale was imbued.

OK I see what's going on here. But now there are some new issues - formostly is the modest state of affairs concerning MinGW64 [posix locale support](https://pubs.opengroup.org/onlinepubs/9699919799/functions/newlocale.html). There is _still_ no newlocale() and probably never will be. MinGW is for Windows, but people keep assuming posix stuff on it..

The truth is any posix API locale functionality will only be simulated at best, so I'm not sure what you were actually hoping to achieve. 

> if we can test legacy MinGW32 (#if defined(__MINGW32__) && !defined(__MINGW64__)?) 

You dont have to, just keep the existing mingw32 support code and section off a new subcode for MINGW64. And remember MINGW64 will declare \_\_MINGW32\_\_ _anyway_ so I was thinking more of something like this:

```
#ifdef __MINGW32__
#include <locale>
#include <sstream>

#ifdef __MINGW64__
/* Borrowed from suppressed statement in libintl.h keep for ref */
using locale_t = _locale_t;
static locale_t locale = (locale_t)0;
#define  strtod_l  _strtod_l

/* credit to the VLC team for this kludge */
#define  LC_NUMERIC_MASK   0
static inline locale_t newlocale(int mask, const char * locale, locale_t base)
{
  (void)mask; (void)locale; (void)base;
  return NULL;
}

void init_locale() {
	if (locale == (locale_t)0) {
    locale = newlocale(LC_NUMERIC_MASK, "C", (locale_t)0);
	}
}
#else
#warning "32-bit MinGW legacy support untested for recent versions. But you can change that :)"
typedef void* locale_t;
void init_locale() {}

double strtod_l(const char* start, char** end, locale_t loc) {
	double d;
	std::stringstream ss;
	ss.imbue(std::locale::classic());
	ss << start;
	ss >> d;
	size_t nread = ss.tellg();
	*end = const_cast<char*>(start) + nread;
	return d;
}
#endif
#else

#ifdef __APPLE__
...
```

What do you think?

**Comment by aothms** [comment]
The question remains then how strtod_l() behaves on MINGW when the *end user* [so not the user that is compiling], behaves when he's on a locale that has different numeric behaviour. The issue this is trying to fix is that e.g. a German user can parse  `1.23` where it's native locale would write `1,23`. I.e locales that use a comma as decimal point. I mean it could well be that MINGW always uses the C locale. I really don't know and can't seem to find any resources on this. 

Essentially we need this us_strtod (following your VLC hint) https://www.videolan.org/developers/vlc/doc/doxygen/html/group__c__locale.html#ga6687100932ffbd6d7fd84b74de30c459 http://git.videolan.org/gitweb.cgi/vlc.git/?p=vlc.git;a=blob;f=src/text/charset.c;h=2e7f44a3944cd8c30e9489b690f7386d54a8efc9;hb=0b00646d20a3401348b8673b7ec896cd7203a05b#l384

**Comment by spl1inter** [comment]
> The issue this is trying to fix is that e.g. a German user can parse 1.23 where it's native locale would write 1,23. I.e locales that use a comma as decimal point.

Well that changes things. We need to chuck the shims and stubs and find a real function. You're right - MINGW documentation is slim to none about these locale portability issues - so I stopped making this a MINGW problem and started making it an MSDN problem. Here's what I came up with (tested working but I lack the Euro system to check it):

```
#ifdef __MINGW32__
#include <locale>
#include <sstream>

#ifdef __MINGW64__
static _locale_t locale = (_locale_t)0;

void init_locale() {
	if (locale == (_locale_t)0) {
                  _locale_t locale = _create_locale(LC_NUMERIC, "C");
	}
}
#else
#warning "32-bit MinGW legacy support untested for recent versions. But you can change that :)"
typedef void* locale_t;
void init_locale() {}

double strtod_l(const char* start, char** end, locale_t loc) {
	double d;
	std::stringstream ss;
	ss.imbue(std::locale::classic());
	ss << start;
	ss >> d;
	size_t nread = ss.tellg();
	*end = const_cast<char*>(start) + nread;
	return d;
}
#endif
#else

#ifdef __APPLE__
...
```

And L#400 or so:
```
#if defined (_MSC_VER) || defined (__MINGW64__) /* also MINGW32? */
  double result = _strtod_l(pStart, &pEnd, locale);
#else
  double result = strtod_l(pStart, &pEnd, locale);
#endif
```

Functionily should be per MSDN.

**Comment by aothms** [comment]
> tested working but I lack the Euro system to check it

Looks ok to me :) Can you send in a Pull Request?


Re:

```
#if defined (_MSC_VER) || defined (__MINGW64__) /* also MINGW32? */
  double result = _strtod_l(pStart, &pEnd, locale);
#else
  double result = strtod_l(pStart, &pEnd, locale);
#endif
```

Maybe we should just do a 

`#define strtod_l _strtod_l` in case of `_MSC_VER` so that we can skip the later `#if`?

Thanks for you continued effort on this :)

**Comment by BIMvoice** [comment]
Verified fixed on the current build (0.8.5-1c5b825): a file containing the exact reported line `#41=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#39,#40);` parses without error and `context.Precision` reads back `1e-05` correctly — no `invalid real` RuntimeError. The old tokenizer issue is gone with the parser rewrite. Safe to close.

**Comment by BIMvoice** [comment]
Closing — reproduced the exact entities from this report (`IFCAXIS2PLACEMENT3D`/`IFCGEOMETRICREPRESENTATIONCONTEXT` with the same nested references) against current `ifcopenshell` 0.8.5: parses cleanly, no "invalid real" error, all attributes resolve correctly. This was a tokenizer issue in the pre-0.6 STEP parser (`0.5.0rc0`), long since rewritten. Reopen with a file if you're still seeing this on a current build.

This comment was written with AI assistance.
