### ISSUE TITLE
'IfcElementQuantity' has no attribute 'HasProperties'

### ISSUE THREAD

**Issue by spl1inter** [IfcOpenShell/IfcOpenShell#1145]
When running the viewer script for 'print properties of current selection' I get:

```
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "D:\MSYS2\mingw64\lib\python2.7\site-packages/ifcopenshell/entity_instance.py", line 68, in __getattr__
    "entity instance of type '%s' has no attribute '%s'" % (self.wrapped_data.is_a(), name))
AttributeError: entity instance of type 'IfcElementQuantity' has no attribute 'HasProperties'
```

What does it mean? The other miniscript seems to work fine.
Still 0.5rc1 MinGW64 python2.7 ..

**Comment by Moult** [comment]
This looks like an error in the script. Can you post the script?

The `IfcElementQuantity` class indeed has no attribute `HasProperties`. Instead, it should check the `Quantities` attribute.

**Comment by spl1inter** [comment]
Sure, but its unchanged from source..

```
###########################################################################
# A simple script that iterates over all IfcPropertySets of the currently #
# selected object and prints them to the console                          #
###########################################################################

# check if something is selected
if selection:
    #get the IfcProduct that is stored in the global variable 'selection'
    obj = selection
    for relDefinesByProperties in obj.IsDefinedBy:
         print("[{0}]".format(relDefinesByProperties.RelatingPropertyDefinition.Name))
         for prop in relDefinesByProperties.RelatingPropertyDefinition.HasProperties:
             print ("{:<20} :{}".format(prop.Name,prop.NominalValue.wrappedValue))
         print ("\n")
```

Not sure if it's related to the same sort of coding, I also notice that if I click on anything in the Types tree panel of the viewer, the app crashes without an error trail (hovering works OK).

**Comment by Moult** [comment]
@spl1inter hope that helps fix the script issue. By the way, there is a util module which makes extracting data much easier. Like `ifcopenshell.util.element.get_psets(element)` - in one line you get a nested dictionary of properties.

Not sure how much I can help with the crash, I'm not too familiar with the geom viewer. Might be one for @aothms

**Comment by spl1inter** [comment]
Merging your change to 0.5rc0 fixes that error but a similar one arose when checking around AC-11-Smiley-West-04-07-2007.ifc:

```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "D:\MSYS2\mingw64\lib\python2.7\site-packages/ifcopenshell/entity_instance.py", line 68, in __getattr__
    "entity instance of type '%s' has no attribute '%s'" % (self.wrapped_data.is_a(), name))
AttributeError: entity instance of type 'IfcRelDefinesByType' has no attribute 'RelatingPropertyDefinition'
```
Also, if you are keeping portability to Python2 app.py#L18 needs to be
```
except ImportError:  # python 2
```

**Comment by Moult** [comment]
@spl1inter what code are you running that triggers that error? These two lines in that commit should've avoided that error: https://github.com/IfcOpenShell/IfcOpenShell/commit/06685f9768da6a4bb5c8ddbc6d3e4ea2e6703b7b#diff-946c14ab819a0a3704657df261bed20b235d92fd7994a919a1084fc380483ea4R161-R162

**Comment by spl1inter** [comment]
Just the latest 0.5 release: 0.5rc0

**Comment by Moult** [comment]
@spl1inter i mean what is the Python code that you are running that triggers that error?

**Comment by spl1inter** [comment]
Sorry I thought it was clear, really nothing complicated at all - I was re-testing your updated 'print properties of current selection' while selecting windows on the pythoncc demo model AC-11-Smiley-West-04-07-2007.ifc just checking your script update.

**Comment by Moult** [comment]
Can you double check the code is what I've committed? Paste it here for a double confirmation?

**Comment by spl1inter** [comment]
Sure. When pasting it into 0.5rc0 I looked like this:
```
            config.set("snippets", "print properties of current selection", self.config_encode("""
###########################################################################
# A simple script that iterates over all IfcPropertySets of the currently #
# selected object and prints them to the console                          #
###########################################################################

# check if something is selected
if selection:
    #get the IfcProduct that is stored in the global variable 'selection'
    obj = selection
    for relDefinesByProperties in obj.IsDefinedBy:
        if not relDefinesByProperties.is_a("IfcRelDefinesByProperties"):
            continue
         print("[{0}]".format(relDefinesByProperties.RelatingPropertyDefinition.Name))
         if relDefinesByProperties.RelatingPropertyDefinition.is_a("IfcPropertySet"):
             for prop in relDefinesByProperties.RelatingPropertyDefinition.HasProperties:
                 print ("{:<20} :{}".format(prop.Name,prop.NominalValue.wrappedValue))
         print ("\\n")
""".lstrip()))
```

**Comment by aothms** [comment]
Have a look at the 0.6 version of the app. It appears to be much more complete wrt IFC schema https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/geom/app.py#L385

**Comment by spl1inter** [comment]
> Have a look at the 0.6 version of the app.

Do we really want to go down this road? I don't have time to update my dependencies and the lion's share of my work is still in python2.7. I had the impression that older dependency support was the reason for ongoing development of the older branches since 0.5 was much easier for me to compile. Wouldn't it be better for you to simply patch 0.5 to final release state and move on? I'm just wanting to be sure before we start committing a lot of time backporting 0.6.

About backward comp, how about this IFC 4 support will it still be fully 2x3 read-compatible or is this a binary decision with hit-and-miss backward format support, since there are schema differences?

**Comment by aothms** [comment]
> About backward comp, how about this IFC 4 support will it still be fully 2x3 read-compatible or is this a binary decision with hit-and-miss backward format support, since there are schema differences?

This is the core reason why the 0.6 branch exists. In 0.5 the schema can only be specified at compile time (which was fine maybe 5 years ago when industry was 99% IFC2X3). Since industry transitioning to IFC4 was so slow, we had to simultaneously begin effort on runtime schema support in the 0.6 branch.  And that is where we are, given that most of our users are on 0.6, that is where the energy goes.

> Do we really want to go down this road? I don't have time to update my dependencies and the lion's share of my work is still in python2.7.

You can probably backport that part of the app to 0.5. 

> I had the impression that older dependency support was the reason for ongoing development of the older branches since 0.5 was much easier for me to compile.

Not really. 0.5 has just less active development and therefore less chances to introduce incompatibilities. Given that the lion's share of the users and developers are quickly adopting newer versions of OCCT as they are released. 7.4 had a bit more issues, but 7.5 is excellent for example. 6.9 does not have n-ary boolean operations and no explicit tolerance management for boolean operations which makes it just incredibly less reliable and performant. Event though OCCT 7 is radically different from 6, the OCCT team has done an amazing job at keeping backwards compatibility. So incompatibilities between IfcOpenShell 0.6 and OCCT 6 are almost always trivial and are typically identified and fixed by the community once in a while (as I mentioned in another thread).

**Comment by Moult** [comment]
Closing issue due to inactivity, and this has been working for a long time on the latest version.
