### ISSUE TITLE
Bug in decorator draw

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1159]
Ping @qwiglydee 

I noticed this in the console. I haven't looked at the code to see what triggers it yet.

```
Traceback (most recent call last):
  File "/home/dion/.config/blender/2.91/scripts/addons/blenderbim/bim/decoration.py", line 150, in __call__
    self.draw_label(segm)
  File "/home/dion/.config/blender/2.91/scripts/addons/blenderbim/bim/decoration.py", line 179, in draw_label
    ang = -Vector((1, 0)).angle_signed(p1 - p0)
ValueError: Vector.angle_signed(other): zero length vectors have no valid angle
```

**Comment by qwiglydee** [comment]
That must be a result of putting strictly vertical dimensions along z. Or maybe actually zero segment because of snapping.
I didn't expect that to happen 🙂
