### ISSUE TITLE
BlenderBIM: export error

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1189]
[This](https://www.dropbox.com/s/174zodhse0kzdcd/20201220.blend?dl=0) file provides the following error upon export.

Blender 2.90 and BB 0.0.201207

```
Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 110, in execute
    ifc_exporter.export(context.selected_objects)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 1351, in export
    self.ifc_parser.parse(selected_objects)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 124, in parse
    self.get_products()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 192, in get_products
    self.add_product(self.get_product(product))
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 422, in get_product
    self.get_product_psets_qtos(product, obj, is_qto=True)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 453, in get_product_psets_qtos
    self.add_automatic_qtos(product["class"], obj)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 478, in add_automatic_qtos
    qto_names = self.get_applicable_qtos(ifc_class)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 503, in get_applicable_qtos
    for ifc_class, qto_names in schema.ifc.applicable_qtos.items():
AttributeError: 'IfcSchema' object has no attribute 'applicable_qtos'

location: <unknown location>:-1


```

**Comment by theoryshaw** [comment]
fyi, i noticed it had the same error with 201115, but it exported with 201025.

**Comment by theoryshaw** [comment]
just found out, if I unchecked that, it exported.

![image](https://user-images.githubusercontent.com/507113/103441229-1d527e80-4c12-11eb-86cc-8b8bcc888107.png)

**Comment by Moult** [comment]
Closing, as this bug should be fixed in the new system. See #1222.
