### ISSUE TITLE
BlenderBIM: export error

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1230]
[Wall_Profile_3.blend](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/tree/ebf1d7bf6276f884b564538ef3f334ccc89a2010/Random%20Tests/Wall_Profile/from_Revit) gives the following error upon export.

2.90 - 201207-win.zip

```
Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 110, in execute
    ifc_exporter.export(context.selected_objects)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 1377, in export
    self.create_styled_items()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 2023, in create_styled_items
    self.process_styled_item(styled_item)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 2044, in process_styled_item
    i = product["raw"].data.BIMMeshProperties.ifc_item_ids.get(str(original_id)).slot_index
AttributeError: 'NoneType' object has no attribute 'slot_index'

location: <unknown location>:-1

```

![image](https://user-images.githubusercontent.com/507113/103499360-63276680-4e0d-11eb-904e-0cd3b33cccfd.png)

**Comment by Moult** [comment]
Sorry I'm not really spending much time looking at these bugs right now since I'm busy refactoring for partial editing for the next release. In the next release, there actually will not be an export IFC at all... likely it'll fix these bugs in the process (but also introduce new ones, since it's effectively a huge rewrite). There will be a way to migrate from the old version to the new one, though.

**Comment by theoryshaw** [comment]
all good, no worries!

**Comment by Moult** [comment]
Closing, as the system which is related to this bug has been removed so it is no longer relevant. See #1222.
