### ISSUE TITLE
IfcOpenShell cannot remove element

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1246]
I'm not quite I fully understand the underlying assumptions behind a call to file.remove(). I've been trying to create some minimal examples of more complex scenarios where I'm encountering crashes, but I'm finding that the minimal examples don't quite work either.

Here's one example:

```
import ifcopenshell
f = ifcopenshell.file()
e = f.createIfcWall()
f.remove(e)
```

Results in:

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    f.remove(e)
  File "/usr/lib/python3.7/site-packages/ifcopenshell/file.py", line 177, in remove
    return self.wrapped_data.remove(inst.wrapped_data)
  File "/usr/lib/python3.7/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 1383, in remove
    return _ifcopenshell_wrapper.file_remove(self, entity)
RuntimeError: Invalid cast
```

If I have a GlobalId, then I don't get the error, but I do get a hang in my terminal which I have to force kill:

```
import ifcopenshell
f = ifcopenshell.file()
e = f.createIfcWall(ifcopenshell.guid.new())
f.remove(e)
```

**Comment by aothms** [comment]
I committed a quick fix for this, but the underlying problem is severe and also related to #1224.

The maps are just not always updated properly on attribute changes. See for example below. Let's keep this issue open to address tht.

```
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> e = f.createIfcWall(ifcopenshell.guid.new())
>>> f.by_guid(e.GlobalId)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tkrij\Miniconda3\envs\py35\lib\site-packages\ifcopenshell\file.py", line 121, in by_guid
    return self[guid]
  File "C:\Users\tkrij\Miniconda3\envs\py35\lib\site-packages\ifcopenshell\file.py", line 101, in __getitem__
    return entity_instance(self.wrapped_data.by_guid(str(key)))
  File "C:\Users\tkrij\Miniconda3\envs\py35\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 1539, in by_guid
    return _ifcopenshell_wrapper.file_by_guid(self, guid)
RuntimeError: Instance with GlobalId '1b6gm_UuvDE9lQfRnoiujg' not found
```

**Comment by Moult** [comment]
Just hit another variation of this bug:

```
import ifcopenshell
f = ifcopenshell.open("/home/dion/Downloads/JudgesReception.ifc")
opening = f.by_id(70332)
rel_fill = opening.HasFillings[0]
filling = rel_fill.RelatedBuildingElement
f.remove(rel_fill)
new_fill = f.create_entity("IfcRelFillsElement", **{
    "GlobalId": ifcopenshell.guid.new(),
    "RelatingOpeningElement": opening,
    "RelatedBuildingElement": filling
})
f.remove(new_fill)
```

**Comment by Moult** [comment]
Closing, as no longer segfaults! Thanks @aothms !
