### ISSUE TITLE
One importer import certain IFC, other does not

### ISSUE THREAD

**Issue by Rokorps** [IfcOpenShell/IfcOpenShell#1250]
Hello,
When I try to import IFC file of fascades I get this error: 
Python: Traceback (most recent call last):
  File "/home/rokorps/.config/blender/2.91/scripts/addons/blenderbim/bim/operator.py", line 135, in execute
    ifc_importer.execute()
  File "/home/rokorps/.config/blender/2.91/scripts/addons/blenderbim/bim/import_ifc.py", line 421, in execute
    self.create_spatial_hierarchy()
  File "/home/rokorps/.config/blender/2.91/scripts/addons/blenderbim/bim/import_ifc.py", line 1751, in create_spatial_hierarchy
    self.add_related_objects(self.project["blender"], rel_aggregate.RelatedObjects)
  File "/home/rokorps/.config/blender/2.91/scripts/addons/blenderbim/bim/import_ifc.py", line 1765, in add_related_objects
    obj = self.create_product(element)
  File "/home/rokorps/.config/blender/2.91/scripts/addons/blenderbim/bim/import_ifc.py", line 973, in create_product
    self.add_product_definitions(element, obj)
  File "/home/rokorps/.config/blender/2.91/scripts/addons/blenderbim/bim/import_ifc.py", line 1428, in add_product_definitions
    self.add_qto(definition.RelatingPropertyDefinition, obj)
  File "/home/rokorps/.config/blender/2.91/scripts/addons/blenderbim/bim/import_ifc.py", line 1471, in add_qto
    for prop in qto.Quantities:
  File "/home/rokorps/.config/blender/2.91/scripts/addons/ifcopenshell/entity_instance.py", line 61, in __getattr__
    self.wrapped_data.get_argument(self.wrapped_data.get_argument_index(name))
  File "/home/rokorps/.config/blender/2.91/scripts/addons/ifcopenshell/ifcopenshell_wrapper.py", line 1650, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Instance #24 not found

location: <unknown location>:-1
But when I try to import with other IFC importer, It works

IFC imports mostly glassly IFC parts

Red Marked importer does not import
Green Marked imports fine
![Screenshot from 2021-01-08 13-28-43](https://user-images.githubusercontent.com/18393730/104012057-d50a0200-51b7-11eb-8eb7-14bbad8231f4.png)

**Comment by Moult** [comment]
It looks as though you have both IfcBlender (from the ifcopenshell.org) website installed as well as the BlenderBIM Add-on. The latter processes a lot more data during import, and hence more chance of problems occurring. It looks as though it's stumbling on some quantities, and possible that you may have an invalid IFC file. Can you attach your IFC file here or share it? If it is private, send to dion@thinkmoult.com

**Comment by Moult** [comment]
Bump? Will close after 20 days have passed.

**Comment by Moult** [comment]
Closing due to lack of response.

**Comment by Moult** [comment]
Reopened as I just received test files from @Rokorps .

The files were exported by Dassault 3DEXPERIENCE Platform3DEXPERIENCE R2021x HotFix 4.5 IFC2X3.

They contain invalid IFC data - such as missing entities. This is quite a fundamental issue with the IFC and not something that makes sense to workaround. Hopefully Dasasult can help fix their software :)
