### ISSUE TITLE
New version v0.0.210131 error cannot install

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#1282]
Cannot enable newest Blenderbim version v0.0.210131 on Blender 2.91.2

Can load latest Blemederbim v0.0.210131 to blender but when activating/ enabling
it gives this error: 

AttributeError: module 'parse' has no attribute 'Parser'

**Comment by theoryshaw** [comment]
I get the following error when I try to enable the plugin...

blender28-bim-210131-win
2.90

I'm able, however, to enable it with 2.91.

```

Traceback (most recent call last):
  File "C:\Program Files\blender-2.90.1-windows64\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\__init__.py", line 23, in <module>
    from .bim import *
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\__init__.py", line 47, in <module>
    modules[name] = importlib.import_module(f"blenderbim.bim.module.{name}")
  File "C:\Program Files\blender-2.90.1-windows64\2.90\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\module\bimtester\__init__.py", line 2, in <module>
    from . import ui, prop, operator
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\module\bimtester\operator.py", line 5, in <module>
    import bimtester.reports
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\bimtester\reports.py", line 7, in <module>
    from .features.steps.utils import switch_locale
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\bimtester\features\steps\utils.py", line 3, in <module>
    import ifcopenshell.express
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\express\__init__.py", line 14, in <module>
    import express_parser
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\express\express_parser.py", line 1
    Read prefs: C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.90\config\userpref.blend
             ^
SyntaxError: invalid syntax


```

**Comment by Moult** [comment]
@Plae-Blue-Dot  this user had the same issue as you, and it was fixed by clearing their add-ons folder. Maybe if you had an old version installed previously, it would've triggered the same bug. See here: https://blenderartists.org/t/blenderbim-openbim-authoring-with-blender/1192437/255?u=noidtluom

**Comment by Moult** [comment]
@theoryshaw that commit that closed this issue addresses your bug.

**Comment by theoryshaw** [comment]
https://blenderbim.org/builds/blender28-bim-210203-win.zip seemed to work for me.

**Comment by matthijskooijman** [comment]
I'm also running into this, but it seems that the latest build (linked above) is only available for Windows, not Linux?
