### ISSUE TITLE
BlenderBIM error "Unexpected end-of-input" when trying to export to CSV

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [IfcOpenShell/IfcOpenShell#1292]
Dear community

I am new to all of this but very enthusiastic about the  open source BIM tool landscape. I imported an IFC into Blender with the BelenderBIM add-on and I get this error when I try to export to CSV: (I tried with 5 different IFC files and all have the same result):

Python: Traceback (most recent call last):
  File "/Users/markus/Library/Application Support/Blender/2.91/scripts/addons/blenderbim/bim/module/csv/operator.py", line 53, in execute
    results = selector.parse(ifc_file, props.ifc_selector)
  File "/Users/markus/Library/Application Support/Blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/selector.py", line 119, in parse
    start = l.parse(query)
  File "/Users/markus/Library/Application Support/Blender/2.91/scripts/addons/blenderbim/libs/site/packages/lark/lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "/Users/markus/Library/Application Support/Blender/2.91/scripts/addons/blenderbim/libs/site/packages/lark/parser_frontends.py", line 194, in parse
    return self._parse(text, start)
  File "/Users/markus/Library/Application Support/Blender/2.91/scripts/addons/blenderbim/libs/site/packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/Users/markus/Library/Application Support/Blender/2.91/scripts/addons/blenderbim/libs/site/packages/lark/parsers/earley.py", line 310, in parse
    raise UnexpectedEOF(expected_tokens)
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: 
	* LPAR
	* LPAR
	* HASH
	* DOT
	* AT
	* STAR
	* DOT

location: <unknown location>:-1

Using Blender 2.91 on MacOS 11.1. Any ideas?

Thanks!

**Comment by Moult** [comment]
@MarkusSteinbrecher g'day! It sounds like your filter query is invalid. Can you show me what query you are using?

If you are unsure how the query should look, this may give you some hints: https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples#IFC_Query_Syntax

Hope it helps! If you still can't solve it, please explain in detail what steps you are taking and I can try to help!

**Comment by MarkusSteinbrecher** [comment]
@Moult good day to you too and thank you very much for this quick response, amazing! I know what I did wrong know and apologize for bothering you with this rookie mistake! Thank you!
