### ISSUE TITLE
Using tmpdir prevents behave to run when multiple drives on Windows

### ISSUE THREAD

**Issue by rbertucat** [IfcOpenShell/IfcOpenShell#1294]
When an user runs BIMTester on another drive, e.g. D: and the temporary directory gets created under C:, behave will fail with the following exception.

Solution would be to make using temporary directory an option.

```
Exception ValueError: path is on mount 'C:', start on mount 'D:'
Traceback (most recent call last):
  File ".\cli.py", line 24, in <module>
    report_json = bimtester.run.TestRunner(args["ifc"], schema=args["schema"] or None).run(args)
  File "D:\IfcOpenShell\src\ifcbimtester\bimtester\run.py", line 45, in run
    behave_main(self.get_behave_args(args, features_path, report_json))
  File "D:\Python\Python38\lib\site-packages\behave\__main__.py", line 183, in main
    return run_behave(config)
  File "D:\Python\Python38\lib\site-packages\behave\__main__.py", line 127, in run_behave
    failed = runner.run()
  File "D:\Python\Python38\lib\site-packages\behave\runner.py", line 804, in run
    return self.run_with_paths()
  File "D:\Python\Python38\lib\site-packages\behave\runner.py", line 808, in run_with_paths
    self.load_hooks()
  File "D:\Python\Python38\lib\site-packages\behave\runner.py", line 784, in load_hooks
    exec_file(hooks_path, self.hooks)
  File "D:\Python\Python38\lib\site-packages\behave\runner_util.py", line 384, in exec_file
    filename2 = os.path.relpath(filename, os.getcwd())
  File "D:\Python\Python38\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'D:'
```

**Comment by Moult** [comment]
Ah I didn't expect this. I thought using a temp dir would solve the portability issue. I'm hesitant to make it a user option, that sounds more like a workaround than a fix - the user should expect it to "just work". I've opened a bug upstream as it sounds more like an upstream issue. If it is not fixed upstream, we can implement a workaround in BIMTester, but I'd very much prefer for it to not be a user option.

**Comment by Moult** [comment]
Let's make a call that if https://github.com/behave/behave/pull/903 isn't merged within 20 days, we swap out the Makefile to pull in @rbertucat 's fork of behave instead?

**Comment by Moult** [comment]
I ended up using patches instead of switching to your fork, as the pypi distribution is quite significantly different from the git master and I didn't want to ruffle feathers :)
