### ISSUE TITLE
Assigning IFC class fails after removing all the IFC people

### ISSUE THREAD

**Issue by plaes** [IfcOpenShell/IfcOpenShell#1312]
I'm getting following tracebacks when removing the default "Hari Seldon" user (probably stupid thing to do) and then trying to "Assign IFC class" to an object:

```
WARN (bpy.rna): /builddir/build/BUILD/blender-2.91.0/source/blender/python/intern/bpy_rna.c:1487 pyrna_enum_to_py: current value '0' matches no enum in 'BIMOwnerProperties', '', 'user_person'
Python: Traceback (most recent call last):
  File "~/.config/blender/2.91/scripts/addons/blenderbim/bim/module/root/operator.py", line 96, in execute
    self.assign_class(context, obj)
  File "~/.config/blender/2.91/scripts/addons/blenderbim/bim/module/root/operator.py", line 102, in assign_class
    product = create_product.Usecase(
  File "~/.config/blender/2.91/scripts/addons/blenderbim/bim/module/root/create_product.py", line 19, in execute
    "OwnerHistory": create_owner_history()
  File "~/.config/blender/2.91/scripts/addons/blenderbim/bim/module/owner/api.py", line 33, in create_owner_history
    "person": file.by_id(int(bpy.context.scene.BIMOwnerProperties.user_person)),
ValueError: invalid literal for int() with base 10: ''
```

```
Python: Traceback (most recent call last):
  File "~/.config/blender/2.91/scripts/addons/blenderbim/bim/module/void/ui.py", line 22, in draw
    Data.load(props.ifc_definition_id)
  File "~/.config/blender/2.91/scripts/addons/blenderbim/bim/module/void/data.py", line 17, in load
    product = file.by_id(product_id)
  File "~/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 111, in by_id
    return self[id]
  File "~/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 99, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key))
  File "~/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 1445, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #0 not found

location: <unknown location>:-1
```

**Comment by Moult** [comment]
On IFC2X3, this is not a bug, as people are required. I would instead encouraging editing Dr. Hari Seldon to your own name :)

In IFC4, this is indeed a bug.

A heads up that I am extremely busy this week and do not have time to address these bugs immediately, but thank you so much for your report and I will certainly fix them!
