### ISSUE TITLE
Box representations are not supported in IfcOpenShell

### ISSUE THREAD

**Issue by ecke101** [IfcOpenShell/IfcOpenShell#1343]
When I click this button, I get this error.

```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\erik\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 174, in execute
    self.pull_mesh_from_ifc()
  File "C:\Users\erik\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 191, in pull_mesh_from_ifc
    shape = ifcopenshell.geom.create_shape(settings, self.file.by_id(self.ifc_definition_id))
  File "C:\Users\erik\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 193, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
  File "C:\Users\erik\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 634, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process representation item

location: <unknown location>:-1
```

![bild](https://user-images.githubusercontent.com/249736/109205323-b92de000-77a6-11eb-89eb-9f61f72292f9.png)

**Comment by Moult** [comment]
Known issue that Box representations are not supported in IfcOpenShell. See #85. Keeping this bug open as #85 wasn't exactly about box representations.

**Comment by Moult** [comment]
Also ping @aothms

**Comment by Moult** [comment]
Closing as fixed.
