### ISSUE TITLE
BlenderBIM - Geometry not exporting

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#1361]
Hi, I'm getting the following error when I try to update spatial container or update mesh representation, seems linked to the sequence of adding a class and moving to container.

Python: Traceback (most recent call last):
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\classification\ui.py", line 84, in draw
    Data.load(self.oprops.ifc_definition_id)
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\classification\data.py", line 31, in load
    return cls.load_product_classifications(product_id)
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\classification\data.py", line 38, in load_product_classifications
    product = cls._file.by_id(product_id)
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 111, in by_id
    return self[id]
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 99, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key))
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1491, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #83038 not found

location: <unknown location>:-1

**Comment by ChubbyQuark** [comment]
Error update below: -

Python: Traceback (most recent call last):
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\model\pie.py", line 105, in execute
    relating_structure=spatial_obj.BIMObjectProperties.ifc_definition_id, related_element=obj.name
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\spatial\operator.py", line 30, in execute
    "product": self.file.by_id(oprops.ifc_definition_id),
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 111, in by_id
    return self[id]
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 99, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key))
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1491, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #86953 not found

location: C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\ops.py:132



location: <unknown location>:-1

**Comment by ChubbyQuark** [comment]
[Model_Shell_Test.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6098038/Model_Shell_Test.zip)

**Comment by Moult** [comment]
You've only included the Blend file - I need the IFC too to debug this.

**Comment by ChubbyQuark** [comment]
For info, this previously had a different IFC file associated, I started getting errors so removed the original spatial tree, de-activated BlenderBIM, re-saved the file to create a new IFC and spatial tree.

[Model_Shell_TestIFC.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6099528/Model_Shell_TestIFC.zip)

**Comment by Moult** [comment]
I've added a few improvements that help in recovering files, and I've recovered your IFC for you.


[Model_Shell_Test_fixed.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6105268/Model_Shell_Test_fixed.zip)

**Comment by ChubbyQuark** [comment]
Hi Moult, I've updated to the latest version but am still getting some erroneous elements stored in the IFC (different file). Is there a way to purge items out that don't sync with the scene?

I really like the idea of modelling in Blender, outside of the IFC structure, then applying the IFC structure when needed. Is your long term goal to have these two environments automatically sync or work exclusively within the IFC hierarchy for new model items or amendments?
