### ISSUE TITLE
Removal of plugin error

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#1371]
On removing an existing BlenderBIM addon (210221) I'm getting this error: -

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\startup\bl_operators\userpref.py", line 793, in execute
    shutil.rmtree(path)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\chris\\AppData\\Roaming\\Blender Foundation\\Blender\\2.92\\scripts\\addons\\blenderbim\\libs\\site\\packages\\ifcopenshell\\_ifcopenshell_wrapper.pyd'

location: <unknown location>:-1

**Comment by ChubbyQuark** [comment]
OK, would this also cause issues with other functions? Sections are no longer working. I'm getting quite a few errors on various functions so could be issues with my set-up. Happy to post as they come in but don't want to cover old ground.

**Comment by Moult** [comment]
Anything to do with drawing generation should be considered unstable and broken for the moment as it is a work in progress. Other bugs are welcome.
