### ISSUE TITLE
Error upon uploading second ifc to same file

### ISSUE THREAD

**Issue by Rokorps** [IfcOpenShell/IfcOpenShell#1389]
**Hello,
When I try to upload second IFC file to same blend file i get this error:**

Python: Traceback (most recent call last):
  File "C:\Users\Rokas\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\operator.py", line 165, in execute
    ifc_importer.execute()
  File "C:\Users\Rokas\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\import_ifc.py", line 323, in execute
    self.load_existing_rooted_elements()
  File "C:\Users\Rokas\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\import_ifc.py", line 1080, in load_existing_rooted_elements
    self.existing_elements[self.file.by_id(obj.BIMObjectProperties.ifc_definition_id).GlobalId] = obj
AttributeError: 'NoneType' object has no attribute 'by_id'

location: <unknown location>:-1

**Upon the upload of the first IFC to blank blend file everything seems fine
Sincerely,
Rokas**

**Comment by Rokorps** [comment]
Updated blender and blenderbim to newest versions. Error seems absent.
