### ISSUE TITLE
blenderbim activation error on linux 20.04 - blender 2.92

### ISSUE THREAD

**Issue by Rokorps** [IfcOpenShell/IfcOpenShell#1394]
Hello,

Installation of addon goes fine, but when I try to activate blenderbim on blender 2.92 linux 20.04 , I get this error:

Traceback (most recent call last):
  File "/snap/blender/111/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/rokorps/.config/blender/2.92/scripts/addons/blenderbim/__init__.py", line 23, in <module>
    from .bim import *
  File "/home/rokorps/.config/blender/2.92/scripts/addons/blenderbim/bim/__init__.py", line 9, in <module>
    from . import ui, prop, operator
  File "/home/rokorps/.config/blender/2.92/scripts/addons/blenderbim/bim/prop.py", line 7, in <module>
    from . import schema
  File "/home/rokorps/.config/blender/2.92/scripts/addons/blenderbim/bim/schema.py", line 79, in <module>
    ifc = IfcSchema()
  File "/home/rokorps/.config/blender/2.92/scripts/addons/blenderbim/bim/schema.py", line 33, in __init__
    self.psetqto = ifcopenshell.util.pset.PsetQto("IFC4")
AttributeError: module 'ifcopenshell.util.pset' has no attribute 'PsetQto'

Regards,
Rokas

**Comment by ecke101** [comment]
Which release of BlenderBIM did you download?

**Comment by Rokorps** [comment]
It is the newest (210221), but after reinstalling blender 2.92 activation goes fine.
Problem seems fixed after reinstallation of blender
