### ISSUE TITLE
IFC export error

### ISSUE THREAD

**Issue by Rokorps** [IfcOpenShell/IfcOpenShell#1395]
Hello,
When I try to export any object on windows 7, blender 2,92, blenderbim 210221 I get this error:

Python: Traceback (most recent call last):
  File "C:\Users\Rokas\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\operator.py", line 99, in execute
    ifc_exporter.export()
  File "C:\Users\Rokas\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\export_ifc.py", line 18, in export
    self.set_header()
  File "C:\Users\Rokas\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\export_ifc.py", line 46, in set_header
    self.file.wrapped_data.header.file_name.name = os.path.basename(self.ifc_export_settings.output_file)
AttributeError: 'NoneType' object has no attribute 'wrapped_data'

location: <unknown location>:-1

Regards,
Rokas

**Comment by Rokorps** [comment]
This is most probably because the blend file was saved without ifc addon installed, therefore lost its BIM quatities. When attaching new quatities everything seems fine.
