### ISSUE TITLE
geom.app "wrong number or type of arguments"

### ISSUE THREAD

**Issue by stefkeB** [IfcOpenShell/IfcOpenShell#1444]
I'm trying to use the `IfcOpenShell.geom.app` application example, but get frequent crashes.

I'm running `Python 3.9` on `macOS Big Sur` and compiled `IfcOpenShell` and `PythonOCC` from sources.
OpenCASCADE is version 7.5.1

## occ_utils.py

Here I get the wrong number or type of arguments, when calling `V3d.V3d_DirectionalLight(viewer_handle)`
When I replace it with `light = V3d.V3d_DirectionalLight(*dir)` and comment out the next line (`SetDirection`), I can at least launch the viewer.

```python
        for dir in dirs:
            light = V3d.V3d_DirectionalLight(*dir)  # viewer_handle)
            # light.SetDirection(*dir)
            viewer.SetLightOn(light.GetHandle() if USE_OCCT_HANDLE else light)
```

## running the viewer

I use following minimal script to launch the viewer:

```python
from ifcopenshell.geom.app import application
a = application().start()
```

This seems to work fairly OK, but whenever I click on one of the Types or try to pick an object, I get a crash when calling into `AIS_InteractiveContext_Select`.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/OCC/Display/qtDisplay.py", line 210, in mouseReleaseEvent
    self._display.Select(pt.x(), pt.y())
  File "/usr/local/lib/python3.9/site-packages/ifcopenshell/geom/app.py", line 571, in HandleSelection
    v.Select()
  File "/usr/local/lib/python3.9/site-packages/OCC/Core/AIS.py", line 4932, in Select
    return _AIS.AIS_InteractiveContext_Select(self, *args)
TypeError: Wrong number or type of arguments for overloaded function 'AIS_InteractiveContext_Select'.
  Possible C/C++ prototypes are:
    AIS_InteractiveContext::Select(Standard_Integer const,Standard_Integer const,Standard_Integer const,Standard_Integer const,opencascade::handle< V3d_View > const &,Standard_Boolean const)
    AIS_InteractiveContext::Select(TColgp_Array1OfPnt2d const &,opencascade::handle< V3d_View > const &,Standard_Boolean const)
    AIS_InteractiveContext::Select(Standard_Boolean const)
```

This seems to be, again, a mismatch between the different libraries (PythonOCC, IfcOpenShell).

**Comment by stefkeB** [comment]
I'm getting more and more errors, but many of them are referring the PythonOCC code which is not fully updated to the latest open cascade release.

E.g., in [app.py#L571](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/geom/app.py#L571) the call `v.Select()` needs arguments 

E.g., in [app.py#L575](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/geom/app.py#L575) the calls to `GetObject()` and `SelectionPriority()` are not supported anymore.

See [https://github.com/tpaviot/pythonocc-core/issues/759](https://github.com/tpaviot/pythonocc-core/issues/759)

I also get an error on [app.py#L368](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/geom/app.py#L368) as `unicode` is not recognised.

**Comment by aothms** [comment]
Hi @stefkeB, thanks for your report. I guess with BlenderBIM existing, people don't really turn to this app anymore. Can you push the things you currently have (where possible with backwards compatibility) and then we resolve the issues as we go?

For backwards compatibility we currently have this https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/geom/app.py#L16

You can indeed trace back the things you mentioned to changes in the OCCT API:

Such as 

    V3d_DirectionalLight (const Handle< V3d_Viewer > &VM, ...

> https://dev.opencascade.org/doc/occt-6.9.0/refman/html/class_v3d___directional_light.html

    V3d_DirectionalLight (const gp_Dir &theDirection, ...

> https://dev.opencascade.org/doc/occt-7.4.0/refman/html/class_v3d___directional_light.html

For Select() it appears simply True is sufficient https://github.com/tpaviot/pythonocc-core/blob/master/src/Display/OCCViewer.py#L585

The SelectionPriority was a hack to get some sort of unique key so that we can associate the AIS_InteractiveShape with the IfcProduct. This was because SWIG would just return an opaque AIS_InteractiveObject at some point in the past on which we couldn't for example get back the TopoDS_Shape. I'm not sure if this has improved with more recent versions of OCCT.

There is apparently a SelectedShape() https://dev.opencascade.org/doc/refman/html/class_a_i_s___interactive_context.html#ac7879e85fade79a71e4f543a154763ff (not sure if new), but I'm not sure how this works for the MultipleConnectedShape https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/geom/occ_utils.py#L152 in use for products with items with different styles.

**Comment by Moult** [comment]
@stefkeB did you manage to commit your code updated for the latest OCCT API?

**Comment by cvoivret** [comment]
Hi , I'm currently exploring the solution of ifcopenshell+occ to make some heavy processing on the geometry of BIM model. I have the same error message when i try to init display. I would like to help but the problems seems to be related to swig and I'm not competent on that subject. Could I help in other ways ?

Btw, @aothms your comment on popularity of blenderbim surprise me. Do you mean that ifcopenshell+occ is not a viable solution or that blenderbim provide a easier access to the same features ?

**Comment by aothms** [comment]
The comment was strictly on the app itself (the property sets, decomposition tree, etc.). I still use ifcopenshell+occ heavily for geometric processing tasks, but then I just use ifcopenshell.geom.utils.initialize_display() and -display_shape(). Which are fully compatible with all thinkable versions of occt. When I need to present work to clients I typically use integrate it with ifc-pipeline [0] and load the analysis outcomes as additional gltfs that can be easily presented in ThreeJS. For the more standard viewer interfaces BlenderBIM is becoming an excellent alternative.

@cvoivret I think there's already a lot of solutions discussed in this issue. Would you be interested in starting with the current v0.7 version and with our guidance resolve the issues you encounter?

[0] https://github.com/AECgeeks/ifc-pipeline

**Comment by cvoivret** [comment]
@aothms thanks for the proposal. Yes, with some guidance I will try !
First step is to install and build last version of ifcopenshell i suppose. After that...

**Comment by aothms** [comment]
Building (as in compiling) is not necessary I guess. You can install using any of the providers here https://github.com/IfcOpenShell/IfcOpenShell/#ifcopenshell or https://github.com/IfcOpenBot/IfcOpenShell/commit/dc67287d4b083cabae39ee4f92fa93b6f74cae11#comments

**Comment by cvoivret** [comment]
Done. I confused by the problem. I understand from the error message that there is a inconsistency between function signatures. Since OCC (C++) is wrapped in python (SWIG) then used in IFCOS, where are the modifications to be done ? just in IFCOS to match/use the last version of the swig output ?

**Comment by aothms** [comment]
Yes, we have to adapt our codebase, preferably in a backwards compatible fashion using try-catch or by looking at OCC.VERSION

**Comment by cvoivret** [comment]
OK. You mean the C++ codebase of ifcos or the python version ? I'm presently using the python version (to get more confused...) and getting the error even with simple [code](https://github.com/cvoivret/canopia_ifcocc) without using the app. 
I do understand the data model for geometries so my poor python code is probably wrong.

**Comment by aothms** [comment]
I mean address in the original stacktrace by @stefkeB here:

```
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/OCC/Display/qtDisplay.py", line 210, in mouseReleaseEvent
      self._display.Select(pt.x(), pt.y())
->  File "/usr/local/lib/python3.9/site-packages/ifcopenshell/geom/app.py", line 571, in HandleSelection
->    v.Select()
    File "/usr/local/lib/python3.9/site-packages/OCC/Core/AIS.py", line 4932, in Select
      return _AIS.AIS_InteractiveContext_Select(self, *args)
```

so that's changing **the code of the geom.app** to be compatible with C++ occt changes (which led to changes in the generated code by swig)

What error do you get in your code then? What version of ifopsh and occt do you have installed?

**Comment by cvoivret** [comment]
I will investigate with around the given stacktrace.
Right now, with this minimal code :

```
import ifcopenshell
import ifcopenshell.geom
display=ifcopenshell.geom.utils.initialize_display()
```

I get this error :

```
[Cell In [5], line 6
      2 import ifcopenshell.geom
      5 # Initialize a graphical display window (from ifcos)
----> 6 display=ifcopenshell.geom.utils.initialize_display()

File ~\Anaconda3\envs\pyoccenv\lib\site-packages\ifcopenshell\geom\occ_utils.py:97, in initialize_display()
     94         light.SetDirection(*dir)
     95         viewer.SetLightOn(light.GetHandle() if USE_OCCT_HANDLE else light)
---> 97 setup()
     98 return handle

File ~\Anaconda3\envs\pyoccenv\lib\site-packages\ifcopenshell\geom\occ_utils.py:93, in initialize_display.<locals>.setup()
     90     dirs = [(3, 2, 1), (-1, -2, -3)]
     92 for dir in dirs:
---> 93     light = V3d.V3d_DirectionalLight(viewer_handle)
     94     light.SetDirection(*dir)
     95     viewer.SetLightOn(light.GetHandle() if USE_OCCT_HANDLE else light)

File ~\Anaconda3\envs\pyoccenv\lib\site-packages\OCC\Core\V3d.py:5380, in V3d_DirectionalLight.__init__(self, *args)
   5349 def __init__(self, *args):
   5350     r"""
   5351     Creates a directional light source in the viewer.
   5352
   (...)
   5378
   5379     """
-> 5380     _V3d.V3d_DirectionalLight_swiginit(self, _V3d.new_V3d_DirectionalLight(*args))
```

I have installed ifopsh and occt with anaconda. The versions are :
ifcopenshell=v0.7.0a4=py39h79529e9_1
pythonocc-core=7.6.2=py39h2100962_0

**Comment by cvoivret** [comment]
I will investigate with around the given stacktrace.
Right now, with this minimal code :

import ifcopenshell
import ifcopenshell.geom
display=ifcopenshell.geom.utils.initialize_display()

I get this error :

Cell In [5], line 6
      2 import ifcopenshell.geom
      5 # Initialize a graphical display window (from ifcos)
----> 6 display=ifcopenshell.geom.utils.initialize_display()

File
~\Anaconda3\envs\pyoccenv\lib\site-packages\ifcopenshell\geom\occ_utils.py:97,
in initialize_display()
     94         light.SetDirection(*dir)
     95         viewer.SetLightOn(light.GetHandle() if USE_OCCT_HANDLE else
light)
---> 97 setup()
     98 return handle

File
~\Anaconda3\envs\pyoccenv\lib\site-packages\ifcopenshell\geom\occ_utils.py:93,
in initialize_display.<locals>.setup()
     90     dirs = [(3, 2, 1), (-1, -2, -3)]
     92 for dir in dirs:
---> 93     light = V3d.V3d_DirectionalLight(viewer_handle)
     94     light.SetDirection(*dir)
     95     viewer.SetLightOn(light.GetHandle() if USE_OCCT_HANDLE else
light)

File ~\Anaconda3\envs\pyoccenv\lib\site-packages\OCC\Core\V3d.py:5380, in
V3d_DirectionalLight.__init__(self, *args)
   5349 def __init__(self, *args):
   5350     r"""
   5351     Creates a directional light source in the viewer.
   5352
   (...)
   5378
   5379     """
-> 5380     _V3d.V3d_DirectionalLight_swiginit(self,
_V3d.new_V3d_DirectionalLight(*args))

I have installed ifopsh and occt with anaconda. The versions are :
ifcopenshell=v0.7.0a4=py39h79529e9_1
pythonocc-core=7.6.2=py39h2100962_0


Le ven. 9 sept. 2022 à 16:08, Thomas Krijnen ***@***.***> a
écrit :

**Comment by aothms** [comment]
Right, so as you can see here:

In 7.4

We still had the constructor:

```c++
V3d_DirectionalLight(
    const Handle< V3d_Viewer > &theViewer,
    const V3d_TypeOfOrientation theDirection=V3d_XposYposZpos,
    const Quantity_Color &theColor=Quantity_NOC_WHITE,
    const Standard_Boolean theIsHeadlight=Standard_False
)
```

https://dev.opencascade.org/doc/occt-7.4.0/refman/html/class_v3d___directional_light.html

In 7.6 we don't have that, so we should probably use this one:

```c++
V3d_DirectionalLight(
    const gp_Dir &theDirection,
    const Quantity_Color &theColor=Quantity_NOC_WHITE,
    const Standard_Boolean theIsHeadlight=Standard_False
)
```

https://dev.opencascade.org/doc/occt-7.6.0/refman/html/class_v3d___directional_light.html

Which means that

**Comment by aothms** [comment]
See https://github.com/IfcOpenShell/IfcOpenShell/commit/6346c5ba471b3e385858411fe9ee52ae4d21bafe
