### ISSUE TITLE
BlenderBIM IFC Work Calendars

### ISSUE THREAD

**Issue by htlcnn** [IfcOpenShell/IfcOpenShell#1454]
@myoualid I'm not sure if creating an issue on github is the proper way to ask for the features you are working on. Please fix me.

I'm using blenderbim-210508 release on Blender 2.90.
I want to create a work calendar so I do it in **IFC Work Calendars** section. I add a calendar and add a working time in it. May I ask what should be filled into **Start** and **Finish** fields? I thought they're for start/finish time in a working day so I added 8 and 17 and chose **Daily** recurrence type. But when I finished editing working time, I had following exception:
```
Error: Traceback (most recent call last):
  File "C:\Users\HTL\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 906, in execute
    **{"work_time": self.file.by_id(self.props.active_work_time_id), "attributes": attributes},
  File "C:\Users\HTL\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 10, in run
    return usecase_class(ifc_file, **settings).execute()
  File "C:\Users\HTL\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\sequence\edit_work_time.py", line 14, in execute
    value = ifcopenshell.util.date.datetime2ifc(value, "IfcDate")
  File "C:\Users\HTL\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\date.py", line 60, in datetime2ifc
    dt = datetime.datetime.fromisoformat(dt)
ValueError: Invalid isoformat string: '8'
```
Here's a screenshot:
![image](https://user-images.githubusercontent.com/931924/117567721-8c237500-b0e7-11eb-91fb-31192c0232f3.png)

Thanks!

**Comment by aothms** [comment]
Judging by the traceback (`datetime.datetime.fromisoformat`) it expects YYYY-MM-DD https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat

**Comment by Moult** [comment]
Start and end is actually a date. It refers to the date range that the working or holiday times apply to.

**Comment by htlcnn** [comment]
I got it. I think they should be renamed **Start Date** and **End Date**.
I found where to add Start Time and End Time:
![image](https://user-images.githubusercontent.com/931924/117568355-0228db80-b0ea-11eb-9df7-faf00ad3ce01.png)
