### ISSUE TITLE
Remove deep unbatch unable to find instance

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1483]
This little snippet was my attempt to use remove_deep but only up to a portion of it. It seemed to trigger this error message. I've worked around it (creating dummy elements to bypass the mandatory cardinality was a bit of a hack), but thought I'd report in case this highlights a deeper problem which I might come across later.

Thanks to @theoryshaw for helping me trigger this bug during a demo session.

Test file: [test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6529702/test.ifc.txt)

```
import ifcopenshell.util.element
f = ifcopenshell.open("test.ifc")
dc = f.create_entity("IfcRepresentationContext")
drm = f.createIfcRepresentationMap()
e = f.by_id(66250)
e.ContextOfItems = dc
for item in e.Items:
    item.MappingSource = drm
ifcopenshell.util.element.remove_deep(f, e)

Traceback (most recent call last):
  File "/home/dion/drive/blender/blender-2.91.0-linux64/2.91/python/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/element.py", line 119, in remove_deep
    ifc_file.unbatch()
  File "/home/dion/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 189, in unbatch
    return self.wrapped_data.unbatch()
  File "/home/dion/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 1546, in unbatch
    return _ifcopenshell_wrapper.file_unbatch(self)
RuntimeError: Instance #66,248 not found
```

**Comment by Moult** [comment]
Tested on v0.7.0 and seems to be fixed.
