### ISSUE TITLE
BlenderBIM:  error when export

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1492]
When I try to re-export out [this](https://gitlab.com/openingdesign/110_enterprise_verona/-/blob/2615a51e50092b69b26e120c38624c746b37a714/Models%20and%20CAD/stairs.ifc) IFC from [this](https://gitlab.com/openingdesign/110_enterprise_verona/-/blob/2615a51e50092b69b26e120c38624c746b37a714/Models%20and%20CAD/Stairs.blend) Blender file, i get the following error. 

```

Python: Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\operator.py", line 31, in invoke
    return self.execute(context)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\operator.py", line 58, in execute
    ifc_exporter.export()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\export_ifc.py", line 24, in export
    self.sync_object_placements_and_deletions()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\export_ifc.py", line 83, in sync_object_placements_and_deletions
    self.sync_object_container(ifc_definition_id, obj)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\export_ifc.py", line 161, in sync_object_container
    bpy.ops.bim.assign_object(relating_object=parent_obj.name, related_object=obj.name)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\aggregate\operator.py", line 43, in execute
    collection.children.link(spatial_collection)
RuntimeError: Error: Collection 'IfcGroup/SECTION - E&W - LOOKING NORTH' already in collection 'IfcGroup/SECTION - E&W - LOOKING NORTH'


location: C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\ops.py:132



location: <unknown location>:-1



```

**Comment by theoryshaw** [comment]
nevermind, i'm an idiot.  :)
