### ISSUE TITLE
BlenderBIM: import error

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1493]
[This](https://gitlab.com/openingdesign/110_enterprise_verona/-/tree/2c21f0d2abe39755cd6bcb76ef1e678a1c4afdb9/Models%20and%20CAD/Blender%20%26%20IFC) IFC seems to export out fine from the Blender file, but if you import the IFC file into a new Blender file, you get the following error. 

```
Python: Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\operator.py", line 122, in execute
    ifc_importer.execute()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\import_ifc.py", line 334, in execute
    self.create_aggregates()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\import_ifc.py", line 1105, in create_aggregates
    rel_aggregates = [a for a in self.file.by_type("IfcRelAggregates") if a.RelatingObject.is_a("IfcElement")]
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\import_ifc.py", line 1105, in <listcomp>
    rel_aggregates = [a for a in self.file.by_type("IfcRelAggregates") if a.RelatingObject.is_a("IfcElement")]
AttributeError: 'NoneType' object has no attribute 'is_a'

location: <unknown location>:-1


```

**Comment by theoryshaw** [comment]
Just guessing this might be an [undo problem](https://github.com/IfcOpenShell/IfcOpenShell/issues/1475) as well.

**Comment by Moult** [comment]
Yes, it does seem suspiciously like borked data coming out of the BlenderBIM Add-on in the first place, which could very well be due to the undo problem. Closing bug and hoping it doesn't occur again.
