### ISSUE TITLE
BlenderBIM: error when drawing renamed

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1495]
See video for steps to replicate:
video: https://www.dropbox.com/s/rpsoc9q3d3wmeno/2021-05-26_21-25-50.mp4?dl=0

IFC [here](https://gitlab.com/openingdesign/110_enterprise_verona/-/blob/b1dc11fa515992b7a069934297bc68d981ac46f1/Models%20and%20CAD/Blender%20&%20IFC/test/test.ifc). 

error...

```

Python: Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\operator.py", line 31, in invoke
    return self.execute(context)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\operator.py", line 58, in execute
    ifc_exporter.export()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\export_ifc.py", line 24, in export
    self.sync_object_placements_and_deletions()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\export_ifc.py", line 83, in sync_object_placements_and_deletions
    self.sync_object_container(ifc_definition_id, obj)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\export_ifc.py", line 161, in sync_object_container
    bpy.ops.bim.assign_object(relating_object=parent_obj.name, related_object=obj.name)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\aggregate\operator.py", line 43, in execute
    collection.children.link(spatial_collection)
RuntimeError: Error: Collection 'IfcGroup/TESTY' already in collection 'IfcGroup/TESTY'


location: C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\ops.py:132



location: <unknown location>:-1



```

**Comment by Moult** [comment]
Fixed as part of https://github.com/IfcOpenShell/IfcOpenShell/commit/7fe2e93dea540a33763f8aa3ce9e07df9bd18844
