### ISSUE TITLE
BlenderBIM: creating an IfcLamp

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1502]
It seemed to create it, but got the following error:
![image](https://user-images.githubusercontent.com/507113/120055063-5d6b3100-bff9-11eb-9850-26cb1284a6a2.png)

```
Python: Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\root\operator.py", line 96, in execute
    self.assign_class(context, obj)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\root\operator.py", line 114, in assign_class
    bpy.ops.bim.add_representation(obj=obj.name, context_id=self.context_id)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 96, in execute
    result = ifcopenshell.api.run("geometry.add_representation", self.file, **representation_data)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 22, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 48, in execute
    return self.create_model_representation()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 103, in create_model_representation
    return self.create_variable_representation()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 223, in create_variable_representation
    return self.create_mesh_representation()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 411, in create_mesh_representation
    return self.create_polygonal_face_set()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 442, in create_polygonal_face_set
    for polygon in self.settings["geometry"].polygons:
AttributeError: 'PointLight' object has no attribute 'polygons'

location: C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\ops.py:132



location: <unknown location>:-1



```

**Comment by theoryshaw** [comment]
solved: https://matrix.to/#/!FORymwGwqHJnZDpjSI:matrix.org/$vYKxB4Is58vyULs-Vp4H2cBeu3T90_zeIYB1tHKcQ8E?via=matrix.org&via=tchncs.de&via=sans-nuage.fr
