### ISSUE TITLE
BlenderBIM: Imported the following IFC file, and deleted some objects, and then exported again

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1561]
Imported the following IFC file, and deleted some objects, and then exported again

File: https://www.dropbox.com/s/5n01brpbog90181/20210710_mudroom_structural_new.ifc?dl=1
Video: https://www.dropbox.com/s/vd30qm90fy2u8n8/2021-07-10_10-39-02.mp4?dl=0

```
Python: Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\operator.py", line 36, in invoke
    return self.execute(context)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\operator.py", line 44, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\ifc.py", line 181, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\operator.py", line 68, in _execute
    ifc_exporter.export()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\export_ifc.py", line 24, in export
    self.sync_object_placements_and_deletions()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\export_ifc.py", line 71, in sync_object_placements_and_deletions
    self.sync_object_placement(obj)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\export_ifc.py", line 96, in sync_object_placement
    blender_matrix = np.matrix(obj.matrix_world)
AttributeError: 'Material' object has no attribute 'matrix_world'

location: <unknown location>:-1

```

**Comment by Jesusbill** [comment]
I get the same error when just changing the assign blender material in one object, after having imported the ifc file

**Comment by Moult** [comment]
Sorry about that, a bit of WIP right now as I allow materials to be tracked by the id_map. The id_map allows you to track changes in Blender which may not go through an operator. Previously, only products (i.e. blender Objects) were tracked. Now, I'm extending it so that also materials are tracked. That way, if you edit things like material names or perhaps colours too, we can auto sync it.
