### ISSUE TITLE
Geometry serializers in python

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#1564]
The geometry serializers (DAE, SVG, OBJ, gLTF, ...) have long been a IfcConvert only thing. In the 0.7 branch we will get access to them from Python. This will enable much more granular control over how and what is serialized. Especially in the case of SVG this will mean a great deal of efficiency when we can keep the parsed model in memory, convert to SVG, join the disconnected line segments to areas, and map the areas back to IFC all in one script.

For a sneak preview have a look here (Unfortunately on linux64 and windows builds for the moment)

https://github.com/IfcOpenBot/IfcOpenShell/commit/83049bf41a9feb2c2094a9ad7e9850e24745a651#commitcomment-53443187

TODO:

- [ ] Next up is getting CGAL and svgfill (https://github.com/IfcOpenShell/svgfill) integrated.
- [ ] Work out all the settings and serializer options

```
import ifcopenshell
import ifcopenshell.geom

ss = ifcopenshell.geom.settings(
    # this is required for serialization
    APPLY_DEFAULT_MATERIALS=True,
)

f = ifcopenshell.open(...)
sr = ifcopenshell.geom.serializers.obj("elem.obj", "elem.mtl", ss)

for elem in ifcopenshell.geom.iterate(ss, f):
    sr.write(elem)
    
sr.finalize()
```

or

```
import ifcopenshell
import ifcopenshell.geom

ss = ifcopenshell.geom.settings(
    # this is required for serialization
    APPLY_DEFAULT_MATERIALS=True,
    DISABLE_TRIANGULATION=True
)

f = ifcopenshell.open(...)

buffer = ifcopenshell.geom.serializers.buffer()
sr = ifcopenshell.geom.serializers.svg(buffer, ss)

sr.setFile(f)
sr.setSectionHeightsFromStoreys()

for elem in ifcopenshell.geom.iterate(ss, f):
    sr.write(elem)
    
sr.finalize()

print(buffer.get_value())
```

**Comment by Moult** [comment]
Awesome! I managed to get some SVG output, so I'm now trying to recreate the existing flags used with IfcConvert. There are some issues, like:

```
>>> sr.setElevationRef("DRAWING")
Traceback (most recent call last):
  File "/home/dion/drive/blender/blender-2.93/2.93/python/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/2.93/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 1522, in setElevationRef
    return _ifcopenshell_wrapper.SvgSerializer_setElevationRef(self, s)
TypeError: in method 'SvgSerializer_setElevationRef', argument 2 of type 'boost::optional< std::string > const &'
```

This is the full args I'm trying to replicate. Can you give an example of the code to replicate it?

```
        subprocess.run(
            [
                ifcconvert_path,
                context.scene.BIMProperties.ifc_file,
                "-yv",
                svg_path,
                "--plan",
                "--model",
                "--elevation-ref=DRAWING",
                "--svg-xmlns",
                "--svg-project",
                "--svg-poly",
                "--svg-without-storeys",
                "--exclude",
                "entities",
                "IfcSpace",
                "IfcOpeningElement",
                "IfcDoor",
                "IfcWindow",
            ]
        )
```

Also, given that this is the v0.7.0 branch, I assume I can't just distribute this build because it might miss out on other fixes done on the v0.6.0 branch. What's the strategy for this? To migrate to v0.7.0, or to backport to v0.6.0?

**Comment by aothms** [comment]
Yep, that one was still on my list. See commit. I'll start a new build. See below for the correspondence between arg and code.

```
ifcconvert_path,                      # 
context.scene.BIMProperties.ifc_file, # f
"-yv",                                # n/a
svg_path,                             # buffer
"--plan",                             # ifcopenshell.geom.settings(INCLUDE_CURVES=True)
"--model",                            # ifcopenshell.geom.settings(EXCLUDE_SOLIDS_AND_SURFACES=False)
"--elevation-ref=DRAWING",            # sr.setElevationRef("DRAWING")
"--svg-xmlns",                        # sr.setUseNamespace(True)
"--svg-project",                      # sr.setAlwaysProject(True)
"--svg-poly",                         # sr.setUseHlrPoly(True)
"--svg-without-storeys",              # sr.setWithoutStoreys(True)
"--exclude",                          # ifcopenshell.geom.iterate(ss, f, include=("IfcSpace", ...)
"entities",                           # ...
"IfcSpace",                           # ...
"IfcOpeningElement",                  # ...
"IfcDoor",                            # ...
"IfcWindow",                          # ...
```

**Comment by aothms** [comment]
> Also, given that this is the v0.7.0 branch, I assume I can't just distribute this build because it might miss out on other fixes done on the v0.6.0 branch. What's the strategy for this? To migrate to v0.7.0, or to backport to v0.6.0?

We'll merge v0.6 a couple of times into v0.7, once v0.7 is stable we abandon v0.6? Thoughts?

**Comment by Moult** [comment]
Awesome :) I'll wait for the next v0.7.0 bot build to try again.

Yep, I think it's a good idea to move to v0.7.0. Anytime you think the time is right, go ahead and merge :)

**Comment by Moult** [comment]
Also ping #1153 for those following in this development.
