### ISSUE TITLE
BlenderBIM : Removing an object from its spatial container throws an error in console

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1599]
Using BlenderBIM v 210726
I realized I didn’t want to put an object in a certain spatial container. I click on the cross on the panel’s right to remove it. 
 
![image](https://user-images.githubusercontent.com/25156105/127161679-1a85cade-4742-41e9-a28e-71d5ba4e4c0a.png)

It throws an error and doesn’t remove the object from the spatial container.
```

Error: Python: Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\spatial\operator.py", line 110, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\ifc.py", line 181, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\spatial\operator.py", line 116, in _execute
    ifcopenshell.api.run(
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 46, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\spatial\remove_container.py", line 22, in execute
    self.file.remove(contained_in_structure)
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 398, in remove
    self.transaction.store_delete(inst)
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 104, in store_delete
    inverses = self.get_element_inverses(element)
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 111, in get_element_inverses
    for inverse in self.file.get_inverse(element):
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 384, in get_inverse
    return [entity_instance(e, self) for e in self.wrapped_data.get_inverse(inst.wrapped_data)]
AttributeError: 'tuple' object has no attribute 'wrapped_data'

location: <unknown location>:-1
```

**Expected Behavior** : Remove the object from the spatial container’s collection, restore the field to a blank slate. Place the object either in the collection it previously was in, (may be better as UX but requires storing a reference to it somewhere), or place it in the Scene Collection (less error-prone, since it’s required to always exist)

When I quit & reload the file, the wall doesn’t recognize it’s an IFCWall object anymore. I click on the icon to reset it.
 
![image](https://user-images.githubusercontent.com/25156105/127162092-237202c4-8ee7-4a5e-a29d-7eda49fd15c8.png)

I then set its class to IfcWall. The console outputs an error. 

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\root\operator.py", line 96, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\ifc.py", line 181, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\root\operator.py", line 107, in _execute
    self.assign_class(context, obj)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\root\operator.py", line 126, in assign_class
    bpy.ops.bim.add_representation(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 69, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\ifc.py", line 181, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 126, in _execute
    "styles": [
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 127, in <listcomp>
    self.file.by_id(s.material.BIMMaterialProperties.ifc_style_id)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 327, in by_id
    return self[id]
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 315, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1499, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1025 not found

location: C:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\bpy\ops.py:132

location: <unknown location>:-1
```

It seems to otherwise have worked. I can click on the cross icon to remove it from its spatial container and it correctly is removed from the spatial container collection and is placed in the scene collection.
I move it back in the spatial container using the panel UI. It works. I export the ifc file. I open the ifc file in a 3rd party BIM viewer. It contains a wall object, under the Walls collection on the ground floor (correct) but there is no geometry.

**Expected behavior** : The wall geometry should be exported.

I saw in the mesh properties that I can “Update the Representation”. I click on it but it throws an error :
```

Error: Python: Traceback (most recent call last):
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 285, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\ifc.py", line 181, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 295, in _execute
    self.update_obj_mesh_representation(context, obj)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 347, in update_obj_mesh_representation
    "styles": [
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 348, in <listcomp>
    self.file.by_id(s.material.BIMMaterialProperties.ifc_style_id)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 327, in by_id
    return self[id]
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 315, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "C:\Users\  \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1499, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1025 not found

location: <unknown location>:-1

```

If I export the file again and open it in a viewer, there is still no geometry attached to the wall.
**Expected behavior** : Fix the geometry ?

At this point I realize I have to start from scratch, but I don’t think there is a way to roll everything to a clean slate. Since my objects have been modified with BIM custom props, I can’t create a new project without risking dirty objects messing things up.

Possible improvements : 
-	Prevent objects from irremediably lose their connection to their data (IFC data, object information and mesh data).
-	Provide a way for users to “clean” their file and remove all BlenderBIM props information from their objects.

**Comment by Moult** [comment]
First error is a bug, will fix. Second and third error are because you may have unlinked the object to IFC, but the material associated with the object still has a broken link. You need to unlink the material as well, then it can recreate it afresh.

That said, I will add a full "purge" ability in the debug panel to help for "cleaning" the file and starting afresh. This is a last resort, however. The first goal is stop make the connection more robust. These bugreports are really good, please continue to report!

**Comment by Gorgious56** [comment]
@Moult That was fast ! Happy to help, I'll report as I learn how to use the add-on :) 
I didn't know the material was also linked, I'll dig into that next time I have a data disconnection.
