### ISSUE TITLE
BlenderBIM : Adding a Subcontract or Crew throws error

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1610]
Using V210726, ifc 2x3
Granted I don't really know what I'm doing but I thought I'd be able to add items to this list.
![image](https://user-images.githubusercontent.com/25156105/127522743-9832039b-4724-4e6a-8e57-71ad0d4618e1.png)
Executing either of one these operators throws the same error and doesn't change anything :

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\resource\operator.py", line 122, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\ifc.py", line 181, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\resource\operator.py", line 125, in _execute
    ifcopenshell.api.run(
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 46, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\resource\add_resource.py", line 31, in execute
    context = self.file.by_type("IfcContext")[0]
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 359, in by_type
    return [entity_instance(e, self) for e in self.wrapped_data.by_type(type)]
  File "C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1481, in by_type
    return _ifcopenshell_wrapper.file_by_type(self, *args)
RuntimeError: Entity with 'IfcContext' not found

location: <unknown location>:-1

```

**Comment by Moult** [comment]
This is a known error, because currently resources, costing, and scheduling features are only built for IFC4. If they work for IFC2X3, it is by coincidence, not by design. The reason is because IFC4 contains a significantly greater number of features for resources, costing, and scheduling.

Perhaps to improve the user experience, we can introduce a poll return false in the UI for the `cost`, `resource`, and `sequence` module ui.py panels that checks if IfcStore.get_file().schema == "IFC2X3". Would this be something you could help tackle?

**Comment by Gorgious56** [comment]
See PR https://github.com/IfcOpenShell/IfcOpenShell/pull/1614

**Comment by Moult** [comment]
Thanks! Btw I think the hasattr is not required. All files have a schema. It'll either be None or a file object.

**Comment by Gorgious56** [comment]
@Moult Yeah I thought that may be overkill... Was overly cautious because I don't know so much (yet) about the `file` innards. Noted !
