### ISSUE TITLE
BlenderBIM : Adding a Cost Schedule throws error

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1611]
Using V0.0.210726 and ifc2x3
Trying to add a Cost Schedule throws error and doesn't complete.

![image](https://user-images.githubusercontent.com/25156105/127524194-ad26de0a-66cb-4d2b-98a2-2b6d2ffae0ee.png)
```

Python: Traceback (most recent call last):
Error: Python: Traceback (most recent call last):
  File "C:\Users\   \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\cost\operator.py", line 17, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\   \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\ifc.py", line 195, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\   \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\cost\operator.py", line 20, in _execute
    ifcopenshell.api.run("cost.add_cost_schedule", IfcStore.get_file())
  File "C:\Users\   \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 46, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\   \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\cost\add_cost_schedule.py", line 21, in execute
    cost_schedule.UpdateDate = ifcopenshell.util.date.datetime2ifc(datetime.now(), "IfcDateTime")
  File "C:\Users\   \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 121, in __setattr__
    self[index] = value
  File "C:\Users\   \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 158, in __setitem__
    raise ValueError(
ValueError: Expected EntityInstance for attribute IfcCostSchedule.UpdateDate, got '2021-07-29T17:53:55.569465'

location: <unknown location>:-1
```

**Comment by Moult** [comment]
Same issue as #1610.

**Comment by Gorgious56** [comment]
See PR https://github.com/IfcOpenShell/IfcOpenShell/pull/1614
