### ISSUE TITLE
Mac OS - Fails to open IFC file

### ISSUE THREAD

**Issue by brendon-reidefine** [IfcOpenShell/IfcOpenShell#1631]
Hi
I removed the previous BlenderBIM addon as recommended; disable first, restart Blender, then remove. Restarted Blender again, then added the latest version, before restarting again. Tried Importing an IFC file and get the below error.

`bpy.ops.bim.save_drawing_style(index="2")
bpy.ops.object.delete(use_global=False)
Deleted 1 object(s)
bpy.context.space_data.system_folders_active = 0
bpy.context.space_data.system_folders_active = 2
bpy.context.space_data.system_folders_active = 0
Python: Traceback (most recent call last):
  File "/Users/Papabej/Library/Application Support/Blender/2.93/scripts/addons/blenderbim/bim/operator.py", line 116, in execute
    logging.basicConfig(
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/logging/__init__.py", line 1999, in basicConfig
    h = FileHandler(filename, mode,
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/logging/__init__.py", line 1128, in __init__
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not tuple

location: <unknown location>:-1

bpy.ops.import_ifc.bim(filepath="/Applications/BIMcollab ZOOM/Sample/EN/01_Design/01_BIMcollab_Example_ARC.ifczip")
bpy.data.window_managers["WinMan"].addon_search = "ifc"
Python: Traceback (most recent call last):
  File "/Users/Papabej/Library/Application Support/Blender/2.93/scripts/addons/blenderbim/bim/operator.py", line 116, in execute
    logging.basicConfig(
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/logging/__init__.py", line 1999, in basicConfig
    h = FileHandler(filename, mode,
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/logging/__init__.py", line 1128, in __init__
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not tuple

location: <unknown location>:-1

bpy.ops.import_ifc.bim(filepath="/Applications/BIMcollab ZOOM/Sample/EN/01_Design/01_BIMcollab_Example_ARC.ifczip")
`

**Comment by Moult** [comment]
Sorry this was something we broke just before releasing and I was too lazy to re-release for Mac - sorry :) Grab a release from here https://github.com/IfcOpenShell/IfcOpenShell/releases and it should be fixed!
