### ISSUE TITLE
error with BlenderBIM while importing (any) ifc

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [IfcOpenShell/IfcOpenShell#1643]
just updated to blender 2.93.2 and blenderBIM 0.0.210731 and I get the following error while importing any ifc:

Python: Traceback (most recent call last):
  File "/Users/markussteinbrecher/Library/Application Support/Blender/2.93/scripts/addons/blenderbim/bim/operator.py", line 116, in execute
    logging.basicConfig(
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/logging/__init__.py", line 1999, in basicConfig
    h = FileHandler(filename, mode,
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/logging/__init__.py", line 1128, in __init__
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not tuple

location: <unknown location>:-1

am I missing something basic? python version?

Thanks!

**Comment by theoryshaw** [comment]
try the following... 
https://github.com/IfcOpenShell/IfcOpenShell/releases

Blender 2.93 uses Python 3.9

![image](https://user-images.githubusercontent.com/507113/129061550-d55834a1-d9ea-40e7-93a0-01f78db039c1.png)

**Comment by Moult** [comment]
Apologies, yes the last release's mac build was messed up at the last moment and although I hotfixed Linux and Windows, I ... didn't do Mac.

Download one of the latest releases from Github (py39) and you should be good to go. In the meantime, I've swapped the download link from the main website to point to Github.
