### ISSUE TITLE
Error when creating project - build 210817

### ISSUE THREAD

**Issue by onceadrog** [IfcOpenShell/IfcOpenShell#1667]
Daily build: 210817-py39-win with Blender 2.93.2

Steps to reproduce:
Open Blender, Scene>IFC Project>Create Project

As a result any other IFC actions don't have objects set up properly, and throw python errors, although you can load an IFC library for types without error.

Issue does not occur in build 210816

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\project\operator.py", line 39, in execute
    result = self._execute(context)
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\project\operator.py", line 63, in _execute
    bpy.ops.bim.assign_class(obj=project.name, ifc_class="IfcProject")
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\root\operator.py", line 115, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\ifc.py", line 217, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\root\operator.py", line 126, in _execute
    self.assign_class(context, obj)
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\root\operator.py", line 132, in assign_class
    product = ifcopenshell.api.run(
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 46, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\root\create_entity.py", line 19, in execute
    "OwnerHistory": ifcopenshell.api.run("owner.create_owner_history", self.file)
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 46, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\owner\create_owner_history.py", line 14, in execute
    self.settings["person"] = ifcopenshell.api.owner.settings.get_person(self.file)
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\handler.py", line 234, in <lambda>
    if getPersons(None, None) and scene.BIMOwnerProperties.user_person
AttributeError: 'NoneType' object has no attribute 'BIMOwnerProperties'

location: C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py:132



location: <unknown location>:-1
```

**Comment by aldomontanari** [comment]
I've tried saving the blender file before creating the IFC project.
Daily build: 210817-py39-win with Blender 3.0.0 Alpha
Same behaviour

Saved "foo1.blend"
bpy.context.space_data.context = 'SCENE'
bpy.ops.bim.add_person()
bpy.ops.bim.add_organisation()
bpy.ops.bim.assign_class(obj="My Project", ifc_class="IfcProject")
bpy.ops.bim.create_project()

Python: Traceback (most recent call last):
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 39, in execute
    result = self._execute(context)
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 63, in _execute
    bpy.ops.bim.assign_class(obj=project.name, ifc_class="IfcProject")
  File "C:\Users\aldom\Downloads\Blender builds\blender-3.0.0-alpha+master.49a363f0e0d8-windows.amd64-release\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\root\operator.py", line 115, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\ifc.py", line 217, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\root\operator.py", line 126, in _execute
    self.assign_class(context, obj)
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\root\operator.py", line 132, in assign_class
    product = ifcopenshell.api.run(
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 46, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\root\create_entity.py", line 19, in execute
    "OwnerHistory": ifcopenshell.api.run("owner.create_owner_history", self.file)
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 46, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\owner\create_owner_history.py", line 14, in execute
    self.settings["person"] = ifcopenshell.api.owner.settings.get_person(self.file)
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\handler.py", line 234, in <lambda>
    if getPersons(None, None) and scene.BIMOwnerProperties.user_person
AttributeError: 'NoneType' object has no attribute 'BIMOwnerProperties'

location: C:\Users\aldom\Downloads\Blender builds\blender-3.0.0-alpha+master.49a363f0e0d8-windows.amd64-release\3.0\scripts\modules\bpy\ops.py:132



location: <unknown location>:-1

**Comment by Moult** [comment]
Ping @Gorgious56 I think some of the changes here might've deleted a bit too much :)
https://github.com/IfcOpenShell/IfcOpenShell/commit/fb1c340664bed07d4d6d6648e8cae2b8e58b9b63

**Comment by Gorgious56** [comment]
Sorry !! I should have tested it, I assumed the scene argument would always point to the current scene but I guess it's not the case. Should be fixed now.
