### ISSUE TITLE
BlenderBim : IFC Style Attribute is None, causing error on validation

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1672]
![image](https://user-images.githubusercontent.com/25156105/130141912-e7892622-742a-4bf1-adf0-34fc0a7653a6.png)

When editing a material's style attributes, the attribute `styles` is initialized as `None`. Which causes an error when validating the style.

```

Error: Python: Traceback (most recent call last):
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\style\operator.py", line 159, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\ifc.py", line 217, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\style\operator.py", line 173, in _execute
    ifcopenshell.api.run("style.edit_style", self.file, **{"style": style, "attributes": attributes})
  File "c:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\ifcopenshell\api\__init__.py", line 46, in run   
    result = usecase_class(ifc_file, **settings).execute()
  File "c:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\ifcopenshell\api\style\edit_style.py", line 10, in execute
    setattr(self.settings["style"], name, value)
  File "c:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\ifcopenshell\entity_instance.py", line 121, in __setattr__
    self[index] = value
  File "c:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\ifcopenshell\entity_instance.py", line 139, in __setitem__
    self.wrapped_data.setArgumentAsNull(idx)
  File "c:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\ifcopenshell\ifcopenshell_wrapper.py", line 1774, in setArgumentAsNull
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsNull(self, i)
RuntimeError: Attribute not set

location: <unknown location>:-1
```

I've found a temporary workaround to set the attribute to an empty string before calling the api operator : 

    def _execute(self, context):
        material = context.active_object.active_material
        props = material.BIMStyleProperties
        attributes = blenderbim.bim.helper.export_attributes(props.attributes)
        """
        for key, value in attributes.items():
            # The "styles" attribute is None which it shouldn't be. Defaulting to empty string to prevent error
            if value is None:
                attributes[key] = ""
        """
        self.file = IfcStore.get_file()
        style = self.file.by_id(material.BIMMaterialProperties.ifc_style_id)
        ifcopenshell.api.run("style.edit_style", self.file, **{"style": style, "attributes": attributes})
        Data.load(IfcStore.get_file(), material.BIMMaterialProperties.ifc_style_id)
        bpy.ops.bim.disable_editing_style()
        return {"FINISHED"}

I'm wondering if the error can be fixed higher up in the chain of events. Just wanted to point that out in case there is an obvious fix. :)

**Comment by Moult** [comment]
Agreed, these issues are better solved higher up in the chain.

In this case, every time you press an "edit" button, the BlenderBIM Add-on does a "mini" import of some IFC attributes that you can edit. For convenience, this "import_attributes" helper [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/helper.py#L53) helps auto fill the blender Attribute property group with the correct data types that correspond to IFC data types.

IFC has a few tricky data types that don't map well to Blender property primitives. They are "entity", which are references to other IFC elements, "list" / "set", which are lists and sets, and "select", which are an enumeration of multiple data types.

In these cases, the helper should not auto map it to a Blender attribute. We should instead use a callback to decide how we want to handle these special cases.

This bug was because the "select" data type slipped through the cracks :) I've made it more robust.

**Comment by Gorgious56** [comment]
Thanks for the explanation ! I think I understand the attribute mapping but I've yet to peek into the ifcopenshell modules to see how it's actually constructed in the backend :)
