### ISSUE TITLE
unit.assign_unit via ifcopenshell.api.run should not show IndexError: list index out of range

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#1677]
I followed the procedure described in [Introduction to OpenBIM, Native IFC, and Open Source AEC](https://www.youtube.com/watch?app=desktop&v=h2Rv9iu7yDk).

I am getting `IndexError: list index out of range`
when executing the following code in BlenderBIM Python Console

```python
import ifcopenshell
import ifcopenshell.api

model = ifcopenshell.api.run('project.create_file')

project = ifcopenshell.api.run('root.create_entity', model, 'IfcProject')
project.Name = 'kubas House'

ifcopenshell.api.run("unit.assign_unit", model)
```

Environment: macOS 11.5.2 (20G95); Blender 2.93.3 2021-08-18; BlemderBIM 0.0.210819

**Comment by kurb70** [comment]
Sorry. Here is the full error message:

```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/Users/kuba/Library/Application Support/Blender/2.93/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 46, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "/Users/kuba/Library/Application Support/Blender/2.93/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/unit/assign_unit.py", line 30, in execute
    unit_assignment = self.get_unit_assignment()
  File "/Users/kuba/Library/Application Support/Blender/2.93/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/unit/assign_unit.py", line 44, in get_unit_assignment
    self.file.by_type("IfcContext")[0].UnitsInContext = unit_assignment
IndexError: list index out of range
```

**Comment by Moult** [comment]
You're missing an `ifc_class="IfcProject"` when you create a project. Otherwise, it doesn't create an IfcProject, it'll fallback to a building element proxy.

**Comment by kurb70** [comment]
@Moult Thank you very much. That was the problem. I just didn't see that.
