### ISSUE TITLE
BlenderBim : Undoing a library addition doesn't fully remove element

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1709]
Brand new file,

1. Create Project
2. Load library file (eg the [demo library file](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/libraries/blenderbim-demo-library.ifc))
3. Append element (eg a beam type)
![image](https://user-images.githubusercontent.com/25156105/131336322-b2ddeba1-b47a-4136-bcde-e97f081e98ed.png)
It's successfully added to the scene and a new empty object is created
![image](https://user-images.githubusercontent.com/25156105/131336381-2f93403a-6cdf-42de-8386-4a2f47968002.png)
4. Undo with CTRL Z
The empty object is removed
![image](https://user-images.githubusercontent.com/25156105/131336422-0f9dcb85-bbc0-46f0-95ab-1e025c36a3db.png)
But the beam type is still available :
![image](https://user-images.githubusercontent.com/25156105/131336464-fcacc059-a7ea-4fdb-81a6-356d207275de.png)
5. Creating a new instance with SHIFT + A throws an error :
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\model\workspace.py", line 145, in 
execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\ifc.py", line 232, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\model\workspace.py", line 150, in 
_execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\model\workspace.py", line 154, in 
hotkey_S_A
    bpy.ops.bim.add_type_instance()
  File "c:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\model\product.py", line 67, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\ifc.py", line 232, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\model\product.py", line 83, in _execute
    if profile.DumbProfileGenerator(relating_type).generate():
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\model\profile.py", line 124, in generate
    return self.derive_from_cursor()
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\model\profile.py", line 128, in derive_from_cursor
    return self.create_profile()
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\model\profile.py", line 180, in create_profile
    bpy.ops.bim.switch_representation(
  File "c:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 197, in execute
    self.pull_mesh_from_ifc(context)
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 238, in pull_mesh_from_ifc
    material_creator.create(element, self.element_obj, mesh)
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\import_ifc.py", line 76, in create       
    self.add_default_material(element)
  File "C:\Users\Gorgious\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\import_ifc.py", line 95, in add_default_material
    self.mesh.materials.append(self.materials[material.id()])
KeyError: 72

location: c:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\bpy\ops.py:132



location: c:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\bpy\ops.py:132



location: <unknown location>:-1
```

But does create a beam with correct type 

![image](https://user-images.githubusercontent.com/25156105/131336936-20fcadb4-a9e4-4fe8-8d72-e7bf390731a3.png)

But no parametric Pset :

![image](https://user-images.githubusercontent.com/25156105/131337022-0c856a33-ca14-4409-86e8-d5a691e3b21f.png)

**Comment by Moult** [comment]
So this is an interesting one and I believe the commit fixes it but I'm not 100% happy with the fix and would like @aothms 's opinion on it.

In short the error is because the transaction system in IfcOpenShell previously tracked changes to create / remove / edit, but I forgot to track changes to add operations (adding is when an element is appended from another file object). My solution looks for all newly created elements above the highest STEP ID, but for now since the C++ `MaxId` is not exposed, I am using `FreshId()`. This skips an ID, which is not illegal but is a bit sloppy.

@aothms what do you think of the approach? Is it sound? Am I forgetting something? Should I expose `MaxId` to Python and stop using `FreshId`?

**Comment by Moult** [comment]
Bump ping @aothms whether or not the transaction approach seems sane, and if so, an exposed MaxId would help.

**Comment by aothms** [comment]
Sorry missed this one.

> added_elements = [e for e in self.traverse(result) if e.id() > max_id]
> [self.transaction.store_create(e) for e in reversed(added_elements)]

Hm, it's clever, there is nothing wrong with FreshId() but surely adding max_id() to python as well is a bit better. This approach does leave behind instances of types for select values, e.g. the nominalvalue of a property, because they have id=0. It's not an immediate concern, as they are not written to file, but it might be noticeable in memory usage if you undo/redo large additions of e.g properties.

Maybe a better approach would be to somehow have file.add() return all instances that recursively got added (as a new function prototype)? In C++ the call is already recursive, so it's not a huge amount of work to make it collect them.

**Comment by Moult** [comment]
@aothms hmm, `file.add()` currently returns the actual instance that got added, which is nice and intuitive (and I use that return value in a number of places, I assume others have too). I guess it could return a list of instances that got added, with the first item in the list being the instance that got added... but this has the risk that if you add something that already has been added, then would the list be empty, or the first item always be the item you've added regardless if its added? Seems quirky, and seemingly not very elegant as an API.

Maybe at a stretch it could have a file.get_added()? Or maybe I am overthinking this?

As for leaving behind instances of types with id=0 I think that's OK, since I believe https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/file.py#L57 catches it.

**Comment by aothms** [comment]
Fully agree, we shouldn't change the API. my thought was more like an optional keyword arg or sth:

```
additions = []
new_inst = file.add(inst, addition=additions)
# additions now contains actually added elements, as you said potentially nothing
```

But these kind of "out" arguments I think is not very pythonic. And quite a pain to implement I think in the current wrapping process. The current swig typemaps are all by value.

Somehow keeping the state of the addition result in the file to be fetched in another call also doesn't sound very appealing to me. At the very least it's thread unsafe.

So yes, if we can get away with not doing this, I also prefer that.

> As for leaving behind instances of types with id=0 I think that's OK

Yes I also don't think there is a functional problem, just that we slowly accumulate them in the file as we cannot clean them up after an undo.

**Comment by Moult** [comment]
Ah OK then, yes indeed the out argument isn't very nice either, and because this is based in transactions, it's easier / nicer to keep it as is, instead of having the wrapper secretly call a different add function signature under the hood.

We'll leave it as is I guess then, with the new max ID functionality - when I use max ID with the next build, I'll close this bug :)
