### ISSUE TITLE
v0.7.0 libSerializers not linked to opencollada

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1757]
[report transferred from #1705]

I see this error:

```
$ python
Python 3.9.7 (default, Aug 30 2021, 00:00:00)
[GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/ifcopenshell/__init__.py", line 43, in <module>
    from . import ifcopenshell_wrapper
  File "/usr/lib64/python3.9/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>
    from . import _ifcopenshell_wrapper
ImportError: /lib64/libSerializers.so.0.6: undefined symbol: _ZN9COLLADASW4CSWC20CSW_ELEMENT_VERTICESB5cxx11E
```

This is because libSerializers.so is not linked to opencollada:

```
[ 94%] Linking CXX shared library libSerializers.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/Serializers.dir/link.txt --verbose=1
/usr/bin/g++ -fPIC -lxml2 -DNDEBUG -O3 -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -shared -Wl,-soname,libSerializers.so.0.6 -o libSerializers.so.0.6.0 CMakeFiles/Serializers.dir/builddir/build/BUILD/IfcOpenShell-0.7.0/src/serializers/ColladaSerializer.cpp.o CMakeFiles/Serializers.dir/builddir/build/BUILD/IfcOpenShell-0.7.0/src/serializers/GltfSerializer.cpp.o CMakeFiles/Serializers.dir/builddir/build/BUILD/IfcOpenShell-0.7.0/src/serializers/HdfSerializer.cpp.o CMakeFiles/Serializers.dir/builddir/build/BUILD/IfcOpenShell-0.7.0/src/serializers/OpenCascadeBasedSerializer.cpp.o CMakeFiles/Serializers.dir/builddir/build/BUILD/IfcOpenShell-0.7.0/src/serializers/SvgSerializer.cpp.o CMakeFiles/Serializers.dir/builddir/build/BUILD/IfcOpenShell-0.7.0/src/serializers/WavefrontObjSerializer.cpp.o CMakeFiles/Serializers.dir/builddir/build/BUILD/IfcOpenShell-0.7.0/src/serializers/XmlSerializer.cpp.o CMakeFiles/Serializers.dir/builddir/build/BUILD/IfcOpenShell-0.7.0/src/serializers/util.cpp.o  -Wl,-rpath,/builddir/build/BUILD/IfcOpenShell-0.7.0/cmake/x86_64-redhat-linux-gnu: libSerializers_ifc2x3.a libSerializers_ifc4.a libSerializers_ifc4x1.a libSerializers_ifc4x2.a libSerializers_ifc4x3_rc1.a libSerializers_ifc4x3_rc2.a libSerializers_ifc4x3_rc3.a libSerializers_ifc4x3_rc4.a libIfcGeom.so.0.6.0 libIfcGeom_ifc2x3.a libIfcGeom_ifc4.a libIfcGeom_ifc4x1.a libIfcGeom_ifc4x2.a libIfcGeom_ifc4x3_rc1.a libIfcGeom_ifc4x3_rc2.a libIfcGeom_ifc4x3_rc3.a libIfcGeom_ifc4x3_rc4.a libIfcParse.so.0.6.0 -lboost_system -lboost_program_options -lboost_regex -lboost_thread -lboost_date_time -lboost_iostreams -lboost_chrono -lboost_atomic -lxml2 -lpthread -lTKernel -lTKMath -lTKBRep -lTKGeomBase -lTKGeomAlgo -lTKG3d -lTKG2d -lTKShHealing -lTKTopAlgo -lTKMesh -lTKPrim -lTKBool -lTKBO -lTKFillet -lTKSTEP -lTKSTEPBase -lTKSTEPAttr -lTKXSBase -lTKSTEP209 -lTKIGES -lTKOffset -lTKHLR -lhdf5_cpp -lhdf5 -lz -lsz -laec 
```

IfcConvert is linked to opencollada, so this is ok:

```
[ 97%] Linking CXX executable IfcConvert
/usr/bin/cmake -E cmake_link_script CMakeFiles/IfcConvert.dir/link.txt --verbose=1
/usr/bin/g++ -lxml2 -DNDEBUG -O3 -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -rdynamic CMakeFiles/IfcConvert.dir/builddir/build/BUILD/IfcOpenShell-0.7.0/src/ifcconvert/IfcConvert.cpp.o -o IfcConvert  -Wl,-rpath,/builddir/build/BUILD/IfcOpenShell-0.7.0/cmake/x86_64-redhat-linux-gnu: libIfcGeom_ifc2x3.a libIfcGeom_ifc4.a libIfcGeom_ifc4x1.a libIfcGeom_ifc4x2.a libIfcGeom_ifc4x3_rc1.a libIfcGeom_ifc4x3_rc2.a libIfcGeom_ifc4x3_rc3.a libIfcGeom_ifc4x3_rc4.a libIfcGeom_ifc2x3.a libIfcGeom_ifc4.a libIfcGeom_ifc4x1.a libIfcGeom_ifc4x2.a libIfcGeom_ifc4x3_rc1.a libIfcGeom_ifc4x3_rc2.a libIfcGeom_ifc4x3_rc3.a libIfcGeom_ifc4x3_rc4.a libSerializers.so.0.6.0 libSerializers_ifc2x3.a libSerializers_ifc4.a libSerializers_ifc4x1.a libSerializers_ifc4x2.a libSerializers_ifc4x3_rc1.a libSerializers_ifc4x3_rc2.a libSerializers_ifc4x3_rc3.a libSerializers_ifc4x3_rc4.a -lTKernel -lTKMath -lTKBRep -lTKGeomBase -lTKGeomAlgo -lTKG3d -lTKG2d -lTKShHealing -lTKTopAlgo -lTKMesh -lTKPrim -lTKBool -lTKBO -lTKFillet -lTKSTEP -lTKSTEPBase -lTKSTEPAttr -lTKXSBase -lTKSTEP209 -lTKIGES -lTKOffset -lTKHLR -lboost_system -lboost_program_options -lboost_regex -lboost_thread -lpthread -lboost_date_time -lboost_iostreams -lboost_chrono -lboost_atomic -lGeneratedSaxParser -lMathMLSolver -lOpenCOLLADABaseUtils -lOpenCOLLADAFramework -lOpenCOLLADASaxFrameworkLoader -lOpenCOLLADAStreamWriter -lUTF -lbuffer -lftoa -lpcre -lhdf5_cpp -lhdf5 -lz -lsz -laec libIfcGeom.so.0.6.0 libIfcGeom_ifc2x3.a libIfcGeom_ifc4.a libIfcGeom_ifc4x1.a libIfcGeom_ifc4x2.a libIfcGeom_ifc4x3_rc1.a libIfcGeom_ifc4x3_rc2.a libIfcGeom_ifc4x3_rc3.a libIfcGeom_ifc4x3_rc4.a libIfcParse.so.0.6.0 -lboost_system -lboost_program_options -lboost_regex -lboost_thread -lboost_date_time -lboost_iostreams -lboost_chrono -lboost_atomic -lxml2 -lpthread -lTKernel -lTKMath -lTKBRep -lTKGeomBase -lTKGeomAlgo -lTKG3d -lTKG2d -lTKShHealing -lTKTopAlgo -lTKMesh -lTKPrim -lTKBool -lTKBO -lTKFillet -lTKSTEP -lTKSTEPBase -lTKSTEPAttr -lTKXSBase -lTKSTEP209 -lTKIGES -lTKOffset -lTKHLR 
```

I can `import ifcopenshell` in the blender python console, presumably this works because blender is linked to opencollada somewhere.

I'm using these build flags:

```
/usr/bin/cmake -S . -B x86_64-redhat-linux-gnu -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 -DLIBDIR=/usr/lib64 -DINCLUDEDIR=/usr/include -DBINDIR=/usr/bin -DOPENCOLLADA_INCLUDE_DIR=/usr/include -DENABLE_BUILD_OPTIMIZATIONS=ON -DLIBXML2_INCLUDE_DIR:FILEPATH=/usr/include/libxml2 -DCMAKE_CXX_FLAGS=-lxml2 -DOCC_INCLUDE_DIR=/usr/include/opencascade -DBUILD_SHARED_LIBS=1 -DJSON_INCLUDE_DIR=/usr/include -DGLTF_SUPPORT=ON -DHDF5_SUPPORT=ON -DUSE_MMAP=ON -DGMP_LIBRARY_DIR=/usr/lib64 -DMPFR_LIBRARY_DIR=/usr/lib64 -DHDF5_LIBRARY_DIR=/usr/lib64 -DHDF5_INCLUDE_DIR=/usr/include
```

**Comment by brunopostle** [comment]
I can get a working python library if I add this to the cmake command:

    '-DCMAKE_CXX_FLAGS=-lxml2 -lGeneratedSaxParser -lMathMLSolver -lOpenCOLLADABaseUtils -lOpenCOLLADAFramework -lOpenCOLLADASaxFrameworkLoader -lOpenCOLLADAStreamWriter -lUTF -lbuffer -lftoa -lpcre'

**Comment by aothms** [comment]
Thanks, you're right. I hope https://github.com/IfcOpenShell/IfcOpenShell/commit/024a306a36466dfd80dbd2661bab7e42c279defb fixes it but I didn't yet test.

**Comment by brunopostle** [comment]
Closing, a current build works here as expected
