### ISSUE TITLE
BlenderBIM, IFCCSV - Importing csv files 

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1773]
The following error is generated every time I use the "Import CSV to IFC" and the number of objects (>700) is large.

Exact steps:

1. Select objects using eyedropper button
2. export ifc to csv
3. import the same file immediately back

`Python: Traceback (most recent call last):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 94, in set_pset_property
    property.NominalValue.wrappedValue = str(value)
AttributeError: 'NoneType' object has no attribute 'wrappedValue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 97, in set_pset_property
    property.NominalValue.wrappedValue = float(value)
ValueError: could not convert string to float: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 100, in set_pset_property
    property.NominalValue.wrappedValue = int(value)
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\csv\operator.py", line 113, in execute
    ifc_csv.Import(ifc_file)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 169, in Import
    element = IfcAttributeSetter.set_element_key(ifc_file, element, headers[i], value)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 50, in set_element_key
    IfcAttributeSetter.set_pset_property(pset, prop, value)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 102, in set_pset_property
    property.NominalValue.wrappedValue = (
AttributeError: 'NoneType' object has no attribute 'wrappedValue'

location: <unknown location>:-1`

**Comment by vulevukusej** [comment]
The problem does not present itself when only exchanging string attributes

**Comment by Moult** [comment]
Good catch. I've only ever used IfcCSV to edit existing properties, whereas it seems you are editing null properties. Very important new feature to add - last commit should fix it.
