### ISSUE TITLE
Installing BB blenderbim-211012-py39-win fails

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1793]
It seems there are some private( @Moult ?) modules that were referenced by accident in the most recent daily build?

As a result, installing the addon fails:

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\IFC_Mapping\__init__.py", line 15, in <module>
    from . import ui, prop, operators
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\IFC_Mapping\operators.py", line 2, in <module>
    from ifcopenshell.api import run
ModuleNotFoundError: No module named 'ifcopenshell'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\__init__.py", line 39, in <module>
    import blenderbim.bim
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\__init__.py", line 71, in <module>
    modules[name] = importlib.import_module(f"blenderbim.bim.module.{name}")
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'blenderbim.bim.module.lendlease'`

**Comment by Moult** [comment]
Hehehehe whoops! Indeed, just delete this line https://github.com/IfcOpenShell/IfcOpenShell/blob/dba6a8d0b43371cae1185756a23e2481e7c53b2c/src/blenderbim/blenderbim/bim/__init__.py#L24
