### ISSUE TITLE
blender import issue

### ISSUE THREAD

**Issue by aditdoshi333** [IfcOpenShell/IfcOpenShell#1921]
Hello,

I want to use blenderbim with blender 2.93 or blender 3 anything works. But when I try import blenderbim after installation I am getting the following error. I am using ubuntu 18.

```
Traceback (most recent call last):
  File "/home/adit/.config/blender/3.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/__init__.py", line 43, in <module>
    from . import ifcopenshell_wrapper
  File "/home/adit/.config/blender/3.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>
    from . import _ifcopenshell_wrapper
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/adit/.config/blender/3.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/_ifcopenshell_wrapper.so)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/adit/Downloads/blender-3.0.0-candidate+v30.d2e608733507-linux.x86_64-release/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/adit/.config/blender/3.0/scripts/addons/blenderbim/__init__.py", line 39, in <module>
    import blenderbim.bim
  File "/home/adit/.config/blender/3.0/scripts/addons/blenderbim/bim/__init__.py", line 21, in <module>
    from . import handler, ui, prop, operator, helper
  File "/home/adit/.config/blender/3.0/scripts/addons/blenderbim/bim/handler.py", line 22, in <module>
    import ifcopenshell.api.owner.settings
  File "/home/adit/.config/blender/3.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/__init__.py", line 51, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'linux/64bit/python3.9' 

```

Any help is appreciated. 
Thank you

**Comment by Moult** [comment]
@aothms might know the exact requirements from the bot build, but have you tried installing GLIBC_2.29 ?

**Comment by aothms** [comment]
IfcOpenShell v0.7 is compiled on ubuntu 20. IfcOpenShell v0.6 is compiled on ubuntu 16 (I think). These versions are fixed and our branches live quite long. So when we switch development branch the build machine is always a bit new.
