### ISSUE TITLE
BlenderBIM: Errors on Import of XERs or XMLs from P6

### ISSUE THREAD

**Issue by garylzimmer** [IfcOpenShell/IfcOpenShell#1954]
Hello, I am so extremely happy this exists and I am trying to see just how much of my workflow I can move to open source tools now! One issue I’m currently running into is that I can’t seem to import any schedule files into my project. I’m on version 3.0.0 of Blender and 0.0.211031 of BlenderBIM.
Here’s my error logs

```
bpy.ops.import_p6xer.bim(filepath="C:\\xxx.xer")
Python: Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 1117, in execute
    p6xer2ifc.execute()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\p6xer2ifc.py", line 94, in execute
    ifcCreator.create_ifc()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 36, in create_ifc
    work_schedule = self.create_work_schedule()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 45, in create_work_schedule
    return ifcopenshell.api.run(
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 46, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\sequence\add_work_schedule.py", line 26, in execute
    work_schedule.CreationDate = ifcopenshell.util.date.datetime2ifc(datetime.now(), "IfcDateTime")
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 121, in __setattr__
    self[index] = value
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 160, in __setitem__
    raise ValueError(
ValueError: Expected EntityInstance for attribute IfcWorkSchedule.CreationDate, got '2021-12-27T23:39:30.815986'

location: <unknown location>:-1
bpy.ops.import_msp.bim(filepath="C:\\xxx.xml")
Python: Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 1117, in execute
    p6xer2ifc.execute()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\p6xer2ifc.py", line 94, in execute
    ifcCreator.create_ifc()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 35, in create_ifc
    self.work_plan = ifcopenshell.api.run("sequence.add_work_plan", self.file)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 46, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\sequence\add_work_plan.py", line 21, in execute
    work_plan.CreationDate = ifcopenshell.util.date.datetime2ifc(datetime.now(), "IfcDateTime")
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 121, in __setattr__
    self[index] = value
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 160, in __setitem__
    raise ValueError(
ValueError: Expected EntityInstance for attribute IfcWorkPlan.CreationDate, got '2021-12-27T23:33:39.032755'

location: <unknown location>:-1
bpy.ops.import_p6.bim(filepath="C:\\xxx.xml")
Python: Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 1139, in execute
    msp2ifc.execute()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\msp2ifc.py", line 52, in execute
    self.parse_xml()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\msp2ifc.py", line 70, in parse_xml
    self.project["Name"] = project.find("pr:Name", self.ns).text
AttributeError: 'NoneType' object has no attribute 'text'

location: <unknown location>:-1
```

Is BlenderBIM tripping over those decimal seconds in the IfcWorkPlan.CreationDate?

**Comment by aothms** [comment]
It's the fact that the schema changed,

Item | SPF | XML | Change | Description
-- | -- | -- | -- | --
CreationDate | X | X | MODIFIED | Type changed from IfcDateTimeSelect to IfcDateTime.

Source: https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/schema/ifcprocessextension/lexical/ifcworkschedule.htm

That's why when you're file is IFC2X3 and you feed it the raw string it complains.

~~~
ValueError: Expected EntityInstance for attribute IfcWorkPlan.CreationDate, got '2021-12-27T23:33:39.032755'
~~~

You can quite easily fix this yourself, a Pull Request would be greatly appreciated if you get this to work. Inspecting your stacktrace:

~~~
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\sequence\add_work_plan.py", line 21, in execute
    work_plan.CreationDate = ifcopenshell.util.date.datetime2ifc(datetime.now(), "IfcDateTime")
~~~

Something like this should do the trick (untested), so that depending on the schema of  the file we wrap the datetime value in a typed value so that it is acceptable for the IfcDateTimeSelect

~~~
datetime_value = ifcopenshell.util.date.datetime2ifc(datetime.now(), "IfcDateTime")

if self.file.schema == "IFC2X3":
    work_plan.CreationDate = self.file.createIfcDateTime(datetime_value)    
else:
    work_plan.CreationDate = datetime_value
~~~

**Comment by Moult** [comment]
@garylzimmer g'day, I replied on the BlenderArtists forum but I'll reply here too - this error seems like your project is IFC2X3. Currently, we're only focusing on IFC4 support for 4D/5D since IFC2X3 is quite lacking in this aspect. You could patch it, but you'd run into other limitations pretty quickly in IFC2X3.

Another approach is to upgrade your project from IFC2X3 to IFC4. Ideally you'd re-create your IFC, but if not, you can use the IfcPatch "Migrate" recipe. You can do this using the Blender UI in the scene properties, using `["IFC4"]` as the arguments to the recipe.

**Comment by garylzimmer** [comment]
@Moult Thanks for the quick reply! I followed your directions and believe I have correctly upgraded to an IFC4 since there are more options available in scene properties and it says IFC4 under IFC Schema. I was able to import an XER (P6 XMLs still cause same error as the third error message above).
However, I'm still not able to generate a gantt chart. When I try, it shows a blank webpage.
Here's my config
![image](https://user-images.githubusercontent.com/10817594/147579601-161d91ce-a808-4ccd-86d6-be700ff94a02.png)

**Comment by garylzimmer** [comment]
@Moult @aothms With regards to IFC2X3 compatibility, I think I might know enough Python to help with a PR, but given Moult's comment about intentions of support, would that even work right now since I didn't see Work Plan or Work Schedule sections under scene properties whilthe project was still in IFC2X3 form?

**Comment by Moult** [comment]
@garylzimmer feel free to submit a PR. Even partial support is better than no support, and partial support eventually leads to full support :)

It looks like you've got the dates in correctly so I don't see why the gantt chart will fail. Unless we screenshare or you share your XML file I can't really debug (also sorry I'm in a bit of a holiday mode. I'm back to hacking on the 4th of Jan).

Also for this error message:

```
bpy.ops.import_p6.bim(filepath="C:\\xxx.xml")
Python: Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 1139, in execute
    msp2ifc.execute()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\msp2ifc.py", line 52, in execute
    self.parse_xml()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\msp2ifc.py", line 70, in parse_xml
    self.project["Name"] = project.find("pr:Name", self.ns).text
AttributeError: 'NoneType' object has no attribute 'text'
```

It looks like the project name can be none in XML which I didn't consider (note that I never saw a spec of the XML, I kinda reverse engineered it from sample files). Happy for a PR to consider if `project.find("pr:Name", self.ns) is None` then `self.project["Name"] = "Unnamed"` :)

Even better if there is a specification for the XML floating around somewhere that would help fix a ton of potential bugs. Ping @HassanEmam - who is the P6 implementation expert :)

**Comment by aothms** [comment]
Just a quick note that `project.findtext("pr:Name", default="Unnamed")` probably also works and saves some typing :)

**Comment by garylzimmer** [comment]
I have broken the IFC2x3 issue into it's own suggestion here
https://github.com/IfcOpenShell/IfcOpenShell/issues/1956
I will play with the XML attributes and see if I can hack it to work first.

**Comment by garylzimmer** [comment]
@HassanEmam I asked my company about P6 integration guidance and this is what they sent me:

https://docs.oracle.com/cd/F12057_01/index.html

https://docs.oracle.com/cd/F12057_01/English/Mapping_and_Schema/ms_project_import_export_data_map_xml/index.htm

https://docs.oracle.com/cd/F12057_01/English/Mapping_and_Schema/xer_import_export_data_map_project/index.htm

https://docs.oracle.com/cd/F12057_01/English/Integration_Documentation/p6_eppm_api_reference/index.html

Is any of this new to you?

**Comment by HassanEmam** [comment]
> @HassanEmam I asked my company about P6 integration guidance and this is what they sent me:
> 
> https://docs.oracle.com/cd/F12057_01/index.html
> 
> https://docs.oracle.com/cd/F12057_01/English/Mapping_and_Schema/ms_project_import_export_data_map_xml/index.htm
> 
> https://docs.oracle.com/cd/F12057_01/English/Mapping_and_Schema/xer_import_export_data_map_project/index.htm
> 
> https://docs.oracle.com/cd/F12057_01/English/Integration_Documentation/p6_eppm_api_reference/index.html
> 
> Is any of this new to you?

Hello @garylzimmer 

These are to do with EPPM which uses the APIs rather than using xml and xer files. To get reference to xer structure the link below is a useful one
https://docs.oracle.com/cd/F12057_01/English/Mapping_and_Schema/xer_import_export_data_map_project/helpmain.htm?toc.htm?97881.htm

**Comment by Moult** [comment]
@HassanEmam does P6 have a doc for their XML format? Something like an XSD perhaps?
