### ISSUE TITLE
Can't activate version 220110

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1976]
I get this error when activating the latest version - (note I am also using the latest version of ifcopenshell from IfcOpenBot):

```
Traceback (most recent call last):
  File "C:\Users\vpaji\Downloads\blender-3.0.0-windows-x64\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\__init__.py", line 39, in <module>
    import blenderbim.bim
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\__init__.py", line 21, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\handler.py", line 22, in <module>
    import ifcopenshell.api.owner.settings
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 54, in <module>
    from .file import file
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 29, in <module>
    from .entity_instance import entity_instance
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 54, in <module>
    for nm in ifcopenshell_wrapper.schema_names():
AttributeError: module 'ifcopenshell.ifcopenshell_wrapper' has no attribute 'schema_names'
```

**Comment by Moult** [comment]
Duplicate on #1959. Waiting for the bot to finish her holidays :D
