### ISSUE TITLE
BlenderBIM: New P6 XML/XER import errors

### ISSUE THREAD

**Issue by garylzimmer** [IfcOpenShell/IfcOpenShell#2017]
My potential use case for BlenderBIM is creating construction animations from IFCs according to P6 XMLs or XERs. Unfortunately, I'm still running into issues often when importing. I'm trying to do some simple testing with just creating a IFC4 project in Blender from a new scene and then importing in the scheduling files. Here are some errors I've been getting:

`Python: Traceback (most recent call last):
  File "C:\Users\gzimmer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 1139, in execute
    p6xer2ifc.execute()
  File "C:\Users\gzimmer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\p6xer2ifc.py", line 94, in execute
    ifcCreator.create_ifc()
  File "C:\Users\gzimmer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 38, in create_ifc
    self.create_tasks(work_schedule)
  File "C:\Users\gzimmer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 187, in create_tasks
    self.create_task_from_wbs(wbs, work_schedule)
  File "C:\Users\gzimmer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 211, in create_task_from_wbs
    self.create_task_from_activity(self.activities[activity_id], wbs, None)
  File "C:\Users\gzimmer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 253, in create_task_from_activity
    days=float(activity["PlannedDuration"]) / float(calendar["HoursPerDay"])
TypeError: float() argument must be a string or a number, not 'NoneType'
`

`Python: Traceback (most recent call last):
  File "C:\Users\gzimmer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 1112, in execute
    p62ifc.execute()
  File "C:\Users\gzimmer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\p62ifc.py", line 67, in execute
    self.parse_xml()
  File "C:\Users\gzimmer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\p62ifc.py", line 98, in parse_xml
    self.parse_resources_xml(root)
  File "C:\Users\gzimmer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\p62ifc.py", line 214, in parse_resources_xml
    "Type": self.RESOURCE_TYPES_MAPPING[resource.find("pr:ResourceType", self.ns).text],
KeyError: 'Nonlabor'`

**Comment by Moult** [comment]
Thanks! These bugreports are really useful since the P6 XML formats are proprietary, so we have to do a lot of guesswork to write an importer, and we only know if what we've written works based on the test files we have access to. So other files in the wild really help.

> self.create_task_from_activity(self.activities[activity_id], wbs, None) File "C:\Users\gzimmer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 253, in create_task_from_activity days=float(activity["PlannedDuration"]) / float(calendar["HoursPerDay"]) TypeError: float() argument must be a string or a number, not 'NoneType' 

This one suggests either the task has no duration or the P6 calendar has not defined an hours per day. I can't tell which without seeing your file and possibly making a human judgement on what scenario this would imply. Would it be possible to share your file? If it is private, either send to dion@thinkmoult.com or can we organise a screenshare where we can debug together?

> p62ifc.py", line 214, in parse_resources_xml "Type": self.RESOURCE_TYPES_MAPPING[resource.find("pr:ResourceType", self.ns).text], KeyError: 'Nonlabor'

Turns out "Nonlabor" is a thing and I think @HassanEmam missed this one - this seems like a generic resource category that IFC doesn't have, but from what I read online it seems to mostly be used for equipment. I've added it to the types we can detect. (Note we don't yet import resources from P6 - we have code for parsing it but it isn't yet imported).

**Comment by garylzimmer** [comment]
[CONSRTRUCTION.xer.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8005714/CONSRTRUCTION.xer.zip)

Thankfully the first error message is from an XER I found online as a test sample. (Remove the .zip from the filename, I had to add that so it would upload...)

**Comment by HassanEmam** [comment]
> [CONSRTRUCTION.xer.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8005714/CONSRTRUCTION.xer.zip)
> 
> Thankfully the first error message is from an XER I found online as a test sample. (Remove the .zip from the filename, I had to add that so it would upload...)

I had a quick look at the file and it seems to be an issue with the file format. If have primavera version 8.1 or later you can load the file and export it in the format it will work.
The issue that the xer file structure has changed a lot since the version used to create the file.

**Comment by HassanEmam** [comment]
> This one suggests either the task has no duration or the P6 calendar has not defined an hours per day. I can't tell which without seeing your file and possibly making a human judgement on what scenario this would imply. Would it be possible to share your file? If it is private, either send to [dion@thinkmoult.com](mailto:dion@thinkmoult.com) or can we organise a screenshare where we can debug together?
> 
> >

It is definitely the Calendar hours per day as the used XER is from a very old version. I can convert it to a newer version and test it.

**Comment by Moult** [comment]
Thanks @HassanEmam !

I've put in a fallback default value if this data doesn't exist in older versions.
