### ISSUE TITLE
How to create an IfcSpace and assign some entities in it?

### ISSUE THREAD

**Issue by CrossStyle** [IfcOpenShell/IfcOpenShell#2033]
Hi,

I am going to create an IfcSapce and assign some entities in it with IfcOpenshell-pyhton. For example, if I manage to get the guid for boundary walls, floor slabs, roofs and some furniture, how can I create an IfcSpace with all these components? Thank you.

**Comment by Moult** [comment]
I would recommend using the ifcopenshell api.

```
ifcopenshell.api.run("spatial.assign_container", ifc_model, product=wall, relating_structure=space)
```

**Comment by CrossStyle** [comment]
Thank you very much, my problem is solved.

**Comment by Moult** [comment]
A very minor note that typically walls aren't in a space. A wall would belong in a storey, but furniture would belong in a space.

**Comment by CrossStyle** [comment]
@Moult Are you saying that the walls are not in the space to prevent being indexed by multiple spaces? Well, how can I create a space surrounded by walls if there is no furniture?

**Comment by Moult** [comment]
@CrossStyle Spaces, walls, and storeys can exist independently of one another. You can have a space with no walls. You can have a space with no furniture in it.

The hierarchy of spaces is hierarchical - so every spatial element (site, building, storey, space, plus the new ones in IFC4.3) has exactly one location in that hierarchy.

Later on, you can indeed create non hierarchical relationships between objects and spatial elements if you want using the IfcRelReferencedInSpatialStructure.

**Comment by CrossStyle** [comment]
@Moult You means like these code below?

```
  fn = r"D:\code\bimsc\ifc_model\duplex.ifc"
  # fn = r"D:\code\bimsc\ifc_model\house5.ifc"
  # fn = r"D:\code\bimsc\ifc_model\cottage\cottage.ifc"
  ifc_model = ifcopenshell.open(fn)
  wall = ifc_model.by_guid('1CZILmCaHETO8tf3SgGEXu')
  space = ifc_model.create_entity('IfcSpace', ifcopenshell.guid.new())
  ifcopenshell.api.run("spatial.assign_container", ifc_model, product=wall, relating_structure=space)
  spaces = ifc_model.by_type('IfcSpace')
  referSpace = ifc_model.by_guid('0BTBFw6f90Nfh9rP1dl_CZ')
  relatingObject = referSpace.Decomposes[0].RelatingObject
  related_objects = []
  related_objects.append(space)

  # ifc_model.createIfcRelAggregates(ifcopenshell.guid.new(),
  #                                  referSpace.OwnerHistory,
  #                                  None,
  #                                  None,
  #                                  relatingObject,
  #                                  related_objects)

  ifc_model.createIfcRelReferencedInSpatialStructure(ifcopenshell.guid.new(),
                                   referSpace.OwnerHistory,
                                   None,
                                   None,
                                   relatingObject,
                                   related_objects)
```
However, the createIfcRelAggregates function works, and createIfcRelReferencedInSpatialStructure return the following errors.
 ```
Traceback (most recent call last):
 File "C:\ProgramData\Anaconda3\envs\bim\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-343e67b84c9a>", line 6, in <module>
    related_objects)
  File "C:\ProgramData\Anaconda3\envs\bim\lib\site-packages\ifcopenshell\file.py", line 278, in create_entity
    e[idx] = arg
  File "C:\ProgramData\Anaconda3\envs\bim\lib\site-packages\ifcopenshell\entity_instance.py", line 196, in __setitem__
    self.method_list[idx](self.wrapped_data, idx, entity_instance.unwrap_value(value))
  File "C:\ProgramData\Anaconda3\envs\bim\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4614, in setArgumentAsAggregateOfEntityInstance
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsAggregateOfEntityInstance(self, i, v)
TypeError: Attribute of type AGGREGATE OF ENTITY INSTANCE needs a python sequence of entity instances
```

**Comment by Moult** [comment]
You've got relatingObject and related_objects the wrong way around, but yes that is the gist of it :)

**Comment by CrossStyle** [comment]
@CrossStyle Oh, what a stupid mistake, hahaha. Anyway, thanks again for your help.

**Comment by aothms** [comment]
Also, see IfcRelSpaceBoundary

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op do 10 feb. 2022 04:41 schreef Neal ***@***.***>:

**Comment by CrossStyle** [comment]
@aothms Like these codes below?

```
  fn = r"D:\code\bimsc\ifc_model\duplex.ifc"
  # fn = r"D:\code\bimsc\ifc_model\house5.ifc"
  # fn = r"D:\code\bimsc\ifc_model\cottage\cottage.ifc"
  ifc_model = ifcopenshell.open(fn)
  wall = ifc_model.by_guid('1CZILmCaHETO8tf3SgGEXu')
  space = ifc_model.create_entity('IfcSpace', ifcopenshell.guid.new())
  ifcopenshell.api.run("spatial.assign_container", ifc_model, product=wall, relating_structure=space)
  spaces = ifc_model.by_type('IfcSpace')
  referSpace = ifc_model.by_guid('0BTBFw6f90Nfh9rP1dl_CZ')
  relatingObject = referSpace.Decomposes[0].RelatingObject
  related_objects = []
  related_objects.append(space)

  # ifc_model.createIfcRelAggregates(ifcopenshell.guid.new(),
  #                                  referSpace.OwnerHistory,
  #                                  None,
  #                                  None,
  #                                  relatingObject,
  #                                  related_objects)

  ifc_model.createIfcRelReferencedInSpatialStructure(
                                      ifcopenshell.guid.new(),
                                      referSpace.OwnerHistory,
                                      None,
                                      None,
                                      related_objects,
                                      relatingObject
                                      )

  ifc_model.createIfcRelSpaceBoundary(
                                      ifcopenshell.guid.new(),
                                      referSpace.OwnerHistory,
                                      None,
                                      None,
                                      related_objects,
                                      relatingObject,
                                      None,
                                      'PHYSICAL',
                                      'EXTERNAL'
                                      )
```
But I got the errors.
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\bim\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-79adfe240234>", line 9, in <module>
    'EXTERNAL'
  File "C:\ProgramData\Anaconda3\envs\bim\lib\site-packages\ifcopenshell\file.py", line 278, in create_entity
    e[idx] = arg
  File "C:\ProgramData\Anaconda3\envs\bim\lib\site-packages\ifcopenshell\entity_instance.py", line 196, in __setitem__
    self.method_list[idx](self.wrapped_data, idx, entity_instance.unwrap_value(value))
  File "C:\ProgramData\Anaconda3\envs\bim\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4609, in setArgumentAsEntityInstance
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsEntityInstance(self, i, v)
TypeError: in method 'entity_instance_setArgumentAsEntityInstance', argument 3 of type 'IfcUtil::IfcBaseClass *'
```
Don't the arguments to the function `createIfcRelSpaceBoundary` follow the rules in this [link](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcproductextension/lexical/ifcrelspaceboundary.htm)

**Comment by Moult** [comment]
@CrossStyle the fifth attribute should be the space, the sixth the element.

**Comment by CrossStyle** [comment]
@Moult Got it.

**Comment by CrossStyle** [comment]
@Moult @aothms  Sorry to bother you again. I would like to know how to specify the position and geometry of the space (for example, H, W and L) when I already know the entities that make up the boundaries of the space, e.g., wall, slab and roof.

**Comment by aothms** [comment]
The IfcSpace would typically just be represented again as an independent extrusion of a polyline. The space can be related to its boundaries on a semantic level using IfcRelSpaceBoundary but not at a geometric level.

**Comment by CrossStyle** [comment]
I referenced the [link](https://academy.ifcopenshell.org/posts/creating-a-simple-wall-with-property-set-and-quantity-information/) and managed to use the following code to create a void space.

```
O = 0., 0., 0.
X = 1., 0., 0.
Y = 0., 1., 0.
Z = 0., 0., 1.


def create_ifcaxis2placement(ifcfile, point=O, dir1=Z, dir2=X):
    point = ifcfile.createIfcCartesianPoint(point)
    dir1 = ifcfile.createIfcDirection(dir1)
    dir2 = ifcfile.createIfcDirection(dir2)
    axis2placement = ifcfile.createIfcAxis2Placement3D(point, dir1, dir2)
    return axis2placement


def create_ifclocalplacement(ifcfile, point=O, dir1=Z, dir2=X, relative_to=None):
    axis2placement = create_ifcaxis2placement(ifcfile,point,dir1,dir2)
    ifclocalplacement2 = ifcfile.createIfcLocalPlacement(relative_to,axis2placement)
    return ifclocalplacement2


def create_ifcpolyline(ifcfile, point_list):
    ifcpts = []
    for point in point_list:
        point = ifcfile.createIfcCartesianPoint(point)
        ifcpts.append(point)
    polyline = ifcfile.createIfcPolyLine(ifcpts)
    return polyline


def create_ifcextrudedareasolid(ifcfile, point_list, ifcaxis2placement, extrude_dir, extrusion):
    polyline = create_ifcpolyline(ifcfile, point_list)
    ifcclosedprofile = ifcfile.createIfcArbitraryClosedProfileDef("AREA", None, polyline)
    ifcdir = ifcfile.createIfcDirection(extrude_dir)
    ifcextrudedareasolid = ifcfile.createIfcExtrudedAreaSolid(ifcclosedprofile, ifcaxis2placement, ifcdir, extrusion)
    return ifcextrudedareasolid


if __name__ == '__main__':
    fn = r'D:\code\bimsc\ifc_model\room\test200-200-40\7.ifc'
    storey = ifc_model.by_type('IfcBuildingStorey')[0]
    storey_placement = storey.ObjectPlacement
    OwnerHistory = ifc_model.by_type('IfcOwnerHistory')[0]
    context = ifc_model.by_type("IfcGeometricRepresentationContext")[0]

    space_placement = create_ifclocalplacement(ifc_model, relative_to=storey_placement)
    polyline = create_ifcpolyline(ifc_model, [(0.0, 0.0, 0.0), (5.0, 0.0, 0.0)])
    axis_representation = ifc_model.createIfcShapeRepresentation(context, "Axis", "Curve2D", [polyline])

    extrusion_placement = create_ifcaxis2placement(ifc_model, O, Z, X)

    point_list_extrusion_area = [(0.0, -100.0, 0.0), (500.0, -100.0, 0.0), (500.0, 100.0, 0.0), (0.0, 100.0, 0.0), (0.0, -100.0, 0.0)]
    solid = create_ifcextrudedareasolid(ifc_model, point_list_extrusion_area, extrusion_placement, (0.0, 0.0, 1.0), 300.0)

    body_representation = ifc_model.createIfcShapeRepresentation(context, "Body", "SweptSolid", [solid])
    space_shape = ifc_model.createIfcProductDefinitionShape(None, None, [axis_representation, body_representation])
    space = ifc_model.create_entity('IfcSpace', ifcopenshell.guid.new())
    space.OwnerHistory = OwnerHistory
    space.Representation = space_shape
    space.ObjectPlacement = space_placement

    relatingObject = storey
    related_objects = []
    related_objects.append(space)

    ifc_model.createIfcRelAggregates(ifcopenshell.guid.new(),
                                     OwnerHistory,
                                     None,
                                     None,
                                     relatingObject,
                                     related_objects)
    ifc_model.write('spaces4.ifc')
```
However, I do not fully understand the code and I would like to know what is the role of `axis_representation` and `polyline`.
