### ISSUE TITLE
BlenderBIM: Export IFC error after importing freecad .obj file into project

### ISSUE THREAD

**Issue by Rokorps** [IfcOpenShell/IfcOpenShell#2051]
Hello,
I have modeled object in freecad and exported into obj format. 
Then I have imported obj into blender.
Then I have moved obj into coresponding spcial hierarchy folder of ifc. 

 Tried to export ifc worked.

Then I have assigned ifc class to that 3d model
got this error:
```
Python: Traceback (most recent call last):
  File "C:\Users\TELSI\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\root\operator.py", line 39, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\TELSI\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\ifc.py", line 299, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\TELSI\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\root\operator.py", line 140, in _execute
    core.assign_class(
  File "C:\Users\TELSI\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\core\root.py", line 70, in assign_class
    collector.sync(obj)
  File "C:\Users\TELSI\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\tool\collector.py", line 62, in sync
    blenderbim.core.spatial.assign_container(
  File "C:\Users\TELSI\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\core\spatial.py", line 31, in assign_container
    collector.assign(element_obj)
  File "C:\Users\TELSI\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\tool\collector.py", line 80, in assign
    object_collection = cls._get_collection(element, obj)
  File "C:\Users\TELSI\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\tool\collector.py", line 182, in _get_collection
    collection = bpy.data.collections.get(container_obj.name)
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1
```

Tried to export ifc - quite same error.

When creating new project and assigning that main ifc file to that document then adding that obj model into any spacial container - export seems to go fine.
But when i import that exported ifc into other blender window, the icon of that 3D model changes from this:
![image](https://user-images.githubusercontent.com/18393730/154565021-867404cb-306c-4dd8-a855-fed7ac4e908a.png)

to this (also model is gone):
![image](https://user-images.githubusercontent.com/18393730/154564900-7d3f366b-5f09-48a6-a489-96594731e61e.png)

Regards,
Rokas

**Comment by Rokorps** [comment]
Also same error when just a adding cube and moving it into certain folder as shown in [tutorial](https://blenderbim.org/blenderbim-tutorial.html)

**Comment by Rokorps** [comment]
Downloaded newer version of blenderBIM (developer build [blenderbim-220210](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-220210)), installed, and issue is comletely gone in all aspects.
Closing issue.
Regards,
Rokas
