### ISSUE TITLE
Cannot create display using ifcopenshell.geom.utils.initialize_display() 

### ISSUE THREAD

**Issue by garethByers** [IfcOpenShell/IfcOpenShell#2073]
I have tried using this method to create a display and have ran into errors. The first was a pixel error that required me to change something in the qtdisplay.py file but now I get an error concerning 'new_V3d_DirectionalLight'. Here is the error I get:
Traceback (most recent call last):
  File "I:\IFCopenshell\main.py", line 15, in <module>
    ifc = ifcopenshell.geom.utils.initialize_display()
  File "E:\conda\envs\pythonOCC\lib\site-packages\ifcopenshell\geom\occ_utils.py", line 97, in initialize_display
    setup()
  File "E:\conda\envs\pythonOCC\lib\site-packages\ifcopenshell\geom\occ_utils.py", line 93, in setup
    light = V3d.V3d_DirectionalLight(viewer_handle)
  File "E:\conda\envs\pythonOCC\lib\site-packages\OCC\Core\V3d.py", line 5271, in __init__
    _V3d.V3d_DirectionalLight_swiginit(self, _V3d.new_V3d_DirectionalLight(*args))
TypeError: Wrong number or type of arguments for overloaded function 'new_V3d_DirectionalLight'.
  Possible C/C++ prototypes are:
    V3d_DirectionalLight::V3d_DirectionalLight(V3d_TypeOfOrientation const,Quantity_Color const &,Standard_Boolean const)
    V3d_DirectionalLight::V3d_DirectionalLight(gp_Dir const &,Quantity_Color const &,Standard_Boolean const)

**Comment by aothms** [comment]
See here https://github.com/IfcOpenShell/IfcOpenShell/issues/1444 probably a duplicate, but hopefully some pointers so that it can be finally resolved. Would you be willing to look into this?

**Comment by garethByers** [comment]
Is there another way for me to create a section with the intention of creating a PGM from the IFC information?

**Comment by garethByers** [comment]
PGM is a file used in mapping for move base planning in gazebo. The idea is to take information from a BIM model and create a map for UGV planning

**Comment by aothms** [comment]
Well, I really can't say much about that. But the issue you encountered is due to minimal inconsistencies in OCCT API's. If you need a minimal dependency python app (ifcopenshell + pythonocc) than fixing those one or two errors is probably the quickest way forward.

**Comment by BIMvoice** [comment]
Closing as fixed. Verified end-to-end on a current setup (ifcopenshell 0.8.4 conda package + pythonocc/OCC 7.9.0): `ifcopenshell.geom.occ_utils.initialize_display()` now succeeds — window and viewer created, light setup runs, and the function returns a working `Viewer3d`. The `V3d_DirectionalLight` overload error reported here can no longer occur: the light setup was rewritten with a version guard that uses the modern `V3d_TypeOfOrientation`-based constructor on OCC ≥ 7.5 (the removed viewer-handle overload is only used on older OCC where it was valid). The probable-duplicate parent #1444 is also closed. One practical tip for viewer users: make sure your pythonocc and ifcopenshell builds target the same OCCT minor version, as mixing (e.g. 7.9.0 vs 7.9.3) can cause native crashes further along in shape display.

This comment was written with AI assistance.
