### ISSUE TITLE
How to select object by a ray caster?

### ISSUE THREAD

**Issue by CrossStyle** [IfcOpenShell/IfcOpenShell#2087]
I found a function called `select_ray`. I tried to use this function with the following code, but it brings these errors. Hopefully, someone can help me with this problem. Many thanks!

```
import ifcopenshell.geom
from OCC.Core.gp import gp_Pnt, gp_Dir

fn = r"D:\code\bimsc\ifc_model\duplex.ifc"
f = ifcopenshell.open(fn)
tree_settings = ifcopenshell.geom.settings()
tree_settings.set(tree_settings.DISABLE_OPENING_SUBTRACTIONS, True)
t = ifcopenshell.geom.tree(f, tree_settings)

a = t.select_ray(gp_Pnt(0,0,0), gp_Dir(1.0,0.0,0.0))
```
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\bim\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c67c90e046a8>", line 1, in <module>
    runfile('D:/code/bimsc/getExterior/test.py', wdir='D:/code/bimsc/getExterior')
  File "C:\Program Files\JetBrains\PyCharm 2020.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/code/bimsc/getExterior/test.py", line 108, in <module>
    a = t.select_ray(gp_Pnt(0,0,0), gp_Dir(1.0,0.0,0.0))
  File "C:\ProgramData\Anaconda3\envs\bim\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 2146, in select_ray
    return _ifcopenshell_wrapper.tree_select_ray(self, p0, d, length)
NotImplementedError: Wrong number or type of arguments for overloaded function 'tree_select_ray'.
  Possible C/C++ prototypes are:
    IfcGeom::tree::select_ray(gp_Pnt const &,gp_Dir const &,double) const
    IfcGeom::tree::select_ray(gp_Pnt const &,gp_Dir const &) const
```

**Comment by aothms** [comment]
Yes this is a bit awkard. 

C++ IfcOpenShell does not understand pythonocc, so you are not supposed to supply OCC.Core.gp.gp_Pnt.

Instead we have typemaps that create them from tuple/list of float https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcwrap/utils/typemaps_in.i#L209-L229

So try this instead

~~~python
a = t.select_ray((0.0,0.0,0.0), (1.0,0.0,0.0))
~~~

**Comment by CrossStyle** [comment]
Problem solved. Thanks again!
