### ISSUE TITLE
blenderbim-220314-py310-win fails to load

### ISSUE THREAD

**Issue by fbpyr** [IfcOpenShell/IfcOpenShell#2088]
@Moult big thx for the bb 310 builds! 🛠️ 🙂 
on win10, blender 3.1, python3.10.2, blenderbim-220314-py310-win 
blenderbim installs, but cannot load the plugin:

I just upgraded to blender 3.1. 🎉 
when upgrading to `blenderbim-220314-py310-win.zip`, plugin fails to load with: 

`ModuleNotFoundError: No module named blenderbim.core.document`
`import blenderbim.core.document as core` 
in `..\Blender\3.1\scripts\addons\blenderbim\bim\module\document` at line 24

maybe related to #2083  ?

**Comment by Moult** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/commit/57f6c072409645fb48e96cd59a017d14b1cd837f

I'm an idiot and forgot to commit

**Comment by fbpyr** [comment]
..opening ifc models fails though, with: 
```
Python: Traceback (most recent call last):
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 499, in execute
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 554, in execute
    ifc_importer.execute()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\import_ifc.py", line 210, in execute
    self.create_project()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\import_ifc.py", line 1175, in create_project
    obj = self.create_product(self.project["ifc"])
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\import_ifc.py", line 826, in create_product
    self.link_element(element, obj)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\import_ifc.py", line 1816, in link_element
    IfcStore.link_element(element, obj)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\ifc.py", line 217, in link_element
    blenderbim.bim.handler.subscribe_to(obj, "name", blenderbim.bim.handler.name_callback)
AttributeError: module 'blenderbim' has no attribute 'bim'

location: C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py:132



location: <unknown location>:-1
```

**Comment by fbpyr** [comment]
works now - seems, like I had to restart blender another time..

**Comment by fbpyr** [comment]
when also adding the import statement from the commit I get this error:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\__init__.py", line 39, in <module>
    import blenderbim.bim
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\__init__.py", line 21, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\handler.py", line 23, in <module>
    import blenderbim.tool as tool
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\tool\__init__.py", line 27, in <module>
    from blenderbim.tool.document import Document
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\tool\document.py", line 26, in <module>
    class Document(blenderbim.core.tool.Document):
AttributeError: partially initialized module 'blenderbim' has no attribute 'core' (most likely due to a circular import)


```

**Comment by Moult** [comment]
@fbpyr @benjamindahl cheers along with the files I forgot to commit in https://github.com/IfcOpenShell/IfcOpenShell/commit/57f6c072409645fb48e96cd59a017d14b1cd837f hopefully the latest commit https://github.com/IfcOpenShell/IfcOpenShell/commit/bc9e403a5812c594908aa29e5f26559fd474a704 also fixes it.

**Comment by Moult** [comment]
Hmm first @benjamindahl had an error with collector, @fbpyr had one with document, and now @benjamindahl you have an error with boundary.

Maybe it's random and not related to the actual module. Something definitely off here. I'm headed to sleep, but tomorrow I'll try to recreate again.

By the way this doesn't seem right: you can't use blenderbim-220314-py39-macos with Blender 3.1, you need the py310 version.

**Comment by benjamindahl** [comment]
> By the way this doesn't seem right: you can't use blenderbim-220314-py39-macos with Blender 3.1, you need the py310 version.

of course … tried it now with blenderbim-220314-py310-macos but same error

**Comment by Moult** [comment]
Pretty stumped. Since it works on a fresh install on Linux I also tried a fresh Windows install using the one on the releases page with no issues. If one are you are online during the Sydney timezone join the OSArch.org live chatroom and let's screenshare hopefully we can work it out.

**Comment by fbpyr** [comment]
I just updated to 220315 - for me worked flawless there!

**Comment by benjamindahl** [comment]
ok, maybe I need to build it one more time for macos arm64

**Comment by Moult** [comment]
@benjamindahl you shouldn't need to rebuild - you can just grab the latest daily build, then delete the pyd or whatever was compiled with your compiled artefacts.

**Comment by benjamindahl** [comment]
Allright. I grabbed the latest build. Installed it in Blender 3.0. Replaced the ifcopenshell folder inside the plugin site packages. Run blender with --factory-startup option and made an interesting observation. 

When I try to activate it I get different errors from the first to the second time.

**First time** (with a new issue at the end)

```
Traceback (most recent call last):
  File "/Applications/Blender 3.0.app/Contents/Resources/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/__init__.py", line 39, in <module>
    import blenderbim.bim
  File "/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/bim/__init__.py", line 21, in <module>
    from . import handler, ui, prop, operator, helper
  File "/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/bim/handler.py", line 23, in <module>
    import blenderbim.tool as tool
  File "/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/tool/__init__.py", line 21, in <module>
    from blenderbim.tool.boundary import Boundary
  File "/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/tool/boundary.py", line 23, in <module>
    from blenderbim.bim.module.geometry.helper import Helper
  File "/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/bim/module/geometry/__init__.py", line 20, in <module>
    from . import ui, prop, operator
  File "/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 37, in <module>
    from blenderbim.bim import import_ifc
  File "/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/bim/import_ifc.py", line 39, in <module>
    from blenderbim.bim.module.drawing.prop import get_diagram_scales
  File "/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/bim/module/drawing/__init__.py", line 20, in <module>
    from . import ui, prop, operator, handler, gizmos
  File "/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 42, in <module>
    from lxml import etree
ImportError: dlopen(/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/libs/site/packages/lxml/etree.cpython-39-darwin.so, 0x0002): tried: '/Users/benny/Library/Application Support/Blender/3.0/scripts/addons/blenderbim/libs/site/packages/lxml/etree.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/etree.cpython-39-darwin.so' (no such file)

```

**Second time**

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/benny/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/__init__.py", line 39, in <module>
    import blenderbim.bim
  File "/Users/benny/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/bim/__init__.py", line 21, in <module>
    from . import handler, ui, prop, operator, helper
  File "/Users/benny/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/bim/handler.py", line 23, in <module>
    import blenderbim.tool as tool
  File "/Users/benny/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/tool/__init__.py", line 21, in <module>
    from blenderbim.tool.boundary import Boundary
  File "/Users/benny/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/tool/boundary.py", line 26, in <module>
    class Boundary(blenderbim.core.tool.Boundary):
AttributeError: partially initialized module 'blenderbim' has no attribute 'core' (most likely due to a circular import)
```

**Comment by Moult** [comment]
Hey that's awesome! So basically it seems as though we also need to get a lxml built for arm.

I looked in https://pypi.org/project/lxml/#files but didn't see anything for arm unfortunately.

Alternatively, since lxml is only used for the drawing module right now, you could as a workaround disable the import in `blenderbim/bim/module/drawing/operator.py` - it won't harm the rest of the functions I believe.

**Comment by benjamindahl** [comment]
There you go!
![Bildschirmfoto 2022-03-15 um 09 22 54](https://user-images.githubusercontent.com/2698024/158336389-508a9c70-bea3-4a63-9c24-7c77e6712966.png)

![Bildschirmfoto 2022-03-15 um 09 24 31](https://user-images.githubusercontent.com/2698024/158336409-f50f20b2-6984-4f29-952d-3257962e08c5.png)
