### ISSUE TITLE
BB: error with delete, undo, and delete again

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2139]
video: https://www.dropbox.com/s/x2rtyndjb45bwpj/2022-04-14_09-31-13_Blender_%5BDDropboxTroubleshooting20220414_-_err_blender.mp4?dl=0

files: https://www.dropbox.com/sh/6oxpb1tqdvl67a7/AAB3f770uLL8P_Em4l5oizEka?dl=0

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 383, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 372, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\ifc.py", line 300, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 387, in _execute
    self.delete_ifc_object(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 336, in delete_ifc_object
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 318, in by_id
    return self[id]
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 306, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4374, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #7,202 not found

location: <unknown location>:-1


```

**Comment by Moult** [comment]
Give this commit a shot, it seems to work for me on a similar issue. Undo and redo is pretty tricky.

**Comment by theoryshaw** [comment]
seems to work on my side. Thx!
