### ISSUE TITLE
BB: AttributeError: type object 'Drawing' has no attribute 'get_reference_sheet'. Did you mean: 'get_reference_element'

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2176]
file: https://github.com/IfcOpenShell/IfcOpenShell/files/8548927/untitled.ifc.txt
video: https://www.dropbox.com/s/r6mynxzvz2r9ezx/2022-04-30_16-55-01_Blender_blender.mp4?dl=0

[blenderbim-220430-py310-win.zip](https://github.com/IfcOpenShell/IfcOpenShell/releases/download/blenderbim-220430/blenderbim-220430-py310-win.zip)
blender 3.1

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 132, in execute
    annotation_svg = self.generate_annotation(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 446, in generate_annotation
    svg_writer.write("annotation")
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 93, in write
    self.draw_annotations()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 161, in draw_annotations
    self.draw_elevation_annotation(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 447, in draw_elevation_annotation
    reference_id, sheet_id = self.get_reference_and_sheet_id_from_annotation(tool.Ifc.get_entity(obj))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 465, in get_reference_and_sheet_id_from_annotation
    sheet = tool.Drawing.get_reference_sheet(reference)
AttributeError: type object 'Drawing' has no attribute 'get_reference_sheet'. Did you mean: 'get_reference_element'?

location: <unknown location>:-1


```

**Comment by Moult** [comment]
Sorry typo
