### ISSUE TITLE
geom.settings OverflowError

### ISSUE THREAD

**Issue by stonesfcr** [IfcOpenShell/IfcOpenShell#2199]
Im trying to serialize into a gltf file, according to the example project

settings = ifcopenshell.geom.settings#(APPLY_DEFAULT_MATERIALS=True)
sr_2 = ifcopenshell.geom.serializers.gltf(v_path.joinpath(glb_file_nom), settings)

but I got this error:

settings | Error in formatting: OverflowError: in method 'IteratorSettings_get', argument 2 of type 'uint64_t'

when I run the same configuration for settings (APPLY_DEFAULT_MATERIALS=True) and then, call the variable I got this:

Traceback (most recent call last):
  File "/snap/blender/2106/3.1/python/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
  File "/home/fcr/.config/blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 857, in __repr__
    (", ".join(map(lambda x: "%s = %r" % (x, self.get(getattr(self, x))), d())))
  File "/home/fcr/.config/blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 857, in <lambda>
    (", ".join(map(lambda x: "%s = %r" % (x, self.get(getattr(self, x))), d())))
  File "/home/fcr/.config/blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 220, in get
    return _ifcopenshell_wrapper.IteratorSettings_get(self, setting)
OverflowError: in method 'IteratorSettings_get', argument 2 of type 'uint64_t'

dont really know how to solve this, thanks

**Comment by aothms** [comment]
The OverflowError is unfortunate (too many settings to fit into the 64bit bitfield apparently) but it can't be the root cause of the issue here. Because the issue is apparent only due to (as reported):

> Error in formatting: OverflowError: in method 'IteratorSettings_get', argument 2 of type 'uint64_t'

The following simple example works for me:

~~~py
settings = ifcopenshell.geom.settings(APPLY_DEFAULT_MATERIALS=True)
sr = ifcopenshell.geom.serializers.gltf('x.gltf', settings)
~~~

Somehow repr is called on the settings object and that indeed breaks currently.

Can you post the full relevant code fragment?

**Comment by stonesfcr** [comment]
Thanks for the reply, I managed to make it work, just setting a string with the name of the file, still, in the example project the storage_file_for_id function returns a path variable not a string, (which in my case seemed to be the problem), anyway, just entering a string works for me

congrats for the work and for this amazing project

**Comment by aothms** [comment]
> path variable not a string

Thanks. If you find a way to make path objects work then feel free to send in a Pull Request. As far as I can tell we simply check for string or (ifcopenshell.geom.serializers.buffer for in-memory output) seems like we could just add an isinstance check for path and convert to string transparenty for the user.

**Comment by aothms** [comment]
Edit: code is here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/geom/main.py#L264

**Comment by BIMvoice** [comment]
Resolved on `v0.8`. The `OverflowError: in method 'IteratorSettings_get', argument 2 of type 'uint64_t'` came from the settings being stored in a 64-bit integer bitfield that no longer fit all the flags. In v0.8 the settings were rewritten to be string-keyed (`settings().setting_names()` returns strings), so there is no bitfield to overflow and `repr(settings())` works in a REPL. Verified on 0.8.4. This is the same root cause tracked in #2539. Safe to close.
