### ISSUE TITLE
Error when "Remove Cost Item"

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#2206]
When click to "Remove Cost Item" with a selected cost item that has a Cost Item Quantity defined, the terminal show this error:
`location: <unknown location>:-1
Python: Traceback (most recent call last):
  File "/home/max/.config/blender/3.1/scripts/addons/blenderbim/bim/module/cost/ui.py", line 54, in draw
    self.draw_cost_schedule_ui(
  File "/home/max/.config/blender/3.1/scripts/addons/blenderbim/bim/module/cost/ui.py", line 89, in draw_cost_schedule_ui
    self.draw_editable_cost_item_ui(cost_schedule_id)
  File "/home/max/.config/blender/3.1/scripts/addons/blenderbim/bim/module/cost/ui.py", line 139, in draw_editable_cost_item_ui
    self.draw_editable_cost_item_quantities_ui()
  File "/home/max/.config/blender/3.1/scripts/addons/blenderbim/bim/module/cost/ui.py", line 153, in draw_editable_cost_item_quantities_ui
    for quantity_id in Data.cost_items[self.props.active_cost_item_id]["CostQuantities"]:
KeyError: 67
`
The error doesn't show up in blender UI but only in the terminal

**Comment by Moult** [comment]
This is an issue with the cost module still using the old fashioned UI reload approach prior to the refactor. The proper solution would be to refactor the UI of the cost module to use data classes. Would you like to chip away at this one?

**Comment by maxfb87** [comment]
Thanks for the advice!
I don't know if i can make it because the cost module is too much complicated for me at the moment.
I prefer to refactor easier modules and, when i'll be better, i could try this...
