### ISSUE TITLE
Error when trying to add new pset to object

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2230]
Context:
Fresh blender install (3.1), BB version 220608 py310

Steps to recreate issue:

1. Create new IFC4 Project
2. Add a cube and assign any ifc class
3a. Attempt to add a new property set OR
3b. Attempt to access bpy.context.active_object.PsetProperties.pset_name

Error message:
`Traceback (most recent call last):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\pset\prop.py", line 60, in getPsetNames
    psets = blenderbim.bim.schema.ifc.psetqto.get_applicable(ifc_class, pset_only=True)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\pset.py", line 67, in get_applicable
    if any_class or self.is_applicable(
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\pset.py", line 100, in is_applicable
    if ifcopenshell.util.schema.is_a(entity, applicable_class):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\schema.py", line 32, in is_a
    if entity.name_uc() == ifc_class:
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 5404, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, entity, name)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'entity' object has no attribute 'name_uc'. Did you mean: 'name_lc'?`

**Comment by vulevukusej** [comment]
I randomly picked an older version (220529) and this works as expected.

**Comment by Moult** [comment]
Yep this was a temporary bug due to an update in IfcOpenShell picked up here: https://github.com/IfcOpenShell/IfcOpenShell/commit/a96bffa34125d2fe8a1fe5bfccee55692f0a7399

There was a new build [12 hours ago](https://github.com/IfcOpenBot/IfcOpenShell/commit/cb8cfd79051cb2f7b5aa0cba233de5152aee2911) It should be fixed in the next build.
