### ISSUE TITLE
Unable to map instance to file when adding an instance to a fresh file

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2244]
```python
import ifcopenshell
f = ifcopenshell.file()
item = f.createIfcCartesianPoint([0., 0., 0.])
layer = f.createIfcPresentationLayerWithStyle("Foo", None, [item], None, True, False, False, [])
h = ifcopenshell.file()
h.createIfcProject(GlobalId=ifcopenshell.guid.new())
h.add(layer)
```

Gives:

```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 342, in add
    result = entity_instance(self.wrapped_data.add(inst.wrapped_data, -1 if _id is None else _id), self)
  File "/home/dion/.config/blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3496, in add
    return _ifcopenshell_wrapper.file_add(self, entity, id)
RuntimeError: Unable to map instance to file
```

Interestingly the bug only occurs when I create an IfcProject. Ideas?

**Comment by Moult** [comment]
Here's another potentially related issue?

```
>>> f = ifcopenshell.file()
>>> e = f.createIfcCartesianPoint([0.,0.,0.])
>>> g = ifcopenshell.file()
>>> g.createIfcProject(GlobalId=ifcopenshell.guid.new())
#1=IfcProject('3JSp301lXBZRl9AxIjoUhn',$,$,$,$,$,$,$,$)

>>> g.add(e)
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 342, in add
    result = entity_instance(self.wrapped_data.add(inst.wrapped_data, -1 if _id is None else _id), self)
  File "/home/dion/.config/blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3496, in add
    return _ifcopenshell_wrapper.file_add(self, entity, id)
RuntimeError: Invalid cast
```
