### ISSUE TITLE
AttributeError: entity instance of type 'IFC2X3.IfcPropertySingleValue' has no attribute 'PartOfPset'

### ISSUE THREAD

**Issue by MariosKoni** [IfcOpenShell/IfcOpenShell#2246]
Hello, I'm trying to this [example](https://gist.github.com/aahoo/c97248816510bf9892a2e8bdf90d1626). But when I try to execute `extPsets = extPropertySingleValue.PartOfPset`, it fails. 

```
Traceback (most recent call last):
  File "P:\ifc\src\static\examine.py", line 11, in <module>
    extPsets = extPropertySingleValue.PartOfPset
  File "C:\Users\Marios\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ifcopenshell\entity_instance.py", line 122, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC2X3.IfcPropertySingleValue' has no attribute 'PartOfPset'
```

I'm not using the file recommended because the page won't load, so I'm using another ifc model.

**Comment by aothms** [comment]
This inverse relationship has been added in IFC4 so if you use a file with 2x3 schema it's not available.

![afbeelding](https://user-images.githubusercontent.com/1096535/175034283-6e51cd64-7ec7-4322-9eb0-87ff86147cbc.png)

https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC2/HTML/link/ifcproperty.htm

You can get roughly the same behaviour with the generic `file.get_inverse(inst)`

~~~
>>> prop
#425=IfcPropertySingleValue('OccupancyZoneName',$,IfcLabel('Unit B OccupancyZoneName'),$)
>>> f
<ifcopenshell.file.file object at 0x000001AF73AE6FA0>
>>> f.get_inverse(prop)
{#24798=IfcPropertySet('36wMftOzX6lxX6ldvtaN6R',#1,'PSet_Revit_Other',$,(#72,#70,#71,#106,#1610,#1618,#428,#420,#419,#416,#425,#429,#107)), #24793=IfcPropertySet('1YbBq_I8n7JR_QQ2qj9roM',#1,'PSet_Revit_Other',$,(#72,#70,#71,#106,#1612,#1598,#428,#420,#419,#416,#425,#429,#107)), #24803=IfcPropertySet('03aGafNUb3NAdGnbIkyObe',#1,'PSet_Revit_Other',$,(#72,#70,#71,#106,#4934,#4962,#428,#420,#419,#416,#425,#429,#107)), #24805=IfcPropertySet('2MulUPfzf6Sh482c$$srJd',#1,'PSet_Revit_Other',$,(#72,#70,#71,#106,#1610,#1618,#428,#420,#419,#416,#425,#429,#107)), #24800=IfcPropertySet('3xd$ZkgcnFX8G5PmvTxMoq',#1,'PSet_Revit_Other',$,(#72,#70,#71,#106,#4999,#4946,#428,#420,#419,#416,#425,#429,#107)), #24791=IfcPropertySet('2VgJDxkXbBDfAe3g6iulp2',#1,'PSet_Revit_Other',$,(#72,#70,#71,#106,#1612,#1598,#428,#420,#419,#416,#425,#429,#107)), #24802=IfcPropertySet('0mqNYDRCT7xAL0fvGTrgCN',#1,'PSet_Revit_Other',$,(#72,#70,#71,#106,#1600,#1597,#428,#420,#419,#416,#425,#429,#107)), #24792=IfcPropertySet('3nN0dERN55av5_FW5p434B',#1,'PSet_Revit_Other',$,(#72,#70,#71,#106,#1600,#1597,#428,#420,#419,#416,#425,#429,#107)), #24809=IfcPropertySet('3fVAdALkDCLPiRoaQDxHMa',#1,'PSet_Revit_Other',$,(#72,#70,#71,#106,#4998,#5003,#428,#420,#419,#416,#425,#429,#107)), #24794=IfcPropertySet('2WZCHTy7P0ywgcU_Z02NiX',#1,'PSet_Revit_Other',$,(#72,#70,#71,#106,#5011,#5002,#428,#420,#419,#416,#425,#429,#107))}
~~~

**Comment by aothms** [comment]
Edit: these days there also easier methods to find elements with a certain property https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples#IFC_Query_Syntax

**Comment by MariosKoni** [comment]
Thank you very much @aothms for the fast replies. What I'm trying to do is to find if an element is external or not. Could you guide me to the direction I need to go in order to solve this problem?

**Comment by Moult** [comment]
Assuming you have an IsExternal property set correctly by the model author, you can get all properties by doing psets = ifcopenshell.util.element.get_psets(element), and then access it via something like psets["Pset_WallCommon"]["IsExternal"]
