### ISSUE TITLE
BB: error when assigning property 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2261]
error when assigning property 

video: https://www.dropbox.com/s/3vcujvtdeg9beqg/2022-07-04_11-18-38_Blender_%5BCUsersOwnerDesktopuntitled.blend%5D_blender.mp4?dl=0

BB 220704

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\pset\operator.py", line 38, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\ifc.py", line 372, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\pset\operator.py", line 246, in _execute
    ifcopenshell.api.run(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\pset\edit_pset.py", line 35, in execute
    new_properties = self.add_new_properties()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\pset\edit_pset.py", line 136, in add_new_properties
    **{"Name": name, "NominalValue": nominal_value},
UnboundLocalError: local variable 'nominal_value' referenced before assignment

location: <unknown location>:-1


```

**Comment by vulevukusej** [comment]
@theoryshaw sorry about that, that was an error I introduced - should be working properly again in the latest release

**Comment by vulevukusej** [comment]
@theoryshaw I committed a fix for this

**Comment by vulevukusej** [comment]
Note there's a missing comma in the BBIM release, you will need to copy this file (api/pset/edit_pset.py) with the latest version:    https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/api/pset/edit_pset.py#:~:text=else%3A-,properties.append(,),-%23TODO%2DThe%20following
