### ISSUE TITLE
IfcFile::init stalls

### ISSUE THREAD

**Issue by ysangkok** [IfcOpenShell/IfcOpenShell#228]
After commits 84813084d0502cddec7b3f8792ee58f90e31de17 (Fix/suppress signed-unsigned integer conversion warnings.) or 5e0da9725a0af2af0bc7a6876b7627fe544cae9e (ifcparse refactoring) , IfcFile::init now stalls the program.

Here is a debugger session which is why I think it is in IfcFile::init.

I tested with release and debug builds in GCC 6.3 and 7.1 on Ubuntu Zesty on x86_64.

The IFC file is here: https://hushfile.it/594021f17d75b#Fl_6L8Hv1MnWfHtOUPd97RfLrqWXiGH8IDtL5dqx

```
Program received signal SIGINT, Interrupt.
0x00007ffff33f6d71 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) up
#1  0x00007ffff33f9404 in _Unwind_RaiseException () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) 
#2  0x00007ffff3998ed7 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) 

#3  0x00005555556ac2e6 in Ifc2x3::Type::FromString (s="IFCCARTESIANPOINTLIST3D") at /home/janus/IfcOpenShell/src/ifcparse/Ifc2x3.cpp:1808
1808	    if ( it == string_map.end() ) throw IfcException("Unable to find find keyword in schema");
(gdb) 
#4  0x00005555559a82f8 in IfcParse::IfcFile::Init (this=0x7fffffffd930, s=0x555555fe3f20) at /home/janus/IfcOpenShell/src/ifcparse/IfcParse.cpp:1179
1179					entity_type = IfcSchema::Type::FromString(TokenFunc::asStringRef(token_stream[2]));
(gdb) down
#3  0x00005555556ac2e6 in Ifc2x3::Type::FromString (s="IFCCARTESIANPOINTLIST3D") at /home/janus/IfcOpenShell/src/ifcparse/Ifc2x3.cpp:1808
1808	    if ( it == string_map.end() ) throw IfcException("Unable to find find keyword in schema");
(gdb) down
#2  0x00007ffff3998ed7 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) up
#3  0x00005555556ac2e6 in Ifc2x3::Type::FromString (s="IFCCARTESIANPOINTLIST3D") at /home/janus/IfcOpenShell/src/ifcparse/Ifc2x3.cpp:1808
1808	    if ( it == string_map.end() ) throw IfcException("Unable to find find keyword in schema");
(gdb) p it
$1 = {first = "", second = Ifc2x3::Type::Ifc2DCompositeCurve}
(gdb) p string_map.end()
$2 = {first = "", second = Ifc2x3::Type::Ifc2DCompositeCurve}
(gdb) list -
1803	}
1804	
1805	Type::Enum Type::FromString(const std::string& s) {
1806	    if (string_map.empty()) InitStringMap();
1807	    std::map<std::string,Type::Enum>::const_iterator it = string_map.find(s);
1808	    if ( it == string_map.end() ) throw IfcException("Unable to find find keyword in schema");
1809	    else return it->second;
1810	}
1811	
1812	static int parent_map[] = {...};
(gdb) p s
$3 = "IFCCARTESIANPOINTLIST3D"
(gdb) down
#2  0x00007ffff3998ed7 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) 
#1  0x00007ffff33f9404 in _Unwind_RaiseException () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) 
#0  0x00007ffff33f6d71 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) up
#1  0x00007ffff33f9404 in _Unwind_RaiseException () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) 
#2  0x00007ffff3998ed7 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) 
#3  0x00005555556ac2e6 in Ifc2x3::Type::FromString (s="IFCCARTESIANPOINTLIST3D") at /home/janus/IfcOpenShell/src/ifcparse/Ifc2x3.cpp:1808
1808	    if ( it == string_map.end() ) throw IfcException("Unable to find find keyword in schema");
(gdb) 
#4  0x00005555559a82f8 in IfcParse::IfcFile::Init (this=0x7fffffffd930, s=0x555555fe3f20) at /home/janus/IfcOpenShell/src/ifcparse/IfcParse.cpp:1179
1179					entity_type = IfcSchema::Type::FromString(TokenFunc::asStringRef(token_stream[2]));
(gdb) list
1174				token_stream[2].type == IfcParse::Token_KEYWORD)
1175			{
1176				current_id = (unsigned) TokenFunc::asIdentifier(token_stream[0]);
1177				IfcSchema::Type::Enum entity_type;
1178				try {
1179					entity_type = IfcSchema::Type::FromString(TokenFunc::asStringRef(token_stream[2]));
1180				} catch (const IfcException& ex) {
1181					Logger::Message(Logger::LOG_ERROR, ex.what());
1182					continue;
1183				}		
(gdb) up
#5  0x00005555559a7e26 in IfcParse::IfcFile::Init (this=0x7fffffffd930, fn="ifc4arch.ifc") at /home/janus/IfcOpenShell/src/ifcparse/IfcParse.cpp:1128
1128		return IfcFile::Init(new IfcSpfStream(fn));
(gdb) 
#6  0x00005555555beb26 in connectWindowsToWallsByGeometry (filename=0x7fffffffe333 "ifc4arch.ifc") at design.cxx:516
516	      if (!file.Init(filename)) {
(gdb) 
#7  0x00005555555c0911 in open_file (doBuildTree=false, filename=0x7fffffffe333 "ifc4arch.ifc") at design.cxx:789
789	    connectWindowsToWallsByGeometry(filename);
(gdb) 
#8  0x00005555555c1a1e in main (argc=3, argv=0x7fffffffdfa8) at design.cxx:997
997	    open_file(false, argv[1]);
(gdb) c
Continuing.


^C
Program received signal SIGINT, Interrupt.
0x00005555559a8226 in IfcParse::IfcFile::Init (this=0x7fffffffd930, s=0x555555fe3f20) at /home/janus/IfcOpenShell/src/ifcparse/IfcParse.cpp:1170
1170		while (!stream->eof) {
(gdb) q
A debugging session is active.

	Inferior 1 [process 15429] will be killed.

Quit anyway? (y or n) y
```

**Comment by aothms** [comment]
Thanks. You are opening an IFC4 file in an executable linked against the 2x3 schema. Hence the exceptions. But you are correct, the program should continue, like it did before 5e0da97.

**Comment by ysangkok** [comment]
Oh. Why isn't it possible to build with both namespaces available? Then I could use something like https://stackoverflow.com/a/15026744/309483 to define a common subset.

**Comment by aothms** [comment]
> Oh. Why isn't it possible to build with both namespaces available?

Just a limitation of IfcOpenShell in its current form that still needs to be resolved.

> Then I could use something like https://stackoverflow.com/a/15026744/309483 to define a common subset.

That's a nifty trick to rely on a function call so that you use Argument Dependent Lookup.

Keep in mind though that compatibility between 2x3 and 4 is not that straightforward. I.e. not something I think is easily addressed by templates. The constraints on cardinalities of inverse attributes for example are quite subtle. Other aspects such as added enumeration attributes to almost all building elements are more obvious.
