### ISSUE TITLE
Selector - Error when filter_key includes "-"

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2280]
See error message below.  Is there perhaps a way to escape this character @aothms ?

```
Traceback (most recent call last):
  File "\selector.py", line 7, in <module>
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 90, in parse
    start = l.parse(query)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\lark\lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 194, in parse
    return self._parse(text, start)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\lark\parsers\earley.py", line 292, in parse
    to_scan = self._parse(stream, columns, to_scan, start_symbol)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 138, in _parse
    to_scan = scan(i, to_scan)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 115, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan)) 
lark.exceptions.UnexpectedCharacters: No terminal defined for '-' at line 1 col 23

.IfcWall[AC_Pset_Kubus-Einrichtung-2.Herstellungsjahr = ""]
                      ^

Expecting: {'DOT'}
```

**Comment by Moult** [comment]
@vulevukusej would you like to try your hand at a fix? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/selector.py#L41

**Comment by vulevukusej** [comment]
@Moult - ok, I figure I edit the regex to include "-" then.  I thought maybe there was already a baked in way to avoid the "-" without editing the code directly.

**Comment by Moult** [comment]
Yeah you'll need to edit the regex since this is a language syntax definition.

**Comment by vulevukusej** [comment]
So the following works for me now:

`pset_or_qto: /[^.= ]+/ "." /[^.= ]+/`

This will raise an error where PsetNames/Prop names have spaces in them though.  Is this something we also want to handle?

**Comment by vulevukusej** [comment]
Sorry if these seem like stupid questions, but since Psets and Props could potentially have spaces at the start, in the middle and the end, shouldn't we than advise users to adhere to a more strict syntax when using the selector, ie with no spaces (unless of course they're really there)?  For example, the user should write:

- selector.parse(ifc, '.IfcWall[Pset_WallCommon.FireRating= "2HR"]')
instead of 
- selector.parse(ifc, '.IfcWall[   Pset_WallCommon.FireRating   = "2HR"]') 
for example.

**Comment by vulevukusej** [comment]
Or require that Pset.Prop is also written within quotation marks ""?

**Comment by Moult** [comment]
Hmm, my preference would be for quotation marks to be optional and only used if they have a trailing or leading space (which I'm tempted to also not support them since it's just really bad data practice).

**Comment by aothms** [comment]
I agree. "Pset_WallCommon.FireRating" = "2HR" would look really strange, like you'd be comparing two string for equality.

**Comment by vulevukusej** [comment]
> since it's just really bad data practice
Agreed.  I'll update the regex to only support internal spaces.  Cheers!
