### ISSUE TITLE
Installation error blenderbim-220726-py310-win.zip and Blender 3.1

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2318]
Installation error blenderbim-220726-py310-win.zip and Blender 3.1

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\__init__.py", line 39, in <module>
    import blenderbim.bim
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\__init__.py", line 21, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\handler.py", line 23, in <module>
    import blenderbim.tool as tool
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\tool\__init__.py", line 45, in <module>
    from blenderbim.tool.sequence import Sequence
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\tool\sequence.py", line 29, in <module>
    class Sequence(blenderbim.core.tool.Sequence):
AttributeError: module 'blenderbim.core.tool' has no attribute 'Sequence'


```

**Comment by theoryshaw** [comment]
ping @myoualid 
maybe here? https://github.com/IfcOpenShell/IfcOpenShell/commit/beeba10b22fd66476608cb8164896cd5203abbf9
