### ISSUE TITLE
Error: can't import

### ISSUE THREAD

**Issue by PlumpMath** [IfcOpenShell/IfcOpenShell#2347]
$ python
Python 3.10.5 (main, Jun  6 2022, 12:05:50) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell

`Traceback (most recent call last):
  File "/nix/store/hx6cs2rwjl41nlxrf5jpvnsiw6kfmgjf-python3-3.10.5-env/lib/python3.10/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: libTKernel.so.7: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/hx6cs2rwjl41nlxrf5jpvnsiw6kfmgjf-python3-3.10.5-env/lib/python3.10/site-packages/ifcopenshell/__init__.py", line 54, in <module>
    from . import ifcopenshell_wrapper
  File "/nix/store/hx6cs2rwjl41nlxrf5jpvnsiw6kfmgjf-python3-3.10.5-env/lib/python3.10/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 17, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
  File "/nix/store/hx6cs2rwjl41nlxrf5jpvnsiw6kfmgjf-python3-3.10.5-env/lib/python3.10/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_ifcopenshell_wrapper')
  File "/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/hx6cs2rwjl41nlxrf5jpvnsiw6kfmgjf-python3-3.10.5-env/lib/python3.10/site-packages/ifcopenshell/__init__.py", line 62, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'linux/64bit/python3.10'`

**Comment by Moult** [comment]
It sounds like you've installed the wrong IfcOpenShell. Try this build: https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-31-v0.7.0-dc67287-linux64.zip

**Comment by PlumpMath** [comment]
This is a problem that occurs while updating nixos' python from 3.9 to 3.10. (I checked the previous versions by building them.)
It seems like we should talk to the nix community to find a solution.

**Comment by Moult** [comment]
If you want to use Python 3.9 you need to install this build: https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-39-v0.7.0-dc67287-linux64.zip

Closing as does not seem to be issue with IfcOpenShell.
