### ISSUE TITLE
BlenderBim: Can't load previously working IFC with latest Blender 3.3

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2388]
Gives this error when attempting to load Ifc:

Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\project\operator.py", line 533, in execute
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\project\operator.py", line 590, in execute
    ifc_importer.execute()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 233, in execute
    self.create_annotations()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 668, in create_annotations
    self.create_generic_elements(self.annotations)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 685, in create_generic_elements
    self.create_product(element)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 900, in create_product
    mesh = self.create_curve(element, shape)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 1832, in create_curve
    curve = bpy.data.curves.new(self.get_mesh_name(geometry), type="CURVE")
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 1769, in get_mesh_name
    representation_id = geometry.id
AttributeError: 'NoneType' object has no attribute 'id'
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\scripts\modules\bpy\ops.py:113

**Comment by Moult** [comment]
Can you share the IFC model? dion@thinkmoult.com if private

**Comment by Plae-Blue-Dot** [comment]
Hi @Moult it is a private file I've sent it via email, thanks for any help

**Comment by Moult** [comment]
So there is a more fundamental problem which has led to invalid IFC in your file (incorrect purging of geometry somewhere), but unfortunately no way to know what the root cause was. As a result, the fix is merely a cosmetic fix, but there is something nasty lurking somewhere.

**Comment by Plae-Blue-Dot** [comment]
None the less thanks for having a look, and even implementing a fix! even if it's cosmetic
