### ISSUE TITLE
Advanced Loading with Whitelist

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2396]
It seems that, along with the elements that are whitelisted (tested using GUIDS for example), IfcSpace, IfcSite and IfcAnnotation is also imported.

**Comment by Moult** [comment]
Spatial elements are (should?) filtered if to select the option to filter spatial elements.

IFC annotations aren't.

**Comment by vulevukusej** [comment]
I tried that, but I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\project\operator.py", line 590, in execute
    ifc_importer.execute()
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 250, in execute
    self.place_objects_in_collections()
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 1622, in place_objects_in_collections
    self.place_object_in_collection(self.file.by_id(ifc_definition_id), obj)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 1626, in place_object_in_collection
    self.place_object_in_decomposition_collection(element, obj)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 1643, in place_object_in_decomposition_collection
    return self.place_object_in_spatial_decomposition_collection(element, obj)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 1673, in place_object_in_spatial_decomposition_collection
    self.collections[container.GlobalId].objects.link(obj)
KeyError: '0jrZ4kmNLEyeIrSAFW8xw8'
Error: Python: Traceback (most recent call last):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\project\operator.py", line 590, in execute
    ifc_importer.execute()
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 250, in execute
    self.place_objects_in_collections()
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 1622, in place_objects_in_collections
    self.place_object_in_collection(self.file.by_id(ifc_definition_id), obj)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 1626, in place_object_in_collection
    self.place_object_in_decomposition_collection(element, obj)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 1643, in place_object_in_decomposition_collection
    return self.place_object_in_spatial_decomposition_collection(element, obj)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 1673, in place_object_in_spatial_decomposition_collection
    self.collections[container.GlobalId].objects.link(obj)
KeyError: '0jrZ4kmNLEyeIrSAFW8xw8'
```

**Comment by vulevukusej** [comment]
For reference, its a fresh install of blender 3.3 on windows, BB 220908 and its the sample ifc file: AC20-Institute-Var.ifc

**Comment by Moult** [comment]
That's a boog! Where can I find the IFC file and what filter did you specify so I can recreate it?

**Comment by vulevukusej** [comment]
https://www.ifcwiki.org/index.php?title=KIT_IFC_Examples

Query:   #2UZhzWc8v0fA0sfv__WgLn

**Comment by Moult** [comment]
So, uh. This now works :)
