### ISSUE TITLE
BB: error after `bpy.ops.bim.create_drawing()`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2411]
Following error after `bpy.ops.bim.create_drawing()`

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 160, in execute
    annotation_svg = self.generate_annotation(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 448, in generate_annotation
    self.svg_writer.create_blank_svg(svg_path).draw_annotations(annotations).save()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 160, in draw_annotations
    self.draw_text_annotation(obj, obj.location)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 532, in draw_text_annotation
    literal = literal.replace(variable, selector.get_element_value(product, variable[2:-2]) or "")
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 226, in get_element_value
    info = element.get_info()
AttributeError: 'NoneType' object has no attribute 'get_info'

```
![image](https://user-images.githubusercontent.com/507113/190218282-9b044c06-afab-47b0-877f-6a0e808cb840.png)

**Comment by theoryshaw** [comment]
whoops, probably a duplicate of [this](https://github.com/IfcOpenShell/IfcOpenShell/issues/2349) issue.
