### ISSUE TITLE
ifcopenshell qtviewer bug

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2415]
so i created a py file with this content:

```
from ifcopenshell.geom.app import application
application().start()
```

After starting the script it works and i can load a ifc file in it:

![image](https://user-images.githubusercontent.com/110968398/190580019-bd8b67c8-bbfc-4ea8-a917-11e81d5f03b6.png)

However when i move the ifc file, it closes the viewer and it throws me this error message:

```
Traceback (most recent call last):
  File "C:\Users\Martin\miniforge\miniforge\envs\pyifc\lib\site-packages\OCC\Display\qtDisplay.py", line 217, in mouseReleaseEvent
    self._display.Select(pt.x(), pt.y())
  File "C:\Users\Martin\miniforge\miniforge\envs\pyifc\lib\site-packages\ifcopenshell\geom\app.py", line 589, in HandleSelection
    v.Select()
  File "C:\Users\Martin\miniforge\miniforge\envs\pyifc\lib\site-packages\OCC\Core\AIS.py", line 5131, in Select
    return _AIS.AIS_InteractiveContext_Select(self, *args)
TypeError: Wrong number or type of arguments for overloaded function 'AIS_InteractiveContext_Select'.
  Possible C/C++ prototypes are:
    AIS_InteractiveContext::Select(AIS_NArray1OfEntityOwner const &,AIS_SelectionScheme const)
    AIS_InteractiveContext::Select(Standard_Integer const,Standard_Integer const,Standard_Integer const,Standard_Integer const,opencascade::handle< V3d_View > const &,Standard_Boolean const)
    AIS_InteractiveContext::Select(TColgp_Array1OfPnt2d const &,opencascade::handle< V3d_View > const &,Standard_Boolean const)
    AIS_InteractiveContext::Select(Standard_Boolean const)
```

**Comment by aothms** [comment]
See https://github.com/IfcOpenShell/IfcOpenShell/issues/1444

**Comment by BIMvoice** [comment]
Root cause: `AIS_InteractiveContext.Select()` has no zero-argument overload in the SWIG bindings, the C++ default for `theToUpdateViewer` doesn't carry through to Python. Fixed in #8588 with `v.Select(True)`, matching pythonocc-core's own reference `OCCViewer.Select()` implementation. Live-verified against pythonocc-core 7.9.0, the exact traceback reproduces with `.Select()` and resolves with `.Select(True)`, and the single-bool overload is stable across OCCT 7.8 through 7.9 so no version branching is needed here (unlike the related #2500).

This comment was written with the assistance of an AI tool.
