### ISSUE TITLE
ifcopenshell-python - get all used types of file (by_type())

### ISSUE THREAD

**Issue by johannesmichael** [IfcOpenShell/IfcOpenShell#244]
To get all used types (entities) in one request would be great (by_type())

**Comment by aothms** [comment]
~~~
>>> import ifcopenshell
>>> f = ifcopenshell.open()
>>> f.createIfcCartesianPoint((0.,0.))
#1=IfcCartesianPoint((0.,0.))
>>> f.types()
('IfcCartesianPoint',)
>>> f.types_with_super()
('IfcCartesianPoint', 'IfcGeometricRepresentationItem', 'IfcPoint', 'IfcRepresentationItem')
~~~

**Comment by halmsx** [comment]
hi. sorry to reopen this. i opened existing file and tried both types() and types_with_super() and getting errors...

`
f = ifcopenshell.open(xxxxx.ifc)
print(f.types())`

`
Traceback (most recent call last):
  File "checker-items.py", line 21, in <module>
    print(f.types())
  File "/Users/halms/Sites/checker/python/ifcopenshell/file.py", line 39, in __getattr__
    else: return getattr(self.wrapped_data, attr)
  File "/Users/halms/Sites/checker/python/ifcopenshell/ifcopenshell_wrapper.py", line 1200, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, file, name)
  File "/Users/halms/Sites/checker/python/ifcopenshell/ifcopenshell_wrapper.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/Users/halms/Sites/checker/python/ifcopenshell/ifcopenshell_wrapper.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'`
