### ISSUE TITLE
Error when the BB plugin is enabled in preferences

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2449]
as of..
d4d923e51b80deae996ee58dd89caad8c2ce263b

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\__init__.py", line 39, in <module>
    import blenderbim.bim
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\__init__.py", line 21, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\handler.py", line 23, in <module>
    import blenderbim.tool as tool
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\tool\__init__.py", line 41, in <module>
    from blenderbim.tool.qto import Qto
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\tool\qto.py", line 26, in <module>
    from blenderbim.bim.module.pset.qto_calculator import QtoCalculator
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\pset\__init__.py", line 20, in <module>
    from . import ui, prop, operator
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\pset\operator.py", line 34, in <module>
    from blenderbim.bim.module.pset.qto_calculator import QtoCalculator
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\pset\qto_calculator.py", line 24, in <module>
    from shapely.geometry import Polygon
ModuleNotFoundError: No module named 'shapely'

```

**Comment by theoryshaw** [comment]
ping @vulevukusej :)

**Comment by Moult** [comment]
Are you working from git or downloading the build zip? If from git you'll need to manually add that new dependency.

**Comment by vulevukusej** [comment]
my commit was barely an hour old :( - haha.  @Moult Can you let me know what I need to do to fix this?

**Comment by Moult** [comment]
Nothing to fix, he's on git so he'll need to manually download the shapely file from the URL in the make file (see commit) and extract and copy the shapely folder into addons blenderbim lib site packages.

**Comment by theoryshaw** [comment]
@Moult in general, is there an easy way to tell if i need to update my `libs` folder?

**Comment by Moult** [comment]
Whenever someone edits the make file. Usually you'll get a critical error as a friendly reminder :)

**Comment by theoryshaw** [comment]
you know i couldn't wait. ;)
Along with the downloading the .tar file, i also had to download the [geos_c.dll](https://stackoverflow.com/questions/56813083/oserror-could-not-find-geos-c-dll-or-load-any-of-its-variants) file and locate in `Blender Foundation\Blender\3.2\scripts\addons\blenderbim\libs\site\packages\shapely\DLLs`

Thanks Guys.

![image](https://user-images.githubusercontent.com/507113/192816562-7342cfd6-12d0-4cd5-829e-e08ecf3ed410.png)
