### ISSUE TITLE
validate.py invalid json

### ISSUE THREAD

**Issue by cadgiru** [IfcOpenShell/IfcOpenShell#2481]
In some cases validate.py will output an invalid json 
```
[
    {
        "level": "error",
        "message": "With attribute:
    <attribute RelatedObjects: <set [1:?] of <entity IfcObject>>>
Value:
    ()
Not valid
",
        "instance": "#519317=IfcRelDefinesByProperties('3rCS_gFoz568TMiSmvkAlE',#21,$,$,(),#519316)"
    },
…
…
...
     {
        "level": "error",
        "message": "With attribute:
    <attribute RelatedObjects: <set [1:?] of <entity IfcObject>>>
Value:
    ()
Not valid
",
        "instance": "#100621=IfcRelDefinesByProperties('3lPiKDU$TA3PnHD1bhlSIy',#21,$,$,(),#100607)"
    }
]
```

**Comment by aothms** [comment]
We just "JSON lines", e.g newline separated python json.dumps(). I'd be highly surprised if there are validity errors in python's native json module. What is exactly the issue and where does it fail.

**Comment by cadgiru** [comment]
An example of crash...
```
PYTHON INTERACTIVE CONSOLE 3.10.2 (main, Apr 26 2022, 10:33:12) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]

Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, blf, mathutils
Convenience Imports:   from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data

>>> f='/home/peter/01testvalcrash.ifc'
>>> ifc = ifcopenshell.open(f)
>>> json_logger = ifcopenshell.validate.json_logger()
>>> ifcopenshell.validate.validate(ifc, json_logger)
Traceback (most recent call last):
  File "/home/peter/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/validate.py", line 367, in validate
    assert_valid_inverse(attr, val, schema)
  File "/home/peter/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/validate.py", line 133, in assert_valid_inverse
    raise ValidationError(
ifcopenshell.validate.ValidationError: With inverse:
    PlacesObject : SET [1:1] OF IfcProduct FOR ObjectPlacement
Value:
    [
      1. #717=IfcAnnotation('05ycQLdyT0hBFngr$YuEct',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036639)
      2. #718=IfcAnnotation('0oNp3ACnn1LegqcfS9iecz',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036649)
      3. #719=IfcAnnotation('1vsAhfSdDF8Q3chkHyDV5S',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036659)
      4. #720=IfcAnnotation('1qvb59DBb9URx4eYx0fOjq',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036669)
      5. #721=IfcAnnotation('36Le1lycDEie0vi4EKw2lH',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036679)
      6. #722=IfcAnnotation('2Yf4zIT8z8OeH6Mqx27Ivu',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036689)
      7. #723=IfcAnnotation('2BDAU0koTBCPMVA4utpAvd',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036699)
      8. #724=IfcAnnotation('3oVDnBMNj8lfLej79z4NhJ',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036709)
      9. #725=IfcAnnotation('23fIaCFij38OEHDh_QleFE',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036719)
      10. #726=IfcAnnotation('0oJp_T6kzBUhV$HlRbqa6R',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036729)
      11. #727=IfcAnnotation('0bGqxRbNLAHAvjqSU8DT01',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036739)
      12. #728=IfcAnnotation('2_ZlMdR7f5tQe90UtwFVQH',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036749)
      13. #729=IfcAnnotation('2AGOeJj5v5JfoTIcsRLoW1',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036759)
      14. #730=IfcAnnotation('29f9nfJd17HvLIIb3d1HUv',#21,'Filled region:Detail Filled Region:12686848',$,'Filled region:Bonava_Light_Green 40%',#1036629,#1036771)
    ]
Not valid


During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/peter/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/validate.py", line 370, in validate
    logger.error(str(e))
  File "/home/peter/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/validate.py", line 58, in log
    log_entry_type(level, message % args, kwargs.get("instance"))._asdict()
TypeError: not enough arguments for format string
```
if after the 'crash' , I enter 
```
>>> json_logger.statements
[{'level': 'error', 'message': 'Attribute <entity IfcFurnitureType>.<attribute AssemblyPlace: <enumeration IfcAssemblyPlaceEnum: (FACTORY, NOTDEFINED, SITE)>> not optional', 'instance': #1678646=IfcFurnitureType('37XSn_slXAvffsphPea6qu',#21,'Skap_bonava_m_symbol:Skap_bonava',$,$,(#1678647,#1678648),(#1678645),'12744036',$,$)},
.........
.............
 {'level': 'error', 'message': 'Attribute <entity IfcFurnitureType>.<attribute AssemblyPlace: <enumeration IfcAssemblyPlaceEnum: (FACTORY, NOTDEFINED, SITE)>> not optional', 'instance': #1074425=IfcFurnitureType('2bZHEvI$v0buAAOw7RyFj2',#21,'Kjøkkenbenk_L:Kjøkkenbenk_L',$,$,(#1074426,#1074427),(#1074423,#1074424),'1352416',$,$)}]

>>> print(f"Length json_logger.statements : {len(json_logger.statements)}")
Length json_logger.statements : 53
```

**Comment by aothms** [comment]
Ah interesting, is this because of the % in the instance string which is being picked up by the logger API as a placeholder for variable substitution? Wouldn't have thought of that, interesting :)

**Comment by BIMvoice** [comment]
This is resolved on the current `v0.8.0`. The `--json` CLI path now serializes each statement with `json.dumps` (`validate.py`, the `for x in logger.statements: print(json.dumps(x, default=conv))` loop), which escapes the newlines inside a `message` as `\\n`, so the output is valid JSON lines.

Verified headless: a file with an invalid `IfcRelDefinesByProperties` (empty `RelatedObjects`) produces messages that do contain raw newlines, and every `json.dumps(statement)` row parses cleanly with `json.loads`. The invalid output in the report (a pretty-printed array with unescaped newlines) came from an older serialization path that predates the `json.dumps` approach. Safe to close.

**Comment by BIMvoice** [comment]
Closing since this is verified fixed in current code (independently re-checked just now, no regression since our note last week). Please reopen if something's still broken here.

**Comment by Moult** [comment]
Reopening for human to verify
