### ISSUE TITLE
[api] root.create_entity can't create an IfcVirtualElement

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2507]
This bug is new since 13th October:

```
$ python
Python 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell.api
>>> file = ifcopenshell.file()
>>> ifcopenshell.api.run("root.create_entity", file,ifc_class="IfcVirtualElement",name="My Virtual Element")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.10/site-packages/ifcopenshell/api/__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "/usr/lib64/python3.10/site-packages/ifcopenshell/api/root/create_entity.py", line 60, in execute
    self.handle_4_defaults(element)
  File "/usr/lib64/python3.10/site-packages/ifcopenshell/api/root/create_entity.py", line 82, in handle_4_defaults
    if not element.PredefinedType:
  File "/usr/lib64/python3.10/site-packages/ifcopenshell/entity_instance.py", line 137, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcVirtualElement' has no attribute 'PredefinedType'
```

**Comment by aothms** [comment]
This is also causing the tests to fail since 4d ago https://github.com/IfcOpenShell/IfcOpenShell/actions/runs/3248123193/jobs/5329739370#step:7:604
