### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2508]
This file. 
https://github.com/buildingSMART/Sample-Test-Files/blob/master/IFC%202x3/SDK%20-%20S1/1.%20IFC%20models%20-%20modellen/02%20Building%20site%20design-%20Bouwplaatsinrichting/E-S1-AAN-Mass%20model%20-%20Massamodel%20S1.ifc

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\project\operator.py", line 537, in execute
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py", line 115, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\project\operator.py", line 594, in execute
    ifc_importer.execute()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\import_ifc.py", line 232, in execute
    self.parse_native_elements()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\import_ifc.py", line 358, in parse_native_elements
    if self.is_native(element):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\import_ifc.py", line 372, in is_native
    if self.is_native_swept_disk_solid(representations):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\import_ifc.py", line 406, in is_native_swept_disk_solid
    items[0].is_a("IfcSweptDiskSolid")
IndexError: list index out of range
Location: C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py:115

```

**Comment by aothms** [comment]
The file is invalid, most likely exactly the cause of this:

```
For instance:
    #17=IfcShapeRepresentation(#11,'Body','Brep',())
                                                 ^^
With attribute:
    <attribute Items: <set [1:?] of <entity IfcRepresentationItem>>>
Value:
    ()
Not valid
```

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/import_ifc.py#L402-L411

`if len(items) == 1:` should be tested in both if branches

**Comment by Moult** [comment]
Thanks for reporting upstream :)
