### ISSUE TITLE
A question about IfcPatch (ExtractElements) with Psets

### ISSUE THREAD

**Issue by avicomartin** [IfcOpenShell/IfcOpenShell#2548]
I'm testing IfcPatch to extract elements based on Pset Properties but without success.
Te data I use (inside Blender Bim) in the IFC_Quality_Control -> IFC_Patch panel is:
Recipes: ExtractElements
IFC Path Imput IFC: The ifc file from I want data
IFC Path Output IFC: The ifc file where I want save data
query: .IfcElement[Pset_Name.Pset_Property *= "My criteria"] (In my case .IfcElement[ACAT_Identificacio.ACAT_P3-Tipusnom *= "GBB"]
I use *= because I want all elements with "GBB" in that property, but this query doesn't work.
I I use .IfcElement[Name *= "GBB"] as query work fine and get expected elements.
The sintaxis for "Pset_Name.Pset_Properties" I use is based in previous test in IFC CSV tool and work fine. Looking the code, it seem csv analize Psets but ExtracElements.py not.

I'm trying to attach the ifc file but is a very big boy (195 MB, 33 Mb compressed) and probably are not allowed.

Other test I have done (linux environment with blender 3.2.2 and blenderbim 220516) show an this error message, related to a character "-" in the pset property name, so maybe is a problem with the name parser:

Python: Traceback (most recent call last):
  File "/home/antonio/.config/blender/3.2/scripts/addons/blenderbim/bim/module/patch/operator.py", line 82, in execute
    ifcpatch.execute(
  File "/home/antonio/.config/blender/3.2/scripts/addons/blenderbim/libs/site/packages/ifcpatch/__init__.py", line 45, in execute
    patcher.patch()
  File "/home/antonio/.config/blender/3.2/scripts/addons/blenderbim/libs/site/packages/ifcpatch/recipes/ExtractElements.py", line 47, in patch
    for element in selector.parse(self.file, self.query):
  File "/home/antonio/.config/blender/3.2/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/selector.py", line 90, in parse
    start = l.parse(query)
  File "/home/antonio/.config/blender/3.2/scripts/addons/blenderbim/libs/site/packages/lark/lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "/home/antonio/.config/blender/3.2/scripts/addons/blenderbim/libs/site/packages/lark/parser_frontends.py", line 194, in parse
    return self._parse(text, start)
  File "/home/antonio/.config/blender/3.2/scripts/addons/blenderbim/libs/site/packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/home/antonio/.config/blender/3.2/scripts/addons/blenderbim/libs/site/packages/lark/parsers/earley.py", line 292, in parse
    to_scan = self._parse(stream, columns, to_scan, start_symbol)
  File "/home/antonio/.config/blender/3.2/scripts/addons/blenderbim/libs/site/packages/lark/parsers/xearley.py", line 138, in _parse
    to_scan = scan(i, to_scan)
  File "/home/antonio/.config/blender/3.2/scripts/addons/blenderbim/libs/site/packages/lark/parsers/xearley.py", line 115, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan))
lark.exceptions.UnexpectedCharacters: No terminal defined for '-' at line 1 col 39

.IfcElement[ACAT_Identificacio.ACAT_I3-Tipusnom *= "GBB"]
                                      ^

Expecting: {'__ANON_6', '__ANON_3', 'RSQB', 'BANG', 'MORETHAN', 'EQUAL', '__ANON_5', 'LESSTHAN', '__ANON_4'}

Note: Character ^ in original error message is exactly under "-" character (between 3 an T characters)

**Comment by Moult** [comment]
Do you see this line of code in `/home/antonio/.config/blender/3.2/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/selector.py` ?


```
pset_or_qto: /[^\\W][^.=<>]*[^\\W]/ "." /[^\\W][^.=<>]*[^\\W]/
```

**Comment by avicomartin** [comment]
The lines I see are:

                    filter: "[" filter_key (comparison filter_value)? "]"
                    filter_key: WORD | pset_or_qto
                    filter_value: ESCAPED_STRING | SIGNED_FLOAT | SIGNED_INT | BOOLEAN | NULL
                    pset_or_qto: /[A-Za-z0-9_]+/ "." /[A-Za-z0-9_]+/

I attach another ifc sample with the same issue (objects modeling installations in a 5 km road tram)
the query I try to run is:

.IfcElement[ACAT_Identificacio.ACAT_I3-Tipusnom *= "PHN1"]

to extract streetlights 
[MB15053_L1_OBEX_RP_INS.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9893977/MB15053_L1_OBEX_RP_INS.ifc.zip)

**Comment by Moult** [comment]
OK that means that you have an outdated version, this was likely already fixed a while ago and available in the unstable release: [https ](https://blenderbim.org/docs/devs/installation.html#unstable-installation)

**Comment by avicomartin** [comment]
Updating to blenderbim-221030 worked but upgrading to blender-3.3.1. With blender-3.2.2 this daily build show errors when try to activate.

**Comment by Moult** [comment]
@avicomartin indeed you caught us at a bad time :) https://github.com/IfcOpenShell/IfcOpenShell/pull/2544#issuecomment-1296101625 there is a temporary incompatibility with the unstable version and 3.2.
