### ISSUE TITLE
[ifcopenshell-python] is there already support for python 3.11?

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2551]
just a little question, because https://www.python.org/downloads/release/python-3110/ is released :)

**Comment by aothms** [comment]
The openbot now also produces 3.11 builds. Please test. New build came through https://github.com/IfcOpenBot/IfcOpenShell/commit/d97594df9645b74f469de47edf3b93cc6c4b4539#comments

**Comment by Martin15135215** [comment]
so first i tested the daily conda build:

```
Python 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
Traceback (most recent call last):
  File "C:\Users\martin\miniforge\miniforge\envs\test11\Lib\site-packages\ifcopenshell\__init__.py", line 54, in <module>
    from . import ifcopenshell_wrapper
  File "C:\Users\martin\miniforge\miniforge\envs\test11\Lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 10, in <module>
    from . import _ifcopenshell_wrapper
ImportError: DLL load failed while importing _ifcopenshell_wrapper: Die angegebene Prozedur wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\martin\miniforge\miniforge\envs\test11\Lib\site-packages\ifcopenshell\__init__.py", line 62, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.11'
>>>
```


So for the second test, i just changed the ifcopenshell package in the site-packages folder with one from the ifcopenbot:

```
Python 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> ifcopenshell.version
'v0.7.0-d97594df'
>>> model = ifcopenshell.file()
>>>
```

The IfcOpenBot Version does function 🎉

**Comment by Andrej730** [comment]
Testing it too, no errors so far.

**Comment by Martin15135215** [comment]
Hi @Krande 

I am using [miniforge ](https://github.com/conda-forge/miniforge)<- there is conda-forge channel the default

1. I did use a fresh conda env to test

This is the shell code i used:
```
conda create --name test11 python=3.11.0
conda activate test11
conda install -c ifcopenshell -c conda-forge ifcopenshell

```

2. I now did `conda clean --all`:

![image](https://user-images.githubusercontent.com/110968398/202483940-dcd05e51-37bb-42d7-92d6-f6f974f22cec.png)

I did run now this shell command:

```
conda create --name test2 python=3.11.0
conda activate test2
conda install -c ifcopenshell -c conda-forge ifcopenshell
```

I still get this ImportError Message:

```
Python 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
Traceback (most recent call last):
  File "C:\Users\martin\miniforge\miniforge\envs\test2\Lib\site-packages\ifcopenshell\__init__.py", line 54, in <module>
    from . import ifcopenshell_wrapper
  File "C:\Users\martin\miniforge\miniforge\envs\test2\Lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 10, in <module>
    from . import _ifcopenshell_wrapper
ImportError: DLL load failed while importing _ifcopenshell_wrapper: Die angegebene Prozedur wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\martin\miniforge\miniforge\envs\test2\Lib\site-packages\ifcopenshell\__init__.py", line 62, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.11'
```

3. I did now run this shell command:

```python 
conda create --name test3 python=3.11.0
conda activate test3
conda install -c conda-forge ifcopenshell
```

And the test here was successful 🎉:

```
Python 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:09:06) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> ifcopenshell.version
'0.7.0'
>>>
```

The big difference i saw between daily-build und conda-forge build was how much stuff was being downloaded:

Daily-Build:
```
(test2) C:\Users\martin>conda install -c ifcopenshell -c conda-forge ifcopenshell
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\martin\miniforge\miniforge\envs\test2

  added / updated specs:
    - ifcopenshell


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ifcopenshell-0.7.0         |  py311h82bb817_0       110.4 MB  ifcopenshell
    python_abi-3.11            |          2_cp311           5 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       110.4 MB

The following NEW packages will be INSTALLED:

  boost-cpp          conda-forge/win-64::boost-cpp-1.78.0-h9f4b32c_1 None
  cgal-cpp           conda-forge/win-64::cgal-cpp-5.5.1-had41446_0 None
  eigen              conda-forge/win-64::eigen-3.4.0-h2d74725_0 None
  expat              conda-forge/win-64::expat-2.5.0-h1537add_0 None
  fontconfig         conda-forge/win-64::fontconfig-2.14.1-hbde0cde_0 None
  freetype           conda-forge/win-64::freetype-2.12.1-h546665d_0 None
  hdf5               conda-forge/win-64::hdf5-1.12.2-nompi_h57737ce_100 None
  ifcopenshell       ifcopenshell/win-64::ifcopenshell-0.7.0-py311h82bb817_0 None
  krb5               conda-forge/win-64::krb5-1.19.3-hc8ab02b_0 None
  libcurl            conda-forge/win-64::libcurl-7.86.0-heaf79c2_1 None
  libiconv           conda-forge/win-64::libiconv-1.17-h8ffe710_0 None
  libpng             conda-forge/win-64::libpng-1.6.38-h19919ed_0 None
  libssh2            conda-forge/win-64::libssh2-1.10.0-h9a1e1f7_3 None
  libxml2            conda-forge/win-64::libxml2-2.10.3-hc3477c8_0 None
  mpfr               conda-forge/win-64::mpfr-4.1.0-h8d14728_1 None
  mpir               conda-forge/win-64::mpir-3.0.0-he025d50_1002 None
  nlohmann_json      conda-forge/win-64::nlohmann_json-3.11.2-h39d44d4_0 None
  occt               conda-forge/win-64::occt-7.4.0-h823b557_3 None
  python_abi         conda-forge/win-64::python_abi-3.11-2_cp311 None
  tbb                conda-forge/win-64::tbb-2020.2-h2d74725_4 None
  zstd               conda-forge/win-64::zstd-1.5.2-h7755175_4 None


Proceed ([y]/n)?
```

Conda-forge Build:

```
(test3) C:\Users\martin>conda install -c conda-forge ifcopenshell
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\martin\miniforge\miniforge\envs\test3

  added / updated specs:
    - ifcopenshell


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aiohttp-3.8.3              |  py311ha68e1ae_1         524 KB  conda-forge
    aiosignal-1.3.1            |     pyhd8ed1ab_0          12 KB  conda-forge
    async-timeout-4.0.2        |     pyhd8ed1ab_0           9 KB  conda-forge
    ffmpeg-5.1.2               | gpl_h6a9407d_103        13.0 MB  conda-forge
    font-ttf-dejavu-sans-mono-2.37|       hab24e00_0         388 KB  conda-forge
    font-ttf-inconsolata-3.000 |       h77eed37_0          94 KB  conda-forge
    font-ttf-source-code-pro-2.038|       h77eed37_0         684 KB  conda-forge
    font-ttf-ubuntu-0.83       |       hab24e00_0         1.9 MB  conda-forge
    fonts-conda-ecosystem-1    |                0           4 KB  conda-forge
    fonts-conda-forge-1        |                0           4 KB  conda-forge
    freeimage-3.18.0           |      h064cf08_10         689 KB  conda-forge
    frozenlist-1.3.3           |  py311ha68e1ae_0          40 KB  conda-forge
    gl2ps-1.4.2                |       h0597ee9_0          74 KB  conda-forge
    glew-2.1.0                 |       h39d44d4_2         941 KB  conda-forge
    gst-plugins-base-1.21.1    |       h001b923_1         2.3 MB  conda-forge
    gstreamer-1.21.1           |       h6b5321d_1         2.1 MB  conda-forge
    hdf5-1.12.2                |nompi_h2a0e4a3_100        24.0 MB  conda-forge
    icu-70.1                   |       h0e60522_0        17.0 MB  conda-forge
    ifcopenshell-v0.7.0a6      |  py311h08ab057_3        92.2 MB  conda-forge
    imath-3.1.6                |       h1758832_0         178 KB  conda-forge
    intel-openmp-2022.1.0      |    h57928b3_3787         3.7 MB  conda-forge
    jpeg-9e                    |       h8ffe710_2         366 KB  conda-forge
    jsoncpp-1.9.5              |       h2d74725_1         532 KB  conda-forge
    jxrlib-1.1                 |       h8ffe710_2         620 KB  conda-forge
    krb5-1.19.3                |       h1176d77_0         847 KB  conda-forge
    lcms2-2.12                 |       h2a16943_0         882 KB  conda-forge
    lerc-4.0.0                 |       h63175ca_0         190 KB  conda-forge
    libblas-3.9.0              |     16_win64_mkl         5.6 MB  conda-forge
    libcblas-3.9.0             |     16_win64_mkl         5.6 MB  conda-forge
    libclang-15.0.4            |default_h77d9078_0         144 KB  conda-forge
    libclang13-15.0.4          |default_h77d9078_0        25.9 MB  conda-forge
    libdeflate-1.14            |       hcfcfb64_0          73 KB  conda-forge
    liblapack-3.9.0            |     16_win64_mkl         5.6 MB  conda-forge
    libogg-1.3.4               |       h8ffe710_1          34 KB  conda-forge
    libraw-0.20.2              |       hee1bdec_1         1.0 MB  conda-forge
    libssh2-1.10.0             |       h680486a_3         228 KB  conda-forge
    libtheora-1.1.1            |    h8d14728_1005         201 KB  conda-forge
    libtiff-4.4.0              |       h8e97e67_4         1.1 MB  conda-forge
    libvorbis-1.3.7            |       h0e60522_0         267 KB  conda-forge
    libwebp-base-1.2.4         |       h8ffe710_0         328 KB  conda-forge
    libzip-1.9.2               |       hfed4ece_1         145 KB  conda-forge
    loguru-0.6.0               |  py311h1ea47a8_2         113 KB  conda-forge
    lz4-c-1.9.3                |       h8ffe710_1         135 KB  conda-forge
    mkl-2022.1.0               |     h6a75c08_874       182.7 MB  conda-forge
    multidict-6.0.2            |  py311ha68e1ae_2          53 KB  conda-forge
    numpy-1.23.4               |  py311h95d790f_1         7.4 MB  conda-forge
    occt-7.6.3                 |       h6c7cb8d_1        26.7 MB  conda-forge
    openexr-3.1.5              |       hab3b255_0         1.4 MB  conda-forge
    openjpeg-2.5.0             |       hc9384bd_1         256 KB  conda-forge
    proj-9.1.0                 |       h3863b3b_0         2.8 MB  conda-forge
    pugixml-1.11.4             |       h0e60522_0         211 KB  conda-forge
    python-3.11.0              |h9a09f29_0_cpython        18.9 MB  conda-forge
    qt-main-5.15.6             |       h9c3277a_1        68.8 MB  conda-forge
    rapidjson-1.1.0            |    ha925a31_1002         104 KB  conda-forge
    tbb-2021.7.0               |       h91493d7_0         174 KB  conda-forge
    tbb-devel-2021.7.0         |       h91493d7_0         1.1 MB  conda-forge
    typing-extensions-4.4.0    |       hd8ed1ab_0           8 KB  conda-forge
    vtk-9.2.2                  |qt_py311h2c833bd_204        36.0 MB  conda-forge
    win32_setctime-1.1.0       |     pyhd8ed1ab_0           7 KB  conda-forge
    wslink-1.9.1               |     pyhd8ed1ab_0          26 KB  conda-forge
    x264-1!164.3095            |       h8ffe710_2        1017 KB  conda-forge
    x265-3.5                   |       h2d74725_3         5.3 MB  conda-forge
    yarl-1.8.1                 |  py311ha68e1ae_0          91 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       562.6 MB

The following NEW packages will be INSTALLED:

  aiohttp            conda-forge/win-64::aiohttp-3.8.3-py311ha68e1ae_1 None
  aiosignal          conda-forge/noarch::aiosignal-1.3.1-pyhd8ed1ab_0 None
  aom                conda-forge/win-64::aom-3.5.0-h63175ca_0 None
  async-timeout      conda-forge/noarch::async-timeout-4.0.2-pyhd8ed1ab_0 None
  attrs              conda-forge/noarch::attrs-22.1.0-pyh71513ae_1 None
  boost-cpp          conda-forge/win-64::boost-cpp-1.78.0-h9f4b32c_1 None
  cgal-cpp           conda-forge/win-64::cgal-cpp-5.5.1-had41446_0 None
  charset-normalizer conda-forge/noarch::charset-normalizer-2.1.1-pyhd8ed1ab_0 None
  colorama           conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0 None
  curl               conda-forge/win-64::curl-7.86.0-heaf79c2_1 None
  double-conversion  conda-forge/win-64::double-conversion-3.2.0-h63175ca_1 None
  eigen              conda-forge/win-64::eigen-3.4.0-h2d74725_0 None
  expat              conda-forge/win-64::expat-2.5.0-h1537add_0 None
  ffmpeg             conda-forge/win-64::ffmpeg-5.1.2-gpl_h6a9407d_103 None
  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0 None
  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0 None
  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0 None
  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-hab24e00_0 None
  fontconfig         conda-forge/win-64::fontconfig-2.14.1-hbde0cde_0 None
  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0 None
  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0 None
  freeimage          conda-forge/win-64::freeimage-3.18.0-h064cf08_10 None
  freetype           conda-forge/win-64::freetype-2.12.1-h546665d_0 None
  frozenlist         conda-forge/win-64::frozenlist-1.3.3-py311ha68e1ae_0 None
  gettext            conda-forge/win-64::gettext-0.21.1-h5728263_0 None
  gl2ps              conda-forge/win-64::gl2ps-1.4.2-h0597ee9_0 None
  glew               conda-forge/win-64::glew-2.1.0-h39d44d4_2 None
  glib               conda-forge/win-64::glib-2.74.1-h12be248_1 None
  glib-tools         conda-forge/win-64::glib-tools-2.74.1-h12be248_1 None
  gst-plugins-base   conda-forge/win-64::gst-plugins-base-1.21.1-h001b923_1 None
  gstreamer          conda-forge/win-64::gstreamer-1.21.1-h6b5321d_1 None
  hdf4               conda-forge/win-64::hdf4-4.2.15-h1b1b6ef_5 None
  hdf5               conda-forge/win-64::hdf5-1.12.2-nompi_h2a0e4a3_100 None
  icu                conda-forge/win-64::icu-70.1-h0e60522_0 None
  idna               conda-forge/noarch::idna-3.4-pyhd8ed1ab_0 None
  ifcopenshell       conda-forge/win-64::ifcopenshell-v0.7.0a6-py311h08ab057_3 None
  imath              conda-forge/win-64::imath-3.1.6-h1758832_0 None
  intel-openmp       conda-forge/win-64::intel-openmp-2022.1.0-h57928b3_3787 None
  jpeg               conda-forge/win-64::jpeg-9e-h8ffe710_2 None
  jsoncpp            conda-forge/win-64::jsoncpp-1.9.5-h2d74725_1 None
  jxrlib             conda-forge/win-64::jxrlib-1.1-h8ffe710_2 None
  krb5               conda-forge/win-64::krb5-1.19.3-h1176d77_0 None
  lcms2              conda-forge/win-64::lcms2-2.12-h2a16943_0 None
  lerc               conda-forge/win-64::lerc-4.0.0-h63175ca_0 None
  libblas            conda-forge/win-64::libblas-3.9.0-16_win64_mkl None
  libcblas           conda-forge/win-64::libcblas-3.9.0-16_win64_mkl None
  libclang           conda-forge/win-64::libclang-15.0.4-default_h77d9078_0 None
  libclang13         conda-forge/win-64::libclang13-15.0.4-default_h77d9078_0 None
  libcurl            conda-forge/win-64::libcurl-7.86.0-heaf79c2_1 None
  libdeflate         conda-forge/win-64::libdeflate-1.14-hcfcfb64_0 None
  libglib            conda-forge/win-64::libglib-2.74.1-he8f3873_1 None
  libiconv           conda-forge/win-64::libiconv-1.17-h8ffe710_0 None
  liblapack          conda-forge/win-64::liblapack-3.9.0-16_win64_mkl None
  libnetcdf          conda-forge/win-64::libnetcdf-4.8.1-nompi_h8c042bf_106 None
  libogg             conda-forge/win-64::libogg-1.3.4-h8ffe710_1 None
  libpng             conda-forge/win-64::libpng-1.6.38-h19919ed_0 None
  libraw             conda-forge/win-64::libraw-0.20.2-hee1bdec_1 None
  libssh2            conda-forge/win-64::libssh2-1.10.0-h680486a_3 None
  libtheora          conda-forge/win-64::libtheora-1.1.1-h8d14728_1005 None
  libtiff            conda-forge/win-64::libtiff-4.4.0-h8e97e67_4 None
  libvorbis          conda-forge/win-64::libvorbis-1.3.7-h0e60522_0 None
  libwebp-base       conda-forge/win-64::libwebp-base-1.2.4-h8ffe710_0 None
  libxml2            conda-forge/win-64::libxml2-2.10.3-hc3477c8_0 None
  libzip             conda-forge/win-64::libzip-1.9.2-hfed4ece_1 None
  loguru             conda-forge/win-64::loguru-0.6.0-py311h1ea47a8_2 None
  lz4-c              conda-forge/win-64::lz4-c-1.9.3-h8ffe710_1 None
  mkl                conda-forge/win-64::mkl-2022.1.0-h6a75c08_874 None
  mpfr               conda-forge/win-64::mpfr-4.1.0-h8d14728_1 None
  mpir               conda-forge/win-64::mpir-3.0.0-he025d50_1002 None
  multidict          conda-forge/win-64::multidict-6.0.2-py311ha68e1ae_2 None
  nlohmann_json      conda-forge/win-64::nlohmann_json-3.11.2-h39d44d4_0 None
  numpy              conda-forge/win-64::numpy-1.23.4-py311h95d790f_1 None
  occt               conda-forge/win-64::occt-7.6.3-h6c7cb8d_1 None
  openexr            conda-forge/win-64::openexr-3.1.5-hab3b255_0 None
  openh264           conda-forge/win-64::openh264-2.3.1-h63175ca_1 None
  openjpeg           conda-forge/win-64::openjpeg-2.5.0-hc9384bd_1 None
  pcre2              conda-forge/win-64::pcre2-10.40-h17e33f8_0 None
  proj               conda-forge/win-64::proj-9.1.0-h3863b3b_0 None
  pugixml            conda-forge/win-64::pugixml-1.11.4-h0e60522_0 None
  python_abi         conda-forge/win-64::python_abi-3.11-2_cp311 None
  qt-main            conda-forge/win-64::qt-main-5.15.6-h9c3277a_1 None
  rapidjson          conda-forge/win-64::rapidjson-1.1.0-ha925a31_1002 None
  sqlite             conda-forge/win-64::sqlite-3.39.4-hcfcfb64_0 None
  svt-av1            conda-forge/win-64::svt-av1-1.3.0-h63175ca_0 None
  tbb                conda-forge/win-64::tbb-2021.7.0-h91493d7_0 None
  tbb-devel          conda-forge/win-64::tbb-devel-2021.7.0-h91493d7_0 None
  typing-extensions  conda-forge/noarch::typing-extensions-4.4.0-hd8ed1ab_0 None
  typing_extensions  conda-forge/noarch::typing_extensions-4.4.0-pyha770c72_0 None
  utfcpp             conda-forge/win-64::utfcpp-3.2.2-h57928b3_0 None
  vtk                conda-forge/win-64::vtk-9.2.2-qt_py311h2c833bd_204 None
  win32_setctime     conda-forge/noarch::win32_setctime-1.1.0-pyhd8ed1ab_0 None
  wslink             conda-forge/noarch::wslink-1.9.1-pyhd8ed1ab_0 None
  x264               conda-forge/win-64::x264-1!164.3095-h8ffe710_2 None
  x265               conda-forge/win-64::x265-3.5-h2d74725_3 None
  yarl               conda-forge/win-64::yarl-1.8.1-py311ha68e1ae_0 None
  zlib               conda-forge/win-64::zlib-1.2.13-hcfcfb64_4 None
  zstd               conda-forge/win-64::zstd-1.5.2-h7755175_4 None

The following packages will be DOWNGRADED:

  openssl                                  3.0.7-hcfcfb64_0 --> 1.1.1s-hcfcfb64_0 None
  python                          3.11.0-hcf16a7b_0_cpython --> 3.11.0-h9a09f29_0_cpython None


Proceed ([y]/n)?
```

**Comment by Krande** [comment]
Thank you, @Martin15135215 for that very helpful debugging! 

No wonder there's an import error. I see that the conda install of the daily build for some reason pulls in the `occt==7.4.0` (which should be `>occt==7.6.2`). That's very interesting. 

I was able to recreate your issue when splitting up the conda env creation and package installation into two separate operations. 

However by simply creating the conda env whilst at the same time including the ifcopenshell package from `-c ifcopenshell` it was working again for me. 

If you could try the following and report if this still results in an import error?

`conda create -n test4 -c ifcopenshell -c conda-forge ifcopenshell python==3.11`

**Comment by aothms** [comment]
How does this actually work in (ana)conda?

We specify `occt` without a version number in the yaml https://github.com/conda-forge/ifcopenshell-feedstock/blob/main/recipe/meta.yaml#L55

Which is indeed I'd say correct. We're compatible with nearly any version on the planet. But how binary compatible is occt between minor releases? And how does the version selected during compilation affect the version to be used at runtime? For example in 7.2 there is BRepAlgoAPI_Splitter so hypothetically if you compile with 7.2 and run with 7.1 you'd be in trouble, but maybe building with 7.6 and running with 7.4 as shared libraries might work?

On windows these might help to see symbol and linkage issues https://www.dependencywalker.com/ https://github.com/lucasg/Dependencies

**Comment by Krande** [comment]
Awesome work, @Martin15135215! Yes, that took me by surprise as well :) I am currently investigating the possibilities of reducing the number of indirect dependencies of the occt package. Hopefully by the end of that I'll find a way to make the installation of the daily conda build a bit more robust (which it isn't today).

**Comment by Moult** [comment]
I suspect this issue may be closed?
