### ISSUE TITLE
[blenderbim] 'module' object has no attribute 'UI_MT_button_context_menu'

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2553]
Since 5fb7f33 blenderbim won't load here (blender 3.2.1), if I comment-out the two `'UI_MT_button_context_menu'` lines in `blenderbim/bim/__init__.py` then it seems to be ok.

```
$ blender
BLT_lang_init: 'locale' data path for translations not found, continuing
Read prefs: /home/bruno/.config/blender/3.2/config/userpref.blend
Warning: brickschema not available.
RDFLib Version: 5.0.0
Failed to load BIMTester. Try disabling other add-ons, in particular Blender-OSM. See bug #1318.
Exception in module register(): /usr/share/blender/3.2/scripts/addons/blenderbim/__init__.py
Traceback (most recent call last):
  File "/usr/share/blender/3.2/scripts/modules/addon_utils.py", line 371, in enable
    mod.register()
  File "/usr/share/blender/3.2/scripts/addons/blenderbim/__init__.py", line 42, in register
    blenderbim.bim.register()
  File "/usr/share/blender/3.2/scripts/addons/blenderbim/bim/__init__.py", line 162, in register
    bpy.types.UI_MT_button_context_menu.append(ui.draw_custom_context_menu)
AttributeError: 'module' object has no attribute 'UI_MT_button_context_menu'

**Comment by Moult** [comment]
Yep mentioned here https://github.com/IfcOpenShell/IfcOpenShell/pull/2544#issuecomment-1296101625 to @Gorgious56 hopefully he knows the extent of what can be supported.

**Comment by Gorgious56** [comment]
I do spend a lot of time reading patch notes but this one flew under the radar. It's actually a rather recent addition : https://www.mail-archive.com/bf-blender-cvs@blender.org/msg162921.html

I'll issue a fix :)
