### ISSUE TITLE
[BlenderBIM] When i tried to open a IFC4.3 there was an error related with IfcDoorStyle

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2559]
```
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\martin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\project\operator.py", line 590, in execute
    ifc_importer.execute()
  File "C:\Users\martin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 220, in execute
    self.process_element_filter()
  File "C:\Users\martin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\import_ifc.py", line 333, in process_element_filter
    + self.file.by_type("IfcDoorStyle")
  File "C:\Users\martin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 355, in by_type
    return [entity_instance(e, self) for e in self.wrapped_data.by_type(type)]
  File "C:\Users\martin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4463, in by_type
    return _ifcopenshell_wrapper.file_by_type(self, *args)
RuntimeError: Entity with name 'IfcDoorStyle' not found in schema 'IFC4X3'
```
The funny thing is, i did not have any door things in the ifc4.3 file

**Comment by aothms** [comment]
Yes, the entity is deleted in IFC4.3 so the code also shouldn't try to access them. Easiest is to wrap the last to by_type() calls there in a try catch. But there's other ways as well.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/import_ifc.py#L334
