### ISSUE TITLE
compile error on macOS 10.12.6

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#257]
I try to compile, but I'm getting an error 

```
Script configuration:


* Target Architecture    = x86_64
 - Whether 32-bit (i686) or 64-bit (x86_64) will be built.
* USE_OCCT               = False
 - Compiling against Open Cascade Community Edition
* Dependency Directory   = /Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64
 - The directory where IfcOpenShell dependencies are installed.
* Build Config Type      = RelWithDebInfo
 - The used build configuration type for the dependencies.
   Defaults to RelWithDebInfo if not specified.
* IFCOS_NUM_BUILD_PROCS  = 5
 - How many compiler processes may be run in parallel.

using command log file '/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/logs/20170909.log'
Collecting dependencies:
Found existing cmake-3.4.1, skipping
Found existing pcre-8.39, skipping
Found existing swig, skipping
Found existing oce-0.18, skipping
Found existing libxml2-2.9.3, skipping
Found existing OpenCOLLADA, skipping
Found existing python-2.7.12, skipping
Found existing python-2.7.12u, skipping
Found existing python-3.2.6, skipping
Found existing python-3.2.6u, skipping
Found existing python-3.3.6, skipping
Fetching python-3.4.6...   
Configuring python-3.4.6...
Building python-3.4.6...   
----------------------------------------------------------------------
../Python/random.c:89:19: warning: implicit declaration of function 'getentropy' is invalid in C99 [-Wimplicit-function-declaration]
            res = getentropy(buffer, len);
                  ^
1 warning generated.
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.4m.a(dynamic_annotations.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.4m.a(pymath.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.4m.a(dynamic_annotations.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.4m.a(pymath.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.4m.a(dynamic_annotations.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.4m.a(pymath.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.4m.a(dynamic_annotations.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.4m.a(pymath.o) has no symbols
/bin/sh: line 1: 52408 Killed: 9               DYLD_LIBRARY_PATH=/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/build/Python-3.4.6/build ./python.exe -E -S -m sysconfig --generate-posix-vars
make: *** [pybuilddir.txt] Error 1

----------------------------------------------------------------------
Traceback (most recent call last):
  File "./build-all.py", line 487, in <module>
    build_dependency("python-%s%s" % (PYTHON_VERSION,abi_tag), "autoconf", PYTHON_CONFIGURE_ARGS + [unicode_conf], "http://www.python.org/ftp/python/%s/" % (PYTHON_VERSION,), "Python-%s.tgz" % (PYTHON_VERSION,))
  File "./build-all.py", line 348, in build_dependency
    __check_call__([make, "-j%s" % (IFCOS_NUM_BUILD_PROCS,)], cwd=extract_build_dir)
  File "./build-all.py", line 216, in __check_call__
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `make -j5` returned exit code 2
```

is there a solution/workaround to compile successful?

**Comment by aothms** [comment]
> `/bin/sh: line 1: 52408 Killed: 9`

Did something or someone force kill the compilation process. Seems like sth went wrong with building python-3.4.6. If you do not so many python wrappers (who does anyway). Remove the ones you don't need here https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.py#L64

**Comment by kurb70** [comment]
Thx. Final I was successful using Python 3.3.6.

BTW I had no success with versions 3.4.6 and 3.5.3.
They produced in the error I mentioned.
