### ISSUE TITLE
BlenderBim: Error in IFCArray editing second array or deleting it

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#2582]
Got the error trying to add second array to IFC, haven't investigated it yet.

Steps to reproduce:
1. Scene Properties - Template: IFC4 Demo Library
2. BIM Tool, add a beam (shift+a)
3. Add array to IFC Array modifier and set it up (for example y = 1, count = 2)
4. Add second array and try to set it up (for example z = 1, count = 2). I get error at this point
5. If you try to remove second or first array you get the same error message.

Error message:
```
Error: Python: Traceback (most recent call last):
  File "AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\tool\ifc.py", line 105, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\ifc.py", line 418, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\model\array.py", line 98, in _execute
    tool.Model.regenerate_array(parent, data)
  File "AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\tool\model.py", line 405, in regenerate_array
    element = tool.Ifc.get().by_guid(removed_child)
  File "AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 327, in by_guid
    return self[guid]
  File "AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 307, in __getitem__
    return entity_instance(self.wrapped_data.by_guid(str(key)), self)
  File "AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4609, in by_guid
    return _ifcopenshell_wrapper.file_by_guid(self, guid)
RuntimeError: Instance with GlobalId '29xAVtiTnDDx83Fj5ZFT1O' not found
```

**Comment by Andrej730** [comment]
Inverstigated the issue - the problem was that after copying object with `tool.Spatial.run_root_copy_class` =it wasn't searchable by the guid.
```python
el = tool.Spatial.run_root_copy_class(obj=child_obj)
tool.Ifc.get().by_guid(el.GlobalId)
# RuntimeError: Instance with GlobalId '29xAVtiTnDDx83Fj5ZFT1O' not found
```

Updated to the most recent version of ifcopenshell and problem is solved (had an older version of ifcopenshell installed fa6bbf2d). My guess the issue was related to #1861
