### ISSUE TITLE
error with IfcMaterialProfileSet

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#2611]
I get very inconsistent errors while instancing objects created with `IfcMaterialProfileSet`. there are times when the instancing happens without any error. sometimes i just get stuck and end up creating the whole file again. attaching the error code below

```
Python: Traceback (most recent call last):
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/module/model/product.py", line 75, in invoke
    return self.execute(context)
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/module/model/product.py", line 78, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/ifc.py", line 418, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/module/model/product.py", line 98, in _execute
    if profile.DumbProfileGenerator(relating_type).generate(link_to_scene=self.link_to_scene):
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/module/model/profile.py", line 119, in generate
    return self.derive_from_cursor(link_to_scene=link_to_scene)
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/module/model/profile.py", line 123, in derive_from_cursor
    return self.create_profile(link_to_scene)
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/module/model/profile.py", line 175, in create_profile
    profile=self.profile_set.CompositeProfile or self.profile_set.MaterialProfiles[0].Profile,
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Moult** [comment]
Note to self, this is due to one of the API calls (but which?) probably removing profiles, and / or leaving the MaterialProfiles as a null when it should be a list with 1 or more items.
