### ISSUE TITLE
Buildt fails on macOS 10.13 

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#266]
When I try to build on macOS 10.13 with **build-all.py** I'm getting the following error:

```
Collecting dependencies:
Found existing cmake-3.4.1, skipping
Found existing pcre-8.39, skipping
Found existing swig, skipping
Found existing occt-7.1.0, skipping
Found existing libxml2-2.9.3, skipping
Found existing OpenCOLLADA, skipping
Found existing python-3.6.2, skipping
Found existing boost-1.59.0, skipping
Found existing icu-56.1, skipping
Building IfcOpenShell:
Configuring executables...
Building executables...   
----------------------------------------------------------------------
Undefined symbols for architecture x86_64:
  "std::string::_Rep::_M_destroy(std::allocator<char> const&)", referenced from:
      boost::system::(anonymous namespace)::generic_error_category::message(int) const in libboost_system.a(error_code.o)
  "std::string::_Rep::_S_empty_rep_storage", referenced from:
      boost::system::(anonymous namespace)::generic_error_category::message(int) const in libboost_system.a(error_code.o)
  "std::string::assign(char const*, unsigned long)", referenced from:
      boost::system::(anonymous namespace)::generic_error_category::message(int) const in libboost_system.a(error_code.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)", referenced from:
      boost::system::(anonymous namespace)::generic_error_category::message(int) const in libboost_system.a(error_code.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)", referenced from:
      boost::system::(anonymous namespace)::generic_error_category::message(int) const in libboost_system.a(error_code.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()", referenced from:
      boost::system::(anonymous namespace)::generic_error_category::message(int) const in libboost_system.a(error_code.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [examples/IfcParseExamples] Error 1
make[1]: *** [examples/CMakeFiles/IfcParseExamples.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2

----------------------------------------------------------------------
Traceback (most recent call last):
  File "./build-all.py", line 543, in <module>
    __check_call__([make, "-j%s" % (IFCOS_NUM_BUILD_PROCS,)], cwd=executables_dir)
  File "./build-all.py", line 217, in __check_call__
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `make -j5` returned exit code 2
```

**Comment by aothms** [comment]
I was expecting this, but still contemplating how to fix this.

OCCT 7 requires C++11, but the `"-mmacosx-version-min=10.6` we were building with does not support C++11. I tried fixing that, but it left the previously built dependencies incompatible with the new compiler arguments.

The solution now is that the platform toolset is also added to the default build path. This means everything is going to be rebuilt. If you do not want to take the time for that and you are fine with using the older OCC community edition, you can do something like the following:

~~~
shopt -s extglob
cd /path/to/IfcOpenShell/nix
mkdir ../build/Darwin/x86_64/10.6
mv ../build/Darwin/x86_64/!(10.*) ../build/Darwin/x86_64/10.6
USE_OCCT=False python build-all.py
~~~
