### ISSUE TITLE
error when creating a new ifc project w/ blenderbim-221226 on Blender 3.4

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2664]
error when creating a new ifc project w/ blenderbim-221226 on Blender 3.4

could be tied to https://github.com/IfcOpenShell/IfcOpenShell/commit/0f9c84c1ce202a31e65667449ac570eb87afb26f

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\project\operator.py", line 533, in execute
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\project\operator.py", line 590, in execute
    ifc_importer.execute()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\import_ifc.py", line 227, in execute
    self.create_project()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\import_ifc.py", line 1343, in create_project
    obj = self.create_product(self.project["ifc"])
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\import_ifc.py", line 954, in create_product
    elif hasattr(element, "ObjectPlacement"):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 138, in __getattr__
    rules = importlib.import_module(f"ifcopenshell.express.rules.{schema_name}")
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ifcopenshell.express.rules'
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:113

```

**Comment by aothms** [comment]
Probably caused by https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/Makefile#L198-L202
