### ISSUE TITLE
BlenderBIM Error removing nonexistent h5 cache file

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2721]
I know I'm an oddity running blenderbim in a readonly folder, but it has worked like this for a long time. With the latest git version it errors trying to remove a cache file that doesn't exist:

```
Traceback (most recent call last):
  File "/usr/share/blender/3.4/scripts/addons/blenderbim/bim/module/project/operator.py", line 827, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/3.4/scripts/addons/blenderbim/bim/module/project/operator.py", line 840, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/usr/share/blender/3.4/scripts/addons/blenderbim/bim/ifc.py", line 422, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/3.4/scripts/addons/blenderbim/bim/module/project/operator.py", line 871, in _execute
    ifc_exporter.export()
  File "/usr/share/blender/3.4/scripts/addons/blenderbim/bim/export_ifc.py", line 49, in export
    self.sync_all_objects()
  File "/usr/share/blender/3.4/scripts/addons/blenderbim/bim/export_ifc.py", line 112, in sync_all_objects
    result = self.sync_object_placement(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/3.4/scripts/addons/blenderbim/bim/export_ifc.py", line 163, in sync_object_placement
    blenderbim.core.geometry.edit_object_placement(tool.Ifc, tool.Geometry, tool.Surveyor, obj=obj)
  File "/usr/share/blender/3.4/scripts/addons/blenderbim/core/geometry.py", line 26, in edit_object_placement
    geometry.clear_cache(element)
  File "/usr/share/blender/3.4/scripts/addons/blenderbim/tool/geometry.py", line 41, in clear_cache
    cache = IfcStore.get_cache()
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/3.4/scripts/addons/blenderbim/bim/ifc.py", line 99, in get_cache
    os.remove(IfcStore.cache_path)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/blender/3.4/scripts/addons/blenderbim/bim/data/cache/d13ff2065009fe560ad2d2fe7f457064.h5'

**Comment by brunopostle** [comment]
I know it works ok if I copy the 'data' and 'schema' folders to ~/.local/share or similar and point the Blenderbim preferences to this location, but it seems that software ought to work when it is readonly.
