### ISSUE TITLE
BlenderBim - When editing using window modifier it gets big

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2724]
![image](https://user-images.githubusercontent.com/78321676/214779813-42bb7974-9fc7-42c3-a470-17f51c121cf5.png)
That's a 900x600 window hahah
I use millimetres as my project units so I imagine it has something to do with that.

When editing is done it returns to normal size
![image](https://user-images.githubusercontent.com/78321676/214780118-b013730e-cb03-4e70-9720-3197398c27c7.png)

Amazing tool though! Good job people! @Andrej730 Awesome work!

**Comment by Andrej730** [comment]
That was a really big window!) Fixed in b1dd20fef742178f31bb86a96e4a4566daa635dc


Interestingly enough noticed that if you set project units to kilometers the window representation will be broken for some reason (all other units work fine).
![image](https://user-images.githubusercontent.com/9417531/214805217-1013eb42-6ce2-491f-9f07-f4432976ce59.png)

If I try to bring with debugger only the thin glass part it results in the following error. I'll look into that.
```Traceback (most recent call last):
  File "\addons\blenderbim\bim\module\debug\operator.py", line 155, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "\addons\blenderbim\bim\ifc.py", line 425, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "\addons\blenderbim\bim\module\debug\operator.py", line 165, in _execute
    shape = ifcopenshell.geom.create_shape(settings, element)
  File "\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 210, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
  File "\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 2378, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process representation item```

**Comment by Plae-Blue-Dot** [comment]
I suppose when doing civil projects using km might be common, not so certain if it would be needed for giant window construction but you know better safe than sorry! hahah

Thanks for getting this sorted so quick!

**Comment by Moult** [comment]
@Andrej730 the UI should not be hardcoded to use mm, instead it should allow any number, and then based on that use ifcopenshell.util.unit.calculate_unit_scale to convert to SI meters for the bmesh representation, and use whatever numbers they put in exactly for the IFC representation.

**Comment by Andrej730** [comment]
> @Andrej730 the UI should not be hardcoded to use mm, instead it should allow any number, and then based on that use ifcopenshell.util.unit.calculate_unit_scale to convert to SI meters for the bmesh representation, and use whatever numbers they put in exactly for the IFC representation.

Changed it to project units instead of mm in 74477d005
