### ISSUE TITLE
Wont install on 3.3 LTS

### ISSUE THREAD

**Issue by Earbuckets** [IfcOpenShell/IfcOpenShell#2725]
Traceback (most recent call last):
  File "C:\blender\BlenderBuilds\stable\blender-3.3.2+lts.bf24652e38a2\3.3\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Earbu\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\__init__.py", line 42, in register
    blenderbim.bim.register()
AttributeError: module 'blenderbim' has no attribute 'bim'

**Comment by Earbuckets** [comment]
Installed fine on 3.2 I'll check it out

**Comment by Moult** [comment]
I'm also running it on 3.3 and 3.4 so it should work on both those versions.

**Comment by Moult** [comment]
Closing, let me know if there are still issues as no other users seem to be reporting problems.
