### ISSUE TITLE
[BlenderBIM] Workplan is not shwon in the UI

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2740]
When i open this https://github.com/Martin15135215/git_ifc_test/blob/main/test_two_cube_wall_4d.ifc file in BlenderBIM blenderbim-230201 -> 
![image](https://user-images.githubusercontent.com/110968398/216946375-02a65583-6ce0-4258-b08f-2b0a09d92342.png)

There is no workplan shown, even if the ifc file has a https://github.com/Martin15135215/git_ifc_test/blob/0eb9516a73631fc412deb5d80e05b639489bf7fb/test_two_cube_wall_4d.ifc#L97 Workplan in the ifc file

Edit:
I found an error message, maybe that can help

```
Traceback (most recent call last):
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\sequence\ui.py", line 43, in draw
    WorkPlansData.load()
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\sequence\data.py", line 233, in load
    "active_work_plan_schedules": cls.active_work_plan_schedules(),
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\sequence\data.py", line 254, in active_work_plan_schedules
    if not self.props.active_work_plan_id:
NameError: name 'self' is not defined
```

Edit:
had the wrong file linked

**Comment by Martin15135215** [comment]
Also testet now the Animation 

![image](https://user-images.githubusercontent.com/110968398/216947265-349f2402-5770-4dc7-a8c3-84454bde70d4.png)

after clicking the new button Guess -> i clicked the Create Animation Button and the Create SnapShot Button -> both of them throw me a error message

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 1044, in execute
    core.visualise_work_schedule_date_range(tool.Sequence, work_schedule=tool.Ifc.get().by_id(self.work_schedule))
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\core\sequence.py", line 503, in visualise_work_schedule_date_range
    sequence.animate_objects(settings, product_frames)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\tool\sequence.py", line 1207, in animate_objects
    cls.animate_output(obj, settings["start_frame"], product_frame)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\tool\sequence.py", line 1233, in animate_output
    cls.animate_movement_to(obj, product_frame, color)
TypeError: Sequence.animate_movement_to() missing 1 required positional argument: 'color'
```

```
Traceback (most recent call last):
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 976, in execute
    self.preprocess_tasks()
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 1001, in preprocess_tasks
    self.preprocess_task(related_object)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 1007, in preprocess_task
    start = helper.derive_date(task, "ScheduleStart", is_earliest=True)
AttributeError: module 'blenderbim.bim.module.sequence.helper' has no attribute 'derive_date'
```

**Comment by myoualid** [comment]
Bugs above should now be solved!

**Comment by Moult** [comment]
@myoualid can you also add tests for them? For example a smoke test calling the add work plan operator should've caught this error.

**Comment by Martin15135215** [comment]
I tried today with the newest BlenderBIM Daily.

- Workplan is found
- Create Animation functions

However i am not sure what Create snapshot should do? 

First i clicked the Guess button (does function), and then the Create Animate button (does function) and after that the Create SnapShot Button, my cubes disappeared and after a click Create Animate button -> the animation does not function

**Comment by Moult** [comment]
Ping @myoualid

**Comment by myoualid** [comment]
> 
@Moult , there was a smoke test for the add_work_plan operator - for the color too, https://github.com/IfcOpenShell/IfcOpenShell/blob/88bddb9531d8978d5a8de9b48fcbb813b21e61ad/src/blenderbim/test/bim/feature/sequence.feature#L4.

**Comment by Moult** [comment]
Ah right it was a UI bug so that's why the smoke test couldn't catch it.

**Comment by myoualid** [comment]
@Moult , @Martin15135215 - [ac5ec72](https://github.com/IfcOpenShell/IfcOpenShell/commit/ac5ec72acfee9b4185074aa8a02c286dbfc3a596) improves the workflow above.

- As it stands, the 📷 create snapshot operator is a simplified version of the create animation. It will show a the construction state of your products at a given date ( calculated using the Start Date of your current date range props).
In words and colors :
- what is to demolish/move unless it hasn't been built yet: normal color
- what is being demolished/moved: 🔴 red
- what is to build : hidden, 
- what is being built : 🟠 orange, 
- what is built: 🟢 green.
- what is demolished: hidden,

The colors are arbitrary right now, but you can expect UI customisation improvements coming shortly :)

**Comment by myoualid** [comment]
@Martin15135215 the guess_date button is now also improved to account for any task related to demolition/logistics etc. ( I noticed it from your snapshot)

Also, make sure an activity happens on the day of your your "start date" property, otherwise everything will be hidden from view unless it is to be demolished at a later date.

PS: You can toggle the show attribute columns operator (next to the sunglasses icon), and click on show default columns to quickly see task information (start,end,duration)

**Comment by Martin15135215** [comment]
Thanks @myoualid for the tips ! it has changed quite a lot from the last time i used it :D
