### ISSUE TITLE
obj2ifc for multiple obj files

### ISSUE THREAD

**Issue by HollowHeartNet** [IfcOpenShell/IfcOpenShell#2743]
Hi,

The current implementation of the script 'obj2ifc-meshlab.py' (see link below) only considers the conversion of a single OBJ file into IFC. I wanted to ask how the code needs to be modified to convert multiple OBJ files into a single IFC file. I was thinking of using a foor loop like this:

```
import pymeshlab
import ifcopenshell
import ifcopenshell.api
import ifcopenshell.api.owner.settings
from pathlib import Path


class Obj2Ifc:
    def __init__(self, fileList):
        self.fileList = fileList

    def execute(self): #convert mesh to ifc
        self.create_ifc_file()

        for i in range(len(self.fileList)):
            self.basename = Path(self.fileList[i]).stem
            print("filename:", self.basename)

            ### start ###
            mesh_set = pymeshlab.MeshSet()
            mesh_set.load_new_mesh(self.fileList[i])

            self.format = None
            if self.fileList[i].lower().endswith(".obj"):
                self.format = "obj"

            for mesh in mesh_set:
                faces = mesh.face_matrix()
                vertices = mesh.vertex_matrix()

                ifc_faces = []
                for face in faces:
                    ifc_faces.append(
                        self.file.createIfcFace(
                            [
                                self.file.createIfcFaceOuterBound(
                                    self.file.createIfcPolyLoop(
                                        [self.file.createIfcCartesianPoint(vertices[index].tolist()) for index in face]
                                    ),
                                    True,
                                )
                            ]
                        )
                    )
                representation = self.file.createIfcProductDefinitionShape(
                    None,
                    None,
                    [
                        self.file.createIfcShapeRepresentation(
                            self.context,
                            "Body",
                            "Brep",
                            [self.file.createIfcFacetedBrep(self.file.createIfcClosedShell(ifc_faces))],
                        )
                    ],
                )
                product = self.file.create_entity(
                    "IfcWall", #Insert IfcClass here
                    **{
                        "GlobalId": ifcopenshell.guid.new(),
                        "Name": self.basename,
                        "ObjectPlacement": self.placement,
                        "Representation": representation,
                    }
                )
                ifcopenshell.api.run("spatial.assign_container", self.file, product=product, relating_structure=self.storey)
                ### end ###
        self.file.write("SORTIE_MODEL.ifc")

    def get_coordinates(self, coordinates):
        if self.format == "obj":
            # OBJ swaps Y and Z axis
            return [coordinates[0], -coordinates[2], coordinates[1]]

    def create_ifc_file(self):
        self.file = ifcopenshell.api.run("project.create_file", version="IFC4")
        person = ifcopenshell.api.run("owner.add_person", self.file)
        person[0] = person.GivenName = None
        person.FamilyName = "user"
        org = ifcopenshell.api.run("owner.add_organisation", self.file)
        org[0] = None
        org.Name = "template"
        user = ifcopenshell.api.run("owner.add_person_and_organisation", self.file, person=person, organisation=org)
        application = ifcopenshell.api.run("owner.add_application", self.file)
        ifcopenshell.api.owner.settings.get_user = lambda ifc: user
        ifcopenshell.api.owner.settings.get_application = lambda ifc: application

        project = ifcopenshell.api.run("root.create_entity", self.file, ifc_class="IfcProject", name="SORTIE-IFC")
        lengthunit = ifcopenshell.api.run("unit.add_si_unit", self.file, unit_type="LENGTHUNIT", name="METRE")
        ifcopenshell.api.run("unit.assign_unit", self.file, units=[lengthunit])
        model = ifcopenshell.api.run("context.add_context", self.file, context_type="Model")
        self.context = ifcopenshell.api.run(
            "context.add_context",
            self.file,
            context_type="Model",
            context_identifier="Body",
            target_view="MODEL_VIEW",
            parent=model,
        )
        site = ifcopenshell.api.run("root.create_entity", self.file, ifc_class="IfcSite", name="My Site")
        building = ifcopenshell.api.run("root.create_entity", self.file, ifc_class="IfcBuilding", name="My Building")
        self.storey = ifcopenshell.api.run(
            "root.create_entity", self.file, ifc_class="IfcBuildingStorey", name="My Storey"
        )
        ifcopenshell.api.run("aggregate.assign_object", self.file, product=site, relating_object=project)
        ifcopenshell.api.run("aggregate.assign_object", self.file, product=building, relating_object=site)
        ifcopenshell.api.run("aggregate.assign_object", self.file, product=self.storey, relating_object=building)

        self.origin = self.file.createIfcAxis2Placement3D(
            self.file.createIfcCartesianPoint((0.0, 0.0, 0.0)),
            self.file.createIfcDirection((0.0, 0.0, 1.0)),
            self.file.createIfcDirection((1.0, 0.0, 0.0)),
        )
        self.placement = self.file.createIfcLocalPlacement(None, self.origin)
        self.history = ifcopenshell.api.run("owner.create_owner_history", self.file)


if __name__ == "__main__":

    file1 = "test_obj2ifc.obj"
    file2 = "test2_obj2ifc.obj"
    filelist = [file1, file2]

    obj2ifc = Obj2Ifc(filelist)
    obj2ifc.execute()
```

However, I get the following error message: 

```
Traceback (most recent call last):
  File ".\obj2ifc.py", line 147, in <module>
    obj2ifc.execute()
  File ".\obj2ifc.py", line 79, in execute
    product = self.file.create_entity(
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\ifcopenshell\file.py", line 284, in create_entity
    e[idx] = arg
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\ifcopenshell\entity_instance.py", line 224, in __setitem__
    self.method_list[idx](
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4867, in setArgumentAsEntityInstance
    return _ifcopenshell_wrapper.entity_ins
```

Can someone please help?

Thanks in advance!

With best regards
HollowHeartNet

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/scripts/obj2ifc-meshlab.py

**Comment by Moult** [comment]
Meshlab only reads a single object from an OBJ, and this is a limitation on their end, not ours I believe.

**Comment by aothms** [comment]
So, as you can see from the traceback the issue is somewhere here:

>     product = self.file.create_entity(
>         "IfcWall", #Insert IfcClass here
>         **{
>             "GlobalId": ifcopenshell.guid.new(),
>             "Name": self.basename,
>             "ObjectPlacement": self.placement,
>             "Representation": representation,
>         }
>     )

`self.basename` is a pathlib.Path, that likely won't work, so try: `str(self.basename)`. 

But the traceback (the bottom end is missing so can't be sure) is abt `setArgumentAsEntityInstance()` which is probably another issue (regarding self.placement or representation) maybe one of these is not what you think it is.

**Comment by Martin15135215** [comment]
This can be closed, see https://github.com/Martin15135215/git_ifc_test/issues/1

**Comment by Moult** [comment]
@Martin15135215 the solution mentioned in the other thread isn't quite right, ObjectPlacement: None is invalid if there is a representation (the rule is that if a representation exists, a placement must exist), so this can't be closed yet. It would be good to fix as well as have a PR to update the script to support multiple obj files.

**Comment by Martin15135215** [comment]
@Moult your are correct, i saw that right now in the doc

> An object placement must be provided if a representation is present.
From https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcProduct.htm

**Comment by Martin15135215** [comment]
there is a bug in run("spatial.assign_container" see https://github.com/IfcOpenShell/IfcOpenShell/issues/2789

@HollowHeartNet  as a workaround use 

```python
product = self.file.create_entity(
                    "IfcWall", #Insert IfcClass here
                    **{
                        "GlobalId": ifcopenshell.guid.new(),
                        "Name": self.basename,
                        "ObjectPlacement": None,
                        "Representation": representation,
                    }
                )

ifcopenshell.api.run("spatial.assign_container", self.file, product=product, relating_structure=self.storey)
product.ObjectPlacement = self.placement
```
