### ISSUE TITLE
Creating shapes fails with different order of representations

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#2744]
I was fixing #2742 by changing element representation context from `Plan/Annotation/PLAN_VIEW` to `Plan/Body/PLAN_VIEW` and noticed some error - when I defined `Plan/Body/PLAN_VIEW` first and `Model/Body/MODEL_VIEW` second, switching to `MODEL_VIEW` representation for this element results in error:

Traceback:
```python
Error: Python: Traceback (most recent call last):
  File "%appdata%\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 41, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "%appdata%\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\ifc.py", line 425, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "%appdata%\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 131, in _execute
    core.switch_representation(
  File "%appdata%\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\core\geometry.py", line 100, in switch_representation
    data = geometry.import_representation(obj, representation)
  File "%appdata%\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\tool\geometry.py", line 182, in import_representation
    shape = ifcopenshell.geom.create_shape(settings, element)
  File "%appdata%\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 210, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
  File "%appdata%\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 2378, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process shape
```

But if you define `Model/Body/MODEL_VIEW` first it works fine. Is it a bug?

To reproduce the problem you can use the `debug_door_bugged.ifc` I've attached and try to switch representation to `MODEL_VIEW` and see the error. 
![image](https://user-images.githubusercontent.com/9417531/217233132-3aeb0bd6-31c6-4241-b8fe-9321915c66fa.png)

If I change just one line in .ifc from `#71=IFCPRODUCTDEFINITIONSHAPE($,$,(#70,#85,#149));` to `#71=IFCPRODUCTDEFINITIONSHAPE($,$,(#70,#149,#85));` (this edit is included in `debug_door _fixed.ifc`) it will work fine.

[debug_door_bugged.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10674537/debug_door_bugged.ifc.txt)
[debug_door _fixed.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10674538/debug_door._fixed.ifc.txt)

**Comment by Moult** [comment]
This could be a more fundamental IfcOpenShell behaviour issue. Ping @aothms. It seems that when you do create_shape(settings, element) where element is an IfcElement (e.g. IfcDoor) as opposed to an IfcShapeRepresentation, it searches for the first Body representation that it can find... however, it _should_ actually search for the first Body representation with a TargetView of MODEL_VIEW instead, I believe?

There is also some form of assumption that the openings on an element apply to the "Body", whereas we should be more explicit and say it only applies to the "Model/Body/MODEL_VIEW", not any other context.

**Comment by aothms** [comment]
I'm a bit scared making these kind of changes given how most tools don't seem to care abt this at all, but I guess we can add a somewhat defensive check that in case we find multiple body reps we take the one with TargetView=MODEL_VIEW.

> There is also some form of assumption that the openings on an element apply to the "Body", whereas we should be more explicit and say it only applies to the "Model/Body/MODEL_VIEW", not any other context.

This sounds even riskier to me and harder to implement. Is this idea specified anywhere?

**Comment by Moult** [comment]
@aothms well the idea is merely based on logic, how would an opening with Model/Body/MODEL_VIEW void an element with a Plan/Body/PLAN_VIEW?

**Comment by aothms** [comment]
Well, the other way around is surely possible I'd say: A simple plan view polyline to cut through a slab. I don't see anything in the standard that would be against it, it's just not convenient in most current bim tools so nobody bothered to think about it, but it would be more efficient and robust then just bodies.

**Comment by BIMvoice** [comment]
The order dependence is fixed on the current `v0.8.0`. I ran your two attached files and `create_shape` on the `Model/Body/MODEL_VIEW` representation now succeeds regardless of the representation order:

```
BUGGED order: Model/Profile=FAIL | Plan/Body=FAIL | Model/Body=OK(8v)
FIXED  order: Model/Profile=FAIL | Model/Body=OK(8v) | Plan/Body=FAIL
```

Both files give identical results, and `MODEL_VIEW` works in both, so switching to `MODEL_VIEW` no longer fails because of where the body representation sits in `IfcProductDefinitionShape.Representations`. That was the reported symptom.

The `Plan/Body/PLAN_VIEW` and `Model/Profile/ELEVATION_VIEW` entries fail identically in both orderings, i.e. not order related. Those are 2D representations; passing them to `create_shape` as solids is a separate matter from this issue. Safe to close for the order-dependence bug.
