### ISSUE TITLE
Error trying to reassign the ifc class to an object

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#2756]
I get an error when trying to reassign the ifc class to an object.
To recreate the bug, simply start a new fresh file, add an ifc project, add a cube, assign an ifc class to it (IfcWall for example) and after that try to reassign the ifc class to the cube in blender UI.
This is the error i get:

Traceback (most recent call last):
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/bim/module/root/operator.py", line 91, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/bim/ifc.py", line 425, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/bim/module/root/operator.py", line 100, in _execute
    product = ifcopenshell.api.run(
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/root/reassign_class.py", line 65, in execute
    element = ifcopenshell.util.schema.reassign_class(
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/schema.py", line 81, in reassign_class
    inverse_pairs = ifc_file.get_inverse(element, allow_duplicate=True, with_attribute_indices=True)
TypeError: file.get_inverse() got an unexpected keyword argument 'with_attribute_indices'
Error: Python: Traceback (most recent call last):
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/bim/module/root/operator.py", line 91, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/bim/ifc.py", line 425, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/bim/module/root/operator.py", line 100, in _execute
    product = ifcopenshell.api.run(
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/root/reassign_class.py", line 65, in execute
    element = ifcopenshell.util.schema.reassign_class(
  File "/home/max/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/schema.py", line 81, in reassign_class
    inverse_pairs = ifc_file.get_inverse(element, allow_duplicate=True, with_attribute_indices=True)
TypeError: file.get_inverse() got an unexpected keyword argument 'with_attribute_indices'

**Comment by Moult** [comment]
Are you using the latest ifcopenshell?

**Comment by maxfb87** [comment]
I downloaded now a fresh new blender version (3.4.1) and installed BBim last release available in github (230210) and actually the traceback is different:

Read prefs: /home/max/.config/blender/3.4/config/userpref.blend
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/schema.py", line 85, in reassign_class
    new_element = ifc_file.create_entity(new_class, id=info["id"], **new_attributes)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 285, in create_entity
    e[idx] = arg
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 247, in __setitem__
    self.method_list[idx](
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3793, in setArgumentAsString
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsString(self, i, a)
RuntimeError: ELEMENTEDWALL does not name a valid item for IfcSlabTypeEnum

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/root/operator.py", line 91, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/ifc.py", line 425, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/root/operator.py", line 100, in _execute
    product = ifcopenshell.api.run(
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/root/reassign_class.py", line 65, in execute
    element = ifcopenshell.util.schema.reassign_class(
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/schema.py", line 87, in reassign_class
    print(f"Class of {element} could not be changed to {new_class}")
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 257, in __repr__
    return repr(self.wrapped_data)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3745, in __repr__
    return _ifcopenshell_wrapper.entity_instance___repr__(self)
RuntimeError: Invalid cast
Error: Python: Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/schema.py", line 85, in reassign_class
    new_element = ifc_file.create_entity(new_class, id=info["id"], **new_attributes)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 285, in create_entity
    e[idx] = arg
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 247, in __setitem__
    self.method_list[idx](
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3793, in setArgumentAsString
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsString(self, i, a)
RuntimeError: ELEMENTEDWALL does not name a valid item for IfcSlabTypeEnum

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/root/operator.py", line 91, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/ifc.py", line 425, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/root/operator.py", line 100, in _execute
    product = ifcopenshell.api.run(
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/root/reassign_class.py", line 65, in execute
    element = ifcopenshell.util.schema.reassign_class(
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/schema.py", line 87, in reassign_class
    print(f"Class of {element} could not be changed to {new_class}")
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 257, in __repr__
    return repr(self.wrapped_data)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3745, in __repr__
    return _ifcopenshell_wrapper.entity_instance___repr__(self)
RuntimeError: Invalid cast

Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/root/ui.py", line 46, in draw
    if not IfcClassData.data["has_entity"]:
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 254, in __len__
    return len(self.wrapped_data)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3715, in __len__
    return _ifcopenshell_wrapper.entity_instance___len__(self)
RuntimeError: Invalid cast
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/aggregate/ui.py", line 42, in poll
    if not IfcStore.get_file().by_id(props.ifc_definition_id).is_a("IfcObjectDefinition"):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/material/ui.py", line 118, in poll
    if not hasattr(IfcStore.get_file().by_id(props.ifc_definition_id), "HasAssociations"):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 60, in get_pset_names
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 60, in get_pset_names
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/ui.py", line 193, in draw
    prop_with_search(row, props, "pset_name", text="")
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/helper.py", line 183, in prop_with_search
    if len(get_enum_items(data, prop_name)) > 10:
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/helper.py", line 202, in get_enum_items
    items = items(data, context or bpy.context)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/root/ui.py", line 46, in draw
    if not IfcClassData.data["has_entity"]:
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 254, in __len__
    return len(self.wrapped_data)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3715, in __len__
    return _ifcopenshell_wrapper.entity_instance___len__(self)
RuntimeError: Invalid cast
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/aggregate/ui.py", line 42, in poll
    if not IfcStore.get_file().by_id(props.ifc_definition_id).is_a("IfcObjectDefinition"):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/material/ui.py", line 118, in poll
    if not hasattr(IfcStore.get_file().by_id(props.ifc_definition_id), "HasAssociations"):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 60, in get_pset_names
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 60, in get_pset_names
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/ui.py", line 193, in draw
    prop_with_search(row, props, "pset_name", text="")
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/helper.py", line 183, in prop_with_search
    if len(get_enum_items(data, prop_name)) > 10:
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/helper.py", line 202, in get_enum_items
    items = items(data, context or bpy.context)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/root/ui.py", line 46, in draw
    if not IfcClassData.data["has_entity"]:
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 254, in __len__
    return len(self.wrapped_data)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3715, in __len__
    return _ifcopenshell_wrapper.entity_instance___len__(self)
RuntimeError: Invalid cast
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/aggregate/ui.py", line 42, in poll
    if not IfcStore.get_file().by_id(props.ifc_definition_id).is_a("IfcObjectDefinition"):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/material/ui.py", line 118, in poll
    if not hasattr(IfcStore.get_file().by_id(props.ifc_definition_id), "HasAssociations"):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 60, in get_pset_names
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 60, in get_pset_names
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/ui.py", line 193, in draw
    prop_with_search(row, props, "pset_name", text="")
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/helper.py", line 183, in prop_with_search
    if len(get_enum_items(data, prop_name)) > 10:
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/helper.py", line 202, in get_enum_items
    items = items(data, context or bpy.context)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/root/ui.py", line 46, in draw
    if not IfcClassData.data["has_entity"]:
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 254, in __len__
    return len(self.wrapped_data)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3715, in __len__
    return _ifcopenshell_wrapper.entity_instance___len__(self)
RuntimeError: Invalid cast
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/aggregate/ui.py", line 42, in poll
    if not IfcStore.get_file().by_id(props.ifc_definition_id).is_a("IfcObjectDefinition"):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/material/ui.py", line 118, in poll
    if not hasattr(IfcStore.get_file().by_id(props.ifc_definition_id), "HasAssociations"):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 60, in get_pset_names
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 60, in get_pset_names
Traceback (most recent call last):
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/ui.py", line 193, in draw
    prop_with_search(row, props, "pset_name", text="")
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/helper.py", line 183, in prop_with_search
    if len(get_enum_items(data, prop_name)) > 10:
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/helper.py", line 202, in get_enum_items
    items = items(data, context or bpy.context)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/bim/module/pset/prop.py", line 65, in get_pset_names
    element = IfcStore.get_file().by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 325, in by_id
    return self[id]
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 313, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/max/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #63 not found
