### ISSUE TITLE
Export cost schedule bug

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2768]
Ping @myoualid 

Also if you run `make test-bim` there are 3 sequence module related failures.

```
rna_uiItemO: operator missing srna 'bim.export_cost_schedule'
/home/dion/.config/blender/3.4/scripts/addons/blenderbim/bim/module/cost/ui.py:60
Traceback (most recent call last):
  File "/home/dion/.config/blender/3.4/scripts/addons/blenderbim/bim/module/cost/ui.py", line 50, in draw
    self.draw_cost_schedule_ui(schedule)
  File "/home/dion/.config/blender/3.4/scripts/addons/blenderbim/bim/module/cost/ui.py", line 60, in draw_cost_schedule_ui
    row.operator("bim.export_cost_schedule", text="", icon="EXPORT").cost_schedule = cost_schedule["id"]
AttributeError: 'NoneType' object has no attribute 'cost_schedule'
rna_uiItemO: operator missing srna 'bim.export_cost_schedule'
```

**Comment by myoualid** [comment]
Export Cost Schedule is now fixed, didn't realise I commited the UI - was still finising up the cli app.

Which test fail for you? I have the color of "animate_wall_consumption" which I can't solve right now

**Comment by Moult** [comment]
Yep now test_animate_the_consumption_of_a_wall is the remaining failure, do you need help?

**Comment by Moult** [comment]
Closing as @Andrej730 has fixed the remaining failure :)
