### ISSUE TITLE
[BlenderBIM] Issue with the IFC Work Schedules Tab by opening the bSI sample file

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2783]
Here is the sample file from bSI https://github.com/buildingSMART/Sample-Test-Files/blob/master/IFC%204.0/BuildingSMARTSpec/construction-scheduling-task.ifc

After loading that file in BlenderBIM and clickung at the IFC Work Schedules tab there was this error

```shell
Traceback (most recent call last):                                                                                                                                                  File "C:\Users\martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 178, in execute                              core.enable_editing_work_schedule_tasks(tool.Sequence, work_schedule=tool.Ifc.get().by_id(self.work_schedule))                                                                  File "C:\Users\martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\core\sequence.py", line 78, in enable_editing_work_schedule_tasks                   sequence.load_task_properties()                                                                                                                                                 File "C:\Users\martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\tool\sequence.py", line 210, in load_task_properties                                item.calendar = calendar.Name if calendar else ""                                                                                                                             TypeError: bpy_struct: item.attr = val: Task.calendar doesn't support None from string types                                                                                      Error: Python: Traceback (most recent call last):                                                                                                                                   File "C:\Users\martin\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 178, in execute                              core.enable_editing_work_schedule_tasks(tool.Sequence, work_schedule=tool.Ifc.get().by_id(self.work_schedule))                                                                  File "C:\Users\martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\core\sequence.py", line 78, in enable_editing_work_schedule_tasks                   sequence.load_task_properties()                                                                                                                                                 File "C:\Users\martin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\tool\sequence.py", line 210, in load_task_properties                                item.calendar = calendar.Name if calendar else ""                                                                                                                             TypeError: bpy_struct: item.attr = val: Task.calendar doesn't support None from string types  
```

I used the Version 0.0.230209

**Comment by Moult** [comment]
@myoualid something you might want to look at?

**Comment by myoualid** [comment]
Regarding the gantt chart / animation, we need to discuss the contents of the file provided before I make any changes.

 We use Scheduled Durations along with the ScheduleStart / ScheduleFinish to get/derive our dates, however, in the file:
- we only have tasks with ScheduleDuration and EarlyStart/Early finish & LateStart/Late Finish (which are calculated values) - and I'm not certain how these were calculated without a Schedule Start or Schedule Finished.
-The root task is the only task that has a ScheduleStart, and I don't expect tasks at the bottom of the tree to inherit the ScheduleStart from the root task - or does it ?
- All tasks have the same early start/early finish, despite having durations and sequential relationships.

Should we do a "dumb" animation that only uses tasks relationships to display an animation sequence?

ping @Moult @Martin15135215

**Comment by Moult** [comment]
There is a comment in the file:

> /* Scheduled start and finish are not specified, such that early start and finish take effect -- */

I find this interesting as a non-domain expert, I had no idea this rule could be the case. In the IFC docs there is this note under the ScheduledStart/Finish attributes:

>  The scheduled start date must be greater than or equal to the earliest start date.

Which doesn't directly confirm the comment, but suggests it might be valid.

I'm happy to either:

 1. Follow the rule that early start/finish may be used as a fallback, and then file a bug to buildingSMART to clarify.
 2. Not follow the rule and decide it's a bad rule, and then also file a bug to buildingSMART to clarify.

You choose @myoualid :)

In theory I see how it might be the case where only the "first" task has a scheduled start, everything else only has durations, and therefore everything else only has calculated early / late dates. Notice how DataOrigin has set to PREDICTED in that scenario.

Maybe the DataOrigin plays a role in when schedule start is followed rigidly (i.e. when DataOrigin is MEASURED) or when things are merely calculated (PREDICTED? SIMULATED? What's the difference?).

**Comment by Martin15135215** [comment]
> * All tasks have the same early start/early finish, despite having durations and sequential relationships.

I am here out of my depth, however i controlled the early start/early finsih and there are not all the same

![image](https://user-images.githubusercontent.com/110968398/220695194-c809f315-96dc-41ce-99fd-b70a971565e3.png)

**Comment by sboddy** [comment]
Sample file link is stale. New location: https://github.com/buildingsmart-community/Community-Sample-Test-Files/blob/main/IFC%204.0.2.1%20(IFC%204)/ISO%20Spec%20archive/construction-scheduling-task.ifc

blender_version: 4.2.9 LTS
bonsai_version: 0.8.3-alpha250418

Loads sample OK. Trying to edit the tasks throws an error:
![Image](https://github.com/user-attachments/assets/d624cdf0-dcf4-4654-b1ac-8ed3f853c9b6)

Seems missing text in the UI:
![Image](https://github.com/user-attachments/assets/0180f88c-7710-4219-ab2b-3e72eb3b9582)

**Comment by sboddy** [comment]
@Martin15135215 Once my tiny fix for the parsing of ifc duration is in, you should be able to load the example file in. The Gantt Chart generation also works. The animation I can't test. Beyond my skills. Perhaps you can retest, and let us know if it all works as you expect now. If you can respond and we can get this oldest of old bugs closed.

**Comment by Moult** [comment]
So the bug aspect of this report is solved, but there are a few related features requested here that we don't yet support:

 1. Need hour parsing (the example file does PT8H)
 2. Need to constrain start based on parent. We should use this as part of the logic in recalculate schedule.
 3. Recalculate schedule logic can also use early start as a guideline as constraint.

Reclassifying as feature request but won't work on it right now as there are other more critical bugs to address first.
