### ISSUE TITLE
BlenderBim - When printing after editing text box alignment to 'middle-middle' it produces this error

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2793]
Python: Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 180, in execute
    annotation_svg = self.generate_annotation(context)
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 541, in generate_annotation
    self.svg_writer.create_blank_svg(svg_path).draw_annotations(annotations).save()
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 162, in draw_annotations
    self.draw_text_annotation(obj, obj.location)
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 545, in draw_text_annotation
    "text-anchor": text_anchor,
UnboundLocalError: local variable 'text_anchor' referenced before assignment

All other Box alignment configurations do work:

top-left, 
top-right, 
top-middle, 
bottom-left, 
bottom-right, 
bottom-middle, 
middle-left, 
middle-right

**Comment by Moult** [comment]
The keyword is "center", which is derived from CSS. Annoyingly IFC does not fix this as an enumeration, which is why it's hard to discover what the correct values are.

**Comment by Plae-Blue-Dot** [comment]
Thanks for the clarification Moult, my bad, I think I did know that in the past,
