### ISSUE TITLE
 RuntimeError: ERROR:root:unhandled exception occurred

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#2811]
I received a huge ifc with some small errors. A few products where missing the ObjectPlacement entity. The file is huge and I am not the author, thus sharing is difficault but I created a simple ifc to show the problem. It can be downloaded in this post: https://github.com/yorikvanhavre/FreeCAD-NativeIFC/issues/23#issuecomment-1443364204

the following code is handled in IfcOS, if it is put in a try: except everything is fine ... 

```
s = ifcfile[80]
s.ObjectPlacement

try:
    s.ObjectPlacement
except Exception:
    print(False)
```

```
>>> 
>>> s = ifcfile[80]
>>> s.ObjectPlacement
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.21.xxxxx\bin\lib\site-packages\ifcopenshell\entity_instance.py", line 136, in __getattr__
    self.wrapped_data.get_argument(idx), self.wrapped_data.file
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.21.xxxxx\bin\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4833, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Instance #77 not found
>>> 
>>> try:
...     s.ObjectPlacement
... except Exception:
...     print(False)
... 
False
>>> 
```

BUT get.info() raises a unhandled Exception in IfcOpenShell, thus it does not help to put it in a try: except: the unhandled exception is raised anyway ...

```
s = ifcfile[80]
s.get_info()

try:
    s.get_info()
except Exception:
    print(False)
```

```
>>> s = ifcfile[80]
>>> s.get_info()
{'id': 80, 'type': 'IfcSlab', 'GlobalId': '2JwE5lcKXFKvWOrg3uyxKD', 'OwnerHistory': #5=IfcOwnerHistory(#3,#4,$,.ADDED.,1677231549,#3,#4,1677231549), 'Name': 'Structure', 'Description': '', 'ObjectType': None, 'Representation': #79=IfcProductDefinitionShape($,$,(#78)), 'Tag': None, 'PredefinedType': 'NOTDEFINED'}
>>> 
>>> try:
...     s.get_info()
... except Exception:
...     print(False)
... 
{'id': 80, 'type': 'IfcSlab', 'GlobalId': '2JwE5lcKXFKvWOrg3uyxKD', 'OwnerHistory': #5=IfcOwnerHistory(#3,#4,$,.ADDED.,1677231549,#3,#4,1677231549), 'Name': 'Structure', 'Description': '', 'ObjectType': None, 'Representation': #79=IfcProductDefinitionShape($,$,(#78)), 'Tag': None, 'PredefinedType': 'NOTDEFINED'}
>>> 
```

as said in both cases the following unhandled exception is raised ... 

```
21:51:26  ERROR:root:unhandled exception occurred setting attribute name for #80=IfcSlab('2JwE5lcKXFKvWOrg3uyxKD',#5,'Structure','',$,#77,#79,$,.NOTDEFINED.)
Traceback (most recent call last):
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.21.xxxxx\bin\lib\site-packages\ifcopenshell\entity_instance.py", line 477, in _
    attr_value = self[i]
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.21.xxxxx\bin\lib\site-packages\ifcopenshell\entity_instance.py", line 242, in __getitem__
    self.wrapped_data.get_argument(key), self.wrapped_data.file
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.21.xxxxx\bin\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4833, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Instance #77 not found
```

IMHO this should not happen, or am I wrong?

**Comment by berndhahnebach** [comment]
Another question ... How do I get the wrong attribute, because get_info() does ignore this at all and the key is missing in the dictionary.

**Comment by Moult** [comment]
I don't understand, this file is invalid (i.e references step ID 77 but 77 doesn't exist (or is intended to be commented out). So naturally an exception is raised when you try to access it.

So what behaviour would you expect instead?

**Comment by berndhahnebach** [comment]
it is only commented to show the problem of the corrupted entrys in the file I have. Only a few of thousands of objects to have this problem. 

the problem is IfcOpenShell does raise an unhandled exception. It means the exception can not be catched by a try: except if element.get_info() is used. 

Only if the attribute is accessed directly by element.ObjectPlacement the exception which is raised by IfcOpenShell can be catched by a try: except:

IMHO it should be possible to catch the exceptiont for get_info() too. For this something needs to be done inside IfcOpenShell.

**Comment by Moult** [comment]
I don't get an exception here:

```
>>> import ifcopenshell
>>> f = ifcopenshell.open('/home/dion/tmp/no_placement_edited.ifc')
>>> e = f.by_id(80)
>>> e.get_info()
{'id': 80, 'type': 'IfcSlab', 'GlobalId': '2JwE5lcKXFKvWOrg3uyxKD', 'OwnerHistory': #5=IfcOwnerHistory(#3,#4,$,.ADDED.,1677231549,#3,#4,1677231549), 'Name': 'Structure', 'Description': '', 'ObjectType': None, 'Representation': #79=IfcProductDefinitionShape($,$,(#78)), 'Tag': None, 'PredefinedType': 'NOTDEFINED'}
```

... and that's because it's already caught and logged by the logger. Is that not a good solution?

**Comment by aothms** [comment]
> IfcOpenShell does raise an unhandled exception. It means the exception can not be catched by a try: except

This seems not be in line with what I expect. A missing instance is definitely a catchable error. There might be other cases of invalid data that result in hard crashes that we can investigate though.

**Comment by Moult** [comment]
It definitely is a catchable error, so I still don't yet see what the bug is @berndhahnebach  ?

```
>>> import ifcopenshell
>>> f = ifcopenshell.open('/home/dion/tmp/no_placement_edited.ifc')
>>> e = f.by_id(80)
>>> e.ObjectPlacement
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 136, in __getattr__
    self.wrapped_data.get_argument(idx), self.wrapped_data.file
  File "/home/dion/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3737, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Instance #77 not found

>>> try:
...     print(e.ObjectPlacement)
... except RuntimeError:
...     print('Caught!')
...     
Caught!
```

**Comment by berndhahnebach** [comment]
exactly what I have written before ... The way you used it, it could be catched ... BUT ...

The problem is the following. If get_info() is used it is not catchable. Imagine ... Where do you get the ObjectPlacement from? Normally one would use get_info() and use the dict keys to know which attributes are on the entity, but in get_info() an unhandled not catchable exception is raised and the key ObjectPlacement is not in the returned dictionary. This means you do not even know which attribute does have a problem without manually debug it.

I found a workaround but is is not a good one IMHO ... https://github.com/yorikvanhavre/FreeCAD-NativeIFC/pull/26/commits/fc0a84f70d85b1b0ea09415c083685b71290805f  It would be much better to fix get_info() somehow.

Hopefully you guys got my point with this description.

cheers bernd

**Comment by aothms** [comment]
> Hopefully you guys got my point with this description.

yes and no, so the issue is:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/entity_instance.py#L505-L510

But what is the request? Is it to add something like a keyword argument `catch_exceptions=True` so that you can override this to false and have the exception bubble up to client code instead of being logged?

To reproduce (or create a test later):

```
>>> import ifcopenshell
>>> import ifcopenshell.template
>>> ifcopenshell.file.from_string(ifcopenshell.template.create().to_string().replace("#19=", "#1000=")).by_type('ifcproject')[0].get_info()
ERROR:root:unhandled exception occurred setting attribute name for #20=IfcProject('1VVKlWgtb3PPNhBotUXhKs',#5,'',$,$,$,$,(#11),#19)
Traceback (most recent call last):
  File "C:\Users\tkrij\miniconda3\envs\ifopsh07\lib\site-packages\ifcopenshell\entity_instance.py", line 376, in _
    attr_value = self[i]
  File "C:\Users\tkrij\miniconda3\envs\ifopsh07\lib\site-packages\ifcopenshell\entity_instance.py", line 222, in __getitem__
    self.wrapped_data.get_argument(key), self.wrapped_data.file
  File "C:\Users\tkrij\miniconda3\envs\ifopsh07\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4833, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Instance #19 not found
{'id': 20, 'type': 'IfcProject', 'GlobalId': '1VVKlWgtb3PPNhBotUXhKs', 'OwnerHistory': #5=IfcOwnerHistory(#3,#4,$,.ADDED.,$,#3,#4,1677575739), 'Name': '', 'Description': None, 'ObjectType': None, 'LongName': None, 'Phase': None, 'RepresentationContexts': (#11=IfcGeometricRepresentationContext($,'Model',3,1.E-05,#9,#10),)}
```

In line with this request it would be interesting to consider also validating the output, because now it will happily give you wrongly typed data:

```
>>> ifcopenshell.file.from_string(ifcopenshell.template.create(project_globalid='a').to_string().replace("'a'", "3")).by_type('ifcproject')[0].get_info()
{'id': 20, 'type': 'IfcProject', 'GlobalId': 3, 'OwnerHistory': #5=IfcOwnerHistory(#3,#4,$,.ADDED.,$,#3,#4,1677576030), 'Name': '', 'Description': None, 'ObjectType': None, 'LongName': None, 'Phase': None, 'RepresentationContexts': (#11=IfcGeometricRepresentationContext($,'Model',3,1.E-05,#9,#10),), 'UnitsInContext': #19=IfcUnitAssignment((#13,#14,#15,#18))}
```

> 'GlobalId': 3

**Comment by berndhahnebach** [comment]
1.) most important would be to get all attribute keys of an entity even if the value of a attribute is wrong without even raise some exception at all.
2.) good question ... In the workaround I use the wrong value is replaced by a Errorstring and I am informed about a wrong value on a certain attribut by the exception message.  ... I do not know if this is a good solution.

may be @yorikvanhavre  could jump in ...

**Comment by aothms** [comment]
> 1.) most important would be to get all attribute keys of an entity even if the value of a attribute is wrong without even raise some exception at all.

Ok that's also an option. We could simply create a class or sth:

```python
class invalid_value:
  def __str__(self): return '*invalid*'
```

One issue would be that that break naive json serialization:

```python
json.dumps(inst.get_info(recursive=True))
``` 

Because the default json encoder in python is very picky in terms of what types of values it excepts. So even that would have to be behind some keyword argument like: `flag_invalid_values=True`. It would make sense then to also validate the values so that a user has a somewhat consistent assignment of these invalid values, not just when an entity instance happens to be missing but also when the wrong type of value is assigned.

**Comment by Moult** [comment]
Just my $0.02 is that this type of error is a fundamental STEP syntax error (referencing a nonexisting number) and that being undefined behaviour I think it's not necessary to be so strict in the get_info() function (which is a relatively high level function for most of the core features anyway). After all that's what the validate() function is for which should catch issues like this.

**Comment by berndhahnebach** [comment]
The main question I am not sure about is how OpenSource IfcOpenShell based viewer should handle such case upon opening the file. Mainly the ifcos file object based Software BlenderBIM and FreeCAD native IFC ... 

How does BlenderBIM handles the problem intern? Deos it just ignors the missing ObjectPlacement? If I import the file into BlenderBIM there is no error or warning (but eventually no viewer I have tested reports an Error or Warning except FreeCAD native IFC). In BlenderBIM even the ObjectPlacement seams fine (but I might be wrong because I am very bad in BlenderBIM Gui). If the ifc is exported out of BlenderBIM back to ifc the entity is still missing.  This makes sense because BlenderBIM just saves back the ifcos file. Than in the header there is written BlenderBIM. Means the normal user would think BlenderBIM has made a Error but the error was there before the ifc was opened in BlenderBIM.

**Comment by Moult** [comment]
In this particular case it so happens that we ignore it since we rely on the iterator. However I'm personally not fussed about catching syntax errors like these because they're syntax errors. I'm not a fan of defensive coding at this level.

Once that save it from Blender (i.e. run file.write()) then the syntax error should disappear. It's still invalid though, as you need to have a placement if there is a representation, but you can't fix everything for them.

**Comment by berndhahnebach** [comment]
> In this particular case it so happens that we ignore it since we rely on the iterator.

Would you point to the code how BlenderBIM reads the attrib, values of a entity?


If you open the file in BlenderBIM an browse the gui, do you see the ObjectPlacement of the opened file has some problems or would you think everything is fine.

**Comment by yorikvanhavre** [comment]
I kind of agree with @Moult and @aothms actually... Basically something saying go to item 77 and item 77 is missing should raise an exception. That's the behaviour we have all around IfcOpenShell.

But it would be indeed cool to be able to process a bad IFC file with the iterator in an error-tolerant manner. We have implemented a workaround in FreeCAD ( https://github.com/yorikvanhavre/FreeCAD-NativeIFC/issues/23 ) - basically not relying on get_info() inside the iterator, which is fine for us, but I'm wondering if there is a more efficient way here...

**Comment by Moult** [comment]
@yorikvanhavre get_info() already is error tolerant, it [catches and logs errors](https://github.com/IfcOpenShell/IfcOpenShell/issues/2811#issuecomment-1445500166). @berndhahnebach wants it _not_ to catch and log the error, so he can catch it himself, I think.

**Comment by yorikvanhavre** [comment]
> @yorikvanhavre get_info() already is error tolerant, it catches and logs errors

According to Bernd it does not inside the iterator... would it be a different version?

**Comment by berndhahnebach** [comment]
I just realised we might have some missunderstanding ... 

The problem is get_info() catches the error internally in IfcOpenShell and passes it to the logger, thus in python console nothing happens. The key of the corrupted value will be ignored in the dictionary. BUT in FreeCAD the logger output seam to be printed in the report console. Thus any normal user sees something has been gone wrong. I wanted to get rid of this, but IfcOpenShell is not responsible how FreeCAD handles logger output.

Eventually all reduces to two questrions from my side:

How is it possible to get ALL attribute keys of a entity even if a value is corupted?

Is it possible to get the value of a key without following the link to the entity. Means if ther is written `#88` I would not like to get the entity 88 but the string ´#88`

**Comment by berndhahnebach** [comment]
```

Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)] on win32
Type 'help', 'copyright', 'credits' or 'license' for more information.
>>> 
>>> import ifcopenshell
>>> f = ifcopenshell.open('C:/Users/BHA/Desktop/no_placement_edited.ifc')
>>> e = f.by_id(80)
>>> e.get_info()
{'id': 80, 'type': 'IfcSlab', 'GlobalId': '2JwE5lcKXFKvWOrg3uyxKD', 'OwnerHistory': #5=IfcOwnerHistory(#3,#4,$,.ADDED.,1677231549,#3,#4,1677231549), 'Name': 'Structure', 'Description': '', 'ObjectType': None, 'Representation': #79=IfcProductDefinitionShape($,$,(#78)), 'Tag': None, 'PredefinedType': 'NOTDEFINED'}

ERROR:root:unhandled exception occurred setting attribute name for #80=IfcSlab('2JwE5lcKXFKvWOrg3uyxKD',#5,'Structure','',$,#77,#79,$,.NOTDEFINED.)
Traceback (most recent call last):
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.21.xxxxx\bin\lib\site-packages\ifcopenshell\entity_instance.py", line 477, in _
    attr_value = self[i]
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.21.xxxxx\bin\lib\site-packages\ifcopenshell\entity_instance.py", line 242, in __getitem__
    self.wrapped_data.get_argument(key), self.wrapped_data.file
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.21.xxxxx\bin\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4833, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Instance #77 not found
>>> 
>>> try:
...     e.get_info()
... except:
...     print(False)
... 
{'id': 80, 'type': 'IfcSlab', 'GlobalId': '2JwE5lcKXFKvWOrg3uyxKD', 'OwnerHistory': #5=IfcOwnerHistory(#3,#4,$,.ADDED.,1677231549,#3,#4,1677231549), 'Name': 'Structure', 'Description': '', 'ObjectType': None, 'Representation': #79=IfcProductDefinitionShape($,$,(#78)), 'Tag': None, 'PredefinedType': 'NOTDEFINED'}

ERROR:root:unhandled exception occurred setting attribute name for #80=IfcSlab('2JwE5lcKXFKvWOrg3uyxKD',#5,'Structure','',$,#77,#79,$,.NOTDEFINED.)
Traceback (most recent call last):
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.21.xxxxx\bin\lib\site-packages\ifcopenshell\entity_instance.py", line 477, in _
    attr_value = self[i]
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.21.xxxxx\bin\lib\site-packages\ifcopenshell\entity_instance.py", line 242, in __getitem__
    self.wrapped_data.get_argument(key), self.wrapped_data.file
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.21.xxxxx\bin\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4833, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Instance #77 not found
>>> 
>>> 
```

**Comment by berndhahnebach** [comment]
![grafik](https://user-images.githubusercontent.com/6129869/222474452-b6cad5fc-7aa5-451d-9b96-d41fb652a3d1.png)

**Comment by Moult** [comment]
According to https://docs.python.org/3/howto/logging.html#when-to-use-logging I think the usage of logging.exception is appropriate. `get_info()` is a relatively high level function for the core, used in many scenarios, which I don't think it is acceptable to expect users to wrap every get_info call in a try except in case things go wrong. So the exception suppression sounds reasonable to me.

If the user wants to really ensure valid data, instead of checking for validity on every get_info call, there is the ifcopenshell.validate module which does this for you.

So in my opinion your issue is not so much that errors are logged, is more a FreeCAD issue that you don't want errors logged to your Python console. I find that odd, because I think I'd want to know if my file was causing errors to be spewed out in a log. But you can also easily suppress it with a logging filter:

```python
import logging
import ifcopenshell

f = ifcopenshell.open('/home/dion/tmp/no_placement_edited.ifc')
e = f.by_id(80)

class ExceptionFilter(logging.Filter):
    def filter(self, record):
        return not record.exc_info

handler = logging.StreamHandler()
logging.root.addHandler(handler)
handler.addFilter(ExceptionFilter())

# Regular logging is uninterrupted
logging.error('Blah')

# Exception is caught and log is filtered out.
print(e.get_info())
```

The possibly annoying thing here is that  ifcopenshell does not define module level loggers. @aothms maybe we should? As a result you need to filter the root logger.

**Comment by Moult** [comment]
> How is it possible to get ALL attribute keys of a entity even if a value is corupted without any error at all?

```
e = f.by_id(80)
print([a.name() for a in e.wrapped_data.declaration().as_entity().all_attributes()])
```

> Is it possible to get the value of a key without following the link to the entity. Means if there is written #88 I would NOT like to get the entity 88 but the string #88

Not by any easy means I'm aware of. You can get the original line via `str(e)` and I suspect there might be some lark rules or a function you can use in https://github.com/IfcOpenShell/step-file-parser but I haven't looked in detail.

**Comment by aothms** [comment]
> Not by any easy means I'm aware of. You can get the original line via str(e) and I suspect there might be some lark rules or a function you can use in https://github.com/IfcOpenShell/step-file-parser but I haven't looked in detail.

Correct, I also think that's the only way.

I still think we can also add the following params to get_info():

- `flag_invalid_values=False` to get complete dict keys with specific values 
- `catch_exceptions=True` to switch between logging and raising client-code exceptions

But as pointed out by Dion this is a fairly high level function and validity is better handled at a lower level. One thing I think would also be interesting is an interface to ifcopenshell.validate with recipes to fix thing. So missing instance on placement can be programmed to create it from the spatial hierarchy and inserting it at the container placement. Missing or invalid guid (just another example) can also be addressed. But that would best be a separate process that people can configure (and use in other workflows too).

**Comment by Moult** [comment]
I'm not a huge fan of adding more bool arguments in general, can I instead suggest creating a module-level logger that users can do whatever they want to filter exceptions (in lieu of catch_exceptions)?

The oneliner `data = {a.name(): None for a in e.wrapped_data.declaration().as_entity().all_attributes()} \n data.update(e.get_info())` should get the behaviour @berndhahnebach might want in lieu of flag_invalid_values.

**Comment by aothms** [comment]
> The oneliner data = {a.name(): None for a in e.wrapped_data.declaration().as_entity().all_attributes()} \n data.update(e.get_info()) should get the behaviour @berndhahnebach might want in lieu of flag_invalid_values.

Not recursively though..

**Comment by BIMvoice** [comment]
Resolved on the current v0.8 line. A dangling attribute reference now resolves to None rather than raising, and get_info() handles it: opening a file whose IfcWall.ObjectPlacement points at a missing instance gives inst.ObjectPlacement == None and inst.get_info() returns a normal dict with no RuntimeError (get_info also takes an ignore parameter). Recommend closing as fixed.
