### ISSUE TITLE
BlenderBim- error when printing certain drawings in Ifc to SVG

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2836]
When printing a large 1:50 drawing to SVG and a larger drawing (site plan) to SVG, this error appears:

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 177, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 460, in generate_linework
    self.merge_linework_and_add_metadata(root)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 537, in merge_linework_and_add_metadata
    polygons.append(shapely.Polygon(coords))
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\shapely\geometry\polygon.py", line 230, in __new__
    shell = LinearRing(shell)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\shapely\geometry\polygon.py", line 104, in __new__
    geom = shapely.linearrings(coordinates)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\shapely\decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\shapely\creation.py", line 173, in linearrings
    return lib.linearrings(coords, out=out, **kwargs)
ValueError: A linearring requires at least 4 coordinates.

**Comment by Moult** [comment]
Is it possible to share the file? This is related to the hatch merging feature which clearly needs more battle testing.

**Comment by Plae-Blue-Dot** [comment]
Yes, private file, it's just sent it, thanks Dion!
