### ISSUE TITLE
ifctester with 'IfcPropertyEnumeratedValue'

### ISSUE THREAD

**Issue by ay-ex** [IfcOpenShell/IfcOpenShell#2877]
Running the vanilla [snippet](https://github.com/IfcOpenShell/IfcOpenShell/blob/31600033bf218c21ec6dab2a4b8eee2d9fa30f4b/src/ifctester/README.md) from ifctester, to create fresh ids 
and run the spec as test on a sample ifc works fine. 
When trying it with a made up enumeration of values like this: 

```python
import ifcopenshell
from ifctester import ids, reporter

# create new IDS
my_ids = ids.Ids(title="My IDS")

# add specification to it
my_spec = ids.Specification(name="My first specification")
my_spec.applicability.append(ids.Entity(name="IFCWALL"))
property = ids.Property(
    name="FireRating", 
    value=["EI30","EI60"],
    propertySet="Pset_WallCommon",
    measure="IfcPropertyEnumeratedValue",
    uri="https://identifier.buildingsmart.org/uri/.../prop/LoadBearing",
    instructions="Walls need FireRating of either EI30 or EI60."
)
# * All IfcWall elements have an Pset_WallCommon.FireRating property
my_spec.requirements.append(property)
my_ids.specifications.append(my_spec)

# Save such IDS to file
result = my_ids.to_xml("d:/tmp/ids/enum_test.ids")

# open  IFC file:
my_ifc = ifcopenshell.open("d:/tmp/ids/sample.ifc")

# validate IFC model against IDS requirements:
my_ids.validate(my_ifc)

# show results:
reporter.Console(my_ids).report()
```
I get the following error: 

```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifctester\ids.py", line 112, in to_xml
    ET.ElementTree(get_schema().encode(self.asdict())).write(filepath, encoding="utf-8", xml_declaration=True)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifctester\ids.py", line 89, in asdict
    ids_dict["specifications"]["specification"].append(spec.asdict())
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifctester\ids.py", line 166, in asdict
    results[clause_type][facet_type] = [facet.asdict()]
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifctester\facet.py", line 57, in asdict
    results[name] = value if "@" in name else self.to_ids_value(value)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifctester\facet.py", line 101, in to_ids_value
    restrictions = {"@base": "xs:" + parameter[0].base}
AttributeError: 'str' object has no attribute 'base'
```

but maybe my assumption of `List[str]` for kwarg `value` was wrong?

It seems however, that the report run works fine. 🤔 

If I could get it to work I would happily add an example 
with enumeration to the documentation.

**Comment by Moult** [comment]
Are you after two possible values? If so use a restriction: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifctester/test/test_facet.py#L182

**Comment by ay-ex** [comment]
Ah in tests. Ok nice - works like a charm!!  
And there are also examples for patterns. ☺️ 
Thank you so much!!

**Comment by ay-ex** [comment]
..added for completeness, the working snippet would be: 
```python
import ifcopenshell
from ifctester import ids, reporter

# create new IDS
my_ids = ids.Ids(title="My IDS")

# add specification to it
my_spec = ids.Specification(name="My first specification")
my_spec.applicability.append(ids.Entity(name="IFCWALL"))
property = ids.Property(
    name="FireRating", 
    value=ids.Restriction(options={"enumeration": ["EI30","EI60"]}),
    propertySet="Pset_WallCommon",
    measure="IfcPropertyEnumeratedValue",
    uri="https://identifier.buildingsmart.org/uri/.../prop/FireRating",
    instructions="Walls need FireRating of either EI30 or EI60.",
)
# * All IfcWall elements have an Pset_WallCommon.FireRating property
my_spec.requirements.append(property)
my_ids.specifications.append(my_spec)

# Save such IDS to file
result = my_ids.to_xml("d:/tmp/ids/enum_test.ids")

# open IFC file:
my_ifc = ifcopenshell.open("d:/tmp/ids/sample.ifc")

# validate IFC model against IDS requirements:
my_ids.validate(my_ifc)

# show results:
reporter.Console(my_ids).report()
```

**Comment by ay-ex** [comment]
Sorrry for re-opening, maybe I was too quick: 
With: 
```python
import ifcopenshell
from ifctester import ids, reporter

# create new IDS
my_ids = ids.Ids(title="My IDS")

# add specification to it
my_spec = ids.Specification(name="My first specification")
my_spec.applicability.append(ids.Entity(name="IFCWALL"))
property = ids.Property(
    name="FireRating", 
    value=ids.Restriction(options={"enumeration": ["EI30","EI60","FOOBAR"]}), # working enum
    #value=ids.Restriction(options={"pattern": "EI.{1,2}0"}),
    propertySet="Pset_WallCommon",
    measure="IfcPropertyEnumeratedValue",
    uri="https://identifier.buildingsmart.org/uri/.../prop/FireRating",
    instructions="Walls need to be load bearing."
)
# * All IfcWall elements have an Pset_WallCommon.FireRating property
my_spec.requirements.append(property)
my_ids.specifications.append(my_spec)

# Save such IDS to file
result = my_ids.to_xml("d:/tmp/ids/enum_test.ids")

# open IFC file:
my_ifc = ifcopenshell.open("d:/tmp/ids/sample.ifc")

# validate IFC model against IDS requirements:
my_ids.validate(my_ifc)

# show results:
reporter.Console(my_ids).report()
```

I do not get any errors anymore, for creating the ids or testing the file.
The ids itself looks good to me:

```xml
<?xml version='1.0' encoding='utf-8'?>
<ids xmlns="http://standards.buildingsmart.org/IDS" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.buildingsmart.org/IDS/ids_05.xsd">
    <info>
        <title>My IDS</title>
    </info>
    <specifications>
        <specification name="My first specification" ifcVersion="IFC2X3 IFC4" minOccurs="0" maxOccurs="unbounded">
            <applicability>
                <entity>
                    <name>
                        <simpleValue>IFCWALL</simpleValue>
                    </name>
                </entity>
            </applicability>
            <requirements>
                <property measure="IfcPropertyEnumeratedValue" uri="https://identifier.buildingsmart.org/uri/.../prop/FireRating" instructions="Walls Pset_WallCommon.FireRating need to be one of either: 'EI30','EI60','FOOBAR'." minOccurs="1" maxOccurs="1">
                    <propertySet>
                        <simpleValue>Pset_WallCommon</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>FireRating</simpleValue>
                    </name>
                    <value>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="EI30" />
                            <xs:enumeration value="EI60" />
                            <xs:enumeration value="FOOBAR" />
                        </xs:restriction>
                    </value>
                </property>
            </requirements>
        </specification>
    </specifications>
</ids>
```

Also:
`FireRating data shall be {'enumeration': ['EI30', 'EI60', 'FOOBAR']} and in the dataset Pset_WallCommon`
in the html report reads fine.

But the wall that has 'FOOBAR' actually gets flagged as wrong:
`The data type "IfcLabel" does not match the requirements #96=IfcWall('1iuBEMYbL5q8FLrEdzU7CF',$,'WALL 4',$,$,#120,#110,$,.NOTDEFINED.)`

telling me there is a datatype IfcLabel which is mismatching. 🤔  
I thought `Pset_WallCommon.FireRating` is a string?

**Comment by Moult** [comment]
The data type (measure type) of a FireRating is an IfcLabel: https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/Pset_WallCommon.htm so you'll need to set `measure="IfcLabel",` :)

**Comment by ay-ex** [comment]
Oh I see - I should have looked there as well, not only at the bbim python hint. 
And now it all works as expected: 

```python
import ifcopenshell
from ifctester import ids, reporter

# create new IDS
my_ids = ids.Ids(title="My IDS")

# add specification to it
my_spec = ids.Specification(name="My first specification")
my_spec.applicability.append(ids.Entity(name="IFCWALL"))
property = ids.Property(
    name="FireRating", 
    value=ids.Restriction(options={"enumeration": ["EI30","EI60","FOOBAR"]}), # working enum
    #value=ids.Restriction(options={"pattern": "EI.{1,2}0"}),
    propertySet="Pset_WallCommon",
    measure="IfcLabel",
    uri="https://identifier.buildingsmart.org/uri/.../prop/FireRating",
    instructions="Walls Pset_WallCommon.FireRating need to be one of either: 'EI30','EI60','FOOBAR'."
)
# * All IfcWall elements have an Pset_WallCommon.FireRating property
my_spec.requirements.append(property)
my_ids.specifications.append(my_spec)

# Save such IDS to file
result = my_ids.to_xml("d:/tmp/ids/enum_test.ids")

# open IFC file:
my_ifc = ifcopenshell.open("d:/tmp/ids/sample.ifc")

# validate IFC model against IDS requirements:
my_ids.validate(my_ifc)

# show results:
reporter.Console(my_ids).report()
```

Thank you @Moult !
