### ISSUE TITLE
IFC selector - error

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2901]
Not sure this is a bug or user error...

video: https://www.dropbox.com/s/2ey5kxq0vtkcytc/2023-03-23_12-25-22_Blender_blender.mp4?dl=0

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\search\operator.py", line 478, in execute
    selection = selection_props.selector_query_syntax if selection_props.manual_override else self.add_groups(selection_props)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\search\operator.py", line 491, in add_groups
    selection = self.add_queries(selection, group)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\search\operator.py", line 504, in add_queries
    selection = self.add_filters(selection, query)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\search\operator.py", line 525, in add_filters
    if value in ("True", "False"):
UnboundLocalError: local variable 'value' referenced before assignment

```

**Comment by Moult** [comment]
I'd like to redesign the search UI to be more friendly. It seems a tad complex right now. That's kinda putting me off adding a bunch of tests related to this :(
