### ISSUE TITLE
BlenderBIM error on bpy.ops.bim.override_object_join()

### ISSUE THREAD

**Issue by ay-ex** [IfcOpenShell/IfcOpenShell#2916]
@Moult I tried the new bbim override object join `bpy.ops.bim.override_object_join()` with some elements similar to the one described in  https://github.com/IfcOpenShell/IfcOpenShell/issues/2913 , but it throws the error below.
the ifc exported after the error crashes blender on opening.

```python
>>> bpy.ops.bim.override_object_join()
Error: Python: Traceback (most recent call last):
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 41, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\ifc.py", line 428, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 630, in _execute
    return self.join_ifc_obj()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 682, in join_ifc_obj
    core.switch_representation(
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\core\geometry.py", line 102, ... truncated
Traceback (most recent call last):
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 41, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\ifc.py", line 428, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 630, in _execute
    return self.join_ifc_obj()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 682, in join_ifc_obj
    core.switch_representation(
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\core\geometry.py", line 102, in switch_representation
    data = geometry.import_representation(obj, representation, apply_openings=apply_openings)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\tool\geometry.py", line 222, in import_representation
    ifc_importer.material_creator.create(element, obj, mesh)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\import_ifc.py", line 73, in create
    self.assign_material_slots_to_faces()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\import_ifc.py", line 147, in assign_material_slots_to_faces
    slot_index = self.obj.material_slots.find(self.styles[material].name)
KeyError: 131
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\ProgramData\portable\blender-3.4.1\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 41, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\ifc.py", line 428, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 630, in _execute
    return self.join_ifc_obj()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 682, in join_ifc_obj
    core.switch_representation(
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\core\geometry.py", line 102, in switch_representation
    data = geometry.import_representation(obj, representation, apply_openings=apply_openings)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\tool\geometry.py", line 222, in import_representation
    ifc_importer.material_creator.create(element, obj, mesh)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\import_ifc.py", line 73, in create
    self.assign_material_slots_to_faces()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\import_ifc.py", line 147, in assign_material_slots_to_faces
    slot_index = self.obj.material_slots.find(self.styles[material].name)
KeyError: 131
Location: C:\ProgramData\portable\blender-3.4.1\3.4\scripts\modules\bpy\ops.py:113

```

**Comment by Moult** [comment]
Yes I think I didn't test joining with materials. Good catch.

**Comment by Gorgious56** [comment]
I've also got an error on join. 

Steps to reproduce :
Brand new file, no ifc file loaded.  
Add 2 cubes. 
Join them with CTRL + J. Error:
```
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 41, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 422, in execute_ifc_operator
    IfcStore.get_file().begin_transaction()
AttributeError: 'NoneType' object has no attribute 'begin_transaction'
Error: Python: Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 41, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 422, in execute_ifc_operator
    IfcStore.get_file().begin_transaction()
AttributeError: 'NoneType' object has no attribute 'begin_transaction'
```

What's weird is this error only happens once, and if the user tries to use CTRL - J again it works as expected.
