### ISSUE TITLE
error when bim.unlink_object()

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2938]
file: [test.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11154650/test.txt)

![2023-04-04_21-28-45_KeyShowView_Carnac](https://user-images.githubusercontent.com/507113/229965761-dd9bf053-6357-4b12-b43d-9ca119768ac5.gif)

**Comment by theoryshaw** [comment]
```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\project\operator.py", line 832, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\project\operator.py", line 848, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\ifc.py", line 428, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\project\operator.py", line 879, in _execute
    ifc_exporter.export()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\export_ifc.py", line 49, in export
    self.sync_all_objects()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\export_ifc.py", line 115, in sync_all_objects
    result = self.sync_object_material(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\export_ifc.py", line 146, in sync_object_material
    bpy.ops.bim.update_representation(obj=obj.name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 41, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\ifc.py", line 428, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 171, in _execute
    self.update_obj_mesh_representation(context, obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 253, in update_obj_mesh_representation
    core.remove_representation(tool.Ifc, tool.Geometry, obj=obj, representation=old_representation)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\core\geometry.py", line 140, in remove_representation
    ifc.run("geometry.remove_representation", representation=representation)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\tool\ifc.py", line 30, in run
    return ifcopenshell.api.run(command, IfcStore.get_file(), **kwargs)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\remove_representation.py", line 42, in execute
    ifcopenshell.util.element.remove_deep2(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\element.py", line 784, in remove_deep2
    ifc_file.unbatch()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 449, in unbatch
    return self.wrapped_data.unbatch()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4589, in unbatch
    return _ifcopenshell_wrapper.file_unbatch(self)
RuntimeError: Instance #42,064 not found
Location: C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py:113

```
