### ISSUE TITLE
Error on creating a new drawing sheet when not on c:// drive

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#2963]
When clicking the "+" button to add a new sheet, I got this error :

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 80, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 429, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 709, in _execute
    core.add_sheet(tool.Ifc, tool.Drawing, titleblock=context.scene.DocProperties.titleblock)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\drawing.py", line 88, in add_sheet
    drawing.create_svg_sheet(sheet, titleblock)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\drawing.py", line 140, in create_svg_sheet
    sheet_builder.create(uri, titleblock)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\sheeter.py", line 53, in create
    titleblock.attrib["xlink:href"] = os.path.relpath(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.5\python\lib\ntpath.py", line 744, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'D:'
```

I am indeed modifying an ifc file on drive D://. If I work on a file in drive C:// I don't get any error on new sheet creation. Windows 11.

**Comment by Gorgious56** [comment]
Yup, fixed. Cheers
