### ISSUE TITLE
'IFC4.IfcSpace' has no attribute 'HasOpenings'

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#2964]
I don't really know when this issue was introduced but when you edit an `IfcSpace` geometry you get an error message at following line in code: https://github.com/IfcOpenShell/IfcOpenShell/blob/352d6b5ef9b9a8176a5ebc1c8b16590c3ef669f2/src/blenderbim/blenderbim/bim/module/geometry/operator.py#L821
Not all ifc class have `HasOpening` attribute so I see how I could fix it but don't want to without knowing what was the intent (@Moult ?).

## Steps to reproduce
1. Create a Mesh/Cube
2. Assign `IfcSpace` class to it
3. Press TAB to edit mesh geometry : eg. change top face height using gz
5. Press TAB to quit edit mesh then ok on prompt
## Error message
```python
Traceback (most recent call last):
  File "/home/cyril/.config/blender/3.5/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 815, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/cyril/.config/blender/3.5/scripts/addons/blenderbim/bim/ifc.py", line 429, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/cyril/.config/blender/3.5/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 821, in _execute
    if tool.Ifc.get_entity(obj).HasOpenings:
  File "/home/cyril/.config/blender/3.5/scripts/modules/ifcopenshell/entity_instance.py", line 173, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcSpace' has no attribute 'HasOpenings'. Did you mean: 'HasCoverings'?
Error: Python: Traceback (most recent call last):
  File "/home/cyril/.config/blender/3.5/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 815, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/cyril/.config/blender/3.5/scripts/addons/blenderbim/bim/ifc.py", line 429, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/cyril/.config/blender/3.5/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 821, in _execute
    if tool.Ifc.get_entity(obj).HasOpenings:
  File "/home/cyril/.config/blender/3.5/scripts/modules/ifcopenshell/entity_instance.py", line 173, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcSpace' has no attribute 'HasOpenings'. Did you mean: 'HasCoverings'?
```

**Comment by Moult** [comment]
Ah yes in this case it is safe to do a getattr(). Would you like to do a PR?
