### ISSUE TITLE
Error when duplicating a drawing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2975]
Error when duplicating a drawing
file: [Clothing_Boutique.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11217864/Clothing_Boutique.txt)

video: https://www.dropbox.com/s/1vrgomfse8ggmzr/2023-04-12_22-26-28_Blender_blender.mp4?dl=0

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1032, in execute
    core.sync_references(tool.Ifc, tool.Collector, tool.Drawing, drawing=tool.Ifc.get().by_id(self.drawing))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\core\drawing.py", line 367, in sync_references
    annotation = drawing_tool.generate_reference_annotation(drawing, reference_element, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\tool\drawing.py", line 855, in generate_reference_annotation
    return cls.generate_section_reference_annotation(drawing, reference_element, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\tool\drawing.py", line 928, in generate_section_reference_annotation
    bounds = helper.ortho_view_frame(camera.data) if camera.data.type == "ORTHO" else None
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\helper.py", line 304, in ortho_view_frame
    scale = parse_diagram_scale(camera)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\helper.py", line 282, in parse_diagram_scale
    _, fraction = camera.BIMCameraProperties.custom_diagram_scale.split("|")
ValueError: not enough values to unpack (expected 2, got 1)

```

**Comment by theoryshaw** [comment]
related:

https://www.dropbox.com/s/pxo1y8vlbmb2q0x/2023-04-12_22-33-00_Blender_blender.mp4?dl=0

create new drawings... defaults to 1/8"=1'-0"... save.. open... and it switches back to custom scale 1/100.
