### ISSUE TITLE
error with bim.create_drawing()

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2978]
[Clothing_Boutique.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11222191/Clothing_Boutique.txt)

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 166, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 210, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 321, in generate_linework
    svg_path = self.get_svg_path(cache_type="linework")
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 665, in get_svg_path
    drawing_path = tool.Drawing.get_document_uri(self.camera_document)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\tool\drawing.py", line 268, in get_document_uri
    if document.is_a("IfcDocumentInformation"):
AttributeError: 'NoneType' object has no attribute 'is_a'
```

**Comment by theoryshaw** [comment]
crashes on newly created files as well
https://www.dropbox.com/s/5vyrdufrr4lriyv/2023-04-13_11-08-22_Blender_blender.mp4?dl=0

**Comment by theoryshaw** [comment]
With the new commit, was able to delete most of the drawings, except those circled below...

latest file: https://gitlab.com/openingdesign/clothing_boutique/-/blob/a760fd0156a082495ddefdb6ead95318726334d5/Clothing_Boutique.ifc

![image](https://user-images.githubusercontent.com/507113/231930556-0a63d2fb-d087-4364-a374-ff9560ace453.png)

**Comment by Moult** [comment]
Do you install the BlenderBIM Add-on fresh from a Github release or do you have symlinks / some dev setup where IfcOpenShell is referenced somehow?

**Comment by theoryshaw** [comment]
work!  Thanks Dion. 

https://gitlab.com/openingdesign/clothing_boutique/-/commit/8fe60f60aace0d3309d1e1cf28873bd88f73a1ec
