### ISSUE TITLE
error when bpy.ops.bim.add_drawing()

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3003]
error when bpy.ops.bim.add_drawing()

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 81, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 96, in _execute
    core.add_drawing(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\core\drawing.py", line 192, in add_drawing
    if drawing.get_unit_system == "METRIC":
AttributeError: type object 'Drawing' has no attribute 'get_unit_system'

```
I tired to solve this. :\

**Comment by Moult** [comment]
Sorry it was late last night :(
