### ISSUE TITLE
BlenderBim - Revit sample Ifc file won't print drawing

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3030]
When attempting to use an exported IFC from the revit sample file,
create a drawing the cut preview appears fine:

![image](https://user-images.githubusercontent.com/78321676/233045229-b6ab5ef9-1fc0-4fb7-a002-d61338144b01.png)
![image](https://user-images.githubusercontent.com/78321676/233045302-2cffddc8-6e3d-49d3-99af-d8597b808304.png)

When printing, we receive this error:

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 166, in invoke
    return self.execute(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 211, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 494, in generate_linework
    self.merge_linework_and_add_metadata(root)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 583, in merge_linework_and_add_metadata
    merged_polygons = shapely.ops.unary_union(polygons)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\shapely\ops.py", line 135, in unary_union
    return shapely.union_all(geoms, axis=None)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\shapely\decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\shapely\set_operations.py", line 426, in union_all
    return lib.unary_union(collections, **kwargs)
shapely.errors.GEOSException: TopologyException: side location conflict at 204.59999999999999 294.89999999999998. This can occur if the input geometry is invalid.

Using Blender 3.5
BlenderBim 23.04.17

The file was exported from Revit 2022 using the ifc4 design transfer view

I've attached the exported Ifc as a txt file

[racbasicsampleproject.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11271866/racbasicsampleproject.ifc.txt)

EDIT:
It does seem to print at an orthographic scale of 5, but nothing bigger

model:
![image](https://user-images.githubusercontent.com/78321676/233050503-c1c8a63b-bea9-4ca8-bd9b-b4a9773990a3.png)

svg:
![image](https://user-images.githubusercontent.com/78321676/233050459-229b7c3c-afa6-47e5-bdd9-469d2cafbdad.png)

Camera details:
![image](https://user-images.githubusercontent.com/78321676/233051226-5365b901-788a-444e-bbcb-a597640a2a22.png)

**Comment by Plae-Blue-Dot** [comment]
Thanks for the work @Moult 

Using BlenderBim-230429,

We can get the full plan printed!
![image](https://user-images.githubusercontent.com/78321676/235314601-d354cfa2-18ca-46d7-ac98-27bc588d696a.png)

Not a major issue but the lvl 1 plan doesn't seem to have a cut preview anymore I don't know if that's because it is cutting the landscape or what the problem might be
![image](https://user-images.githubusercontent.com/78321676/235314728-3dce2c4f-0078-43dd-b9f4-d5990855c6ae.png)

The next floors seems to have no issue previewing on the same file:
![image](https://user-images.githubusercontent.com/78321676/235314756-08eb98e0-7a81-40f1-a1ce-354d3ab0315f.png)
