### ISSUE TITLE
BlenderBim - cannot edit wall in imported revit sample file

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3031]
When attempting to edit a wall in the Revit sample file exported to IFC

First issue
Using the Bim tool to extend a wall with shift E
Wall is simply deselected no error

Second issue
When attempting to adjust a wall with shift E
We get this error:

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 378, in invoke
    return self.execute(context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 370, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 433, in hotkey_S_E
    bpy.ops.bim.join_wall(join_type="T")
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\wall.py", line 68, in _execute
    joiner.join_E(context.active_object, context.scene.cursor.location)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\wall.py", line 997, in join_E
    self.recreate_wall(element1, wall1, axis, body)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\wall.py", line 1082, in recreate_wall
    self.join(
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\wall.py", line 1236, in join
    extrusion2 = self.get_extrusion_data(body2)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\wall.py", line 1209, in get_extrusion_data
    item = representation.Items[0]
AttributeError: 'NoneType' object has no attribute 'Items'
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\3.5\scripts\modules\bpy\ops.py:113

3rd Issue:

When attempting to delete this wall: 
![image](https://user-images.githubusercontent.com/78321676/233047774-bb4ae040-88fb-4d53-b428-b8797ab71238.png)

we receive this error:
Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 377, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 392, in _execute
    tool.Geometry.delete_ifc_object(obj)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\geometry.py", line 100, in delete_ifc_object
    ifcopenshell.api.run("root.remove_product", tool.Ifc.get(), product=element)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\root\remove_product.py", line 76, in execute
    ifcopenshell.api.run("geometry.remove_representation", self.file, **{"representation": representation})
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\remove_representation.py", line 42, in execute
    ifcopenshell.util.element.remove_deep2(
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\element.py", line 784, in remove_deep2
    ifc_file.unbatch()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 449, in unbatch
    return self.wrapped_data.unbatch()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4589, in unbatch
    return _ifcopenshell_wrapper.file_unbatch(self)
RuntimeError: Instance #145,881 not found

The wall deletes on the second attempt

Using Blender 3.5
BlenderBim 23.04.17

Exported IFC from Revit 2022
Using IFC4 Design transfer view

Not certain if these are issues with: 
the method of IFC export
The Ifc file itself
Or BlenderBim

But I thought the Revit sample file would be a good test case to see what is what

[racbasicsampleproject.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11272028/racbasicsampleproject.ifc.txt)

**Comment by Andrej730** [comment]
Investigated a bit - its seems for extending wall profile bbim currently expects wall occurence to have `IfcMaterialLayerSetUsage` and in this example wall has `IfcMaterialLayerSet` inherited from the type.

https://github.com/IfcOpenShell/IfcOpenShell/blob/7cae099fb4167ae89c711248b1a64e1d52ead94a/src/blenderbim/blenderbim/bim/module/model/workspace.py#L372

https://github.com/IfcOpenShell/IfcOpenShell/blob/7cae099fb4167ae89c711248b1a64e1d52ead94a/src/blenderbim/blenderbim/tool/model.py#L472-L478

**Comment by Moult** [comment]
1. This is expected. The Revit file does not include parametric material usages as mentioned by @Andrej730 , so there is no way to know how to extend the wall. This is a problem with Revit. It's not invalid, but it is cannot be used for parametric shapes (i.e. it simply states "there are layers" but doesn't indicate where the layers are.
2. How do I recreate this?
3. I tried deleting the wall and it worked without any problems. Can you try again?

**Comment by sboddy** [comment]
@Plae-Blue-Dot Doing some triage here. This is a super stale bug. Any feedback to Moult? Or can it be closed?

**Comment by sboddy** [comment]
@Plae-Blue-Dot It's been 3 months so I'm going to close this as "stale". Please reopen if you think the issue is still needed.

**Comment by Plae-Blue-Dot** [comment]
Hi @sboddy apologies for the delay, happy to have this closed if I run into the issue again I will post it here
