### ISSUE TITLE
Error with MergeProject patch

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3036]
Trying to merge [this](https://gitlab.com/openingdesign/clothing_boutique/-/blob/64d148db8db373232671fcf96461f2aa22afeca6/Clothing_Boutique.ifc) file with [this](https://gitlab.com/openingdesign/clothing_boutique/-/blob/64d148db8db373232671fcf96461f2aa22afeca6/Revit_Template-IFC4.ifc) file, but getting the following errors. 

![image](https://user-images.githubusercontent.com/507113/233106296-d2e51226-9782-4bc2-98fa-3faa0302132b.png)

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\patch\operator.py", line 90, in execute
    output = ifcpatch.execute(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcpatch\__init__.py", line 79, in execute
    patcher.patch()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcpatch\recipes\MergeProject.py", line 48, in patch
    source = ifcopenshell.open(self.filepath)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 130, in open
    raise exc(msg)
OSError: Unable to open file for reading

```

**Comment by ay-ex** [comment]
Hi @theoryshaw , 
could you try replacing the doubled backslashes in `filepath` with single backslashes?

**Comment by theoryshaw** [comment]
Thanks!.. it used to not be that way!
I changed the wiki: https://wiki.osarch.org/index.php?title=BlenderBIM_Add-on/IFC_Patch_Recipes

**Comment by ay-ex** [comment]
@theoryshaw : I was merely interested, if a single merge would work for you.
since supplying the merge models without list and apostrophes disables potential multi merge.
from the tool's help text though, it seems the tool was designed for single model merge.. (?) 🤔 
thank you for updating the wiki!! 🙂
