### ISSUE TITLE
Build under macOS 10.13.1 fails

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#304]
Unfortunately, the build doesn't work under macOS (10.13.1) since one of the last changes in IfcOpenShell.

Xcode 9.0 (9A235) is installed.

Kurt

```
./build-all.py 
This script fetches and builds IfcOpenShell and its dependencies

Script configuration:


* Target Architecture    = x86_64
 - Whether 32-bit (i686) or 64-bit (x86_64) will be built.
* USE_OCCT               = True
 - Compiling against official Open Cascade
* Dependency Directory   = /Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9
 - The directory where IfcOpenShell dependencies are installed.
* Build Config Type      = RelWithDebInfo
 - The used build configuration type for the dependencies.
   Defaults to RelWithDebInfo if not specified.
* IFCOS_NUM_BUILD_PROCS  = 5
 - How many compiler processes may be run in parallel.

using command log file '/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/logs/20171124.log'
Collecting dependencies:
Found existing cmake-3.4.1, skipping
Found existing pcre-8.39, skipping
Found existing swig, skipping
Found existing occt-7.1.0, skipping
Found existing libxml2-2.9.3, skipping
Found existing OpenCOLLADA, skipping
Found existing python-3.6.2, skipping
Found existing boost-1.59.0, skipping
Found existing icu-56.1, skipping
Building IfcOpenShell:
Configuring executables...
----------------------------------------------------------------------
CMake Error at /Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/cmake-3.4.1/share/cmake-3.4/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/build/ifcopenshell/executables/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_7109c/fast"

  /Applications/Xcode.app/Contents/Developer/usr/bin/make -f
  CMakeFiles/cmTC_7109c.dir/build.make CMakeFiles/cmTC_7109c.dir/build

  Building C object CMakeFiles/cmTC_7109c.dir/testCCompiler.c.o

  
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
  -fPIC -fdata-sections -ffunction-sections -fvisibility=hidden
  -mmacosx-version-min=10.9 -o CMakeFiles/cmTC_7109c.dir/testCCompiler.c.o -c
  /Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/build/ifcopenshell/executables/CMakeFiles/CMakeTmp/testCCompiler.c


  Linking C executable cmTC_7109c

  
  /Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/cmake-3.4.1/bin/cmake
  -E cmake_link_script CMakeFiles/cmTC_7109c.dir/link.txt --verbose=1

  
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
  -fPIC -fdata-sections -ffunction-sections -fvisibility=hidden
  -mmacosx-version-min=10.9 -Wl,-search_paths_first
  -Wl,-headerpad_max_install_names -Wl,--gc-sections
  -mmacosx-version-min=10.9 CMakeFiles/cmTC_7109c.dir/testCCompiler.c.o -o
  cmTC_7109c

  ld: unknown option: --gc-sections

  clang: error: linker command failed with exit code 1 (use -v to see
  invocation)

  make[1]: *** [cmTC_7109c] Error 1

  make: *** [cmTC_7109c/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:22 (project)



----------------------------------------------------------------------
Traceback (most recent call last):
  File "./build-all.py", line 548, in <module>
    "-DCMAKE_INSTALL_PREFIX="    "%s/install/ifcopenshell" % (DEPS_DIR,)], cmake_dir=CMAKE_DIR, cwd=executables_dir)
  File "./build-all.py", line 265, in run_cmake
    __check_call__([cmake_path, P]+cmake_args+["-DCMAKE_BUILD_TYPE=%s" % (BUILD_CFG,)], cwd=cwd)
  File "./build-all.py", line 227, in __check_call__
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/cmake-3.4.1/bin/cmake /Users/kuba/dev/projects-bim/IfcOpenShell/cmake -DBOOST_ROOT=/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/boost-1.59.0 -DOCC_INCLUDE_DIR=/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/occt-7.1.0/include/opencascade -DOCC_LIBRARY_DIR=/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/occt-7.1.0/lib -DOPENCOLLADA_INCLUDE_DIR=/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/OpenCOLLADA/include/opencollada -DOPENCOLLADA_LIBRARY_DIR=/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/OpenCOLLADA/lib/opencollada -DICU_INCLUDE_DIR=/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/icu-56.1/include -DICU_LIBRARY_DIR=/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/icu-56.1/lib -DPCRE_LIBRARY_DIR=/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/pcre-8.39/lib -DBUILD_IFCPYTHON=OFF -DUSE_MMAP=OFF -DCMAKE_INSTALL_PREFIX=/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/ifcopenshell -DCMAKE_BUILD_TYPE=RelWithDebInfo` returned exit code 1
```

**Comment by thorade** [comment]
Does upgrading CMake help maybe?

**Comment by kurb70** [comment]
Unfortunately not. After switching to cmake-3.10.0 I get:

```
./build-all.py 
This script fetches and builds IfcOpenShell and its dependencies

Script configuration:


* Target Architecture    = x86_64
 - Whether 32-bit (i686) or 64-bit (x86_64) will be built.
* USE_OCCT               = True
 - Compiling against official Open Cascade
* Dependency Directory   = /Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9
 - The directory where IfcOpenShell dependencies are installed.
* Build Config Type      = RelWithDebInfo
 - The used build configuration type for the dependencies.
   Defaults to RelWithDebInfo if not specified.
* IFCOS_NUM_BUILD_PROCS  = 5
 - How many compiler processes may be run in parallel.

using command log file '/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/logs/20171124.log'
Collecting dependencies:
Fetching cmake-3.10.0...   
Download '/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/build/cmake-3.10.0.tar.gz' already exists, assuming it's an undamaged download and that it has been extracted if possible, skipping
Configuring cmake-3.10.0...
----------------------------------------------------------------------

----------------------------------------------------------------------
Traceback (most recent call last):
  File "./build-all.py", line 433, in <module>
    build_dependency(name="cmake-%s" % (CMAKE_VERSION,), mode="autoconf", build_tool_args=[], download_url="https://cmake.org/files/v%s" % (CMAKE_VERSION_2,), download_name="cmake-%s.tar.gz" % (CMAKE_VERSION,))
  File "./build-all.py", line 360, in build_dependency
    run_autoconf(name, build_tool_args, cwd=extract_build_dir)
  File "./build-all.py", line 257, in run_autoconf
    __check_call__(["/bin/sh", "../configure"]+configure_args+["--prefix=%s" % (os.path.realpath("%s/install/%s" % (DEPS_DIR, arg1)),)], cwd=cwd)
  File "./build-all.py", line 227, in __check_call__
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `/bin/sh ../configure --prefix=/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/install/cmake-3.10.0` returned exit code 8
```

**Comment by aothms** [comment]
We changed the way support for `--gc-sections` is detected, because we no longer wanted to rely on `man` for that. ea3318ae2e298c9dfeba1b4a796c01af7ddf59f0

> `ld: unknown option: --gc-sections`

Could you let me know what the output of `ld --gc-sections` is on your system? Thanks!

**Comment by kurb70** [comment]
thx. I hope I got you right. ;)

```
kubasMBPr:nix kuba$ which ld
/usr/bin/ld

kubasMBPr:nix kuba$ ld --gc-sections
ld: unknown option: --gc-sections

kubasMBPr:nix kuba$ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-302.3.1
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 9.0.0, (clang-900.0.38) (static support for 21, runtime is 21)
TAPI support using: Apple TAPI version 900.0.14 (tapi-900.0.14)
```

**Comment by aothms** [comment]
Ok interesting, what is being matched is `unrecognised option`, but yours prints `unknown option`. Fair enough, I guess this is a bad idea anyway to look for stderr output considering potential i18n output. Let's search instead for whether the option is repeated. Can you try again with the latest commit? Thanks.

95be422

**Comment by kurb70** [comment]
Great! With your last commit I could compile without errors.
BTW I used CMAKE 3.10.0
Thanks, Thomas

**Comment by aothms** [comment]
Ok, thanks for confirming
