### ISSUE TITLE
OverflowError: in method 'entity_instance_setArgumentAsInt', argument 3 of type 'int'

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#3058]
Hello,

I encountered an issue while trying to set a low int as creation date. In some date system 30.12.1899 is 0 for example in LibreOffice/Excel sheets. See [Epoch (computing)](https://en.wikipedia.org/wiki/Epoch_(computing)). If you convert it to an ifc compatible date you get `-2209165200` which apparently currently produce an overflow. So a date left to default 0 produce an error.

## Error message
```python
Exception has occurred: OverflowError
in method 'entity_instance_setArgumentAsInt', argument 3 of type 'int'
  File "/home/cyril/git/IfcOpenShell/src/ifcopenshell-python/ifcopenshell/ifcopenshell_wrapper.py", line 3695, in setArgumentAsInt
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsInt(self, i, v)
  File "/home/cyril/git/IfcOpenShell/src/ifcopenshell-python/ifcopenshell/entity_instance.py", line 267, in __setitem__
    self.method_list[idx](
  File "/home/cyril/git/IfcOpenShell/src/ifcopenshell-python/ifcopenshell/file.py", line 286, in create_entity
    e[idx] = arg
  File "/home/cyril/git/IfcOpenShell/src/ifcopenshell-python/scripts/issue_lowtimestamp.py", line 52, in <module>
    owner_history = file.createIfcOwnerHistory(
OverflowError: in method 'entity_instance_setArgumentAsInt', argument 3 of type 'int'
```

## Code to reproduce
```python
import uuid
import ifcopenshell
import datetime


file = ifcopenshell.file(schema='IFC4')

# https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcaddress.htm
address = file.createIfcAddress(
    Purpose="OFFICE",
    Description="Anton Philipslaan 199\n5616TW Eindhoven\nThe Netherlands",
)

# https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcorganization.htm
organisation = file.createIfcOrganization(
    Name="AECGeeks",
    Description="""Software development and consultancy for the
    Architecture Engineering and Construction industry""",
    Addresses=[address],
)

# https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcapplication.htm
application = file.createIfcApplication(
    ApplicationDeveloper=organisation,
    Version=ifcopenshell.version,
    ApplicationFullName="IfcOpenShell",
    ApplicationIdentifier="ifcopenshell",
)

# https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcroleenum.htm
role = file.createIfcActorRole("MANUFACTURER")

# https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcperson.htm
person = file.createIfcPerson(
    Identification=str(uuid.uuid4()),
    FamilyName="Unknown",
    GivenName="Unknown",
    Roles=[role],
)

# https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcorganization.htm
organisation = file.createIfcOrganization(
    Identification="companyid", Name="company", Roles=[role]
)

# https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcpersonandorganization.htm
person_and_organisation = file.createIfcPersonAndOrganization(
    person, organisation, Roles=[role]
)

# https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcownerhistory.htm
owner_history = file.createIfcOwnerHistory(
    OwningUser=person_and_organisation,
    OwningApplication=application,
    CreationDate=int(datetime.datetime(1899, 12, 30).timestamp()),
)
```

**Comment by aothms** [comment]
I cannot get this to work (on windows at least)

```
>>> int(datetime.datetime(1899, 12, 30).timestamp())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: timestamp out of range
```

on 3.9/3.10 I get

```
>>> datetime.datetime(1899, 12, 30).timestamp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```

But indeed, this number is apparently too large to fit into a python "regular" int as it requires more than 32bits:

```
>>> -2209165200
-2209165200
>>> - (2 ** 31)
-2147483648
```

And hence,

```
>>> sys.getsizeof(-1)
28
>>> sys.getsizeof(-2209165200)
32
```

So it doesn't get mapped to a C++ int by swig.

This should be a common problem, but I'm not getting good search results on this. Anyone?

It's nowhere near of what I would expect to be the max of a 64bit int though. So on 64bit ifcopenshell there theoretically doesn't need to be a problem.

```
>>> 2 ** 63
9223372036854775808
```

**Comment by CyrilWaechter** [comment]
Hmm, strange. I didn't test on windows but on my GNU/Linux OS `python`, `swig` and `_ifcopenshell_wrapper.so` are all 64 bits.

**Comment by civilx64** [comment]
Same environment as @CyrilWaechter and same results:
```
Python 3.9.14 (main, Sep  7 2022, 23:43:29)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime(1899, 12, 30).timestamp()
-2209143600.0
>>> int(datetime.datetime(1899, 12, 30).timestamp())
-2209143600
```
```
File "/home/civilx64/.virtualenvs/IfcOpenShell/lib/python3.9/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 3777, in setArgumentAsInt
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsInt(self, i, v)
OverflowError: in method 'entity_instance_setArgumentAsInt', argument 3 of type 'int'
>>>
```

**Comment by Moult** [comment]
I get the same results as @CyrilWaechter on Gentoo Linux using bot builds.

**Comment by aothms** [comment]
Ok, this issue is more fundamental then I thought. Apparently even on 64bit platforms an `int` is just 4 bytes. So if we change this naively just in python we get something even worse:

```
>>> import ifcopenshell
>>> ifcopenshell.file().createIfcInteger(-2209165200)
IfcInteger(2085802096)
```

We'll have to defer this to v0.8 and make all integers (incl. schema namespaces) an int64_t (for example).

**Comment by BIMvoice** [comment]
Status check on 0.8.5-1c5b825: still reproduces exactly as reported — `f.create_entity("IfcTimeStamp", -2209165200)` and `owner_history.CreationDate = -2209165200` both raise `OverflowError: entity_instance_setArgumentAsInt, argument 3 of type 'int'`, and anything past 2^31 (post-2038 dates) fails the same way. So the 32-bit integer attribute storage @aothms identified survived the 0.8 parser/storage rewrite. Practical impact remains: IFC timestamps before 1901-12-13 or after 2038-01-19 cannot be authored from Python.
