### ISSUE TITLE
Error when installingBlender BIM in Blender 3.5.0

### ISSUE THREAD

**Issue by andreitam11** [IfcOpenShell/IfcOpenShell#3060]
I cannot install BlenderBIM in Blender 3.5.0. 

Steps to replicate error:

1. Install Blender 3.5.0
2. Download latest version of BlenderBIM, and install.

Version:
Blender 3.5.0
BlenderBIM blenderbim-230304-py310

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\__init__.py", line 42, in register
    blenderbim.bim.register()
AttributeError: module 'blenderbim' has no attribute 'bim'
```

**Comment by Moult** [comment]
Is that the entire error? You may have an uncleaned old installation. Try a manual uninstall: https://blenderbim.org/docs/users/installation.html#uninstalling

Then do a fresh install following https://blenderbim.org/docs/users/installation.html#

If it still doesn't work, jump on osarch.org/chat and let's do a live screenshare.
