### ISSUE TITLE
BlenderBim - when attempting to align centreline it gives this error

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3075]
With a wall selected with the BIM tool and attempting either
SHIFT-X
SHIFT-C
SHIFT-V

They all give this error:

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 380, in invoke
    return self.execute(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 372, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 553, in hotkey_S_V
    bpy.ops.bim.align_wall(align_type="INTERIOR")
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.bim.align_wall.poll() failed, context is incorrect

**Comment by sboddy** [comment]
With multiple walls selected all three shortcuts behave as expected, and align the walls as expected.

With a single wall selected (which doesn't really make sense anyway), Shift-X and Shift-C do nothing as you would expect. Shift-V also has no effect, but throws an error:
```
os: Linux
os_version: #147-Ubuntu SMP Sat Mar 15 15:53:30 UTC 2025
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: x86_64
blender_version: 4.2.9 LTS
bonsai_version: 0.8.3-alpha250418
bonsai_commit_hash: 917d28a
bonsai_commit_date: 2025-04-18T19:25:46+05:00
last_actions: 
# ifcopenshell.api: geometry.regenerate_wall_representation
>>> {}
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
# operator: BIM_OT_hotkey
last_error: Traceback (most recent call last):
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/ifc.py", line 458, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/workspace.py", line 1102, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/workspace.py", line 1331, in hotkey_S_V
    bpy.ops.bim.align_wall(align_type="INTERIOR")
  File "/snap/blender/6126/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.bim.align_wall.poll() Please select at least two mesh objects.

ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.3-alpha250418
originating_system: IfcOpenShell 0.8.3-alpha250418
```

**Comment by sboddy** [comment]
The Shift-V error was fixed by https://github.com/IfcOpenShell/IfcOpenShell/commit/2db6b860b2a8d5055c515083928cb859cb847d6a so I'm closing this issue as all shortcuts give an appropriate popup in the UI now.
