### ISSUE TITLE
Error when creating roof modifier.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3080]
Error when creating roof modifier...

https://user-images.githubusercontent.com/507113/235382817-5ea35203-0cc5-41d9-92ec-2b48a252045f.mp4

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\roof.py", line 467, in _execute
    update_roof_modifier_bmesh(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\roof.py", line 361, in update_roof_modifier_bmesh
    generate_hiped_roof_bmesh(bm, props.generation_method, height, props.angle, mutate_current_bmesh=True)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\roof.py", line 178, in generate_hiped_roof_bmesh
    verts, edges, faces = calculate_hiped_roof()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\roof.py", line 132, in calculate_hiped_roof
    closed_polygons = shapely.polygonize(unioned_boundaries.geoms)
AttributeError: 'LineString' object has no attribute 'geoms'. Did you mean: '_geom'?

```

**Comment by Andrej730** [comment]
The error happened because it's expecting footprint-like object to create roof from.
Not sure if there is more intuitive solution for user experience but currently I've changed it so that it leaves only object's footprint before creating a roof.

https://user-images.githubusercontent.com/9417531/235432235-eb5abaf6-c853-4ca3-8845-f07fa5ef5f69.mp4

**Comment by Moult** [comment]
That seems risky. If the object is weird and doesn't have anything footprintish then it would still fail. The safest solution would be to ignore anything prior, and always start with a 2x2m square (or local XY dim extents) or something. The downside is that if the user already had modeled a footprint, they'd lose it. Though I can't imagine a scenario where they might choose to model a footprint first - why not just create the roof, then create the footprint from that. Or, if they already have a footprint, leave it as a separate object and create a roof anew, then trace the existing footprint (after all roof footprints aren't complex shapes so it'll be a quick task). This is the same approach we take for converting arbitrary shapes to parametric walls - we discard and only keep the local X dimension.

**Comment by Andrej730** [comment]
Makes sense.
Got idea that it can start with square with XY dimensions from current's object bounding box and placed at min_z, should be safe too.
