### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'user_remap'

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3088]
Is there a relatively easy way to fix this file?
https://gitlab.com/openingdesign/mineral_point_residence/-/blob/337e3ab048a24a32b5327d1e4d4b7a0863ea02d6/Mineral_Point_Residence.ifc

It was saving for hours, but when I reimported, got the following error when activating a drawing. 

It's drawing specific.  Some drawings don't give the error.

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1292, in execute
    core.activate_drawing_view(tool.Ifc, tool.Drawing, drawing=drawing)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\drawing.py", line 405, in activate_drawing_view
    drawing_tool.activate_drawing(camera)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\drawing.py", line 1484, in activate_drawing
    blenderbim.core.geometry.switch_representation(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\geometry.py", line 108, in switch_representation
    geometry.change_object_data(obj, data, is_global=is_global)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\geometry.py", line 37, in change_object_data
    obj.data.user_remap(data)
AttributeError: 'NoneType' object has no attribute 'user_remap'

```

**Comment by theoryshaw** [comment]
fixed it... 
this was the offending object...
not sure where that came from, or why it threw the error. 

![image](https://user-images.githubusercontent.com/507113/235562762-3409b36d-8f08-4747-bf6b-86e7df5cd994.png)
