### ISSUE TITLE
BlenderBim - Work schedule task error when attempting to edit time

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3091]
When attempting to edit the time of one task I get this error:

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\isodate\isodatetime.py", line 51, in parse_datetime
    datestring, timestring = datetimestring.split('T')
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 260, in _execute
    core.enable_editing_task_time(tool.Ifc, tool.Sequence, task=tool.Ifc.get().by_id(self.task))
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\sequence.py", line 184, in enable_editing_task_time
    sequence.load_task_time_attributes(task_time)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\sequence.py", line 364, in load_task_time_attributes
    blenderbim.bim.helper.import_attributes2(task_time, props.task_time_attributes, callback)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\helper.py", line 91, in import_attributes2
    import_attribute(attribute, props, element.get_info(), callback=callback)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\helper.py", line 105, in import_attribute
    is_handled_by_callback = callback(attribute.name(), new, data) if callback else None
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\sequence.py", line 354, in callback
    for key, value in helper.parse_duration_as_blender_props(data[name]).items():
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\sequence\helper.py", line 51, in parse_duration_as_blender_props
    dt = ifcdateutils.ifc2datetime(dt)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\date.py", line 45, in ifc2datetime
    duration = isodate.parse_duration(element)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\isodate\isoduration.py", line 91, in parse_duration
    durdt = parse_datetime(datestring[1:])
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\isodate\isodatetime.py", line 53, in parse_datetime
    raise ISO8601Error("ISO 8601 time designator 'T' missing. Unable to"
isodate.isoerror.ISO8601Error: ISO 8601 time designator 'T' missing. Unable to parse datetime string ''

**Comment by Moult** [comment]
What value did you enter?

**Comment by Plae-Blue-Dot** [comment]
> What value did you enter?

In the start and end dates it was initially:
2023-05-02T09:00:00
2023-05-02T17:00:00

With is set to WORKTIME and the D set to 1

These were the only values I was changing, And I must've done something to them
When pressing Generate Gantt it still gave the correct chart with the right dates, the only difference is that the bar was red instead of blue.

Unfortunately I wasn't thinking and deleted the task, I can't add the example with the error here, If I encounter it again I will add the Ifc.

**Comment by Moult** [comment]
Red means that the task is on the critical path.

**Comment by Moult** [comment]
@myoualid is this fixed? I saw a commit. Were you able to recreate this?

**Comment by myoualid** [comment]
I can't recreate it except for this bug fix [cd27a02](https://github.com/IfcOpenShell/IfcOpenShell/commit/cd27a026fd435ff736eaa63e106bd07f7c81711b).

**Comment by sboddy** [comment]
@Plae-Blue-Dot Have you encountered this again in the 2+ years since? If not, then maybe this issue can be closed?

**Comment by sboddy** [comment]
@Plae-Blue-Dot Another "stale" issue. As elsewhere, please reopen if this is still needed.

**Comment by Moult** [comment]
@sboddy I think it's fine to close issues where we've asked for more details but no response has been given, but for issues like this I think devs can still re-investigate and check (e.g. here check to make sure error catching is used for invalid date times and durations).

**Comment by Plae-Blue-Dot** [comment]
HI @sboddy I haven't run into this issue again, I am happy to close it and will reopen if I encounter it

**Comment by BIMvoice** [comment]
Re-investigated per @Moult's note about error-catching for invalid date-times and durations.

On current v0.8.0 the original `"P"`-duration case from the traceback is already handled, but a malformed IfcDuration without a leading `P` (e.g. `1D`, `WORKTIME`, or an empty string) still crashed the task time editor: `parse_duration_as_blender_props` hands the raw string to `ifc2datetime`, which guesses the type from the string shape and misroutes such values into date/time parsing, raising an uncaught `ValueError`.

Guarded it in #8334 so a bad duration is logged and treated as empty instead of taking down the editor. `ifc2datetime` itself is left untouched so real bugs elsewhere aren't masked, and no wrong date is fabricated. Tested against `""`, `1D`, `WORKTIME`, `9:00`, `2023-13-45`, `abc`, `T8H`, `5` (all now handled) with valid durations unchanged.
