### ISSUE TITLE
Export IFC with bpy.ops.export_ifc.bim() fails with 'NoneType' object has no attribute 'end_transaction'

### ISSUE THREAD

**Issue by tati-** [IfcOpenShell/IfcOpenShell#3109]
Hello,

I have a blender model consisting of a number of simple objects (meshes), and I want to export it to IFC format after assigning an IFC class to each object, all through the python API. I am on ubuntu 20.04. 

I load my blender file, and then I create an IFC project with
`bpy.ops.bim.create_project()`

I go on and assign ifc classes to all my objects, and then I export with the command
`bpy.ops.export_ifc.bim(filepath=savepath)`

I get the following error:
`
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/tat/.pyenv/versions/dimensioning/lib/python3.10/site-packages/3.3/scripts/addons/blenderbim/bim/module/project/operator.py", line 847, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/tat/.pyenv/versions/dimensioning/lib/python3.10/site-packages/3.3/scripts/addons/blenderbim/bim/ifc.py", line 413, in execute_ifc_operator
    IfcStore.get_file().end_transaction()
AttributeError: 'NoneType' object has no attribute 'end_transaction'
Location: /home/tat/.pyenv/versions/dimensioning/lib/python3.10/site-packages/3.3/scripts/modules/bpy/ops.py:113
`

I tried this both with the latest stable version, and the latest version, and I get the same error. 

Surprisingly, the error occurs after the message:
`Export finished in 0.15 seconds`
An IFC is in fact saved, and when I re-import it with blender it seems ok. However, with some of the online IFC viewers some objects seem to have lost their shape and are shown as simple cubes. If I do the process through the blender GUI there is no such issue. 

I am new to blender and even more new to blenderBIM, and I need the IFC to pass it on to some other people working on the same project, so I am afraid the produced file might be corrupted. 

Thanks in advance, any help or insight is appreciated!

**Comment by tati-** [comment]
Hello again, 

actually it was my bad, I was not using the absolute path in the `filepath` parameter. 
The error is now gone.
