### ISSUE TITLE
BlenderBim - extend wall to roof no longer works?

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3132]
In Blenderbim 230508:

When attempting to extend a wall to a roof
1. select wall
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/e2bff470-690b-4eac-aac8-f5a8a2de7ecf)

2. select roof
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/52fde915-9a02-4c8e-ad3f-3ca6a53b526a)

3. shift - e

we get this error:

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 387, in invoke
    return self.execute(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 379, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 458, in hotkey_S_E
    bpy.ops.bim.enable_editing_extrusion_profile()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\slab.py", line 610, in _execute
    if extrusion.Position:
AttributeError: 'NoneType' object has no attribute 'Position'
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\3.5\scripts\modules\bpy\ops.py:113

**Comment by Andrej730** [comment]
Close as the same issue as #3357
