### ISSUE TITLE
IfcRailing converted to curve on file load : Can't edit the railing profile

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3144]
After creating an IfcRailing with the railing modifier and messing around with it, after I saved the file and tried to re-load it, it is loaded as a Curve object so I can't modify the curve anymore.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/96bc6126-4a22-4dd5-b304-1513ba5671a5)
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 387, in invoke
    return self.execute(context)
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 379, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 426, in hotkey_S_E
    bpy.ops.bim.enable_editing_railing_path()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\railing.py", line 458, in _execute
    update_railing_modifier_bmesh(context)
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\railing.py", line 148, in update_railing_modifier_bmesh
    tool.Blender.apply_bmesh(obj.data, bm)
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\blender.py", line 215, in apply_bmesh
    bm.to_mesh(mesh)
TypeError: expected 'Mesh' type found 'Curve' instead
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\3.5\scripts\modules\bpy\ops.py:113
```

IFC file (as txt)
[railing_to_curve_bug.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11466275/railing_to_curve_bug.txt)

**Comment by Gorgious56** [comment]
I think this was related to a bug caused by my PR #3142, so it might not ever happen to the average user. 

I'm still curious about why it was imported as a curve object in Blender ?

**Comment by Gorgious56** [comment]
Nope, it's happening consistently on that file now. Can't really seem to pinpoint what's causing it

**Comment by Andrej730** [comment]
Narrowed it down a bit - it's probably related to IFCSWEPTDISKSOLID used in the wall mounted handrail representation.
Attached two files below:
- first has one item in representation and it's IfcSweptDiskSolid and it's imported as a curve;
- second one has 2 items in repr and it's imported as a mesh(IfcSweptDiskSolid and IfcExtrudedAreaSolid, tried with 2 IfcSweptDiskSolid - same result)

[railing_repr_disk_only.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11516591/railing_repr_disk_only.ifc.txt)
[railing_repr_disk_and_extrusion.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11516590/railing_repr_disk_and_extrusion.ifc.txt)

The only difference between two files:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/9583ca2f-c74c-4173-875c-9e33a9eaf006)
