### ISSUE TITLE
Blenderbim IFC Roof modifier : Error on modifying Gable Roof Angle

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3171]
I got an error when trying to modify the gable roof angle on a segment of an ifc roof.

It's caused by these lines of code (`identical_edge` not defined)

https://github.com/IfcOpenShell/IfcOpenShell/blob/894a688bd88372b047ac5f03fac532792a512106/src/blenderbim/blenderbim/bim/module/model/roof.py#L238-L243

```
Traceback (most recent call last):
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\decorator.py", line 103, in __call__
    bm = get_custom_bmesh()
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\roof.py", line 591, in get_custom_bmesh
    second_bm = generate_hiped_roof_bmesh(
  File "C:\Users\NH\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\roof.py", line 243, in generate_hiped_roof_bmesh
    verts_to_move = find_other_polygon_verts(identical_edge)
UnboundLocalError: local variable 'identical_edge' referenced before assignment
```

**Comment by Gorgious56** [comment]
After short troubleshooting it seems it's caused by the roof control points not being located on the same XY plane

**Comment by Andrej730** [comment]
Can you please send an example of the roof shape that causes this error? I'll try to add some more descriptive error message.
