### ISSUE TITLE
IFC CSV - cannot import CSV to IFC

### ISSUE THREAD

**Issue by mdjska** [IfcOpenShell/IfcOpenShell#3192]
The "Import CSV to IFC" function doesn't work.
Example method:
- Use the "Export IFC to CSV" function to export a simple CSV with eg. just the names of walls
- Make a change, eg. the name of a wall
- Save file and try to use the 'Import CSV to IFC' function
- Error I get:
```
Python: Traceback (most recent call last):
  File "/Users/.../Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/csv/operator.py", line 190, in execute
    ifc_csv.Import(ifc_file)
  File "/Users/.../Library/Application Support/Blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifccsv.py", line 285, in Import
    element = IfcAttributeSetter.set_element_key(ifc_file, element, headers[i], value)
  File "/Users/.../Library/Application Support/Blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifccsv.py", line 49, in set_element_key
    return ifcopenshell.util.schema.reassign_class(ifc_file, element, value)
  File "/Users/.../Library/Application Support/Blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/schema.py", line 76, in reassign_class
    for attribute in declaration.all_attributes():
UnboundLocalError: local variable 'declaration' referenced before assignment
```

**Comment by Andrej730** [comment]
Just tested - changing wall names seems to work.

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/5502ea1f-5cbb-4e98-899c-e6c668c17485

From the traceback it's seems you're trying to change not just the name but the class too. There should be another error message prior to that traceback - like "Class of {element} could not be changed to {new_class} as the class does not exist".

Can you share .ifc and .csv you're using? Then I'll be able to investigate further.

**Comment by mdjska** [comment]
Ok, so it does work if "Name" is the only attribute. The issue is when "type" attribute is added as well. I didn't change the type or class, it's the same as exported. There also isn't any other error message before the one I posted. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/16716147/fd90ad1d-07c8-48ce-a1ad-36827b3fbbda
