### ISSUE TITLE
Error on `bim.activate_drawing`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3224]
We're trying to maintain the blender/ifc connection in the following file, since we'd like to use Blender's rendering capacities. 
[Restaurant_Livingston.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11620829/Restaurant_Livingston.zip)

If you open 'EXISTING PLAN - 1ST FLOOR` drawing we get the following error. 
Is there a relatively easy way to fix this?

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1315, in execute
    core.activate_drawing_view(tool.Ifc, tool.Drawing, drawing=drawing)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\drawing.py", line 413, in activate_drawing_view
    drawing_tool.activate_drawing(camera)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\drawing.py", line 1511, in activate_drawing
    current_representation = tool.Geometry.get_active_representation(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\geometry.py", line 127, in get_active_representation
    return tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 326, in by_id
    return self[id]
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4515, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #823,006 not found

```

**Comment by Andrej730** [comment]
The issue with object "IfcWall/G-No_Name_001.001". In .blend it's mesh is referring to ifc representation that doesn't exist.
I usually get this kind of error when I forget to save .ifc and only save .blend (happens sometimes because saving .ifc is not connected to saving .blend :\ )
There is probably better way to do it but solution from the top of my head - remove this object and add it again since it's just a wall.

Not sure if we have some tool in BBIM to spot those broken kind of problems in current .blend file so it wouldn't interrupt user's workflow to debug it or reload .ifc.

**Comment by theoryshaw** [comment]
Cool. Curious how did you realize this was connected to `IfcWall/G-No_Name_001.001`?... just for future troubleshooting?

**Comment by theoryshaw** [comment]
related: https://matrix.to/#/!ahYNbqalYLpFCLDRoz:matrix.org/$wu3N1Wg5uS8QxmbKRD9yVuuAl02vnkVnMGQpyiXMBEc?via=matrix.org
