### ISSUE TITLE
After deleting object, get erro when `bim.create_drawing`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3244]
When i try to delete this chandelier, i get the following error when i `bim.create_drawing`

files: [Restaurant_Livingston.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11641650/Restaurant_Livingston.zip)

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/ebd3caa8-f042-408c-828b-489e0f25088a

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 167, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 212, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 333, in generate_linework
    invalidated_elements = exporter.sync_all_objects()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\export_ifc.py", line 97, in sync_all_objects
    result = self.sync_object_placement(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\export_ifc.py", line 138, in sync_object_placement
    element = self.file.by_id(obj.BIMObjectProperties.ifc_definition_id)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 326, in by_id
    return self[id]
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4515, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #502,485 not found

```

**Comment by Andrej730** [comment]
I'm not sure what's the root cause of this but this is why it occurs:
1) There is also some opening element `IfcOpeningElement/Cube` which has ifc definition #502485 IfcIndexedPolygonalFace and it has .ToFaceSet #486567 IfcPolygonalFaceSet.
2) Both #502485 and #486567 get deleted when you remove the chandelier since #486567 IfcPolygonalFaceSet is part of chandlier's body tessellation #486574 IfcShapeRepresentation.

Tried to remove the `IfcOpeningElement/Cube` but it results in another error.
`RuntimeError: Token $ at offset 12 356 907 invalid instance name`

**Comment by Moult** [comment]
Either it's a sneaky sync issue we haven't yet caught, or it's a result of you trying to keep the Blender file and switch between IFC versions. Unfortunately there isn't anything we can do unless we identify the root cause so as much as I don't like it this'll need to be closed.
