### ISSUE TITLE
Error thrown when saving a file with a linked IFC file.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3252]
Error thrown when saving a file with a linked IFC file.

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/349dd5dd-cd40-486b-9775-06c51e07c612

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\project\operator.py", line 831, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\project\operator.py", line 847, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\project\operator.py", line 878, in _execute
    ifc_exporter.export()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\export_ifc.py", line 48, in export
    self.sync_all_objects()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\export_ifc.py", line 97, in sync_all_objects
    tool.Collector.sync(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\collector.py", line 70, in sync
    blenderbim.core.aggregate.assign_object(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\aggregate.py", line 35, in assign_object
    collector.assign(related_obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\collector.py", line 98, in assign
    collection.children.unlink(object_collection)
RuntimeError: Error: Could not (un)link the collection 'IfcSite/My Site' because the collection 'IfcProject/My Project' is linked

```

**Comment by theoryshaw** [comment]
Different error, same concept

files(s): https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9dab28fb-c626-4996-af09-7546ed814a17


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d5835f2f-05ed-4c77-a84d-fae22f2ce623




```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\project\operator.py", line 831, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\project\operator.py", line 847, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\project\operator.py", line 878, in _execute
    ifc_exporter.export()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\export_ifc.py", line 48, in export
    self.sync_all_objects()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\export_ifc.py", line 101, in sync_all_objects
    result = self.sync_object_material(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\export_ifc.py", line 132, in sync_object_material
    bpy.ops.bim.update_representation(obj=obj.name)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 41, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 171, in _execute
    self.update_obj_mesh_representation(context, obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 200, in update_obj_mesh_representation
    context_of_items = old_representation.ContextOfItems
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 180, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcAxis2Placement3D' has no attribute 'ContextOfItems'
Location: C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py:113

```
