### ISSUE TITLE
Assign IfcLightFixture to a blender light object. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3303]
I thought, at one point, it was possible to assign IfcLightFixture to a blender light object. 

Currently has an error upon assignment...

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\root\operator.py", line 38, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\root\operator.py", line 140, in _execute
    core.assign_class(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\root.py", line 70, in assign_class
    root.run_geometry_add_representation(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\root.py", line 147, in run_geometry_add_representation
    return blenderbim.core.geometry.add_representation(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\geometry.py", line 45, in add_representation
    representation = ifc.run(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 30, in run
    return ifcopenshell.api.run(command, IfcStore.get_file(), **kwargs)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 69, in execute
    return self.create_model_representation()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 131, in create_model_representation
    return self.create_variable_representation()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 235, in create_variable_representation
    elif not len(self.settings["geometry"].edges):
AttributeError: 'PointLight' object has no attribute 'edges'

```

**Comment by Gorgious56** [comment]
I think it's tricky because in Blender light objects don't have a mesh representation, which pretty much all elements with a physical representation rely on. It would be nice to be able to aggregate a light mesh object with a native blender light, though ?

**Comment by Moult** [comment]
You need to first create a "Lighting" (most likely MODEL_VIEW) context.

Then you can create a light object and assign it to that lighting context. Note that you shouldn't use IfcLightingFixture though - a lighting fixture is the actual luminaire (i.e. the bulb holder, shade, etc). You should use IfcLamp for the actual light source itself.

A quick test shows that even though you can create it, we don't load them so... let's leave this open.

**Comment by BIMvoice** [comment]
This reproduces as fixed on current v0.8.0. In headless Blender 5.1.2 I created a Blender point light in a fresh IFC project and ran Assign IFC Class with IfcLightFixture: the operator returns FINISHED and the light becomes #63=IfcLightFixture(...) with a placement (IfcLightFixture count 0 to 1), and the old "'PointLight' object has no attribute 'edges'" error no longer occurs. The original crash came from the representation code reading mesh edges on a non-mesh object. In v0.8 Assign IFC Class only builds a mesh representation when obj.type == "MESH" (see src/bonsai/bonsai/bim/module/root/operator.py), so a light is now assigned a class and placement without touching mesh geometry. Safe to close.

This was verified with the assistance of an AI tool.
