### ISSUE TITLE
Schedule XER and other Files Not imported Error Message showing

### ISSUE THREAD

**Issue by ashwinbim** [IfcOpenShell/IfcOpenShell#3304]
Python: Traceback (most recent call last):
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\project\ui.py", line 36, in draw
    class IFCFileSelector:
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\project\data.py", line 37, in load
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\project\data.py", line 48, in template_file
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\user1\\AppData\\Roaming\\Blender Foundation\\Blender\\3.5\\scripts\\addons\\blenderbim\\bim\\data\\libraries'

**Comment by Moult** [comment]
That error looks unrelated to XER. Does `C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\data\libraries` exist on your system?

**Comment by ashwinbim** [comment]
@Moult 

IFC4 Demo Library.ifc
IFC4 EU Steel.ifc
IFC4 AU Library.ifc
IFC4 AU Steel.ifc
These files are currently showing.

**Comment by ashwinbim** [comment]
Please help me, I don't know what exact problem this but during Schedule importing this error are showing. 

Python: Traceback (most recent call last):
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 598, in execute
    p6xer2ifc.execute()
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifc4d\p6xer2ifc.py", line 91, in execute
    ifcCreator.create_ifc()
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 34, in create_ifc
    self.work_plan = ifcopenshell.api.run("sequence.add_work_plan", self.file)
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\sequence\add_work_plan.py", line 73, in execute
    work_plan.CreationDate = ifcopenshell.util.date.datetime2ifc(
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 239, in __setattr__
    self[index] = value
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 267, in __setitem__
    self.method_list[idx](
  File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4923, in setArgumentAsEntityInstance
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsEntityInstance(self, i, v)
TypeError: in method 'entity_instance_setArgumentAsEntityInstance', argument 3 of type 'IfcUtil::IfcBaseClass *'
