### ISSUE TITLE
Some mypy experiments

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#3306]
Let's say we want to create some sort of optional type annotation layer to ifcopenshell. I couldn't get further than this:

```
from typing import Sequence, Union, Optional, Type, TypeVar

class Instance:
    name : str

class IFC2X3_IfcOwnerHistory(Instance): 
    CreationDate : int

class IFC4_IfcOwnerHistory(Instance):
    CreationDate : int

class IFC2X3_IfcRoot(Instance):
    GlobalId : str
    OwnerHistory : IFC2X3_IfcOwnerHistory

class IFC4_IfcRoot(Instance):
    GlobalId : str
    OwnerHistory : Optional[IFC4_IfcOwnerHistory]

class IFC2X3_IfcWallStandardCase(IFC2X3_IfcRoot):
    name = 'IfcWallStandardCase'

class IFC4_IfcWallStandardCase(IFC4_IfcRoot):
    name = 'IfcWallStandardCase'

class IFC2X3_IfcWindow(IFC2X3_IfcRoot):
    name = 'IfcWindow'

class IFC4_IfcWindow(IFC4_IfcRoot):
    name = 'IfcWindow'

IfcWallStandardCase = Union[IFC2X3_IfcWallStandardCase, IFC4_IfcWallStandardCase]
IfcWindow = Union[IFC2X3_IfcWallStandardCase, IFC4_IfcWallStandardCase]
OwnerHistory = Union[IFC2X3_IfcOwnerHistory, IFC4_IfcOwnerHistory]

def x(v : IfcWallStandardCase):
    print(v.GlobalId)

def y(v : IfcWallStandardCase):
    print(v.OwnerHistory.CreationDate)

def z(v : IfcWallStandardCase):
    if v.OwnerHistory:
        print(v.OwnerHistory.CreationDate)

import ifcopenshell

T = TypeVar('T', bound=Instance)

class typed_file(ifcopenshell.file):
    def by_type(self, t : Type[T]) -> Sequence[T]:
        return ifcopenshell.file.by_type(self, t.name)

f : typed_file = ifcopenshell.file()
f.createIfcWallStandardCase('A')
f.__class__ = typed_file
x(f.by_type(IfcWallStandardCase)[0])
y(f.by_type(IfcWallStandardCase)[0])
z(f.by_type(IfcWallStandardCase)[0])
z(f.by_type(IfcWindow)[0])
```

```shell
$ mypy test.py
test.py:40: error: Item "None" of "Union[IFC2X3_IfcOwnerHistory, IFC4_IfcOwnerHistory, None]" has no attribute "CreationDate"  [union-attr]
test.py:46: error: Skipping analyzing "ifcopenshell": module is installed, but missing library stubs or py.typed marker  [import]
test.py:46: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
test.py:57: error: Argument 1 to "by_type" of "typed_file" has incompatible type "<typing special form>"; expected "Type[<nothing>]"  [arg-type]
test.py:58: error: Argument 1 to "by_type" of "typed_file" has incompatible type "<typing special form>"; expected "Type[<nothing>]"  [arg-type]
test.py:59: error: Argument 1 to "by_type" of "typed_file" has incompatible type "<typing special form>"; expected "Type[<nothing>]"  [arg-type]
test.py:60: error: Argument 1 to "by_type" of "typed_file" has incompatible type "<typing special form>"; expected "Type[<nothing>]"  [arg-type]
```

```shell
$ python test.py
Traceback (most recent call last):
  File "C:\Users\tkrij\Documents\IfcOpenShell\mypy\test.py", line 57, in <module>
    x(f.by_type(IfcWallStandardCase)[0])
  File "C:\Users\tkrij\Documents\IfcOpenShell\mypy\test.py", line 52, in by_type
    return ifcopenshell.file.by_type(self, t.name)
  File "C:\Users\tkrij\miniconda3\envs\ifopsh07\lib\typing.py", line 710, in __getattr__
    return getattr(self.__origin__, attr)
AttributeError: '_SpecialForm' object has no attribute 'name'
```

Maybe this is completely the wrong direction and maybe I shouldn't be passing actual typing annotations to the by_type() function. But then how else can we construct a typed sequence of something and still have the native C++ code have a proper str type to evaluate.

On the other hand it's quite promising that `y()` yield a type error but `z()` not. That's exactly the kind of structural typing on schema agnostic code that's potentially very powerful.

Who can help us out?!

**Comment by aothms** [comment]
Maybe a bit better in that at least execution in the interpreter works. But still it doesn't make a lot of sense and is bound to be horribly verbose.

```py
from typing import Sequence, Union, Optional, Type, TypeVar

class Instance:
    name : str

class Schema:
    name : str

    IfcWallStandardCase : Type[IfcWallStandardCase]
    IfcWindow : Type[IfcWindow]

class IFC2X3_IfcOwnerHistory(Instance): 
    CreationDate : int

class IFC4_IfcOwnerHistory(Instance):
    CreationDate : int

class IFC2X3_IfcRoot(Instance):
    GlobalId : str
    OwnerHistory : IFC2X3_IfcOwnerHistory

class IFC4_IfcRoot(Instance):
    GlobalId : str
    OwnerHistory : Optional[IFC4_IfcOwnerHistory]

class IFC2X3_IfcWallStandardCase(IFC2X3_IfcRoot):
    name = 'IfcWallStandardCase'

class IFC4_IfcWallStandardCase(IFC4_IfcRoot):
    name = 'IfcWallStandardCase'

class IFC2X3_IfcWindow(IFC2X3_IfcRoot):
    name = 'IfcWindow'

class IFC4_IfcWindow(IFC4_IfcRoot):
    name = 'IfcWindow'

class Ifc2x3(Schema):
    IfcWallStandardCase = IFC2X3_IfcWallStandardCase

class Ifc4(Schema):
    IfcWallStandardCase = IFC4_IfcWallStandardCase

IfcWallStandardCase = Union[IFC2X3_IfcWallStandardCase, IFC4_IfcWallStandardCase]
IfcWindow = Union[IFC2X3_IfcWallStandardCase, IFC4_IfcWallStandardCase]
OwnerHistory = Union[IFC2X3_IfcOwnerHistory, IFC4_IfcOwnerHistory]

def x(v : IfcWallStandardCase):
    print(v.GlobalId)

def y(v : IfcWallStandardCase):
    print(v.OwnerHistory.CreationDate)

def z(v : IfcWallStandardCase):
    if v.OwnerHistory:
        print(v.OwnerHistory.CreationDate)

import ifcopenshell

T = TypeVar('T', bound=Instance)

class typed_file(ifcopenshell.file):
    def by_type(self, t : Type[T]) -> Sequence[T]:
        return ifcopenshell.file.by_type(self, t.name)
    def get_schema(self) -> Schema:
        if self.schema.lower() == 'ifc2x3':
            return Ifc2x3()
        else:
            return Ifc4()
            
f : typed_file = ifcopenshell.file()
f.createIfcWallStandardCase('A')
f.__class__ = typed_file
x(f.by_type(f.get_schema().IfcWallStandardCase)[0])
y(f.by_type(f.get_schema().IfcWallStandardCase)[0])
z(f.by_type(f.get_schema().IfcWallStandardCase)[0])
z(f.by_type(f.get_schema().IfcWindow)[0])
```
