### ISSUE TITLE
Blender BIM - Item not found after undo (Walls)

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#3313]
Adjust wall height --> undo last height command, produces the following error:

```
Python: Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/tool/ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/model/wall.py", line 235, in _execute
    DumbWallRecalculator().recalculate(layer2_objs)
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/model/wall.py", line 418, in recalculate
    joiner.recreate_wall(element, wall)
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/model/wall.py", line 1079, in recreate_wall
    extrusion_data = self.get_extrusion_data(tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id))
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #385,383 not found
```

**Comment by ChubbyQuark** [comment]
Sure, what software do you use to make light-weight animated gifs, the screen recorder I use produces huge files.

**Comment by theoryshaw** [comment]
[ShareX](https://getsharex.com/), it's for windows though.

**Comment by ChubbyQuark** [comment]
Thanks, just found Giphy, seems ok. See attached for process and resulting error:
![Blender BIM - Undo Error - m1 Mac](https://github.com/IfcOpenShell/IfcOpenShell/assets/26485679/b0b856e0-038a-4aff-975e-16e29ba934cf)

**Comment by Andrej730** [comment]
Couldn't reproduce it.


https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/9d3996d9-1eae-4538-a03a-53f1df47e60e



@ChubbyQuark is there something specific about that wall? can you please try it with the default wall from demo library?

**Comment by ChubbyQuark** [comment]
Just tried with a standard wall, works ok. This may have been a
custom wall, nothing too unusual, just a variation of thickness.

**Comment by Gorgious56** [comment]
I have had that happen many times. It just happened to me recently but I tried to reproduce it and couldnt. It happens specifically when extending a wall and undoing.

1. add wall type instance
2. Extend with SHIFt + E
3. Undo with CTRL + Z
4. Try to do anything
5. Error

It doesn't seem to corrupt the file though so I would not expect it to show in the ifc file.

**Comment by ChubbyQuark** [comment]
Yes, seems to be connected to wall join command and/or change in dimension
value.

Also not managed to get it to consistently work or not. Will keep a close
eye on it though.

**Comment by Moult** [comment]
Let's keep this open for a bit to see if anybody can recreate an undo-wall related bug :) There have been quite a few recent fixes that might affect this, such as https://github.com/IfcOpenShell/IfcOpenShell/commit/0078d691d3b4be64e9c79265f18f78481c3250ea which might've stuffed up the undo system but we'll see.

**Comment by brunopostle** [comment]
Possibly related and completely reproducible:

1. Mitre two walls
2. Undo
3. Mitre them again
4. Error is the same as above
5. Saving and loading the Ifc seems to fix things

Same thing happens with 'butt' and, I think, 'extend'.

**Comment by brunopostle** [comment]
Trying on another machine and can't reproduce either, will investigate..

**Comment by Gorgious56** [comment]
FWIW https://github.com/IfcOpenShell/IfcOpenShell/issues/3659#issuecomment-1707846164

**Comment by ChubbyQuark** [comment]
This may be connected the original bug, so will post it here for now:

This wall, which was previously working without issue is now throwing the error below if any modification is made with the BB panel. Refresh, extend, butt, mitre etc.


![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/26485679/b290e6de-9674-4f66-9019-b962a9a6a73d)


Python: Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/workspace.py", line 550, in invoke
    return self.execute(context)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/ifc.py", line 201, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/workspace.py", line 542, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/workspace.py", line 683, in hotkey_S_G
    bpy.ops.bim.recalculate_wall()
  File "/Applications/Blender 3.6LTS.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/ifc.py", line 201, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/wall.py", line 207, in _execute
    DumbWallRecalculator().recalculate(context.selected_objects)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/wall.py", line 431, in recalculate
    joiner.recreate_wall(element, wall)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/wall.py", line 1111, in recreate_wall
    extrusion_data = self.get_extrusion_data(tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id))
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 388, in by_id
    return self[id]
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 376, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3532, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #413,643 not found
Location: /Applications/Blender 3.6LTS.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py:113

**Comment by sboddy** [comment]
Not reproducible. I tried all attempts detailed above to reproduce, and can't get the error in latest dev build. A _lot_ of code churn since issue was opened, so closing as resolved.
