### ISSUE TITLE
Error on retrieving shader graph nodes in non english clients

### ISSUE THREAD

**Issue by oliveiros** [IfcOpenShell/IfcOpenShell#3316]
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/project/operator.py", line 535, in execute
    bpy.ops.bim.load_project_elements()
  File "/app/blender/3.5/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Erro: Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/project/operator.py", line 594, in execute
    ifc_importer.execute()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 241, in execute
    self.create_styles()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 1471, in create_styles
    self.create_style(style)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 1491, in create_style
    self.create_surface_style_rendering(blender_material, surface_style)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 1543, in create_surface_style_rendering
    bsdf = blender_material.node_tree.nodes["Principled BSDF"]
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'
Location: /app/blender/3.5/scripts/modules/bpy/ops.py:113

**Comment by oliveiros** [comment]
Changing the language from Brazilian Portuguese to English solved the problem

**Comment by Andrej730** [comment]
Thanks for reaching out! Fixed.
