### ISSUE TITLE
RuntimeError: Instance #1,590 not found on loading BooleansData

### ISSUE THREAD

**Issue by oliveiros** [IfcOpenShell/IfcOpenShell#3317]
```
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
bpy.ops.transform.translate(value=(0, 0, 0), orient_axis_ortho='X', orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', mirror=False, snap=True, snap_elements={'INCREMENT'}, use_snap_project=False, snap_target='CLOSEST', use_snap_self=True, use_snap_edit=True, use_snap_nonedit=True, use_snap_selectable=False, cursor_transform=True, release_confirm=True)
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
bpy.ops.bim.assign_class(obj="Door", ifc_class="IfcDoor")
bpy.ops.bim.add_filled_opening(voided_obj="IfcWall/Wall.002", filling_obj="IfcDoor/Door.006")
bpy.ops.bim.add_constr_type_instance()
bpy.ops.bim.hotkey(hotkey="S_A", x=0.5, y=0.5, z=0.5)
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/model/workspace.py", line 387, in invoke
    return self.execute(context)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/tool/ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/model/workspace.py", line 379, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/model/workspace.py", line 399, in hotkey_S_A
    bpy.ops.bim.add_constr_type_instance()
  File "/app/blender/3.5/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/model/product.py", line 76, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/model/product.py", line 163, in _execute
    bpy.ops.bim.add_filled_opening(voided_obj=building_obj.name, filling_obj=obj.name)
  File "/app/blender/3.5/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/tool/ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/model/opening.py", line 49, in _execute
    FilledOpeningGenerator().generate(bpy.data.objects.get(self.filling_obj), bpy.data.objects.get(self.voided_obj))
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/model/opening.py", line 124, in generate
    representation = self.generate_opening_from_filling(filling, filling_obj, voided_obj)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/model/opening.py", line 276, in generate_opening_from_filling
    shape_builder.rectangle(size=opening_size),
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/shape_builder.py", line 102, in rectangle
    return self.polyline(self.get_rectangle_coords(size, position), closed=True)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/shape_builder.py", line 89, in get_rectangle_coords
    position + size * id_matrix[non_empty_coords[1]],
IndexError: list index out of range
Location: /app/blender/3.5/scripts/modules/bpy/ops.py:113
Location: /app/blender/3.5/scripts/modules/bpy/ops.py:113
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
bpy.ops.bim.load_type_thumbnails(ifc_class="IfcDoorType")
bpy.ops.bim.add_constr_type_instance(ifc_class="IfcDoorType", relating_type_id=281, from_invoke=True)
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/model/product.py", line 73, in invoke
    return self.execute(context)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/model/product.py", line 76, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/model/product.py", line 88, in _execute
    props.relating_type_id = str(self.relating_type_id)
TypeError: bpy_struct: item.attr = val: enum "281" not found in ('281')
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
Python: Traceback (most recent call last):
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/ui.py", line 102, in draw
    BooleansData.load()
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 77, in load
    cls.data = {"total_booleans": cls.total_booleans()}
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/bim/module/void/data.py", line 89, in total_booleans
    representation = tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 326, in by_id
    return self[id]
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/oliveira/.var/app/org.blender.Blender/config/blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3487, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1,590 not found
```

**Comment by Moult** [comment]
See FAQ number 5: https://github.com/IfcOpenShell/IfcOpenShell/commit/438ddc17f51308c4a1ecce5641bdbfcf715575a3
