### ISSUE TITLE
Error with `bim.select_type`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3318]
When using `bim.select_type` on certain instances, i get the following error.

Files: [Restaurant_Livingston.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11766550/Restaurant_Livingston.zip)

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/58f0fc69-3c5d-46c9-b411-44add59f7bb9

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\type\operator.py", line 151, in execute
    context.scene.BIMModelProperties.relating_type_id = str(self.relating_type)
TypeError: bpy_struct: item.attr = val: enum "1020543" not found in ('328755', '139', '1110702', '144', '337313', '328460')

```

**Comment by mschwan** [comment]
I observe a very similar issue. Very often, whenever I want to add e.g. a IfcWallType through the BIM Tool, it throws the following error:
```
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1337 pyrna_enum_to_py: current value '8' matches no enum in 'BIMModelProperties', '', 'ifc_class'
Traceback (most recent call last):
  File "/home/martin/.config/blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 67, in invoke
    return self.execute(context)
  File "/home/martin/.config/blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 70, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/martin/.config/blender/3.6/scripts/addons/blenderbim/bim/ifc.py", line 414, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/martin/.config/blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 82, in _execute
    props.relating_type_id = str(self.relating_type_id)
TypeError: bpy_struct: item.attr = val: enum "1840" not found in ('131', '136')
Error: Python: Traceback (most recent call last):
  File "/home/martin/.config/blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 67, in invoke
    return self.execute(context)
  File "/home/martin/.config/blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 70, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/martin/.config/blender/3.6/scripts/addons/blenderbim/bim/ifc.py", line 414, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/martin/.config/blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 82, in _execute
    props.relating_type_id = str(self.relating_type_id)
TypeError: bpy_struct: item.attr = val: enum "1840" not found in ('131', '136')
```
The BIM Tool also does neither show the correct type, nor correct actions in the toolbar:
![Screenshot from 2023-07-02 00-29-16](https://github.com/IfcOpenShell/IfcOpenShell/assets/4512073/3a869de2-3649-4613-b6d3-859facc55127)
When selecting any type from the dropdown, it then shows all correct types, but the error still shows up after trying to add the object.

Using the current development build on commit 6fed9bf

**Comment by Andrej730** [comment]
Fixed issue catched by @theoryshaw 

@mschwan can you please try now - is issue still reproducable for you? If so please send some example .ifc + .blend

**Comment by mschwan** [comment]
Sorry for the late response. I tried reproducing it, but couldn't observe this issue in newly created projects. So guess it is kind of fixed now.

However in an existing project, I see a similar but slightly different error now:
```
Python: Traceback (most recent call last):
  File "/usr/share/blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 85, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 88, in execute
    return IfcStore.execute_ifc_operator(self, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/3.6/scripts/addons/blenderbim/bim/ifc.py", line 421, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 100, in _execute
    props.relating_type_id = str(self.relating_type_id)
    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "282" not found in ('131', '136')
```
This was triggered when I tried to add a door to a wall:
![Screenshot from 2023-07-11 18-01-55](https://github.com/IfcOpenShell/IfcOpenShell/assets/4512073/d2bae90e-23a3-4d0b-9845-26934107e589)
I've attached the project for you to play around with: 
[stadtvilla.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12016798/stadtvilla.zip)

**Comment by Andrej730** [comment]
@mschwan it's a different issue, if you check full traceback in console it says that ifc entity `#2018` is missing - so it fails  somewhere along the way updating ui for currently selected object. Looks very similar to issues that happen if you save .blend file and don't save .ifc (should occur less after db4c61a4722678e850ff2b93e5c1604d0d29dd7a). Please report if there is some other way to reproduce the bug when wall representation is missing.

Traceback:
```
Traceback (most recent call last):
  File "\3.6\scripts\addons\blenderbim\bim\handler.py", line 95, in active_object_callback
    update_bim_tool_props()
  File "\3.6\scripts\addons\blenderbim\bim\handler.py", line 127, in update_bim_tool_props
    AuthoringData.load()
  File "\3.6\scripts\addons\blenderbim\bim\module\model\data.py", line 68, in load
    cls.data["active_representation_type"] = cls.active_representation_type()
  File "\3.6\scripts\addons\blenderbim\bim\module\model\data.py", line 208, in active_representation_type
    representation = tool.Geometry.get_active_representation(bpy.context.active_object)
  File "\3.6\scripts\addons\blenderbim\tool\geometry.py", line 132, in get_active_representation
    return tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
  File "\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 388, in by_id
    return self[id]
  File "\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 376, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4531, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #2 018 not found
```

`#2018` is wall representation:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/3d15d348-5433-422a-aac4-c7dff964d873)

**Comment by mschwan** [comment]
Thanks @Andrej730 for looking into it and the explanation!

> Please report if there is some other way to reproduce the bug when wall representation is missing.

Will do. :+1:
