### ISSUE TITLE
Failed to install BlenderBIM for Blender 3.5.1 on Mac

### ISSUE THREAD

**Issue by slavingia** [IfcOpenShell/IfcOpenShell#3322]
```
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 333, in enable mod = import (module name)
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/_init_py", line 40, in <module> import blenderbim.bim
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/ init
-py", line 22, in <module>
from . import handler, ui, prop, operator, helper
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/handler.py", line 23, in <module> import blenderbim. tool as tool
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/tool/ init _py", line 21, in <module> from blenderbim.tool. boundary import Boundary
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/tool/boundary.py", line 23, in <module> from blenderbim.bim. module.geometry. helper import Helper
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/geometry/ init
-py", line 20, in <module>
from . import ui, prop, operator
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/geometry/prop.py", line 20, in <module> from blenderbim. bim. prop import StrProperty, Attribute File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/prop.py", line 34, in <module> import blenderbim. bim.schema
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/schema.py", line 104, in <module>
ifc = IfcSchema()
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/schema.py", line 54, in.
_init_
self.load pset templates()
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/schema.py", line 59, in load pset templates
self.psetto = ifcopenshell.util.pset.get template(self.schema name)
AttributeError: module 'ifcopenshell' has no attribute 'util
```

**Comment by slavingia** [comment]
>
