### ISSUE TITLE
Error when activating camera

### ISSUE THREAD

**Issue by slavingia** [IfcOpenShell/IfcOpenShell#3323]
```
Python: Traceback (most recent call last):
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 1306, in execute core.activate_drawing_view (tool.Ifc, tool.Drawing, drawing=drawing)
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/core/drawing-py", line 405, in activate_drawing_view drawing_tool.activate_drawing(camera)
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/tool/drawing.py", line 1488, in activate_ drawing
current_representation = tool.Geometry.get_active_representation(obj)
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/tool/geometry.py", line 127, in get active representation return tool.Ifc.get.by_id(obj.data.BIMMeshProperties.ifc_definition_id)
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file. py", line 326, in by id return selflidi
File "Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 314, in_ getitem return entity_instance(self. wrapped _data.by_id(key), self)
File "/Users/sahil/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell _wrapper.py", line 3487, in by_id return _ifcopenshell_ wrapper.file_ by _id(self, id)
RuntimeError: Instance #2,153 not found
```

**Comment by Andrej730** [comment]
Hello! 
Is there way to reproduce it?
A lot of times `Instance #2,153 not found` happen when you save .blend file and not save .ifc and then reopen the project.
