### ISSUE TITLE
Deleting a drawing causes Blender to crash

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#3347]
When I try to delete a drawing by clicking on the X in the Drawings section of the BIM Documentation context menu blender crashes without warning.

Attached is a small file that contains one beam in the My Storey spatial container and one drawing called MY STOREY PLAN. The error should be repeatable by opening the file and trying to delete the drawing via the context menu as described above.

I am running Blender 3.5.1 and BlenderBIM 0.0.230506 on an Apple silicon Mac.

Does anyone know if there is a workaround to manually delete a drawing from an IFC file in BlenderBIM?

[drawing_delete_test.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11861787/drawing_delete_test.ifc.zip)

**Comment by Andrej730** [comment]
@trhyder 

Can you please check blender system console for errors?

To start blender with system console on Mac you need to run it from terminal with something like `"/Applications/Blender 3.5.app/Contents/MacOS/Blender" -con`

**Comment by trhyder** [comment]
Thanks @Andrej730

Unfortunately, after installing BlenderBIM 0.0.230626 it fails to load an ifc project. I get this error from the console after trying to load the above drawing_delete_test.ifc file:

`Traceback (most recent call last):
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/project/operator.py", line 598, in execute
    ifc_importer.execute()
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 247, in execute
    self.create_elements()
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 699, in create_elements
    self.create_generic_elements(self.elements)
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 702, in create_generic_elements
    if isinstance(self.file, ifcopenshell.sqlite):
AttributeError: module 'ifcopenshell' has no attribute 'sqlite'
Error: Python: Traceback (most recent call last):
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/project/operator.py", line 598, in execute
    ifc_importer.execute()
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 247, in execute
    self.create_elements()
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 699, in create_elements
    self.create_generic_elements(self.elements)
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 702, in create_generic_elements
    if isinstance(self.file, ifcopenshell.sqlite):
AttributeError: module 'ifcopenshell' has no attribute 'sqlite'
Location: /Applications/Blender 3.51.app/Contents/Resources/3.5/scripts/modules/bpy/ops.py:113
Traceback (most recent call last):
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/project/operator.py", line 539, in execute
    bpy.ops.bim.load_project_elements()
  File "/Applications/Blender 3.51.app/Contents/Resources/3.5/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/project/operator.py", line 598, in execute
    ifc_importer.execute()
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 247, in execute
    self.create_elements()
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 699, in create_elements
    self.create_generic_elements(self.elements)
  File "/Users/tim/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/import_ifc.py", line 702, in create_generic_elements
    if isinstance(self.file, ifcopenshell.sqlite):
AttributeError: module 'ifcopenshell' has no attribute 'sqlite'
Location: /Applications/Blender 3.51.app/Contents/Resources/3.5/scripts/modules/bpy/ops.py:113
`
Here is also the full console log
[Last login: Sun Jun 25 21:39:52.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11868580/Last.login.Sun.Jun.25.21.39.52.txt)

**Comment by Moult** [comment]
Sorry about that, we're just sneaking in a few extra features now. Try again in an hour or so when there is a new build :)

**Comment by trhyder** [comment]
This issue appears to be fixed now. Thank you!
