### ISSUE TITLE
BlenderBim 230628 - drawing, saving & reloading issues

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3354]
Using Blender 3.6
And BlenderBim-230628-py10

edit: also tested on 3.3.8 LTS and it has all the same issues

A few issues so far:

The drawing dropdown is empty (can't create a new drawing)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/39535eb7-6e5b-4246-a2df-64134ba00f0a)

After saving an ifc the save and save as buttons disappear
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/a07cf715-b91f-4e22-8604-3f119fa2d27b)

When saving a file and reloading the ifc is not displayed correctly:
Saved project file:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/206c990a-ee10-4f0f-987e-a3f720303bfa)

On reopen we get an empty file and this error:

Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 539, in execute
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\lexer.py", line 376, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\lexer.py", line 182, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, allowed=allowed, state=self.state, token_history=last_token and [last_token])
lark.exceptions.UnexpectedCharacters: No terminal defined for ''' at line 1 col 1

'degree',#7);
^

Expecting: {'HASH'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 598, in execute
    ifc_importer.execute()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 225, in execute
    self.calculate_unit_scale()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 1354, in calculate_unit_scale
    self.unit_scale = ifcopenshell.util.unit.calculate_unit_scale(self.file)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\unit.py", line 536, in calculate_unit_scale
    for unit in units.Units:
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\stream.py", line 305, in __getattr__
    attributes = self.stream_wrapper.file.parser.parse(line.strip())[2]
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 125, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parsers\lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parsers\lalr_parser.py", line 83, in parse
    for token in stream:
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\lexer.py", line 391, in lex
    raise UnexpectedToken(t, e.allowed, state=e.state)
lark.exceptions.UnexpectedToken: Unexpected token Token(STRING, "'degree'") at line 1, column 1.
Expected one of: 
	* HASH
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py:113

**Comment by Andrej730** [comment]
related to 20b63f5

**Comment by Andrej730** [comment]
There are still some problems with stream mode, it could be disabled from addon's preferences but by default it's enabled.
I set it to disabled by default for now to avoid this kind of errors.

**Comment by Plae-Blue-Dot** [comment]
Thanks @Andrej730 I disabled the streaming and it's all good

**Comment by Moult** [comment]
Sorry about that definitely nobody should enable streaming unless they're doing some voodoo and have also disabled geometry.
