### ISSUE TITLE
Blenderbim - Extend wall to roof does not work, gives an error

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3357]
So the established process to extend a walls height is this (which works with a wall and a slab):

Step 1: Select wall
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/48e5ce1d-7351-4f20-b6c6-88644928b609)

Step 2: Shift + Select slab
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/1dcab34b-2e85-4c9f-88e0-cb4cae47e33a)

Step 3: Shift-e (extend, even though the tooltip says edit profile) 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/722e587a-eb3e-4fed-a352-f40da6e29fa7)

Step 4: wall rises to meet slab
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/d5b2cb71-2579-4c29-9ed8-b7b39334a81d)

When attempting to extend the wall to the roof element:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/93a72c31-e535-4f8b-9bc3-47a8b30c855e)

It gives this error:

Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\workspace.py", line 380, in invoke
    return self.execute(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 414, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\workspace.py", line 372, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\workspace.py", line 461, in hotkey_S_E
    bpy.ops.bim.enable_editing_extrusion_profile()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 414, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\slab.py", line 618, in _execute
    if extrusion.Position:
AttributeError: 'NoneType' object has no attribute 'Position'
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py:113

Ifc file for testing:
[Wall to roof extend test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11904002/Wall.to.roof.extend.test.ifc.txt)

**Comment by Gorgious56** [comment]
I think these two shortcuts (Extend / Edit Profile) should not be under the same keypresses given that the workflow requires you to select an object that will react ambiguously to it. You've actually already reported this :) https://github.com/IfcOpenShell/IfcOpenShell/issues/3132

**Comment by Plae-Blue-Dot** [comment]
Oh damn, I honestly thought that was resolved and it popped up again, my memory is not what it was,

And agreed they should have different hotkeys I think depreciating the shift-e for the roof and the slab works well, because you can edit the slab with 'tab' now which is way more intuitive. and shift-e = extend just makes more sense

**Comment by Andrej730** [comment]
The error itself was caused by BBIM not detecting a roof and was trying to edit it as a slab profile.

So there are several issues here:
1) Agree that we should remove editing profiles and paths from shift-e since now we have Tab and this way it should be more natural and we'll have additional hotkey.
2) Confusing UI for slab - it says "edit profile" when it actually is going to extend a wall.
3) No way to extend a wall to roof if roof is not a slab.
