### ISSUE TITLE
BlenderBim - Error when attempting to print & delete drawings created before drawing changes

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3358]
Hi all,

I am currently working in an older file and I cant print the drawings anymore, I noticed it just doesn't have the local links to .css file, markers, patterns etc

So after putting in those link it gives me this error:
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 164, in invoke
    return self.execute(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 209, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 322, in generate_linework
    svg_path = self.get_svg_path(cache_type="linework")
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 974, in get_svg_path
    drawing_path = tool.Drawing.get_document_uri(self.camera_document)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 339, in get_document_uri
    if document.is_a("IfcDocumentInformation"):
AttributeError: 'NoneType' object has no attribute 'is_a'

I can create new drawings and start again.

However When attempting to delete the old drawings I get this error:

Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1381, in invoke
    return self.execute(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 82, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 414, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1394, in _execute
    core.remove_drawing(tool.Ifc, tool.Drawing, drawing=drawing)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\drawing.py", line 287, in remove_drawing
    drawing_tool.run_drawing_activate_model()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 1463, in run_drawing_activate_model
    bpy.ops.bim.activate_model()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1279, in execute
    blenderbim.core.geometry.switch_representation(
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\geometry.py", line 102, in switch_representation
    data = geometry.import_representation(obj, representation, apply_openings=apply_openings)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 282, in import_representation
    shape = ifcopenshell.geom.create_shape(settings, element)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 210, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 2378, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process shape
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py:113

**Comment by Moult** [comment]
There is a special upgrade script for old models to be compatible with the new drawing system, I wonder if this helps https://github.com/IfcOpenShell/IfcOpenShell/issues/2978#issuecomment-1510374693

**Comment by Plae-Blue-Dot** [comment]
You are such a boss @Moult It worked like a charm, drawings even print!
