### ISSUE TITLE
Borked this syncing somehow

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3368]
I borked this syncing somehow, not sure how. 

Get the following error. 
My dropbox syncing was not on, so lost a day of work, if this is unrepairable. :/
Oh joy. 

files: [Restaurant_Livingston.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11923250/Restaurant_Livingston.zip)

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1310, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1319, in execute
    core.activate_drawing_view(tool.Ifc, tool.Drawing, drawing=drawing)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\drawing.py", line 426, in activate_drawing_view
    drawing_tool.activate_drawing(camera)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\drawing.py", line 1526, in activate_drawing
    blenderbim.core.geometry.switch_representation(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\geometry.py", line 115, in switch_representation
    geometry.clear_cache(ifc.get_entity(obj))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\geometry.py", line 46, in clear_cache
    cache.remove(element.GlobalId)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1761, in remove
    return _ifcopenshell_wrapper.HdfSerializer_remove(self, guid)
RuntimeError: An unknown error occurred

```

**Comment by Moult** [comment]
Can you try delete the H5 cache?

**Comment by theoryshaw** [comment]
as easy as that. :\\
Thanks! 
For passerbys. 
`bim.purge_hdf5_cache()`
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/31ddadf7-9034-41f3-a231-e34cf9740ee8)
