### ISSUE TITLE
Blender BIM - Wall creation error

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#3370]
Blender 3.6 LTS
BB version - 220702
OSX Mac m1

Following error is produced when creating a wall from the Demo linbrary, works ok on Blender 3.5

```python
Python: Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 67, in invoke
    return self.execute(context)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 70, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/ifc.py", line 414, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 93, in _execute
    if self.generate_layered_element(ifc_class, relating_type):
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/product.py", line 217, in generate_layered_element
    obj = wall.DumbWallGenerator(relating_type).generate()
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/wall.py", line 457, in generate
    return self.derive_from_cursor()
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/wall.py", line 580, in derive_from_cursor
    return self.create_wall()
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/wall.py", line 596, in create_wall
    element = blenderbim.core.root.assign_class(
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/core/root.py", line 74, in assign_class
    collector.sync(obj)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/collector.py", line 50, in sync
    object_collection = cls._get_collection(element, obj)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/collector.py", line 212, in _get_collection
    project_obj = tool.Ifc.get_object(tool.Ifc.get().by_type("IfcProject")[0])
IndexError: list index out of range
```

**Comment by Moult** [comment]
Something looks fundamentally broken, not just creating walls. What happens if you run this in the console after creating a fresh demo project and/or just before / after creating a wall?

```python
import blenderbim.tool as tool
print(tool.Ifc.get().by_type("IfcProject")[0])
```

**Comment by Andrej730** [comment]
check console error prior to that, there must be some other issue when you create project

**Comment by ChubbyQuark** [comment]
Just tested again after a re-start. Creating a new wall works but adding a door to the wall produces the error submitted in #3371

**Comment by Moult** [comment]
Screenshared and wasn't able to recreate.
