### ISSUE TITLE
Error when using butt tool on walls

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3382]
Error when using butt tool on walls

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 384, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 414, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 376, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\workspace.py", line 559, in hotkey_S_T
    bpy.ops.bim.join_wall(join_type="L")
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: It requires 2 selected objects to do join of type L

```

**Comment by Moult** [comment]
> RuntimeError: Error: It requires 2 selected objects to do join of type L

Did you have two walls selected?
