### ISSUE TITLE
BBIM_Array error

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3386]
When i try to delete a non-ifc object in the following file, it throws error.
ping @brunoperdigao 

![2023-07-05_22-39-37_Blender_ DDropboxGitLabrestaurant_livingston_Encry_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/0115c1c7-3fb8-4c34-8a01-66133802915d)

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 406, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 385, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 414, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 418, in _execute
    pset = ifcopenshell.util.element.get_pset(tool.Ifc.get_entity(obj), "BBIM_Array")
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\element.py", line 53, in get_pset
    if element.is_a("IfcTypeObject"):
AttributeError: 'NoneType' object has no attribute 'is_a'

```

**Comment by theoryshaw** [comment]
files: https://www.dropbox.com/s/cwjbkqymturmo15/Restaurant_Livingston.zip?dl=1
