### ISSUE TITLE
IfcRailing modifier loop throws an error

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3415]
I'm trying to model this using the IfcRailing modifier, so I created an hexagonal loop of edges which threw an error and corrupted the object.

Would it be a valid usecase or am I trying to do something not smart ?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/1ed5d9dc-728b-4520-a5e7-9164847b16b8)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/67c43213-9fd2-4ce7-ab56-6bbfb15fd34e)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/55316839-3c9a-4b86-97a9-4b5bbf4cbb75)

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1381, in invoke
    return IfcStore.execute_ifc_operator(self, context, is_invoke=True)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 415, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1417, in _invoke
    bpy.ops.bim.finish_editing_railing_path()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 136, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 417, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\railing.py", line 501, in _execute
    update_railing_modifier_bmesh(context)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\railing.py", line 136, in update_railing_modifier_bmesh
    new_verts = [bm.verts.new(Vector(v) * si_conversion) for v in path_data["verts"]]
TypeError: 'NoneType' object is not subscriptable
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py:113
```

**Comment by Moult** [comment]
You're right, we should add support for closed loops!
