### ISSUE TITLE
IfcSverchok installation error 

### ISSUE THREAD

**Issue by smr02** [IfcOpenShell/IfcOpenShell#3418]
I get the following error when installing IfcSverchok. Both on MacOS and Ubuntu. 

Blender: v3.6.0
BlenderBIM: v0.0.230710
Sverchok: v1.2.0
IFCSverchok: v0.0.230704

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/ifcsverchok/__init__.py", line 278, in register
    module.register()
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/ifcsverchok/nodes/ifc/create_file.py", line 64, in register
    bpy.utils.register_class(SvIfcCreateFile)
ValueError: register_class(...): already registered as a subclass 'SvIfcCreateFile'
```

**Comment by smr02** [comment]
the above error only shows when trying to activate ifcsverchok the second time. The first time  the following: 

```
Traceback (most recent call last):
  File "/snap/blender/3763/3.6/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/home/user/.config/blender/3.6/scripts/addons/ifcsverchok/__init__.py", line 278, in register
    module.register()
  File "/home/user/.config/blender/3.6/scripts/addons/ifcsverchok/nodes/ifc/api_WIP.py", line 129, in register
    bpy.utils.register_class(SvIfcTooltip)
NameError: name 'SvIfcTooltip' is not defined

```

**Comment by Moult** [comment]
Oh sorry about that, I think this was discussed before but never committed - can you just delete the api_WIP entirely and test it / submit a new PR? It's not needed.
