### ISSUE TITLE
Can't add Level (Plan) to a floor plan drawing

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#3432]
The level tool was not working for me on the previous version. When the latest release became available I updated and tried again on my existing project file. But it still doesn't work. I am using a M1 Mac install of Blender 3.6 on the latest release of BBim.

The sequence I did to replicate the issue:
1. load the below ifc file
2. go into any floor plan camera (say SITE PLAN)
3. In the Annotation Tool select Level (Plan) and Add Annodation

I expected to see a dimension level.

Instead, I get the below error:

`Python: Traceback (most recent call last):
  File "/Applications/Blender 3.6 LTS.app/Contents/Resources/3.6/scripts/startup/bl_ui/space_view3d.py", line 36, in draw
    self.draw_tool_settings(context)
  File "/Applications/Blender 3.6 LTS.app/Contents/Resources/3.6/scripts/startup/bl_ui/space_view3d.py", line 49, in draw_tool_settings
    tool = ToolSelectPanelHelper.draw_active_tool_header(
  File "/Applications/Blender 3.6 LTS.app/Contents/Resources/3.6/scripts/startup/bl_ui/space_toolsystem_common.py", line 809, in draw_active_tool_header
    draw_settings(context, layout, tool)
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/workspace.py", line 72, in draw_settings
    AnnotationToolUI.draw(context, layout)
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/workspace.py", line 175, in draw
    AnnotationData.load()
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/data.py", line 332, in load
    cls.data["relating_types"] = cls.get_relating_types()
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/data.py", line 339, in get_relating_types
    if tool.Drawing.is_annotation_object_type(relating_type, object_type):
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/drawing.py", line 154, in is_annotation_object_type
    if element_type == "IfcTypeProduct" and element.ApplicableOccurrence.startswith("IfcAnnotation/"):
AttributeError: 'NoneType' object has no attribute 'startswith'
`

[Mashoobra.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12034344/Mashoobra.ifc.zip)

**Comment by Moult** [comment]
Great! You found a bug!

After the fix, note that you'll need to add an Annotation/PLAN_VIEW representation context as well to store the plan level.

**Comment by trhyder** [comment]
@Moult I tried to install blenderbim-230713-py310-macosm1.zip but after installing the zip it wont activate.

I got the following terminal log:

`Read prefs: "/Users/tim/Library/Application Support/Blender/3.6/config/userpref.blend"
Device with name Apple M1 Ultra supports metal minimum requirements
METAL API - DETECTED GPU: Apple M1 Ultra
WARN (bgl): source/blender/python/generic/bgl.c:2662 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.
sv: import settings
sv: SciPy package is not available. Voronoi nodes and RBF-based nodes will not be available.
sv: geomdl package is not available, some NURBS related nodes will not be available
sv: SciKit-Image package is not available; SciKit-based implementation of Marching Cubes and Marching Squares will not be available
sv: PyMCubes package is not available. PyMCubes-based implementation of Marching Cubes will not be available
sv: Circlify package is not available. Circlify node will not be available
sv: FreeCAD package is not available, Solids nodes will not be available
sv: Numba package is not available, njit compiled functions will not be available
sv: pyOpenSubdiv package is not available, the OpenSubdivision node (Catmull-Clark subdivision) will not be available
sv: Dependencies available: pip, Cython.
sv: import all modules
sv: enable internal debug logging.
2023-07-13 09:25:45,853 [INFO] logging: log level, 20
 ______ _    _ _______  ______ _______ _     _  _____  _     _
/______  \  /  |______ |_____/ |       |_____| |     | |____/ 
______/   \/   |______ |    \_ |_____  |     | |_____| |    \_
initialized.

sv: version: v1.1.0
2023-07-13 09:25:45,939 [INFO] ladybug: Successfully imported Ladybug plugin: ladybug_tools
2023-07-13 09:25:45,940 [INFO] ladybug: Successfully imported Ladybug plugin: ladybug_comfort
2023-07-13 09:25:45,940 [INFO] ladybug: Successfully imported Ladybug plugin: ladybug_geometry
2023-07-13 09:25:46,044 [INFO] ladybug_tools 141: Registered 84 nodes
2023-07-13 09:25:46,053 [INFO] ladybug_tools 158: Node `SvPMV Polygon' is not available (probably due to missing dependencies).
addon_utils.disable: blenderbim not disabled
Modules Installed (blenderbim) from '/Users/tim/Downloads/blenderbim-230713-py39-macosm1.zip' into '/Users/tim/Library/Application Support/Blender/3.6/scripts/addons'
Traceback (most recent call last):
  File "/Applications/Blender 3.6 LTS.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/__init__.py", line 40, in <module>
    import blenderbim.bim
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/handler.py", line 24, in <module>
    import blenderbim.tool as tool
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/__init__.py", line 21, in <module>
    from blenderbim.tool.boundary import Boundary
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/boundary.py", line 23, in <module>
    from blenderbim.bim.module.geometry.helper import Helper
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/geometry/__init__.py", line 20, in <module>
    from . import ui, prop, operator
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 37, in <module>
    from blenderbim.bim import import_ifc
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/import_ifc.py", line 39, in <module>
    from blenderbim.bim.module.drawing.prop import ANNOTATION_TYPES_DATA
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/__init__.py", line 20, in <module>
    from . import ui, prop, operator, handler, gizmos, workspace
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/ui.py", line 30, in <module>
    from blenderbim.bim.module.drawing.prop import ANNOTATION_TYPES_DATA
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/prop.py", line 27, in <module>
    import blenderbim.bim.module.drawing.decoration as decoration
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/decoration.py", line 25, in <module>
    import shapely
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/shapely/__init__.py", line 1, in <module>
    from .lib import GEOSException  # NOQA
ModuleNotFoundError: No module named 'shapely.lib'`

**Comment by Moult** [comment]
You are on Blender 3.6 so you should be installing py310 not py39 - hope that helps :)

**Comment by Moult** [comment]
No, that's normal. The views are lazy loaded as-needed when you activate drawings. Imagine you have 500 drawings, we don't want to load them all at once.

**Comment by trhyder** [comment]
Hmmm... so where have you hidden the Load Drawings button now. I don't see the BIM Documentation in the context toggle anymore.

**Comment by Moult** [comment]
The scene properties tab now has a dropdown at the top. It defaults to project overview. You can change it to drawings and docs.

**Comment by trhyder** [comment]
Sorry to bug you again, but I still can't get a Level (Plan) annotation in my existing file (it works fine in a new file).

If I add an Untyped Level (Plan), nothing happens.
If I save a new Type before adding a new Level (Plan), it added a Level (Plan) but I get an error and when I try to generate a SVG it switches off.

Below is the error that is generated:

`Python: Traceback (most recent call last):
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/workspace.py", line 283, in invoke
    return self.execute(context)
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/workspace.py", line 36, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/ifc.py", line 421, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/workspace.py", line 278, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/workspace.py", line 300, in hotkey_S_A
    create_annotation()
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/workspace.py", line 192, in create_annotation
    create_annotation_occurence(bpy.context)
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/workspace.py", line 172, in create_annotation_occurence
    element = tool.Drawing.run_root_assign_class(
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/drawing.py", line 777, in run_root_assign_class
    return blenderbim.core.root.assign_class(
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/core/root.py", line 70, in assign_class
    root.run_geometry_add_representation(
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/root.py", line 151, in run_geometry_add_representation
    return blenderbim.core.geometry.add_representation(
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/core/geometry.py", line 45, in add_representation
    representation = ifc.run(
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/ifc.py", line 30, in run
    return ifcopenshell.api.run(command, IfcStore.get_file(), **kwargs)
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "/Users/tim/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/geometry/add_representation.py", line 68, in execute
    if self.settings["context"].ContextType == "Model":
AttributeError: 'NoneType' object has no attribute 'ContextType'`

I think I have perhaps not understood how to "After the fix, note that you'll need to add an Annotation/PLAN_VIEW representation context as well to store the plan level."

**Comment by Moult** [comment]
All geometry has to belong to a "geometric context". For example, a door might have two geometries - one 3D one of the 3D body of the door, and a 2D symbolic one with a swing to show it in plan view, and another 2D one to show it a section or elevation with a triangle showing the swing / hinge.

So in order to create plan levels, you first need to have the appropriate geometric context. In this case it should be an Annotation (since it is an annotation) and PLAN_VIEW target since it is intended to be viewed top down in plan.

You can add this in the Scene Tab > Project Overview > Geometry > Geometric Representation Contexts panel.
