### ISSUE TITLE
Error when importing ifc models in 20230717 and 18

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#3469]
I don't get this in 20230716 so something must have been broken in the newer builds. I tested only on Windows.

obj.BIMObjectProperties.ifc_definition_id = [element.id](http://element.id/)()
AttributeError: 'Curve' object has no attribute 'BIMObjectProperties'. Did you mean: 'BIMMeshProperties'

**Comment by BIMvoice** [comment]
You're quick, thank you :)

**Comment by BIMvoice** [comment]
And I can confirm that now it works as it is supposed to. Thank you!

**Comment by BIMvoice** [comment]
Unfortunately, I got again another error, with the 20230719 version:

`Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 597, in execute
    return self.finish_loading_project(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 611, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 670, in execute
    ifc_importer.execute()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 247, in execute
    self.create_elements()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 705, in create_elements
    self.create_generic_elements(self.elements)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 718, in create_generic_elements
    products = self.create_products(elements, settings=self.settings_curve)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 819, in create_products
    self.create_product(product, shape)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 983, in create_product
    self.material_creator.create(element, obj, mesh)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 72, in create
    self.assign_material_slots_to_faces()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 146, in assign_material_slots_to_faces
    slot_index = self.mesh.materials.find(self.styles[material].name)
KeyError: 1746
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113
`

**Comment by Moult** [comment]
I think this is a different error. Can you share your model?

**Comment by BIMvoice** [comment]
Yes, you can download it from here: https://sites.google.com/view/simba-bim-krav/simba-2-0/simba-2-0-referansemodeller
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/5aa26b87-7726-45e3-a18b-0499663b757e)
