### ISSUE TITLE
Fills for Type's 2D representation

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3473]
A way to have a 'fill' in a type's 2D representation, as discussed here: 
https://community.osarch.org/discussion/1575/configure-a-type-where-the-2d-representation-has-a-fill

**Comment by chopinregis** [comment]
i tested this feature, but i repeatedly get errors,
Here are some screenshots, and the error message i got.

Python: Traceback (most recent call last):
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 43, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 334, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 98, in _execute
    core.add_representation(
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\geometry.py", line 45, in add_representation
    representation = ifc.run(
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 32, in run
    return ifcopenshell.api.run(command, IfcStore.get_file(), **kwargs)
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 73, in execute
    return self.create_plan_representation()
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 170, in create_plan_representation
    return self.create_annotation2d_representation()
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 827, in create_annotation2d_representation
    items = [self.file.createIfcGeometricCurveSet(self.create_curves(is_2d=True))]
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 467, in create_curves
    if self.is_mesh_curve_consequtive(geom_data):
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 422, in is_mesh_curve_consequtive
    start_vert = bm.verts[0]
IndexError: BMElemSeq[index]: index 0 out of range

![Snipaste_2023-07-31_09-31-12](https://github.com/IfcOpenShell/IfcOpenShell/assets/13260872/71f3978b-d517-4c65-9eb8-dc91649a2789)

![Screenshot 2023-07-31 093144](https://github.com/IfcOpenShell/IfcOpenShell/assets/13260872/17e762a0-58ac-46b0-bcb8-b343f9f26b89)

![Screenshot 2023-07-31 093201](https://github.com/IfcOpenShell/IfcOpenShell/assets/13260872/0c1c3d80-5cc0-4e08-9477-a2ddbbe37c1e)

![Screenshot 2023-07-31 093233](https://github.com/IfcOpenShell/IfcOpenShell/assets/13260872/f19fb647-3193-4350-8983-86750cd25c12)

**Comment by theoryshaw** [comment]
Here's a test file that used to work at one point in the past. 
https://www.dropbox.com/scl/fo/8odi2um3tg4pjp9uw6ywk/h?rlkey=gg01g448x5mfopo0gy8fadfys&dl=0

This was the general hacky approach...

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9fbb0044-f7c4-440a-b6f6-28bd0e4e71ab)


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/a560b5c0-b45b-4e11-8fc2-0b25bd6cdfcb
