### ISSUE TITLE
Blender restart required to uninstall BlenderBIM - on Windows

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#3481]
I don't know if it's only me, but I must confess this is very annoying.

I cannot uninstall the existing enabled BlenderBIM Add-on without restarting it. I need first to disable it and then restart Blender, otherwise, I get this error:

`Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\startup\bl_operators\userpref.py", line 785, in execute
    shutil.rmtree(path)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\shutil.py", line 620, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\shutil.py", line 618, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Ingen tilgang: 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\blenderbim\\libs\\site\\packages\\ifcopenshell\\_ifcopenshell_wrapper.pyd'
`
Only after that, do I get to uninstall and install the new version I want in one go.

This is not happening on my Mac M1.

Looks like it's a permission error, and I wonder if it's anything that can be done without involving or depending again on my IT dep.

**Comment by Moult** [comment]
There's nothing we can do about this. https://blenderbim.org/docs/users/installation.html#uninstalling

**Comment by BIMvoice** [comment]
I understand, thank you. Very interesting though, how come it just works on Mac.

**Comment by Moult** [comment]
Linux and Mac don't have this problem because Mac and Linux can reference objects even though they've been moved / removed. For example on Linux you can rename a file even while it's open whereas on Windows you keep on getting annoying popups like "This file is open somewhere blah blah blah"
