### ISSUE TITLE
error with `bpy.ops.bim.generate_space()`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3482]
This might be [known issue](https://github.com/IfcOpenShell/IfcOpenShell/issues/3391) already, but it seems space regeneration fails. 

- select all walls.
- `bpy.ops.bim.generate_spaces_from_walls()`
- move 1 wall
- try `bpy.ops.bim.generate_space()`
- get the following error.

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\spatial\workspace.py", line 153, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\spatial\workspace.py", line 33, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 334, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\spatial\workspace.py", line 148, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\spatial\workspace.py", line 181, in hotkey_S_G
    bpy.ops.bim.generate_space()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.bim.generate_space.poll() failed, context is incorrect

```

**Comment by maxfb87** [comment]
@theoryshaw when you execute "generate_space”, is the storey collection selected?

**Comment by maxfb87** [comment]
Better, if you have already generated the spaces and after you want to update an existing one, you can select the space and execute "generate_space"..it should work

**Comment by theoryshaw** [comment]
That was it!  Although, there's a conflict with DEMOLISH walls, on the space regen.  Will create another issue.
