### ISSUE TITLE
Error when `bim.generate_space`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3498]
I pulled the latest. 

error when `bim.generate_space`

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\ifc.py", line 186, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 334, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\space.py", line 104, in _execute
    or not tool.Drawing.is_intersecting_plane(obj, self.cut_point, self.cut_normal)
AttributeError: type object 'Drawing' has no attribute 'is_intersecting_plane'. Did you mean: 'is_intersecting_camera'?
```

**Comment by theoryshaw** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/15884ff2-3f26-4df9-ae41-2abc693711ea

**Comment by Moult** [comment]
Sorry forgot to commit.
