### ISSUE TITLE
[BlenderBIM] Warnings when loading New Demo Project

### ISSUE THREAD

**Issue by marcuspollio** [IfcOpenShell/IfcOpenShell#3514]
Hi there !

When trying the latest dev BlenderBIM version (0.230727-06ea051) and File > New IFC Project > New Demo Project, the Info Console in the Status Bar displays some warnings:

<details><summary>Warning when loading Demo Project</summary>
<code>bpy.ops.bim.select_library_file(filepath="/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/data/libraries/IFC4 Demo Library.ifc")
bpy.ops.bim.append_library_element(definition=21)
bpy.ops.bim.append_library_element(definition=26)
bpy.ops.bim.append_library_element(definition=30)
bpy.ops.bim.append_library_element(definition=34)
bpy.ops.bim.append_library_element(definition=38)
bpy.ops.bim.append_library_element(definition=42)
bpy.ops.bim.append_library_element(definition=48)
bpy.ops.bim.append_library_element(definition=54)
bpy.ops.bim.append_library_element(definition=59)
bpy.ops.bim.append_library_element(definition=63)
bpy.ops.bim.append_library_element(definition=67)
bpy.ops.bim.append_library_element(definition=72)
bpy.ops.bim.append_library_element(definition=77)
bpy.ops.bim.append_library_element(definition=82)
bpy.ops.bim.append_library_element(definition=87)
bpy.ops.bim.append_library_element(definition=92)
bpy.ops.bim.append_library_element(definition=96)
bpy.ops.bim.create_project()
bpy.ops.bim.new_project(preset="demo")
Python: Traceback (most recent call last):
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 82, in execute
    bpy.ops.bim.create_project()
  File "/home/XXX/blender-git/build_linux/bin/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 95, in execute
    self._execute(context)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 108, in _execute
    core.create_project(tool.Ifc, tool.Project, schema=props.export_schema, template=template)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/core/project.py", line 89, in create_project
    project.append_all_types_from_template(template)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/tool/project.py", line 37, in append_all_types_from_template
    bpy.ops.bim.append_library_element(definition=element.id())
  File "/home/XXX/blender-git/build_linux/bin/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 382, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/ifc.py", line 334, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 395, in _execute
    self.import_type_from_ifc(element, context)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 436, in import_type_from_ifc
    ifc_importer.create_element_type(element)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/import_ifc.py", line 658, in create_element_type
    tool.Loader.link_mesh(shape, mesh)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/tool/loader.py", line 73, in link_mesh
    mesh.BIMMeshProperties.ifc_definition_id = int(geometry.id.replace(",", ""))
AttributeError: 'NoneType' object has no attribute 'BIMMeshProperties'
Location: /home/XXX/blender-git/build_linux/bin/4.0/scripts/modules/bpy/ops.py:109</code>
</details>

Then, trying to add e.g. a new IFCWall via the Toolbar displays these warnings:

<details><summary>Warning when adding IFCWall via Toolbar</summary>
<code>Python: Traceback (most recent call last):
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/model/workspace.py", line 504, in invoke
    return self.execute(context)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/tool/ifc.py", line 186, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/ifc.py", line 334, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/model/workspace.py", line 496, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/model/workspace.py", line 516, in hotkey_S_A
    bpy.ops.bim.add_constr_type_instance()
  File "/home/XXX/blender-git/build_linux/bin/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/model/product.py", line 122, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/ifc.py", line 334, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/model/product.py", line 148, in _execute
    if self.generate_layered_element(ifc_class, relating_type):
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/model/product.py", line 270, in generate_layered_element
    obj = wall.DumbWallGenerator(relating_type).generate()
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/model/wall.py", line 458, in generate
    return self.derive_from_cursor()
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/model/wall.py", line 581, in derive_from_cursor
    return self.create_wall()
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/bim/module/model/wall.py", line 631, in create_wall
    blenderbim.core.geometry.switch_representation(
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/core/geometry.py", line 111, in switch_representation
    geometry.rename_object(data, geometry.get_representation_name(representation))
  File "/home/XXX/.config/blender/4.0/scripts/addons/blenderbim/tool/geometry.py", line 531, in rename_object
    obj.name = name
AttributeError: 'NoneType' object has no attribute 'name'
Location: /home/XXX/blender-git/build_linux/bin/4.0/scripts/modules/bpy/ops.py:109</code>
</details>

Blender version is latest local build main branch (4.0 dev), python is 3.10.12

Do you need any more infos ?

By the way, the new Tools Icons in the Toolbar are super cool ! =D
Thanks in advance !

**Comment by Moult** [comment]
I can't seem to recreate this. Would you be able to do a screenshare with me if we agree on a time/day? I'm available 9 to 5 sydney timezone

**Comment by marcuspollio** [comment]
Hi @Moult 
Thanks for your answer.
Ok, I just tested with a fresh local build of Blender LTS (3.6.1) and there's no warnings.
So it's either on my side or Blender 4.0 as of now, but not BlenderBIM addon's fault.
Sorry for the noise. At least you know I like the new icons =P

**Comment by marcuspollio** [comment]
Hi @Moult 
Thanks for your answer.
Ok, I just tested with a fresh local build of Blender LTS (3.6.1) and there's no warnings.
So it's either on my side or Blender 4.0 as of now, but not BlenderBIM addon's fault.
Sorry for the noise. At least you know I like the new icons =P
