### ISSUE TITLE
'IfcSlab/Slab' can't be selected because it is not in View Layer 'ViewLayer'!

### ISSUE THREAD

**Issue by kjell-arne** [IfcOpenShell/IfcOpenShell#3550]
Python: Traceback (most recent call last):
  File "C:\Users\kjell\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\product.py", line 67, in invoke
    return self.execute(context)
  File "C:\Users\kjell\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\product.py", line 70, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\kjell\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 414, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\kjell\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\product.py", line 93, in _execute
    if self.generate_layered_element(ifc_class, relating_type):
  File "C:\Users\kjell\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\product.py", line 215, in generate_layered_element
    obj = slab.DumbSlabGenerator(relating_type).generate()
  File "C:\Users\kjell\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\slab.py", line 143, in generate
    return self.derive_from_cursor()
  File "C:\Users\kjell\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\slab.py", line 147, in derive_from_cursor
    return self.create_slab()
  File "C:\Users\kjell\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\model\slab.py", line 218, in create_slab
    obj.select_set(True)
RuntimeError: Error: Object 'IfcSlab/Slab' can't be selected because it is not in View Layer 'ViewLayer'!

**Comment by Andrej730** [comment]
@kjell-arne can you please share example .blend + .ifc where the issue occurs?

**Comment by kjell-arne** [comment]
How can I upload the file?

**Comment by Andrej730** [comment]
@kjell-arne you can upload it here, just add ".txt" to the file extension. For example "test.blend" -> "test.blend.txt".

**Comment by Moult** [comment]
Bump @kjell-arne
