### ISSUE TITLE
BlenderBim - When activating elevation view produces an error

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3582]
When activating an elevation view from an older file created on 23023.08.03

It produces this error:

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1458, in invoke
    return self.execute(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1467, in execute
    core.activate_drawing_view(tool.Ifc, tool.Drawing, drawing=drawing)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\drawing.py", line 429, in activate_drawing_view
    drawing_tool.activate_drawing(camera)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 1649, in activate_drawing
    blenderbim.core.geometry.switch_representation(
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\geometry.py", line 110, in switch_representation
    data = geometry.import_representation(obj, representation, apply_openings=apply_openings)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 440, in import_representation
    shape = ifcopenshell.geom.create_shape(settings, element)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 210, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 2394, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process shape

**Comment by theoryshaw** [comment]
I'm not sure how to remove IfcOpeningElements, however.

**Comment by Moult** [comment]
Can you share your model? dion@thinkmoult.com if private.

**Comment by Plae-Blue-Dot** [comment]
@theoryshaw You are a genius, I'd obviously created some corrupt roof model by accident, after removing no error.

@Moult I've sent the model via email, It's resolved but I've been having this error pop up frequently lately

**Comment by Moult** [comment]
Cheers, so the root cause is that somehow you have managed to create a pure vertex representation (i.e. no edges no faces) ... without any vertices. So uh, nothing at all :)

This shouldn't be possible. But turns out it is. Let me know if you have any ideas how that might've occurred!

**Comment by Moult** [comment]
Because it's a roof, ping @Andrej730 is there any possible scenario where a roof generation might fail (e.g. due to invalid closed profile, etc) and update_representation or add_representation which would then have a representation not of the generated roof but instead of the roof profile (or invalid profile)?

**Comment by Andrej730** [comment]
@Moult not sure if there is some weird case where it will pass but currently it won't allow you finish editing path with invalid roof footprint - therefore the only option for user would be to either fix it or to cancel and get back to the previous roof shape that was valid.
