### ISSUE TITLE
Error when using `.IfcDoor, Pset_DoorCommon.Status=NEW` in IFCCSV.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3584]
I'm using `.IfcDoor, Pset_DoorCommon.Status=NEW` in ...
![](https://community.osarch.org/uploads/editor/a2/g80axgll5wzy.png "")

And get this error, when `bim.export_ifccsv`

I'm assuming that IFCCSV uses the IFC facet-based selector syntax, correct?

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\csv\operator.py", line 151, in execute
    results = ifcopenshell.util.selector.filter_elements(ifc_file, props.ifc_selector)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 118, in filter_elements
    transformer.transform(filter_elements_grammar.parse(query))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 194, in parse
    return self._parse(text, start)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\parsers\earley.py", line 292, in parse
    to_scan = self._parse(stream, columns, to_scan, start_symbol)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 138, in _parse
    to_scan = scan(i, to_scan)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 115, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan))
lark.exceptions.UnexpectedCharacters: No terminal defined for '.' at line 1 col 1

.IfcDoor, Pset_DoorCommon.Status=NEW
^

Expecting: {'LOCATION', 'BANG', 'ESCAPED_STRING', 'MATERIAL', 'TYPE', 'SLASH', '__ANON_0', 'CLASSIFICATION', '__ANON_3', '__ANON_2', '__ANON_1'}

```

**Comment by Moult** [comment]
Yep, so remove the "."

**Comment by theoryshaw** [comment]
Cool. 

I tried `IfcDoor, Pset_DoorCommon.Status=NEW`, but nothing was exported to the .ODS file.

**Comment by theoryshaw** [comment]
`IfcWall, Pset_WallCommon.FireRating=2 HR`

gives the following error...

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\csv\operator.py", line 151, in execute
    results = ifcopenshell.util.selector.filter_elements(ifc_file, props.ifc_selector)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 118, in filter_elements
    transformer.transform(filter_elements_grammar.parse(query))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 194, in parse
    return self._parse(text, start)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\parsers\earley.py", line 292, in parse
    to_scan = self._parse(stream, columns, to_scan, start_symbol)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 138, in _parse
    to_scan = scan(i, to_scan)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 115, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan))
lark.exceptions.UnexpectedCharacters: No terminal defined for 'H' at line 1 col 39

IfcWall, Pset_WallCommon.FireRating=2 HR
                                      ^

Expecting: {'PLUS', 'COMMA'}

```

but, `IfcWall, Pset_WallCommon.FireRating="2 HR"` works. 

... but `IfcDoor, Pset_DoorCommon.Status="NEW"` does not.

**Comment by Moult** [comment]
2 HR has a space, so you need to quote it.
