### ISSUE TITLE
BlenderBIM: cant import xml file (schedule export from P6) 

### ISSUE THREAD

**Issue by isma1453** [IfcOpenShell/IfcOpenShell#3603]
Hi there,
So, I am fairly new to BlenderBIM and this forum.
I have an imported IFC 4.3 file in BlenderBIM and I am also trying to import an .xml file but whenever I try to import it, it gives me errors:
_Traceback (most recent call last):
  File "C:\Users\isma\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 572, in execute
    p62ifc.execute()
  File "C:\Users\isma\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc4d\p62ifc.py", line 83, in execute
    ifcCreator.create_ifc()
  File "C:\Users\isma\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 36, in create_ifc
    self.create_calendars()
  File "C:\Users\isma\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 52, in create_calendars
    self.process_exceptions(calendar.get("HolidayOrExceptions"), calendar["ifc"])
  File "C:\Users\isma\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 102, in process_exceptions
    self.process_full_day_exceptions(year, month, month_data, calendar)
  File "C:\Users\isma\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc4d\common.py", line 110, in process_full_day_exceptions
    ifcopenshell.api.run(
  File "C:\Users\isma\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\isma\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\sequence\edit_work_time.py", line 60, in execute
    setattr(self.settings["work_time"], name, value)
  File "C:\Users\isma\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 225, in __setattr__
    self[index] = value
  File "C:\Users\isma\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 239, in __setitem__
    method = self.method_list[idx]
IndexError: list index out of range_

the .xml file is an export from Primavera (P6 .xml).
I realized that at least for the dates it was an error regarding the format (changed the format to what Blender wanted and it seemed to fix that error) I looked into all the other errors, but could not understand what the issue with those are.
I hope someone can help me out here.
Thanks in advance!

**Comment by Andrej730** [comment]
Hello! Can you please share example .ifc and .xml?

**Comment by isma1453** [comment]
> Hello! Can you please share example .ifc and .xml?
hi yes, forgot to do so. here you go! :)
[Blender import.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12377200/Blender.import.zip)

**Comment by Moult** [comment]
It works fine for me :) I think the error you're experiencing is that you're working with IFC2X3. IFC2X3 has generally significantly less 4D/5D capabilities compared to IFC4, so at the moment the BlenderBIM Add-on has not got any official support for using IFC2X3 for 4D/5D purposes. if anything works, it's coincidental, not intentional :)

If you create a blank IFC4 project then import in your XML, I see this:

![2023-08-18-215412_981x973_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/eec6472f-6ffc-4b7c-a229-7a30be5d52c9)

Here's the gantt chart (admittedly it's a very big detailed schedule so it's not the cleanest rendering):

![2023-08-18-221321_1920x878_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/7a815cfc-cb74-471a-8fd2-ac8c55a2422a)

**Comment by isma1453** [comment]
> It works fine for me :) I think the error you're experiencing is that you're working with IFC2X3. IFC2X3 has generally significantly less 4D/5D capabilities compared to IFC4, so at the moment the BlenderBIM Add-on has not got any official support for using IFC2X3 for 4D/5D purposes. if anything works, it's coincidental, not intentional :)
> 
> If you create a blank IFC4 project then import in your XML, I see this:
> 
> ![2023-08-18-215412_981x973_scrot](https://user-images.githubusercontent.com/88302/261602141-eec6472f-6ffc-4b7c-a229-7a30be5d52c9.png)
> 
> Here's the gantt chart (admittedly it's a very big detailed schedule so it's not the cleanest rendering):
> 
> ![2023-08-18-221321_1920x878_scrot](https://user-images.githubusercontent.com/88302/261602242-7a815cfc-cb74-471a-8fd2-ac8c55a2422a.png)

Hi Moult, thanks for your fast reply! the imported ifc model should be ifc 4.3 as far as I know. I have tried to create a new ifc 4 project in BlenderBIM and tried to import again, but same issue..

Do you mind uploading a picture of from where you are importing the xml into BlenderBIM? maybe the way I am trying to import is wrong - I have tried to import the xml from: File>Import>P6(.xml)

**Comment by Moult** [comment]
IFC4.3 changed their attribute names of IfcWorkTime which can explain the error you're getting (we haven't tested much against IFC4X3) ... but it should work in IFC4. If you're online now, you can jump on https://meet.jit.si/openbim and screenshare and we can check.

You might also want to make sure you're using the latest version: https://github.com/IfcOpenShell/IfcOpenShell/releases/download/blenderbim-230818/blenderbim-230818-py310-win.zip - there are very often many bug fixes and the "stable" version from the website is almost 2 months old which is very outdated.

**Comment by isma1453** [comment]
I am out the office at the moment, would it be possible to meet on Monday perhaps? in the meantime, I will make sure everything is up to date and give it another try throughout the weekend. 

Thank you for your help!

**Comment by isma1453** [comment]
How about 4:30pm Sydney timezone? (That is the time I will be in office, as you are 8 hours ahead of Copenhagen timezone)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Moult** [comment]
Tuesday 4:30pm Sydney timezone works for me if that's OK with you.

**Comment by isma1453** [comment]
Hi again,
Tuesday 4:30pm Sydney timezone sounds good

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by isma1453** [comment]
> IFC4.3 changed their attribute names of IfcWorkTime which can explain the error you're getting (we haven't tested much against IFC4X3) ... but it should work in IFC4. If you're online now, you can jump on https://meet.jit.si/openbim and screenshare and we can check.
> 
> You might also want to make sure you're using the latest version: https://github.com/IfcOpenShell/IfcOpenShell/releases/download/blenderbim-230818/blenderbim-230818-py310-win.zip - there are very often many bug fixes and the "stable" version from the website is almost 2 months old which is very outdated.


Hi Moult. thanks for all the help. this solution worked! I updated BlenderBIM to the newest version you have sent me and using IFC 4 (4.3 still didnt work) seemed to do the job for me. I now have to make sure to use IFC 4 for my next trials and continue from there.

Thanks again:)
