### ISSUE TITLE
Errors using new Facet select in drawings

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3627]
Used `IfcElement, /Pset_.*Common/.Status=DEMOLISH` in [this](https://gitlab.com/openingdesign/milwaukee_st_4429/-/tree/55be41d4c13a1c9a5a3fbfa8e7422cb3d680a3ad/Models/BlenderBIM) file.

<details>
  <summary>Got this error. Click</summary>

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1460, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1469, in execute
    core.activate_drawing_view(tool.Ifc, tool.Drawing, drawing=drawing)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\drawing.py", line 429, in activate_drawing_view
    drawing_tool.activate_drawing(camera)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 1647, in activate_drawing
    current_representation = tool.Geometry.get_active_representation(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 289, in get_active_representation
    if obj.data and hasattr(obj.data, "BIMMeshProperties") and obj.data.BIMMeshProperties.ifc_definition_id:
AttributeError: 'NoneType' object has no attribute 'data'

```

</details>

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/afe82671-6a5f-4ab4-8c56-9fa5542d5eb1

---

Use 'IfcWall' in exclude and everything disappeared. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b20383db-b441-48b2-bdb4-3308cd108389

**Comment by theoryshaw** [comment]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/76e0bd71-8227-4710-9f22-87ced4f8e5eb)

That still makes everything disappear in the drawing, on my end. 




https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/27419623-f8ff-42aa-b506-b91067f7eb48

**Comment by theoryshaw** [comment]
fixed!
