### ISSUE TITLE
Can't tab into mesh

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3636]
Can't tab into mesh
ping @Gorgious56, as it might be related to recent commit. 

file, if you need it: https://gitlab.com/openingdesign/milwaukee_st_4429/-/tree/main/Models/BlenderBIM?ref_type=heads

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/e36a1d33-4c8b-4fd3-be13-d0a9ac4c257c

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1442, in invoke
    return IfcStore.execute_ifc_operator(self, context, is_invoke=True)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 332, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1447, in _invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1336, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 334, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1375, in _execute
    elif "IfcCircleProfileDef" in tool.Geometry.get_ifc_representation_class(element, representation):
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by Gorgious56** [comment]
Woopsie ! Sorry, should be fixed. Thank you for reporting ! Cheers
