### ISSUE TITLE
Can't enable BB, since 839e35f

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3640]
Ever since [this](https://github.com/IfcOpenShell/IfcOpenShell/commit/66f5081ada29e557fd2ade3a7a103ac19a5c8cc4) commit, I can't seem to enable BlenderBIM.
ping @myoualid

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\__init__.py", line 41, in <module>
    import blenderbim.bim
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\handler.py", line 24, in <module>
    import blenderbim.tool as tool
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\__init__.py", line 46, in <module>
    from blenderbim.tool.resource import Resource
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\resource.py", line 35, in <module>
    import ifcopenshell.util.constraint
ModuleNotFoundError: No module named 'ifcopenshell.util.constraint'
```

**Comment by Moult** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/constraint.py do you have this file?

**Comment by theoryshaw** [comment]
I do. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/3aad003f-e12c-42de-a11e-0a83b7fae0c8

**Comment by Andrej730** [comment]
@theoryshaw Can you try to checkout commit 839e35f1da91433838201c1737b549bb5f7aca81 (it's the one before 66f5081ada29e557fd2ade3a7a103ac19a5c8cc4) and run this in python console. I'm curious if it's somehow is using ifcopenshell from elsewhere.

```python
import ifcopenshell
print(ifcopenshell.util.__file__)
# '\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\blenderbim\\libs\\site\\packages\\ifcopenshell\\util\\__init__.py'
import ifcopenshell.util.constraint
```

**Comment by Moult** [comment]
Yep just confirmed in chat that he has a different IOS path conflicting.

**Comment by theoryshaw** [comment]
I'm an idiot: https://matrix.to/#/!ssOmSJysZpXBupsgjO:matrix.org/$o1ECcJu3fhUXoMDYdbzO-myEpN7nfPOMF_MiVAZ_V_0?via=libera.chat&via=matrix.org&via=crossbach.de
