### ISSUE TITLE
BlenderBim 230826 - print sheets button gives error

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3647]
Using this version:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/5047a2de-23d2-442a-bf31-857c42f4a076)

When attempting to print a newly created sheet of any ifc file it gives this error:

Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 84, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 338, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1303, in _execute
    subprocess.run(command)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Moult** [comment]
Does `inkscape` exist in your path? For example if you open a command prompt, can you type in `inkscape` and it will launch inkscape?

**Comment by Plae-Blue-Dot** [comment]
Yip I made sure before hand:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/0af1b590-56c4-4d8c-a616-dcacf28d3e79)
Inkscape launches alright

**Comment by aothms** [comment]
Windows path resolution is a funky beast. Win32 API CreateProcess will look up the directory containing the executable, but it will not add `.exe` for you as opposed to the command prompt.

https://github.com/IfcOpenShell/IfcOpenShell/blob/38a9e291026abb31d571b5af603f68592a365a9a/src/blenderbim/blenderbim/bim/module/drawing/operator.py#L1302-L1304

First of all  I'd recommend `ast.literal_eval()` instead of `eval()` for safety.

Secondly you can do:

```python
for command map(list, commands):
    subprocess.run([shutil.which(command[0]) or command[0], *command[1:]])
```

as a cross-platform workaround. `shutil.which()` is smart enough to search including the executable extension.

For a quick fix @Plae-Blue-Dot you can also just `[['inkscape.exe', svg, '-o', pdf]]`

**Comment by Plae-Blue-Dot** [comment]
It worked! brilliant thankyou @aothms !
The quick fix is a life saver! This is going to save so much time

**Comment by Plae-Blue-Dot** [comment]
Thanks Moult so the new command would be:
[["inkscape.exe", "svg", "-o", "pdf"]]
