### ISSUE TITLE
Duplicate object issue when using IFC links

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#3651]
Scenario:
I have an IFC project with the demo library.
I link an IFC file with the same file structure but containing two objects in the "IfcBuildingStorey/My Storey".
I hide and unhide things. I may or may not click on collections.
I activate the Wall Tool.
I add a Wall, called wall1
I duplicate wall1, now called wall2 and play with it and join it to wall1. 
I duplicate wall2:
--> Error

```
Python: Traceback (most recent call last):
  File "...\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 657, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "...\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 338, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "...\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 703, in _execute
    new = blenderbim.core.root.copy_class(tool.Ifc, tool.Collector, tool.Geometry, tool.Root, obj=new_obj)
  File "...\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\root.py", line 44, in copy_class
    collector.assign(obj)
  File "...\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\collector.py", line 100, in assign
    object_collection.objects.link(obj)
RuntimeError: Error: Could not (un)link the object 'IfcWall/Wall.006' because the collection 'IfcBuildingStorey/My Storey' is linked
```

**Comment by theoryshaw** [comment]
i think ive experieced this as well.

**Comment by myoualid** [comment]
I've managed to replicate this error with the following steps : 

I have an IFC project with the demo library.
I link an IFC file ( which has the same file structure and therefore step ids?).
I save the .ifc and .blend.
I close the file.
I open the file.
I add a drawing view for my storey.
I activate the wall tool.
I add a wall : 
I get the following erroer :
```
Error: Python: Traceback (most recent call last):
  File "...\3.6\scripts\addons\blenderbim\bim\module\model\workspace.py", line 537, in invoke
    return self.execute(context)
  File "...\3.6\scripts\addons\blenderbim\tool\ifc.py", line 193, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "...\3.6\scripts\addons\blenderbim\bim\ifc.py", line 338, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "...\3.6\scripts\addons\blenderbim\bim\module\model\workspace.py", line 529, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "...\3.6\scripts\addons\blenderbim\bim\module\model\workspace.py", line 549, in hotkey_S_A
    bpy.ops.bim.add_constr_type_instance()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "...\3.6\scripts\addons\blenderbim\bim\module\model\product.py", line 123, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "...\3.6\scripts\addons\blenderbim\bim\ifc.py", line 338, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "...\3.6\scripts\addons\blenderbim\bim\module\model\product.py", line 148, in _execute
    if self.generate_layered_element(ifc_class, relating_type):
  File "...\3.6\scripts\addons\blenderbim\bim\module\model\product.py", line 276, in generate_layered_element
    obj = wall.DumbWallGenerator(relating_type).generate()
  File "...\3.6\scripts\addons\blenderbim\bim\module\model\wall.py", line 458, in generate
    return self.derive_from_cursor()
  File "...\3.6\scripts\addons\blenderbim\bim\module\model\wall.py", line 581, in derive_from_cursor
    return self.create_wall()
  File "...\3.6\scripts\addons\blenderbim\bim\module\model\wall.py", line 597, in create_wall
    element = blenderbim.core.root.assign_class(
  File "...\3.6\scripts\addons\blenderbim\core\root.py", line 74, in assign_class
    collector.sync(obj)
  File "...\3.6\scripts\addons\blenderbim\tool\collector.py", line 76, in sync
    blenderbim.core.spatial.assign_container(
  File "...\3.6\scripts\addons\blenderbim\core\spatial.py", line 41, in assign_container
    collector.assign(element_obj)
  File "...\3.6\scripts\addons\blenderbim\tool\collector.py", line 100, in assign
    object_collection.objects.link(obj)
RuntimeError: Error: Could not (un)link the object 'IfcWall/Wall' because the collection 'IfcBuildingStorey/GROUND_FLOOR-' is linked
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113
```

**Comment by sboddy** [comment]
@myoualid Can you still reproduce this with latest Blender/Bonsai combo? I tried following your steps and couldn't get the error.

**Comment by Moult** [comment]
This should be fixed because we've now totally decoupled the hierarchy from collection system (one of the many subtle bugs that were addressed from that decision). We no longer have `object_collection` and we now use `link_collection_object_safe`.
