### ISSUE TITLE
Error when `Include GlobalId` is checked

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3654]
If that is not checked, the error goes away. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/3ab93738-14ef-4779-a3a5-cc994c8b3b40)

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\csv\operator.py", line 197, in execute
    ifc_csv.export(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 115, in export
    self.sort_results(sort, attributes, include_global_id)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 261, in sort_results
    if include_global_id and len(list(self.results[0])) > 1:
TypeError: 'dict_values' object is not subscriptable

```

**Comment by Moult** [comment]
Fixed here https://github.com/IfcOpenShell/IfcOpenShell/commit/c520e160312743aa49e0bac514d7c6726528251b#diff-8ffc2cac11aedb3df139f82258dcd9986b54a3db6b18181d8955d6e27b4e9bdb
