### ISSUE TITLE
Duplicating and playing with (connected?) walls

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#3659]
When I model walls, I often duplicate existing walls which have connections to other walls.

I sometimes rotate these duplicated walls, move them, and extend them to other walls. all sorts of things.
I'm unable to retrace my steps exactly, but, once in a while, after duplicating a wall and trying to do some operations on it:
I get this error:

``` 
Error: Python: Traceback (most recent call last):
  File "...\Blender\3.6\scripts\addons\blenderbim\bim\module\model\workspace.py", line 537, in invoke
    return self.execute(context)
  File "...\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 193, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "...\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 338, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "...\Blender\3.6\scripts\addons\blenderbim\bim\module\model\workspace.py", line 529, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "...\Blender\3.6\scripts\addons\blenderbim\bim\module\model\workspace.py", line 695, in hotkey_S_R
    bpy.ops.bim.rotate_90(axis="Z")
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "...\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 193, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "...\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 338, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "...\Blender\3.6\scripts\addons\blenderbim\bim\module\model\profile.py", line 912, in _execute
    DumbWallRecalculator().recalculate(layer2_objs)
  File "...\Blender\3.6\scripts\addons\blenderbim\bim\module\model\wall.py", line 431, in recalculate
    joiner.recreate_wall(element, wall)
  File "...\Blender\3.6\scripts\addons\blenderbim\bim\module\model\wall.py", line 1110, in recreate_wall
    extrusion_data = self.get_extrusion_data(tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id))
  File "...\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 388, in by_id
    return self[id]
  File "...\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 376, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "...\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4531, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #6,274 not found
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113
```

**Comment by Gorgious56** [comment]
This may be related to https://github.com/IfcOpenShell/IfcOpenShell/issues/3313

Hard-to-replicate bug wher wall entities are invalidated. I've never contemplated that it could come from invalid connections to other walls though, you might be on to something ?

**Comment by Moult** [comment]
@myoualid can you turn on screencast keys, start recording your screen. Go crazy, then see if you can recreate it?

**Comment by myoualid** [comment]
I did.. went crazy for 1h30 and nothing :D

**Comment by Gorgious56** [comment]
I finally was able to replicate it !! I think it's related to the OP

Please see

![Animation3](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/620b2d52-c497-4596-bc9a-1c0559c5116c)

How to replicate :

- Brand new file
- Create wall type
- Instance wall
- Duplicate wall, rotate it
- Mitre both walls
- Duplicate on wall, move it
- Mite two of the walls
- CTRL - Z to undo
- Mitre (or butt) two of the walls
- Error

**Comment by Gorgious56** [comment]
Oh man, I was able to replicate it twice but now I can't anymore. This bug is really irritating. Anyways I am 99% sure it comes from the undo system.

**Comment by Gorgious56** [comment]
Also, is this a bug or is this supposed to happen ? How can we connect two continuous walls with a very limited Z angle difference ? Extend, mitre and butt produce somewhat mangled or imprecise geometry.

![Animation3](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/4f2657f7-e48b-4bbf-bbe1-56e6232a4007)

**Comment by Andrej730** [comment]
> I finally was able to replicate it !! I think it's related to the OP

Couldn't reproduce it but found some other issue along the way - 6887210a1. 
Not sure if it's related but I've noticed that on object duplicate BBIM was producing some orphaned mesh with `.BIMMeshProperties.ifc_definition_id` pointing to the original duplicated object (which could be gone at some point).

Btw found it kind of useful for debugging undo issues to use some snippet like this in `undo_post()` in https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/handler.py

```python
    # undo debugger
    for mesh in bpy.data.meshes:
        ifc_id = mesh.BIMMeshProperties.ifc_definition_id
        if not mesh.BIMMeshProperties.ifc_definition_id:
            continue
        try:
            element = tool.Ifc.get().by_id(ifc_id)
        except Exception as e:
            tool.Blender.show_info_message("Undo error!")
            print(mesh, e)
```

**Comment by ChubbyQuark** [comment]
I followed the above steps but I can't re-produce it. This bug certainly seems less common with latest builds. I haven't managed to re-produce it on a clean file. I'll try the original file which I was having issues and see if I can re-produce it.

**Comment by Andrej730** [comment]
>Also, is this a bug or is this supposed to happen ? How can we connect two continuous walls with a very limited Z angle difference ? Extend, mitre and butt produce somewhat mangled or imprecise geometry.

It was indeed a bug, fixed after ffbb91216

**Comment by myoualid** [comment]
I found a new one !
If you use vertical layered coverings, or walls: 

When selecting a vertical covering ( or wall) and extending to a slab above with Shift+E; then if you try to Flip the covering or the wall with Shift+F.  You get an error .
See below video https://youtu.be/G9WiLqK4yqQ?t=490

**Comment by Moult** [comment]
This is now fixed with the new extend / flip implementation.
