### ISSUE TITLE
BlenderBim - error when activating drawing from before window fix update

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3681]
I've been working on this one ifc file for a few months, I stopped using newer Blenderbim versions because of the window's not printing bug since it has been fixed I attempted to update and I get this error:

Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1462, in invoke
    return self.execute(context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1471, in execute
    core.activate_drawing_view(tool.Ifc, tool.Drawing, drawing=drawing)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\drawing.py", line 429, in activate_drawing_view
    drawing_tool.activate_drawing(camera)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 1620, in activate_drawing
    filtered_elements = cls.get_drawing_elements(drawing) | cls.get_drawing_spaces(drawing)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 1519, in get_drawing_elements
    elements -= ifcopenshell.util.selector.filter_elements(ifc_file, exclude)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 248, in filter_elements
    transformer.transform(filter_elements_grammar.parse(query))
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 194, in parse
    return self._parse(text, start)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parsers\earley.py", line 292, in parse
    to_scan = self._parse(stream, columns, to_scan, start_symbol)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 138, in _parse
    to_scan = scan(i, to_scan)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 115, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan))
lark.exceptions.UnexpectedCharacters: No terminal defined for '.' at line 1 col 1

.IfcGeographicElement[Name="Terrain"]
^

Expecting: {'CLASSIFICATION', 'SLASH', '__ANON_1', '__ANON_3', 'BANG', 'ESCAPED_STRING', 'MATERIAL', 'LOCATION', '__ANON_2', '__ANON_4', 'TYPE', '__ANON_0'}

This error is from BlenderBim 230831

The last tested version it was working on was BlenderBim 230706

**Comment by Plae-Blue-Dot** [comment]
That was exactly the issue, I completely forgot about the syntax selector change it's much easier now! Thanks @Moult this is resolved just user error here
