### ISSUE TITLE
Error during drawing creation: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3688]
When i try to print `FLOOR PLAN - 1ST` in the following file, i get the following error. 
https://gitlab.com/openingdesign/milwaukee_st_4429/-/tree/e849b314a9c3d47d2634981736c98279d3478738/Models/BlenderBIM

As you can see the intelligent tags, are no longer picking up the product's values. 

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 203, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 258, in execute
    annotation_svg = self.generate_annotation(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1092, in generate_annotation
    self.svg_writer.create_blank_svg(svg_path).draw_annotations(annotations, precision, decimal_places).save()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 211, in draw_annotations
    self.draw_text_annotation(obj, obj.location)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 851, in draw_text_annotation
    text = tool.Drawing.replace_text_literal_variables(text_literal.Literal, product)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 1393, in replace_text_literal_variables
    text = text.replace(original_command, str(eval(command[2:-2])))
  File "<string>", line 1, in <module>
TypeError: 'NoneType' object is not subscriptable

```

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/6b0a9f13-f844-4947-93ec-e1b8f4838628)

**Comment by theoryshaw** [comment]
This problem was introduced on.. 
Revision: 9a7a284561a2af554f689f1eab58092b07fe3e62

**Comment by theoryshaw** [comment]
Also when creating a drawing, i get the following error. 

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 203, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 258, in execute
    annotation_svg = self.generate_annotation(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1092, in generate_annotation
    self.svg_writer.create_blank_svg(svg_path).draw_annotations(annotations, precision, decimal_places).save()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 189, in draw_annotations
    self.draw_leader_annotation(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 635, in draw_leader_annotation
    self.draw_text_annotation(obj, position)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 854, in draw_text_annotation
    text = tool.Drawing.replace_text_literal_variables(text_literal.Literal, product or element)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 1396, in replace_text_literal_variables
    text = text.replace(original_command, ifcopenshell.util.selector.format(command[2:-2]))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 241, in format
    return FormatTransformer().transform(format_grammar.parse(query))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 194, in parse
    return self._parse(text, start)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parsers\earley.py", line 292, in parse
    to_scan = self._parse(stream, columns, to_scan, start_symbol)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 138, in _parse
    to_scan = scan(i, to_scan)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 115, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan))
lark.exceptions.UnexpectedCharacters: No terminal defined for '[' at line 1 col 7

"None"[0]
      ^

```

**Comment by theoryshaw** [comment]
I think it has something to do with annotation types having things like the following in them. 
```
{{r"Pset_.*Common"."Status"}}[0][:2]
```
```
``round({{Qto_SpaceBaseQuantities.NetFloorArea}} or 0.)`` SF
```

**Comment by Moult** [comment]
Yep the syntax has changed. What happens if you change it to /Pset_.*Common/.Status?

Also there is a new substr command like ``substr({{/Pset_.*Common/.Status}}, 0, 2)``

And the "or 0." Should no longer be required with the new round function (same functions as in IfcCSV)

**Comment by theoryshaw** [comment]
Thanks!.
`{{/Pset_.*Common/.Status}}` works, but

`substr({{/Pset_.*Common/.Status}}, 0, 2)` does not. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/af1e9566-5e6d-407c-8f8a-2d41aeda9054)

**Comment by Moult** [comment]
Ah github changed the formatting you need the double backticks \`\`substr(...)\`\`

Alsp BTW the substr command was just added today.

**Comment by theoryshaw** [comment]
Thanks!

**Comment by Moult** [comment]
Ah that's because it's a list, I guess you could do:

```
``substr({{/Pset_.*Common/.Status.0}}, 0, 2)``
```
