### ISSUE TITLE
No existing types (door/window/column/etc) 

### ISSUE THREAD

**Issue by archiheart** [IfcOpenShell/IfcOpenShell#3696]
I just installed the addon however upon trying to create anything I get an error ( image bellow). No matter what I'm trying to create I get an error of the kind. What could be the issue? This is an IFC file open, seem to be working if i create a new ifc file but 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/7851156/ff51823f-adb4-4b64-98be-ce3de0219f69)

**Comment by Andrej730** [comment]
@archiheart Can you please describe more specifically steps to reproduce this error?
From the traceback it looks like you were trying to extend a wall with shift+e hotkey or something.

**Comment by archiheart** [comment]
> @archiheart Can you please describe more specifically steps to reproduce this error? From the traceback it looks like you were trying to extend a wall with shift+e hotkey or something.

well, actually in case of opening an ifc file, no matter what i do, whether it is trying to create a wall or extent the existing I get the same kind of error.

**Comment by Andrej730** [comment]
@archiheart is it some specific ifc file or it's the same error if you create new project with demo library you get the same error?

**Comment by archiheart** [comment]
> @archiheart is it some specific ifc file or it's the same error if you create new project with demo library you get the same error?

Atm in terms of opening ifc files I only tried 1, dont currently have others to try. When I just create a new ifc blender file seems to work fine*. 
*Aside from windows and doors not properly inserting onto the wall, but this one might be an issue of use maybe, I'm looking into tutorials to check.

**Comment by Andrej730** [comment]
>Atm in terms of opening ifc files I only tried 1, dont currently have others to try. When I just create a new ifc blender file seems to work fine*.

Can you share example .ifc file with the issue?

> Aside from windows and doors not properly inserting onto the wall, but this one might be an issue of use maybe, I'm looking into tutorials to check.

It's common problem - need to make sure wall is selected before you add window/door, that way it will create an opening.

**Comment by Gorgious56** [comment]
Hello, would you kindly tell us what version of the BlenderBIM addon you're running ? What Operating System ? How you installed the addon ?

**Comment by archiheart** [comment]
> @archiheart is it some specific ifc file or it's the same error if you create new project with demo library you get the same error?

Atm in terms of opening ifc files I only tried 1, dont currently have others to try. When I just create a new ifc blender file seems to work fine*. 
*Aside from windows and doors not properly inserting onto the wall, but this one might be an issue of use maybe, I'm looking into tutorials to check.

**Comment by archiheart** [comment]
@Andrej730 here is the file [bedroom redesign.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12539195/bedroom.redesign.zip)
although i believe having selected the wall prior to adding the window, maybe i didnt, but i did find a way to make the opening by selecting the wall and and the element and  then the shortcut is shift+o i believe ( not sure anymore, sorry) .
@Gorgious56 I just installed it, so it would be the latest version I got through the website. Im on windows. I installed it as you usually install an add-on, not aware of other way (properties/add-on/install ( the zip file)

**Comment by theoryshaw** [comment]
There might be other problems too, but one was that the IFC didn't have a 'Geometric Representation Context'.

video: https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/bf730561-47d3-465a-b4e8-ca73ad3ebfb2

Also, If you're continuing to model in BB, i would upgrade this file from IFC2x3 to IFC4.  As it's more stable, modeling wise.

**Comment by theoryshaw** [comment]
Also, just a little tip, if you plan on creating drawings with BB, high poly objects like these will cause the drawings to take forever to be created.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/a41b69a1-db32-4516-905f-0783330c905c)

**Comment by theoryshaw** [comment]
Curious, how did you export this model out of Rhino? Plugin?  Native rhino?

**Comment by Andrej730** [comment]
Noticed some an error adding a wall / slab - this .ifc has only MODEL context and no subcontexts. To create a wall / slab you'll need to add Model/Body/MODEL_VIEW subcontext:


https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/308f13bc-2669-4323-b784-9fd9e77d7015

<details>
<summary>Error was</summary>

```
RuntimeError: Error: Python: Traceback (most recent call last):
  File "\blenderbim\bim\module\model\product.py", line 123, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "\blenderbim\bim\ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "\blenderbim\bim\module\model\product.py", line 148, in _execute
    if self.generate_layered_element(ifc_class, relating_type):
  File "\blenderbim\bim\module\model\product.py", line 276, in generate_layered_element
    obj = wall.DumbWallGenerator(relating_type).generate()
  File "\blenderbim\bim\module\model\wall.py", line 458, in generate
    return self.derive_from_cursor()
  File "\blenderbim\bim\module\model\wall.py", line 581, in derive_from_cursor
    return self.create_wall()
  File "\blenderbim\bim\module\model\wall.py", line 618, in create_wall
    representation = ifcopenshell.api.run(
  File "\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_wall_representation.py", line 46, in execute
    self.settings["context"].ContextIdentifier,
AttributeError: 'NoneType' object has no attribute 'ContextIdentifier'
```

</details>

Also found some error with creating slabs in ifc2x3 and fixed it in d4e471785.

But anyway this file has many IFC issues, you can check them by running validate in the debug panel and checking system console (Window - Toggle System Console in Blender)., so working on this file might have many other issues.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/6fee7609-0697-4036-9219-b1b31fefc4d4)

**Comment by archiheart** [comment]
> Curious, how did you export this model out of Rhino? Plugin? Native rhino?

I used VisualARQ. A plugin on Rhino.

**Comment by sboddy** [comment]
@archiheart Are you still using Bonsai (nee BlenderBIM)? I tried opening this file in latest Bonsai, and it opens without error. Perhaps this old issue can be closed?

**Comment by sboddy** [comment]
@archiheart No response after 3 months means I'm going to close this issue as "stale". You can reopen if still needed.
