### ISSUE TITLE
"BIM DOCUMENTATION" tab is missing

### ISSUE THREAD

**Issue by JuanJ67m** [IfcOpenShell/IfcOpenShell#3711]
Today I installed Blender BIm and Blender 3.6, "BIM DOCUMENTATION" tab is missing.

**Comment by JuanJ67m** [comment]
today I received this message when tried print:

```

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 203, in invoke
    return self.execute(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 254, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 368, in generate_linework
    svg_path = self.get_svg_path(cache_type="linework")
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1124, in get_svg_path
    drawing_path = tool.Drawing.get_document_uri(self.camera_document)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 396, in get_document_uri
    if document.is_a("IfcDocumentInformation"):
AttributeError: 'NoneType' object has no attribute 'is_a'
```


model used was found here: 
`https://community.osarch.org/discussion/1254/blenderbim-beginner-tutorial-step-by-step-project-part-1-modelling#latest`

**Comment by theoryshaw** [comment]
If you're somewhat new to BlenderBIM, i would suggest posting your questions and/or problems to the https://community.osarch.org/categories/general community instead.

**Comment by Moult** [comment]
A note that that model used is for an older version and is incompatible, hence the error.
