### ISSUE TITLE
Print to SVG drop error

### ISSUE THREAD

**Issue by JuanJ67m** [IfcOpenShell/IfcOpenShell#3714]
today I received this message when tried print:

```

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 203, in invoke
    return self.execute(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 254, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 368, in generate_linework
    svg_path = self.get_svg_path(cache_type="linework")
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1124, in get_svg_path
    drawing_path = tool.Drawing.get_document_uri(self.camera_document)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 396, in get_document_uri
    if document.is_a("IfcDocumentInformation"):
AttributeError: 'NoneType' object has no attribute 'is_a'
```

model used was found here:
`https://community.osarch.org/discussion/1254/blenderbim-beginner-tutorial-step-by-step-project-part-1-modelling#latest`

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/4990279/4c14f65b-5a38-4ee4-90b4-7f18499cf52a)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/4990279/f79aea58-b04d-4285-aca4-f59c2a28a3d2)

**Comment by theoryshaw** [comment]
A lot has changed since @Pale-Blue-Dot made this file a couple months ago.  The file would need to be tweaked work again under the latest development. 

@Pale-Blue-Dot, would be cool to put these files in a git, so changes like these could be made, and these example files could have a longer life.

**Comment by JuanJ67m** [comment]
> A lot has changed since @Pale-Blue-Dot made this file a couple months ago. The file would need to be tweaked to work again under the latest development.
> 
> @Pale-Blue-Dot, would be cool to put these files in a git, so changes like these could be made, and these example files could have a longer life.

I tried create a new file with a wall to test print to SVG, but there still exist same error:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/4990279/6abfed8c-c37a-4c48-9a53-95530dd52e40)
