### ISSUE TITLE
BlenderBim - Error when printing section & sheet

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3752]
In a particular file I get this error with a specific section:

Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 203, in invoke
    return self.execute(context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 254, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 532, in generate_linework
    self.serialiser.finalize()
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1529, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
RuntimeError: An unknown error occurred

All the other drawing views print without issue, this one, even If I make a new section of the same portion gives the same error, I can only assume something, not visible in any other drawing, that it is cutting or projecting is causing the error,

And the sheet is giving this error:

Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 75, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1276, in _execute
    references = sheet_builder.build(sheet)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\sheeter.py", line 264, in build
    self.build_drawings(root, sheet)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\sheeter.py", line 348, in build_drawings
    reference = tool.Ifc.get().by_id(int(view.attrib["data-id"]))
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 388, in by_id
    return self[id]
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 376, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4571, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #90,290 not found

Which it did not give until I removed the section that gave an error

It is a private file so unfortunately I cant share it here

**Comment by theoryshaw** [comment]
if you search 90290 in the ifc file, what is the entity? a boolean?

i think ive had this problem before too... try removing all booleans and miters etc, and running the drawing again.

**Comment by Moult** [comment]
Is it possible to share your file privately to dion@thinkmoult.com ?

**Comment by Plae-Blue-Dot** [comment]
HI @theoryshaw thanks for the suggestion, I can't seem to find it with the search as it doesn't seem to give a result regardless of the search criteria, The file itself is fairly large to remove every boolean, I managed to sort it by loading an older version of the file.

And thanks @Moult I've shared it

**Comment by Moult** [comment]
I suspect this issue might be caused by adding / removing drawings from a sheet whilst also having that sheet open in Inkscape, and then saving over in Inkscape (which causes an outdated reference to an drawing ID which no longer exists). In this case the drawing reference is section GG. This is not something we can control, so I've added some code to accommodate it.

**Comment by Moult** [comment]
By the way your drawings are beautiful! :) Definitely starting to match the quality of proprietary software!

**Comment by Plae-Blue-Dot** [comment]
Thankyou, they are still a way from the quality I want but that's a skill issue not a software problem hahaha

**Comment by Plae-Blue-Dot** [comment]
> I suspect this issue might be caused by adding / removing drawings from a sheet whilst also having that sheet open in Inkscape, and then saving over in Inkscape (which causes an outdated reference to an drawing ID which no longer exists). In this case the drawing reference is section GG. This is not something we can control, so I've added some code to accommodate it.

This makes sense, I abuse the connection alot and just keep inkscape open while I print, adjust and reprint sheets and drawings, thanks for the accommodation!
