### ISSUE TITLE
On drawing activation: AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3836]
If you open `Highland_Haven.blend` file first (w/ `Highland_Haven.ifc`), and then try to activate `SITE PLAN_testy` drawing, it gives the following error.

file(s) here: https://gitlab.com/openingdesign/highland_haven/-/tree/b933b6bbd3bd0b6b81b20c1cf655cd4997054114/Models_and_CAD/BlenderBIM

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1485, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1494, in execute
    core.activate_drawing_view(tool.Ifc, tool.Drawing, drawing=drawing)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\drawing.py", line 429, in activate_drawing_view
    drawing_tool.activate_drawing(camera)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 1648, in activate_drawing
    current_representation = tool.Geometry.get_active_representation(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 297, in get_active_representation
    if obj.data and hasattr(obj.data, "BIMMeshProperties") and obj.data.BIMMeshProperties.ifc_definition_id:
AttributeError: 'NoneType' object has no attribute 'data'

```

**Comment by Andrej730** [comment]
Error is due `#2035066=IfcVirtualElement('1xcFz6un55ExZBwFrEIVCf',$,'VirtualElement.015',$,'ReferenceLine',#2062423,#2035081,$)` missing blender object. Starting IFC file fresh/ resync should help. 
Any ideas how it's got deleted without removing the IFC element?

**Comment by Andrej730** [comment]
Closing as can't reproduce this.
