### ISSUE TITLE
can not create drawing in blenderbim

### ISSUE THREAD

**Issue by faberns** [IfcOpenShell/IfcOpenShell#3849]
hi,
im trying to create horizontal sections with blenderbim. i loaded an ifc file via load project. but as soon as i click on create drawing, the program loads a while and then shows me this error:

Python: Traceback (most recent call last):
File "C:\Users\ernst\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 202, in invoke
return self.execute(context)
File "C:\Users\ernst\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 253, in execute
linework_svg = self.generate_linework(context)
File "C:\Users\ernst\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 531, in generate_linework
self.serialiser.finalize()
File "C:\Users\ernst\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1529, in finalize
return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
RuntimeError: An unknown error occurred

(Could anyone give me some advice, how to solve this problem? i think it's a problem of the ifc-file itself. The file is originally created with vectorworks as far as i know) If im moving the section cube to the area where the facade is just straight without any curves it works, but as soon as it should show some of the rounded body this error occurs. The files were transformed to ifc4 when loaded with blenderbim.
Blender version 3.6.4 windows
Blenderbim 231003-py310

thanks for any help.
![2023-10-04 09_02_](https://github.com/IfcOpenShell/IfcOpenShell/assets/147024686/bbdfd64f-32e0-4516-b71a-0c6e08d4dfd8)

only the facade of the project
[Fassade-IFC4.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12812601/Fassade-IFC4.zip)
the whole building
[FA_L3_-IFC4.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12812610/FA_L3_-IFC4.zip)
[blender_debug_output.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12812634/blender_debug_output.txt)

**Comment by Andrej730** [comment]
I've narrowed it down to 2 elements that lead to the error, @aothms could you please take a look?

Reduced IFC file and script to reproduce the issue:


[unknown_error_serialisation.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12816540/unknown_error_serialisation.ifc.txt)

```python
import ifcopenshell
import ifcopenshell.geom
import multiprocessing

ifc = ifcopenshell.open("unknown_error_serialisation.ifc")

svg_settings = ifcopenshell.geom.settings(
    DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True, INCLUDE_CURVES=True
)
svg_buffer = ifcopenshell.geom.serializers.buffer()
serialiser = ifcopenshell.geom.serializers.svg(svg_buffer, svg_settings)
serialiser.setFile(ifc)
serialiser.setWithoutStoreys(True)
serialiser.setPolygonal(True)
serialiser.setUseHlrPoly(True)
# Objects with more than these edges are rendered as wireframe instead of HLR for optimisation
serialiser.setProfileThreshold(10000)
serialiser.setUseNamespace(True)
serialiser.setAlwaysProject(True)
serialiser.setAutoElevation(False)
serialiser.setAutoSection(False)
serialiser.setPrintSpaceNames(False)
serialiser.setPrintSpaceAreas(False)
serialiser.setDrawDoorArcs(False)
serialiser.setNoCSS(True)
serialiser.setElevationRefGuid('3r6d$csMj9DPvJBIe4IO_l')
serialiser.setScale(0.01)
serialiser.setSubtractionSettings(ifcopenshell.ifcopenshell_wrapper.ALWAYS)
serialiser.setUsePrefiltering(True)
serialiser.setUnifyInputs(True)
serialiser.setSegmentProjection(True)

geom_settings = ifcopenshell.geom.settings(
    DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True, INCLUDE_CURVES=True
)
geom_settings.set_context_ids([44, 45])
it = ifcopenshell.geom.iterator(
    geom_settings, 
    ifc, 
    multiprocessing.cpu_count(), 
    include={ifc.by_id(i) for i in [159856, 159573]}
)

def yield_from_iterator(it):
    if it.initialize():
        while True:
            yield it.get()
            if not it.next():
                break

for elem in yield_from_iterator(it):
    serialiser.write(elem)
serialiser.finalize()
```
