### ISSUE TITLE
error after `bpy.ops.bim.add_drawing()`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3862]
error after `bpy.ops.bim.add_drawing()`

ping, @Andrej730 
is probably related to: https://github.com/IfcOpenShell/IfcOpenShell/commit/33536957d8bb752587d4d6ea49772c0442e199c4

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 74, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 135, in _execute
    core.add_drawing(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\drawing.py", line 194, in add_drawing
    element = drawing.run_root_assign_class(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 861, in run_root_assign_class
    return blenderbim.core.root.assign_class(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\root.py", line 70, in assign_class
    root.run_geometry_add_representation(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\root.py", line 204, in run_geometry_add_representation
    return blenderbim.core.geometry.add_representation(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\geometry.py", line 73, in add_representation
    geometry.change_object_data(obj, data, is_global=True)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 40, in change_object_data
    cls.replace_object_data_globally(obj.data, data)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 46, in replace_object_data_globally
    if old_data.is_editmode:
AttributeError: 'Camera' object has no attribute 'is_editmode'

```

**Comment by Andrej730** [comment]
Thanks for the ping! 😄
