### ISSUE TITLE
Better visualisation and quick selection of element decomposition (aggregates, nests, covers, void fills)

### ISSUE THREAD

**Issue by danielkrajnik** [IfcOpenShell/IfcOpenShell#3887]
BlenderBIM could set a callback to select all elements in a collection when any of its constituent elements gets selected. 

This could ensure that elements in a collection don't get accidentally separated and may seem more familiar to workflows in other CAD/BIM software.

User should be allowed to choose, which collection gets this behavior. Otherwise a project with a lot of nested collections may become unmanageable. My initial idea to implement this is to add a prefix `.block` to the name?

Color of the selection would change to indicate it.

A separate operator would be needed to turn this callback off when the user wants to access individual elements in such a "collection block".

Personally I'm not sure how 3d artists manage their assemblies in larger scenes without such mechanism. The same behavior appears in maya, although not in [3dsmax](https://www.youtube.com/watch?v=OAAH5MFHY8E). I assume that as the assemblies grow more complex they create dummy handles to communicate the child-parent relationships, but this approach wouldn't work inside of buildings with many overlapping elements and limited visibility.

**Comment by brunoperdigao** [comment]
I was planning to achieve a similar goal for duplicate aggregates by using IfcGroup. In my case, I'm trying to use a prefix in the IfcGroup name, instead of relying on blender collections. I'll update here when I have something to show.

**Comment by danielkrajnik** [comment]
Thank you, I don't want to duplicate the work, so I'll take a look at the "duplicate aggregates".

**Comment by brunoperdigao** [comment]
I'm playing with the idea of creating a decorator for aggregates. It creates a bounding box around all the objects in the aggregate when you select one of them. It doesn't prevent you from moving or editing, but it warns the user that the object belongs to an aggregate.
Also added the idea of selecting everything by double-clicking one of the elements.
Thoughts?

![GIF 22-10-2023 00-17-06](https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/d5547ab2-7c95-4cf7-ab42-e409a312309f)

**Comment by danielkrajnik** [comment]
Wow, that looks cool! "selecting everything by double-clicking" sounds useful although I'd still prefer to turn it around and select everything by default (if it has been tagged) and double click to move a component. The main concern for me was that the user would accidentally move a component of the assembly.

Sorry, I've been stuck due to a few technical desktop issues (unrelated).

**Comment by theoryshaw** [comment]
cool!

> I'd still prefer to turn it around and select everything by default (if it's a "tagged" aggregate) and double click to move a part (or a "sub-aggregate")

would agree.  Maybe, could it be a 'tab' to get into the aggregate? ... similar to other Blender UI approaches.

**Comment by theoryshaw** [comment]
I do like the double click though... i wish that did the same thing as 'tab', for other stuff in BB, as well.

**Comment by danielkrajnik** [comment]
iirc 'Tab' is also used in revit to select subcomponents? Would make it more familiar to those users then.

**Comment by brunoperdigao** [comment]
I generally agree with the idea that we should keep things similar to how they work in vanilla Blender. That's why I would keep "one-click=one object". But maybe this could be customizable in the addon preferences. I think it's possible, would have to investigate.
How would 'tab' work when you have to go into and aggregate and then 'tab' again to edit it?

**Comment by danielkrajnik** [comment]
> But maybe this could be customizable in the addon preferences.

Yes, making it "opt-in" sounds like a good idea - in the same way "Base Snap" and "Navigate while Transforms" options were added.

**Comment by Moult** [comment]
Alt-D currently selects the decomposition. How about if there is no decomposition it selects siblings instead?

**Comment by Moult** [comment]
@brunoperdigao hey revisiting https://github.com/IfcOpenShell/IfcOpenShell/issues/3887#issuecomment-1773981035 how on earth did you acheive this amazing work of art?

Ping @Andrej730

**Comment by brunoperdigao** [comment]
@Moult I had forgotten about this. Unfortunately, I haven't worked on it since then, but here is the code: https://github.com/brunoperdigao/IfcOpenShell/tree/aggregate-selection

**Comment by Moult** [comment]
Oh it's a decorator! So sneakily blended into the same colourscheme as the selection colour. Niiice.

**Comment by brunoperdigao** [comment]
Hi @theoryshaw, could you point me to one of your projects that have a lot of aggregates? I'm trying out a few things and would like to test it in multiple scenarios.
Now I'm revisiting the idea that it should create a bounding box over the whole aggregate. However, in the example below, the third wall (from left to right) does not belong to the aggregate, so using only the bounding box might be misleading. That's why I created a way to highlight the objects that belong to the aggregate.
![Image](https://github.com/user-attachments/assets/0388e006-b478-4fd1-97ea-d8914d33f226)

**Comment by brunoperdigao** [comment]
@Moult I'm thinking that for decomposition elements we could have the same behavior we have for arrays. The parts would be locked and have a constraint to the aggregate. But in this case we could have an option to turn that lock on and off. What do you think?

**Comment by theoryshaw** [comment]
> Hi @theoryshaw, could you point me to one of your projects that have a lot of aggregates? I'm trying out a few things and would like to test it in multiple scenarios. Now I'm revisiting the idea that it should create a bounding box over the whole aggregate. However, in the example below, the third wall (from left to right) does not belong to the aggregate, so using only the bounding box might be misleading. That's why I created a way to highlight the objects that belong to the aggregate. ![Image](https://private-user-images.githubusercontent.com/57102715/367537060-0388e006-b478-4fd1-97ea-d8914d33f226.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMjU2MjQsIm5iZiI6MTcyNzEyNTMyNCwicGF0aCI6Ii81NzEwMjcxNS8zNjc1MzcwNjAtMDM4OGUwMDYtYjQ3OC00ZmQxLTk3ZWEtZDg5MTRkMzNmMjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDIxMDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmY2Y4ZjBkMjAyNGRjNmFkN2I4MWJmNTMxM2JlNjgxMGNlM2QyMWZmNGZkMTVkNTkzM2MxZmEzYjVmZjgxMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f8RUg3HxjwYBkZz8sdejbFPaitahOZeg46b6XjyGAeg)

whoopsie, i missed this one. 
this one is good: https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/a4079de8fdc2f10b2d95bbb61542fe560a83b143/Open/Models_and_CAD/BlenderBIM/Highland_Haven.ifc

**Comment by Moult** [comment]
@brunoperdigao for the bounding box decorator, have a look at how the new Item mode decoration works. It might be worthwhile doing something similar.

No strong opinions on locking, it's not something I've worked with much.

**Comment by brunoperdigao** [comment]
> @brunoperdigao for the bounding box decorator, have a look at how the new Item mode decoration works. It might be worthwhile doing something similar.
> 
> No strong opinions on locking, it's not something I've worked with much.
Looks cool. I think it can work nicely in this context as well

**Comment by brunoperdigao** [comment]
I tried to create an option that doesn't rely too much on decorators, because it was not performing well with [Highland Have](https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/a4079de8fdc2f10b2d95bbb61542fe560a83b143/Open/Models_and_CAD/BlenderBIM/Highland_Haven.ifc) file. So the idea is to use the decorator just to show the aggregate origin and its parts:

https://github.com/user-attachments/assets/e80dd5e1-f69e-416b-8401-e4cbe8236561

Also, the parts are constrained to the aggregate and the move tool (`G`) will be overridden by another function, meaning that if it belongs to an aggregate, the move tool will move the whole aggregation. If the user wants to move a single object, it will have to enter the "aggregate edit mode" (not hotkey for this yet). Then all the other objects will be displayed as "BOUNDS", and you can move individual objects that belong to that aggregate. See the example below.

What do you guys think of this approach?

https://github.com/user-attachments/assets/3768a476-40cf-4836-97f8-90d99a699b9e

**Comment by theoryshaw** [comment]
so very cool!

**Comment by theoryshaw** [comment]
Is there a branch somewhere where i can testy? :)

**Comment by brunoperdigao** [comment]
@theoryshaw I created a PR: https://github.com/IfcOpenShell/IfcOpenShell/pull/5787

To enter the "aggregate edit mode" you have to use F3 and type the name of the operator. Let me know you you have any suggestion on which hotkey to use. I thought of using TAB but I think it might get confusing.

**Comment by theoryshaw** [comment]
This is awesome of course. 

Ran into a small error...
I have the 'sun' in the default blender file.
...
Also, would it be too much overhead to turn off 'selectability' of the wireframe objects outside the aggregate, when in edit mode?

https://github.com/user-attachments/assets/598f213c-1285-49da-bd37-025fb81281b8

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 441, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\aggregate\operator.py", line 387, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\ifc.py", line 291, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\aggregate\operator.py", line 416, in _execute
    data = ItemDecorator.get_obj_data(obj.original)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\decorator.py", line 58, in get_obj_data
    if len(obj.data.loop_triangles) > 0:
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SunLight' object has no attribute 'loop_triangles'

```

**Comment by brunoperdigao** [comment]
@theoryshaw done

**Comment by theoryshaw** [comment]
cool. 

>  I thought of using TAB but I think it might get confusing.

I think 'tab' would be great.
And maybe 'enter' to exit. (similar to the UI with the meaure, polyline tool, etc.)

**Comment by brunoperdigao** [comment]
I'm still experimenting, but I think it might get confusing to use `TAB`. Let's say the user wants to edit an object without knowing that that object is part of an aggregation and try to use tab to edit it. It will behave differently then expected and there is no clear information on why that happened.
With this approach, at least the user is informed that there is a specific way to edit an aggregate. Right now I'm using the `crtl + tab hotkey, which I think it's not commonly used in vanilla Blender. Makes sense?

**Comment by theoryshaw** [comment]
> It will behave differently then expected and there is no clear information on why that happened.

What about an edit mode like this, to tell the user what happened. 


```
import bpy
import gpu
from gpu_extras.batch import batch_for_shader
from mathutils import Vector

class BorderProperties:
    width = 10  # Default width

def draw_callback_px(self, context):
    """Draw callback for the viewport border."""
    width = context.region.width
    height = context.region.height
    border_width = BorderProperties.width  # Use the stored width
    
    # Create vertices for four rectangles (top, right, bottom, left)
    vertices = (
        # Top rectangle
        Vector((0, height - border_width, 0)),
        Vector((width, height - border_width, 0)),
        Vector((width, height, 0)),
        Vector((0, height, 0)),
        
        # Right rectangle
        Vector((width - border_width, 0, 0)),
        Vector((width, 0, 0)),
        Vector((width, height, 0)),
        Vector((width - border_width, height, 0)),
        
        # Bottom rectangle
        Vector((0, 0, 0)),
        Vector((width, 0, 0)),
        Vector((width, border_width, 0)),
        Vector((0, border_width, 0)),
        
        # Left rectangle
        Vector((0, 0, 0)),
        Vector((border_width, 0, 0)),
        Vector((border_width, height, 0)),
        Vector((0, height, 0))
    )
    
    indices = ((0,1,2), (0,2,3),  # Top
               (4,5,6), (4,6,7),  # Right
               (8,9,10), (8,10,11),  # Bottom
               (12,13,14), (12,14,15))  # Left
    
    shader = gpu.shader.from_builtin('UNIFORM_COLOR')
    batch = batch_for_shader(shader, 'TRIS', 
        {"pos": vertices},
        indices=indices
    )
    
    gpu.state.blend_set('ALPHA')
    
    shader.bind()
    shader.uniform_float("color", (1, 0, 0, 0.8))
    batch.draw(shader)

# Store handler to remove it later
_handle = None

def register():
    global _handle
    # Always unregister first to clean up any existing handler
    unregister()
    
    args = (None, bpy.context)
    _handle = bpy.types.SpaceView3D.draw_handler_add(
        draw_callback_px, args, 'WINDOW', 'POST_PIXEL'
    )
    # Force a redraw
    for window in bpy.context.window_manager.windows:
        for area in window.screen.areas:
            if area.type == 'VIEW_3D':
                area.tag_redraw()

def unregister():
    global _handle
    if _handle is not None:
        bpy.types.SpaceView3D.draw_handler_remove(_handle, 'WINDOW')
        _handle = None

def set_border_width(width):
    """Set the border width and refresh the display."""
    BorderProperties.width = width
    # Force a redraw
    for window in bpy.context.window_manager.windows:
        for area in window.screen.areas:
            if area.type == 'VIEW_3D':
                area.tag_redraw()

# Initial setup
if __name__ == "__main__":
    register()
```

![image](https://github.com/user-attachments/assets/93456cd8-285a-404c-882a-f1cfbf0d052f)

**Comment by theoryshaw** [comment]
I do like the simplicity of using 'tab' universally to **_get into_** something, whether it's an aggregate, edit mode, edit profile outline, edit an item, etc.

**Comment by brunoperdigao** [comment]
> What about an edit mode like this, to tell the user what happened.

I thought about this, but I wasn't happy with the result, visually. I'll try to  come up with something similar.

**Comment by brunoperdigao** [comment]
@theoryshaw I made a few updates, let me know what you think. It's using `TAB` now. I think you were right, feels better to use `TAB`.

**Comment by theoryshaw** [comment]
Very cool, i like it so far!

What's your thoughts on the following?  I brought them up in the PR, but will repeat them here, as it's easier to keep track of the conversation thread. 

---

https://github.com/IfcOpenShell/IfcOpenShell/pull/5787/files#diff-c67865bbf0847242e8678ca2943686a9dd234d2e1be7d8476393e7335182e7c4R136-R147

the one thing that concerns me is how long this loop takes to finish. With Highland Haven, when i enter in edit mode, it take 5 seconds... and another 5 seconds when i exit edit mode. Unfortunately that would be kinda annoying to deal with.

Could there be a way, i wonder, to not use this loop at all, and have some visual display that you're 'in' edit mode.

---

https://github.com/IfcOpenShell/IfcOpenShell/pull/5787/files#diff-c67865bbf0847242e8678ca2943686a9dd234d2e1be7d8476393e7335182e7c4R144

I noticed it seems with this set to 'BOUNDS' it doesn't allow you to snap to these objects, which i think it important to maintain, as usually the objects in the aggregate need to snap to its surrounding context.

**Comment by brunoperdigao** [comment]
A few more changes:
- I ran some test and what is actually causing the delay is to turn of the object selection. I removed that. Now you can select the object but you won't be able to move or edit it.
- To enhance visual feedback, I've added a bounding box that turns green when in aggregate mode.
- I've also explored using "WIRE" instead of "BOUNDS", which enables snapping.
- Additionally, I've created two new UI operators: • One to exit aggregate mode; another to toggle local view, displaying only objects belonging to the current aggregate.
![imagem](https://github.com/user-attachments/assets/6f643294-bdf5-441f-b66c-e6d1172b8454)

**Comment by theoryshaw** [comment]
love it.

...

How do you move 'just' the aggregate's empty(origin) without moving all the parts with it?

...

I noticed when you select the aggregate's empty and tab into it, you get the following error. 

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 441, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1802, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\ifc.py", line 291, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1809, in _execute
    bonsai.core.aggregate.enable_aggregate_mode(tool.Aggregate, context.active_object)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\aggregate.py", line 93, in enable_aggregate_mode
    aggregator.enable_aggregate_mode(obj)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\aggregate.py", line 151, in enable_aggregate_mode
    aggregate_obj= tool.Ifc.get_object(aggregate)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\ifc.py", line 130, in get_object
    return IfcStore.get_element(element.id())
                                ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

```

...

>  I've added a bounding box that turns green when in aggregate mode.

I didn't see this on my end.  Maybe not needed anyways, as the wire frame is indication enough that you're in aggregate edit mode. 

https://github.com/user-attachments/assets/dbe4bca6-4780-480d-b71f-54d02fbb0b41

**Comment by brunoperdigao** [comment]
New commits:
- https://github.com/IfcOpenShell/IfcOpenShell/pull/5787/commits/9bdcc12cca42f2c245aed138b4d044beab596d78

https://github.com/user-attachments/assets/175a8f5a-786b-4aab-8f73-5037384e75ac



- https://github.com/IfcOpenShell/IfcOpenShell/pull/5787/commits/0981548a85b61b03e75af564b483ffe5a956aae2

@theoryshaw I couldn't reproduce your error. Could you try again with the last changes? Or maybe point me the exact aggregate you tried to `TAB`into?

**Comment by theoryshaw** [comment]
I think you fixed it! (or it was operator error) :)
...
It seems tabbing out of an aggregates take some time...

https://github.com/user-attachments/assets/320aebce-5de3-424e-a6d2-01d6d61c3e67

**Comment by brunoperdigao** [comment]
@theoryshaw Thanks for testing, I think I spotted the issue. Let me know if the last commit reduces the time.

**Comment by theoryshaw** [comment]
It's smooth now!
