### ISSUE TITLE
'IFC4.IfcVoidingFeature' has no attribute 'HasFillings'. Did you mean: 'HasOpenings'?

### ISSUE THREAD

**Issue by VDobranov** [IfcOpenShell/IfcOpenShell#3889]
Hi!
I am trying to meddle with IfcVoidingFeatures in BB. But has some struggles with showing-hiding voids.

First, I export a part with cutouts from Tekla:
![Снимок экрана 2023-10-15 в 15 28 58](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/7cc4aa88-061d-4a8b-ab30-f068e26e6c03)

This how it looks in BIMcollabZOOM (not sure why voids are solid):
![Снимок экрана 2023-10-15 в 15 29 18](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/631157a5-0653-427f-b7f0-a428da8969ce)

And this how it looks after opening the file in BB:
![Снимок экрана 2023-10-15 в 15 29 28](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/e30957a5-0ba1-4866-965e-f435d0149e98)

I turn on the voids visibility:
![Снимок экрана 2023-10-15 в 15 29 47](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/d6192d08-29f1-4012-9738-519d234149c7)

I try to turn off the voids visibility:
![Снимок экрана 2023-10-15 в 15 29 54](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/7186c9ca-2924-44c3-8cc4-3f7fec13a0ae)

Console output:
```
Error: Python: Traceback (most recent call last):
  File "/Users/vdobranov/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/workspace.py", line 537, in invoke
    return self.execute(context)
  File "/Users/vdobranov/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/ifc.py", line 193, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/Users/vdobranov/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/ifc.py", line 338, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/vdobranov/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/workspace.py", line 529, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "/Users/vdobranov/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/workspace.py", line 774, in hotkey_A_O
    bpy.ops.bim.edit_openings()
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/vdobranov/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/ifc.py", line 193, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/Users/vdobranov/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/ifc.py", line 338, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/vdobranov/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/opening.py", line 777, in _execute
    building_objs.update(self.get_all_building_objects_of_similar_openings(opening))
  File "/Users/vdobranov/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/model/opening.py", line 785, in get_all_building_objects_of_similar_openings
    if not opening.HasFillings:
  File "/Users/vdobranov/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 188, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcVoidingFeature' has no attribute 'HasFillings'. Did you mean: 'HasOpenings'?
Location: /Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py:113
```

Debug info:
```
os: Darwin
os_version: Darwin Kernel Version 21.6.0: Thu Mar  9 20:10:19 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_ARM64_T8101
python_version: 3.10.12
architecture: ('64bit', '')
machine: arm64
processor: arm
blender_version: 3.6.0
blenderbim_version: 0.0.230902
ifc: 250_END-R0_A.ifc
schema: IFC4
preprocessor_version: Tekla structures 2023 Service Pack 6
originating_system: IFC Export version Sep 28 2023
```

IFC-file itself: 
[250_END-R0_A.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12909279/250_END-R0_A.ifc.zip)

**Comment by Andrej730** [comment]
It's giving errors since it's expecting opening from IfcPlate -> HasOpenings -> IfcRelVoidsElement -> RelatedOpeningElement -> IfcVoidingFeature and expecting it to be IfcOpeningElement.

In [IfcVoidingFeature section of IFC documentation](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcVoidingFeature.htm) it says that the standard use is part of element types, not occurences. But it's not restricted, so it's a valid IFC.

> The standard use of instances of [IfcVoidingFeature](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcVoidingFeature.htm) is as a part of element type objects (instances of subtypes of [IfcElementType](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcElementType.htm)). The part–whole relationship is established by an aggregation relationship object, expressing the decomposition of an element type into one or more additive elements (element parts) and zero or more feature elements.


From examples for [slabs](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcSlab.htm#Figure-6.1.3.35.G-A-section-showing-a-slab-made-from-precast-hollow-core-panels) and [walls](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcWall.htm#Figure-6.1.3.41.J-A-wall-decomposed-into-parts.) it seems that IfcVoidingFeature suggested to be implemented through IfcWall -> IfcRelAggregates -> RelatingObject -> IfcBuildingElement -> PartRelatedObjects -> IfcRelVoidsElement -> IfcVoidingFeature:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/bcd34d3f-4eba-4750-94e2-784fff2e2554)

It seems `ifcopenshell.geom.create_shape` is not applying those openings too. 
@aothms Can you please take a look? 
```python
import ifcopenshell
import ifcopenshell.geom
from pprint import pprint
import numpy as np

file = ifcopenshell.open(r"250_END-R0_A.ifc")

# #58=IfcPlate('2ZsHQ$xOH8SQOL8Q2Ab_DL',$,'250_END-R0_A','18',$,#41,#57,'ОСП-3',.NOTDEFINED.)
element = file.by_id(58) 
# #53=IfcShapeRepresentation(#52,'Body','SolidModel',(#51))
representation = file.by_id(53)
settings = ifcopenshell.geom.settings()
settings.set(settings.WELD_VERTICES, True)

shape = ifcopenshell.geom.create_shape(settings, element)
verts = np.array(shape.geometry.verts).reshape(-1, 3)
pprint(verts)
# array([[ 0.   ,  0.   ,  0.009],
#        [ 0.   ,  0.   , -0.009],
#        [ 0.918,  0.   , -0.009],
#        [ 0.918,  0.   ,  0.009],
#        [ 0.918,  0.392, -0.009],
#        [ 0.918,  0.392,  0.009],
#        [ 0.   ,  0.392, -0.009],
#        [ 0.   ,  0.392,  0.009]])

shape = ifcopenshell.geom.create_shape(settings, representation)
verts = np.array(shape.verts).reshape(-1, 3)
pprint(verts)
# array([[ 0.   ,  0.   ,  0.009],
#        [ 0.   ,  0.   , -0.009],
#        [ 0.918,  0.   , -0.009],
#        [ 0.918,  0.   ,  0.009],
#        [ 0.918,  0.392, -0.009],
#        [ 0.918,  0.392,  0.009],
#        [ 0.   ,  0.392, -0.009],
#        [ 0.   ,  0.392,  0.009]])
```

**Comment by aothms** [comment]
@Andrej730 I've added a commit to handle openings based on their supertype, so this includes then voiding feature and also earthworks cut in IFC4.3 onwards. I'll start a new build.

**Comment by Andrej730** [comment]
@VDobranov I've added some fixes for those errors but to see the actualy geometry with openings we'll need to wait for a new build.
Previously we mainly were considering openings made of IfcOpeningElement, not IfcVoidingFeature. If you meet more issues, don't hesitate to report!

**Comment by VDobranov** [comment]
Thank you both for your efforts!

**Comment by Andrej730** [comment]
Tested on new build, it's working now:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/11a8c4b6-1efc-4247-a15b-fe03ee51347d)
