### ISSUE TITLE
When try to `bpy.ops.bim.unlink_object()` get following error. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3898]
When try to `bpy.ops.bim.unlink_object()` get following error. 

ping @Andrej730 
might be https://github.com/IfcOpenShell/IfcOpenShell/commit/f38952dc51cc4cf1b9ff2563804e0893ae354efd :)

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\root\operator.py", line 162, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\root\operator.py", line 183, in _execute
    tool.Ifc.unlink_element(obj=obj)
AttributeError: type object 'Ifc' has no attribute 'unlink_element'

```

**Comment by Andrej730** [comment]
Ooops.
