### ISSUE TITLE
Failed to process shape and no view of annotation on reopen IFC file

### ISSUE THREAD

**Issue by SavuGust27** [IfcOpenShell/IfcOpenShell#3903]
When going to my saved drawing views and activating, none of the annotation are visible and the objects do not convert to my plan view representation. I also cannot print the view. was working well until i reopen the IFC file. I updated BlenderBIM to the daily builds, but still the same. creating a new view does not resolve the issue, witch previously was the way i could resolve it. I leave the file if it is needed. Also, i keep the file in my google drive, i dont know if that has an impact, since i work in my laptop and my desktop, and google drive is how i manage to work in the same file

```
Python: Traceback (most recent call last):
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 481, in import_representation
    shape = ifcopenshell.geom.create_shape(settings, element)
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 210, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 2434, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process shape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1485, in invoke
    return self.execute(context)
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1494, in execute
    core.activate_drawing_view(tool.Ifc, tool.Drawing, drawing=drawing)
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\drawing.py", line 429, in activate_drawing_view
    drawing_tool.activate_drawing(camera)
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 1655, in activate_drawing
    blenderbim.core.geometry.switch_representation(
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\geometry.py", line 116, in switch_representation
    new_repr_data = geometry.import_representation(obj, representation, apply_openings=apply_openings)
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 487, in import_representation
    shape = ifcopenshell.geom.create_shape(settings, element)
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 210, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 2434, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process shape
```

[CLOUTHIER MASTER.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12976370/CLOUTHIER.MASTER.zip)

**Comment by Andrej730** [comment]
Hello! The problem is with those StairFlight representations:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/c2396f05-d71c-405f-acd5-fdab305063de)

they have Point Cloud representation that are pointing to empty list of points:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/5e706fac-55bb-40df-b2f2-3b5e2d3f8a7f)

You can remove those Point Cloud representations and it will work.

To debug similar issues you can run validation for ifc file
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/bc2cc455-3ffc-4fdd-97c8-ca89f3a2491a)
 
And run "Test All Shapes" to narrow down the problematic shapes.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/30d895ed-37d6-4b11-9905-500b2e46501c)

**Comment by SavuGust27** [comment]
Thanks for the fix. Those PointCloud representation happen when i duplicate a smart stair, it has happens before, but usually when that happens, the sairs switch to empties, and i can fix it. but the problem is when i duplicate does stairs
