### ISSUE TITLE
IfcAnnotation DRAWING objects without reference documents and groups

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3920]
Not sure how these errant ifcannotation objects were created, but I can't seem to delete them. 

file: https://gitlab.com/openingdesign/Restaurant_Sun_Prairie/-/blob/b25421ff496b63ade03e244fa0d390ef07a03b3b/Models/BlenderBIM/Restaurant_Sun_Prairie.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/7042a839-f5c1-4648-af4f-296d6fcfb5de

**Comment by theoryshaw** [comment]
error. 
```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 527, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 506, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 546, in _execute
    tool.Geometry.delete_ifc_object(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 87, in delete_ifc_object
    return blenderbim.core.drawing.remove_drawing(tool.Ifc, tool.Drawing, drawing=element)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\drawing.py", line 299, in remove_drawing
    information = drawing_tool.get_reference_document(drawing_tool.get_drawing_document(drawing))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 1560, in get_reference_document
    return reference.ReferencedDocument
AttributeError: 'NoneType' object has no attribute 'ReferencedDocument'

```

**Comment by theoryshaw** [comment]
Also get the following error with `bim.activate_model`.

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1454, in execute
    blenderbim.core.geometry.switch_representation(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\geometry.py", line 116, in switch_representation
    new_repr_data = geometry.import_representation(obj, representation, apply_openings=apply_openings)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 509, in import_representation
    mesh = ifc_importer.create_camera(element, shape)
AttributeError: 'IfcImporter' object has no attribute 'create_camera'. Did you mean: 'create_material'?


```

**Comment by Andrej730** [comment]
I think you can just change ObjectType for those 3 to anything besides `DRAWING` and they'll be safe to remove.

Those objects are a bit weird - they don't have any relating DRAWING IfcGroup and are not associated with any IfcDocumentReference, this is why they produce errors. We need to know how they were produced to fix the issue (if there is an issue).

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/e36862f6-7fa4-4595-a9fe-f00af00cc11d)

**Comment by theoryshaw** [comment]
cool.. thx!

I'm not sure how it was originally created.  I'll keep this issue open and keep my eye open, if it happens again.
