### ISSUE TITLE
MEP Authoring : Changing IfcPipeSegment bend settings in operator redo panel leaves stray fitting objects

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3932]
I think this might be a matter of garbage collection but it sems like changing the operator settings in the redo panel doesn't get rid of the previously generated items.

![Animation3](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/6de4f005-62ba-4d87-b6ce-4bc57f14ed71)

Leads to that on reloading the ifc file :

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/ff78735e-eed3-4347-8a5d-15016e02751e)

**Comment by Moult** [comment]
Indeed, this is exactly why for the wall tool we don't allow this workflow. Instead there is an explicit "refresh" button when changing parameters and you can't set the parameter on creation.

**Comment by Gorgious56** [comment]
I think a solution may be to compute the correct geometry and create dumb vanille meshes on execution and only instantiate the ifc entity if the operator is validated for good. Would it be possible or is the execution tightly tied to the ifc instantiation? Also, I don't remember if there is a callback when the operator is applied for good. It might not since from Blender's perspective the data is overwritten and gced every time the redo panel is tweaked but that's a problem since the data is still written in the ifc file.
 Another solution would be to use a gpu shader to draw the connection in 3d and activate some kind of "draw mode" in the tool panel where the bend settings can be tweaked before the operator is run and the user sees what they will get when executed. Random thoughts 😅

**Comment by Andrej730** [comment]
I don't think there is a way to detect when the operator is applied for good, only by asking user the user to explicitly state that it is. Yeah, we probably can do something like we do with doors and windows when element is generated with bmesh until user didn't state that the edit process is over, then it's saved to ifc.

Not sure what I'm missing but can't reproduce this, tried to adjust the bend from the redo panel, then close it and redo again and then save the ifc.
<video src="https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/c7dd9a37-972e-4712-9526-26d3bc7488da"/>

**Comment by Gorgious56** [comment]
The duplicated fittings are only shown after closing and opening the blend and ifc file again next time

**Comment by Andrej730** [comment]
Tried this too.

**Comment by Gorgious56** [comment]
Went to test if the bug is still existing but I'm greeted by instant error when tweaking any prop in the redo panel.
Bonsai 250413 + Blender 4.3.2

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 458, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\mep.py", line 998, in _execute
    segments_intersection_ws = tool.Cad.intersect_edges(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by BIMvoice** [comment]
On current v0.8.0 the instant error is still there. `MEPAddBend._execute` calls `tool.Cad.intersect_edges(...)[0]`, and `intersect_edges` returns `None` for parallel/collinear segment axes (no crossing), which is what raises `'NoneType' object is not subscriptable`. I've guarded it the same way `compute_bend_preview_polylines` already handles that `None`: the operator now reports a clear error and cancels instead of crashing, before touching the IFC. Added a regression test. Fixed in #8339.

The original stray-fitting report is a separate, mostly-addressed matter: the newer bend-preview flow commits once on Apply and the re-edit path deletes the old bend via `editing_bend_id`. The one gap left is that the "Add Bend" toolbar button still invokes `MEPAddBend` directly (with a redo panel) rather than going through the preview, so tweaking that redo panel can still duplicate a fitting. Routing the button through the preview flow would close that, but it's a workflow change rather than the crash fix, so I left it out of this PR.
