### ISSUE TITLE
Library not working for python 3.12

### ISSUE THREAD

**Issue by imanwarsame** [IfcOpenShell/IfcOpenShell#3955]
First tried installing using pip and got this error. Then I installed the pre-built package and added to my virtual environment site packages and still getting this error. Is 3.12 not supported?
```
Traceback (most recent call last):
  File "c:\Users\XXXX\source\repos\XXXX\.venv\Lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module    
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 915, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1288, in create_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
ImportError: DLL load failed while importing _ifcopenshell_wrapper: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\XXXX\source\repos\XXXX\.venv\Lib\site-packages\ifcopenshell\__init__.py", line 61, in <module>     
    from . import ifcopenshell_wrapper
  File "c:\Users\XXXX\source\repos\XXXX\.venv\Lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 17, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
                            ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\XXXX\source\repos\XXXX\.venv\Lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_ifcopenshell_wrapper')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module    
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\XXXX\source\repos\XXXX\geometry.py", line 7, in <module>
    import ifcopenshell
  File "c:\Users\XXXX\source\repos\XXXX\.venv\Lib\site-packages\ifcopenshell\__init__.py", line 69, in <module>     
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.12'
```

**Comment by Moult** [comment]
Yeah 3.12 is not part of the build system yet :(
