### ISSUE TITLE
Blender crashes when changing type's IFC class. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3958]
Blender crashes when changing type's IFC class. 

 File: https://gitlab.com/openingdesign/Restaurant_Sun_Prairie/-/blob/8990784e2bc0cf80495a5dc111120f96c7e5da28/Models/BlenderBIM/Restaurant_Sun_Prairie.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/490d2a68-e14c-4fdd-8eeb-187302297ebf

```
0 / 25 elements processed ...
C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\shapely\set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\schema.py", line 69, in reassign_class
    declaration = schema.declaration_by_name(new_class)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 5770, in declaration_by_name
    return _ifcopenshell_wrapper.schema_definition_declaration_by_name(self, *args)
RuntimeError: Entity with name 'IfcElectricApplianc' not found in schema 'IFC4'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\root\operator.py", line 92, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\root\operator.py", line 101, in _execute
    product = ifcopenshell.api.run(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\root\reassign_class.py", line 83, in execute
    ifcopenshell.api.run(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\root\reassign_class.py", line 72, in execute
    element = ifcopenshell.util.schema.reassign_class(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\schema.py", line 71, in reassign_class
    raise Exception(f"Class of {element} could not be changed to {new_class} as the class does not exist")
Exception: Class of #1278321=IfcBuildingElementProxy('2suH8y00n5nxYZVIqkE7xK',#1128771,'co43r-uc self-contained:DISPLAY REFRIG:3598656',$,'co43r-uc self-contained:DISPLAY REFRIG',#1326661,#1278320,'3598656',.NOTDEFINED.) could not be changed to IfcElectricApplianc as the class does not exist
```

**Comment by Moult** [comment]
Ping @myoualid note that `strip()` treats its arg as a list of characters to strip.
