### ISSUE TITLE
Can't generate Gantt chart for IfcWorkSchedule with references

### ISSUE THREAD

**Issue by mdjska** [IfcOpenShell/IfcOpenShell#3985]
When I create a work schedule with the `sequence.add_work_schedule` api function, a reference to an IfcPerson and IfcOwnerHistory is created. These references seem to break the `Generate Gantt` functionality of BlenderBIM.

Work schedule created with ifcopenshell (#15 is IfcPerson) -> Gantt chart can't be generated:
```
#89105=IFCOWNERHISTORY(#17,#2,.READWRITE.,.ADDED.,1699532280,#17,#2,1699532280);
#89106=IFCWORKSCHEDULE('24v26eYeT0lhNpWuCRKSTZ',#89105,'Construction',$,$,$,'2023-11-09T13:18:00.049229',(#15),$,$,$,'2023-11-09T13:18:00.045657',$,.NOTDEFINED.);
#89107=IFCOWNERHISTORY(#17,#2,.READWRITE.,.ADDED.,1699532280,#17,#2,1699532280);
#89108=IFCRELDECLARES('090DduH6X4WgPETrOHl2DJ',#89107,$,$,#93,(#89106));
```
Work schedule created with BlenderBIM -> Gantt chart can be generated normally:
```
#89111=IFCWORKSCHEDULE('0WgGNOCYHACvAhAoSGqUbt',$,'Construction',$,$,$,'2023-11-09T13:16:35.828460',$,$,$,$,'2023-11-09T13:16:35.827692',$,.PLANNED.);
#89112=IFCRELDECLARES('3XkiP3FbbCqA0Jqqi$4gFG',$,$,$,#93,(#89111));
```
If I manually remove the references, the Gantt chart will be created normally. This is the full error I get:
```
Python: Traceback (most recent call last):
  File "/Users/martina/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/sequence/operator.py", line 573, in execute
    core.generate_gantt_chart(tool.Sequence, work_schedule=tool.Ifc.get().by_id(self.work_schedule))
  File "/Users/martina/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/core/sequence.py", line 533, in generate_gantt_chart
    sequence.generate_gantt_browser_chart(json, work_schedule)
  File "/Users/martina/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/tool/sequence.py", line 1550, in generate_gantt_browser_chart
    pystache.render(t.read(), {"json_data": task_b64, "data": json.dumps(work_schedule.get_info())})
  File "/Applications/Blender.app/Contents/Resources/3.5/python/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Applications/Blender.app/Contents/Resources/3.5/python/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Blender.app/Contents/Resources/3.5/python/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Applications/Blender.app/Contents/Resources/3.5/python/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type entity_instance is not JSON serializable
```
system: macos 12.6.9
ifcopenshell version: ifcopenshell-0.7.0.231018
blenderbim version: blenderbim-231108

**Comment by sboddy** [comment]
Whoops. This is referring to an ifcopenshell issue, not Bonsai.

**Comment by Moult** [comment]
It's a bit hard to track down when exactly this was fixed, but I think around 0.8.0 the fix was in (replacing `work_schedule.get_info()` with `recursive=True`).
