### ISSUE TITLE
BlenderBIM error duplicating a Space Boundary

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#3993]
Attempting to duplicate a Space Boundary produces this error:

```
ReferenceError: StructRNA of type Object has been removed
Error: Python: Traceback (most recent call last):
  File "/usr/share/blender/3.6/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 722, in execute
    return OverrideDuplicateMove.execute_duplicate_operator(self, context, linked=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/3.6/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 731, in execute_duplicate_operator
    IfcStore.execute_ifc_operator(self, context)
  File "/usr/share/blender/3.6/scripts/addons/blenderbim/bim/ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/3.6/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 725, in _execute
    return OverrideDuplicateMove.execute_ifc_duplicate_operator(self, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/3.6/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 816, in execute_ifc_duplicate_operator
    tool.Boundary.decorate_boundary(new_obj)
  File "/usr/share/blender/3.6/scripts/addons/blenderbim/tool/boundary.py", line 77, in decorate_boundary
    new.obj = obj
    ^^^^^^^
```

eg. a single *Wall* element may require multiple 2ndLevel Space Boundaries, the most obvious way to do this is to duplicate an existing boundary and adjust the geometry. Note that a duplicated boundary would have a different origin, but boundaries must always share the same origin as their parent space, see #2621.

Another solution would be to disable duplication, but allow a boundary to be split at the cursor position (similar to the current split operator for walls).

See also #1676

**Comment by CyrilWaechter** [comment]
I thought it was fully fixed in https://github.com/IfcOpenShell/IfcOpenShell/commit/6216ee9a9826a3c0e6cdcb67834f317f7668e3f4 but there is still an error occurring:
```python
Python: Traceback (most recent call last):
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 721, in execute
    return OverrideDuplicateMove.execute_duplicate_operator(self, context, linked=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 730, in execute_duplicate_operator
    IfcStore.execute_ifc_operator(self, context)
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/ifc.py", line 340, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 724, in _execute
    return OverrideDuplicateMove.execute_ifc_duplicate_operator(self, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 829, in execute_ifc_duplicate_operator
    OverrideDuplicateMove.remove_old_connections(old_to_new)
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 876, in remove_old_connections
    for connection in new[0].ConnectedTo:
                      ^^^^^^^^^^^^^^^^^^
  File "/home/cyril/git/IfcOpenShell/src/blenderbim/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 191, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcRelSpaceBoundary2ndLevel' has no attribute 'ConnectedTo'
```

**Comment by brunopostle** [comment]
Closing, as copying a space boundary seems to work now.

Also Cyril's error seems to have been fixed in dda803d
