### ISSUE TITLE
invalidating python handles on `ifc_file.remove`

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#4033]
Currently if you remove IFC entity with `file.remove` and then try to acess the removed entity it will lead to a crash which makes it's sometimes very tricky to debug what code exactly accessed the removed entity to solve it.

Example:
```python
import ifcopenshell
file = ifcopenshell.file()
wall = file.createIfcWall(GlobalId="xxx")
print(wall)
file.remove(wall)
print(wall)
print('never printed because of the EXCEPTION_ACCESS_VIOLATION')
```

In Blender they used to have the same issue, it was especially nasty because all objects got invalidated not just on their deletion but also on any undo/redo in the current Blender session. 

The way they solved it is when object becomes invalid to avoid crashes it starts returning `<bpy_struct, Object invalid>` instead of the original object and throw `ReferenceError: StructRNA of type Object has been removed` if any of it's attributes or methods are accessed. That way Blender doesn't crash and you get a traceback indicating where invalidated object was accessed and it's easier to fix it.

Not sure how exactly it's working internally but I guess on object remove it's kind of switching some kind of flag in python handle instead of removing it completely - object is still accessible but indicates that's not valid anymore.

```python
a = bpy.data.objects['Cube']
a
# bpy.data.objects['Cube']
a.location
# Vector((0.0, 0.0, 0.0))
bpy.data.objects.remove(a)
a
#~ <bpy_struct, Object invalid>
a.location
# Traceback (most recent call last):
#   File "<blender_console>", line 1, in <module>
# ReferenceError: StructRNA of type Object has been removed
```

**Comment by Andrej730** [comment]
A bit related thing I never understood - on Windows when entity is removed some of it's attributes (atleast `.id()`) is still accessible but on Linux and Mac it will lead to crash right away.

```python
import ifcopenshell

file = ifcopenshell.file()
wall = ifcopenshell.api.run("root.create_entity", file, ifc_class="IfcWall")
file.remove(wall)
print(wall.id()) # 1
print(wall) # crash
```

**Comment by aothms** [comment]
> on Windows when entity is removed some of it's attributes (atleast .id()) is still accessible but on Linux and Mac it will lead to crash right away.

In the C++ world they call it "undefined behaviour" for a reason.

It's one of the last remaining deep fundamental issues. I hope I can resolve it in v0.8.

**Comment by Andrej730** [comment]
Is there way to check whether `ifcopenshell_wrapper.entity_instance` became invalid without crashing python? There seems to be couple methods inside the swig objects, maybe they can help:
```python
import ifcopenshell

ifc_file = ifcopenshell.file()
wall = ifc_file.create_entity("IfcWall")
data = wall.wrapped_data

# <Swig Object of type 'IfcUtil::IfcBaseClass *' at 0x0000014F59E1F870>
# ['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__int__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'acquire', 'append', 'disown', 'next', 'own']
print(data.this)
print(dir(data.this))
```



Also, haven't tried yet but would it work adding a new method to https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcwrap/IfcParseWrapper.i like `bool is_valid(IfcUtil::IfcBaseClass* entity) return entity != nullptr;` ?

**Comment by aothms** [comment]
No, there isn't an easy way to address this without fundamental changes. What we have is a pointer to a memory location. When deleting an instance that region may be reclaimed, but also may stay in tact for a while. Pointers pointing to that region do not get updated (or 'notified' whatever that may mean).

There are two ways we can address this:

- `std::shared_ptr` + `std::weak_ptr`. We should probably still try to squeeze this in for v0.8.
- not actually freeing memory associated with removing deleted instances, but introducing a boolean flag `is_deleted_` on every instance. This would mean memory is increased, because nothing gets actually deleted, and there is an additional boolean flag on every instance. But the benefit of this approach is that it doesn't require any API changes, because everything can remain naked pointers, just when you perform an operation anything is_deleted=true a runtime exception is raised.

**Comment by Andrej730** [comment]
To put it out there for anyone having issues debugging this kind of cases - in python you can enable `faulthandler` (default python module) to get a traceback in case of segfault.

```python
import faulthandler
faulthandler.enable()

import ifcopenshell
ifc_file = ifcopenshell.file()
wall = ifc_file.create_entity("IfcWall")
ifc_file.remove(wall)
# Windows fatal exception: access violation
# Current thread 0x00007714 (most recent call first):
#   File "\ifcopenshell\ifcopenshell_wrapper.py", line 5250 in __repr__
#   File "\ifcopenshell\entity_instance.py", line 360 in __repr__
#   File "\test.py", line 8 in <module>
print(wall)
```

**Comment by aothms** [comment]
@Andrej730 This is miraculous. Thanks for sharing!

See https://github.com/IfcOpenShell/IfcOpenShell/pull/4637 for the WIP definitive fix for this in 0.8.

**Comment by Moult** [comment]
Now that we've switched to v0.8.0 should this be revisited?
