### ISSUE TITLE
pyocc-core V3d error when install ifcopenshell and pyocc-core in same conda environment

### ISSUE THREAD

**Issue by khuongtran78** [IfcOpenShell/IfcOpenShell#4042]
Hi all,

I've just installed pythonocc-core and my ifcopenshell codes break when trying to use geom.add_profile_presentation. I attached the error and the package versions as follows:
- ifcopenshell: 0.7.0.230918
- pyocc-core: 7.7.2

Error:
`Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\ifcopenshell\geom\occ_utils.py", line 38, in <module>
    from OCC.Core import V3d, TopoDS, gp, AIS, Quantity, BRepTools, Graphic3d
  File "C:\ProgramData\anaconda3\lib\site-packages\OCC\Core\V3d.py", line 15, in <module>
    from . import _V3d
ImportError: DLL load failed while importing _V3d: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\temp\Documents\Codebase\IFC_Tutorial\09_create_beams.py", line 169, in <module>
    create_beam_array(beam_name, beam_profile_x, beam_profile_y, beam_length_x, beam_total_length_n_y, beam_inbetween_distance)
  File "C:\Users\temp\Documents\Codebase\IFC_Tutorial\09_create_beams.py", line 110, in create_beam_array
    representation = ifcopenshell.api.run("geometry.add_profile_representation", ifc_file, context=representations["body"], profile=profile, depth=bam_inbetween_distance-beam_profile_x)
  File "C:\ProgramData\anaconda3\lib\site-packages\ifcopenshell\api\__init__.py", line 61, in run
    importlib.import_module(f"ifcopenshell.api.{usecase_path}")
  File "C:\ProgramData\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ProgramData\anaconda3\lib\site-packages\ifcopenshell\api\geometry\add_profile_representation.py", line 19, in <module>
    import ifcopenshell.geom
  File "C:\ProgramData\anaconda3\lib\site-packages\ifcopenshell\geom\__init__.py", line 47, in <module>
    from . import occ_utils as utils
  File "C:\ProgramData\anaconda3\lib\site-packages\ifcopenshell\geom\occ_utils.py", line 42, in <module>
    from OCC import V3d, TopoDS, gp, AIS, Quantity, BRepTools, Graphic3d
ImportError: cannot import name 'V3d' from 'OCC' (C:\ProgramData\anaconda3\lib\site-packages\OCC\__init__.py)`

Any help is appreciated!

Thanks

**Comment by Krande** [comment]
Hey @khuongtran78, this is usually an error message resulting from trying to run Ifcopenshell with an occt version different than what ifcopenshell was compiled with. 

Did you install ifcopenshell using `conda install ifcopenshell`, `conda install ifcopenshell -c ifcopenshell` or did you download the pre-built packages of ifcopenshelll from (see https://blenderbim.org/docs-python/ifcopenshell-python/installation.html for reference of all the various installation alternatives)?

Try installing both from conda using either 

`conda install ifcopenshell pythonocc-core`

or

`conda install ifcopenshell pythonocc-core -c ifcopenshell`

It helps if you check which versions of occt and ifcopenshell you are currently using, please report the results from typing `conda list` in the terminal with the activated python environment containing your ifcopenshell and occt packages.

**Comment by khuongtran78** [comment]
Hi @Krande ,

I've tried to create a new test environment and install both ifcopenshell & pythonocc-core using conda command. The issue still remains so I attach here the packages version for your reference. Appreciate your help!

Thanks
[packages.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13468626/packages.txt)

**Comment by khuongtran78** [comment]
Hi @Krande ,

It seems the error goes away if we install both ifcopenshell and pythonooc-core in the same conda command. I took the solution you posted in here (https://github.com/IfcOpenShell/IfcOpenShell/issues/2267#issuecomment-1176022090) and it seems working well without any error

Thanks very much
Khuong

**Comment by Moult** [comment]
For future reference this single command is given in the docs: https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#conda

Should we add a "warning" note in the docs to emphasize that it needs to be installed in a single command?

**Comment by Krande** [comment]
@Moult Yeah, I think that's a good idea. 

Although if the packages had been properly configured in conda-forge wrt dependencies my understanding is that we shouldn't really have to. I'll try to fix that in future releases of IfcOpenShell on conda-forge.

**Comment by khuongtran78** [comment]
Hi @Krande , @Moult  I noticed that the exact error returns after I install bpy (to work in blenderbim) via `pip install bpy`. I wonder if there is a dependency conflict amongst the 3 packages.

**Comment by Moult** [comment]
Your error is to do with OCC versions. Doing `pip install bpy` has no impact. Also installing ifcopenshell via pip is completely separate and won't pull in OCC.

**Comment by aothms** [comment]
For people running into similar issues: I tracked down an issue with failure to import V3d that I solved by doing `copy .\Library\bin\deflate.dll .\Library\bin\libdeflate.dll` in the root of my conda environment directory (don't ask me why, but I traced this down using the dll dependency walker).
