### ISSUE TITLE
SvgSerializer error on drawing activation

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4059]
If you remove those 2 objects in the view, the drawing works. 

Not sure what's wrong with those objects. 

file: https://hub.openingdesign.com/OpeningDesign/Monica_Residence/src/commit/e201ea34d9374fd0b4382dd0262991d44a96ddd7/Models/BlenderBIM/Monica_Residence.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/dd471172-9421-42c3-aca3-955bc0e432c7

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 202, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 253, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 533, in generate_linework
    self.serialiser.finalize()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1530, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
RuntimeError: An unknown error occurred

```

**Comment by Moult** [comment]
This is now fixed in the latest builds thanks to awesome work by @aothms ! Whooo!
