### ISSUE TITLE
segfaulting IFC file

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#4070]
This is  a Homemaker output file, so it should be ok: [_test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13532082/_test.ifc.txt)

To reproduce:

```
$ IfcConvert _test.ifc
IfcOpenShell IfcConvert 0.7.0 (OCC 7.6.3)
Scanning file...
Done scanning file   
Parsing input file took 1 second
Creating geometry...
[                                                  ]Segmentation fault (core dumped)
```

Other similar IFC files are ok.

**Comment by aothms** [comment]
It's related to this line:

```
#1196=IFCDIRECTION((-nan.,-nan.,-nan.));
```

which likely relates to this other issue I saw coming by on the numpy invalid value in divide (?)

the validation service catches this nicely btw

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/5bebc867-8d8a-43e9-92b7-24e917393207)

**Comment by brunopostle** [comment]
Yes I was trying to locate the numpy error when I generated this file.

The validation service must be doing additional checks, because `ifcopenshell.validate` segfaults.

**Comment by aothms** [comment]
That's true. There is a bespoke syntax check in front using a more
compliant grammar than the IfcOpenShell c++ code base uses.

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op zo 3 dec. 2023 12:34 schreef Bruno Postle ***@***.***>:

**Comment by brunopostle** [comment]
Segfault is here:

```
IfcOpenShell IfcConvert 0.7.0 (OCC 7.6.3)                                                              
Scanning file...
Done scanning file   
Parsing input file took 1 second
Creating geometry...
[                                                  ]
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff06b3a6a in read_aggregate_as_vector<double> (size=<optimized out>, list=<optimized out>)
    at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcparse/IfcParse.cpp:793
793			return_value.push_back(*list[i]);
```

see also #4329

**Comment by brunopostle** [comment]
```
#0  0x00007ffff06b3a6a in read_aggregate_as_vector<double> (size=<optimized out>, list=<optimized out>) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcparse/IfcParse.cpp:793
#1  IfcParse::ArgumentList::operator std::vector<double, std::allocator<double> > (this=<optimized out>) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcparse/IfcParse.cpp:811
#2  0x00007ffff0bb6ca6 in Ifc4::IfcDirection::DirectionRatios (this=this@entry=0x555555f43740) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcparse/Ifc4.cpp:13185
#3  0x00007ffff6362e6b in IfcGeom::KernelIfc4::convert (this=0x555557364598, l=0x555555f43740, dir=...) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/IfcDirection.cpp:27
#4  0x00007ffff636f21a in IfcGeom::KernelIfc4::convert (this=0x555557364598, pln=0x555555f43f00, plane=...) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/IfcPlane.cpp:57
#5  0x00007ffff6365407 in IfcGeom::KernelIfc4::convert (this=0x555557364598, l=0x555555f44240, shape=...) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/IfcHalfSpaceSolid.cpp:38
#6  0x00007ffff6359860 in IfcGeom::KernelIfc4::convert_shape (this=0x555557364598, l=0x555555f44240, r=...) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/mapping.i:86
#7  0x00007ffff635f8a3 in IfcGeom::KernelIfc4::convert (this=0x555557364598, l=0x555555f44590, shape=...) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/IfcBooleanResult.cpp:164
#8  0x00007ffff6359780 in IfcGeom::KernelIfc4::convert_shape (this=0x555557364598, l=0x555555f44590, r=...) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/mapping.i:84
#9  0x00007ffff637249b in IfcGeom::KernelIfc4::convert (this=0x555557364598, l=<optimized out>, shapes=std::vector of length 0, capacity 0) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/IfcRepresentation.cpp:34
#10 0x00007ffff6356a38 in IfcGeom::KernelIfc4::convert_shapes (this=0x555557364598, l=0x555555edf4e0, r=std::vector of length 0, capacity 0) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/mapping.i:46
#11 0x00007ffff633f76d in IfcGeom::KernelIfc4::create_brep_for_representation_and_product (this=0x555557364598, settings=..., representation=0x555555edf4e0, product=0x555555f40c40) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/IfcGeom.cpp:593
#12 0x00007ffff634c36a in IfcGeom::IteratorImplementation_Ifc4::create_shape_model_for_next_entity()::{lambda()#1}::operator()() const (__closure=<synthetic pointer>) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/IfcGeomIteratorImplementation.h:791
#13 IfcGeom::IteratorImplementation_Ifc4::decorate_with_cache_<IfcGeom::IteratorImplementation_Ifc4::create_shape_model_for_next_entity()::{lambda()#1}>(GeometrySerializer::read_type, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, IfcGeom::IteratorImplementation_Ifc4::create_shape_model_for_next_entity()::{lambda()#1}) (rt=GeometrySerializer::READ_BREP, f=..., representation_id="1201", product_guid="05j2dkULT5QQoO6r5ebDT9", this=0x5555573644f0) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/IfcGeomIteratorImplementation.h:760
#14 IfcGeom::IteratorImplementation_Ifc4::create_shape_model_for_next_entity (this=0x5555573644f0) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/IfcGeomIteratorImplementation.h:789
#15 IfcGeom::IteratorImplementation_Ifc4::create (this=0x5555573644f0) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcgeom/IfcGeomIteratorImplementation.h:1092
#16 0x0000555555571765 in IfcGeom::Iterator::next (this=0x7fffffffc230) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcconvert/../serializers/../ifcgeom_schema_agnostic/IfcGeomIterator.h:135
#17 main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20240319git.fc39.x86_64/src/ifcconvert/IfcConvert.cpp:1180

**Comment by aothms** [comment]
Thanks for the reminder. Fixed now.
