### ISSUE TITLE
Error when loading a model in the latest build: 0.0.231204

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4077]
It was working just fine before this build, @Moult.

This error is repeated several times:
```
Python: Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\helper.py", line 364, in extract
    return self.extract_ifc_spf(ifc_file)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\helper.py", line 375, in extract_ifc_spf
    line = next(ifc_file)
StopIteration
```
And this just once at the end: 
```
Python: Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 642, in execute
    return self.finish_loading_project(context)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 654, in finish_loading_project
    context.scene.BIMProjectProperties.total_elements = len(tool.Ifc.get().by_type("IfcElement"))
AttributeError: 'NoneType' object has no attribute 'by_type'
```

**Comment by brunopostle** [comment]
It works here (latest blenderbim from git, IfcOpenShell from 2023-11-28). The extract_ifc_spf() error suggests there is something weird about your IFC file header section.

**Comment by Andrej730** [comment]
@BIMvoice hi! Can you please send an example .ifc file or ifc file header (it's that part highlighted in the example below)? 
It seems, it's failing because it couldn't find `FILE_SCHEMA` before the .ifc ended.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/7e87ec21-6dc6-4284-9fb1-85812a9a16d1)

**Comment by BIMvoice** [comment]
@Andrej730 you are right. For some reason, the file was corrupted. I downloaded it again and it works just fine now.
