### ISSUE TITLE
Error saving when there's a linked IFC file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4081]
I get the following error after limit dissolving an object. 
I think it has something to do with the linked ifc. 

Open the `Restaurant_Sun_Prairie.blend` file first. 

files: https://www.dropbox.com/scl/fo/p2grb14lr4krtpei4lgbr/h?rlkey=utcrl6cx40azi7qjq1ghpnrq9&dl=1

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/7bf2c96f-bfbf-43eb-a9a1-fca6cc2d40ff

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 1041, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 1062, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 1094, in _execute
    ifc_exporter.export()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\export_ifc.py", line 47, in export
    self.sync_all_objects()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\export_ifc.py", line 98, in sync_all_objects
    tool.Collector.sync(obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\collector.py", line 79, in sync
    blenderbim.core.aggregate.assign_object(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\aggregate.py", line 34, in assign_object
    collector.assign(relating_obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\collector.py", line 108, in assign
    collection_collection.children.link(object_collection)
RuntimeError: Error: Could not (un)link the collection 'IfcSite/Revit_Import' because the collection 'IfcProject/My Project' is linked

```

**Comment by theoryshaw** [comment]
Here's a few simpler test files. 

open `20231205 - error on save with ifc links - simple.blend` first.

files: https://www.dropbox.com/scl/fo/6fz6g6cyiejk2886bra4h/h?rlkey=e9a6qmtdh2nre43cotl0yhs5b&dl=1

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/0b6001e7-6c59-4221-995a-c2e0e6f97976

**Comment by theoryshaw** [comment]
We still get the same error with when we link the .blend file via this way, as well. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/86c42b27-52c8-4b76-aff3-100128e81248)

**Comment by Andrej730** [comment]
Surprised we've got this far without meeting this one, fixed.
Basically it was accidentally linking object's from linked .blend file to the current .ifc file leading to those kind of issues.
