### ISSUE TITLE
 No module named 'blenderbim.bim' after migrating from Blender 3.6.

### ISSUE THREAD

**Issue by RyanJMcGowan** [IfcOpenShell/IfcOpenShell#4100]
Installation took some turns after migrating from 3.6 to 4.0.2.

Blender migrates settings, and BlenderBIM menus came up empty on 4.0.0.

Just downloaded v0.0.231104 and Blender 4.0.2 from blender.org.

Upon checking the enable checkbox, I get:
 
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\rjmil\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\__init__.py", line 39, in <module>
    import blenderbim.bim
ModuleNotFoundError: No module named 'blenderbim.bim'`

Remove button would not work, until after multiple restarts while trying different things. I can't pin down what made the remove button start to work, but that was the key to it.

Finally got BlenderBIM uninstalled, removed, and reinstalled. Currently it works and has been resolved. If anyone else experiences this issue, I think manually deleting BlenderBIM add-on may help.

Machine info:
Windows 11.
AMD 5900X
128 GB RAM

**Comment by Moult** [comment]
Yeah to be safe do an upgrade between Blender versions. Upgrading needs to be done in a particular sequence: 1) disable addon 2) restart blender 3) remove addon. The restart is important.
