### ISSUE TITLE
Error when classifying elements using bSDD

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4112]
This is the error I get:

`Python: Traceback (most recent call last):
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/tool/ifc.py", line 201, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/module/classification/operator.py", line 337, in _execute
    ifcopenshell.api.run("pset.edit_pset", tool.Ifc.get(), pset=pset, properties=properties)
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/pset/edit_pset.py", line 162, in execute
    new_props = self.add_new_properties()
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/pset/edit_pset.py", line 346, in add_new_properties
    value = self.cast_value_to_primary_measure_type(value, primary_measure_type)
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/pset/edit_pset.py", line 410, in cast_value_to_primary_measure_type
    return type_fn(value)
ValueError: could not convert string to float: ''
`

![Screenshot 2023-12-13 at 15 39 11](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/c23429a5-77cf-42db-9829-b468aa1e5e0d)

**Comment by BIMvoice** [comment]
Re-checked against the current `v0.8.0`. The original 2023 traceback came through the old `blenderbim` bSDD classification operator, which has since been rewritten, so that exact path is gone. But the underlying library behaviour still reproduces:

```python
import ifcopenshell, ifcopenshell.api.pset, ifcopenshell.api.root
f = ifcopenshell.file(schema="IFC4")
ifcopenshell.api.root.create_entity(f, ifc_class="IfcProject")
wall = ifcopenshell.api.root.create_entity(f, ifc_class="IfcWall")
pset = ifcopenshell.api.pset.add_pset(f, product=wall, name="Pset_WallCommon")
ifcopenshell.api.pset.edit_pset(f, pset=pset, properties={"ThermalTransmittance": ""})
# ValueError: could not convert string to float: ''
```

Root cause: `edit_pset.cast_value_to_primary_measure_type` calls `float(value)` directly, so an empty string for a numeric measure crashes. `None` is already handled (it purges the property), but `""` is not.

This is a design decision rather than a clear-cut bug: an empty string for an optional numeric property could reasonably be treated as "no value" (purge, consistent with the existing `None` handling) or rejected explicitly. Happy to send a PR for the "treat empty numeric as None" behaviour if that is the preferred direction.

**Comment by BIMvoice** [comment]
Opened #8251 with the fix. An empty string for a numeric property is now treated as no value (purged / cleared), the same as `None`, so a single blank value no longer crashes a bulk classification. Empty strings for string measures are preserved and a genuinely non-numeric string still raises. Regression test added for IFC2X3 and IFC4.

**Comment by BIMvoice** [comment]
Traced and fixed in #8296.

Root cause: when a property is covered by a pset template (as bSDD classification properties are), `edit_pset` uses the template's numeric `PrimaryMeasureType`. An empty value string then hit `float("")` in `cast_value_to_primary_measure_type` and raised `ValueError: could not convert string to float: ''`.

The fix stores an empty string on a numeric or boolean measure as a property with no nominal value instead of crashing, while empty strings on string measures still round-trip and genuinely invalid values still raise. Reproduced on `v0.8.0` and verified fixed, with a red-green regression test for both IFC2X3 and IFC4. Closing as resolved by #8296.

**Comment by BIMvoice** [comment]
Reopening this.

It was closed on 2026-07-05 when a fix was proposed, but that fix is still open in #8251 and has not been merged, so the behaviour is unchanged on released versions. Note #8296 was opened later for the same bug and duplicates #8251, which is the more complete fix.

Reopening so the tracker reflects the actual state, and so the linked pull request is not mistaken for something already resolved.
