### ISSUE TITLE
error: shapely.errors.GEOSException: TopologyException

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4115]
When I create the `SECTION - NORTH - LINE` drawing with 'Calculate Shapely Surfaces' selected I get the following error. 

file: https://hub.openingdesign.com/OpeningDesign/Restaurant_Sun_Prairie/src/commit/4d2b3550f29d567478c522dbe61ec0fa0d73dc06/Models/BlenderBIM/Restaurant_Sun_Prairie.ifc

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 206, in invoke
    return self.execute(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 257, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 597, in generate_linework
    internal_point = centroid if polygon.contains(centroid) else polygon.representative_point()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\shapely\geometry\base.py", line 658, in contains
    return _maybe_unpack(shapely.contains(self, other))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\shapely\decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\shapely\predicates.py", line 540, in contains
    return lib.contains(a, b, **kwargs)
shapely.errors.GEOSException: TopologyException: side location conflict at 459.51468269651554 39.61468269651548. This can occur if the input geometry is invalid.

```

**Comment by theoryshaw** [comment]
this one is just old. ha.
