### ISSUE TITLE
bSDD issues

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4126]
I get this error when I clicked on the button to Add Classification from bSDD:

`Python: Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\ifc.py", line 207, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 340, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\classification\operator.py", line 116, in _execute
    classification.Location = domain.namespace_uri
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 245, in __setattr__
    self[index] = value
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 254, in __setitem__
    self.wrapped_data.file.transaction.store_edit(self, idx, value)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 99, in store_edit
    "old": self.serialise_value(element, element[index]),
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 249, in __getitem__
    raise IndexError("Attribute index {} out of range for instance of type {}".format(key, self.is_a()))
IndexError: Attribute index 4294967295 out of range for instance of type IfcClassification
`

This happens in a newly created IFC2x3 project.

**Comment by BIMvoice** [comment]
Checked against the current `v0.8.0`. This is fixed.

The crash was `IfcClassification.Location = domain.namespace_uri` on an IFC2X3 project, where `IfcClassification` has no `Location` attribute (IFC2X3 only defines Source, Edition, EditionDate, Name), producing the out-of-range `IndexError`.

The bSDD classification operator now sets the location through `tool.Classification.set_location()` (`src/bonsai/bonsai/tool/classification.py`), which guards the schema explicitly:

```python
schema = classification.file.schema
if schema in ("IFC4", "IFC4X3"):
    classification[5] = location
    return
elif schema == "IFC2X3":
    return
```

On IFC2X3 it is now a no-op instead of a crash. Closing as resolved. Thanks.
