### ISSUE TITLE
IfcTester - Error when saving ods report

### ISSUE THREAD

**Issue by Chachiws** [IfcOpenShell/IfcOpenShell#4127]
I get the error shown below when saving an ods report with the IfcTester (update blenderBIM  231215)

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\...\PycharmProjects\2023_11_IDS Checker\gui.py", line 161, in command_button_ok
    self.validate_ifc()
  File "C:\Users\...\PycharmProjects\2023_11_IDS Checker\gui.py", line 170, in validate_ifc
    self.save_report(ods_report)
  File "C:\Users\...\PycharmProjects\2023_11_IDS Checker\gui.py", line 175, in save_report
    ods_report.to_file(filename)
  File "C:\Users\...\PycharmProjects\2023_11_IDS Checker\.venv\lib\site-packages\ifctester\reporter.py", line 398, in to_file
    element_type = ifcopenshell.util.element.get_type(failure.get("element", None))
  File "C:\Users\...\PycharmProjects\2023_11_IDS Checker\.venv\lib\site-packages\ifcopenshell\util\element.py", line 350, in get_type
    if element.is_a("IfcTypeObject"):
AttributeError: 'str' object has no attribute 'is_a'

**Comment by aothms** [comment]
Hard to say without access to the model, but sometimes these kind of errors can also be caused by schema errors in the model. I would advise running the model through validate.buildingsmart.org to detect these (or run `python -m ifcopenshell.validate <filename>` which is basically the same)

**Comment by Chachiws** [comment]
No errors on python -m ifcopenshell.validate <filename>. Maybe this error is related to my other question to add an extra column in the ods report, [https://github.com/IfcOpenShell/IfcOpenShell/issues/4037](url)

**Comment by Andrej730** [comment]
Hello! Can you please share .ifc file to reproduce the issue?
