### ISSUE TITLE
SvgSerializer error

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4130]
Error when creating a drawing from the attached file. 

[WD.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13710154/WD.ifc.txt)

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/a5876df3-8d9d-4052-ab66-18a631123640

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 206, in invoke
    return self.execute(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 257, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 537, in generate_linework
    self.serialiser.finalize()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1530, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
RuntimeError: An unknown error occurred
```

**Comment by Moult** [comment]
@aothms this one is a bit strange.

With this debug script I get an error if setUseHlrPoly(true):

```
double free or corruption (!prev)
[1]    19391 IOT instruction  python ~/Projects/ifcopenshell/debug.py
```

In Blender also with setUseHlrPoly(true) I actually don't get any error at all, but I get only three paths instead of the full washbasin (like three small random lines).

If I setUseHlrPoly(false) then I don't get that error and it works as expected ... but I don't understand when to use true or false, or when I'll get curves back (because we do expect polylines for the SVG step).

**Comment by aothms** [comment]
> but I don't understand when to use true or false, or when I'll get curves back (because we do expect polylines for the SVG step).

with `setPolygonal(True)` you will always get polygonal output. `setUseHlrPoly()` is just a matter of whether the curved edges/faces are retained internally up to the HLR elimination step.

---

My guess is that the HlrPoly algo is somewhat susceptible to invalid topology.

I see some face-face intersections below, but I think there is also some actually invalid faces, that have inner wire intersections or are otherwise invalid. At least that's what the newly built `setOnlyValid(True)` reports. (I'm pretty sure face-face intersections are not checked in the occt analyser, only topological issues).

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/d9d52416-f989-4de6-97b5-1c9accf73e7f)

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/fd8e0a2e-bd26-4646-a9e0-faab317fcb85)

setUnifyInputs(True) is also an operation that will likely change topology a lot and in case of failures should be scrutinized.

---

I guess we should work on some feature to visualize these kind of issues in the viewport so that users are not completely in the dark on what causes the issues. Note that this particular issue involves a face with inner boundaries, so we can likely not fix this without changing topology, but we can parse the invalid topologies as logged and render them in OpenGL directly. Any ideas?

**Comment by Moult** [comment]
Is there perhaps a nice way to get a list of element IDs that are invalid? That way we can highlight them and that might be a start? At least now it doesn't completely stop drawings.

**Comment by aothms** [comment]
I could add an is_valid() to ConversionResultShape which means you should be able to do something when iterating over the serializer in native output mode. Does that help?

**Comment by Moult** [comment]
Yeah, I think it'd help, but I think it needs more investigation. See #6581.
