### ISSUE TITLE
Nothing to purge anymore. :)

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4138]
Used all the following to purge the file. 
- `bim.purge_unused_profiles`
- `bim.purge_unused_types`
- `bim.purge_unused_representations`
- `bim.purge_unused_elements_by_class`

[Here](https://www.dropbox.com/scl/fo/c9imimi8zkwhw8d4wrfqs/h?rlkey=gpqb9wh6ni06arimrptwrkwv9&dl=0) are all the files saved after every class type that was purged.

It looks like there might be a ton of unused classes such a IFCPOLYGONALFACESET, IFCSTYLEDITEM, and IFCINDEXEDPOLYGONALFACE left over still--which is making the file huge. I tried to purge these classes via `bim.purge_unused_elements_by_class` but they were not processed.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/0c281a0b-c3b7-446b-bc92-f73a6224dccb)

**Comment by theoryshaw** [comment]
Also, when i try to purge 'IFCSTYLEDITEM` I get the following error...


```

Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 207, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 340, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\debug\operator.py", line 516, in _execute
    purged_elements = core.purge_unused_elements(tool.Ifc, tool.Debug, props.ifc_class_purge)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\debug.py", line 32, in purge_unused_elements
    debug.remove_unused_elements(unused_elements)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\debug.py", line 57, in remove_unused_elements
    ifcopenshell.util.element.remove_deep2(ifc_file, element)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\element.py", line 1024, in remove_deep2
    subgraph = list(ifc_file.traverse(element, breadth_first=True))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 449, in traverse
    return [entity_instance(e, self) for e in fn(inst.wrapped_data, max_levels)]
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4593, in traverse_breadth_first
    return _ifcopenshell_wrapper.file_traverse_breadth_first(self, instance, max_level)
RuntimeError: Instance #1,376,057 not found
Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 207, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 340, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\debug\operator.py", line 516, in _execute
    purged_elements = core.purge_unused_elements(tool.Ifc, tool.Debug, props.ifc_class_purge)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\debug.py", line 32, in purge_unused_elements
    debug.remove_unused_elements(unused_elements)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\debug.py", line 57, in remove_unused_elements
    ifcopenshell.util.element.remove_deep2(ifc_file, element)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\element.py", line 1024, in remove_deep2
    subgraph = list(ifc_file.traverse(element, breadth_first=True))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 449, in traverse
    return [entity_instance(e, self) for e in fn(inst.wrapped_data, max_levels)]
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4593, in traverse_breadth_first
    return _ifcopenshell_wrapper.file_traverse_breadth_first(self, instance, max_level)
RuntimeError: Instance #1,376,057 not found
```

**Comment by Andrej730** [comment]
Unused IfcStyledItem is okay since in IFC they may not be referred by any other element but still be in use - connecting representation item and some surface style.

Any examples of unused IFCPOLYGONALFACESET, IFCINDEXEDPOLYGONALFACE? Tested "Restaurant_Pewaukee_modified39_everything purged.ifc" and all they all seem to be used somewhere.
```python
set([ifc_file.get_total_inverses(f) for f in ifc_file.by_type("IFCPOLYGONALFACESET")]) # {1,2}
set([ifc_file.get_total_inverses(f) for f in ifc_file.by_type("IFCINDEXEDPOLYGONALFACE")]) # {1}
set([ifc_file.get_total_inverses(f) for f in ifc_file.by_type("IFCSTYLEDITEM")]) # {0}
 ```

**Comment by Andrej730** [comment]
> Was this umbrella object, which I manually deleted, along with a bunch of other stuff, that I no longer needed in the file. Was thus the reason I want to do the subsequent 'purge' exercise to remove any types/materials/profiles/styles/reps/etc that was associated with this umbrella afterword.

It helped uncovering a bug - basically deleting elements with fast method were leaving behind IfcStyledItems (and IfcPresentationLayerAssignments) still referring to already deleted representation items, fixed it. You can clean up those broken IfcStyledItems with the script below.

```python
import blenderbim.tool as tool
import ifcopenshell

ifc_file = tool.Ifc.get()

# use batch method as ifc_file.remove(element)
# if element refers to another element that doesn't exist
# will result in `RuntimeError: Instance #xxxx not found`
# and unsetting invalid ref attributes will also result in RuntimeError
ifcopenshell.util.element.batch_remove_deep2(ifc_file)

to_delete = set()
for item in ifc_file.by_type("IfcStyledItem"):
    try:
        item.Item
    except RuntimeError: # entity doesn't exist
        to_delete.add(item)
        print(item)

print(f"{len(to_delete)} broken IfcStyledItems were removed.")
ifc_file.to_delete.update(to_delete)
new_file = ifcopenshell.util.element.unbatch_remove_deep2(ifc_file)
tool.Ifc.set(new_file)
```

**Comment by theoryshaw** [comment]
Hi, i ran these tests again after [this ](https://github.com/IfcOpenShell/IfcOpenShell/commit/0b47fb5987abec75874ae9a963708402d508184d)commit and it still seems like there's a lot of orphaned `IFCINDEXEDPOLYGONALFACE` `IFCPOLYGONALFACESET` classes still.

Perhaps I'm missing something.

files: 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/ea80f090-b8a6-4b8f-9099-0c2c2a697364)

**Comment by Andrej730** [comment]
@theoryshaw how do you identify oprhaned `IFCINDEXEDPOLYGONALFACE` and `IFCPOLYGONALFACESET`?

I usually test it by checking inverses with this code and it shows that all of them in `Restaurant_Pewaukee10_IfcMaterialDefinition.ifc` are used by some other elements.
```python
set([ifc_file.get_total_inverses(f) for f in ifc_file.by_type("IFCPOLYGONALFACESET")]) # {1,2}
set([ifc_file.get_total_inverses(f) for f in ifc_file.by_type("IFCINDEXEDPOLYGONALFACE")]) # {1}
```

**Comment by theoryshaw** [comment]
Merry Christmas.

Intuitively the file seemed quite big, considering the little that shows up in BB, so using a text editor I just looked for entities that repeated a lot.

If you take `#1310073`, for example, which is a `IFCPOLYGONALFACESET`, it doesn't point to a `IFCSHAPEREPRESENTATION`, which I assume would be the case if it wasn't orphaned, correct?

Perhaps I missing something.

**Comment by Andrej730** [comment]
@theoryshaw `#1310073` example helped 👍 so it was still referred by IfcStyledItem, so it wasn't "completely orphaned". 

Anyway, when we delete representation we usually also remove styled items, so there was an issue. 

Turned out, we wasn't considering IfcIndexedColourMaps attached to IfcTessellatedFaceSets, if they were present we wasn't removing IfcTessellatedFaceSet and subsequently IfcStyledItem, leaving orphaned data. 

Fixed now, you can clean up your file from those facesets and styled items with the script below, it removes 112 facesets from `Restaurant_Pewaukee10_IfcMaterialDefinition.ifc`.

```python
import blenderbim.tool as tool
ifc_file = tool.Ifc.get()
import ifcopenshell

removed_facesets = 0
for element in ifc_file.by_type("IfcTessellatedFaceSet"):
    inverses = ifc_file.get_inverse(element)
    styled_items = {i for i in inverses if i.is_a("IfcStyledItem")}
    if len(inverses - styled_items) != 0:
        continue

    ifcopenshell.util.element.remove_deep2(
        ifc_file,
        element,
        also_consider=list(styled_items),
    )

    for item in styled_items:
        ifc_file.remove(item)

    removed_facesets += 1

print(f'Removed facesets: {removed_facesets}')
```

**Comment by Moult** [comment]
Awesome work @Andrej730 ! I've read through and I'm not sure if there is anything else left to be done, so closing :)
