### ISSUE TITLE
Blender IfcSverchock

### ISSUE THREAD

**Issue by ger08061959** [IfcOpenShell/IfcOpenShell#4156]
Circulair reference during load: tries to load sverchok.core in __init__ routine of sverchok. Problem doesn't exist in older versions before 3.3 (using 4.0.2, 3.6.x 3.4.x ). But current BlenderBIM and sverchock won't load with versions before 3.4. Seems to be related with the lazy_loader.

  File "/home/ger/.config/blender/4.0/scripts/addons/ifcsverchok/__init__.py", line 34, in <module>
    from sverchok.ui.nodeview_space_menu import add_node_menu
  File "/home/ger/.config/blender/4.0/scripts/addons/sverchok-master/ui/nodeview_space_menu.py", line 31, in <module>
    from sverchok.ui import presets
  File "/home/ger/.config/blender/4.0/scripts/addons/sverchok-master/ui/presets.py", line 35, in <module>
    from sverchok.utils.sv_json_import import JSONImporter
  File "/home/ger/.config/blender/4.0/scripts/addons/sverchok-master/utils/sv_json_import.py", line 17, in <module>
    from sverchok import old_nodes
  File "/home/ger/.config/blender/4.0/scripts/addons/sverchok-master/__init__.py", line 113, in <module>
    imported_modules, node_modules, core = import_sverchok()
  File "/home/ger/.config/blender/4.0/scripts/addons/sverchok-master/__init__.py", line 98, in import_sverchok
    import sverchok.core as core
ImportError: cannot import name 'core' from partially initialized module 'sverchok-master' (most likely due to a circular import) (/home/ger/.config/blender/4.0/scripts/addons/sverchok-master/__init__.py)

Saved session recovery to "/tmp/quit.blend"
Writing userprefs: "/home/ger/.config/blender/4.0/config/userpref.blend" ok
Info: Preferences saved

Blender quit

**Comment by Andrej730** [comment]
@ger08061959 couldn't reproduce it with the latest versions of bbim, ifcsverchok and sverchok. 
Can you please restart Blender and send full console output at Blender start? Perhaps there are some other errors in the way.

**Comment by ger08061959** [comment]
I had it running.  

After disabling and trying to enable the error has changed to:
(base) ger@ger-HP-Pavilion:~/blender-4.0.2-linux-x64$ ./blender
Read prefs: "/home/ger/.config/blender/4.0/config/userpref.blend"
/home/ger/blender-4.0.2-linux-x64/4.0/python/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/home/ger/blender-4.0.2-linux-x64/4.0/scripts/modules/addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "/home/ger/blender-4.0.2-linux-x64/4.0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ger/.config/blender/4.0/scripts/addons/sverchok-1_2_0/__init__.py", line 113, in <module>
    imported_modules, node_modules, core = import_sverchok()
  File "/home/ger/.config/blender/4.0/scripts/addons/sverchok-1_2_0/__init__.py", line 100, in import_sverchok
    imported_modules_ = core.init_architecture()
  File "/home/ger/.config/blender/4.0/scripts/addons/sverchok-1_2_0/core/__init__.py", line 128, in init_architecture
    import_all_modules(imported_modules, mods_bases)
  File "/home/ger/.config/blender/4.0/scripts/addons/sverchok-1_2_0/core/__init__.py", line 100, in import_all_modules
    import_modules(mods, base, imported_modules)
  File "/home/ger/.config/blender/4.0/scripts/addons/sverchok-1_2_0/core/__init__.py", line 63, in import_modules
    im = importlib.import_module('.{}'.format(m), base)
  File "/home/ger/blender-4.0.2-linux-x64/4.0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ger/.config/blender/4.0/scripts/addons/sverchok-1_2_0/dependencies.py", line 129, in <module>
    import skimage
  File "/home/ger/blender-4.0.2-linux-x64/4.0/python/lib/python3.10/site-packages/skimage/__init__.py", line 142, in <module>
    from .data import data_dir
  File "/home/ger/blender-4.0.2-linux-x64/4.0/python/lib/python3.10/site-packages/skimage/data/__init__.py", line 14, in <module>
    __getattr__, __dir__, __all__ = lazy.attach_stub(__name__, __file__)
AttributeError: module 'lazy_loader' has no attribute 'attach_stub'

Tried sverchok-master, 1.2.0 and 1.1.0, All dependencies are present.

**Comment by Andrej730** [comment]
Last error log looks unrelated to IfcSverchok. 
It looks like Sverchok is trying to load `skimage` module and there is some problem loading it. As `skimage` is located in `blender-4.0.2-linux-x64/4.0/python/lib/python3.10` and not in near-sverchok directories, I assume it's issue in unrelated to Sverchok too.

Any ideas where this `skimage` comes from? It doesn't seem to be packed with Blender by default.
You get the same error if you do `import skimage` in blender python console? If the error is the same you can reinstall `skimage` or remove/move somewhere it if you're not sure if you need it

**Comment by Moult** [comment]
Sounds like a Sverchok installation issue. Can you try post here https://github.com/nortikin/sverchok/issues ?
