### ISSUE TITLE
IfcRelSpaceBoundary : Error while adding some boundaries

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#4157]
# Description
Adding boundary by selecting IfcSpace then an IfcWall works in most case but we encountered following issue in some case. I have no idea why yet. I unfortunately cannot share the source file to reproduce the issue.

```python
Python: Traceback (most recent call last):
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/spatial/workspace.py", line 155, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/spatial/workspace.py", line 33, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/ifc.py", line 340, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/spatial/workspace.py", line 150, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/spatial/workspace.py", line 169, in hotkey_S_B
    bpy.ops.bim.add_boundary()
  File "/usr/share/blender/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/tool/ifc.py", line 207, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/ifc.py", line 340, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/boundary/operator.py", line 675, in _execute
    bpy.ops.bim.show_boundaries()
  File "/usr/share/blender/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/boundary/operator.py", line 83, in create_mesh
    shape = ifcopenshell.geom.create_shape(self.settings, surface)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/git/IfcOpenShell/src/blenderbim/blenderbim/libs/site/packages/ifcopenshell/geom/main.py", line 210, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/git/IfcOpenShell/src/blenderbim/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 1769, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to process representation item

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cyril/.config/blender/4.0/scripts/addons/blenderbim/bim/module/boundary/operator.py", line 95, in create_mesh
    shape = ifcopenshell.geom.create_shape(self.fallback_settings, inner_boundary)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/git/IfcOpenShell/src/blenderbim/blenderbim/libs/site/packages/ifcopenshell/geom/main.py", line 210, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/git/IfcOpenShell/src/blenderbim/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 1769, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: An unknown error occurred
Location: /usr/share/blender/4.0/scripts/modules/bpy/ops.py:109
Location: /usr/share/blender/4.0/scripts/modules/bpy/ops.py:109
```

**Comment by theoryshaw** [comment]
can you share a pared-down version of the file?  Maybe just the space and the wall?

**Comment by CyrilWaechter** [comment]
It might be a core issue (#4158) or BlenderBIM is creating an invalid geometry at some point.

**Comment by CyrilWaechter** [comment]
Probably due to work done on cf3ba334b7faa0d7b3c55f1f6e577ce978b90626 the issue is not triggered anymore. I wonder if we should test all `shapely.Polygon` using [is_valid](https://shapely.readthedocs.io/en/stable/reference/shapely.Polygon.html#shapely.Polygon.is_valid) method before assigning it to a `IfcRelSpaceBoundary.ConnectionGeometry`.

**Comment by CyrilWaechter** [comment]
After work on 64c711a02a00de47aca47e89b867d80bb8b4885f. Let's consider this as fixed until someone encounter another error.

Note : is_valid was not sufficient because an empty polygon is also considered as valid in shapely.
