### ISSUE TITLE
Error when trying to apply a custom Qto to an object. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4167]
I get the following error when trying to apply a custom Qto to an object. 

Custom Qset Template: [OD_Qto.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13815087/OD_Qto.ifc.txt)

```
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('','2024-01-02T19:12:29',(),(),'IfcOpenShell v0.7.0-6c9e130ca','IfcOpenShell v0.7.0-6c9e130ca','');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1=IFCPROPERTYSETTEMPLATE('3C6K_Hf6PDxB9pYsOVFLWK',$,'OD_Qto','',.QTO_OCCURRENCEDRIVEN.,'IfcObject',(#2));
#2=IFCSIMPLEPROPERTYTEMPLATE('2B6e_e7IXAguzzUDROWr0M',$,'EgressLength','',.P_SINGLEVALUE.,'IfcReal',$,$,$,$,$,.READWRITE.);
ENDSEC;
END-ISO-10303-21;
```

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f5791a6d-e1ab-4747-ab03-cf0f809cb39b

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\pset\operator.py", line 39, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 340, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\pset\operator.py", line 312, in _execute
    ifcopenshell.api.run(
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\pset\edit_qto.py", line 122, in execute
    new_properties = self.add_new_properties()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\pset\edit_qto.py", line 161, in add_new_properties
    self.file.create_entity(
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 318, in create_entity
    e = entity_instance((self.schema_identifier, type), self)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 122, in __init__
    e = ifcopenshell_wrapper.new_IfcBaseClass(*e)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 5846, in new_IfcBaseClass
    return _ifcopenshell_wrapper.new_IfcBaseClass(schema_identifier, name)
RuntimeError: Entity with name 'IfcQuantitySinglevalue' not found in schema 'IFC4'

```

**Comment by Moult** [comment]
P_SINGLEVALUE should be Q_LENGTH. I noticed the UI didn't allow managing this type of thing so it's now fixed.

**Comment by theoryshaw** [comment]
> P_SINGLEVALUE should be Q_LENGTH. 
Thank you.
