### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4200]
I don't get the following error if I delete the following light, when creating a drawing. 

file: https://www.dropbox.com/scl/fi/sxh3bwuay4107mvdsmedj/Restaurant_Sun_Prairie.ifc?rlkey=ysx4u7irut3x0j1547kjdu69g&dl=1

![2024-01-10_19-21-11_blenderBlenderblender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/76d01dce-bdbc-498f-839d-80ac64ca2ba8)

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 206, in invoke
    return self.execute(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 257, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 550, in generate_linework
    self.merge_linework_and_add_metadata(root)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 938, in merge_linework_and_add_metadata
    classes = self.get_svg_classes(element)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 899, in get_svg_classes
    value = ifcopenshell.util.selector.get_element_value(element, key)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 261, in get_element_value
    return Selector.get_element_value(element, keys)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 909, in get_element_value
    if key.match(pset_name):
TypeError: expected string or bytes-like object


```

**Comment by Moult** [comment]
This is a bit of an odd one. That light's type for some reason has a totally invalid reference. Instead of referencing a property set, it's referencing a property set relationship as well as a document information. It's just completely wrong and bizarre and I can't imagine what might've caused that to happen. Did you perhaps run some custom scripts on this file?

This'll fix it. It's a safe script to run anytime anywhere.

```python
import ifcopenshell
ifc_file = ifcopenshell.open('/your/file.ifc')
for e in ifc_file.by_type("IfcElementType"):
    is_valid = True
    for r in e.HasPropertySets or []:
        if not r.is_a("IfcPropertySetDefinition"):
            is_valid = False
    if not is_valid:
        e.HasPropertySets = [x for x in e.HasPropertySets if x.is_a("IfcPropertySetDefinition")] or None
ifc_file.write("/home/dion/fixed.ifc")
```
