### ISSUE TITLE
Error with hppfcl for IfcClash in linux

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#4238]
I'm getting the following error while trying to execute the Ifc Clash.
I'm on Linux with blender 4 and blenderbim-240120

```
Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/arun/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcclash/ifcclash.py", line 29, in <module>
    from . import collider
  File "/home/arun/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcclash/collider.py", line 19, in <module>
    import hppfcl
  File "/home/arun/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/hppfcl/__init__.py", line 35, in <module>
    from .hppfcl import *
ImportError: libboost_python310.so.1.82.0: cannot open shared object file: No such file or directory
```

**Comment by Moult** [comment]
hppfcl is now superseded by the geom.tree upgrades :)
