### ISSUE TITLE
Error when `bim.load_styles`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4245]
When i try to `bim.load_styles(style_type="IfcSurfaceStyle")` get the following error

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/fcaecdfc-04db-48bc-9e57-2a03bc2b4a79)

file: https://www.dropbox.com/scl/fi/wyd7u11aiupcpm07ab8ih/Restaurant_Pewaukee_cleaned.ifc?rlkey=zmb8a8t4ngtrl43xx32zjjwn4&dl=1

Not sure how #2059424 went missing. 

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 207, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 340, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\style\operator.py", line 406, in _execute
    core.load_styles(tool.Style, style_type=self.style_type)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\style.py", line 134, in load_styles
    style.import_presentation_styles(style_type)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\style.py", line 487, in import_presentation_styles
    new.total_elements = len(ifcopenshell.util.element.get_elements_by_style(tool.Ifc.get(), style))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\element.py", line 570, in get_elements_by_style
    if inverse.Item:
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 151, in __getattr__
    return entity_instance.wrap_value(self.wrapped_data.get_argument(idx), self.wrapped_data.file)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4895, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Instance #2,059,424 not found

```

**Comment by theoryshaw** [comment]
Nevermind, forgot about [this](https://github.com/IfcOpenShell/IfcOpenShell/issues/4138#issuecomment-1867579739) script! :)
