### ISSUE TITLE
classification.add_classification should add classification without AttributeError

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#4257]
I am trying to add a custom classification to my small IFC project created with IfcOpenShell-python 0.7.0.231218, which has been created without any errors so far.

If I add this one line 

```python
ifcopenshell.api.run("classification.add_classification", this.model, classification="MyCustomClassification")
````
as described at https://github.com/IfcOpenShell/IfcOpenShell/blob/566fd443db4153e89214928706953a4b714b57cd/src/ifcopenshell-python/ifcopenshell/api/classification/add_classification.py

I get this error message:

````
  File "/Users/kuba/dev/projects/BIM4BIPV-playground/creator.py", line 106, in create_solar_device_type
    classification = ifcopenshell.api.run("classification.add_reference", self.model, classification="MyCustomClassification")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kuba/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ifcopenshell/api/__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kuba/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ifcopenshell/api/classification/add_reference.py", line 121, in execute
    self.is_rooted = self.settings["product"].is_a("IfcRoot")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_a'
````

I suspect that this is a problem in the implementation of add_reference.py

**Comment by Andrej730** [comment]
Hello! Can you please share full example to reproduce the issue, with .ifc files?

**Comment by kurb70** [comment]
Thank you for taking a look at it.
Here is the python code and my small IFC test file.

```python
import ifcopenshell.api

model = ifcopenshell.open('./model.ifc')
ifcopenshell.api.run("classification.add_classification", model, classification="MyCustomClassification")
model.write('./model_with_classification.ifc')
```
[model.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/14081402/model.ifc.zip)

With this reduced python code I got another error I do not expect

```
Traceback (most recent call last):
  File "/Users/kuba/dev/projects/BIM4BIPV-playground/tester.py", line 4, in <module>
    ifcopenshell.api.run("classification.add_classification", model, classification="MyCustomClassification")
  File "/Users/kuba/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ifcopenshell/api/__init__.py", line 61, in run
    importlib.import_module(f"ifcopenshell.api.{usecase_path}")
  File "/Users/kuba/.pyenv/versions/3.11.7/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/kuba/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ifcopenshell/api/classification/add_classification.py", line 21, in <module>
    import ifcopenshell.util.date
  File "/Users/kuba/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ifcopenshell/util/date.py", line 21, in <module>
    from dateutil import parser
ModuleNotFoundError: No module named 'dateutil'
```

**Comment by kurb70** [comment]
BTW My "workaround" with this lines work out just fine.

```python
        # add classification entity
        classification = model.createIfcClassification(Name="MyCustomClassification")
        # and attach classification to project
        model.create_entity("IfcRelAssociatesClassification",
                                 GlobalId=ifcopenshell.guid.new(),
                                 RelatedObjects=[model.by_type("IfcProject")[0]],
                                 RelatingClassification=classification)
```

**Comment by Andrej730** [comment]
@kurb70 

>Here is the python code and my small IFC test file.

It seems your original code fail not on `classification.add_classification` but on `classification.add_reference`, so we won't be able to reproduce the original issue with this python code.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/ee211b30-8e43-455a-8e13-f7e218c60f0d)



> ModuleNotFoundError: No module named 'dateutil'

are you sure you have `dateutil` module? where you've got ifcopenshell from?
