### ISSUE TITLE
unknown error, BlenderBIM drawing output error.

### ISSUE THREAD

**Issue by JonnyManako** [IfcOpenShell/IfcOpenShell#4277]
Hi Team,

So I ran into an unknown error when publishing some drawings, this only happens when trying to publish E06, E07 and E08 (under "Section Views").

Is anyone able to shine some light on why this might be? File is in the linked question;
https://community.osarch.org/discussion/1946/help-with-an-unknown-error-blenderbim-drawing-output-error/p1?new=1

Perhaps I've stumbled across a bug?

Thanks in advance for any help, wish I had the skills to troubleshoot this myself. Will get there one day.

Python: Traceback (most recent call last):
File "C:\Users\Jonny\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 257, in execute
linework_svg = self.generate_linework(context)
File "C:\Users\Jonny\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 537, in generate_linework
self.serialiser.finalize()
File "C:\Users\Jonny\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1530, in finalize
return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
RuntimeError: An unknown error occurred

**Comment by Moult** [comment]
@aothms I think I've narrowed it down to fail on this line on SvgSerializer.cpp:

```
auto hlr_items = (drawing_name.first ? this->storey_hlr.find(drawing_name.first)->second : *hlr).build();
```

Specifically the `.build()` call (I think the `*hlr` works).

Recreate using [this file](https://community.osarch.org/uploads/editor/oa/pgp085dggtl9.ifc) with this script (in my shell I had to escape the dollar sign):

```
python debug.py 240201_3BygravePlace.ifc "1GNOaB0QX5T8\$7Es8DSI6r" "1GTjl8xpPEtxeuQC7byQjT,3ZLKbvWAn9Fg77Gg8RH57H" out.svg
```

This is the same script as before I just tweaked it to accept comma separated guids of elements. I found that in this one if I just use one element, I don't get an error, but If I try to render both those elements (i.e the wall and the roof) then I can trigger the error:

```python
import sys
import ifcopenshell
import ifcopenshell.geom
import multiprocessing
from typing import NamedTuple, List

# python standalone_drawer.py model.ifc guid_of_drawing guids,of,bad,elements output.svg


class LineworkContexts(NamedTuple):
    body: List[List[int]]
    annotation: List[List[int]]


class Drawer:
    def execute(self):
        ifc = ifcopenshell.open(sys.argv[1])
        self.camera_element = ifc.by_guid(sys.argv[2])
        # Don't use draw.main() just whilst we're prototyping and experimenting
        # Get all representation contexts to see what we're dealing with.
        target_view = ifcopenshell.util.element.get_psets(self.camera_element)["EPset_Drawing"]["TargetView"]
        contexts = self.get_linework_contexts(ifc, target_view)
        drawing_elements = set([ifc.by_guid(g) for g in sys.argv[3].split(",")])

        self.setup_serialiser(ifc, target_view)

        tree = ifcopenshell.geom.tree()
        tree.enable_face_styles(True)

        self.serialize_contexts_elements(ifc, tree, contexts, "body", drawing_elements, target_view)
        self.serialize_contexts_elements(ifc, tree, contexts, "annotation", drawing_elements, target_view)

        if self.camera_element not in drawing_elements:
            # The camera must always be included, regardless of any include/exclude filters.
            geom_settings = ifcopenshell.geom.settings(DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True)
            it = ifcopenshell.geom.iterator(geom_settings, ifc, include=[self.camera_element])
            for elem in it:
                self.serialiser.write(elem)

        self.serialiser.finalize()
        results = self.svg_buffer.get_value()
        print("results", results)

        with open(sys.argv[4], "w") as svg:
            svg.write(results)

    def get_linework_contexts(self, ifc, target_view) -> LineworkContexts:
        plan_body_target_contexts = []
        plan_body_model_contexts = []
        model_body_target_contexts = []
        model_body_model_contexts = []

        plan_annotation_target_contexts = []
        plan_annotation_model_contexts = []
        model_annotation_target_contexts = []
        model_annotation_model_contexts = []

        for rep_context in ifc.by_type("IfcGeometricRepresentationContext"):
            if rep_context.is_a("IfcGeometricRepresentationSubContext"):
                if rep_context.ContextType == "Plan":
                    if rep_context.ContextIdentifier in ["Body", "Facetation"]:
                        if rep_context.TargetView == target_view:
                            plan_body_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            plan_body_model_contexts.append(rep_context.id())
                    elif rep_context.ContextIdentifier == "Annotation":
                        if rep_context.TargetView == target_view:
                            plan_annotation_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            plan_annotation_model_contexts.append(rep_context.id())
                elif rep_context.ContextType == "Model":
                    if rep_context.ContextIdentifier in ["Body", "Facetation"]:
                        if rep_context.TargetView == target_view:
                            model_body_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            model_body_model_contexts.append(rep_context.id())
                    elif rep_context.ContextIdentifier == "Annotation":
                        if rep_context.TargetView == target_view:
                            model_annotation_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            model_annotation_model_contexts.append(rep_context.id())
            elif rep_context.ContextType == "Model":
                # You should never purely assign to a "Model" context, but
                # if you do, this is what we assume your intention is.
                model_body_model_contexts.append(rep_context.id())
                continue

        body_contexts = (
            [
                plan_body_target_contexts,
                plan_body_model_contexts,
                model_body_target_contexts,
                model_body_model_contexts,
            ]
            if target_view in ["PLAN_VIEW", "REFLECTED_PLAN_VIEW"]
            else [
                model_body_target_contexts,
                model_body_model_contexts,
            ]
        )

        annotation_contexts = (
            [
                plan_annotation_target_contexts,
                plan_annotation_model_contexts,
                model_annotation_target_contexts,
                model_annotation_model_contexts,
            ]
            if target_view in ["PLAN_VIEW", "REFLECTED_PLAN_VIEW"]
            else [
                model_annotation_target_contexts,
                model_annotation_model_contexts,
            ]
        )

        return LineworkContexts(body_contexts, annotation_contexts)

    def serialize_contexts_elements(
        self, ifc, tree: ifcopenshell.geom.tree, contexts: LineworkContexts, context_type, drawing_elements, target_view
    ):
        drawing_elements = drawing_elements.copy()
        contexts = getattr(contexts, context_type)
        for context in contexts:
            if not context or not drawing_elements:
                continue
            geom_settings = ifcopenshell.geom.settings(
                DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True, INCLUDE_CURVES=True
            )
            if ifc.by_id(context[0]).ContextType == "Plan" and "PLAN_VIEW" in target_view:
                offset = ifcopenshell.ifcopenshell_wrapper.float_array_3()
                # A 2mm Z offset to combat Z-fighting in plan or RCPs
                offset[2] = 0.002 if target_view == "PLAN_VIEW" else -0.002
                geom_settings.offset = offset
            geom_settings.set_context_ids(context)
            it = ifcopenshell.geom.iterator(geom_settings, ifc, multiprocessing.cpu_count(), include=drawing_elements)
            processed = set()
            for elem in it:
                processed.add(ifc.by_id(elem.id))
                self.serialiser.write(elem)
                tree.add_element(elem)
            drawing_elements -= processed

    def setup_serialiser(self, ifc, target_view):
        self.svg_settings = ifcopenshell.geom.settings(
            DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True, INCLUDE_CURVES=True
        )
        self.svg_buffer = ifcopenshell.geom.serializers.buffer()
        self.serialiser = ifcopenshell.geom.serializers.svg(self.svg_buffer, self.svg_settings)
        self.serialiser.setFile(ifc)
        self.serialiser.setWithoutStoreys(True)
        self.serialiser.setPolygonal(True)
        self.serialiser.setUseHlrPoly(True)
        # Objects with more than these edges are rendered as wireframe instead of HLR for optimisation
        self.serialiser.setProfileThreshold(10000)
        self.serialiser.setUseNamespace(True)
        self.serialiser.setAlwaysProject(True)
        self.serialiser.setAutoElevation(False)
        self.serialiser.setAutoSection(False)
        self.serialiser.setPrintSpaceNames(False)
        self.serialiser.setPrintSpaceAreas(False)
        self.serialiser.setDrawDoorArcs(False)
        self.serialiser.setNoCSS(True)
        self.serialiser.setElevationRefGuid(self.camera_element.GlobalId)
        self.serialiser.setScale(1 / 50)
        self.serialiser.setSubtractionSettings(ifcopenshell.ifcopenshell_wrapper.ALWAYS)
        self.serialiser.setUsePrefiltering(True)  # See #3359
        # self.serialiser.setUsePrefiltering(False)  # See #3359
        self.serialiser.setUnifyInputs(True)
        self.serialiser.setSegmentProjection(True)
        if target_view == "REFLECTED_PLAN_VIEW":
            self.serialiser.setMirrorY(True)


Drawer().execute()
```

**Comment by JonnyManako** [comment]
Good evening (or morning.. or whatever works for your part of the world!)

I have to admit I was surprised to see some of the names in this email
chain, I'm honoured that a single user like me would get the attention of
you.

Although I don't understand the programming stuff in the previous email
(I'm assuming this is one of a list of things being worked on for future
releases)
I do want to say that without a doubt BlenderBIM has enabled me to
pursue my own architectural practise which is primarily focused on social
housing and broader topics of architectural critique (two areas sorely
lacking in New Zealand).

Thank you all for sharing your hard work, it's truly appreciated!

All the best,
Jonny.

**Comment by Moult** [comment]
Hey @JonnyManako ! You got this email because you reported a bug to us back in Feb 01. It took us over a month to get around to looking at it (we've got a big backlog to work through!) but rest assured your bug report is extremely valuable and likely will help us stabilise the drawing feature for other users. You'll continue to get notifications about it until the bug is resolved. You can unsubscribe if you want too :)

**Comment by JonnyManako** [comment]
Thanks heaps Dion.

Feeling way more valued than I ever did by graphisoft.

Thanks again for your work.
I'm very glad to be a donating user of BB.
It's always nice to be able to invest in things one believes in.


Cheers,
Jonny.

**Comment by Moult** [comment]
@aothms fixed a bunch of issues related to drawing generation and I'm happy to say that this is now fixed :)
