### ISSUE TITLE
ModuleNotFoundError: No module named 'ifcopenshell.express.rules.IFC4X3_ADD2'

### ISSUE THREAD

**Issue by kulasegaram** [IfcOpenShell/IfcOpenShell#4288]
Hi, 

This error occurred when I attempted to open [this ifc file](https://github.com/IfcTruss/IfcTruss/blob/main/nbs/00_General/tutorial-with-resutls.ifc) in BlenderBIM.

```

Traceback (most recent call last):
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 168, in __getattr__
    rules = importlib.import_module(f"ifcopenshell.express.rules.{schema_name}")
  File "/USER/tarballs/blender-4.0.2-stable+v40.9be62e85b727-linux.x86_64-release/4.0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ifcopenshell.express.rules.IFC4X3_ADD2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 734, in execute
    ifc_importer.execute()
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/bim/import_ifc.py", line 237, in execute
    self.create_project()
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/bim/import_ifc.py", line 1532, in create_project
    obj = self.create_product(self.project["ifc"])
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/bim/import_ifc.py", line 1122, in create_product
    elif hasattr(element, "ObjectPlacement"):
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 173, in __getattr__
    fn = schema_path[:-4] + '.py'
TypeError: 'NoneType' object is not subscriptable
Error: Python: Traceback (most recent call last):
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 168, in __getattr__
    rules = importlib.import_module(f"ifcopenshell.express.rules.{schema_name}")
  File "/USER/tarballs/blender-4.0.2-stable+v40.9be62e85b727-linux.x86_64-release/4.0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ifcopenshell.express.rules.IFC4X3_ADD2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/bim/modTraceback (most recent call last):
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 642, in execute
    return self.finish_loading_project(context)
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 657, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "/USER/tarballs/blender-4.0.2-stable+v40.9be62e85b727-linux.x86_64-release/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 168, in __getattr__
    rules = importlib.import_module(f"ifcopenshell.express.rules.{schema_name}")
  File "/USER/tarballs/blender-4.0.2-stable+v40.9be62e85b727-linux.x86_64-release/4.0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ifcopenshell.express.rules.IFC4X3_ADD2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 734, in execute
    ifc_importer.execute()
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/bim/import_ifc.py", line 237, in execute
    self.create_project()
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/bim/import_ifc.py", line 1532, in create_project
    obj = self.create_product(self.project["ifc"])
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/bim/import_ifc.py", line 1122, in create_product
    elif hasattr(element, "ObjectPlacement"):
  File "/home/USER/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 173, in __getattr__
    fn = schema_path[:-4] + '.py'
TypeError: 'NoneType' object is not subscriptable
Location: /USER/tarballs/blender-4.0.2-stable+v40.9be62e85b727-linux.x86_64-release/4.0/scripts/modules/bpy/ops.py:109

```

The Ifc file was validated with [IfcCheckingTool](https://www.iai.kit.edu/english/1649.php).

BlenderBIM version: 0.0.240202
Blender version: 4.0.2
OS version: MX-23.2_x64 Libretto (Debian GNU/Linux 12)

**Comment by aothms** [comment]
The latest version of ifcopenshell has this resolved. Maybe you can
manually copy over it in your blender bim installation. I'm traveling so
can't provide more detail

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op za 3 feb. 2024 11:53 schreef Ashwin Kulasegaram ***@***.***

**Comment by Moult** [comment]
@aothms does the last IfcOpenBot build have the fix? https://github.com/IfcOpenBot/IfcOpenShell/commit/742a9ecd810b7d29b726660485e18e5ae53e755b#comments if so I can bump it.

**Comment by Moult** [comment]
I just realised that builds fail on Windows (ping @aothms ?) so we'll wait until that's resolved before bumping.

**Comment by aothms** [comment]
Latest build seems ok?
https://github.com/IfcOpenBot/IfcOpenShell/commit/742a9ecd810b7d29b726660485e18e5ae53e755b#comments

Op zo 4 feb 2024 om 22:12 schreef Dion Moult ***@***.***>:

**Comment by Moult** [comment]
Not yet, sorry, been a little swamped but we'll do a mad rush before the next release to get some of these sorted out.

**Comment by Moult** [comment]
This is now included in latest builds :)
