### ISSUE TITLE
[BlenderBIM] Error editing IfcWorkCalendar

### ISSUE THREAD

**Issue by Walpa** [IfcOpenShell/IfcOpenShell#4294]
The error occurs when editing IfcWorkCalendar without creating any IfcWorKSchedule /IfcTask.

```
Python: Traceback (most recent call last):
  File "/home/wal/.config/blender/4.0/scripts/addons/blenderbim/tool/ifc.py", line 207, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/wal/.config/blender/4.0/scripts/addons/blenderbim/bim/ifc.py", line 341, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/wal/.config/blender/4.0/scripts/addons/blenderbim/bim/module/sequence/operator.py", line 592, in _execute
    core.edit_work_calendar(
  File "/home/wal/.config/blender/4.0/scripts/addons/blenderbim/core/sequence.py", line 283, in edit_work_calendar
    sequence.load_task_properties()
  File "/home/wal/.config/blender/4.0/scripts/addons/blenderbim/tool/sequence.py", line 193, in load_task_properties
    task = tool.Ifc.get().by_id(item.ifc_definition_id)
  File "/home/wal/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 403, in by_id
    return self[id]
  File "/home/wal/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 391, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/home/wal/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3534, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #73,016 not found
```

This instance (`#73`) that you are looking for in Ifc does not actually exist, it was removed in a previous revision.

After creating IfcWorKSchedule /IfcTask, the IfcWorkCalendar appears edited and no longer presents the error.

![edit_work_calendar_error](https://github.com/IfcOpenShell/IfcOpenShell/assets/32360904/4d1f41fc-5ff4-48fc-8483-c5682c7b3f4d)

Blender 4.0.2
BlenderBim-240130

**Comment by Andrej730** [comment]
Couldn't reproduce it - it seems to be some problem occured in the specific Blender session and reloading .ifc should help.
Need a consistent way to reproduce the issue to investigate any further.
