### ISSUE TITLE
How to extract the 4x4 transformation matrix from a IfcBeam

### ISSUE THREAD

**Issue by smr02** [IfcOpenShell/IfcOpenShell#4301]
I've created a beam from the BlenderBim Demo Library. 
When i try to use `ifcopenshell.util.placement.get_local_placement(placement)` from [the documentation](https://blenderbim.org/docs-python/autoapi/ifcopenshell/util/placement/index.html?highlight=placement#ifcopenshell.util.placement.get_local_placement), i get the following error: 

```
>>> import ifcopenshell
>>> import blenderbim.tool as tool
>>> 
>>> model = tool.Ifc.get()
>>> beam = model.by_type('ifcbeam')[0]
>>> beam
#1222=IfcBeam('3lj9HhdVPA08y7$_8QTwu4',$,'Beam',$,$,#1231,#1235,$,$)

>>> ifcopenshell.util.placement.get_local_placement(beam)
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/smr/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/placement.py", line 102, in get_local_placement
    if placement.PlacementRelTo is None:
  File "/home/smr/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 191, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcBeam' has no attribute 'PlacementRelTo'

>>> 
>>> ifcopenshell.version
'v0.7.0-6c9e130ca'

>>> 
```

It's the same for a IfcWall

**Comment by smr02** [comment]
I found my mistake. I missed `.ObjectPlacement`
```
>>> ifcopenshell.util.placement.get_local_placement(beam.ObjectPlacement)
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
```

So i think the example in the documentation should be: 
```
element = file.by_type("IfcBeam")[0]
matrix = ifcopenshell.util.placement.get_local_placement(element.ObjectPlacement)
```

**Comment by Andrej730** [comment]
Yes, it should have .ObjectPlacement. 

We didn't updated the documentation yet:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/33979681-1d3f-452f-bf6c-e182c057bfd0)

**Comment by Moult** [comment]
Docs are updated.
