### ISSUE TITLE
If space name is a number, upon import, via the Spreadsheet Import/Export, it throws error

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4305]
If space `Name` is a number, upon import, via the Spreadsheet Import/Export, it throws the following error. 

files: https://hub.openingdesign.com/OpeningDesign/Restaurant_Pewaukee/src/commit/fdcf2e518df19847f4a571235fd2ff45e905e407/Open/Models/BlenderBIM

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b96e1817-53ed-4738-9d8e-f90945ae8ec9

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\csv\operator.py", line 275, in execute
    ifc_csv.Import(
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 385, in Import
    self.import_ods(ifc_file, table, attributes, null, empty, bool_true, bool_false)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 411, in import_ods
    self.import_pd(ifc_file, df, attributes, null, empty, bool_true, bool_false)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 422, in import_pd
    self.process_row(ifc_file, row.tolist(), headers, attributes, null, empty, bool_true, bool_false)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 442, in process_row
    ifcopenshell.util.selector.set_element_value(ifc_file, element, key, value)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 323, in set_element_value
    return setattr(element, key, value)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 245, in __setattr__
    self[index] = value
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 265, in __setitem__
    self.method_list[idx](self.wrapped_data, idx, entity_instance.unwrap_value(value))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4965, in setArgumentAsString
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsString(self, i, a)
TypeError: in method 'entity_instance_setArgumentAsString', argument 3 of type 'std::string const &'

```

**Comment by theoryshaw** [comment]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/244b5251-b9cd-4a67-9408-90e8a5f72cc0)
