### ISSUE TITLE
BlenderBim - Export ifc from selection -  Feature request

### ISSUE THREAD

**Issue by Tudjack** [IfcOpenShell/IfcOpenShell#4316]
It would be nice to have a feature to be able to extract selected objects to an output ifc.
Similar to "ExtractElements" recipe from Ifc Patch but for specific selected objects, not for a full subset of elements.

**Comment by theoryshaw** [comment]
You might know this already.  The following is one way to do it...

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/31a14460-6b50-4a19-ac51-94773b030a7a

**Comment by Tudjack** [comment]
Wow! Thanks!
I would have never found this out.
Anyway, a separate button which does all the above would be less counterintuitive. Just a suggestion.
But thanks a lot for this method, I will definitely try it out!

**Comment by Tudjack** [comment]
Unfortunately I am receiving the following error:


Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 734, in execute
    ifc_importer.execute()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\import_ifc.py", line 240, in execute
    self.create_collections()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\import_ifc.py", line 1515, in create_collections
    self.create_aggregate_and_nest_collections()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\import_ifc.py", line 1559, in create_aggregate_and_nest_collections
    elif element.IsNestedBy:
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 191, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC2X3.IfcReinforcingBar' has no attribute 'IsNestedBy'. Did you mean: 'IsDefinedBy'?

**Comment by theoryshaw** [comment]
Can you share the file, or a parred-down version of it, if sensitive?

**Comment by theoryshaw** [comment]
Btw, i think i was incorrect in thinking you could create a new file...
https://community.osarch.org/discussion/1968/how-to-create-a-new-ifc-file-with-just-a-few-select-objects-from-another-ifc-file#latest

I just tested, and it doesn't seem to work, like i thought it would.  Sorry for the misinformation.

**Comment by Tudjack** [comment]
Unfortunately I can't share the file, it's under a very strict NDA.
It's a large file as well, thousands of reinforcing bars and couplers. 
Just want to find a way to create a "mini ifc" out of a few selected bars.

**Comment by Tudjack** [comment]
the only way I managed to extract the bars I want in a separate ifc was to delete all other elements not in my selection.
And it basically took me the whole day. It's incredibly slow, sometimes Blender crashes as well. Did not expect deleting ifc elements to cause heavy CPU processing.

**Comment by Moult** [comment]
Have you tried using the ExtractElements parch recipe? I think it does what you're asking (although the graphical integration isn't as slick as it could be)

**Comment by Tudjack** [comment]
I tried it pasting the GlobaID of one element into the Query, but I don't know how to paste in multiple GuID's.
I don't know how to write the arguments for this.

**Comment by Tudjack** [comment]
Little update. It actually works, just pasting the Guid's separated by commas. The problem I faced was actually for some elements which give me an error when trying to export. It's something with this ifc file.

I will paste the error here:


Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\patch\operator.py", line 93, in execute
    output = ifcpatch.execute(
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcpatch\__init__.py", line 79, in execute
    patcher.patch()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcpatch\recipes\ExtractElements.py", line 63, in patch
    self.add_element(element)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcpatch\recipes\ExtractElements.py", line 68, in add_element
    new_element = self.append_asset(element)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcpatch\recipes\ExtractElements.py", line 85, in append_asset
    return ifcopenshell.api.run("project.append_asset", self.new, library=self.file, element=element)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\project\append_asset.py", line 98, in execute
    return self.append_product()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\project\append_asset.py", line 169, in append_product
    ifcopenshell.api.run(
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\type\assign_type.py", line 213, in execute
    "OwnerHistory": ifcopenshell.api.run("owner.create_owner_history", self.file),
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\owner\create_owner_history.py", line 109, in execute
    return self.file.create_entity(
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 337, in create_entity
    e[idx] = arg
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 263, in __setitem__
    self.wrapped_data.setArgumentAsNull(idx)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4940, in setArgumentAsNull
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsNull(self, i)
RuntimeError: Attribute not set

**Comment by Andrej730** [comment]
> Little update. It actually works, just pasting the Guid's separated by commas. The problem I faced was actually for some elements which give me an error when trying to export. It's something with this ifc file.

This error looks like file has some invalid ifc - it seems like it doesn't have either IfcApplication or IfcPersonAndOrganization to initialize IfcOwnerHistory.

As for the original feature request, it can indeed be done by generating query listing selected guids in Search section and then use it for ExtractElements IfcPatch recipe. I'm not sure if we should add special "extract from selection" button to this recipe UI since then it would make sense copying the entire Search UI there.

**Comment by Tudjack** [comment]
For the moment I coded my own plugin which does this. It's quite basic, stores the guids from selection as a string delimited by commas and pasted it into the IfcPatch recipe. I needed something then. It worked, but as I said that particular ifc had some issues.
I wonder why does it have to have either IfcApplication or IfcPersonAndOrganizaton set? Why does it need IfcOwnerHistory?

**Comment by Andrej730** [comment]
> I wonder why does it have to have either IfcApplication or IfcPersonAndOrganizaton set? Why does it need IfcOwnerHistory?

I assume your file was in IFC2X3 and in IFC2X3 OwnerHistory on IfcRoot elements is not optional.

See: https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifckernel/lexical/ifcroot.htm
