### ISSUE TITLE
Issue installing BlenderBim on Blender <3.3

### ISSUE THREAD

**Issue by marszulc** [IfcOpenShell/IfcOpenShell#4319]
Hi,
I encounter errors while trying to load blenderbim 240214.
```
Traceback (most recent call last):
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\drawing\ui.py", line 364, in draw
    DocumentsData.load()
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\drawing\data.py", line 197, in load
    documents = cls.count_documents()
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\drawing\data.py", line 215, in count_documents
    for d in tool.Ifc.get().by_type("IfcDocumentInformation"):
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\tool\ifc.py", line 40, in get
    return IfcStore.get_file()
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\ifc.py", line 77, in get_file
    IfcStore.path = bpy.context.scene.BIMProperties.ifc_file
AttributeError: 'Scene' object has no attribute 'BIMProperties'
```
I needed to reinstall bbim because of fix on IfcTester (applicability facet on Attributes).

**Comment by marszulc** [comment]
Another errors appeared during another try of installation:
```
Modules Installed (blenderbim) from '\\\\citrix-vdi\\XenDesktopProfiles$\\pd6402\\Downloads\\blenderbim-240214-py310-win.zip' into 'C:\\Users\\pd6402\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
Traceback (most recent call last):
  File "\\citrix-vdi\XenDesktopProfiles$\pd6402\Documents\blender-3.2.2-windows-x64\3.2\scripts\modules\addon_utils.py", line 371, in enable
    mod.register()
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\__init__.py", line 44, in register
    blenderbim.bim.register()
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\__init__.py", line 204, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "ShapeAspect" registration error: 'name' StringProperty could not register (see previous error)

Python: Traceback (most recent call last):
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\drawing\gizmos.py", line 486, in poll
    and obj.data.BIMMeshProperties.ifc_parameters.get("IfcExtrudedAreaSolid/Depth") is not None
AttributeError: 'Mesh' object has no attribute 'BIMMeshProperties'

```

**Comment by Moult** [comment]
Can you try with a clean environment? See the FAQ https://blenderbim.org/docs/users/installation.html#faq

**Comment by marszulc** [comment]
Tried but without success
I got:
```
Modules Installed (blenderbim) from '\\\\citrix-vdi\\XenDesktopProfiles$\\pd6402\\Downloads\\blenderbim-240214-py310-win.zip' into 'C:\\Users\\pd6402\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
Traceback (most recent call last):
  File "\\citrix-vdi\XenDesktopProfiles$\pd6402\Documents\blender-3.2.2-windows-x64\3.2\scripts\modules\addon_utils.py", line 371, in enable
    mod.register()
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\__init__.py", line 44, in register
    blenderbim.bim.register()
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\__init__.py", line 204, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "ShapeAspect" registration error: 'name' StringProperty could not register (see previous error)

Python: Traceback (most recent call last):
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\ui.py", line 806, in poll
    return tool.Blender.is_tab(context, "FM")
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\tool\blender.py", line 76, in is_tab
    return context.screen.BIMTabProperties.tab == tab
AttributeError: 'Screen' object has no attribute 'BIMTabProperties'
Python: Traceback (most recent call last):
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\ui.py", line 791, in poll
    return tool.Blender.is_tab(context, "FM")
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\tool\blender.py", line 76, in is_tab
    return context.screen.BIMTabProperties.tab == tab
AttributeError: 'Screen' object has no attribute 'BIMTabProperties'

```

also:
```
Python: Traceback (most recent call last):
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\drawing\ui.py", line 406, in draw
    SheetsData.load()
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\drawing\data.py", line 68, in load
    "total_sheets": cls.total_sheets(),
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\module\drawing\data.py", line 79, in total_sheets
    return len([d for d in tool.Ifc.get().by_type("IfcDocumentInformation") if d.Scope == "SHEET"])
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\tool\ifc.py", line 40, in get
    return IfcStore.get_file()
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blenderbim\bim\ifc.py", line 77, in get_file
    IfcStore.path = bpy.context.scene.BIMProperties.ifc_file
AttributeError: 'Scene' object has no attribute 'BIMProperties'

```
and similar ones...

**Comment by marszulc** [comment]
Sorry, it seems it is a problem with my machine.
The same errors appear when I try to install old release.

It has also problems with uninstalling bbim:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110668180/963434f5-82fc-4038-a447-3d2ef12cbd94)
(i can remove it manually but anyway still can`t get it to work after installing)

**Comment by Andrej730** [comment]
@marszulc hi! check the instructions uninstalling the addon:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/fcd6fac5-188a-48f4-8995-6a0508b22b29)

**Comment by marszulc** [comment]
Hi @Andrej730
Ok it seems that I need to restart blender to remove bbim even if it wasn`t succesfully enabled.
Restarting helps to remove it.
But still no success enabling.

**Comment by Andrej730** [comment]
Was able to reproduce the issue on Blender 3.1. The full traceback was:
```
TypeError: 'search' is an invalid keyword argument for StringProperty()
Exception in module register(): C:\Users\Andrej\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\__init__.py
Traceback (most recent call last):
  File "\blender-3.1.2+stable.cc66d1020c3b\3.1\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\__init__.py", line 44, in register
    blenderbim.bim.register()
  File "\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\__init__.py", line 204, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "ShapeAspect" registration error: 'name' StringProperty could not register (see previous error)
```
Fixed it as currently we state on [download page](https://blenderbim.org/download.html) that we support Blender 3.1+ but the main development and testing currently happens on Blender 3.6 and 4.0. So please consider updating Blender to more recent version as it will be more stable for Blender itself and BBIM.

**Comment by marszulc** [comment]
Confirmed, works on blender 4

**Comment by Moult** [comment]
No harm in the fix, but I'll update the download page to require Blender 3.5 and up. Based on https://blenderbim.org/docs/devs/system_support.html we support the latest 3 versions.

**Comment by Moult** [comment]
Website updated :) Note that in the next release you will need Blender 4.1.
