### ISSUE TITLE
A redundant `=` is saved with .json file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4323]
saving the json for...

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/bc5449db-a5e1-4b8e-a7a7-aba5bc706e34)

creates...

`"query": "IfcMaterial, query:\"OD_Materials.In_Finish_Schedule\"=TRUE",` 
(because when this is loaded again, and run, the following error happens)

i think it should create...

`"query": "IfcMaterial, query:\"OD_Materials.In_Finish_Schedule\"TRUE",`

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 68, in _call_userfunc
    return f(children)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 540, in query
    self.elements = set(filter(filter_function, self.elements))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 538, in filter_function
    return self.compare(get_element_value(element, keys), comparison, value)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 609, in compare
    value = int(value)
ValueError: invalid literal for int() with base 10: '=TRUE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\csv\operator.py", line 201, in execute
    results = ifcopenshell.util.selector.filter_elements(
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 269, in filter_elements
    transformer.transform(filter_elements_grammar.parse(query))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 105, in transform
    return self._transform_tree(tree)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 101, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 92, in _transform_children
    yield self._transform_tree(c)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 101, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 92, in _transform_children
    yield self._transform_tree(c)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 101, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 92, in _transform_children
    yield self._transform_tree(c)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 101, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 92, in _transform_children
    yield self._transform_tree(c)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 102, in _transform_tree
    return self._call_userfunc(tree, children)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 72, in _call_userfunc
    raise VisitError(tree.data, tree, e)
lark.exceptions.VisitError: Error trying to process rule "query":

invalid literal for int() with base 10: '=TRUE'

```

**Comment by milinddethe15** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/28099ddc8fedde30182b10d13f847539dc4737a6/src/blenderbim/blenderbim/tool/search.py#L79-L82
can we just remove the `{comparison}` for query?

**Comment by Moult** [comment]
@milinddethe15 try it and find out :)

**Comment by milinddethe15** [comment]
I tried to solve this by removing the `comparison` from query fitler by
```py
elif ifc_filter.type == "query":
                    keys = cls.wrap_value(ifc_filter, ifc_filter.name)
                    _, value = cls.get_comparison_and_value(ifc_filter)
                    filter_group_query.append(f"query:{keys}{value}")
```
but I got :
 ```py
Python: Traceback (most recent call last):
File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/bim/module/search/operator.py", line 176, in execute
results = ifcopenshell.util.selector.filter_elements(
File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/selector.py", line 269, in filter_elements
transformer.transform(filter_elements_grammar.parse(query))
File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/lark/lark.py", line 333, in parse
return self.parser.parse(text, start=start)
File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/lark/parser_frontends.py", line 194, in parse
return self._parse(text, start)
File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/lark/parser_frontends.py", line 54, in _parse
return self.parser.parse(input, start, *args)
File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/lark/parsers/earley.py", line 292, in parse
to_scan = self._parse(stream, columns, to_scan, start_symbol)
File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/lark/parsers/xearley.py", line 138, in _parse
to_scan = scan(i, to_scan)
File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/lark/parsers/xearley.py", line 115, in scan
raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan))
lark.exceptions.UnexpectedCharacters: No terminal defined for ',' at line 1 col 12

ifcMaterial, query:"OD_Materials.In_Finish_Schedule
```
later then I modifed the func get_comparison_and_value to return nothing for query:
```py
@classmethod
    def get_comparison_and_value(cls, ifc_filter):
        if ifc_filter.value.startswith("!="):
            return ("!=", cls.wrap_value(ifc_filter, ifc_filter.value[2:].strip()))
        elif ifc_filter.type == "query":
            return ("", cls.wrap_value(ifc_filter, ifc_filter.value.strip()))
        return ("=", cls.wrap_value(ifc_filter, ifc_filter.value.strip()))
```
but got this: 
```py
Python: Traceback (most recent call last):
  File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/bim/module/search/operator.py", line 178, in execute
    results = ifcopenshell.util.selector.filter_elements(
  File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/selector.py", line 269, in filter_elements
    transformer.transform(filter_elements_grammar.parse(query))
  File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/lark/lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/lark/parser_frontends.py", line 194, in parse
    return self._parse(text, start)
  File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/home/mint/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/lark/parsers/earley.py", line 310, in parse
    raise UnexpectedEOF(expected_tokens)
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: 
	* EQUAL
	* __ANON_8
	* __ANON_7
	* __ANON_6
	* BANG
	* MORETHAN
	* LESSTHAN
```
can someone help me debug this?

**Comment by Moult** [comment]
Sounds like you shouldn't have removed it. But do you understand why? Which error messages can you understand and which don't you understand?

**Comment by milinddethe15** [comment]
Ig it is lark parser grammer, I cant modify it, which isnt matching with changes made to query. I need to revert the changes and find another way...?
