### ISSUE TITLE
`imperial_length({{value}}, 4, "inch")` seems to throw an error when 'Export IFC to ODS'

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4328]
When trying to 'Export IFC to ODS' get the following error. 

Is this the correct syntax?
`imperial_length({{value}}, 4, "inch")`

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/1e741bb2-dc9b-4eb6-a7f1-cca065297365)

```

Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\csv\operator.py", line 225, in execute
    ifc_csv.export(
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 122, in export
    self.format_results(formatting, attributes, null)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 247, in format_results
    row[index] = ifcopenshell.util.selector.format(format_query.replace("{{value}}", row[index]))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 257, in format
    return FormatTransformer().transform(format_grammar.parse(query))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 194, in parse
    return self._parse(text, start)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parsers\earley.py", line 292, in parse
    to_scan = self._parse(stream, columns, to_scan, start_symbol)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 138, in _parse
    to_scan = scan(i, to_scan)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 115, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan))
lark.exceptions.UnexpectedCharacters: No terminal defined for ')' at line 1 col 33

imperial_length("3.5", 4, "inch")
                                ^

Expecting: {'COMMA'}
```

**Comment by Moult** [comment]
This is a syntax error. The imperial length takes either 2 or 4 arguments.

If you only supply 2 arguments, it assumes you're giving it input in feet and want the output in feet too. So `imperial_length(3.5, 4)` means you want to first round 3.5 ft to the nearest 1/4 inch then format it as feet. So you get 3' 6".

If you supply 4 arguments, then you have the flexibility to choose both the input and output format. So it's `imperial_length(number, precision, input_format, output_format)`. e.g.:

```
imperial_length("123.123", 2, "inch", "foot") == 10' - 3"
imperial_length("123.123", 2, "inch", "inch") == 123"
```
