### ISSUE TITLE
IfcDirection was saved corrupted by nan values

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4329]
Is there anyway to recover [this](https://hub.openingdesign.com/OpeningDesign/Tradesman_Warehouse_TI/src/commit/32a6c4ab56fee5847097a5e0c6f5dd4f4689e58d/Open/Models/BlenderBIM/Tradesman_Warehouse_TI.ifc) file?

Unfortunately we were working on this file all day, and when we closed it, we couldn't open it again.  

All our versions, saved via the file syncing throughout the day, were corrupt too. :\

```
Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 734, in execute
    ifc_importer.execute()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 251, in execute
    self.create_elements()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 839, in create_elements
    self.create_generic_elements(self.elements)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 864, in create_generic_elements
    products = self.create_pointclouds(elements)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 1048, in create_pointclouds
    pointcloud = self.create_pointcloud(product, representation)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 1055, in create_pointcloud
    placement_matrix = self.get_element_matrix(product)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 1757, in get_element_matrix
    result = ifcopenshell.util.placement.get_local_placement(element.ObjectPlacement)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\placement.py", line 106, in get_local_placement
    return np.dot(parent, get_axis2placement(placement.RelativePlacement))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\placement.py", line 61, in get_axis2placement
    z = np.array(placement.Axis.DirectionRatios if placement.Axis else (0, 0, 1))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 151, in __getattr__
    return entity_instance.wrap_value(self.wrapped_data.get_argument(idx), self.wrapped_data.file)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4895, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Argument is not a number
Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 734, in execute
    ifc_importer.execute()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 251, in execute
    self.create_elements()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 839, in create_elements
    self.create_generic_elements(self.elements)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 864, in create_generic_elements
    products = self.create_pointclouds(elements)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 1048, in create_pointclouds
    pointcloud = self.create_pTraceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 630, in load_handler
    self.finish_loading_project(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 657, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 734, in execute
    ifc_importer.execute()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 251, in execute
    self.create_elements()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 839, in create_elements
    self.create_generic_elements(self.elements)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 864, in create_generic_elements
    products = self.create_pointclouds(elements)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 1048, in create_pointclouds
    pointcloud = self.create_pointcloud(product, representation)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 1055, in create_pointcloud
    placement_matrix = self.get_element_matrix(product)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\import_ifc.py", line 1757, in get_element_matrix
    result = ifcopenshell.util.placement.get_local_placement(element.ObjectPlacement)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\placement.py", line 106, in get_local_placement
    return np.dot(parent, get_axis2placement(placement.RelativePlacement))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\placement.py", line 61, in get_axis2placement
    z = np.array(placement.Axis.DirectionRatios if placement.Axis else (0, 0, 1))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 151, in __getattr__
    return entity_instance.wrap_value(self.wrapped_data.get_argument(idx), self.wrapped_data.file)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4895, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Argument is not a number
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113
```

**Comment by Andrej730** [comment]
Sure! Replace those lines in the file (they are a bit a part from each other in .ifc file)

```
#3012222=IFCDIRECTION((-nan(ind).,-nan(ind).,-nan(ind).));
#3012223=IFCDIRECTION((0.00870694874044573,-0.999962093803376,0.));

...

#3014248=IFCDIRECTION((-nan(ind).,-nan(ind).,-nan(ind).));
#3014249=IFCDIRECTION((0.59999387739339,0.80000459191835,0.));

```

with lines
```
#3012222=IFCDIRECTION((0.,0.,1.));
#3012223=IFCDIRECTION((1.,0.,0.));

...

#3014248=IFCDIRECTION((0.,0.,1.));
#3014249=IFCDIRECTION((1.,0.,0.));
```

Those are the direction vectors from the placements of 2 elements below. Replacing the lines will reset their rotation but file will work.
`#3014246=IFCVIRTUALELEMENT('2GV$3IkqXFFOHpSPiV6cLk',$,'BL|A$C537C4680_mesh_',$,$,#3014251,#3014254,$);`
`#3012220=IFCWALL('0rUOZ3$Lv9URMsfZDjoNoU',$,'BL|A$C2ee6ad36_curve_',$,'CAD IMPORT',#3012225,#3012251,$,.USERDEFINED.);`

The issue was that somehow corrupted nan values got into those direction vectors. First time I see this 🤔

**Comment by brunopostle** [comment]
nan numbers appeared in #4057, it was caused by a matrix normalisation function that did a division by zero. I fixed the one that that was bothering me in a8078e3

**Comment by brunopostle** [comment]
There are two unresolved bugs in #4057, one is that IfcOpenShell is capable of writing 'nan' in a float, the other is that IfcOpenShell segfaults when parsing a nan in an IFC file

**Comment by theoryshaw** [comment]
Thanks Guys!

**Comment by theoryshaw** [comment]
@chopinregis and I will keep an eye out for steps to reproduce.

**Comment by theoryshaw** [comment]
Just to log here. 

The workflows that we were doing at the time, included importing a dxf, converting the 2d curves to meshes, and then assigning an ifcclass.

**Comment by Moult** [comment]
Reopening, because I suspect through careful inspection of the code in #4057 we can figure it out.

**Comment by Andrej730** [comment]
In the case #4057 it was caused by trying to find a cross product between parallel vectors, so if this is the case the main suspects are `local2global`, `global2local`, `a2p`.

**Comment by aothms** [comment]
> There are two unresolved bugs in https://github.com/IfcOpenShell/IfcOpenShell/issues/4057, one is that IfcOpenShell is capable of writing 'nan' in a float, the other is that IfcOpenShell segfaults when parsing a nan in an IFC file

I'm addressing point 1. But point 2 I cannot reproduce, they seem to even persist all the way through python, which surprises me a bit:

e.g on some random file I modified in a text editor:

```
>>> f[2]
#2=IfcDirection((nan,0.0,1.0))
>>> f[488]
#488=IfcBuildingStorey('1xS3BCk291UvhgP2dvNMQJ',#1,'Level 2',$,$,#29,$,$,.ELEMENT.,nan)
>>> f[488].Elevation
nan
>>> type(f[488].Elevation)
<class 'float'>
```

**Comment by brunopostle** [comment]
Too many bugs...

The file with nan values that segfaults is attached to #4070 (and I can still reproduce with IfcOpenShell 0.7 from 2024-03-19)
