### ISSUE TITLE
BlenderBIM - Moving an object corrupts the ifc

### ISSUE THREAD

**Issue by Tudjack** [IfcOpenShell/IfcOpenShell#4330]
I manged to break an ifc model by moving an object. 
I have to mention this model is a reinforcement model exported from Tekla (I think)
Just wanted to move a bar around.
After save and re-open, I get the following error:

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 734, in execute
    ifc_importer.execute()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\import_ifc.py", line 231, in execute
    self.calculate_model_offset()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\import_ifc.py", line 615, in calculate_model_offset
    return self.guess_false_origin()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\import_ifc.py", line 644, in guess_false_origin
    offset_point = self.get_offset_point()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\import_ifc.py", line 664, in get_offset_point
    placement = ifcopenshell.util.placement.get_local_placement(element.ObjectPlacement)[:, 3][0:3]
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\placement.py", line 106, in get_local_placement
    return np.dot(parent, get_axis2placement(placement.RelativePlacement))
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\placement.py", line 63, in get_axis2placement
    o = placement.Location.Coordinates
AttributeError: 'NoneType' object has no attribute 'Coordinates'

**Comment by Tudjack** [comment]
Also very interesting, if I try to delete one of the objects(re-bar) I get the following error as well:


Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 508, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 341, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 548, in _execute
    tool.Geometry.delete_ifc_object(obj)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\geometry.py", line 124, in delete_ifc_object
    ifcopenshell.api.run("root.remove_product", tool.Ifc.get(), product=element)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\root\remove_product.py", line 97, in execute
    ifcopenshell.api.run("geometry.remove_representation", self.file, **{"representation": representation})
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\remove_representation.py", line 50, in execute
    [presentation_layer_assignments.add(s) for s in subelement.LayerAssignment]
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 191, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC2X3.IfcAxis2Placement3D' has no attribute 'LayerAssignment'. Did you mean: 'LayerAssignments'?

**Comment by Andrej730** [comment]
@Tudjack hello! Can you please share some .ifc example to reproduce the issue?

**Comment by Tudjack** [comment]
Here is the original ifc and the corrupted one after moving a bar in the original and saving.

[ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/14309740/ifc.zip)

**Comment by Andrej730** [comment]
Also related commit a2ff63f9e

Should be fixed now, thank you for reporting this.
