### ISSUE TITLE
BBIM - 3d grids and images not saved in Ifc file

### ISSUE THREAD

**Issue by jes-r** [IfcOpenShell/IfcOpenShell#4331]
Hi, 

I have an Ifc project made in BlenderBIM following tutorials. 
The issue: I change the 3D grids, even delete them, but when I reopen file they're back to where they were. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/160035772/af2fe724-b8b8-4a58-b1a5-5ae606f77161)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/160035772/fa7b3103-cb32-4b68-8b97-68167963d8ae)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/160035772/62d1c536-4369-48ad-8dad-59f2a72e92f6)

Image 1: original situation;
Image 2: changed and saved situation;
Image 3: reopened situation; The slab is saved but the grids are not.

My image I used as tracing (not in screenshots) is a little bit different. It doesn't save at all, I have to import and scale it every time I reopen the file.

The file (is this how it should be shared? First time user here): 
[github_issue_3d_grids.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/14310962/github_issue_3d_grids.ifc.txt)

Is this how it should be or am I missing something?
I'm using Blender 3.6.8 with BlenderBIM 240215 (thought it was the same case in other versions but not sure).

Thanks!

**Comment by theoryshaw** [comment]
I tried to delete one of the gridlines, and got the following error. 

As a work around, try to delete in this way...

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/5a841685-4746-4e70-a47d-64fc5561b2b5



```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\root\operator.py", line 186, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 341, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\root\operator.py", line 209, in _execute
    tool.Geometry.delete_ifc_object(obj)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 124, in delete_ifc_object
    ifcopenshell.api.run("root.remove_product", tool.Ifc.get(), product=element)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\root\remove_product.py", line 228, in execute
    history = self.settings["product"].OwnerHistory
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 191, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcGridAxis' has no attribute 'OwnerHistory'

```

**Comment by theoryshaw** [comment]
If relatively new to BB, would also recommend posting questions on https://community.osarch.org/categories/general

Perhaps for your image problem, can you do a videocast, and ask the question on the osarch forum.  That way, other users can learn too.

**Comment by jes-r** [comment]
It works, though only if I save and open the .blend file. The .Ifc file still has it loaded after this workaround. Moving the grids also works if I save and load the .blend file. But shouldn't the grids be stored in the ifc file? 

Will try that forum!

What types of question should be posted on OsArch vs here then? Thx!

**Comment by theoryshaw** [comment]
It's up to you really, but there's more users on the osarch forum, and i've found with new users, a lot of the bugs they encounter, are common, and just a user not currently knowing the way to approach things. 

Github tends to be more geared toward developers.  

There's no hard fast rules, however, in my opinion. 

...

In general, as a new user, it's not recommended to even save the .blend file, only the .ifc file... since there's often syncing problems. 
see faq#5: https://blenderbim.org/docs/users/installation.html#faq

**Comment by sboddy** [comment]
@jes-r Still an issue?

**Comment by jes-r** [comment]
@sboddy I will try it later this week, don't have time right now! Same goes for the other older issues

**Comment by sboddy** [comment]
@jes-r Ping! Did you get chance?

**Comment by theoryshaw** [comment]
closing, please open if still an issue.
