### ISSUE TITLE
IfcTester - errors with <info> section

### ISSUE THREAD

**Issue by marszulc** [IfcOpenShell/IfcOpenShell#4333]
Hi, 
after installing blender 4 and fresh release of bbim, i can't run any ids without error 'Unexpected child with tag 'ids:description' at position 5.'
I can`t figure out whats wrong.
Tried to put quotation marks around the description but it doesnt help.

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\tester\operator.py", line 57, in execute
    specs = ifctester.ids.open(props.specs)
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifctester\ids.py", line 35, in open
    get_schema().decode(filepath, strip_namespaces=True, namespaces={"": "http://standards.buildingsmart.org/IDS"})
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\xmlschema\validators\schemas.py", line 2023, in decode
    for result in self.iter_decode(source, path, schema_path, validation, *args, **kwargs):
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\xmlschema\validators\schemas.py", line 2009, in iter_decode
    yield from xsd_element.iter_decode(elem, validation, **kwargs)
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\xmlschema\validators\elements.py", line 752, in iter_decode
    for result in content_decoder.iter_decode(obj, validation, **kwargs):
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\xmlschema\validators\groups.py", line 1074, in iter_decode
    for result in xsd_element.iter_decode(child, validation, **kwargs):
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\xmlschema\validators\elements.py", line 752, in iter_decode
    for result in content_decoder.iter_decode(obj, validation, **kwargs):
  File "C:\Users\pd6402\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\xmlschema\validators\groups.py", line 1102, in iter_decode
    raise error
xmlschema.validators.exceptions.XMLSchemaChildrenValidationError: failed validating <Element '{http://standards.buildingsmart.org/IDS}info' at 0x0000028F67360630> with XsdGroup(model='sequence', occurs=[1, 1]):

Reason: Unexpected child with tag 'ids:description' at position 5.

Schema:

  <xs:complexType xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:sequence>
          <xs:element name="title" type="xs:string" />
          <xs:element name="copyright" type="xs:string" minOccurs="0" />
          <xs:element name="version" type="xs:string" minOccurs="0" />
          <xs:element name="description" type="xs:string" minOccurs="0" />
          <xs:element name="author" minOccurs="0">
              <xs:simpleType>
                  <xs:restriction base="xs:string">
                      <xs:pattern value="[^@]+@[^\.]+\..+" />
                  </xs:restriction>
              </xs:simpleType>
          </xs:element>
          <xs:element name="date" type="xs:date" minOccurs="0" />
          <xs:element name="purpose" type="xs:string" minOccurs="0" />
          <xs:element name="milestone" type="xs:string" minOccurs="0" />
      </xs:sequence>
  </xs:complexType>

Instance:

  <info xmlns="http://standards.buildingsmart.org/IDS">
      <title>IDS0_XXXXX_Wiele</title>
      <copyright>MSzulc</copyright>
      <author>marcin.szulc@porr.pl</author>
      <date>2024-02-16</date>
      <description>General checks for basic model informations</description>
      <purpose>Subcontractor model validation</purpose>
      <milestone>KM3</milestone>
  </info>

Path: /ids/info
```

**Comment by Moult** [comment]
The schema by buildingSMART requires your metadata to be in a particular order. I.e. first title, copyright, then version, then description, then order, etc.

Edit your IDS file to follow that order, e.g. move up your description tag.

Let's keep this bug open in case we're guilty of not following this order.
