### ISSUE TITLE
Python API ifcopenshell.api.run doesn't work with IFC2x3

### ISSUE THREAD

**Issue by Licini** [IfcOpenShell/IfcOpenShell#4340]
The python API `ifcopenshell.api.run` throws error when the file is IFC2X3
To reproduce the error:

```python
import ifcopenshell
import ifcopenshell.api

print(ifcopenshell.version)

file = ifcopenshell.file(schema="IFC2X3")
ifcopenshell.api.run("root.create_entity", file, ifc_class="IfcProject", name="Default Project")
```

```
Traceback (most recent call last):
  File "d:\Github\compas_ifc\temp\bug.py", line 7, in <module>
    ifcopenshell.api.run("root.create_entity", file, ifc_class="IfcProject", name="Default Project")
  File "C:\Users\leoch\anaconda3\envs\ifc\lib\site-packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\leoch\anaconda3\envs\ifc\lib\site-packages\ifcopenshell\api\root\create_entity.py", line 78, in execute
    "OwnerHistory": ifcopenshell.api.run("owner.create_owner_history", self.file),
  File "C:\Users\leoch\anaconda3\envs\ifc\lib\site-packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\leoch\anaconda3\envs\ifc\lib\site-packages\ifcopenshell\api\owner\create_owner_history.py", line 109, in execute
    return self.file.create_entity(
  File "C:\Users\leoch\anaconda3\envs\ifc\lib\site-packages\ifcopenshell\file.py", line 337, in create_entity
    e[idx] = arg
  File "C:\Users\leoch\anaconda3\envs\ifc\lib\site-packages\ifcopenshell\entity_instance.py", line 260, in __setitem__
    self.wrapped_data.setArgumentAsNull(idx)
  File "C:\Users\leoch\anaconda3\envs\ifc\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4939, in setArgumentAsNull
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsNull(self, i)
RuntimeError: Attribute not set
```

The version is `v0.7.0-f0e03c79d`, using the build `py39-win64`

**Comment by Moult** [comment]
This is not an error. In IFC2x3 you are expected to setup your own owner history data. The documentation explaining this is here: https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/owner/create_owner_history/index.html

See the sample code of how you are required to setup ownership prior to creating elements.

**Comment by aothms** [comment]
> Would be helpful if the error message could hint what is the missing compulsory attribute.

I agree. On multiple levels actually.

- RuntimeError: Attribute not set

This message is somehow very unclear. It should be something like `ValueError: non optional attribute IFC2X3.IfcRoot.OwnerHistory cannot be null.`

- In the high level API we should properly catch this error (or check before invocation) and tell the user to properly populate a user.

Contributions are very welcome on this front :) if you can find the time.
