### ISSUE TITLE
Unable to duplicate gridlines, after a save, and reopen. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4344]
Unable to duplicate grid lines, after a save, and reopen. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c0ca6599-edb8-4418-9133-18e1a9d430ce

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 721, in execute
    return OverrideDuplicateMove.execute_duplicate_operator(self, context, linked=False)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 732, in execute_duplicate_operator
    context.view_layer.objects.active = self.new_active_obj
RuntimeError: Error: ViewLayer 'ViewLayer' does not contain object 'IfcGridAxis/03.003'

```

**Comment by theoryshaw** [comment]
this seems to have been fixed!
