### ISSUE TITLE
Have the `IfcElementAssembly` empty turn on too, if at least one object in the assembly, is turned on as well. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4361]
when `bim.activate_drawing` is run, it would be nice to have the `IfcElementAssembly` empty turn on too, if at least one object in the assembly, is turned on as well. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/34b89570-2556-4cc8-a984-eabc5b5e0cfe)

**Comment by theoryshaw** [comment]
Getting the following error since https://github.com/IfcOpenShell/IfcOpenShell/commit/3848a2113622b32ca9827f7ae4ae6f47fb2b768b

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 269, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 548, in generate_linework
    self.serialize_contexts_elements(ifc, tree, contexts, "body", drawing_elements, target_view)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 484, in serialize_contexts_elements
    it = ifcopenshell.geom.iterator(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 111, in __init__
    raise ValueError("include and exclude need to be an aggregate of IfcProduct")
ValueError: include and exclude need to be an aggregate of IfcProduct

```
