### ISSUE TITLE
error when linking IFC

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4380]
```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 841, in execute
    bpy.ops.bim.load_link(filepath=filepath)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 901, in execute
    self.link_ifc()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 943, in link_ifc
    self.link_blend(blend_filepath)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 905, in link_blend
    with bpy.data.libraries.load(filepath, link=True) as (data_from, data_to):
OSError: load: D:\Dropbox\Codeberg\Loftsgordon_Residence\Open\Models\BlenderBIM\ifc scans\attic.ifc.cache.blend failed to open blend file
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113

```

**Comment by Moult** [comment]
There is probably an error even further up than that which is the real error. I haven't fully packaged this yet.

**Comment by Moult** [comment]
Can you paste the whole error if there is more error btw?

**Comment by theoryshaw** [comment]
That's really it.

Did the following...

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b7c688f2-db81-4a54-a588-0670baec2e60




```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 841, in execute
    bpy.ops.bim.load_link(filepath=filepath)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 901, in execute
    self.link_ifc()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 943, in link_ifc
    self.link_blend(blend_filepath)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 905, in link_blend
    with bpy.data.libraries.load(filepath, link=True) as (data_from, data_to):
OSError: load: C:\Users\Ryan Schultz\Desktop\2.ifc.cache.blend failed to open blend file
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113

```

and

```
bpy.ops.bim.link_ifc(filepath="C:\\Users\\Ryan Schultz\\Desktop\\2.ifc", files=[{"name":"2.ifc", "name":"2.ifc"}], directory="C:\\Users\\Ryan Schultz\\Desktop\\")

```

**Comment by Moult** [comment]
There may be more error messages if you open up the console rather than only looking in that window.

In any case try after the next build :)

**Comment by Moult** [comment]
Ping @aothms I noticed that Python 3.6 builds for Linux/Win are failing in the latest bot build https://github.com/IfcOpenBot/IfcOpenShell/commit/eaa2aa05a43b9c372263376032b0b4faad740816#comments - is this expected?

**Comment by aothms** [comment]
Yes, this is expected. The python code base (`from __future__ import annotations`) is no longer compatible.

(The py36 OSX builds are actually older variants that are not cleaned up properly!!)

**Comment by Moult** [comment]
OK, I don't think there is any real interest in trying to resurrect support for it, so are you OK with me removing those download links from the install table matrix?

**Comment by aothms** [comment]
Please! 3.6 went EOL 2021-12-23 and in fact 3.7 is also already EOL. https://devguide.python.org/versions/

**Comment by Moult** [comment]
I think this is now fixed.

**Comment by theoryshaw** [comment]
Is the fix for this one reliant on a new IfcOpenBot build?

**Comment by Moult** [comment]
Nope. Does it work for you @theoryshaw ?

**Comment by theoryshaw** [comment]
No one fortunately, I get the same error.
