### ISSUE TITLE
Error while deleting entity

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#4385]
Hi, I get the following error while trying to delete any entity. I have to again select the same entity second time and delete to actually delete the entity.

I have tried this with multiple files and multiple entities too. Same error.

Using BlenderBim 0.0.240301 on Linux
```
Python: Traceback (most recent call last):
  File "/home/arun/.config/blender/4.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 509, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/arun/.config/blender/4.0/scripts/addons/blenderbim/bim/ifc.py", line 341, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/arun/.config/blender/4.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 549, in _execute
    tool.Geometry.delete_ifc_object(obj)
  File "/home/arun/.config/blender/4.0/scripts/addons/blenderbim/tool/geometry.py", line 130, in delete_ifc_object
    tool.Blender.remove_data_block(obj.data)
  File "/home/arun/.config/blender/4.0/scripts/addons/blenderbim/tool/blender.py", line 459, in remove_data_block
    getattr(bpy.data, collection_name).remove(
RuntimeError: Error: Mesh '15/1237' must have zero users to be removed, found 1 (try with do_unlink=True parameter)

```

**Comment by theoryshaw** [comment]
Haha... i came to report the same issue. ha.

If I just try to 'Delete' the following object from [this](https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/776ee8859b24e8113e80cf7ef1e362e0e9429665/Open/Models_and_CAD/BlenderBIM/Highland_Haven.ifc) file, I get the following error. 

If i use `IFC delete` it seems to work. 



https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/78bcf02b-c8bb-44cf-bbc5-44f0995c4b0b

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 530, in invoke
    return self.execute(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 509, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 341, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 549, in _execute
    tool.Geometry.delete_ifc_object(obj)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\geometry.py", line 130, in delete_ifc_object
    tool.Blender.remove_data_block(obj.data)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\blender.py", line 459, in remove_data_block
    getattr(bpy.data, collection_name).remove(
RuntimeError: Error: Mesh '24/3830622' must have zero users to be removed, found 1 (try with do_unlink=True parameter)

```

**Comment by theoryshaw** [comment]
I think it's related to https://github.com/IfcOpenShell/IfcOpenShell/commit/0c2a3ff4000da22ef521446382264050633be15f
