### ISSUE TITLE
poll errors with clipping plane gizmo

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#4392]
Hi,
I 'm getting multiple errors while searching and filtering for elements.
Using BlenderBIM 0.0.240303 on Linux
```
Python: Traceback (most recent call last):
  File "/home/arun/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/gizmo.py", line 37, in poll
    and obj.name.startswith("ClippingPlane")
AttributeError: 'NoneType' object has no attribute 'name'
Python: Traceback (most recent call last):
  File "/home/arun/.config/blender/4.0/scripts/addons/blenderbim/bim/module/project/gizmo.py", line 60, in refresh
    if self.obj != context.object or self.last_mw != context.object.matrix_world:
AttributeError: 'NoneType' object has no attribute 'matrix_world'

```

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/58535690/5b685631-2fa6-46d9-8c20-ba16e04f7ec4)

**Comment by Andrej730** [comment]
Hi! Fixed the error messages, it wasn't related to search section and wasn't affecting it.
