### ISSUE TITLE
`toposort` is not included in BlenderBIM

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#4399]
Error occurs running Optimise IfcPatch from BlenderBIM. Not sure if Optimise was experimental and this is why `toposort` wasn't included, creating an issue to keep track of it.

```
Traceback (most recent call last):
  File "\blenderbim\bim\module\patch\operator.py", line 93, in execute
    output = ifcpatch.execute(
  File "\blenderbim\libs\site\packages\ifcpatch\__init__.py", line 79, in execute
    patcher.patch()
  File "\blenderbim\libs\site\packages\ifcpatch\recipes\Optimise.py", line 55, in patch
    from toposort import toposort_flatten as toposort
ModuleNotFoundError: No module named 'toposort'
Error: Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'toposort'
```

Current workaround for users - install `toposort` from BBIM Debug section:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/9bfb80a6-8df0-4de6-96df-870b39d2278a)

**Comment by Moult** [comment]
Optimize is currently experimental and too slow to be practical so it isn't used. It's OK not to bundle it for now.

**Comment by aothms** [comment]
I recall this from earlier discussion. I think the problem is not toposort, but `inst.get_info(recursive=True)`, which as you move up the dependency stack gets to serialize deeper and deeper trees to native python objects. The simple solution should be to use recursive=False and serialize entity instance references to something like `{instance: 123}`. Because of toposort we don't need to recursively flatten to values because we know that dependencies have already been folded into unique instances are earlier iterations.
