### ISSUE TITLE
Link external IFC file fails if IFC file is on separate disk partition. 

### ISSUE THREAD

**Issue by bdamay** [IfcOpenShell/IfcOpenShell#4411]
I tried to use the link IFC feature and it appears that i get an error while opening ifc linked file.  apparently something to do with cache.blend file

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/16347726/c3ebb86f-badb-4438-804f-c0538970861d)

```
Python: Traceback (most recent call last):
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 907, in execute
    self.link_ifc()
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 949, in link_ifc
    self.link_blend(blend_filepath)
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 911, in link_blend
    with bpy.data.libraries.load(filepath, link=True) as (data_from, data_to):
OSError: load: C:\Users\bdama\Documents\GitHub\blenderbim-tutos-fr\TUTO_1\TUTO_1.ifc.cache.blend failed to open blend file


```

My BBIM version is 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/16347726/d8c32605-f234-493d-9753-e9a56e53536f)

**Comment by ppaawweeuu** [comment]
You can not directly link ifc file.
See more here: https://youtu.be/aMcYy5Oomv0?si=VtHas5ODBHMbFWqy

**Comment by theoryshaw** [comment]
Per [this](https://github.com/IfcOpenShell/IfcOpenShell/commit/002112dd5049c25b8478c5eb7c8ea4a5a52813e6) commit, I think you can link .IFC directly now. 

However, i think there's a bug...
https://github.com/IfcOpenShell/IfcOpenShell/issues/4380

Not sure if a new IfcOpenBot build is required however.  If so, I don't think there has been one, since this commit.

**Comment by Moult** [comment]
Can you share your model? Privately dion@thinkmoult.com if need be.

**Comment by bdamay** [comment]
@Moult You can find the ifc model i try to link here https://github.com/bdamay/blenderbim-tutos-fr/tree/main/TUTO_1
(TUTO_1.ifc). Steps to reproduce, I opened a new empty ifc project, saved it on disk and went to link ifc - that's where i got the error. Tell me if you need some more informations or want me to test something.

@ppaawweeuu, thanks for yout reply, but as @theoryshaw said, with latest releases of bbim one should be able to directly link ifc file (and that's really cool!) but it appears to fail with me..

**Comment by bdamay** [comment]
I tried it on another machine and seems to have same problems but i managed to have a bit more log information that might be helping. (On this machine my document dir is not located on the same drive than appdata and looks like it tells me it cannot transfer the file from one drive to the other?) 

In particular this line ``` OSError: [WinError 17] Impossible de déplacer le fichier vers un lecteur de disque différent: 'C:\\Users\\bdama\\AppData\\Local\\Temp\\tmpoeo7vio2' -> 'E:/Users/bdama/Documents/GitHub/blenderbim-tutos-fr/TUTO_1/TUTO_1.ifc.cache.sqlite'``` 

``` 
Read prefs: "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
Blender 4.0.2 (hash 9be62e85b727 built 2023-12-05 13:01:12)
Read prefs: "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
Processing E:/Users/bdama/Documents/GitHub/blenderbim-tutos-fr/TUTO_1/TUTO_1.ifc
Finished opening
Traceback (most recent call last):
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 1208, in execute
    ifcpatch.write(db, self.db_filepath)
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcpatch\__init__.py", line 102, in write
    os.rename(output, filepath)
OSError: [WinError 17] Impossible de déplacer le fichier vers un lecteur de disque différent: 'C:\\Users\\bdama\\AppData\\Local\\Temp\\tmpoeo7vio2' -> 'E:/Users/bdama/Documents/GitHub/blenderbim-tutos-fr/TUTO_1/TUTO_1.ifc.cache.sqlite'
Error: Python: Traceback (most recent call last):
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 1208, in execute
    ifcpatch.write(db, self.db_filepath)
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcpatch\__init__.py", line 102, in write
    os.rename(output, filepath)
OSError: [WinError 17] Impossible de déplacer le fichier vers un lecteur de disque différent: 'C:\\Users\\bdama\\AppData\\Local\\Temp\\tmpoeo7vio2' -> 'E:/Users/bdama/Documents/GitHub/blenderbim-tutos-fr/TUTO_1/TUTO_1.ifc.cache.sqlite'
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "C:\Users\bdama\AppData\Local\Temp\tmpqvomzjg0.py", line 9, in <module>
    run()
  File "C:\Users\bdama\AppData\Local\Temp\tmpqvomzjg0.py", line 5, in run
    bpy.ops.bim.load_linked_project(filepath="E:/Users/bdama/Documents/GitHub/blenderbim-tutos-fr/TUTO_1/TUTO_1.ifc", false_origin="0,0,0")
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 1208, in execute
    ifcpatch.write(db, self.db_filepath)
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcpatch\__init__.py", line 102, in write
    os.rename(output, filepath)
OSError: [WinError 17] Impossible de déplacer le fichier vers un lecteur de disque différent: 'C:\\Users\\bdama\\AppData\\Local\\Temp\\tmpoeo7vio2' -> 'E:/Users/bdama/Documents/GitHub/blenderbim-tutos-fr/TUTO_1/TUTO_1.ifc.cache.sqlite'
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109

An error occurred while processing your IFC.
Traceback (most recent call last):
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 907, in execute
    self.link_ifc()
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 949, in link_ifc
    self.link_blend(blend_filepath)
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 911, in link_blend
    with bpy.data.libraries.load(filepath, link=True) as (data_from, data_to):
OSError: load: E:\Users\bdama\Documents\GitHub\blenderbim-tutos-fr\TUTO_1\TUTO_1.ifc.cache.blend failed to open blend file
Error: Python: Traceback (most recent call last):
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 907, in execute
    self.link_ifc()
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 949, in link_ifc
    self.link_blend(blend_filepath)
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 911, in link_blend
    with bpy.data.libraries.load(filepath, link=True) as (data_from, data_to):
OSError: load: E:\Users\bdama\Documents\GitHub\blenderbim-tutos-fr\TUTO_1\TUTO_1.ifc.cache.blend failed to open blend file
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 843, in execute
    bpy.ops.bim.load_link(filepath=filepath, false_origin=self.false_origin)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 907, in execute
    self.link_ifc()
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 949, in link_ifc
    self.link_blend(blend_filepath)
  File "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 911, in link_blend
    with bpy.data.libraries.load(filepath, link=True) as (data_from, data_to):
OSError: load: E:\Users\bdama\Documents\GitHub\blenderbim-tutos-fr\TUTO_1\TUTO_1.ifc.cache.blend failed to open blend file
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109
```

**Comment by bdamay** [comment]
OK then i tried it moving my file to C:\Temp and it seems to be ok in that case
```
Read prefs: "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
Blender 4.0.2 (hash 9be62e85b727 built 2023-12-05 13:01:12)
Read prefs: "C:\Users\bdama\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
Processing C:/Temp/TUTO_1.ifc
Finished opening
Finished writing property database
Finished 0.11977410316467285
Info: Total files 0 | Changed 0 | Failed 0
Info: Saved "TUTO_1.ifc.cache.blend"

Blender quit
Finished linking 1 IFCs 2.726407766342163 
```

**Comment by aothms** [comment]
Some background here: os.rename expects to be able to do an atomic move, data on disk stays the same and a reference in the volume hierarchy is updated. When you move across partitions the data needs to move as a well, because a partition is a contiguous segment on disk, so it is not atomic. Maybe the code should be updated to do a `shutil.move()`, which can handle both cases.

**Comment by Moult** [comment]
@bdamay can you try that solution? Change from os.remove to shutil.move? If it works, a PR would be very appreciated :) Also I wonder if you grep the codebase for os.remove anywhere else we should replace it too.

**Comment by bdamay** [comment]
Yes. I'll look at that tomorrow.

**Comment by bdamay** [comment]
@Moult I inspected the code this morning. It appears that os.rename() is inside ifcpatch that i don't have in my scoped code on my dev machine. (I think i have to add it to the symlinks i originally set for my local machine) .

That said, i wonder if, in that particular case, it wouldn't be good to store the cache.blend files in sort of temp/cache app location that would be on the same partition of the disk ?  I'm not sure if having this file in the ifc project dir is mandatory. 
in link_ifc, i would replace 
`        blend_filepath = self.filepath + ".cache.blend"
        h5_filepath = self.filepath + ".cache.h5"`
by something like
`        blend_filepath = blender_temp/cache_dir + ".cache.blend"
        h5_filepath =blender_temp/cache_dir  + ".cache.h5"`

Do we have this kind of disk location in BlenderBIM ?

**Comment by Moult** [comment]
The reason the cache file are stored next to the IFC is so that next time it can auto-detect it and load the cache (whereas the temp folder will be purged).

**Comment by bdamay** [comment]
OK, looks like a good reason, i'll track os.rename in ifcpatch then. i'll let you know when it's done. Have a good day

**Comment by bdamay** [comment]
@Moult I pushed a PR. 
Also did grep the code to find other occurences of os.rename found in the source code 
There are some but it looks like they all rename from/to same disk, so i didn't change them

**Comment by bdamay** [comment]
Forgot to say it solved the issue :-)

**Comment by bdamay** [comment]
Hi @theoryshaw, i resync with IfcOpenshel v0.7.0 but it seems i can't reproduce this error home. (i tried links from 2 different drives and it works fine)
Is this a IFC link you're trying to achieve ?

**Comment by theoryshaw** [comment]
Hi Benoit, yes via...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/370752da-f6af-428a-8663-1d00cf210f50)

From the error it looks like its a problem with different drives.  All my apps are on C:, but my files are in D:

...

Just to test, i relocated my test files to the C: drive, and it worked.

**Comment by theoryshaw** [comment]
Did more tests...

When i use absolute path it works, but when I use relative path, i get that error...
```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 855, in execute
    filepath = os.path.relpath(filepath, bpy.path.abspath("//")).replace("\\", "/")
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\ntpath.py", line 747, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'D:', start on mount 'C:'

```

**Comment by bdamay** [comment]
@theoryshaw 
Looks like something else than what i had myself. 
Code is:
`            if self.use_relative_path:
                filepath = os.path.relpath(filepath, bpy.path.abspath("//")).replace("\\", "/")
`
Looks like npath python library if failing with relative path coming from two different disk. (that makes sense to me) 

The question I have is why is the operator property "use_relative_path" is set as True in your case, if you browse to another disk location. (default value for property is False), you may have something checked somewhere that i don't know of (..yet) 

line 842 i read
`    use_relative_path: bpy.props.BoolProperty(name="Use Relative Path", default=False)
`
