### ISSUE TITLE
Drawing creation and printing fails on demo project (Duplex apartment)

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#4414]
Testing drawing creation and printing fails on the below test .ifc project:

OS: Mac/Windows 11 (same error on both OS)
BB version: blenderbim-240308
Same result after demo project is upgraded form IFC 2x3 to IFC4

Steps to reproduce:
Open demo project (linked below)
Create drawing action produces the following error
Drawing is created

https://github.com/buildingSMART/Sample-Test-Files/blob/master/IFC%202x3/Duplex%20Apartment/Duplex_A_20110907.ifc

**Error on drawing creation**

Python: Traceback (most recent call last):
File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/[operator.py](http://operator.py/)", line 74, in execute
IfcStore.execute_ifc_operator(self, context)
File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/[ifc.py](http://ifc.py/)", line 336, in execute_ifc_operator
result = getattr(operator, "_execute")(context)
File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/[operator.py](http://operator.py/)", line 135, in _execute
core.add_drawing(
File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/core/[drawing.py](http://drawing.py/)", line 194, in add_drawing
element = [drawing.run](http://drawing.run/)_root_assign_class(
File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/[drawing.py](http://drawing.py/)", line 865, in run_root_assign_class
return blenderbim.core.root.assign_class(
File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/core/[root.py](http://root.py/)", line 70, in assign_class
[root.run](http://root.run/)_geometry_add_representation(
File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/[root.py](http://root.py/)", line 204, in run_geometry_add_representation
return blenderbim.core.geometry.add_representation(
File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/core/[geometry.py](http://geometry.py/)", line 45, in add_representation
representation = [ifc.run](http://ifc.run/)(
File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/tool/[ifc.py](http://ifc.py/)", line 32, in run
return [ifcopenshell.api.run](http://ifcopenshell.api.run/)(command, IfcStore.get_file(), **kwargs)
File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/init.py", line 66, in run
result = usecase_class(ifc_file, **settings).execute()
File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/geometry/add_[representation.py](http://representation.py/)", line 70, in execute
if self.settings["context"].ContextType == "Model":
AttributeError: 'NoneType' object has no attribute 'ContextType'

**Error on print:**

Python: Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 212, in invoke
    return self.execute(context)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 235, in execute
    self.drawing = self.file.by_id(drawing_id)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 411, in by_id
    return self[id]
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 396, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
  File "/Users/user/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3573, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #0 not found

**Comment by Moult** [comment]
That sample model doesn't contain any geometric subcontexts. Drawing generation requires subcontexts since that's how we handle 3D, 2D, body, and annotation, and so on.

**Comment by Moult** [comment]
More reading https://github.com/buildingSMART/Sample-Test-Files/issues/137
