### ISSUE TITLE
BBim - Install fails on 24.03.11 - Windows 10 Blender 4.0.2

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#4418]
When attempting to install BlenderBim 240311

on Windows10 
Blender 4.0.2

When checking the activate box
It gives this error:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\__init__.py", line 41, in <module>
    import blenderbim.bim
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\__init__.py", line 21, in <module>
    from blenderbim.tool.boundary import Boundary
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\boundary.py", line 23, in <module>
    from blenderbim.bim.module.geometry.helper import Helper
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\geometry\__init__.py", line 20, in <module>
    from . import ui, prop, operator
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 26, in <module>
    import ifcopenshell.util.unit
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\unit.py", line 596
    if unit.is_a("IfcSIUnit")':
                             ^
SyntaxError: unterminated string literal (detected at line 596)

the error is not present on BBim 240308

**Comment by Andrej730** [comment]
Fixed with 6e8de29
