### ISSUE TITLE
Bbim 240308 - print drawing fails after editing camera pset

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#4419]
On Blender 240308
Blender 4.0.2
Windows 10

When editing the camera pset in any way it wont print and will give an error

example:

1) Add a camera
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/53997b48-f178-4034-a56d-5f73c7370fcf)

2) exclude object from camera
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/2ce63987-c651-401a-88b7-bab35a3eb8fa)

3) activate camera (reflects exclusion)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/ed15a1fc-eb71-499d-ba9d-050ce68fde9a)

4) print drawing:

it gives this error:

Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 263, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 526, in generate_linework
    self.serialize_contexts_elements(ifc, tree, contexts, "body", drawing_elements, target_view)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 471, in serialize_contexts_elements
    self.serialiser.write(elem)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1559, in write
    return _ifcopenshell_wrapper.SvgSerializer_write(self, *args)
RuntimeError: Invalid cast

**Comment by theoryshaw** [comment]
Try this...
Might be related to https://github.com/IfcOpenShell/IfcOpenShell/issues/4389

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/73c61cc4-bc0b-4c34-bf05-fdebc0571304

**Comment by Plae-Blue-Dot** [comment]
> Try this... Might be related to #4389
> 
>  2024-03-07_10-22-27_blenderBlenderblender.mp4

This did the trick! Thanks Theoryshaw! same issue, I'll have to avoid the the newer releases for production for now

**Comment by Moult** [comment]
The fix for this should now be available in the latest builds.

**Comment by Plae-Blue-Dot** [comment]
Thanks @Moult !
