### ISSUE TITLE
Error when refreshing linked aggregate

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4435]
When i try to refresh the linked aggregates in the following file, it gives the following error. 

file: 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/55d93753-ba02-4344-9e98-c914f4789fb9

```

Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1103, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1267, in _execute
    original_names = get_original_names(element)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1137, in get_original_names
    index = pset['Index']                    
TypeError: 'NoneType' object is not subscriptable


```

ping @brunoperdigao

**Comment by brunoperdigao** [comment]
@theoryshaw Please try running this script and test again to see if the issue is solved: https://gist.github.com/brunoperdigao/6b0f0d255a9d4eebd8faf9b8f778329d

The problem is that one of the aggregate had the "BBIM_Linked_Aggregate" pset missing. Hard to know what might have caused this.

**Comment by theoryshaw** [comment]
Very cool.. that seems to have worked.  

I 'think' i know what caused it. 

I think it was something like this.  See video.

[aggregate psets.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/14623949/aggregate.psets.ifc.txt)

It would be nice, however, if doing something like this was possible--as i've found myself doing this quite a bit in the current workflow. That is, being able to remove sub aggregates from a parent aggregate, and have them still be linked aggregates. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d4f6021c-ead1-426e-8287-f64d02013e0e

**Comment by brunoperdigao** [comment]
I can implement this, but it has limitations. For exemple:
I have these two structures that are linked, and the beams are a sub-aggregate:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/ba97852c-e611-4fff-811f-a2ab75b680d4)

If I unassign the Beams from the Structure, remove two beams and refresh, it will work. Which means that Beams is still connected to Beams_1:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/ac4afbe7-9c23-46e3-a8ef-fb88d30184a1)

However, when I refresh the Structure, I will remove the Beams_1, because the Structure doesn't have a sub-aggregate anymore, so this will be reflected in Structure_1:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/6ad6d1fe-b113-4937-9a20-b6450aa9fd50)

So, I would have to also unassing Beams_1 from Structure_1. That way, all the links will remain.

**Comment by theoryshaw** [comment]
This is okay, if i'm following you correctly--as most times, if not all, if I 'remove' a sub aggregate from a parent, i delete that parent afterward. 
It's kinda like 'exploding' the aggregate. :)

Perhaps this could be a future roadmap, to do this is one gesture.
