### ISSUE TITLE
Lark UnexpectedCharacters Error

### ISSUE THREAD

**Issue by c-mellueh** [IfcOpenShell/IfcOpenShell#4448]
I tried streaming a big file with 
```python
ifcopenshell.open("xxx",should_stream=True)
```

but i get an error at this function at the third line: 
```python
    def get_parent_group(cls, group: ifcopenshell.stream_entity) -> list[entity_instance]:
        parent_assignment = []
        for assignement in group.HasAssignments:
            if not assignement.is_a("IfcRelAssignsToGroup"):
                continue
            parent_assignment.append(assignement)

        if not parent_assignment:
            return []
        return [assignment.RelatingGroup for assignment in parent_assignment]
```

this is my error:
```python
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\SOM-Toolkit\lib\site-packages\lark\lexer.py", line 665, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\SOM-Toolkit\lib\site-packages\lark\lexer.py", line 598, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches '0' in the current parser context, at line 1 col 1

034,16.5667870378224,1.77328632092201));
^
Expected one of: 
	* HASH
```

this is the corresponding line in the ifc-file:
```
#18091990=IFCCARTESIANPOINT((21.4931305509034,16.5667870378224,1.77328632092201));
```

**Comment by aothms** [comment]
I've said this before, but would be good to unify with https://github.com/IfcOpenShell/step-file-parser/blob/master/main.py which is a more direct translation of the official spf grammar. Are you interested in having a look?

**Comment by c-mellueh** [comment]
Unfortunately I know nothing about Lark and Step parsing.

**Comment by BIMvoice** [comment]
This is resolved on the current `v0.8.0`. Streaming (`ifcopenshell.open(path, should_stream=True)`) no longer throws `lark.UnexpectedCharacters` on coordinate lines.

Verified with the exact `IfcCartesianPoint` from your report:

```python
sf = ifcopenshell.open(path, should_stream=True)
sf.by_type('IfcCartesianPoint')[0].Coordinates
# (21.4931305509034, 16.5667870378224, 1.77328632092201)   -- parses fine
```

Accessing inverse attributes on a stream entity (the `group.HasAssignments` / `IsGroupedBy` path where you hit it) also works. The Lark-based streaming parser has since been replaced, so the `No terminal matches` error no longer occurs. Safe to close.

**Comment by BIMvoice** [comment]
@c-mellueh a correction to my earlier note, and I owe you an apology for it: this is NOT fully resolved. My previous "resolved" comment was based on an incomplete check (I only tested a file with LF line endings, which parses fine).

Streaming a file whose line endings differ from the running interpreter's `os.linesep` (for example a CRLF-authored file, which matches your Windows case) still reproduces the exact `lark` `UnexpectedToken` you reported. Root cause: the streaming line-offset index in `stream.py` assumed every line ends with `os.linesep`, so the accumulated byte offset drifts by a byte per line and a later `seek()` lands mid-token.

PR #8911 fixes it by deriving the offsets from the file's own `tell()` instead, which correctly handles LF, CRLF, bare-CR, and mixed line endings within one file. Added regression tests that reproduce your exact traceback against the old code and pass against the fix.

Thanks for your patience, and sorry for the premature all-clear.
