### ISSUE TITLE
IfcClash error

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4469]
`Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcclash/ifcclash.py", line 29, in <module>
    from . import collider
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcclash/collider.py", line 19, in <module>
    import hppfcl
ModuleNotFoundError: No module named 'hppfcl'
`

<img width="1097" alt="Screenshot 2024-03-26 at 15 52 46" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/4c05d253-1ae9-426b-a0f7-889b52f537ee">

@Andrej730 can you do anything about this, please?

Blender 4.0 with latest daily BBIM build.

**Comment by BIMvoice** [comment]
That's awesome news Dion! Noted, thank you!

**Comment by BIMvoice** [comment]
Hey @Moult , I still get an error so I cannot run/use it yet. Is this a quick fix?

`Python: Traceback (most recent call last):
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/module/clash/operator.py", line 274, in execute
    clasher.clash()
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcclash/ifcclash.py", line 43, in clash
    self.process_clash_set(clash_set)
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcclash/ifcclash.py", line 49, in process_clash_set
    source["ifc"] = self.load_ifc(source["file"])
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcclash/ifcclash.py", line 112, in load_ifc
    ifc = ifcopenshell.open(path)
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/__init__.py", line 138, in open
    raise exc(msg)
ifcopenshell.Error: Unable to parse IFC SPF header
`

**Comment by BIMvoice** [comment]
That error has been fixed. Now I get this one:

`Python: Traceback (most recent call last):
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/module/clash/operator.py", line 275, in execute
    clasher.export()
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcclash/ifcclash.py", line 150, in export
    return self.export_bcfxml()
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcclash/ifcclash.py", line 162, in export_bcfxml
    np.array(clash["position"]),
KeyError: 'position'
`

**Comment by Moult** [comment]
BCF support is not yet ready, in the meantime you can export JSON. (just change the filename to have a .json extension)

**Comment by BIMvoice** [comment]
Oh lol. That did the trick. Awesome, thank you very much Dion!

**Comment by BIMvoice** [comment]
I think we can close this for now. I'm sure we will have more issues on this topic since there are so many changes undergoing.
