### ISSUE TITLE
Error on drawing creation

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4476]
Get the following error when i try to create a drawing for the `METAL STUD - TYPICAL FRAMING ELEVATION @ DOOR OPENING ≥ THAN 3FT OPENING` view

file: https://hub.openingdesign.com/OpeningDesign/Tradesman_Warehouse_TI/src/commit/899c31e2a0ee663f464fa173ef3766b51109f66c/Open/Models/BlenderBIM/Tradesman_Warehouse_TI.ifc

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 212, in invoke
    return self.execute(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 263, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 526, in generate_linework
    self.serialize_contexts_elements(ifc, tree, contexts, "body", drawing_elements, target_view)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 471, in serialize_contexts_elements
    self.serialiser.write(elem)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1559, in write
    return _ifcopenshell_wrapper.SvgSerializer_write(self, *args)
RuntimeError: Token $ at offset 45,892,126 invalid instance name

```

**Comment by theoryshaw** [comment]
fixed it via:
https://github.com/IfcOpenShell/IfcOpenShell/issues/4389#issuecomment-1977363303

Was just confused, as it was a different error.

**Comment by theoryshaw** [comment]
Also too, this error did not happen with the latest build.
