### ISSUE TITLE
Error if tab into extrusion geometry

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4477]
If i 'tab' into the following geometry, i get the following error. 

file: https://hub.openingdesign.com/OpeningDesign/Tradesman_Warehouse_TI/src/commit/899c31e2a0ee663f464fa173ef3766b51109f66c/Open/Models/BlenderBIM/Tradesman_Warehouse_TI.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/ed1ffa17-8b17-4692-ada0-721ceb4e86b1

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1595, in invoke
    return IfcStore.execute_ifc_operator(self, context, is_invoke=True)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 347, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1645, in _invoke
    bpy.ops.bim.edit_extrusion_profile()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 211, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\slab.py", line 657, in _execute
    profile = tool.Model.export_profile(obj, position=position)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\model.py", line 132, in export_profile
    indices = helper.auto_detect_arbitrary_profile_with_voids(obj, obj.data)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\helper.py", line 145, in auto_detect_arbitrary_profile_with_voids
    is_special, group_index = tool.Blender.bmesh_check_vertex_in_groups(vert, deform_layer, group_indices)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\blender.py", line 577, in bmesh_check_vertex_in_groups
    for group_index in vertex[deform_layer].keys():
AttributeError: BMElem[key]: invalid key, must be a BMLayerItem
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113

```

**Comment by theoryshaw** [comment]
Might be related to: https://github.com/IfcOpenShell/IfcOpenShell/commit/395598d8e38d21bc19e4ea86e2aa4fde2e3e71cb

ping @Andrej730
