### ISSUE TITLE
IfcTester Error

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4483]
Hey guys, still getting an error when running this IDS to check if all wals have True value for LoadBearing. It works just fine when I check only if they have LoadBearing, but getting error when checking if it's true.

I attached the IDS
[097test.ids.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/14810351/097test.ids.zip)

And this is the error I get: 
`Python: Traceback (most recent call last):
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/module/tester/operator.py", line 57, in execute
    specs = ifctester.ids.open(props.specs)
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifctester/ids.py", line 45, in open
    return Ids().parse(
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifctester/ids.py", line 121, in parse
    spec.parse(xml_spec)
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifctester/ids.py", line 213, in parse
    self.parse_clause(ids_dict["requirements"]) if ids_dict.get("requirements", None) is not None else []
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifctester/ids.py", line 226, in parse_clause
    facet = globals()[name_capitalised]().parse(facet_xml)
  File "/Users/petru/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifctester/facet.py", line 83, in parse
    setattr(self, name, Restriction().parse(value["restriction"][0]))
KeyError: 0
`

**Comment by Moult** [comment]
Ah yeah this is because now restrictions are limited to 1 which is good.

By the way in your IDS it specifies a boolean true like this:

```xml
          <ids:value>
            <xs:restriction base="xs:boolean">
              <xs:pattern value="true" />
            </xs:restriction>
          </ids:value>
```

I don't think this is allowed. According to the IDS documentation True/false must be specified as uppercase strings e.g.:

```xml
          <value>
            <simpleValue>FALSE</simpleValue>
          </value>
```

See this example: https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases/property/pass-booleans_must_be_specified_as_uppercase_strings_2_3.ids

If this is from ACCA, maybe ping @andreaaielloALMA ?

**Comment by BIMvoice** [comment]
Yeah, I felt something was looking sketchy there. I'll ping Andrea. Thanks again, Dion!
