### ISSUE TITLE
Error on spreadsheet import

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4495]
Tried to import the following spreadsheet into the following files, got the following error

[spreadsheet](https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/60f13d41879895046baa190bf57da7527af31636/Open/Models_and_CAD/BlenderBIM/schedules/WALL%20-%20QUANTITY%20TAKE-OFF.ods)
[ifc](https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/60f13d41879895046baa190bf57da7527af31636/Open/Models_and_CAD/BlenderBIM/Highland_Haven.ifc)
[blend](https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/60f13d41879895046baa190bf57da7527af31636/Open/Models_and_CAD/BlenderBIM/Highland_Haven.blend)

Open .blend file first and go to the 'Layout' tab.

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\csv\operator.py", line 275, in execute
    ifc_csv.Import(
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 392, in Import
    self.import_ods(ifc_file, table, attributes, null, empty, bool_true, bool_false)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 426, in import_ods
    self.import_pd(ifc_file, df, attributes, null, empty, bool_true, bool_false)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 437, in import_pd
    self.process_row(ifc_file, row.tolist(), headers, attributes, null, empty, bool_true, bool_false)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 467, in process_row
    ifcopenshell.util.selector.set_element_value(ifc_file, element, key, value)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 464, in set_element_value
    cls.set_element_value(ifc_file, v, keys[i + 1 :], value)
NameError: name 'cls' is not defined

```

**Comment by Andrej730** [comment]
Should be fixed now. Though there is a caveat - you'd need to change query to `material.item.0.Material.Name` from `material.item.Material.Name.0` to ensure that it will work during csv import. I've created a separate issue about this #4687
