### ISSUE TITLE
Error after changing a wall's material assignment. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4496]
If you go to the following type, and try to change the material assignment to something different, the following error is thrown. 

ifc: https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/7425a643b4f542bf142a0f4a6f563eab4eec68c3/Open/Models_and_CAD/BlenderBIM/Highland_Haven.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d3458fd4-e9b3-4a10-9390-fa8c912b13de

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 211, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\material\operator.py", line 641, in _execute
    ifcopenshell.api.run(
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 73, in run
    listener(usecase_path, ifc_file, settings)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\wall.py", line 724, in regenerate_from_layer
    DumbWallRecalculator().recalculate([w for w in set(walls) if w])
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\wall.py", line 431, in recalculate
    joiner.recreate_wall(element, wall)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\wall.py", line 1122, in recreate_wall
    self.join(
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\wall.py", line 1311, in join
    if tool.Cad.is_x(tool.Cad.angle_edges(self.axis, proposed_axis, degrees=True), 180, tolerance=0.001):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\cad.py", line 84, in angle_edges
    a = (edge1[1] - edge1[0]).angle(edge2[1] - edge2[0])
ValueError: Vector.angle(other): zero length vectors have no valid angle

```

**Comment by theoryshaw** [comment]
also, it throws the error, but it does seem to change the assignment.
