### ISSUE TITLE
AttributeError: module 'blenderbim.bim.module.geometry.prop' has no attribute 'ShapeAspect'

### ISSUE THREAD

**Issue by onyeibo** [IfcOpenShell/IfcOpenShell#4498]
I just downloaded Blender 4.1 and BlenderBIM (240401, https://github.com/IfcOpenShell/IfcOpenShell/releases/download/blenderbim-240401/blenderbim-240401-py311-linux.zip).

The addon installs but fails to activate.  See traceback below.

Modules Installed (blenderbim) from '/home/schemefusion/Downloads/apps/blenderbim-240401-py311-linux.zip' into '/home/schemefusion/.config/blender/4.1/scripts/addons'
Traceback (most recent call last):
  File "/home/schemefusion/Downloads/apps/blender-4.1.0-linux-x64/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schemefusion/Downloads/apps/blender-4.1.0-linux-x64/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/schemefusion/.config/blender/4.1/scripts/addons/blenderbim/__init__.py", line 41, in <module>
    import blenderbim.bim
  File "/home/schemefusion/.config/blender/4.1/scripts/addons/blenderbim/bim/__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "/home/schemefusion/.config/blender/4.1/scripts/addons/blenderbim/bim/handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "/home/schemefusion/.config/blender/4.1/scripts/addons/blenderbim/tool/__init__.py", line 21, in <module>
    from blenderbim.tool.boundary import Boundary
  File "/home/schemefusion/.config/blender/4.1/scripts/addons/blenderbim/tool/boundary.py", line 23, in <module>
    from blenderbim.bim.module.geometry.helper import Helper
  File "/home/schemefusion/.config/blender/4.1/scripts/addons/blenderbim/bim/module/geometry/__init__.py", line 62, in <module>
    prop.ShapeAspect,
    ^^^^^^^^^^^^^^^^
AttributeError: module 'blenderbim.bim.module.geometry.prop' has no attribute 'ShapeAspect'

**Comment by Moult** [comment]
See FAQ number 4: https://blenderbim.org/docs/users/installation.html#faq

**Comment by onyeibo** [comment]
> See FAQ number 4: https://blenderbim.org/docs/users/installation.html#faq

That worked.  Thanks
