### ISSUE TITLE
Error linking an .ifc file. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4521]
Got the following error linking an .ifc file. 

Was a simple file, made from the demo library, with one wall in it. 

windows10

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 868, in execute
    bpy.ops.bim.load_link(filepath=filepath, false_origin=self.false_origin)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 947, in execute
    self.link_ifc()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 989, in link_ifc
    self.link_blend(blend_filepath)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 951, in link_blend
    with bpy.data.libraries.load(filepath, link=True) as (data_from, data_to):
OSError: load: D:\Dropbox\Troubleshooting\20240405 - linking test\1.ifc.cache.blend failed to open blend file
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113

```

**Comment by maxfb87** [comment]
@theoryshaw got the same error and i resolved saving all the files in the same directory and saving also the .blend file toghether with the .ifc file.
This was a workaround btw and i think that this should be better explained/resolved...

**Comment by Moult** [comment]
Is this because one model is on C: and the other is on D:?

**Comment by theoryshaw** [comment]
All the test files were located here...

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/0bfb2e76-9271-495d-9d90-87f53b599e21)

**Comment by maxfb87** [comment]
So the problem is because there isn't the related .blend file in the folder

**Comment by Nattefrost666** [comment]
Same problem here, I resolved saving the ifc file as a blend file in the same folder with the following name "namefile.ifc.cache.blend"

**Comment by theoryshaw** [comment]
> So the problem is because there isn't the related .blend file in the folder

  I was under the impression that it creates the .blend file and the SQL database automatically.
