### ISSUE TITLE
cannot activate add-on Blender4.1 macOS 14.4.1

### ISSUE THREAD

**Issue by cekuhnen** [IfcOpenShell/IfcOpenShell#4527]
Traceback (most recent call last):
  File "/Applications/Blender 4.1.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender 4.1.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/__init__.py", line 41, in <module>
    import blenderbim.bim
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/tool/__init__.py", line 30, in <module>
    from blenderbim.tool.document import Document
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/tool/document.py", line 23, in <module>
    from blenderbim.bim import import_ifc
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 42, in <module>
    from blenderbim.bim.module.drawing.prop import ANNOTATION_TYPES_DATA
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/module/drawing/__init__.py", line 20, in <module>
    from . import ui, prop, operator, handler, gizmos, workspace
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/module/drawing/ui.py", line 31, in <module>
    from blenderbim.bim.module.drawing.prop import ANNOTATION_TYPES_DATA
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/module/drawing/prop.py", line 27, in <module>
    import blenderbim.bim.module.drawing.decoration as decoration
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/module/drawing/decoration.py", line 25, in <module>
    import shapely
  File "/Users/ez5554/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/libs/site/packages/shapely/__init__.py", line 1, in <module>
    from shapely.lib import GEOSException  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'shapely.lib'

**Comment by Moult** [comment]
See FAQ 4: https://docs.blenderbim.org/users/installation.html#faq
