### ISSUE TITLE
AttributeError: entity instance of type 'IFC4.IfcAnnotation' has no attribute 'IsConnectionRealization'

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4575]
When I save the .blend/.ifc session from the following files, i get the following error:

blend: https://hub.openingdesign.com/OpeningDesign/Restaurant_Pewaukee/src/commit/c77312c20f63757f70fce8aa712d4699cb5d2aa3/Open/Models/BlenderBIM/Restaurant_Pewaukee.blend
ifc: https://hub.openingdesign.com/OpeningDesign/Restaurant_Pewaukee/src/commit/c77312c20f63757f70fce8aa712d4699cb5d2aa3/Open/Models/BlenderBIM/Restaurant_Pewaukee.ifc

Open the .blend file first.

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\ui.py", line 267, in draw
    ConnectionsData.load()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\data.py", line 153, in load
    cls.data = {"connections": cls.connections(), "is_connection_realization": cls.is_connection_realization()}
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\data.py", line 225, in is_connection_realization
    connections = element.IsConnectionRealization
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 196, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcAnnotation' has no attribute 'IsConnectionRealization'

```

**Comment by Andrej730** [comment]
Fixed. Error occurred if you would open "Connections" UI section for IfcAnnotation or other element that's unrelated to connections. Though this error was just UI error and shouldn't get in the way of saving ifc file.
