### ISSUE TITLE
Trying to create drawing when model view is activated causes error

### ISSUE THREAD

**Issue by manuvarkey** [IfcOpenShell/IfcOpenShell#4581]
When model view is activated (drawing views are not activated), trying to generate drawing by clicking on `Generate Drawing` raises the following error in blender.

![Screenshot from 2024-04-24 18-10-49](https://github.com/IfcOpenShell/IfcOpenShell/assets/4415312/87d6091a-2104-450e-a85f-f571e1b4c056)
```

Python: Traceback (most recent call last):
  File "/home/eee/.config/blender/4.1/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 241, in execute
    self.drawing = self.file.by_id(drawing_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 416, in by_id
    return self[id]
           ~~~~^^^^
  File "/home/eee/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 401, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3800, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #0 not found

```

**Comment by manuvarkey** [comment]
IFC file is attached

[test blender.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15104546/test.blender.txt)

Actually I have noticed that this happens with all files. I have made this screencast
[Screencast from 25-04-24 10:53:21 AM IST.webm](https://github.com/IfcOpenShell/IfcOpenShell/assets/4415312/393d53f9-ac79-42d5-899c-81affed4a750)

**Comment by Andrej730** [comment]
thank for the bug report, issue is fixed.
