### ISSUE TITLE
Get an error when editing the sheet identification. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4596]
Get an error when editing the sheet identification. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c4de1c35-8c49-4f8f-a988-659d6f07b9f6

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 76, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 2434, in _execute
    core.rename_reference(tool.Ifc, tool.Drawing, reference=sheet, identification=self.identification)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\core\drawing.py", line 149, in rename_reference
    ifc.run("document.edit_reference", reference=reference, attributes=attributes)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\ifc.py", line 34, in run
    return ifcopenshell.api.run(command, IfcStore.get_file(), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 172, in run
    result = usecase_class(ifc_file, **settings).execute()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\document\edit_reference.py", line 59, in execute
    setattr(self.settings["reference"], name, value)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 279, in __setattr__
    self[index] = value
    ~~~~^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 288, in __setitem__
    self.wrapped_data.file.transaction.store_edit(self, idx, value)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 101, in store_edit
    "old": self.serialise_value(element, element[index]),
                                         ~~~~~~~^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 283, in __getitem__
    raise IndexError("Attribute index {} out of range for instance of type {}".format(key, self.is_a()))
IndexError: Attribute index 4294967295 out of range for instance of type IfcDocumentReference

```

**Comment by theoryshaw** [comment]
Ping @Andrej730 
I think it started to happen here: https://github.com/IfcOpenShell/IfcOpenShell/commit/e14d96e6ee2a12dff7c3526ebe9cde548c8f5bab

**Comment by Andrej730** [comment]
@theoryshaw can you please share .ifc file? Couldn't reproduce this.

And are you sure you're on the latest version? There shouldn't be no more errors like `IndexError: Attribute index 4294967295 out of range for instance of type IfcDocumentReference` and it should be something like `AttributeError: entity instance of type 'IFC2X3.IfcWall' has no attribute 'Identification'` after cce2fee

**Comment by theoryshaw** [comment]
Hi, I tried again, and pulling down the latest.  
Still get the same error. 
file: https://hub.openingdesign.com/OpeningDesign/Tradesman_Warehouse_TI/src/commit/6bdfd8187af4a074e716df79268ed9d422727610/Open/Models/BlenderBIM/Tradesman_Warehouse_TI.ifc

where i checked out...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/e1e5b178-b1f8-4db8-b602-ef9a76520140)

**Comment by Andrej730** [comment]
Found it, was a typo...

Though I do have more descriptive error message below - you might have `ifcopenshell/entity_instance.py` not symlinked to the repo.
```
Error: Python: Traceback (most recent call last):
  File "\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 281, in __setattr__
    self[index] = value
    ~~~~^^^^^^^
  File "\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 297, in __setitem__
    self.wrapped_data.file.transaction.store_edit(self, idx, value)
  File "\blenderbim\libs\site\packages\ifcopenshell\file.py", line 101, in store_edit
    "old": self.serialise_value(element, element[index]),
                                         ~~~~~~~^^^^^^^
  File "\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 292, in __getitem__
    raise IndexError("Attribute index {} out of range for instance of type {}".format(key, self.is_a()))
IndexError: Attribute index 4294967295 out of range for instance of type IfcDocumentReference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 285, in __setattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcDocumentReference' has no attribute 'Identifiaction'
```
