### ISSUE TITLE
Exception Thrown When Trying to Show Pipe Segment Ports

### ISSUE THREAD

**Issue by zicklag** [IfcOpenShell/IfcOpenShell#4598]
Hey there!

I'm running into an exception with Blender 4.1.1 and BlenderBIM v0.0.240402 when I try to click the button to show the ports on a pipe segment:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25393315/9cc87da8-d64a-4de9-8458-84b697411f53)

Here's the log results of me starting blender, creating a new project, adding a pipe, trying to show the ports a couple times, saving the file, opening the file again, and trying to show the ports:

<details>

```
2024-04-30:16:35:44,382 ERROR   [import_ifc.py:819] Failed to generate shape for #1083=IfcTypeProduct('3pq2B$0k52ZOv2bFuRYkxO',$,'SETOUT-TAG',$,'IfcAnnotation/TEXT',(#1059),(#1082),$)
2024-04-30:16:35:44,387 ERROR   [import_ifc.py:819] Failed to generate shape for #1109=IfcTypeProduct('11M3ahhrr9NBdB29YEazzw',$,'DOOR-TAG',$,'IfcAnnotation/TEXT',(#1085),(#1108),$)
2024-04-30:16:35:44,391 ERROR   [import_ifc.py:819] Failed to generate shape for #1129=IfcTypeProduct('1eE8Y$BVDFDgG8Fj6d9wiV',$,'WINDOW-TAG',$,'IfcAnnotation/TEXT',(#1111),(#1128),$)
2024-04-30:16:35:44,396 ERROR   [import_ifc.py:819] Failed to generate shape for #1161=IfcTypeProduct('0vvfHSiaPBxewA$32C4LdW',$,'SPACE-TAG',$,'IfcAnnotation/TEXT',(#1131),(#1160),$)
2024-04-30:16:35:44,400 ERROR   [import_ifc.py:819] Failed to generate shape for #1181=IfcTypeProduct('36lTcd9yT8UBNDejQUNWrq',$,'MATERIAL-TAG',$,'IfcAnnotation/TEXT',(#1163),(#1180),$)
2024-04-30:16:35:44,405 ERROR   [import_ifc.py:819] Failed to generate shape for #1201=IfcTypeProduct('1rxhEX6I16oPqglXaGZ7Sw',$,'TYPE-TAG',$,'IfcAnnotation/TEXT',(#1183),(#1200),$)
2024-04-30:16:35:44,409 ERROR   [import_ifc.py:819] Failed to generate shape for #1221=IfcTypeProduct('0sws1hxNb2Og1etXqyoEh1',$,'NAME-TAG',$,'IfcAnnotation/TEXT',(#1203),(#1220),$)
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1360 pyrna_enum_to_py: current value '0' matches no enum in 'BIMModelProperties', '', 'relating_type_id'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1360 pyrna_enum_to_py: current value '0' matches no enum in 'BIMModelProperties', '', 'relating_type_id'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1360 pyrna_enum_to_py: current value '0' matches no enum in 'BIMModelProperties', '', 'relating_type_id'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1360 pyrna_enum_to_py: current value '0' matches no enum in 'BIMModelProperties', '', 'relating_type_id'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1360 pyrna_enum_to_py: current value '0' matches no enum in 'BIMModelProperties', '', 'relating_type_id'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1360 pyrna_enum_to_py: current value '0' matches no enum in 'BIMModelProperties', '', 'relating_type_id'
0 / 2 elements processed ...
Traceback (most recent call last):
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 32, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 155, in _execute
    core.show_ports(tool.Ifc, tool.System, tool.Spatial, element=tool.Ifc.get_entity(context.active_object))
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/core/system.py", line 76, in show_ports
    system.load_ports(element, ports)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/tool/system.py", line 158, in load_ports
    ifc_importer.place_objects_in_collections()
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1733, in place_objects_in_collections
    self.place_object_in_collection(self.file.by_id(ifc_definition_id), obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1737, in place_object_in_collection
    self.place_object_in_decomposition_collection(element, obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1761, in place_object_in_decomposition_collection
    return self.place_object_in_spatial_decomposition_collection(element, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1794, in place_object_in_spatial_decomposition_collection
    self.collections[container.GlobalId].objects.link(obj)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '3Yt$vwjQrE$gTtq5W5eVVr'
Error: Python: Traceback (most recent call last):
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 32, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 155, in _execute
    core.show_ports(tool.Ifc, tool.System, tool.Spatial, element=tool.Ifc.get_entity(context.active_object))
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/core/system.py", line 76, in show_ports
    system.load_ports(element, ports)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/tool/system.py", line 158, in load_ports
    ifc_importer.place_objects_in_collections()
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1733, in place_objects_in_collections
    self.place_object_in_collection(self.file.by_id(ifc_definition_id), obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1737, in place_object_in_collection
    self.place_object_in_decomposition_collection(element, obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1761, in place_object_in_decomposition_collection
    return self.place_object_in_spatial_decomposition_collection(element, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1794, in place_object_in_spatial_decomposition_collection
    self.collections[container.GlobalId].objects.link(obj)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '3Yt$vwjQrE$gTtq5W5eVVr'

Starting export
Warning: add-on missing 'bl_info', this can cause poor performance!: '/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/plyfile.py'
Export finished in 0.02 seconds
0 / 2 elements processed ...
Traceback (most recent call last):
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 32, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 155, in _execute
    core.show_ports(tool.Ifc, tool.System, tool.Spatial, element=tool.Ifc.get_entity(context.active_object))
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/core/system.py", line 76, in show_ports
    system.load_ports(element, ports)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/tool/system.py", line 158, in load_ports
    ifc_importer.place_objects_in_collections()
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1733, in place_objects_in_collections
    self.place_object_in_collection(self.file.by_id(ifc_definition_id), obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1737, in place_object_in_collection
    self.place_object_in_decomposition_collection(element, obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1761, in place_object_in_decomposition_collection
    return self.place_object_in_spatial_decomposition_collection(element, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1794, in place_object_in_spatial_decomposition_collection
    self.collections[container.GlobalId].objects.link(obj)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '3Yt$vwjQrE$gTtq5W5eVVr'
Error: Python: Traceback (most recent call last):
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 32, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 155, in _execute
    core.show_ports(tool.Ifc, tool.System, tool.Spatial, element=tool.Ifc.get_entity(context.active_object))
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/core/system.py", line 76, in show_ports
    system.load_ports(element, ports)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/tool/system.py", line 158, in load_ports
    ifc_importer.place_objects_in_collections()
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1733, in place_objects_in_collections
    self.place_object_in_collection(self.file.by_id(ifc_definition_id), obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1737, in place_object_in_collection
    self.place_object_in_decomposition_collection(element, obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1761, in place_object_in_decomposition_collection
    return self.place_object_in_spatial_decomposition_collection(element, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1794, in place_object_in_spatial_decomposition_collection
    self.collections[container.GlobalId].objects.link(obj)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '3Yt$vwjQrE$gTtq5W5eVVr'

0 / 2 elements processed ...
Traceback (most recent call last):
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 32, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 155, in _execute
    core.show_ports(tool.Ifc, tool.System, tool.Spatial, element=tool.Ifc.get_entity(context.active_object))
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/core/system.py", line 76, in show_ports
    system.load_ports(element, ports)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/tool/system.py", line 158, in load_ports
    ifc_importer.place_objects_in_collections()
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1733, in place_objects_in_collections
    self.place_object_in_collection(self.file.by_id(ifc_definition_id), obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1737, in place_object_in_collection
    self.place_object_in_decomposition_collection(element, obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1761, in place_object_in_decomposition_collection
    return self.place_object_in_spatial_decomposition_collection(element, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1794, in place_object_in_spatial_decomposition_collection
    self.collections[container.GlobalId].objects.link(obj)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '3Yt$vwjQrE$gTtq5W5eVVr'
Error: Python: Traceback (most recent call last):
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 32, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 155, in _execute
    core.show_ports(tool.Ifc, tool.System, tool.Spatial, element=tool.Ifc.get_entity(context.active_object))
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/core/system.py", line 76, in show_ports
    system.load_ports(element, ports)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/tool/system.py", line 158, in load_ports
    ifc_importer.place_objects_in_collections()
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1733, in place_objects_in_collections
    self.place_object_in_collection(self.file.by_id(ifc_definition_id), obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1737, in place_object_in_collection
    self.place_object_in_decomposition_collection(element, obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1761, in place_object_in_decomposition_collection
    return self.place_object_in_spatial_decomposition_collection(element, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1794, in place_object_in_spatial_decomposition_collection
    self.collections[container.GlobalId].objects.link(obj)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '3Yt$vwjQrE$gTtq5W5eVVr'

Starting import process :: 0.00
Loading file :: 0.00
Calculate unit scale :: 0.00
Process context filter :: 0.00
Calculate model offset :: 0.00
Predict dense mesh :: 0.07
Set units :: 0.00
Create project :: 0.00
Process element filter :: 0.00
Create collections :: 0.00
Create materials :: 0.00
Create styles :: 0.00
Parsing native elements :: 0.00
Done creating geometry
Create native elements :: 0.00
Done creating geometry
Create elements :: 0.01
Create annotations :: 0.00
Create grids :: 0.00
0 / 3 elements processed ...
Create spatial elements :: 0.05
Create structural items :: 0.00
2024-04-30:16:36:30,340 ERROR   [import_ifc.py:819] Failed to generate shape for #1083=IfcTypeProduct('3pq2B$0k52ZOv2bFuRYkxO',$,'SETOUT-TAG',$,'IfcAnnotation/TEXT',(#1059),(#1082),$)
2024-04-30:16:36:30,462 ERROR   [import_ifc.py:819] Failed to generate shape for #1129=IfcTypeProduct('1eE8Y$BVDFDgG8Fj6d9wiV',$,'WINDOW-TAG',$,'IfcAnnotation/TEXT',(#1111),(#1128),$)
2024-04-30:16:36:30,468 ERROR   [import_ifc.py:819] Failed to generate shape for #1109=IfcTypeProduct('11M3ahhrr9NBdB29YEazzw',$,'DOOR-TAG',$,'IfcAnnotation/TEXT',(#1085),(#1108),$)
2024-04-30:16:36:30,475 ERROR   [import_ifc.py:819] Failed to generate shape for #1221=IfcTypeProduct('0sws1hxNb2Og1etXqyoEh1',$,'NAME-TAG',$,'IfcAnnotation/TEXT',(#1203),(#1220),$)
2024-04-30:16:36:30,476 ERROR   [import_ifc.py:819] Failed to generate shape for #1201=IfcTypeProduct('1rxhEX6I16oPqglXaGZ7Sw',$,'TYPE-TAG',$,'IfcAnnotation/TEXT',(#1183),(#1200),$)
2024-04-30:16:36:30,477 ERROR   [import_ifc.py:819] Failed to generate shape for #1181=IfcTypeProduct('36lTcd9yT8UBNDejQUNWrq',$,'MATERIAL-TAG',$,'IfcAnnotation/TEXT',(#1163),(#1180),$)
2024-04-30:16:36:30,478 ERROR   [import_ifc.py:819] Failed to generate shape for #1161=IfcTypeProduct('0vvfHSiaPBxewA$32C4LdW',$,'SPACE-TAG',$,'IfcAnnotation/TEXT',(#1131),(#1160),$)
Create element types :: 0.15
Place objects in collections :: 0.00
Add project to scene :: 0.00
Setting default context :: 0.01
Import finished in 0.30 seconds
0 / 2 elements processed ...
Traceback (most recent call last):
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 32, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 155, in _execute
    core.show_ports(tool.Ifc, tool.System, tool.Spatial, element=tool.Ifc.get_entity(context.active_object))
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/core/system.py", line 76, in show_ports
    system.load_ports(element, ports)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/tool/system.py", line 158, in load_ports
    ifc_importer.place_objects_in_collections()
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1733, in place_objects_in_collections
    self.place_object_in_collection(self.file.by_id(ifc_definition_id), obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1737, in place_object_in_collection
    self.place_object_in_decomposition_collection(element, obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1761, in place_object_in_decomposition_collection
    return self.place_object_in_spatial_decomposition_collection(element, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1794, in place_object_in_spatial_decomposition_collection
    self.collections[container.GlobalId].objects.link(obj)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '3Yt$vwjQrE$gTtq5W5eVVr'
Error: Python: Traceback (most recent call last):
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 32, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/system/operator.py", line 155, in _execute
    core.show_ports(tool.Ifc, tool.System, tool.Spatial, element=tool.Ifc.get_entity(context.active_object))
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/core/system.py", line 76, in show_ports
    system.load_ports(element, ports)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/tool/system.py", line 158, in load_ports
    ifc_importer.place_objects_in_collections()
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1733, in place_objects_in_collections
    self.place_object_in_collection(self.file.by_id(ifc_definition_id), obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1737, in place_object_in_collection
    self.place_object_in_decomposition_collection(element, obj)
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1761, in place_object_in_decomposition_collection
    return self.place_object_in_spatial_decomposition_collection(element, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zicklag/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 1794, in place_object_in_spatial_decomposition_collection
    self.collections[container.GlobalId].objects.link(obj)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '3Yt$vwjQrE$gTtq5W5eVVr'
```

</details>

Here's the file I'm running into the issue with. All I did was create a new demo IFC project, add a pipe with the pipe tool ( after creating a new pipe type with the button ), and then try to show it's ports.

[error.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/15171329/error.ifc.zip)

---

It's also worth noting that I just updated blender and installed the latest BlenderBIM because I was running into this issue. Strangely, when I opened my project created with the previous version of Blender/BlenderBIM, I was able to show the ports on some of my pipes the first time I opened the file.

Thinking that the issue was fixed, I deleted my old pipes because they were in the wrong spot, and started to re-create them. After re-creating, though, I couldn't show the ports anymore. I can't reproduce the ability to actually show the ports now, so I'm not sure why it worked for a second.

---

Also, I've been finding BlenderBIM really useful. A HUGE thanks to you guys for your work. ❤️

**Comment by Andrej730** [comment]
Thank you for the bug report.
