### ISSUE TITLE
For efficiency, would be nice if the wall regened, if `Ctrl+G` was used on the selected window, as well.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4601]
For efficiency, would be nice if the wall regened, if `Ctrl+G` was used on the selected window, as well.

**Comment by theoryshaw** [comment]
current error. 

I 'think' i remember this working before.  Not sure.
```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 601, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\ifc.py", line 211, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 349, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 585, in _execute
    self.relating_material = element.HasAssociations[0].RelatingMaterial.is_a()
                             ~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range
```

**Comment by theoryshaw** [comment]
i think this is fixed.
