### ISSUE TITLE
BlenderBIM doesn't support representations with mixed polygons and curves

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#4606]
Trying to fix #4593 found that we don't support importing representations that consists both out of curves and polygons (e.g. Annotation2D allows having both IFCGEOMETRICCURVESET and IFCANNOTATIONFILLAREA. Example ifc - 
[mixed_repr.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15198661/mixed_repr.ifc.txt)

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/3d66f7e6-21bb-4a32-a65b-3e4c92effe35

Related piece of code:
https://github.com/IfcOpenShell/IfcOpenShell/blob/25fff3fdd01dfd167ae84d6b0c86d12653ea0bc6/src/blenderbim/blenderbim/bim/import_ifc.py#L1944-L1972

**Comment by sboddy** [comment]
Tried to test this. The test file is now throwing a big old exception when trying to activate the Plan/Annotation/PLAN_VIEW representation:
```
os: Linux
os_version: #147-Ubuntu SMP Sat Mar 15 15:53:30 UTC 2025
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: x86_64
blender_version: 4.2.9 LTS
bonsai_version: 0.8.3-alpha250418
bonsai_commit_hash: 917d28a
bonsai_commit_date: 2025-04-18T19:25:46+05:00
last_actions: 
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_object
# ifcopenshell.api: geometry.validate_type
>>> {}
# operator: BIM_OT_override_object_delete
# ifcopenshell.api: root.remove_product
>>> {"product": {"cast_type": "entity_instance", "value": 3317, "Name": "FurnishingElement"}}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 3317, "Name": "FurnishingElement"}, "representation": {"cast_type": "entity_instance", "value": 3328, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 3328, "Name": null}}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 3317, "Name": "FurnishingElement"}, "representation": {"cast_type": "entity_instance", "value": 3336, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 3336, "Name": null}}
# ifcopenshell.api: type.unassign_type
>>> {"related_objects": [{"cast_type": "entity_instance", "value": 3317, "Name": "FurnishingElement"}]}
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_enable_editing_representation_items
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
last_error: Traceback (most recent call last):
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/ifc.py", line 458, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/geometry/operator.py", line 374, in _execute
    core.switch_representation(
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/core/geometry.py", line 138, in switch_representation
    geometry.reimport_element_representations(obj, representation, apply_openings=apply_openings)
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/tool/geometry.py", line 879, in reimport_element_representations
    mprops = tool.Geometry.get_mesh_props(mesh)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/tool/geometry.py", line 88, in get_mesh_props
    return mesh.BIMMeshProperties
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'BIMMeshProperties'

ifc: mixed_repr.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: BlenderBIM 0.0.240422-86cc2bf
```
3D viewport still shows the Model/Body/MODEL_VIEW repr.

**Comment by BIMvoice** [comment]
Reproduced on v0.8.0. The representation `#117` really does return both faces (the `IfcAnnotationFillArea`) and loose edges (the `IfcGeometricCurveSet`), and IfcOpenShell packs `material_ids` as `[face materials, loose-edge materials]`. `convert_geometry_to_mesh` assumed all-faces-or-all-edges and fed the full material-id array into a per-face attribute, which raised `internal error setting the array`; `create_mesh` swallowed it and returned `None`, hence the `'NoneType' ... BIMMeshProperties` crash on switch. Fixed in #8340 by slicing the material ids to the face count and adding the loose curve edges to the mesh, so the fill area and the curves both import (2 faces + 36 loose curve edges, no crash); a normal tessellated mesh is unchanged. Item-mode editing of the individual curve items in a mixed rep is still not wired up; that's a separate enhancement.
