### ISSUE TITLE
Filtering - can't load saved filter when class exclusion is used

### ISSUE THREAD

**Issue by ppaawweeuu** [IfcOpenShell/IfcOpenShell#4609]
I can't load that filter when exclusion syntax mark `!` is used

I set Class filters looking for all IfcElement, without IfcWall ( `IfcElement, ! IfcWall` )
I can save that filter. It is listed as group and it works. I can select object from saved group. It works.

I can't load that filter using load button.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/0c7d0adb-6e09-41c0-b910-034d23797fc8)
or
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/b21ea51f-9f03-4fb8-ad04-651117e742bb)

Error is rised:
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 68, in _call_userfunc
    return f(children)
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\search.py", line 166, in entity
    return {"type": "entity", "value": " ".join([a.children[0].value for a in args])}
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\search.py", line 166, in <listcomp>
    return {"type": "entity", "value": " ".join([a.children[0].value for a in args])}
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 92, in _transform_children
    yield self._transform_tree(c)
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 101, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 92, in _transform_children
    yield self._transform_tree(c)
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 101, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 92, in _transform_children
    yield self._transform_tree(c)
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 101, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 92, in _transform_children
    yield self._transform_tree(c)
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 102, in _transform_tree
    return self._call_userfunc(tree, children)
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\lark\visitors.py", line 72, in _call_userfunc
    raise VisitError(tree.data, tree, e)
lark.exceptions.VisitError: Error trying to process rule "entity":

list index out of range
```

**Comment by Andrej730** [comment]
Thanks for the bug report, it's fixed. It was also breaking for guids exclusion.
