### ISSUE TITLE
Unable to enable BB

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4635]
On 4.1, i installed the [blenderbim-240507-py311-win.zip](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-240507) release. 
I enabled it and it worked.
ran the [updated](https://github.com/IfcOpenShell/IfcOpenShell/commit/26434f0331dad5b5b5d2ff9a07a260b790baed6c#diff-b0bc2a249d05f5115f1780ace6428db2938ddb55d3299c7c83855833455bb26f) bat file, for symlinking. 
was synced to: bc72c927c1d6737730a2db1391e5b4a9e4de21d3

Tried to enable BB again, got following error. 
If I check out past commits in history, still get the same error. 

```
Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 81, in <module>
    from . import ifcopenshell_wrapper
ImportError: cannot import name 'ifcopenshell_wrapper' from partially initialized module 'ifcopenshell' (most likely due to a circular import) (C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 41, in <module>
    import blenderbim.bim
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\handler.py", line 23, in <module>
    import ifcopenshell.api.owner.settings
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 83, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.11'


```

**Comment by Moult** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/commit/984b1212a6a394e7f39c37fc7294d2ef8e0d42fc
