### ISSUE TITLE
BCF export from IDS report

### ISSUE THREAD

**Issue by vitorhpmartins** [IfcOpenShell/IfcOpenShell#4640]
I'm trying to generate/export a BCF file from an IDS report run by BlenderBIM, but it's giving this error:

```
Python: Traceback (most recent call last):
File "C:\Users\engvi\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\tester\[operator.py](http://operator.py/)", line 214, in execute
bcf_[reporter.report](http://reporter.report/)()
File "C:\Users\engvi\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifctester\[reporter.py](http://reporter.py/)", line 177, in report
specification_report = [self.report](http://self.report/)_specification(specification)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\engvi\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifctester\[reporter.py](http://reporter.py/)", line 224, in report_specification
"failed_entities": [self.report](http://self.report/)_failed_entities(requirement),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\engvi\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifctester\[reporter.py](http://reporter.py/)", line 430, in report_failed_entities
{"reason": requirement.failed_reasons[i], "element": e} for i, e in enumerate(requirement.failed_entities)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Attribute' object has no attribute 'failed_entities'
```

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/116745805/364b5dad-fa33-4950-83d2-59fbec16e07b)

**Comment by Moult** [comment]
It looks like you're using an outdated version of IfcTester / BBIM. Can you upgrade to the latest version?

**Comment by Moult** [comment]
https://docs.blenderbim.org/devs/installation.html#unstable-installation

**Comment by vitorhpmartins** [comment]
@Moult I updated BlenderBIM, but the error message persists.
See below:

```
Python: Traceback (most recent call last):
  File "C:\Users\engvi\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\tester\operator.py", line 215, in execute
    bcf_reporter.to_file(self.filepath)
  File "C:\Users\engvi\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifctester\reporter.py", line 705, in to_file
    bcfxml = BcfXml.create_new(self.results["title"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engvi\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\bcf\v2\bcfxml.py", line 143, in create_new
    instance = cls(xml_handler=xml_handler or XmlParserSerializer())
                                              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engvi\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\bcf\xml_parser.py", line 60, in __init__
    self.parser = build_xml_parser(self.context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engvi\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\bcf\xml_parser.py", line 13, in build_xml_parser
    parser.register_namespace(ns_map=parser.ns_map, prefix="xs", uri="http://www.w3.org/2001/XMLSchema")
TypeError: PushParser.register_namespace() got an unexpected keyword argument 'ns_map'
```

**Comment by Andrej730** [comment]
@vitorhpmartins it's a different issue, should be resolved now. Can you please try the latest build?

**Comment by vitorhpmartins** [comment]
@Andrej730 yes, now it's works! thanks very very much.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/116745805/b1b3217f-e996-41cc-babd-1ffb5bd83ebd)
