### ISSUE TITLE
Outliner tree structure flattened

### ISSUE THREAD

**Issue by ppaawweeuu** [IfcOpenShell/IfcOpenShell#4644]
Since BB 240508 new ifc file starts with strange/flat project structure, and Spatial Manager can't see Spatial Structure at all.
I use blender 4.0.1

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/2c9bf6af-5f45-4497-9744-d51beb762690)

BB 240507 (and before) started with:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/73b6399a-d27b-4f16-afd3-9daf707503da)

**Comment by ppaawweeuu** [comment]
and there is console error with:
`AttributeError: module 'ifcopenshell.api' has no attribute 'spatial'. Did you mean: 'partial'?`

full message:
```
Python: Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 94, in execute
    bpy.ops.bim.create_project()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 326, in wrapper
    result = usecase(*args, **settings)
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\aggregate\assign_object.py", line 126, in assign_object
    ifcopenshell.api.run("spatial.unassign_container", file, products=possibly_contained_products)
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 163, in run
    usecase_function = getattr(getattr(ifcopenshell.api, module), usecase)
AttributeError: module 'ifcopenshell.api' has no attribute 'spatial'. Did you mean: 'partial'?
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109
```

**Comment by ppaawweeuu** [comment]
after 20240510 update everything is fine
issue to be closed, i think

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/f262f0f5-c0b5-4ccf-970a-80ac0137c43d)
