### ISSUE TITLE
Error when creating project with demo library

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4650]
I get an error when I created a project with the demo library. This happens on both, mac and windows. I'm using Blender 4.1 and today's ifcopenshell py311 build.

` Read prefs: "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\config\userpref.blend"
reloading addon meta-data: blenderbim 'C:\\Users\\peco01\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons\\blenderbim\\__init__.py' (time-stamp change detected)
Modules Installed () from 'C:\\Users\\peco01\\Downloads\\blenderbim-240509-py311-win.zip' into 'C:\\Users\\peco01\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 107, in execute
    self._execute(context)
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 124, in _execute
    core.create_project(tool.Ifc, tool.Project, schema=props.export_schema, template=template)
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\core\project.py", line 80, in create_project
    project.run_aggregate_assign_object(relating_obj=project_obj, related_obj=site)
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\project.py", line 65, in run_aggregate_assign_object
    return blenderbim.core.aggregate.assign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\core\aggregate.py", line 31, in assign_object
    rel = ifc.run(
          ^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\ifc.py", line 34, in run
    return ifcopenshell.api.run(command, IfcStore.get_file(), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 166, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 326, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\aggregate\assign_object.py", line 126, in assign_object
    ifcopenshell.api.run("spatial.unassign_container", file, products=possibly_contained_products)
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 161, in run
    importlib.import_module(f"ifcopenshell.api.{usecase_path}")
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\spatial\__init__.py", line 31, in <module>
    wrap_usecases(__path__, __name__)
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 353, in wrap_usecases
    usecase = getattr(module, usecase_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'ifcopenshell.api.spatial' has no attribute 'remove_container' (most likely due to a circular import)
Error: Python: Traceback (most recent call last):
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 326, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\aggregate\assign_object.py", line 126, in assign_object
    ifcopenshell.api.run("spatial.unassign_container", file, products=possibly_contained_products)
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 161, in run
    importlib.import_module(f"ifcopenshell.api.{usecase_path}")
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\spatial\__init__.py", line 31, in <module>
    wrap_usecases(__path__, __name__)
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 353, in wrap_usecases
    usecase = getattr(module, usecase_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'ifcopenshell.api.spatial' has no attribute 'remove_container' (most likely due to a circular import)

`

**Comment by S59-Koara** [comment]
In my environment, it also happens with blank project, so it may not be caused by demo liblary.

**Comment by jsaarane** [comment]
There is no content in the demolibrary and it doesn't let you save.
