### ISSUE TITLE
Error when opening IFC-file "AttributeError: 'NoneType' object has no attribute 'BIMMeshProperties'"

### ISSUE THREAD

**Issue by hannesw** [IfcOpenShell/IfcOpenShell#4652]
I'm unable to open [this IFC-File](https://github.com/IfcOpenShell/IfcOpenShell/files/15273715/101_36-Gebaude.ifc.txt) in BlenderBIM.

Opening with BIMCollab works fine:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/1560010/63590f5e-9933-43f7-ad0a-1d32967a4424)

**Versions**
Blender: 4.1.1
BBim: 0.0.240505

```
2024-05-10:12:14:15,485 ERROR   [import_ifc.py:1978] Could not create mesh for #46587=IfcBuildingElementProxyType('2KdClK5JL039RMZuTeD5oa',#2,'Neutracon',$,$,$,(#34),$,$,.NOTDEFINED.)
Traceback (most recent call last):
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 1915, in create_mesh
    m = shape.transformation.matrix.data
        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 871, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Triangulation, name)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Triangulation' object has no attribute 'transformation'

Traceback (most recent call last):
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 766, in execute
    ifc_importer.execute()
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 285, in execute
    self.create_element_types()
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 805, in create_element_types
    self.create_element_type(element_type)
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 821, in create_element_type
    tool.Loader.link_mesh(shape, mesh)
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\loader.py", line 79, in link_mesh
    mesh.BIMMeshProperties.ifc_definition_id = int(geometry.id.replace(",", ""))
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'BIMMeshProperties'
Error: Python: Traceback (most recent call last):
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 766, in execute
    ifc_importer.execute()
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 285, in execute
    self.create_element_types()
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 805, in create_element_types
    self.create_element_type(element_type)
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 821, in create_element_type
    tool.Loader.link_mesh(shape, mesh)
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\loader.py", line 79, in link_mesh
    mesh.BIMMeshProperties.ifc_definition_id = int(geometry.id.replace(",", ""))
    ^^^Error in bpy.app.handlers.load_post[7]:
Traceback (most recent call last):
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 662, in load_handler
    self.finish_loading_project(context)
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 689, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 766, in execute
    ifc_importer.execute()
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 285, in execute
    self.create_element_types()
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 805, in create_element_types
    self.create_element_type(element_type)
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 821, in create_element_type
    tool.Loader.link_mesh(shape, mesh)
  File "C:\Users\hwoer\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\loader.py", line 79, in link_mesh
    mesh.BIMMeshProperties.ifc_definition_id = int(geometry.id.replace(",", ""))
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'BIMMeshProperties'
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109
```

**Comment by Moult** [comment]
Thanks for the report! Fixed, but BTW there's some crazy stuff going on in that model, like the types don't correctly map representations to instances, and also types are 1000 times larger (maybe a mix up between mm and m units). BIMCollab doesn't show those types, but we do, and the non-mapping of types and occurrences effectively doubles the load time (you can enable advanced mode and enable "for coordination only" to not load types),

**Comment by hannesw** [comment]
@Moult thank you so much for the quick fix and the hint.
After i was able to load the mode, I identified the weird stuff. it was because I imported a revit family into BricsCAD BIM, which is the authoring software of this model.
