### ISSUE TITLE
RuntimeError: Invalid cast ...when generating drawing after changing DecimalPlaces

### ISSUE THREAD

**Issue by marwiss** [IfcOpenShell/IfcOpenShell#4657]
What I did:

Under "Object Information".

I selected all IfcAnnotation in the view and added EPset_Drawing with the property DecimalPlaces set to 1.

No my screen looked like this:

![bild](https://github.com/IfcOpenShell/IfcOpenShell/assets/935375/68aafa67-87cc-4337-b3a3-6f6c290ea4ff)

I could not see that the number of decimal places was changed in the camera view, so I wanted to create an svg drawing to see if the decimal places would change there.

So I went to "Drawings and Documents".

I pushed the "Create Drawing" button.

RuntimeError: Invalid cast ... occured.

Here is a traceback:

```
Info: Saved "test.blend"
Info: IFC Project "test.ifc" And Current Blend File Are Saved

Initialize drawing generation process 0.003033500164747238
Generate underlay 0.00045999977737665176
sync 0.009644600097090006
Processing body context 2.100132405757904e-06
Processing body context 0.03244509967043996
Processing annotation context 0.02259579999372363
Processing annotation context 0.00017150025814771652
Finalizing 0.0158008998259902
Generate linework 0.09322790009900928
Generate annotation 0.10595260001718998
Combine SVG layers 0.022270699962973595
Drawing generation process 0.22598270000889897
Initialize drawing generation process 0.0027115000411868095
Generate underlay 0.0004189000464975834
sync 0.008520900271832943
Processing body context 1.0998919606208801e-06
Processing body context 0.022428300231695175
Processing annotation context 0.02314419997856021
Processing annotation context 0.0001580999232828617
Finalizing 0.013750100042670965
Generate linework 0.07578880013898015
Generate annotation 0.016071700025349855
Combine SVG layers 0.01249920018017292
Drawing generation process 0.10911369975656271
Initialize drawing generation process 0.003029999788850546
Generate underlay 0.000409100204706192
Generate linework 0.000736599788069725
Generate annotation 0.0006857002153992653
Combine SVG layers 0.006516499910503626
Drawing generation process 0.012056099716573954
Error evaluating number, see Info editor for details: Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'A' is not defined

Initialize drawing generation process 0.003384600393474102
Generate underlay 0.00037189992144703865
sync 0.008613400161266327
Processing body context 8.00006091594696e-07
Processing body context 0.03155879955738783
Generate linework 0.04452949995175004
Drawing generation process 0.04865279980003834
Traceback (most recent call last):
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 202, in invoke
    return self.execute(context)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 253, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 501, in generate_linework
    self.serialiser.write(elem)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1512, in write
    return _ifcopenshell_wrapper.SvgSerializer_write(self, *args)
RuntimeError: Invalid cast
Error: Python: Traceback (most recent call last):
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 253, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 501, in generate_linework
    self.serialiser.write(elem)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1512, in write
    return _ifcopenshell_wrapper.SvgSerializer_write(self, *args)
RuntimeError: Invalid cast
```

The next thing I was trying to do was to try to save the IFC file. Then another error occured:

PermissionError:

```
Starting export
Traceback (most recent call last):
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 1039, in invoke
    return self.execute(context)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 1060, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 1092, in _execute
    ifc_exporter.export()
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\export_ifc.py", line 46, in export
    IfcStore.update_cache()
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 116, in update_cache
    os.replace(IfcStore.cache_path, new_cache_path)
PermissionError: [WinError 32] Det går inte att komma åt filen eftersom den
används av en annan process: 'C:\\Users\\Martin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\blenderbim\\bim\\data\\cache\\118ee2c1d38f1c6ca3c1d2df185235f6.h5' -> 'C:\\Users\\Martin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\blenderbim\\bim\\data\\cache\\0ac03c2d0ec32821816cc69630141274.h5'
Error: Python: Traceback (most recent call last):
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 1039, in invoke
    return self.execute(context)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 1060, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 1092, in _execute
    ifc_exporter.export()
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\export_ifc.py", line 46, in export
    IfcStore.update_cache()
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 116, in update_cache
    os.replace(IfcStore.cache_path, new_cache_path)
PermissionError: [WinError 32] Cant access file because used by other process: 'C:\\Users\\Martin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\blenderbim\\bim\\data\\cache\\118ee2c1d38f1c6ca3c1d2df185235f6.h5' -> 'C:\\Users\\Martin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\blenderbim\\bim\\data\\cache\\0ac03c2d0ec32821816cc69630141274.h5'
```

I wrote this issue.

Then I saved the .blend file using regular blender->File->Save.

Then I tried to save the IFC file again. And this time it worked without error.

It seems like the IFC file can not be saved while some file is used by another process. But after this process is complete it is now possible to save the IFC file again.

I closed BlenderBIM and then I opened the .blend file again.

Now I can see that the number of decimal places actually have changed.

But there is a new problem. Most of my vertical dimension annotations have disappeared.

And my horisontal annotations have moved.

My drawing is now a mess.

![bild](https://github.com/IfcOpenShell/IfcOpenShell/assets/935375/55d8a57b-949e-48c9-ba0d-3dc79847a6f7)

Maybe the transformations should have been applied before closing and reopening the file?

**Comment by theoryshaw** [comment]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/1e8e35ac-39e2-4cdd-8982-e56dff4630a8)

Don't apply this to the dimension object, change this value in the EPset_Drawing pset that's attached to the drawing camera object.   That is, this value is tied to all the dimensions on the drawing. 

...   

It would be nice to have dimension types, that have different rounding tolerances, but I don't think that functionality exists yet.

**Comment by marwiss** [comment]
I spontaneously thought that this was a property of each IfcAnnotation object.

Thank you for clarifying.

**Comment by Moult** [comment]
There's a lot to digest here. The first is that we the properties weren't restricted to drawing objects. That's now fixed.

Then there's this error, which looks unrelated and perhaps you were trying to custom run some Python code or something? It doesn't seem related to BBIM.

```
Error evaluating number, see Info editor for details: Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'A' is not defined
```

The third is that a drawing was not able to be generated. It's hard to say exactly what caused this without being able to recreate it with a file. Can't really debug this without knowing more. That's this error:

```
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 253, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 501, in generate_linework
    self.serialiser.write(elem)
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1512, in write
    return _ifcopenshell_wrapper.SvgSerializer_write(self, *args)
RuntimeError: Invalid cast
```

Then there's the error where the cache file seems to be accessed or cannot be moved or something. This is Windows specific, but I'm a little surprised it occurred. Maybe due to a previous error, something wasn't clean and the cache file was still being accessed, or maybe you had more than one session of Blender open with that model... in any case, we can handle that situation and that's now fixed. That's this issue:

```
PermissionError: [WinError 32] Cant access file because used by other process: 'C:\\Users\\Martin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\blenderbim\\bim\\data\\cache\\118ee2c1d38f1c6ca3c1d2df185235f6.h5' -> 'C:\\Users\\Martin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\blenderbim\\bim\\data\\cache\\0ac03c2d0ec32821816cc69630141274.h5'
```

> I closed BlenderBIM and then I opened the .blend file again.

Long story short: never save or open blend files. Especially if a single error occurs and you keep on working, we cannot guarantee that state will be sane. Only save and open IFCs. The IFC is now your native format. The blend file is just like a temporary session.

Now the final issue:

> Most of my vertical dimension annotations have disappeared.

This sounds suspiciously like your annotations were created under a 2D context instead of a 3D context, which should be the default for elevations. There was a point in time where these defaults were not very sane, but I thought they were fixed prior to the last release (I guess you're using the stable version, not the latest unstable). Or maybe this is a different issue entirely.

It sounds depressingly like you're encountering a lot of issues trying to do basic things and it must be frustrating. It's awesome that you're reporting bugs, please keep them coming. Here's some advice:

 1. Upgrade to Blender 4.1.
 2. Upgrade to the latest unstable version of BBIM. Things move very fast: https://docs.blenderbim.org/devs/installation.html#unstable-installation - maybe a bunch of stuff is already fixed? Or if you're willing, [straight from Git](https://docs.blenderbim.org/devs/installation.html#live-development-environment)
 3. Don't load and save .blend files (at least for now). Only load and save IFC. Keep backups.
 4. Some things cannot be treated as vanilla Blender. For example, rather than dragging and dropping around stuff in the collections tree, use the dedicated IFC panels to manage it. Stick to the Scene tab, the other stuff like materials and data and modifiers and so on are all auto managed by BBIM - so if you change it, it'll likely cause things to break subtly or not so subtly. Even basic Blender functions are completely overwritten, like duplicating objects, joining objects, and so on. It looks like a Blender mesh, but it isn't a mesh :) it's IFC.

Clearly we have a huge amount of work still to do. I really appreciate these reports!

**Comment by marwiss** [comment]
Thanks for info!
