### ISSUE TITLE
Error when `bim.create_project()`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4659]
```

Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 107, in execute
    self._execute(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 124, in _execute
    core.create_project(tool.Ifc, tool.Project, schema=props.export_schema, template=template)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\core\project.py", line 37, in create_project
    project.run_root_assign_class(obj=project_obj, ifc_class="IfcProject")
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\project.py", line 105, in run_root_assign_class
    return blenderbim.core.root.assign_class(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\core\root.py", line 70, in assign_class
    root.run_geometry_add_representation(
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\root.py", line 287, in run_geometry_add_representation
    return blenderbim.core.geometry.add_representation(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\core\geometry.py", line 50, in add_representation
    raise IncompatibleRepresentationError()
blenderbim.core.geometry.IncompatibleRepresentationError

```

**Comment by theoryshaw** [comment]
Happened at 
Revision: 3fa573e3c108d1706329a3d25991b3b6bbecfb08
