### ISSUE TITLE
bpy.ops.bim.join_wall(join_type="L") RuntimeError: Instance not found during

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4666]
```
Python: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 591, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 784, in hotkey_S_T
    bpy.ops.bim.join_wall(join_type="L")
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 88, in _execute
    joiner.join_L(another_selected_object, context.active_object)
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 1037, in join_L
    self.recreate_wall(element1, wall1, axis1["reference"], axis1["reference"])
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 1128, in recreate_wall
    extrusion_data = self.get_extrusion_data(tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 425, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 410, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4917, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #16,882 not found
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109
```

**Comment by Andrej730** [comment]
Seems to be same issue as #4667
