### ISSUE TITLE
bpy.ops.bim.recalculate_wall() - RuntimeError: Instance not found

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4667]
```
Python: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 591, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 734, in hotkey_S_G
    bpy.ops.bim.recalculate_wall()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 210, in _execute
    DumbWallRecalculator().recalculate(context.selected_objects)
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 434, in recalculate
    joiner.recreate_wall(element, wall)
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 1128, in recreate_wall
    extrusion_data = self.get_extrusion_data(tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 425, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 410, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4917, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #16,882 not found
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109
```

**Comment by theoryshaw** [comment]
In general, it's hard to troubleshoot just an error message. 

The following things might provide more context, when submitting a bug report. 

- Steps to Reproduce: Provide clear, step-by-step instructions to reproduce the bug. Be specific about actions taken, inputs provided, and expected outcomes.
- Expected Behavior: Describe what you expected to happen when performing the steps above.
- Actual Behavior: Explain what actually happened. Include any error messages, unexpected behaviors, or outcomes.
- Environment: Specify relevant details about your environment, such as operating system, browser version (if applicable), device, software version, etc.
- Screenshots or Videos: If possible, attach screenshots or videos demonstrating the issue. Visuals can greatly aid understanding.
- Attached Files: Upload the file(s) that might be causing the issue. If there are multiple files, compress them into a single archive (e.g., ZIP) before uploading.
- Additional Context: Any additional information that might be helpful in diagnosing or fixing the issue, such as recent changes, relevant logs, or related issues.

**Comment by Andrej730** [comment]
Need an example how to reproduce the issue. From logs it seems to be something during `bpy.ops.bim.recalculate_wall()`.
#4666 appears to be the same issue but during `bpy.ops.bim.join_wall(join_type="L")`

**Comment by Moult** [comment]
See #4671.
