### ISSUE TITLE
self.mesh.materials.append(self.styles[surface_style[0].id()]) KeyError

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4671]
```
Python: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 591, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 734, in hotkey_S_G
    bpy.ops.bim.recalculate_wall()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 210, in _execute
    DumbWallRecalculator().recalculate(context.selected_objects)
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 434, in recalculate
    joiner.recreate_wall(element, wall)
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 1252, in recreate_wall
    blenderbim.core.geometry.switch_representation(
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\core\geometry.py", line 133, in switch_representation
    new_repr_data = geometry.import_representation(obj, representation, apply_openings=apply_openings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\geometry.py", line 540, in import_representation
    ifc_importer.material_creator.create(element, obj, mesh)
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 68, in create
    self.add_default_material(element)
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 84, in add_default_material
    self.mesh.materials.append(self.styles[surface_style[0].id()])
                               ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 9281
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109
```

**Comment by blenderarc** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 591, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 734, in hotkey_S_G
    bpy.ops.bim.recalculate_wall()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 210, in _execute
    DumbWallRecalculator().recalculate(context.selected_objects)
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 434, in recalculate
    joiner.recreate_wall(element, wall)
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 1252, in recreate_wall
    blenderbim.core.geometry.switch_representation(
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\core\geometry.py", line 133, in switch_representation
    new_repr_data = geometry.import_representation(obj, representation, apply_openings=apply_openings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\geometry.py", line 540, in import_representation
    ifc_importer.material_creator.create(element, obj, mesh)
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 68, in create
    self.add_default_material(element)
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 84, in add_default_material
    self.mesh.materials.append(self.styles[surface_style[0].id()])
                               ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 9281
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109

**Comment by IvoHvP** [comment]
Same here for some weeks now

**Comment by Andrej730** [comment]
@blenderarc @IvoHvP can you please show a way to reproduce this? Need an example .ifc file and steps to recreate the issue.

**Comment by Moult** [comment]
This is almost certainly a sync issue between the IFC and the Blend. Unfortunately it's really hard to know exactly without more details from @blenderarc. There are a number of issues which all exhibit the exact same symptoms from @blenderarc which all probably can be resolved by using BBIM as a native IFC editor rather than expecting to use a .blend as as the main file.
