### ISSUE TITLE
Error enabling BlenderBIM on Blender 3.6 / 4.0 - IfcOpenShell not built for 'windows\64bit\python3.10'

### ISSUE THREAD

**Issue by IvoHvP** [IfcOpenShell/IfcOpenShell#4672]
I cleaned the Roaming map and installed Blender 3.6 again. A Same with 4.0. And according to the site, only 4,1 needs a special installation. I don't have the older version of BlenderBIM anymore. Are those still available? (for the time) 

```
Traceback (most recent call last):
  File "C:\Users\IvoSc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _ifcopenshell_wrapper: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\IvoSc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 61, in <module>
    from . import ifcopenshell_wrapper
  File "C:\Users\IvoSc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 17, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
  File "C:\Users\IvoSc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_ifcopenshell_wrapper')
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\IvoSc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\__init__.py", line 41, in <module>
    import blenderbim.bim
  File "C:\Users\IvoSc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\IvoSc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\handler.py", line 23, in <module>
    import ifcopenshell.api.owner.settings
  File "C:\Users\IvoSc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 69, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.10'
```

**Comment by Andrej730** [comment]
What version of BBIM you're using? It seems like you're using the one that requries Python 3.11 (Blender 4.1) on Blender with Python 3.10 (4.0 and prior).

Try unstable installation - https://docs.blenderbim.org/devs/installation.html#unstable-installation as suggested in installation: https://docs.blenderbim.org/users/installation.html.

Make sure to unistall the addon by instruction - https://docs.blenderbim.org/users/installation.html#uninstalling

**Comment by Moult** [comment]
Bump @IvoHvp - if you still have issues you can also reach out at https://osarch.org/chat - but most likely you've simply not downloaded the correct version for your Blender.
