### ISSUE TITLE
Feature request? Have the possibility to split elements

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4675]
Splitting elements today, IFC natively is not so straightforward. Is it possible to do anything about this so it's easy to split a slab for example into more? This is useful in the cast-in-place context, to define the casting sequences.

**Comment by Moult** [comment]
There is a tool available to split specifically for this purpose (e.g. slab pours) in the Miscellaneous panel called "Split Along Edge".

 1. Draw your split plane
 2. Select both plane and slab (or wall or whatever)
 3. Press button

![2024-05-16-102314_270x402_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/d2c50bcc-35a5-4b50-9163-c45cec61dac1)

**Comment by BIMvoice** [comment]
Awesome stuff Dion, that this is already available. I get an error though:

`File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\geometry.py", line 660, in resolve_mapped_representation
    if representation.RepresentationType == "MappedRepresentation":
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'RepresentationType'`

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/e0d18638-ab76-49f3-adbc-5d91e52cf903)

P.S. Copy error message to the clipboard does not work btw.

**Comment by theoryshaw** [comment]
maybe you did this, but try the slicing plane this way...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/af3c403b-4de8-4dc3-a71b-21ba705ba2e4)

**Comment by BIMvoice** [comment]
It is very strange. I keep getting error. But weirdly enough only once it worked. After undoing everything and trying again, I keep getting the same error.

I tried both, to select the slab first and then the plane, and the other way around. I do this on windows now, Blender 4.1 with this week BBIM release.

`last_actions:
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 218, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 73, "Name": "Slab"}, "representation": {"cast_type": "entity_instance", "value": 156, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 156, "Name": null}}
# operator: BIM_OT_override_object_delete
# operator: BIM_OT_split_along_edge
# operator: BIM_OT_split_along_edge
# operator: BIM_OT_split_along_edge
# operator: BIM_OT_split_along_edge
# operator: BIM_OT_split_along_edge
# operator: BIM_OT_split_along_edge
last_error: Traceback (most recent call last):
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\misc\operator.py", line 156, in _execute
    representation = tool.Geometry.get_active_representation(obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\geometry.py", line 325, in get_active_representation
    return tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 425, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 410, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4917, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #88 not found

ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: IfcOpenShell v0.7.0-f7c03db75
--------------------------------------------------------------------------------
os: WindowsTraceback (most recent call last):
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\misc\operator.py", line 32, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\misc\operator.py", line 156, in _execute
    representation = tool.Geometry.get_active_representation(obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\geometry.py", line 325, in get_active_representation
    return tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 425, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 410, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4917, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #88 not found
Error: Python: Traceback (most recent call last):
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\misc\operator.py", line 156, in _execute
    representation = tool.Geometry.get_active_representation(obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\geometry.py", line 325, in get_active_representation
    return tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 425, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 410, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4917, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #88 not found`

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/d896541e-151c-4234-a12b-75e80ea38a2f)

**Comment by Andrej730** [comment]
@BIMvoice please format logs with markdown code blocks - https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

**Comment by Plae-Blue-Dot** [comment]
It seems it only works if the splitting plane has all its transforms applied, otherwise it wont perform the split
could be included as a line in the description note:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/e96c4265-9e96-430e-878d-a7860b34c886)
