### ISSUE TITLE
Bug in BCF output report in the python `ifctester` package

### ISSUE THREAD

**Issue by philipperenzen** [IfcOpenShell/IfcOpenShell#4680]
Hi IfcOpenShell community, 

Whilst using the `ifctester` package, namely the `reporter` and `ids` modules, I get an error when I attempt to create a BCF output file. The bug seems to originate in the `bcf` module  in the `xml_parser.py` file.

The error I receive is: 
```
Traceback (most recent call last):
  File "/Users/work/Desktop/projects/./python/MWEbcfIssue.py", line 38, in <module>
    validateIds('IDS_wooden-windows_IFC.ifc', 'IDS_wooden-windows.ids', 'output.bcf')
  File "/Users/work/Desktop/projects/./python/MWEbcfIssue.py", line 28, in validateIds
    bcf_reporter.to_file(bcf_report_destination_path)
  File "/opt/homebrew/lib/python3.12/site-packages/ifctester/reporter.py", line 540, in to_file
    bcfxml = BcfXml.create_new(self.results["title"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/bcf/v2/bcfxml.py", line 143, in create_new
    instance = cls(xml_handler=xml_handler or XmlParserSerializer())
                                              ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/bcf/xml_parser.py", line 59, in __init__
    self.parser = build_xml_parser(self.context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/bcf/xml_parser.py", line 13, in build_xml_parser
    parser.register_namespace("xs", "http://www.w3.org/2001/XMLSchema")
TypeError: PushParser.register_namespace() missing 1 required positional argument: 'uri'
```

## Minimal working example:
For this example I use the IFC and IDS files provided here by the buildingSMART organization:
* IFC file: [**IDS_wooden-windows_IFC.ifc**](https://github.com/buildingSMART/IDS/blob/master/Development/IDS_wooden-windows_IFC.ifc)
* IDS file [**IDS_wooden-windows.ids**](https://github.com/buildingSMART/IDS/blob/master/Development/IDS_wooden-windows.ids)
```python
import ifcopenshell
from ifctester import ids, reporter

def validateIds(source_ifc_path: str, source_ids_path: str, bcf_report_destination_path: str):
    try:
        ids_file = ids.open(source_ids_path)
    except Exception as e:
        print(f'ERROR! There was an error reading the provided IDS file: {source_ids_path}\nThe error message:\n')
        raise e

    try:
        ifc_file = ifcopenshell.open(source_ifc_path)
    except Exception as e:
        print(f'ERROR! There was an error reading the provided IFC file: {source_ifc_path}\nThe error message:\n')
        raise e

    # validate IFC model against IDS requirements:
    ids_file.validate(ifc_file)

    # Only the JSON reporter object seems to have access to the status
    json_report = reporter.Json(ids_file)
    status = json_report.report()['status']

    # Initialize and report with BCF reporter if path is provided
    if bcf_report_destination_path:
        bcf_reporter = reporter.Bcf(ids_file)
        bcf_reporter.report()
        bcf_reporter.to_file(bcf_report_destination_path)

    # Check overall status and print success or failure message
    if status == True:
        print(f"IFC IDS validation passed! The IFC model meets all IDS requirements.\nThe resulting BCF file is available here: {bcf_report_destination_path}")
    else:
        raise Exception(f"IFC IDS validation failed! The IFC model does not meet all IDS requirements.\nThe resulting BCF file is available here: {bcf_report_destination_path}")

validateIds('path/to/IDS_wooden-windows_IFC.ifc', 'path/to/IDS_wooden-windows.ids', 'path/to/output.bcf')
```

**Comment by philipperenzen** [comment]
@Andrej730 apologies, I was adjusting the content of my issue, as I accidently posted this issue too early by pressing `ctrl + enter` 😅

**Comment by Andrej730** [comment]
@philipperenzen thanks for the detailed bug report! Issue is fixed now. PyPI will update tomorrow.
