### ISSUE TITLE
Error when editing a 2D representation in IFC2X3

### ISSUE THREAD

**Issue by jsaarane** [IfcOpenShell/IfcOpenShell#4685]
Blenderbim won't let me save edits on my 2d representation.

```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240517
last_actions: 
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 2152273, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcLightFixtureType/MeyerSuperlightLED3\") at 0x0000019A01B9AB08>", "geometry": "<bpy_struct, Mesh(\"2152273/2183374\") at 0x0000019A82174808>", "coordinate_offset": "None", "total_items": "2", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 2152273, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcLightFixtureType/MeyerSuperlightLED3\") at 0x0000019A01B9AB08>", "geometry": "<bpy_struct, Mesh(\"2152273/2183374\") at 0x0000019A82174808>", "coordinate_offset": "None", "total_items": "2", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
last_error: Traceback (most recent call last):
  File "C:\Users\JoonasSaaranen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JoonasSaaranen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1629, in _execute
    bpy.ops.bim.update_representation(obj=obj.name, ifc_representation_class="")
  File "C:\Users\JoonasSaaranen\Documents\blender-4.1.1-windows-x64\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\JoonasSaaranen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JoonasSaaranen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 324, in _execute
    self.update_obj_mesh_representation(context, obj)
  File "C:\Users\JoonasSaaranen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 405, in update_obj_mesh_representation
    if tool.Geometry.is_body_representation(new_representation):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JoonasSaaranen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\geometry.py", line 574, in is_body_representation
    return representation.ContextOfItems.ContextIdentifier == "Body"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ContextOfItems'
Location: C:\Users\JoonasSaaranen\Documents\blender-4.1.1-windows-x64\4.1\scripts\modules\bpy\ops.py:109


ifc: OMTK_VAL.ifc
schema: IFC2X3
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: BlenderBIM 0.0.240517-da4ce37

```

https://github.com/IfcOpenShell/IfcOpenShell/assets/13415484/fb8a4d4c-9c9b-48ba-a2d0-c737ad018cfe

**Comment by Andrej730** [comment]
Unrelated to ifc2x3, it's the issue with applying curve representations if they are not consecutive:

https://github.com/IfcOpenShell/IfcOpenShell/blob/8662e20c58a824f1ba6d8a6d7928b4284e41766f/src/ifcopenshell-python/ifcopenshell/api/geometry/add_representation.py#L503-L508

**Comment by Andrej730** [comment]
thanks for the bug report, resolved in the latest build in github releases

**Comment by Plae-Blue-Dot** [comment]
I think I am getting the same error here:

os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
blender_version: 4.1.1
blenderbim_version: 0.0.240516
last_actions: 
# ifcopenshell.api: spatial.assign_container
>>> {"products": [{"cast_type": "entity_instance", "value": 40818, "Name": "Window.026"}], "relating_structure": {"cast_type": "entity_instance", "value": 42, "Name": "Ground Floor"}}
# ifcopenshell.api: spatial.assign_container
>>> {"products": [{"cast_type": "entity_instance", "value": 41019, "Name": "Window.027"}], "relating_structure": {"cast_type": "entity_instance", "value": 42, "Name": "Ground Floor"}}
# ifcopenshell.api: spatial.assign_container
>>> {"products": [{"cast_type": "entity_instance", "value": 41365, "Name": "Window.028"}], "relating_structure": {"cast_type": "entity_instance", "value": 42, "Name": "Ground Floor"}}
# ifcopenshell.api: spatial.assign_container
>>> {"products": [{"cast_type": "entity_instance", "value": 41759, "Name": "Window.029"}], "relating_structure": {"cast_type": "entity_instance", "value": 42, "Name": "Ground Floor"}}
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 29, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/LINEWORK.008\") at 0x000001B293272B08>", "geometry": "<bpy_struct, Mesh(\"29/156380\") at 0x000001B293943208>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
last_error: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1629, in _execute
    bpy.ops.bim.update_representation(obj=obj.name, ifc_representation_class="")
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 332, in __setitem__
    self.wrapped_data.setArgumentAsNull(idx)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 5285, in setArgumentAsNull
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsNull(self, i)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Attribute not set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 324, in _execute
    self.update_obj_mesh_representation(context, obj)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 403, in update_obj_mesh_representation
    new_representation = ifcopenshell.api.run("geometry.add_representation", self.file, **representation_data)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 184, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 344, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 92, in add_representation
    return usecase.execute()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 108, in execute
    return self.create_plan_representation()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 205, in create_plan_representation
    return self.create_annotation2d_representation()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 868, in create_annotation2d_representation
    items = [self.file.createIfcGeometricCurveSet(self.create_curves(is_2d=True))]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 353, in create_entity
    e[idx] = arg
    ~^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 335, in __setitem__
    raise ValueError(
ValueError: attribute 'Elements' is not optional for entity instance of type 'IFC4.IfcGeometricCurveSet'
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\modules\bpy\ops.py:109


ifc: Censored - 2024.05.17alt.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: BlenderBIM 0.0.240516-9969de5

------------------------------------------------------------------------------
Is it no longer possible to have a 2d line with multiple disconnected lines?
I use it that way in almost all my drawings, it's incredibly useful

**Comment by Plae-Blue-Dot** [comment]
> in github releases

Timing is great, I'll check on the newer release
