### ISSUE TITLE
BBIM - Tracing Outline bug / Fix creating geometric curve set 

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#4688]
Trying to add a plan representation of an object, by tracing its outline : When I press:

context = Plan/Annotation/PLAN_VIEW
bpy.ops.bim.add_representation(representation_conversion_method='OUTLINE')

Error:

```
Traceback (most recent call last):
  File "blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "blenderbim\bim\module\geometry\operator.py", line 181, in _execute
    core.add_representation(
  File "blenderbim\core\geometry.py", line 52, in add_representation
    representation = ifc.run(
  File "blenderbim\tool\ifc.py", line 34, in run
    return ifcopenshell.api.run(command, IfcStore.get_file(), **kwargs)
  File "ifcopenshell\api\__init__.py", line 166, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
  File "ifcopenshell\api\__init__.py", line 326, in wrapper
    result = usecase(*args, **settings)
  File "ifcopenshell\api\geometry\add_representation.py", line 64, in add_representation
    return usecase.execute()
  File "ifcopenshell\api\geometry\add_representation.py", line 80, in execute
    return self.create_plan_representation()
  File "ifcopenshell\api\geometry\add_representation.py", line 177, in create_plan_representation
    return self.create_annotation2d_representation()
  File "ifcopenshell\api\geometry\add_representation.py", line 840, in create_annotation2d_representation
    items = [self.file.createIfcGeometricCurveSet(self.create_curves(is_2d=True))]
  File "ifcopenshell\file.py", line 353, in create_entity
    e[idx] = arg
  File "ifcopenshell\entity_instance.py", line 335, in __setitem__
    raise ValueError(
ValueError: attribute 'Elements' is not optional for entity instance of type 'IFC4.IfcGeometricCurveSet'

```

**Comment by theoryshaw** [comment]
I'm thinking this was resolved via: https://github.com/IfcOpenShell/IfcOpenShell/issues/4670
closing, but please open if still an issue.
