### ISSUE TITLE
MeasureIt_ARCH dependency conflict

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4691]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/140309875/42186d7e-f2b7-46aa-99d4-1a6eba2d9b32)

**Comment by ppaawweeuu** [comment]
@blenderarc  BlenderBIM could not load.
Try be more precise, pls. Can you copy and paste here console error?

**Comment by ppaawweeuu** [comment]
ough, i got the same :/ BBIM 0.0.240518

```
os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
blender_version: 4.0.1
blenderbim_version: 0.0.240518
last_actions:
last_error: Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\__init__.py", line 88, in <module>
    import blenderbim.bim
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\handler.py", line 23, in <module>
    import ifcopenshell.api.owner.settings
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 85, in <module>
    from .file import file
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 179, in <module>
    class file:
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 382, in file
    def __getattr__(self, attr) -> Union[Any, Callable[..., ifcopenshell.entity_instance]]:
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\typing.py", line 1206, in __getitem__
    return self.__getitem_inner__(params)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\typing.py", line 312, in inner
    return func(*args, **kwds)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\typing.py", line 1212, in __getitem_inner__
    result = _type_check(result, msg)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Callable[args, result]: result must be a type. Got <module 'ifcopenshell.entity_instance' from 'C:\\Users\\user_name\\AppData\\Roaming\\Blender F.

FATAL ERROR: Unable to load the BlenderBIM Add-on
WARN (asset_system.asset_catalog_service): C:\Users\blender\git\blender-v400\blender.git\source\blender\asset_system\intern\asset_catalog.cc:328 load_from_disk: path not found: C:\ProgramData\Blender Foundation\Blender\4.0\datafiles\icons\
```

**Comment by ppaawweeuu** [comment]
same with bb 0.0.240517, 0.0.240516 and 0.0.240515
0.0.240514 seems to be ok.

**Comment by Moult** [comment]
I tested with the latest 0.0.240518 release on both Windows and Linux with a fresh install and was not able to replicate. Maybe this issue is local to your environment?

@ppaawweeuu note that you specifically need to install the Windows py310 variant.

Can both of you try following the instructions in https://docs.blenderbim.org/users/troubleshooting.html to get a fresh environment? Potentially there is something from an older installation mucking things up. Also feel free to drop by the [OSArch chatroom](https://osarch.org/chat) in case we need a screenshare.

**Comment by blenderarc** [comment]
os: Windows
os_version: 10.0.22621
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240519
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 88, in <module>
    import blenderbim.bim
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\__init__.py", line 94, in <module>
    modules[name] = importlib.import_module(f"blenderbim.bim.module.{name}")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\bcf\__init__.py", line 20, in <module>
    from . import ui, prop, operator
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\bcf\ui.py", line 21, in <module>
    from . import bcfstore
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\bcf\bcfstore.py", line 22, in <module>
    import bcf.v2.bcfxml
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\bcf\v2\bcfxml.py", line 10, in <module>
    from bcf.v2.topic import TopicHandler
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\bcf\v2\topic.py", line 16, in <module>
    from bcf.v2.visinfo import VisualizationInfoHandler
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\bcf\v2\visinfo.py", line 18, in <module>
    from bcf.xml_parser import AbstractXmlParserSerializer, XmlParserSerializer
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\bcf\xml_parser.py", line 4, in <module>
    from xsdata.formats.dataclass.context import XmlContext
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\xsdata\formats\dataclass\context.py", line 7, in <module>
    from xsdata.formats.dataclass.models.builders import XmlMetaBuilder
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\xsdata\formats\dataclass\models\builders.py", line 23, in <module>
    from xsdata.formats.dataclass.typing import (
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\xsdata\formats\dataclass\typing.py", line 18, in <module>
    from typing_extensions import ForwardRef
ImportError: cannot import name 'ForwardRef' from 'typing_extensions' (C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MeasureIt_ARCH-development\libs\typing_extensions.py)

**Comment by Moult** [comment]
@blenderarc can you please try to follow the troubleshooting steps? That error looks as though it's to do with the MeasureIt-ARCH add-on, not the BlenderBIM Add-on.

**Comment by Andrej730** [comment]
@blenderarc 

That's basically dependency version conflict with MeasureIt_ARCH. typing_extensions is not default python library, MeasureIt_ARCH is using 2 years old version of this module (https://github.com/kevancress/MeasureIt_ARCH/blob/development/libs/typing_extensions.py) but for BlenderBIM our dependency `xsdata` requires newer version that does have `ForwardRef`.

How to resolve it:
1) Download the latest build as I'm not sure if explicitly included `typing_extensions.py` to the build before f666053.
2) Disable both BlenderBIM and MeasureIt_ARCH addons.
3) Restart Blender.
4) Enable BlenderBIM first, so it will load BBIM's dependency first.
5) Enable MeasureIt_ARCH.

**Comment by Moult** [comment]
Also given that they are using a 2 year old module, I'd say it's also a good idea to file a bug with MeasureIt_ARCH to bump their dependencies :) Thanks @andrej730 !

**Comment by Andrej730** [comment]
@ppaawweeuu 

>TypeError: Callable[args, result]: result must be a type. Got <module 'ifcopenshell.entity_instance' from


it's a different error, resolved after 7c6c01e6b, try the latest build

**Comment by Andrej730** [comment]
> How to resolve it:
> 
> 1. Download the latest build as I'm not sure if previously we explicitly included `typing_extensions.py` to the build before [f666053](https://github.com/IfcOpenShell/IfcOpenShell/commit/f666053b63023b113e81ea9ba5d20676e94f771c).
> 2. Disable both BlenderBIM and MeasureIt_ARCH addons.
> 3. Restart Blender.
> 4. Enable BlenderBIM first, so it will load BBIM's dependency first.
> 5. Enable MeasureIt_ARCH.

@blenderarc instructions how to resolve your issue.

**Comment by blenderarc** [comment]
thanks @Moult @Andrej730

**Comment by danielraziel** [comment]
> @blenderarc
> 
> That's basically dependency version conflict with MeasureIt_ARCH. typing_extensions is not default python library, MeasureIt_ARCH is using 2 years old version of this module (https://github.com/kevancress/MeasureIt_ARCH/blob/development/libs/typing_extensions.py) but for BlenderBIM our dependency `xsdata` requires newer version that does have `ForwardRef`.
> 
> How to resolve it:
> 
> 1. Download the latest build as I'm not sure if previously we explicitly included `typing_extensions.py` to the build before [f666053](https://github.com/IfcOpenShell/IfcOpenShell/commit/f666053b63023b113e81ea9ba5d20676e94f771c).
> 2. Disable both BlenderBIM and MeasureIt_ARCH addons.
> 3. Restart Blender.
> 4. Enable BlenderBIM first, so it will load BBIM's dependency first.
> 5. Enable MeasureIt_ARCH.

Thanks This worked for me! I also made blender run as administrator by default.
