### ISSUE TITLE
blenderbim cloud not load

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4692]
os: Windows
os_version: 10.0.22621
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240518
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 88, in <module>
    import blenderbim.bim
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\__init__.py", line 94, in <module>
    modules[name] = importlib.import_module(f"blenderbim.bim.module.{name}")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\bcf\__init__.py", line 20, in <module>
    from . import ui, prop, operator
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\bcf\ui.py", line 21, in <module>
    from . import bcfstore
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\bcf\bcfstore.py", line 22, in <module>
    import bcf.v2.bcfxml
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\bcf\v2\bcfxml.py", line 10, in <module>
    from bcf.v2.topic import TopicHandler
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\bcf\v2\topic.py", line 16, in <module>
    from bcf.v2.visinfo import VisualizationInfoHandler
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\bcf\v2\visinfo.py", line 18, in <module>
    from bcf.xml_parser import AbstractXmlParserSerializer, XmlParserSerializer
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\bcf\xml_parser.py", line 4, in <module>
    from xsdata.formats.dataclass.context import XmlContext
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\xsdata\formats\dataclass\context.py", line 7, in <module>
    from xsdata.formats.dataclass.models.builders import XmlMetaBuilder
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\xsdata\formats\dataclass\models\builders.py", line 23, in <module>
    from xsdata.formats.dataclass.typing import (
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\xsdata\formats\dataclass\typing.py", line 18, in <module>
    from typing_extensions import ForwardRef
ImportError: cannot import name 'ForwardRef' from 'typing_extensions' (C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MeasureIt_ARCH-development\libs\typing_extensions.py)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/140309875/89834d2c-7f32-445f-b369-fb440053d26d)

**Comment by Moult** [comment]
See #4691. This is most likely the same issue.
