### ISSUE TITLE
BBIM | creation of new window or door triggers error

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#4719]
I have installed the latest 240521 or 240522
if I start a blank IFC (not the demo one) and I want to create a new door type it throws an error

os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
blender_version: 4.1.0
blenderbim_version: 0.0.240522
last_actions: 
# operator: BIM_OT_join_wall
# ifcopenshell.api: geometry.disconnect_path
>>> {"element": {"cast_type": "entity_instance", "value": 73, "Name": "Wall"}, "connection_type": "ATEND"}
# ifcopenshell.api: geometry.add_axis_representation
>>> {"context": {"cast_type": "entity_instance", "value": 27, "Name": null}, "axis": "[Vector((0.0, 0.0)), Vector((4.627577304840088, 0.0))]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 73, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 80, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 80, "Name": null}}
# ifcopenshell.api: geometry.add_wall_representation
>>> {"context": {"cast_type": "entity_instance", "value": 15, "Name": null}, "length": "4.627577398591628", "height": "3.0", "x_angle": "0", "offset": "0.0", "thickness": "0.1", "clippings": "[]", "booleans": "[]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 73, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 96, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 96, "Name": null}}
# operator: BIM_OT_add_default_type
# operator: BIM_OT_add_type
last_error: Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\product.py", line 117, in _execute
    bpy.ops.bim.add_type()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\type\operator.py", line 434, in _execute
    element = blenderbim.core.root.assign_class(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: assign_class() missing 1 required positional argument: 'context'
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109

ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: IfcOpenShell v0.7.0-f7c03db75

**Comment by Plae-Blue-Dot** [comment]
I have the same issue

**Comment by Andrej730** [comment]
Thanks for the bug report, fixed after df15a37.

**Comment by steverugi** [comment]
Excellent job @Andrej730 many , many thanks
