### ISSUE TITLE
Need help with Live Development Environment

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#4733]
I have successfully setup bbim with v0.8.0 compiled from source and a live development environment on one computer. I'm trying to set the same environment up on another computer, but it isn't working.

The obvious differences between the setup on the two computers are:
- Good Setup
   - Open and New IFC Project show up on the File menu
   - Edit > Preferences > Add-ons: there is a lot of information in a "Preferences" section below the Remove button (see image below)
- Bad Setup
   - No IFC Project comments on the File menu
   - Edit > Preferences > Add-ons: No "Preferences" section below the Remove button (see image below)

I've done side by side comparisons of the directory tree and the look exactly the same.

Any ideas?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/37087370/674ad4f0-acee-4368-91f6-5c9b3e04857e)

**Comment by Moult** [comment]
In the console (on windows you can do Window > Toggle System Console) are there any errors?

**Comment by RickBrice** [comment]
Here is the error log.

Read prefs: "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\config\userpref.blend"
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 41, in <module>
    import blenderbim.bim
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\__init__.py", line 20, in <module>
    from blenderbim.tool.blender import Blender
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\blender.py", line 29, in <module>
    from blenderbim.bim.ifc import IFC_CONNECTED_TYPE
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 26, in <module>
    import ifcopenshell.geom
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\__init__.py", line 49, in <module>
    from .main import *
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 115, in <module>
    class settings(settings_mixin, ifcopenshell_wrapper.Settings):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ifcopenshell.ifcopenshell_wrapper' has no attribute 'Settings'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 41, in <module>
    import blenderbim.bim
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\__init__.py", line 20, in <module>
    from blenderbim.tool.blender import Blender
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\blender.py", line 29, in <module>
    from blenderbim.bim.ifc import IFC_CONNECTED_TYPE
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 26, in <module>
    import ifcopenshell.geom
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\__init__.py", line 49, in <module>
    from .main import *
  File "C:\Users\rickb\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 115, in <module>
    class settings(settings_mixin, ifcopenshell_wrapper.Settings):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ifcopenshell.ifcopenshell_wrapper' has no attribute 'Settings'

**Comment by Moult** [comment]
I don't see anything there that jumps out. I guess I would just try again from a fresh start. I.e. start with a [clean env](https://docs.blenderbim.org/users/troubleshooting.html#installation-issues), install, make sure regular install works, then run the [batch script](https://docs.blenderbim.org/devs/installation.html#live-development-environment) but look at it carefully for any errors during the batch script phase.

I'm also available online at https://osarch.org/chat if you want to live screenshare / debug together.

**Comment by RickBrice** [comment]
Thanks. I’ll start clean and try again. If problems persist I’ll reach out on chat.

**Comment by theoryshaw** [comment]
@RickBrice you might have done this already, but when running the cmd, to run your bat script, run it in admin mode.

**Comment by RickBrice** [comment]
@theoryshaw Thanks - I tried that. Somehow the ifcopenshell_wrapper.py file is different between the install that works and the one that doesn't. I've taken the nuclear option and started over.
