### ISSUE TITLE
Costing and scheduling, Work Calander, add Exception times-errors

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4734]
![Skermskoot (105)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/d473ec3f-8cb3-47dc-bf04-37a7ce5e105c)
[HFCC-Chrech Toilet.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15444489/HFCC-Chrech.Toilet.txt)
This is the following error code when trying to add public holidays into the works calendar. Nothing happens when trying to add “Yearly and specified dates”, is this for one or more than one “home” day. Maybe it could be user-friendly to include (yyyy/mm/dd) for example “Start (hh:mm)”

```
os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.0.240525
last_actions: 
# operator: BIM_OT_assign_recurrence_pattern
# ifcopenshell.api: sequence.assign_recurrence_pattern
>>> {"parent": {"cast_type": "entity_instance", "value": 16440, "Name": null}, "recurrence_type": "YEARLY_BY_DAY_OF_MONTH"}
# operator: BIM_OT_assign_recurrence_pattern
# ifcopenshell.api: sequence.assign_recurrence_pattern
>>> {"parent": {"cast_type": "entity_instance", "value": 16440, "Name": null}, "recurrence_type": "YEARLY_BY_DAY_OF_MONTH"}
# operator: BIM_OT_assign_recurrence_pattern
# ifcopenshell.api: sequence.assign_recurrence_pattern
>>> {"parent": {"cast_type": "entity_instance", "value": 16440, "Name": null}, "recurrence_type": "YEARLY_BY_DAY_OF_MONTH"}
# operator: BIM_OT_edit_work_time
# ifcopenshell.api: sequence.edit_work_time
>>> {"work_time": {"cast_type": "entity_instance", "value": 16440, "Name": null}, "attributes": "{'Name': 'Publick holidays', 'DataOrigin': None, 'UserDefinedDataOrigin': None, 'Start': None, 'Finish': None}"}
# operator: BIM_OT_edit_work_time
# ifcopenshell.api: sequence.edit_work_time
>>> {"work_time": {"cast_type": "entity_instance", "value": 16440, "Name": "Publick holidays"}, "attributes": "{'Name': 'Publick holidays', 'DataOrigin': None, 'UserDefinedDataOrigin': None, 'Start': None, 'Finish': None}"}
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\sequence\operator.py", line 867, in _execute
    core.edit_work_time(tool.Ifc, tool.Sequence)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\core\sequence.py", line 360, in edit_work_time
    ifc.run("sequence.edit_work_time", work_time=work_time, attributes=sequence.get_work_time_attributes())
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\ifc.py", line 34, in run
    return ifcopenshell.api.run(command, IfcStore.get_file(), **kwargs)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 184, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 350, in wrapper
    raise e
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 344, in wrapper
    result = usecase(*args, **settings)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\sequence\edit_work_time.py", line 61, in edit_work_time
    value = ifcopenshell.util.date.datetime2ifc(value, "IfcDate")
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\date.py", line 160, in datetime2ifc
    raise TypeError(f"Unsupported ifc_type for conversion from datetime.datetime = {ifc_type}.")
TypeError: Unsupported ifc_type for conversion from datetime.datetime = IfcDate.
```

ifc: HFCC-Chrech Toilet.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: BlenderBIM 0.0.240525-b087aa0

**Comment by Andrej730** [comment]
should be fixed now, it was an issue occurring if Start / Finish date is a null.

**Comment by Ave-5D** [comment]
Thank you Andre
