### ISSUE TITLE
4D sample model yielding error

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4747]
I get this error when I try to open the sample file Yassine has shared for his 4D crash course.

The file from the start folder: https://www.consult-bim.com/courses/bbim_4_beginners/BBIM4B3-3

The one in the folder "end" can be opened.

````
os: Windows
os_version: 10.0.19044
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 154 Stepping 4, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240527
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 691, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 771, in execute
    ifc_importer.execute()
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 265, in execute
    self.create_collections()
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 1607, in create_collections
    self.create_aggregate_and_nest_collections()
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 1665, in create_aggregate_and_nest_collections
    ] + [
        ^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 1669, in <listcomp>
    (relating_obj := r.RelatingObject).is_a("IfcElement")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_a'
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109


ifc: 3D.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-9cc1f5f0e
originating_system: BlenderBIM 0.0.230906-f1a5805
````

**Comment by Moult** [comment]
This is unfortunately just a bug that Yassine needs to sort out. It's an invalid model.
