### ISSUE TITLE
[BBIM] error on appending element from default IFC4 project library to IFC4X3 project

### ISSUE THREAD

**Issue by dirkolbrich** [IfcOpenShell/IfcOpenShell#4766]
I get the following error when I try to append a library element from one of the supplied default IFC4 libraries to an IFC4X3 project.

As the newly created project uses the IFC4X3 schema, an import from an IFC4 library file should be automatically migrated to the newer standard.

Steps to reproduce:
- start Blender
- switch to BIM workspace
- Property Editor -> Project overview -> section Project Info -> under IFC Schema select IFC4X3 from the dropdown menu -> Create Project
- Property Editor -> Project overview -> section Project Setup -> Project Library -> select IFC3 Furniture Library from the dropdown menu
- select IfcTypeProduct -> press little arrow
- select IfcFurnitureType -> press little arrow
- select one of the elements from the list, e.g. `Double bed` or `Generic Large Desk`
- append library element to the current IFC project by selecting the paper clip icon next to the element entry
- the error occurs

Copied error message:
```
os: Darwin
os_version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
python_version: 3.11.7
architecture: ('64bit', '')
machine: arm64
processor: arm
blender_version: 4.1.1
blenderbim_version: 0.0.240530
last_actions: 
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 36, "Name": "My Building"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 36, "Name": "My Building"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}], "relating_object": {"cast_type": "entity_instance", "value": 36, "Name": "My Building"}}
# ifcopenshell.api: spatial.unassign_container
>>> {"products": "[]"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}}
# operator: BIM_OT_append_library_element
# ifcopenshell.api: project.append_asset
>>> {"library": "<ifcopenshell.file.file object at 0x3270d9090>", "element": {"cast_type": "entity_instance", "value": 9720, "Name": "Generic Large Desk"}}
last_error: Traceback (most recent call last):
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/module/project/operator.py", line 436, in _execute
    element = ifcopenshell.api.run(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 184, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 344, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/project/append_asset.py", line 124, in append_asset
    return usecase.execute()
           ^^^^^^^^^^^^^^^^^
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/project/append_asset.py", line 140, in execute
    return self.append_type_product()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/project/append_asset.py", line 192, in append_type_product
    element = self.add_element(self.settings["element"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/project/append_asset.py", line 236, in add_element
    new = self.file.add(element)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 454, in add
    result = entity_instance(self.wrapped_data.add(inst.wrapped_data, -1 if _id is None else _id), self)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dirkolbrich/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3840, in add
    return _ifcopenshell_wrapper.file_add(self, entity, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unabled to add instance from IFC4 schema to file with IFC4X3_ADD2 schema

ifc: Unsaved
schema: IFC4X3
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: IfcOpenShell v0.7.0-f7c03db75
```

**Comment by RoadCaddie-TW** [comment]
I am getting a similar issue in python script:

ifcopenshell_wrapper.py", line 4976, in add
    return _ifcopenshell_wrapper.file_add(self, entity, id)
RuntimeError: Unabled to add instance from IFC4X3_RC4 schema to file with IFC4X3_ADD2 schema

Not sure where to go from here...

**Comment by dirkolbrich** [comment]
I traced it back to this line in `ifcparse/IfcParse.cpp`:
https://github.com/IfcOpenShell/IfcOpenShell/blob/e2dc5f4a485d8f3ca8285fa87bc7f1d73125cd38/src/ifcparse/IfcParse.cpp#L1884-L1886
Here it tries to add the Entity (e.g. IfcProduct) to the model, but does a schema check first. If the schemas deviate, the function throws an error.

So ultimately it is missing functionality in the IfcOS kernel. Instead of just throwing an error, the kernel should try to migrate the Entity to the other schema if possible. Or as another workflow, the calling function should intercept the error flow, then try to migrate the Entity and try another addEntity() call with the correct schema.

**Comment by RoadCaddie-TW** [comment]
Thanks for replying... I am a novice / recreational coder so more often than not, when things don't work they are something I am doing wrong or I am just ignorant about. I had a feeling this was more of a problem in the IfcOpenShell but was not certain. Thanks

**Comment by Moult** [comment]
Migrating schemas is not a trivial task. Generally, it's safer to upgrade than to downgrade. This function is already implemented in IfcOpenShell-Python, and in fact enabled for using classification libraries that don't match the schema version. That said, it's one thing migrating a classification library, it's another thing migrating a project library, especially as a project library may be an entire project.

I see a few possible solutions:

 1. Show an error message telling them the schemas don't match. The user then need to explicitly run the upgrade process (e.g. via the IfcPatch panel) to use it.
 2. Invisibly upgrade the entire library and possibly save the upgraded file alongside the original for the future
 3. Invisibly do a partial upgrade only of the asset we want imported, but this potentially creates problems keeping track of what is and isn't yet imported.

**Comment by RoadCaddie-TW** [comment]
What interesting is that I had just built some code to explore an idea. My code simply takes and IFC file and creates a new file for each individual element. So my hope is that it would simply generate a new file with the same schema as provided. Basically I have a section of pavement with four layers and I want each layer to be its one separate IFC file. 

Here is my attempt and what cause me to get this error:

import ifcopenshell
import hashlib
import os
from tkinter import Tk, filedialog

def sha256_hash(contents):
    """Generate SHA256 hash for the given contents."""
    return hashlib.sha256(contents).hexdigest()

def process_ifc(ifc_file_path):
    """Process the IFC file and generate individual IFC files for each object."""
    ifc_model = ifcopenshell.open(ifc_file_path)
    output_directory = "exported_ifc_objects"
    os.makedirs(output_directory, exist_ok=True)
    print(ifc_model.schema)

    for entity in ifc_model.by_type('IfcProduct'):
        if entity.is_a('IfcProduct'):
            # Create a new IFC model for the single object
            single_object_model = ifcopenshell.file(schema=ifc_model.schema)
            single_object_model.add(entity)
           
            # Serialize the model to a string
            file_contents = single_object_model.write().encode('utf-8')
           
            # Generate SHA256 hash for the file contents
            hash_name = sha256_hash(file_contents)
            filename = f"{hash_name}.ifc"
            file_path = os.path.join(output_directory, filename)
           
            # Save the new IFC file
            with open(file_path, 'wb') as f:
                f.write(file_contents)
           
            print(f"Created: {filename}")

def select_file_and_process():
    """Open a file dialog to select an IFC file and process it."""
    root = Tk()
    root.withdraw()  # Hide the root window
    file_path = filedialog.askopenfilename(title="Select IFC File", filetypes=[("IFC files", "*.ifc")])
    if file_path:
        process_ifc(file_path)

if __name__ == "__main__":
    select_file_and_process()

**Comment by Moult** [comment]
For extracting single elements into their own file, I recommend you use the ExtractElements recipe:

 - https://docs.ifcopenshell.org/ifcpatch.html
 - https://docs.ifcopenshell.org/autoapi/ifcpatch/recipes/ExtractElements/index.html

**Comment by RoadCaddie-TW** [comment]
Thank you! I will look into this in more detail. :-)

**Comment by BIMvoice** [comment]
Fixed in #8352 by migrating the library to the project's schema before appending, using the existing `ifcopenshell.util.schema.Migrator`. `project.append_asset` now detects a schema mismatch (including IFC4X3 sub-versions like RC4 vs ADD2) and migrates an in-memory copy of the library, so your loaded library file is never mutated and inverse-linked materials/psets/styles are preserved. IFC4→IFC4X3 appends of the default furniture library now succeed and validate clean. Elements with no equivalent in the target schema now fail with a clear message instead of the raw wrapper error. Regression tests added.
