### ISSUE TITLE
Error while importing a Cost Schedule from csv with IfcQuantityCost

### ISSUE THREAD

**Issue by Breogan10** [IfcOpenShell/IfcOpenShell#4776]
I'm trying to import a (parametric) Cost Schedule using this table:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/171332332/5fbc8d3e-0e14-4401-8b37-f2c0567d4043)

The error (related to last row in previous table) is this:

attribute 'CountValue' for entity 'IFC4X3.IfcQuantityCount' is expecting value of type 'INT', got 'float'.

I've found that this import only works directly after creating a new project.

The error complete error descripton I got from BB is this:

os: Windows
os_version: 10.0.19041
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 26 Stepping 5, GenuineIntel
blender_version: 3.6.8
blenderbim_version: 0.0.240529
last_actions: 
# ifcopenshell.api: cost.assign_cost_item_quantity
>>> {"cost_item": {"cast_type": "entity_instance", "value": 902654, "Name": "Unidad 4"}, "products": [{"cast_type": "entity_instance", "value": 59701, "Name": "Escalera 1"}, {"cast_type": "entity_instance", "value": 59645, "Name": "Escalera 3"}, {"cast_type": "entity_instance", "value": 58839, "Name": "Escalera 4"}, {"cast_type": "entity_instance", "value": 59673, "Name": "Escalera 2"}], "prop_name": ""}
# ifcopenshell.api: control.assign_control
>>> {"related_object": {"cast_type": "entity_instance", "value": 59701, "Name": "Escalera 1"}, "relating_control": {"cast_type": "entity_instance", "value": 902654, "Name": "Unidad 4"}}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: control.assign_control
>>> {"related_object": {"cast_type": "entity_instance", "value": 59645, "Name": "Escalera 3"}, "relating_control": {"cast_type": "entity_instance", "value": 902654, "Name": "Unidad 4"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 902659, "Name": null}}
# ifcopenshell.api: control.assign_control
>>> {"related_object": {"cast_type": "entity_instance", "value": 58839, "Name": "Escalera 4"}, "relating_control": {"cast_type": "entity_instance", "value": 902654, "Name": "Unidad 4"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 902659, "Name": null}}
# ifcopenshell.api: control.assign_control
>>> {"related_object": {"cast_type": "entity_instance", "value": 59673, "Name": "Escalera 2"}, "relating_control": {"cast_type": "entity_instance", "value": 902654, "Name": "Unidad 4"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 902659, "Name": null}}
# ifcopenshell.api: cost.add_cost_item_quantity
>>> {"cost_item": {"cast_type": "entity_instance", "value": 902654, "Name": "Unidad 4"}, "ifc_class": "IfcQuantityCount"}
last_error: Traceback (most recent call last):
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 342, in __setitem__
    self.method_list[idx](self.wrapped_data, idx, entity_instance.unwrap_value(value))
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 5290, in setArgumentAsInt
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsInt(self, i, v)
TypeError: in method 'entity_instance_setArgumentAsInt', argument 3 of type 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\cost\operator.py", line 526, in _execute
    core.import_cost_schedule_csv(tool.Cost, self.filepath, self.is_schedule_of_rates)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\cost.py", line 285, in import_cost_schedule_csv
    cost.import_cost_schedule_csv(file_path, is_schedule_of_rates)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\cost.py", line 519, in import_cost_schedule_csv
    csv2ifc.execute()
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc5d\csv2ifc.py", line 42, in execute
    self.create_ifc()
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc5d\csv2ifc.py", line 124, in create_ifc
    self.create_cost_items(self.cost_items)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc5d\csv2ifc.py", line 130, in create_cost_items
    self.create_cost_item(cost_item, parent)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc5d\csv2ifc.py", line 213, in create_cost_item
    self.create_cost_items(cost_item["children"], cost_item["ifc"])
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc5d\csv2ifc.py", line 130, in create_cost_items
    self.create_cost_item(cost_item, parent)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc5d\csv2ifc.py", line 213, in create_cost_item
    self.create_cost_items(cost_item["children"], cost_item["ifc"])
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc5d\csv2ifc.py", line 130, in create_cost_items
    self.create_cost_item(cost_item, parent)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifc5d\csv2ifc.py", line 201, in create_cost_item
    ifcopenshell.api.run(
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 184, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 350, in wrapper
    raise e
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 344, in wrapper
    result = usecase(*args, **settings)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\cost\assign_cost_item_quantity.py", line 95, in assign_cost_item_quantity
    return usecase.execute()
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\cost\assign_cost_item_quantity.py", line 117, in execute
    self.update_cost_item_count()
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\cost\assign_cost_item_quantity.py", line 145, in update_cost_item_count
    ifcopenshell.api.run(
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 184, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 350, in wrapper
    raise e
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 344, in wrapper
    result = usecase(*args, **settings)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\cost\add_cost_item_quantity.py", line 82, in add_cost_item_quantity
    quantity[3] = 0.0
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 344, in __setitem__
    raise TypeError(
TypeError: attribute 'CountValue' for entity 'IFC4X3.IfcQuantityCount' is expecting value of type 'INT', got 'float'.

**Comment by Andrej730** [comment]
@Breogan10 Thanks for the bug report! Issue is resolved after c05abc4

**Comment by Breogan10** [comment]
Well, I've tested it... and worked!!

To me it's a very important feature (It allows not only the manual counting of objects, but also automatic counting + object selecting - query feature - via csv import).

Thank you VERY MUCH, for the quick answer and solution, and for contributing to unlock this simple but very valuable feaure.
