### ISSUE TITLE
Save to temporary file and rename to prevent file corruption during file write

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4797]
A user reported a crash during save and the IFC had all sorts of unreferenced STEP IDs. After discussion with @brunopostle this seems to be a safer approach.

**Comment by aothms** [comment]
This makes sense. Just make sure it's on the same partition so that the move is atomic. So instead of tmpdir I'd recommend adding a postfix like `my_file.ifc.randomnumber123.tmp`. Feel free to implement it under ifcopenshell.file.write() with a keyword arg to turn it on or off (default I don't care).

**Comment by Moult** [comment]
Bump @brunopostle :)

**Comment by brunopostle** [comment]
I haven't forgotten, just need to find the time

**Comment by brunopostle** [comment]
An update on this, I can implement atomic file writes in ifcopenshell.file.write() with something like this:

```
        if atomic:
            fd, temp_path = tempfile.mkstemp(dir=path.parent)
            temp_path = Path(temp_path)
            self.wrapped_data.write(str(temp_path))
            temp_path.replace(path)
        else:
            self.wrapped_data.write(str(path))
```

I also need to fiddle with the file permissions, but the main problem is that the IFC file gets written with the `FILE_NAME` header set to the temporary file name, and there is no way to fix this unless I put the temporary file in a different folder.

**Comment by brunopostle** [comment]
Some more research: it would be easy to create a temporary folder, write the file there, move it to the parent folder, and delete the temporary folder.

This would be atomic on ext4, NTFS and APFS. However it isn't atomic on fat32 or SMB, so this technique would be a problem on USB sticks and network drives.

Alternatives I can see:

1. Rename the old file to `myfile.bak`, write the file to the correct filename, optionally delete the .bak file. This is what autocad does, and I guess this is what all those .blend1 files left around by blender are for.
2. Change the c++ to allow setting the `FILE_NAME` header to something other than the filename.

**Comment by aothms** [comment]
> Change the c++ to allow setting the FILE_NAME header to something other than the filename.

The file_name is not set on the C++ side of things. It's not even really known in the library because we open the filestream in swig and stream the C++ file object through that.

https://github.com/IfcOpenShell/IfcOpenShell/blob/6d9487168375563cc19fbbbc22dc5d4b5d870d9e/src/ifcwrap/IfcParseWrapper.i#L143-L146

**Comment by Andrej730** [comment]
> An update on this, I can implement atomic file writes in ifcopenshell.file.write() with something like this:
> 
> ```
>         if atomic:
>             fd, temp_path = tempfile.mkstemp(dir=path.parent)
>             temp_path = Path(temp_path)
>             self.wrapped_data.write(str(temp_path))
>             temp_path.replace(path)
>         else:
>             self.wrapped_data.write(str(path))
> ```

Looks good in general but on Windows it seems to require `os.close(fd)` before `.replace`, otherwise I get the error below with the snippet
```python
import ifcopenshell
from pathlib import Path

path = Path(r"C:\") / "project.ifc"
ifc_file = ifcopenshell.file()
ifc_file.write(path)
print('finished')
```

Error:
```
Traceback (most recent call last):
  File "\test.py", line 6, in <module>
    ifc_file.write(path)
  File "\ifcopenshell\file.py", line 684, in write
    temp_path.replace(path)
  File "\Lib\pathlib.py", line 1188, in replace
    os.replace(self, target)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\tmp8nl2f1c6' -> 'C:\\project.ifc
```

Also about permissions. Was investigating #5809 and found that on Windows (not sure how it is on Unix) `os.access(dir_path, os.W_OK)` is unreliable as it returns `True` even if user doesn't have write access to the directory. So the ultimate test seems to be to just create a file to see if it works. 

So in theory `tempfile.mkstemp` should have cover that but there's a bug in `tempfile` (https://github.com/python/cpython/issues/66305#issuecomment-2503074764, see some workaround in the linked comment) when it doesn't recognize missing permissions and just keeps hanging indefinetely until it tries all zillion names for temporary files... So, I guess the solution is to create our method for creating a temp file? :\

**Comment by aothms** [comment]
> Looks good in general but on Windows it seems to require os.close(fd) before .replace

Yes that's what I recall as well, linux allows to delete/move a file that's used, but windows doesn't.

> So the ultimate test seems to be to just create a file to see if it works.

That's what I recall as best practice as well

> So, I guess the solution is to create our method for creating a temp file? :\

Shouldn't we just implement this fully in C++. Just always write to `my_file.ifc~` for example and at the very end rename transparently in (swig generated) C++.

Note that in IfcConvert we already do sth similar.

https://github.com/IfcOpenShell/IfcOpenShell/blob/c9847caa6a20b4fa1b16a6b78ec7060df4c904f6/src/ifcconvert/IfcConvert.cpp#L622

**Comment by Moult** [comment]
Ping @aothms - might this be something easily coded with an LLM in C++ that you would be able to take a look at? (I'm going through the Severity:Critical bugs)

**Comment by BIMvoice** [comment]
Implemented atomic writes fully in C++, as suggested. `ifcopenshell.file.write()` now serializes to a temp file next to the target and atomically renames it into place, so an interrupted save can no longer truncate the file or leave dangling STEP ids. Added `IfcUtil::path::atomic_rename_file` (`std::rename` on POSIX, `MoveFileExW` + `MOVEFILE_REPLACE_EXISTING` on Windows) which, unlike `rename_file`, never unlinks the destination first. The stream is closed before the rename (Windows). On any error the temp is removed and the original file is left intact.

Confirmed empirically that the `FILE_NAME` header is unaffected: it comes from the model header, not the write path, so the temp name never leaks. That's what the earlier temp-file experiments were hitting, and it's exactly why doing this in C++ is safe where the Python temp-path approach was not.

Always-on, matching IfcConvert. Tested against the real `IfcParse` serializer: byte-identical output, clean FILE_NAME header, no temp litter on success, original file intact on a simulated write failure, clear error on an unwritable directory. PR #8341.

One open question: preserve original file permissions on overwrite? Currently a new file gets the default mode, same as before.
