### ISSUE TITLE
build_all.py on Fedora 27 - - - Stop at OpenCollada

### ISSUE THREAD

**Issue by paullee0** [IfcOpenShell/IfcOpenShell#480]
Hi, I attempt again compiling - - - aim to use IfcOpenShell-python for FreeCAD IfcExport / Import only.

I try the nix/build_all.py and it stop at OpenCollada.

I am not familiar with Python, appreciate any ideas could be offered.

```
Configuring OpenCOLLADA...
Building OpenCOLLADA...   
----------------------------------------------------------------------
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c: In function ‘ConvertUTF16toUTF8’:
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:270:65: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 4: *--target = (UTF8)((ch | byteMark) & byteMask); ch >>= 6;
                                                              ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:271:6: note: here
      case 3: *--target = (UTF8)((ch | byteMark) & byteMask); ch >>= 6;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:271:65: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 3: *--target = (UTF8)((ch | byteMark) & byteMask); ch >>= 6;
                                                              ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:272:6: note: here
      case 2: *--target = (UTF8)((ch | byteMark) & byteMask); ch >>= 6;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:272:65: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 2: *--target = (UTF8)((ch | byteMark) & byteMask); ch >>= 6;
                                                              ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:273:6: note: here
      case 1: *--target =  (UTF8)(ch | firstByteMark[bytesToWrite]);
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c: In function ‘isLegalUTF8’:
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:301:42: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 4: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return false;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:302:5: note: here
     case 3: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return false;
     ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:302:42: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 3: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return false;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:303:5: note: here
     case 2: if ((a = (*--srcptr)) > 0xBF) return false;
     ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:311:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
      default:   if (a < 0x80) return false;
                    ^
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:314:5: note: here
     case 1: if (*source >= 0x80 && *source < 0xC2) return false;
     ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c: In function ‘ConvertUTF8toUTF16’:
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:357:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 5: ch += *source++; ch <<= 6; /* remember, illegal UTF-8 */
                               ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:358:6: note: here
      case 4: ch += *source++; ch <<= 6; /* remember, illegal UTF-8 */
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:358:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 4: ch += *source++; ch <<= 6; /* remember, illegal UTF-8 */
                               ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:359:6: note: here
      case 3: ch += *source++; ch <<= 6;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:359:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 3: ch += *source++; ch <<= 6;
                               ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:360:6: note: here
      case 2: ch += *source++; ch <<= 6;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:360:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 2: ch += *source++; ch <<= 6;
                               ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:361:6: note: here
      case 1: ch += *source++; ch <<= 6;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:361:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 1: ch += *source++; ch <<= 6;
                               ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:362:6: note: here
      case 0: ch += *source++;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c: In function ‘ConvertUTF32toUTF8’:
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:448:65: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 4: *--target = (UTF8)((ch | byteMark) & byteMask); ch >>= 6;
                                                              ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:449:6: note: here
      case 3: *--target = (UTF8)((ch | byteMark) & byteMask); ch >>= 6;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:449:65: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 3: *--target = (UTF8)((ch | byteMark) & byteMask); ch >>= 6;
                                                              ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:450:6: note: here
      case 2: *--target = (UTF8)((ch | byteMark) & byteMask); ch >>= 6;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:450:65: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 2: *--target = (UTF8)((ch | byteMark) & byteMask); ch >>= 6;
                                                              ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:451:6: note: here
      case 1: *--target = (UTF8) (ch | firstByteMark[bytesToWrite]);
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c: In function ‘ConvertUTF8toUTF32’:
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:483:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 5: ch += *source++; ch <<= 6;
                               ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:484:6: note: here
      case 4: ch += *source++; ch <<= 6;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:484:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 4: ch += *source++; ch <<= 6;
                               ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:485:6: note: here
      case 3: ch += *source++; ch <<= 6;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:485:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 3: ch += *source++; ch <<= 6;
                               ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:486:6: note: here
      case 2: ch += *source++; ch <<= 6;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:486:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 2: ch += *source++; ch <<= 6;
                               ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:487:6: note: here
      case 1: ch += *source++; ch <<= 6;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:487:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
      case 1: ch += *source++; ch <<= 6;
                               ~~~^~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/UTF/src/ConvertUTF.c:488:6: note: here
      case 0: ch += *source++;
      ^~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/MathMLSolver/src/AST/MathMLASTConstantExpression.cpp: In copy constructor ‘MathML::AST::ConstantExpression::ConstantExpression(const MathML::AST::ConstantExpression&)’:
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/Externals/MathMLSolver/src/AST/MathMLASTConstantExpression.cpp:28:9: warning: base class ‘class MathML::AST::INode’ should be explicitly initialized in the copy constructor [-Wextra]
         ConstantExpression::ConstantExpression( const ConstantExpression& ref )
         ^~~~~~~~~~~~~~~~~~
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/GeneratedSaxParser/src/GeneratedSaxParserLibxmlSaxParser.cpp:51:2: warning: missing initializer for member ‘_xmlSAXHandler::getParameterEntity’ [-Wmissing-field-initializers]
  };
  ^
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/GeneratedSaxParser/src/GeneratedSaxParserLibxmlSaxParser.cpp:51:2: warning: missing initializer for member ‘_xmlSAXHandler::cdataBlock’ [-Wmissing-field-initializers]
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/GeneratedSaxParser/src/GeneratedSaxParserLibxmlSaxParser.cpp:51:2: warning: missing initializer for member ‘_xmlSAXHandler::externalSubset’ [-Wmissing-field-initializers]
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/GeneratedSaxParser/src/GeneratedSaxParserLibxmlSaxParser.cpp:51:2: warning: missing initializer for member ‘_xmlSAXHandler::initialized’ [-Wmissing-field-initializers]
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/GeneratedSaxParser/src/GeneratedSaxParserLibxmlSaxParser.cpp:51:2: warning: missing initializer for member ‘_xmlSAXHandler::_private’ [-Wmissing-field-initializers]
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/GeneratedSaxParser/src/GeneratedSaxParserLibxmlSaxParser.cpp:51:2: warning: missing initializer for member ‘_xmlSAXHandler::startElementNs’ [-Wmissing-field-initializers]
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/GeneratedSaxParser/src/GeneratedSaxParserLibxmlSaxParser.cpp:51:2: warning: missing initializer for member ‘_xmlSAXHandler::endElementNs’ [-Wmissing-field-initializers]
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/GeneratedSaxParser/src/GeneratedSaxParserLibxmlSaxParser.cpp:51:2: warning: missing initializer for member ‘_xmlSAXHandler::serror’ [-Wmissing-field-initializers]
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/COLLADAStreamWriter/src/COLLADASWLibraryAnimations.cpp: In constructor ‘COLLADASW::LibraryAnimations::LibraryAnimations(COLLADASW::StreamWriter*)’:
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/COLLADAStreamWriter/src/COLLADASWLibraryAnimations.cpp:64:102: warning: passing NULL to non-pointer argument 1 of ‘std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const allocator_type&) [with _Tp = COLLADASW::Animation*; _Alloc = std::allocator<COLLADASW::Animation*>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<COLLADASW::Animation*>]’ [-Wconversion-null]
             : Library ( streamWriter, CSWC::CSW_ELEMENT_LIBRARY_ANIMATIONS ), mOpenAnimations ( NULL )
                                                                                                      ^
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/COLLADASaxFrameworkLoader/src/COLLADASaxFWLFormulasLinker.cpp: In member function ‘MathML::AST::INode* COLLADASaxFWL::FormulasLinker::link(COLLADAFW::Formula*, COLLADASaxFWL::COLLADACsymbol*, bool&)’:
/run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA/COLLADASaxFrameworkLoader/src/COLLADASaxFWLFormulasLinker.cpp:174:14: error: cannot convert ‘bool’ to ‘MathML::AST::INode*’ in return
       return false;
              ^~~~~
make[2]: *** [COLLADASaxFrameworkLoader/CMakeFiles/OpenCOLLADASaxFrameworkLoader_static.dir/build.make:879: COLLADASaxFrameworkLoader/CMakeFiles/OpenCOLLADASaxFrameworkLoader_static.dir/src/COLLADASaxFWLFormulasLinker.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:478: COLLADASaxFrameworkLoader/CMakeFiles/OpenCOLLADASaxFrameworkLoader_static.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

----------------------------------------------------------------------
Traceback (most recent call last):
  File "./build-all.py", line 488, in <module>
    build_dependency("OpenCOLLADA", "cmake", build_tool_args=["-DLIBXML2_INCLUDE_DIR=%s/install/libxml2-%s/include/libxml2" % (DEPS_DIR, LIBXML_VERSION), "-DLIBXML2_LIBRARIES=%s/install/libxml2-%s/lib/libxml2.a" % (DEPS_DIR, LIBXML_VERSION), "-DPCRE_INCLUDE_DIR=%s/install/pcre-%s/include" % (DEPS_DIR, PCRE_VERSION), "-DPCRE_PCREPOSIX_LIBRARY=%s/install/pcre-%s/lib/libpcreposix.a" % (DEPS_DIR, PCRE_VERSION), "-DPCRE_PCRE_LIBRARY=%s/install/pcre-%s/lib/libpcre.a" % (DEPS_DIR, PCRE_VERSION), "-DCMAKE_INSTALL_PREFIX=%s/install/OpenCOLLADA/" % (DEPS_DIR,)], download_url="https://github.com/KhronosGroup/OpenCOLLADA.git", download_name="OpenCOLLADA", download_tool=download_tool_git, revision=OPENCOLLADA_COMMIT)
  File "./build-all.py", line 377, in build_dependency
    __check_call__([make, "-j%s" % (IFCOS_NUM_BUILD_PROCS,)], cwd=extract_build_dir)
  File "./build-all.py", line 230, in __check_call__
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `make -j5` returned exit code 2

```

**Comment by aothms** [comment]
Hm, not sure why compiling OpenCOLLADA would suddenly fail on fedora 27, but fedora can be a bit more bleeding edge then what I test with. Can you please try changing the opencollada version being used [1] to e.g. "v1.6.63" (since some time now they do proper tagging over there, the commit we track now is from 19 Dec 2013, probably worth updating as newer compilers might rightfully complain).

Probably best to `rm -rf /run/media/paullee/80G_Data/Download/Download_IfcOpenShell/git/IfcOpenShell/build/Linux/x86_64/build/OpenCOLLADA` before restarting.

Let me know and if it works feel free to send in a Pull Request.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.py#L251

**Comment by paullee0** [comment]
Thanks, revising it to  "v1.6.63" seems works, it is working on something else now.  I am not sure if this works other the Fedora 27, a PR still?

**But if I only need IfcOpenShell-python, anywhere I can find more hint / instruction?**

Thanks again!

**Comment by paullee0** [comment]
An it seem build_all.py only build below for PythonPython-2.7.12 , 3.x
_ifcopenshell_wrapper.so
ifcopenshell_wrapper.py 

Seem I need Python 2.7.6 to fit FreeCAD python version

Any idea?

**Comment by aothms** [comment]
> I am not sure if this works other the Fedora 27, a PR still?

Yeah there were previous versions that did not work regardless of OS / compiler. This version should be fine.

> But if I only need IfcOpenShell-python, anywhere I can find more hint / instruction?

Almost everything is needed for IfcOpenShell-python, so you don't win much by disabling specific outputs. But you probably want to change the `PYTHON_VERSIONS` [1] to match your needs.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.py#L64
