### ISSUE TITLE
Error  bpy.ops.object.mode_set.poll() Context missing active object when toggling edit mode

### ISSUE THREAD

**Issue by jobkuijper2** [IfcOpenShell/IfcOpenShell#4804]
```
os: Darwin
os_version: Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64
python_version: 3.10.12
architecture: ('64bit', '')
machine: x86_64
processor: i386
blender_version: 3.6.1
blenderbim_version: 0.0.240602
last_actions: 
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_object
last_error: Traceback (most recent call last):
  File "/Users/jobkuijper/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/ifc.py", line 358, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
  File "/Users/jobkuijper/Library/Application Support/Blender/3.6/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 1698, in _invoke
    bpy.ops.object.mode_set(mode="EDIT", toggle=True)
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object
```

**Comment by Moult** [comment]
The thing is that in theory the debug log gives us everything we need to recreate it ... yet when I try to match his environment (except using Linux, not Mac) I can't recreate the issue.

```
os: Linux
os_version: #1 SMP PREEMPT_DYNAMIC Thu May  2 17:09:53 -00 2024
python_version: 3.10.12
architecture: ('64bit', 'ELF')
machine: x86_64
processor: AMD Ryzen 5 7600X 6-Core Processor
blender_version: 3.6.3
blenderbim_version: 0.0.240602
last_actions: 
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_object
last_error: None
```
