### ISSUE TITLE
[BlenderBIM] Loading viewpoint from a bcf file causes a error

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#4811]
This is my ifc file:
[two-cube-built-element.ifc.txt](https://github.com/user-attachments/files/15592194/two-cube-built-element.ifc.txt)

Without the ending .txt

This is my bcf file:
[Test.bcf.txt](https://github.com/user-attachments/files/15592198/Test.bcf.txt)

Without the ending .txt

The error is caused when i click this button:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110968398/8c407a46-e658-4c25-a222-1d15ad1e0849)

This is the Python Traceback:

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\bcf\operator.py", line 869, in execute
    self.set_viewpoint_components(viewpoint, context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\bcf\operator.py", line 941, in set_viewpoint_components
    exception_global_ids = {v.ifc_guid for v in viewpoint.visualization_info.components.visibility.exceptions.component or []}
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'component'

Windows 10
Blender version 4.1
BlenderBIM version 0.0.240602

**Comment by Andrej730** [comment]
@Martin15135215 Hi! Can you please try again? Couldn't reproduce this now using the provided files, issue might have been fixed in 84d475c.

**Comment by sboddy** [comment]
@Martin15135215 I concur with Andrej. This appears fixed and works without error. I'm going to close it, but please reopen if you still see this issue.
