### ISSUE TITLE
Error editing IfcSweptDiskPolygonal Representation

### ISSUE THREAD

**Issue by Breogan10** [IfcOpenShell/IfcOpenShell#4813]
I'm trying to use a non-standard kind of representation (It is not included as an option when creating a new duct type), which is a Swept Disk, not with a straigth path, but with a polygonal path.

It's obvious that this representation is quite useful to deal with steel rebars, but also with those tubes which can be modeled disregarding special elements for the elbows.

I've found a file in which an entity has this representation is already implemented:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/171332332/a40f29b4-8f1b-4689-b9e5-4fe5bf3c4734)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/171332332/b03131b0-5cbf-4c29-b7b7-5834859a8f2b)

I remember that I was able to edit this representation with previous versions of BB.

When trying to edit it, whit most recent version (240602), I got this error message:

Python: Traceback (most recent call last):
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1647, in invoke
    return IfcStore.execute_ifc_operator(self, context, is_invoke=True)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 358, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1652, in _invoke
    return self.execute(context)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1530, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1596, in _execute
    operator()
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1581, in <lambda>
    operator = lambda: bpy.ops.bim.hotkey(hotkey="S_E")
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 211, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\workspace.py", line 591, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\workspace.py", line 689, in hotkey_S_E
    bpy.ops.bim.enable_editing_extrusion_profile()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\ifc.py", line 211, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\glopez\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\model\slab.py", line 632, in _execute
    if extrusion.Position:
AttributeError: 'NoneType' object has no attribute 'Position'
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113

**Comment by BIMvoice** [comment]
Thanks for the report. On current v0.8.0 the original `slab.py` error is gone, but editing still fails: a swept disk solid (straight or polygonal directrix) loads as a native Blender curve, and entering edit mode routed it into the mesh-based item editor, which crashed with `AssertionError: Unexpected mesh type.` because a curve has no mesh item ids.

Fixed in #8355: Bonsai now detects these curve objects and reports "Editing swept disk solid representations is not supported yet." instead of crashing. Honest scope: full parametric editing of the swept path isn't wired into the current item-based edit mode yet (there's no curve to `IfcSweptDiskSolid` save-back path), so for now this just stops the crash and fails cleanly. Real editing support is worth tracking separately.

**Comment by BIMvoice** [comment]
Updated #8355 to narrow the curve guard: it now declines only non-annotation curves, so this swept-disk crash fix no longer blocks editing of curve annotations (dimensions, leaders), reconciling with #5025.
