### ISSUE TITLE
Invalid IFC after removing work plans / work schedules

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4819]
Hi

Under "Costing and Schedualing" I deteted one "Works Plan" and "Works Schedual" saved the IFC file and then got this message when I tried to open my file again. 
```
os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.0.240606
last_actions: 
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 17124, "Name": "Doors and windows"}], "relating_object": {"cast_type": "entity_instance", "value": 7614, "Name": "New"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 17684, "Name": "Tiling"}], "relating_object": {"cast_type": "entity_instance", "value": 7614, "Name": "New"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 16829, "Name": "Roof"}], "relating_object": {"cast_type": "entity_instance", "value": 7614, "Name": "New"}}
# ifcopenshell.api: spatial.assign_container
>>> {"products": [{"cast_type": "entity_instance", "value": 7475, "Name": "Exisitng"}], "relating_structure": {"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 17159, "Name": "Foundation"}], "relating_object": {"cast_type": "entity_instance", "value": 7614, "Name": "New"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 5899, "Name": "Wall"}], "relating_object": {"cast_type": "entity_instance", "value": 7475, "Name": "Exisitng"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 17633, "Name": "Final fix"}], "relating_object": {"cast_type": "entity_instance", "value": 7614, "Name": "New"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}], "relating_object": {"cast_type": "entity_instance", "value": 36, "Name": "My Building"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 30, "Name": "My Site"}], "relating_object": {"cast_type": "entity_instance", "value": 1, "Name": "My Project"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 36, "Name": "My Building"}], "relating_object": {"cast_type": "entity_instance", "value": 30, "Name": "My Site"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 693, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 773, in execute
    ifc_importer.execute()
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\import_ifc.py", line 266, in execute
    self.create_collections()
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\import_ifc.py", line 1608, in create_collections
    self.create_aggregate_and_nest_collections()
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\import_ifc.py", line 1662, in create_aggregate_and_nest_collections
    rel_aggregates = [
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\import_ifc.py", line 1665, in <listcomp>
    if (relating_obj := r.RelatingObject).is_a("IfcElement") or relating_obj.is_a("IfcElementType")
AttributeError: 'NoneType' object has no attribute 'is_a'
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109


ifc: HFCC-Chrech Toilet.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: BlenderBIM 0.0.240606-98ec3e2
```
Pre-deletion -[HFCC-Chrech Toilet.txt](https://github.com/user-attachments/files/15678424/HFCC-Chrech.Toilet.txt)
[HFCC-Chrech Toilet-can't open in BB.txt](https://github.com/user-attachments/files/15679351/HFCC-Chrech.Toilet-can.t.open.in.BB.txt)

**Comment by Andrej730** [comment]
@Ave-5D thanks for the bug report, it helped uncover a few issues and they are fixed now.
To fix your file you can remove the line below:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/86cc1415-9196-4e0b-82bf-91a1d41a532b)

**Comment by Ave-5D** [comment]
Thank you
