### ISSUE TITLE
Wall Butt tool generates error

### ISSUE THREAD

**Issue by chopinregis** [IfcOpenShell/IfcOpenShell#4820]
when trying to butt two walls, i get an error.

```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
blender_version: 4.1.1
blenderbim_version: 0.0.240604
last_actions: 
# operator: BIM_OT_join_wall
# ifcopenshell.api: geometry.connect_path
>>> {"relating_element": {"cast_type": "entity_instance", "value": 3246639, "Name": "Wall"}, "related_element": {"cast_type": "entity_instance", "value": 3246599, "Name": "Wall"}, "relating_connection": "ATEND", "related_connection": "ATEND", "description": "BUTT"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# operator: BIM_OT_hotkey
# operator: BIM_OT_join_wall
# ifcopenshell.api: geometry.disconnect_path
>>> {"element": {"cast_type": "entity_instance", "value": 3246639, "Name": "Wall"}, "connection_type": "ATEND"}
# operator: BIM_OT_hotkey
# operator: BIM_OT_join_wall
# ifcopenshell.api: geometry.connect_path
>>> {"relating_element": {"cast_type": "entity_instance", "value": 3246639, "Name": "Wall"}, "related_element": {"cast_type": "entity_instance", "value": 3246599, "Name": "Wall"}, "relating_connection": "ATEND", "related_connection": "ATEND", "description": "BUTT"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
last_error: Traceback (most recent call last):
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 591, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\workspace.py", line 784, in hotkey_S_T
    bpy.ops.bim.join_wall(join_type="L")
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 88, in _execute
    joiner.join_L(another_selected_object, context.active_object)
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 1036, in join_L
    self.recreate_wall(element1, wall1, axis1["reference"], axis1["reference"])
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\wall.py", line 1127, in recreate_wall
    extrusion_data = self.get_extrusion_data(tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 425, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 410, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4917, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #3,246,662 not found
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109


ifc: Lake_Kegonsa_Renovation.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: BlenderBIM 0.0.240604-dc8ea31
```

![Snipaste_2024-06-06_18-12-13](https://github.com/IfcOpenShell/IfcOpenShell/assets/13260872/9c21f5a0-3c19-40f1-b4d9-afe970d9b2a7)

**Comment by Moult** [comment]
This looks like a file sync issue. Can you recreate this if you loaded just the IFC and no blend involved?

**Comment by chopinregis** [comment]
Yes you are right, without the linked .blend scans/file, it doesn't bug

**Comment by Moult** [comment]
In that case it's a different sync bug which is hard to know exactly what and depends on a lot of factors, including how old the file is because things change a lot so keeping a .blend throughout those changes is very risky.

**Comment by chopinregis** [comment]
yeah thanks, @theoryshaw had mentioned that perhaps the synch issue was also happening because i had the .ifc associated with the .blend. So for now i'll try to work without the .ifc scan and see how things progress. I shall report here if i see the same bug re-appearing.
