### ISSUE TITLE
Error when running latest build

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4831]
I restarted, same thing. Yesterday's version worked just fine.

```
os: Darwin
os_version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
python_version: 3.11.7
architecture: ('64bit', '')
machine: arm64
processor: arm
blender_version: 4.1.0
blenderbim_version: 0.0.240607
last_actions: 
last_error: Traceback (most recent call last):
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/__init__.py", line 96, in <module>
    import blenderbim.bim
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/tool/__init__.py", line 30, in <module>
    from blenderbim.tool.document import Document
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/tool/document.py", line 23, in <module>
    from blenderbim.bim import import_ifc
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 44, in <module>
    from blenderbim.tool.loader import OBJECT_DATA_TYPE
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/tool/loader.py", line 42, in <module>
    class Loader(blenderbim.core.tool.Loader):
  File "/Users/petru/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/tool/loader.py", line 59, in Loader
    def get_mesh_name(cls, geometry: ifcopenshell.geom.ShapeType) -> str:
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ifcopenshell.geom' has no attribute 'ShapeType'
```

**Comment by Moult** [comment]
We're transitioning to v0.8.0 right now so perhaps wait a bit.
