### ISSUE TITLE
ERROR CREATE STOREY

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4853]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/140309875/2bf402af-a442-40bc-a6fa-1c1ce78a8d42)

**Comment by steverugi** [comment]
same here, I was advised to go back to 240602 until the new updates are sorted out

**Comment by Moult** [comment]
I'm still curious what you're doing to trigger this error? BTW @blenderarc in the future please post the error message otherwise we can't know what's happening. Click the button that says "copy error message to clipboard", then paste it in here.

**Comment by steverugi** [comment]
Hi @Moult 
in my case the error was triggered on creation of a new storey, as the title suggests
for me to reproduce it I need to reinstall 240606..
the storey was created eventually but I couldn't edit its level, will make sure to post the error next time
thanks

**Comment by steverugi** [comment]
sorry!
I did create a new storey using the drop-down menu above the new spatial decomposition tool
it showed OK in the Outliner but couldn't fix the height level
if you like I can re-install 240606 and send you the error log

**Comment by blenderarc** [comment]
```
os: Windows
os_version: 10.0.22621
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240605
last_actions: 
# operator: BIM_OT_assign_class
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcBuildingStorey", "predefined_type": "", "name": "My BuildingStorey1"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 1222, "Name": "My BuildingStorey1"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1222, "Name": "My BuildingStorey1"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 1222, "Name": "My BuildingStorey1"}], "relating_object": {"cast_type": "entity_instance", "value": 36, "Name": "My Building"}}
# ifcopenshell.api: spatial.unassign_container
>>> {"products": "[]"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 60, "Name": null}}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 1222, "Name": "My BuildingStorey1"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1222, "Name": "My BuildingStorey1"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\aggregate\operator.py", line 294, in _execute
    tool.Spatial.load_container_manager()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Spatial' has no attribute 'load_container_manager'

ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: IfcOpenShell v0.7.0-c7830e9e5
```

**Comment by Moult** [comment]
This should now be working. Can you test @steverugi @blenderarc ?

**Comment by steverugi** [comment]
Hi @Moult 
just installed 240701 and it seems to be OK so far, including adding a storey
fingers crossed, thanks!
