### ISSUE TITLE
Enum "EDIT" not found in ('OBJECT')

### ISSUE THREAD

**Issue by senyai** [IfcOpenShell/IfcOpenShell#4854]
```
os: Linux
os_version: #202403110203~1715181801~22.04~aba43ee SMP PREEMPT_DYNAMIC Wed M
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: 
blender_version: 4.1.1
blenderbim_version: 0.0.240602
last_actions: 
# ifcopenshell.api: pset.add_pset
>>> {"product": {"cast_type": "entity_instance", "value": 1589, "Name": "Wall"}, "name": "EPset_Parametric"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: pset.edit_pset
>>> {"pset": {"cast_type": "entity_instance", "value": 1611, "Name": "EPset_Parametric"}, "properties": "{'Engine': 'BlenderBIM.DumbLayer2'}"}
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_object
last_error: Traceback (most recent call last):
  File "/home/senyai/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 358, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/senyai/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 1698, in _invoke
    bpy.ops.object.mode_set(mode="EDIT", toggle=True)
  File "/app/blender/4.1/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Converting py args to operator properties:  enum "EDIT" not found in ('OBJECT')

ifc: house_zubovo.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: BlenderBIM 0.0.240602-47704b1
```
Happens when clicking "Discard Changes" button:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/76137/6b1db228-31e8-49d0-b0c3-6df652b30c3e)

**Comment by Moult** [comment]
I can't recreate this - what steps did you do prior to pressing discard changes? Can you recreate it in a fresh environment?

**Comment by senyai** [comment]
4 Steps:
* Start blender
* Remove all objects
* Add -> Empty -> Plain Axes
* Click 'IFC Object Mode' button, set it to 'Edit mode'

Hope it helps.

**Comment by Moult** [comment]
Thanks :) Indeed there are a few things we didn't accommodate here - the fact that it is visible even without an IFC project, and the ability to toggle editing on non-editable things.

Will fix!
