### ISSUE TITLE
Error when modeling non bim model

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4858]
```
os: Windows
os_version: 10.0.22621
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240605
last_actions: 
# operator: BIM_OT_update_representation
# operator: BIM_OT_update_representation
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 30, "Name": "My Site"}], "relating_object": {"cast_type": "entity_instance", "value": 1, "Name": "My Project"}}
# operator: BIM_OT_update_representation
# operator: BIM_OT_update_representation
# operator: BIM_OT_update_representation
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_object
last_error: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 358, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1744, in _invoke
    elif obj.data.BIMMeshProperties.ifc_definition_id:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'BIMMeshProperties'

ifc: untitled.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: BlenderBIM 0.0.240605-802e196
```

**Comment by Gorgious56** [comment]
Hello, can you confirm the culprit object is an Empty object ?

**Comment by Moult** [comment]
This has now been fixed since we're more strict in the UI to prevent users manually toggling "IFC Edit Mode".
