### ISSUE TITLE
Error on creating new wall

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#4859]
Latest 0.8.0 dev build,

I've got a cascade of errors when trying to instance a wall from a wall type, I got to the first error which I assume made everything fall apart,

```
2024-06-13 11:17:01,704    ERROR import_ifc.py 1680 Could not create mesh for #73=IfcWall('0ikfywb0L5KhPVpm1Fglud',$,'Wall',$,$,#86,#81,$,$)
Traceback (most recent call last):
  File "C:\Users\nhild\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 1676, in create_mesh
    mesh["ios_materials"] = [m.instance_id() for m in geometry.materials]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nhild\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 1676, in <listcomp>
    mesh["ios_materials"] = [m.instance_id() for m in geometry.materials]
                             ^^^^^^^^^^^^^
AttributeError: 'SwigPyObject' object has no attribute 'instance_id'

swig/python detected a memory leak of type 'ifcopenshell::geometry::taxonomy::style *', no destructor found.
```

**Comment by Moult** [comment]
See #4832. We're in the middle of transitioning and there are quite a few quirks so I don't recommend using the daily builds for now and stick to the 'stable' build.

Those particular issues you've noticed have already been resolved, but there are still others so I guess we'll wait a bit until it's worth it to do a bot build.
