### ISSUE TITLE
Error draing

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#4864]
```
os: Linux
os_version: #1 SMP PREEMPT_DYNAMIC Fri May 17 21:20:15 UTC 2024
python_version: 3.12.3
architecture: ('64bit', 'ELF')
machine: x86_64
processor: 
blender_version: 4.0.2
blenderbim_version: 0.0.0
last_actions: 
# operator: BIM_OT_load_type_thumbnails
last_error: Traceback (most recent call last):
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 691, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "/usr/share/blender/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/bim/module/project/operator.py", line 777, in execute
    tool.Project.load_default_thumbnails()
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/tool/project.py", line 56, in load_default_thumbnails
    bpy.ops.bim.load_type_thumbnails(ifc_class=ifc_class, offset=0, limit=9)
  File "/usr/share/blender/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/tool/ifc.py", line 211, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/bim/ifc.py", line 380, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/bim/module/model/product.py", line 395, in _execute
    if tool.Model.update_thumbnail_for_element(element):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/tool/model.py", line 799, in update_thumbnail_for_element
    tool.Profile.draw_image_for_ifc_profile(draw, profile, size)
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/tool/profile.py", line 47, in draw_image_for_ifc_profile
    max_x = max([v[0] for v in grouped_verts])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
Location: /usr/share/blender/4.0/scripts/modules/bpy/ops.py:109
Location: /usr/share/blender/4.0/scripts/modules/bpy/ops.py:109


ifc: library.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.7.0
originating_system: BlenderBIM 0.0.999999
```

**Comment by Moult** [comment]
I think this is a duplicate of https://github.com/IfcOpenShell/IfcOpenShell/issues/4832#issuecomment-2162090927

**Comment by aothms** [comment]
I think so too. @brunopostle can you check again after https://github.com/IfcOpenShell/IfcOpenShell/commit/9c22e6ecc8a013632384b1710203a42c0d68f66a

**Comment by brunopostle** [comment]
Yes, it works. I can open the file in BlenderBIM, the error messages are gone, and I can preview the three profiles as expected.

Thanks, closing..

**Comment by aothms** [comment]
Thanks for checking
