### ISSUE TITLE
error install blenderbim

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4868]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/140309875/3b1581d3-9087-46eb-b41a-1dc051bda990)
os: Windows
os_version: 10.0.22621
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.7.9.240612
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 95, in <module>
    import blenderbim.bim
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\__init__.py", line 30, in <module>
    from blenderbim.tool.document import Document
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\document.py", line 23, in <module>
    from blenderbim.bim import import_ifc
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 38, in <module>
    import ifcopenshell.util.shape
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\shape.py", line 26, in <module>
    from ifcopenshell.geom import ShapeElementType, ShapeType
ImportError: cannot import name 'ShapeElementType' from 'ifcopenshell.geom' (C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\__init__.py)

**Comment by Moult** [comment]
We're still transitioning to a new version. I recommend waiting for another week before upgrading. Stick to the "stable" release for now.

**Comment by blenderarc** [comment]
yesterday I installed blenderbim 240612 successfully, but after I reinstalled version 240612 it failed

**Comment by Moult** [comment]
Are you following the upgrade process correctly? https://docs.blenderbim.org/users/installation.html#updating - especially the bit explaining that you have to disable, then **restart Blender**, prior to any upgrade.

That said, even if the install succeeds, I recommend you do not use the unstable version. There are many things still broken and you will likely damage your models.

**Comment by blenderarc** [comment]
I have done it correctly, but it still fails

**Comment by Tudjack** [comment]
I have the same errors an all releases above 240601. I tested it on two Windows machines and on a Fedora Linux machine as well. Blender 4.1 (Pyhton 3.11)

**Comment by Moult** [comment]
The stable release is 240602 on the Blender website - that _should_ work. Anything above that at the moment is not guaranteed. If you are having issues with the 240602 stable release, I'd really like to know about it and possibly join https://osarch.org/chat to share screen and debug together.

**Comment by Tudjack** [comment]
Yes, the stable release 240602 works as well. Most of the above of that release don't work. I haven't tested them all, but it's alright there's no rush :)

**Comment by BIMvoice** [comment]
I use the latest release from the 6th of June, which works on both Windows and Mac.

**Comment by Moult** [comment]
Installation should now work again.

However although it will install, don't expect it to work much. When there is a bot build later today or early tomorrow, it should start working again a bit more - i.e. most files will load. There are currently known issues with:

 1. AdvancedBRep geometry will not load
 2. Drawings will crash
 3. A bunch of material bugs - likely creating a wall type or similar from scratch will result in a bug.

**Comment by Moult** [comment]
Bot build variant is up, so closing this issue. Other known issues are tracked in separate bugs but at least it installs and has basic functions.
