### ISSUE TITLE
Error creating a drawing with underlay but no active drawing style

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4870]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/140309875/bf9b5c83-7f14-4f8c-8f73-a1ff6c518718)

Python: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 267, in execute
    underlay_svg = self.generate_underlay(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 354, in generate_underlay
    drawing_style = context.scene.DocProperties.drawing_styles[self.cprops.active_drawing_style_index]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

**Comment by blenderarc** [comment]
blenderbim 240602

**Comment by falken10vdl** [comment]
@blenderarc could you please provide some context about the error? What were your doing? Can you share an ifc file that generates this error or is it general?
Thanks!

**Comment by Andrej730** [comment]
If anyone stumble upon this, the solution is to select a drawing style you want for underlay, this error occurs if none of them is active.
I'll add a more readable error for this case.

<img width="327" height="211" alt="Image" src="https://github.com/user-attachments/assets/e557e2ae-3c9b-43b2-b74c-ee63097edd2a" />
