### ISSUE TITLE
Ui Patch Module has KeyError Literal in Reset Absolute Coordinate

### ISSUE THREAD

**Issue by aditiapratama** [IfcOpenShell/IfcOpenShell#4882]
Hello,

I stumble this error when switch to Reset Absolute Coordinate in Patch UI 

```shell

KeyError: 'Literal'
Location: /opt/blender/4.1.1/4.1/scripts/modules/bpy/ops.py:109
Traceback (most recent call last):
  File "/home/aditia/.config/blender/4.1/scripts/addons/blenderbim/bim/module/patch/prop.py", line 61, in update_ifc_patch_recipe
    bpy.ops.bim.update_ifc_patch_arguments(recipe=self.ifc_patch_recipes)
  File "/opt/blender/4.1.1/4.1/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/aditia/.config/blender/4.1/scripts/addons/blenderbim/bim/module/patch/operator.py", line 130, in execute
    new_attr.data_type = {
                         ^
KeyError: 'Literal'
Location: /opt/blender/4.1.1/4.1/scripts/modules/bpy/ops.py:109

File "/home/aditia/.config/blender/4.1/scripts/addons/blenderbim/bim/module/patch/prop.py", line 60, in update_ifc_patch_recipe
```

For now, I commented this code from line `130-135` in `bim/module/patch/operator.py` and seems it's working now.

```python
new_attr.data_type = {
    "str": "string",
    "float": "float",
    "int": "integer",
    "bool": "boolean",
}[arg_info.get("type", "str")]
```

**Comment by Moult** [comment]
This was fixed in d408568d01dd59657ee771f1fc11dfe25592c016 - feel free to ignore for now.
