### ISSUE TITLE
Doors don't show in one drawing, but do in another drawing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4883]
`FLOOR PLAN - BASEMENT` and `FLOOR PLAN - 1ST FLOOR` have the same drawings settings. 

![2024-06-17_12-46-22_blender_(Unsaved)_-_Blender_4 1blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/4106a6a4-57a8-4469-bc63-b87d15796489)

However the doors don't show up on the `FLOOR PLAN - 1ST FLOOR` , but they do for the `FLOOR PLAN - BASEMENT` drawing. 

files: [temp.zip](https://github.com/user-attachments/files/15875073/temp.zip)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d229f25e-737d-46b2-b2fc-f2e165f9be79)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/139ecb07-b5b4-494d-a191-9c53a28a43e4)

bb 240607

**Comment by theoryshaw** [comment]
This one has me flummoxed.

**Comment by theoryshaw** [comment]
For what it's worth, the hacky work around i've found is to change the 'z' distance on the camera, and it works **once**, but when I run it again, it doesn't work.

**Comment by theoryshaw** [comment]
if you try to activate `FLOOR PLAN - 1ST FLOOR` you get the following error. 
Not sure it's related to the original issue. 

`4.2.1 Bonsai 07.11-alpha240829-c3bcc2d`

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1546, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1561, in execute
    core.activate_drawing_view(tool.Ifc, tool.Blender, tool.Drawing, drawing=drawing)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\drawing.py", line 492, in activate_drawing_view
    drawing_tool.activate_drawing(camera)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 1787, in activate_drawing
    filtered_elements = cls.get_drawing_elements(drawing) | cls.get_drawing_spaces(drawing)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 1698, in get_drawing_spaces
    elements = cls.get_elements_in_camera_view(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 1886, in get_elements_in_camera_view
    [
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 1889, in <listcomp>
    if cls.is_in_camera_view(o, camera_inverse_matrix, x, y, camera.data.clip_start, camera.data.clip_end)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 1904, in is_in_camera_view
    local_bbox = [camera_inverse_matrix @ obj.matrix_world @ Vector(v) for v in obj.bound_box]
                                                                                ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'bound_box'

```

**Comment by theoryshaw** [comment]
this ifc file is now missing objects.

**Comment by Moult** [comment]
Seems to work now.

![Image](https://github.com/user-attachments/assets/2b912d42-e1b9-4e4c-b10f-edceaf7cd484)
![Image](https://github.com/user-attachments/assets/ddf7ff27-c0a4-479d-9de6-fafde841d68a)

Missing objects is due to invalid IFC data where there are IfcAxis2Placement3D elements with no coordinates. I guess this is a question for @aothms : 

 - When did IfcOpenShell start becoming picky about these invalid placements?
 - How come if I run the iterator including only elements that are unrelated to these invalid placements, the iterator still seems to process these placements? Is it doing extra work?

You can fix it like this:

```python
ifc_file = ifcopenshell.open('/home/dion/tmp/bugs/temp/old.ifc')
wrapper.turn_on_detailed_logging()

for e in ifc_file.by_type("IfcAxis2Placement3D"):
    if not e.Location:
        e.Location = ifc_file.createIfcCartesianPoint((0., 0., 0.))
        
ifc_file.write('/home/dion/tmp/bugs/temp/old2.ifc')
```

Test iterator script:

```python
import multiprocessing
import ifcopenshell
import ifcopenshell.ifcopenshell_wrapper as wrapper
import ifcopenshell.geom
wrapper.turn_off_detailed_logging()
ifc_file = ifcopenshell.open('/home/dion/tmp/bugs/temp/old.ifc')
wrapper.turn_on_detailed_logging()

for e in ifc_file.by_type("IfcAxis2Placement3D"):
    if not e.Location:
        e.Location = ifc_file.createIfcCartesianPoint((0., 0., 0.))
        

context = ifc_file.by_id(24)
settings = ifcopenshell.geom.settings()
settings.set("context-ids", [context.id()])
elements = [ifc_file.by_guid("0ac$_msGXFRhuDsqcmGOyN")]
iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count(), include=elements)
if iterator.initialize():
    print('init')
    while True:
        shape = iterator.get()
        element = ifc_file.by_id(shape.id)
        print(element)
        matrix = shape.transformation.matrix
        faces = shape.geometry.faces
        edges = shape.geometry.edges
        verts = shape.geometry.verts
        materials = shape.geometry.materials
        material_ids = shape.geometry.material_ids
        # ... write code to process geometry here ...
        if not iterator.next():
            break
print('fin')
```

With this output:

```
[Error] [2025-04-18 14:40:47] Type held at index 0 is 5Blank and not PN7IfcUtil12IfcBaseClassE
Failed to convert:
#2890502=IfcAxis2Placement3D($,$,$)
[Error] [2025-04-18 14:40:47] Unexpected topology
[Notice] [2025-04-18 14:40:47] Created 0 tasks for 0 products
[Warning] [2025-04-18 14:40:47] No representations encountered, aborting
```

**Comment by aothms** [comment]
No longer fails on invalid location.

> How come if I run the iterator including only elements that are unrelated to these invalid placements, the iterator still seems to process these placements? Is it doing extra work?

Because this is a placement on a representation map. The iterator first looks at the representations and searches for  the corresponding products. In this process the placement is evaluated, because of how mapped items are only considered with identity transformations. Maybe it's a bit wasteful, especially in selective processing.
