### ISSUE TITLE
error create drawing

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4888]
Python: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 271, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 550, in generate_linework
    drawing_elements = tool.Drawing.get_drawing_elements(self.camera_element, ifc_file=ifc)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\drawing.py", line 1671, in get_drawing_elements
    elements -= ifcopenshell.util.selector.filter_elements(ifc_file, exclude)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 326, in filter_elements
    transformer.transform(filter_elements_grammar.parse(query))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\lark\lark.py", line 658, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\lark\parser_frontends.py", line 104, in parse
    return self.parser.parse(stream, chosen_start, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\lark\parsers\earley.py", line 279, in parse
    to_scan = self._parse(lexer, columns, to_scan, start_symbol)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 152, in _parse
    to_scan = scan(i, to_scan)
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 125, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan},
lark.exceptions.UnexpectedCharacters: No terminal matches '.' in the current parser context, at line 1 col 1

.IfcVirtualElement
^
Expected one of: 
	* CLASSIFICATION
	* __ANON_3
	* ESCAPED_STRING
	* __ANON_2
	* MATERIAL
	* BANG
	* __ANON_0
	* __ANON_1
	* __ANON_4
	* TYPE
	* LOCATION
	* PARENT
	* SLASH
	* GROUP

**Comment by Moult** [comment]
Yep, the syntax you're using is the old selector. Remove the `.` at the beginning.
