### ISSUE TITLE
Crash when I try to delete some IFC "collections"

### ISSUE THREAD

**Issue by deedend** [IfcOpenShell/IfcOpenShell#4891]
```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240607
last_actions: 
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 338940, "Name": null}}
# ifcopenshell.api: root.remove_product
>>> {"product": {"cast_type": "entity_instance", "value": 341473, "Name": ""}}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 341473, "Name": ""}, "representation": {"cast_type": "entity_instance", "value": 341488, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 341488, "Name": null}}
# ifcopenshell.api: type.unassign_type
>>> {"related_objects": [{"cast_type": "entity_instance", "value": 341473, "Name": ""}]}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 338940, "Name": null}}
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 341473, "Name": ""}, "pset": {"cast_type": "entity_instance", "value": 341476, "Name": "Stacking"}}
# ifcopenshell.api: root.remove_product
>>> {"product": {"cast_type": "entity_instance", "value": 296198, "Name": "Beam"}}
# ifcopenshell.api: type.unassign_type
>>> {"related_objects": "(#296193=IfcBeam('3sSAqz7YucJwoWlrTX2wcz',#7,'200 x 200 x 16EA','',$,#296296,#296290,$,$), #296332=IfcBeam('3sSAqz7YucJwoWlrTX2wcl',#7,'200 x 200 x 16EA','',$,#296427,#296424,$,$), #296451=IfcBeam('3sSAqz7YucJwoWlrTX2wdP',#7,'200 x 200 x 16EA','',$,#296546,#296543,$,$), #296570=IfcBeam('3sSAqz7YucJwoWlrTX2wdB',#7,'200 x 200 x 16EA','',$,#296665,#296662,$,$), #296689=IfcBeam('3sSAqz7YucJwoWlrTX2wXJ',#7,'200 x 200 x 16EA','',$,#296784,#296781,$,$), #296808=IfcBeam('3sSAqz7YucJwoWlrTX2wXT',#7,'200 x 200 x 16EA','',$,#296903,#296900,$,$), #296927=IfcBeam('3sSAqz7YucJwoWlrTX2wXF',#7,'200 x 200 x 16EA','',$,#297022,#297019,$,$), #297710=IfcBeam('3sSAqz7YucJwoWlrTX2T8B',#7,'200 x 200 x 16EA','',$,#297805,#297802,$,$), #297829=IfcBeam('3sSAqz7YucJwoWlrTX2T9F',#7,'200 x 200 x 16EA','',$,#297924,#297921,$,$), #297948=IfcBeam('3sSAqz7YucJwoWlrTX2TAo',#7,'200 x 200 x 16EA','',$,#298043,#298040,$,$), #298067=IfcBeam('3sSAqz7YucJwoWlrTX2TA$',#7,'200 x 200 x 16EA','',$,#298162,#298159,$,$), #298186=IfcBeam('3sSAqz7YucJwoWlrTX2Sqg',#7,'200 x 200 x 16EA','',$,#298282,#298279,$,$), #317269=IfcBeam('3sSAqz7YucJwoWlrTX13iY',#7,'200 x 200 x 16EA','',$,#317364,#317361,$,$), #317388=IfcBeam('3sSAqz7YucJwoWlrTX13iZ',#7,'200 x 200 x 16EA','',$,#317483,#317480,$,$), #317507=IfcBeam('3sSAqz7YucJwoWlrTX13iW',#7,'200 x 200 x 16EA','',$,#317602,#317599,$,$), #317840=IfcBeam('3sSAqz7YucJwoWlrTX13MZ',#7,'200 x 200 x 16EA','',$,#317935,#317932,$,$), #317959=IfcBeam('3sSAqz7YucJwoWlrTX13MX',#7,'200 x 200 x 16EA','',$,#318054,#318051,$,$), #318078=IfcBeam('3sSAqz7YucJwoWlrTX13Mc',#7,'200 x 200 x 16EA','',$,#318173,#318170,$,$), #318197=IfcBeam('3sSAqz7YucJwoWlrTX13HD',#7,'200 x 200 x 16EA','',$,#318292,#318289,$,$), #318316=IfcBeam('3sSAqz7YucJwoWlrTX13Ho',#7,'200 x 200 x 16EA','',$,#318411,#318408,$,$))"}
# ifcopenshell.api: root.remove_product
>>> {"product": {"cast_type": "entity_instance", "value": 338976, "Name": "Gridlines"}}
last_error: Traceback (most recent call last):
  File "C:\Users\dvicario\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dvicario\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 714, in _execute
    tool.Geometry.delete_ifc_object(obj)
  File "C:\Users\dvicario\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\geometry.py", line 153, in delete_ifc_object
    blenderbim.core.spatial.load_container_manager(tool.Spatial)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'blenderbim.core.spatial' has no attribute 'load_container_manager'

ifc: N22_0027_M00_240530.ifc
schema: IFC4
preprocessor_version: Processor version 5.1.0.0
originating_system: hsbcad. IFCExporter v. 26.0.1.3412
```

**Comment by Moult** [comment]
This has since been fixed.
