### ISSUE TITLE
ERROR CREATE DRAWING

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4897]
Python: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 267, in execute
    underlay_svg = self.generate_underlay(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 354, in generate_underlay
    drawing_style = context.scene.DocProperties.drawing_styles[self.cprops.active_drawing_style_index]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

**Comment by blenderarc** [comment]
[DETAIL STRUKTUR - Copy.zip](https://github.com/user-attachments/files/15902847/DETAIL.STRUKTUR.-.Copy.zip)

**Comment by theoryshaw** [comment]
I bet it has something to do with this...
https://github.com/IfcOpenShell/IfcOpenShell/issues/4739

Basically, don't use this bottom...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/cb7a8bbb-9fb2-4999-80e3-22c9f0e7e72d)

use this one.. it will bring up (3) default styles that are created when you run a drawing...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/2b3ec78d-27ba-46c7-9c4c-620057e4f099)

**Comment by sboddy** [comment]
@blenderarc Do you still see this issue? I have opened your file in recent Blender/Bonsai, and all three drawings were created without issue. If you still see it, we would need more information on steps so we can replicate.

**Comment by sboddy** [comment]
Closing due to lack of response for more than 2 months. Please reopen if still an issue.
