### ISSUE TITLE
Duplicated Menu

### ISSUE THREAD

**Issue by R2naizr** [IfcOpenShell/IfcOpenShell#4904]
Seems to be a duplicated menu for "Material set property sets" labelled as "Material set item property sets",

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79116991/e597bd66-911e-4a89-9f62-e89610318966)

The latter returns the following error:

```
os: Windows
os_version: 10.0.22621
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240602
last_actions: 
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_add_pset
last_error: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\pset\operator.py", line 198, in _execute
    core.add_pset(tool.Ifc, tool.Pset, tool.Blender, obj_name=self.obj, obj_type=self.obj_type)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\core\pset.py", line 38, in add_pset
    elements = [ifc.get().by_id(blender.get_obj_ifc_definition_id(obj_name, obj_type))]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 425, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 410, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4917, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #0 not found

ifc: ifc project test.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: BlenderBIM 0.0.240602-47704b1
```

**Comment by Moult** [comment]
They are two different menus. One is psets for the material set, and the other is psets for the material set item. That said, we should improve it so that it is only visible when you have an active item (and therefore don't trigger that error).

**Comment by BIMvoice** [comment]
This is resolved on current v0.8.0. As @Moult noted, these are two distinct panels (property sets on the material set vs. on the active material set item). The Material Set Item panel now only shows its add control when there is an active material set item; otherwise it displays "No Material Set Item Edited." and returns, so the `+` button can no longer be clicked into the `Instance #0 not found` error. Verified in a headless repro: with no active item the add_pset path is unreachable from the UI, and with an active item it works. Recommend closing.

**Comment by BIMvoice** [comment]
@Moult re-confirming this is still resolved on current v0.8.0, closing since it looks like it was just missed. Thanks for the original clarification on the two panels.

Generated with the assistance of an AI coding tool.
