### ISSUE TITLE
Current daily build of bbaddon no longer works

### ISSUE THREAD

**Issue by MichaelVargg** [IfcOpenShell/IfcOpenShell#4906]
Maybe this will help with development:
os: Linux
os_version: #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: 
blender_version: 4.1.1
blenderbim_version: 0.7.9.240621
last_actions: 
last_error: Traceback (most recent call last):
  File "/home/michael/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/__init__.py", line 95, in <module>
    import blenderbim.bim
  File "/home/michael/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "/home/michael/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "/home/michael/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/tool/__init__.py", line 30, in <module>
    from blenderbim.tool.document import Document
  File "/home/michael/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/tool/document.py", line 23, in <module>
    from blenderbim.bim import import_ifc
  File "/home/michael/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 34, in <module>
    import ifcopenshell.util.shape
  File "/home/michael/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/shape.py", line 26, in <module>
    from ifcopenshell.geom import ShapeElementType, ShapeType
ImportError: cannot import name 'ShapeElementType' from 'ifcopenshell.geom' (/home/michael/.var/app/org.blender.Blender/config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/geom/__init__.py)
I had prior to posting this thought this only occurred on windows but it seems to be more general.

**Comment by Moult** [comment]
See #4868. We're still waiting on certain bugs to be resolved e.g. #4895 and then for a new bot build to complete.
