### ISSUE TITLE
v0.8.0 'Settings' object has no attribute 'DISABLE_TRIANGULATION'

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#4909]
I see this error trying to create the SVG for a drawing in BlenderBIM. This is with both IfcOpenShell and BlenderBIM from 2024-06-19, so they are in sync:

```
Error: Python: Traceback (most recent call last):
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 219, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 272, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 539, in generate_linework
    self.setup_serialiser(target_view)
  File "/usr/share/blender/4.0/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 877, in setup_serialiser
    self.svg_settings = ifcopenshell.geom.settings(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/ifcopenshell/geom/main.py", line 117, in __init__
    self.set(getattr(self, k), v)
             ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/ifcopenshell/geom/main.py", line 178, in __getattr__
    raise AttributeError("'Settings' object has no attribute '%s'" % k)
AttributeError: 'Settings' object has no attribute 'DISABLE_TRIANGULATION'
```

**Comment by aothms** [comment]
This is indeed one of the settings that got renamed in v0.8. 

    ITERATOR_OUTPUT=ifcopenshell.ifcopenshell_wrapper.NATIVE

**Comment by brunopostle** [comment]
There are still a few references to `DISABLE_TRIANGULATION`:
```
src/ifcgeom/IteratorSettings.h
src/serializers/HdfSerializer.cpp
src/ifcopenshell-python/ifcopenshell/draw.py
src/ifcopenshell-python/docs/ifcopenshell/geometry_settings.rst
src/blenderbim/blenderbim/bim/module/drawing/operator.py
```

**Comment by Moult** [comment]
Should be all clear on the Python side now. Just C++ and the docs to be updated.

**Comment by brunopostle** [comment]
There are still two references to `DISABLE_TRIANGULATION`, both in C++ code:

```
./serializers/HdfSerializer.cpp: IfcGeom::IteratorSettings::DISABLE_TRIANGULATION | IfcGeom::IteratorSettings::USE_BREP_DATA |
./ifcgeom/IteratorSettings.h: DISABLE_TRIANGULATION = 1 << 6,
```

**Comment by aothms** [comment]
@brunopostle both where in  a comment, but did a little bit of cleanup 9713b06d754603691d002aeb64aa15087d761b58
