### ISSUE TITLE
Segfault when using SVG serialiser on v0.8.0

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4913]
This is a model with a single cube and a single drawing.

[plan.ifc.txt](https://github.com/user-attachments/files/15951609/plan.ifc.txt)

You can recreate the segfault with:

```
python standalone_drawer.py /home/dion/plan.ifc "3S\$9XJfKj5JwcFWu8iLiOG" "3f5xqcou149PevOxs1meON"
```

Script:

```python
import sys
import ifcopenshell
import ifcopenshell.geom
import ifcopenshell.util.element
import multiprocessing
from typing import NamedTuple, List

# python standalone_drawer.py model.ifc guid_of_drawing guids,of,bad,elements output.svg


class LineworkContexts(NamedTuple):
    body: List[List[int]]
    annotation: List[List[int]]


class Drawer:
    def execute(self):
        ifc = ifcopenshell.open(sys.argv[1])
        self.camera_element = ifc.by_guid(sys.argv[2])
        # Don't use draw.main() just whilst we're prototyping and experimenting
        # Get all representation contexts to see what we're dealing with.
        target_view = ifcopenshell.util.element.get_psets(self.camera_element)["EPset_Drawing"]["TargetView"]
        contexts = self.get_linework_contexts(ifc, target_view)
        drawing_elements = set([ifc.by_guid(g) for g in sys.argv[3].split(",")])

        self.setup_serialiser(ifc, target_view)

        tree = ifcopenshell.geom.tree()
        tree.enable_face_styles(True)

        self.serialize_contexts_elements(ifc, tree, contexts, "body", drawing_elements, target_view)
        self.serialize_contexts_elements(ifc, tree, contexts, "annotation", drawing_elements, target_view)

        if self.camera_element not in drawing_elements:
            # The camera must always be included, regardless of any include/exclude filters.
            geom_settings = ifcopenshell.geom.settings()
            geom_settings.set("dimensionality", ifcopenshell.ifcopenshell_wrapper.CURVES_SURFACES_AND_SOLIDS)
            geom_settings.set("iterator-output", ifcopenshell.ifcopenshell_wrapper.NATIVE)
            # geom_settings.set_deflection_tolerance(0.0001)
            it = ifcopenshell.geom.iterator(geom_settings, ifc, include=[self.camera_element])
            for elem in it:
                self.serialiser.write(elem)

        self.serialiser.finalize()
        results = self.svg_buffer.get_value()
        print("results", results)

        with open(sys.argv[4], "w") as svg:
            svg.write(results)

    def get_linework_contexts(self, ifc, target_view) -> LineworkContexts:
        plan_body_target_contexts = []
        plan_body_model_contexts = []
        model_body_target_contexts = []
        model_body_model_contexts = []

        plan_annotation_target_contexts = []
        plan_annotation_model_contexts = []
        model_annotation_target_contexts = []
        model_annotation_model_contexts = []

        for rep_context in ifc.by_type("IfcGeometricRepresentationContext"):
            if rep_context.is_a("IfcGeometricRepresentationSubContext"):
                if rep_context.ContextType == "Plan":
                    if rep_context.ContextIdentifier in ["Body", "Facetation"]:
                        if rep_context.TargetView == target_view:
                            plan_body_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            plan_body_model_contexts.append(rep_context.id())
                    elif rep_context.ContextIdentifier == "Annotation":
                        if rep_context.TargetView == target_view:
                            plan_annotation_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            plan_annotation_model_contexts.append(rep_context.id())
                elif rep_context.ContextType == "Model":
                    if rep_context.ContextIdentifier in ["Body", "Facetation"]:
                        if rep_context.TargetView == target_view:
                            model_body_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            model_body_model_contexts.append(rep_context.id())
                    elif rep_context.ContextIdentifier == "Annotation":
                        if rep_context.TargetView == target_view:
                            model_annotation_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            model_annotation_model_contexts.append(rep_context.id())
            elif rep_context.ContextType == "Model":
                # You should never purely assign to a "Model" context, but
                # if you do, this is what we assume your intention is.
                model_body_model_contexts.append(rep_context.id())
                continue

        body_contexts = (
            [
                plan_body_target_contexts,
                plan_body_model_contexts,
                model_body_target_contexts,
                model_body_model_contexts,
            ]
            if target_view in ["PLAN_VIEW", "REFLECTED_PLAN_VIEW"]
            else [
                model_body_target_contexts,
                model_body_model_contexts,
            ]
        )

        annotation_contexts = (
            [
                plan_annotation_target_contexts,
                plan_annotation_model_contexts,
                model_annotation_target_contexts,
                model_annotation_model_contexts,
            ]
            if target_view in ["PLAN_VIEW", "REFLECTED_PLAN_VIEW"]
            else [
                model_annotation_target_contexts,
                model_annotation_model_contexts,
            ]
        )

        return LineworkContexts(body_contexts, annotation_contexts)

    def serialize_contexts_elements(
        self, ifc, tree: ifcopenshell.geom.tree, contexts: LineworkContexts, context_type, drawing_elements, target_view
    ):
        drawing_elements = drawing_elements.copy()
        contexts = getattr(contexts, context_type)
        for context in contexts:
            if not context or not drawing_elements:
                continue
            geom_settings = ifcopenshell.geom.settings()
            geom_settings.set("dimensionality", ifcopenshell.ifcopenshell_wrapper.CURVES_SURFACES_AND_SOLIDS)
            geom_settings.set("iterator-output", ifcopenshell.ifcopenshell_wrapper.NATIVE)
            if ifc.by_id(context[0]).ContextType == "Plan" and "PLAN_VIEW" in target_view:
                offset = ifcopenshell.ifcopenshell_wrapper.float_array_3()
                # A 2mm Z offset to combat Z-fighting in plan or RCPs
                offset[2] = 0.002 if target_view == "PLAN_VIEW" else -0.002
                geom_settings.offset = offset
            geom_settings.set("context-ids", context)
            it = ifcopenshell.geom.iterator(geom_settings, ifc, multiprocessing.cpu_count(), include=drawing_elements)
            processed = set()
            for elem in it:
                processed.add(ifc.by_id(elem.id))
                self.serialiser.write(elem)
                tree.add_element(elem)
            drawing_elements -= processed

    def setup_serialiser(self, ifc, target_view):
        self.svg_settings = ifcopenshell.geom.settings()
        self.svg_settings.set("dimensionality", ifcopenshell.ifcopenshell_wrapper.CURVES_SURFACES_AND_SOLIDS)
        self.svg_settings.set("iterator-output", ifcopenshell.ifcopenshell_wrapper.NATIVE)
        self.svg_buffer = ifcopenshell.geom.serializers.buffer()
        self.serialiser_settings = ifcopenshell.geom.serializer_settings()
        self.serialiser = ifcopenshell.geom.serializers.svg(
            self.svg_buffer, self.svg_settings, self.serialiser_settings
        )
        self.serialiser.setFile(ifc)
        self.serialiser.setWithoutStoreys(True)
        self.serialiser.setPolygonal(True)  # Always get back polygon output
        # self.serialiser.setUseHlrPoly(True)
        self.serialiser.setUseHlrPoly(False)
        # Objects with more than these edges are rendered as wireframe instead of HLR for optimisation
        self.serialiser.setProfileThreshold(10000)
        self.serialiser.setUseNamespace(True)
        self.serialiser.setAlwaysProject(True)
        self.serialiser.setAutoElevation(False)
        self.serialiser.setAutoSection(False)
        self.serialiser.setPrintSpaceNames(False)
        self.serialiser.setPrintSpaceAreas(False)
        self.serialiser.setDrawDoorArcs(False)
        self.serialiser.setNoCSS(True)
        self.serialiser.setElevationRefGuid(self.camera_element.GlobalId)
        self.serialiser.setScale(1 / 50)
        self.serialiser.setSubtractionSettings(ifcopenshell.ifcopenshell_wrapper.ALWAYS)
        self.serialiser.setUsePrefiltering(True)  # See #3359
        # self.serialiser.setUsePrefiltering(False)  # See #3359
        self.serialiser.setUnifyInputs(True)
        self.serialiser.setSegmentProjection(True)
        if target_view == "REFLECTED_PLAN_VIEW":
            self.serialiser.setMirrorY(True)


Drawer().execute()
```

**Comment by Moult** [comment]
Stacktrace:

```
(gdb) bt
#0  0x00007ffff3a5f2e0 in ifcopenshell::geometry::taxonomy::item::item (this=0x555555ce24f0) at /home/dion/Projects/ifcopenshell/src/ifcwrap/../ifcgeom/../ifcgeom/../ifcgeom/../ifcgeom/../ifcgeom/../ifcgeom/taxonomy.h:98
#1  0x00007ffff3a60ae6 in ifcopenshell::geometry::taxonomy::style::style (this=0x555555ce24f0) at /home/dion/Projects/ifcopenshell/src/ifcwrap/../ifcgeom/../ifcgeom/../ifcgeom/../ifcgeom/../ifcgeom/../ifcgeom/taxonomy.h:417
#2  0x00007ffff3afebb1 in std::__new_allocator<ifcopenshell::geometry::taxonomy::style>::construct<ifcopenshell::geometry::taxonomy::style, ifcopenshell::geometry::taxonomy::style const&> (__p=0x555555ce24f0, this=0x555555ced6b8)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/new_allocator.h:191
#3  std::allocator_traits<std::allocator<ifcopenshell::geometry::taxonomy::style> >::construct<ifcopenshell::geometry::taxonomy::style, ifcopenshell::geometry::taxonomy::style const&> (__p=0x555555ce24f0, __a=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/alloc_traits.h:538
#4  std::vector<ifcopenshell::geometry::taxonomy::style, std::allocator<ifcopenshell::geometry::taxonomy::style> >::_M_realloc_insert<ifcopenshell::geometry::taxonomy::style const&> (this=0x555555ced6b8, 
    __position=non-dereferenceable iterator for std::vector) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/vector.tcc:468
#5  0x00007ffff3aa7152 in std::vector<ifcopenshell::geometry::taxonomy::style, std::allocator<ifcopenshell::geometry::taxonomy::style> >::push_back (this=0x555555ced6b8, __x=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/stl_vector.h:1289
#6  0x00007ffff3a7ee2b in IfcGeom::tree::add_element (this=0x555555ced2f0, elem=0x7fffd801a550) at /home/dion/Projects/ifcopenshell/src/ifcwrap/../ifcgeom/kernels/opencascade/IfcGeomTree.h:1983
#7  0x00007ffff3971837 in _wrap_tree_add_element__SWIG_1 (self=<module at remote 0x7ffff702cae0>, nobjs=2, swig_obj=0x7fffffffcb50)
    at /home/dion/Projects/ifcopenshell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:55729
#8  0x00007ffff3971c3d in _wrap_tree_add_element (self=<module at remote 0x7ffff702cae0>, args=Python Exception <class 'AssertionError'>: 
) at /home/dion/Projects/ifcopenshell/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:55779
#9  0x00007ffff7b19405 in ?? () from /usr/lib64/libpython3.11.so.1.0
#10 0x00007ffff7ad44ce in _PyObject_Call () from /usr/lib64/libpython3.11.so.1.0
#11 0x00007ffff7a83a84 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.11.so.1.0
#12 0x00007ffff7bae9b0 in ?? () from /usr/lib64/libpython3.11.so.1.0
#13 0x00007ffff7baea79 in PyEval_EvalCode () from /usr/lib64/libpython3.11.so.1.0
#14 0x00007ffff7bf1a03 in ?? () from /usr/lib64/libpython3.11.so.1.0
#15 0x00007ffff7bf1c26 in ?? () from /usr/lib64/libpython3.11.so.1.0
#16 0x00007ffff7bf1d00 in ?? () from /usr/lib64/libpython3.11.so.1.0
#17 0x00007ffff7bf488d in _PyRun_SimpleFileObject () from /usr/lib64/libpython3.11.so.1.0
#18 0x00007ffff7bf4e34 in _PyRun_AnyFileObject () from /usr/lib64/libpython3.11.so.1.0
#19 0x00007ffff7c133d0 in Py_RunMain () from /usr/lib64/libpython3.11.so.1.0
#20 0x00007ffff7c1392b in Py_BytesMain () from /usr/lib64/libpython3.11.so.1.0
#21 0x00007ffff785e320 in ?? () from /lib64/libc.so.6
#22 0x00007ffff785e3d9 in __libc_start_main () from /lib64/libc.so.6
#23 0x0000555555555095 in _start ()
```

**Comment by Moult** [comment]
This is now fixed :)
