### ISSUE TITLE
[bug] Error when removing presentation layer: "Instance xxx not found"

### ISSUE THREAD

**Issue by Vanuan** [IfcOpenShell/IfcOpenShell#4934]
When attempting to remove a presentation layer in the Geometric Relationships section of the Geometry and Materials subtab, I encountered the following error:

RuntimeError: Instance xxxx not found

Steps to reproduce:
1. Open the Geometry and Materials subtab
2. Navigate to the Geometric Relationships section
3. Add presentation layer
4. Click assign/disable/freeze icons in random sequence several times
5. Attempt to remove a presentation layer

Environment:
- OS: Linux (Ubuntu)
- Blender version: 4.1.1
- BlenderBIM version: 0.0.240602
- Python version: 3.11.7
- Architecture: 64-bit
- IFC schema: IFC4

Full stacktrace:
```
os: Linux
os_version: #117-Ubuntu SMP PREEMPT Tue Apr 30 10:12:40 UTC 2024
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: x86_64
blender_version: 4.1.1
blenderbim_version: 0.0.240602
last_actions: 
# ifcopenshell.api: layer.edit_layer
>>> {"layer": {"cast_type": "entity_instance", "value": 6946, "Name": "Plan"}, "attributes": "{'Name': 'Plan', 'Description': None, 'Identifier': None}"}
# operator: BIM_OT_assign_presentation_layer
# ifcopenshell.api: layer.assign_layer
>>> {"items": [{"cast_type": "entity_instance", "value": 5394, "Name": null}], "layer": {"cast_type": "entity_instance", "value": 6946, "Name": "Plan"}}
# operator: BIM_OT_unassign_presentation_layer
# ifcopenshell.api: layer.unassign_layer
>>> {"items": [{"cast_type": "entity_instance", "value": 5394, "Name": null}], "layer": {"cast_type": "entity_instance", "value": 6946, "Name": "Plan"}}
# operator: BIM_OT_assign_presentation_layer
# operator: BIM_OT_assign_presentation_layer
# operator: BIM_OT_remove_presentation_layer
# operator: BIM_OT_remove_presentation_layer
# operator: BIM_OT_remove_presentation_layer
last_error: Traceback (most recent call last):
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/layer/operator.py", line 132, in _execute
    ifcopenshell.api.run("layer.remove_layer", self.file, **{"layer": self.file.by_id(self.layer)})
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 425, in by_id
    return self[id]
           ~~~~^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 410, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3800, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #6,946 not found

ifc: testmore.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: BlenderBIM 0.0.240402-bf9bddc
```

**Comment by Vanuan** [comment]
Ok, can't reproduce anymore. But another bug: button Assign Presentation Layer doesn't change the icon. Also, I would think that if no object selected, the button should not be visible

**Comment by Vanuan** [comment]
Anyway, according to this thread presentation layers panel is buggy: https://community.osarch.org/discussion/1859/ifc-layer-support

**Comment by BIMvoice** [comment]
Thanks @Vanuan. Root caused and fixed.

The crash is a stale layer id. The Presentation Layers panel bakes each layer's id into its row buttons at draw time. Presentation layers are removed automatically once they have no assigned items left (an IfcPresentationLayerAssignment must keep at least one item to stay schema valid), so unassigning the last item, or an otherwise emptied layer, deletes the layer. A queued or repeated click then hands the remove/assign operator an id that no longer exists, and file.by_id raised RuntimeError: Instance #N not found, breaking the panel.

Fix: every layer operator that takes an id from the UI (remove, assign, unassign, enable editing, select) now resolves it through a guard that validates the id against current state. If the layer is gone it reloads the layer list so the stale row disappears, shows a short warning, and cancels cleanly instead of calling by_id on a deleted entity.

Verified in a live Blender session across the reported paths: the stale id sequence (assign, unassign so the layer is emptied and auto removed, then assign again on the same id) now reports "Presentation layer no longer exists, the layer list has been refreshed" with no traceback; rapid repeated assign and unassign across several objects does not crash; and the same holds for IfcPresentationLayerWithStyle layers with the on, frozen and blocked icons.

PR: #8384
