### ISSUE TITLE
[bug] Error when switching representations for door type: "'NoneType' object has no attribute 'BIMMeshProperties'"

### ISSUE THREAD

**Issue by Vanuan** [IfcOpenShell/IfcOpenShell#4936]
Title: Error when switching representations for door type: "'NoneType' object has no attribute 'BIMMeshProperties'"

Description:

I encountered an error while working with representations for a door type. The error occurs when trying to switch representations after adding and deleting some representations.

Steps to reproduce:
1. Create a door type with a few instances in the wall.
2. Select the door type.
3. Add a new representation > bounding box.
4. Add another representation > Full representation.
5. Activate one of the representations.
6. Delete one of the representations.
7. Attempt to switch representations.

Error message:

```
os: Linux
os_version: #117-Ubuntu SMP PREEMPT Tue Apr 30 10:12:40 UTC 2024
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: x86_64
blender_version: 4.1.1
blenderbim_version: 0.0.240602
last_actions: 
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 7203, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 7184, "Name": null}}
# operator: BIM_OT_switch_representation
# operator: BIM_OT_remove_representation
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 5413, "Name": "TYPEX2"}, "representation": {"cast_type": "entity_instance", "value": 7212, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 7224, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 7231, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 7212, "Name": null}}
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
last_error: Traceback (most recent call last):
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 269, in _execute
    core.switch_representation(
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/core/geometry.py", line 141, in switch_representation
    new_repr_data = geometry.import_representation(obj, representation, apply_openings=apply_openings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/tool/geometry.py", line 551, in import_representation
    ifc_importer.material_creator.create(element, obj, mesh)
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 72, in create
    tool.Geometry.record_object_materials(obj)
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/tool/geometry.py", line 639, in record_object_materials
    obj.data.BIMMeshProperties.material_checksum = str([s.id() for s in cls.get_styles(obj) if s])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'BIMMeshProperties'

ifc: testmore.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: BlenderBIM 0.0.240402-bf9bddc
```

**Comment by Moult** [comment]
Yes, this is a known limitation where the moment it's an empty, you can't switch back to a mesh. I guess it's rare that users directly manipulate representations like this so it has never been a priority. I've got some code locally uncommitted for at least a year now that handles this so I'll take a look.

**Comment by sboddy** [comment]
@Vanuan I can't reproduce this in 
```
blender_version: 4.4.1
bonsai_version: 0.8.3-alpha250420
```

Do you still see this, or can we close the issue?

**Comment by sboddy** [comment]
No response from submitter. Closing for now, but please reopen if necessary.
