### ISSUE TITLE
Bug in BimBlender add on while opening an ifc (which element classes were reassigned through a ifccsv import )

### ISSUE THREAD

**Issue by alaasquan** [IfcOpenShell/IfcOpenShell#4940]
```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240602
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 691, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 771, in execute
    ifc_importer.execute()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 265, in execute
    self.create_collections()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 1607, in create_collections
    self.create_aggregate_and_nest_collections()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 1661, in create_aggregate_and_nest_collections
    rel_aggregates = [
                     ^
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 1664, in <listcomp>
    if (relating_obj := r.RelatingObject).is_a("IfcElement") or relating_obj.is_a("IfcElementType")
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_a'
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109


ifc: updated_ifc_file.ifc
schema: IFC4
preprocessor_version: The EXPRESS Data Manager Version 5.02.0100.07 : 28 Aug 2013
originating_system: 22.0.2.392 - Exporter 22.0.2.392 - Interface utilisateur alternative 22.0.2.392
```

**Comment by Moult** [comment]
That looks like your model is invalid. Can you please share it (or dion@thinkmoult.com if private)?

**Comment by Moult** [comment]
Bump @alaasquan can you share your model?

**Comment by sboddy** [comment]
@Moult Did @alaasquan ever send in a file via the private route? If not I think this should get closed.

**Comment by alaasquan** [comment]
@sboddy @Moult Hello guys , thank you so much for the consideration. It's been months since I finished the project related to this. In fact , as I remember, I was trying to open the IFC while the addon was not available I guess you were switching to Bonsai that time. Thank you again!
