### ISSUE TITLE
[BlenderBIM] Error when create drawing: RuntimeError: Instance #0 not found 

### ISSUE THREAD

**Issue by vivenHu** [IfcOpenShell/IfcOpenShell#4943]
I created my own IfcElementTypes in blenderBIM, and generate a test scene. When I try to create drawing for a 2d plan, I got this error
```
Python: Traceback (most recent call last):
  File "C:\Users\hwwde\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 235, in execute
    self.drawing = self.file.by_id(drawing_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwwde\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 411, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\hwwde\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 396, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwwde\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4917, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #0 not found
```
Here's the IFC file I created just faked in txt format:
[test.txt](https://github.com/user-attachments/files/16028098/test.txt)

Thank you for your help.

**Comment by Moult** [comment]
I just tested this and it seems to work fine in the latest stable version from blenderbim.org. Are you sure you are loading the .ifc file? Do not load the .blend file.

**Comment by sboddy** [comment]
@vivenHu Like Moult, I cannot reproduce. The drawing generates successfully for me with recent Blender/Bonsai. If you still believe this is an issue, please reopen.
