### ISSUE TITLE
Object not found when butting/extending the wall

### ISSUE THREAD

**Issue by Vanuan** [IfcOpenShell/IfcOpenShell#4946]
I think I finally reproduced something reliably.

1. Create a perimeter with mitres.
2. Create an internal wall across slightly larger
3. Select the internal wall and the adjacent wall
4. Click butt
5. An adjacent wall becomes shorter
6. Click undo
7. Now the internal wall is buggy, clicking extend raises exception.

[project0.zip](https://github.com/user-attachments/files/16034306/project0.zip)

```
os: Linux
os_version: #117-Ubuntu SMP PREEMPT Tue Apr 30 10:12:40 UTC 2024
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: x86_64
blender_version: 4.1.1
blenderbim_version: 0.0.240602
last_actions: 
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 1658, "Name": null}}
# ifcopenshell.api: geometry.add_wall_representation
>>> {"context": {"cast_type": "entity_instance", "value": 15, "Name": null}, "length": "2.9999998410550437", "height": "2.79999995231628", "x_angle": "0", "offset": "0.0", "thickness": "0.200000002980232", "clippings": "[{'type': 'IfcBooleanClippingResult', 'operand_type': 'IfcHalfSpaceSolid', 'matrix': Matrix(((-0.7071051597595215, 0.0, 0.7071084380149841, 2.999999761581421),\n        (0.7071084380149841, 0.0, 0.7071051597595215, -2.3851043806644157e-08),\n        (0.0, 1.0, 0.0, 0.0),\n        (0.0, 0.0, 0.0, 1.0)))}]", "booleans": "[]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 243, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 1682, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 1682, "Name": null}}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 243, "Name": "Wall"}, "matrix": {"cast_type": "ndarray", "value": [[6.715443419125222e-07, -1.0, 0.0, 3.000001907348633], [1.0, 6.715443419125222e-07, 0.0, 2.9999983310699463], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 243, "Name": "Wall"}}
# operator: BIM_OT_hotkey
# operator: BIM_OT_join_wall
# ifcopenshell.api: geometry.connect_path
>>> {"related_element": {"cast_type": "entity_instance", "value": 657, "Name": "Wall"}, "relating_element": {"cast_type": "entity_instance", "value": 243, "Name": "Wall"}, "relating_connection": "ATPATH", "related_connection": "ATSTART", "description": "BUTT"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
last_error: Traceback (most recent call last):
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/model/workspace.py", line 591, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/model/workspace.py", line 707, in hotkey_S_E
    bpy.ops.bim.join_wall(join_type="T")
  File "/snap/blender/4786/4.1/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/model/wall.py", line 111, in _execute
    joiner.join_T(obj, context.active_object)
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/model/wall.py", line 1094, in join_T
    self.recreate_wall(element1, wall1, axis1["reference"], axis1["reference"])
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/model/wall.py", line 1127, in recreate_wall
    extrusion_data = self.get_extrusion_data(tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 425, in by_id
    return self[id]
           ~~~~^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 410, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3800, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #1,596 not found
Location: /snap/blender/4786/4.1/scripts/modules/bpy/ops.py:109


ifc: project0.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: BlenderBIM 0.0.240602-47704b1
```

**Comment by Vanuan** [comment]
Actually, it works with undoing any ETY action.

**Comment by Vanuan** [comment]
Looks to be a duplicate of  #3659

**Comment by Moult** [comment]
Hmm, I can't recreate this. Maybe I'm not doing it exactly right?

**Comment by Vanuan** [comment]
I think I found the culprit. It's selecting three walls and applying Mitre. I think it should just display an error in the status bar rather than printing stacktrace. After that, clicking extend, undo and extend again should reproduce the issue.

This is from a fresh Blender session:
https://youtu.be/wXJpofkyEUY

If it isn't reproducible, might be fixed in the HEAD already.

**Comment by theoryshaw** [comment]
You might know this already, but you can upload mp4's to these github issues.

**Comment by Vanuan** [comment]
It's mkv. Don't know how to convert

**Comment by Vanuan** [comment]
Reproducible in blenderbim-0.7.9.240629

**Comment by Moult** [comment]
> I think it should just display an error in the status bar rather than printing stacktrace.

Fixed, but let's keep this open since there are more situations I need to handle.

> After that, clicking extend, undo and extend again should reproduce the issue.

The first stack trace left the state mangled and would result in that sync issue. As a general rule, any exception that triggers an uncaught exception (and that big notice saying "hey, an error occured") means that it may be unsafe to continue.

**Comment by Vanuan** [comment]
> As a general rule, any exception that triggers an uncaught exception (and that big notice saying "hey, an error occured") means that it may be unsafe to continue.

Hm. Maybe there should be a dialog with two button "I understand the risk, continue" and "Save and restart" with collapsible advanced panel with "Copy technical details"? Dismissable panel makes an impression the error is recoverable.

Alternatively, all errors should be truly recoverable.
