### ISSUE TITLE
Creating Insulation Via IfcBuildingElementPartType / IfcBuildingElementPart

### ISSUE THREAD

**Issue by Dayo9174** [IfcOpenShell/IfcOpenShell#4948]
Hi 

I get the error below when ever i am trying to create a under floor insulation

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/129775059/2454ac63-0259-4f24-b9b8-bb0844ab557c)

I am using the latest build, blenderbim-0.7.9.240612-py310-win. But no error when ever I use the last stable build blenderbim-240606-py311-win

Am I doing something wrong?

```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
blender_version: 4.1.0
blenderbim_version: 0.7.9.240629
last_actions: 
# ifcopenshell.api: material.unassign_material
>>> {"products": [{"cast_type": "entity_instance", "value": 122853, "Name": "TYPEX"}]}
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_add_type
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcBuildingElementPartType", "predefined_type": "INSULATION", "name": "Under-Floor Insulation"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 123246, "Name": "Under-Floor Insulation"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: material.assign_material
>>> {"products": [{"cast_type": "entity_instance", "value": 123246, "Name": "Under-Floor Insulation"}], "type": "IfcMaterialLayerSet"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: material.add_layer
>>> {"layer_set": {"cast_type": "entity_instance", "value": 123247, "Name": null}, "material": {"cast_type": "entity_instance", "value": 27234, "Name": "Default"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\type\operator.py", line 318, in _execute
    layer = ifcopenshell.api.run("material.add_layer", ifc_file, layer_set=layer_set, material=material)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 92, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 271, in wrapper
    listener(usecase_path, ifc_file, settings)
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\model\product.py", line 517, in ensure_material_assigned
    elements = settings["products"]
               ~~~~~~~~^^^^^^^^^^^^
KeyError: 'products'

ifc: 00.SJCES - Main Building - 2406021.ifc
schema: IFC4X3
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: BlenderBIM 0.0.240606-98ec3e2
```

**Comment by Moult** [comment]
I don't recommend using the latest unstable release for anything other than testing right now. There are too many incomplete things. In this case it's due to the listeners for materials vs styles which we're in the process of redoing. It's now "fixed" but there are still many incomplete things which can lead to broken state.

**Comment by Dayo9174** [comment]
Noted, thanks for all you guys do.
