### ISSUE TITLE
[bug?] Door rotation and alignment issue causes 3D representation to disappear

### ISSUE THREAD

**Issue by Vanuan** [IfcOpenShell/IfcOpenShell#4949]
When attempting to change the direction of a door's opening, I rotated the door 180 degrees. I also tried to align the door to the exterior of the wall. Following these actions, the 3D representation of the door disappeared. Interestingly, this issue also affected other instances of the same door type.

**Steps to Reproduce:**
1. Change the direction of the door's opening by rotating it 180 degrees.
2. Align the door to the exterior of the wall.
3. Observe that the 3D representation of the door disappears.
4. Note that other instances of the same door type are also affected.

**Expected Behavior:**
The door should rotate 180 degrees and align with the exterior of the wall without losing its 3D representation.

**Actual Behavior:**
The 3D representation of the door disappears after rotation and alignment, and this issue also affects other instances of the same door type.

**Stack Trace:**
When trying to force displaying the SweptSolid representation, the following error is raised:

```
os: Linux
os_version: #117-Ubuntu SMP PREEMPT Tue Apr 30 10:12:40 UTC 2024
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: x86_64
blender_version: 4.1.1
blenderbim_version: 0.0.240602
last_actions: 
# ifcopenshell.api: geometry.add_wall_representation
>>> {"context": {"cast_type": "entity_instance", "value": 15, "Name": null}, "length": "0.9500000489385608", "height": "-0.025000000372528936", "x_angle": "3.1415927410125732", "offset": "0.0", "thickness": "0.0", "clippings": "[]", "booleans": "[]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 113, "Name": "DoorType"}, "representation": {"cast_type": "entity_instance", "value": 196, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 196, "Name": null}}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 221, "Name": "Door"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 2.384185791015625e-07, 0.0, 1.3650543689727783], [-2.384185791015625e-07, 1.0, 0.0, 0.09250015020370483], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 221, "Name": "Door"}}
# operator: BIM_OT_switch_representation
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 221, "Name": "Door"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 2.384185791015625e-07, 0.0, 1.3650543689727783], [-2.384185791015625e-07, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 221, "Name": "Door"}}
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 15, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcDoor/Door\") at 0x7f0ec6ab0108>", "geometry": "<bpy_struct, Mesh(\"15/441\") at 0x7f0ebad07308>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "IfcExtrudedAreaSolid/IfcArbitraryProfileDefWithVoids", "profile_set_usage": "None", "text_literal": "None"}
last_error: Traceback (most recent call last):
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 269, in _execute
    core.switch_representation(
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/core/geometry.py", line 120, in switch_representation
    geometry.run_geometry_update_representation(obj=obj)
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/tool/geometry.py", line 691, in run_geometry_update_representation
    bpy.ops.bim.update_representation(obj=obj.name, ifc_representation_class="")
  File "/snap/blender/4786/4.1/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 326, in _execute
    self.update_obj_mesh_representation(context, obj)
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 406, in update_obj_mesh_representation
    new_representation = ifcopenshell.api.run("geometry.add_representation", self.file, **representation_data)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 184, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 350, in wrapper
    raise e
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/__init__.py", line 344, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/geometry/add_representation.py", line 97, in add_representation
    return usecase.execute()
           ^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/geometry/add_representation.py", line 114, in execute
    return self.create_model_representation()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/geometry/add_representation.py", line 183, in create_model_representation
    return self.create_variable_representation()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/geometry/add_representation.py", line 301, in create_variable_representation
    return self.create_arbitrary_void_extrusion_representation()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/geometry/add_representation.py", line 706, in create_arbitrary_void_extrusion_representation
    return self.create_arbitrary_extrusion_representation()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/api/geometry/add_representation.py", line 694, in create_arbitrary_extrusion_representation
    item = helper.create_extruded_area_solid(self.settings["geometry"], indices["extrusion"], profile_def)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/geometry/helper.py", line 507, in create_extruded_area_solid
    direction = self.get_extrusion_direction(mesh, extrusion_indices, profile_def["curve_ucs"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.config/blender/4.1/scripts/addons/blenderbim/bim/module/geometry/helper.py", line 649, in get_extrusion_direction
    curve_ucs["center"] + (mesh.vertices[extrusion_indices[1]].co - mesh.vertices[extrusion_indices[0]].co)
                                         ~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
Location: /snap/blender/4786/4.1/scripts/modules/bpy/ops.py:109


ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: IfcOpenShell v0.7.0-c7830e9e5
```

**Attachments:**

https://www.youtube.com/watch?v=5W0WjORxT1E

**Comment by Vanuan** [comment]
@theoryshaw I guess not all videocodecs are supported? Does it play for you? Is it available for download?

**Comment by Vanuan** [comment]
Maybe it's silly, trying to align an exterior face of the door to exterior face of the wall. But I think swept solid shouldn't disappear.

Maybe there's a better way to change the direction of the opening? Mirror?

Maybe there's a way to align the exterior of the door to the interior of the wall? Putting alignment tools inside the object creation seems awkward.

**Comment by Vanuan** [comment]
Reproducible in blenderbim-0.7.9.240629

**Comment by Vanuan** [comment]
Further quirk: applying void with rotated door rotates the door back with origins aligned. So how do I change the opening direction of the door?

**Comment by Vanuan** [comment]
Actually, apply void repositions the door whether it's rotated or not. If you applied the void, you have to align the door to the required face again.

**Comment by Moult** [comment]
The main issue is resolved in https://github.com/IfcOpenShell/IfcOpenShell/commit/c4b3e57677f70a569c465d336375ce7b94cdea52

The apply void issues is a separate issue - basically that feature doesn't consider flipped state yet so we'll need to add that consideration.

**Comment by Vanuan** [comment]
Created a new bug report for the apply void issue.
Will test the fix after the daily build is released.

**Comment by Moult** [comment]
BTW the daily builds are available after each commit (though the date won't increment). So typically 5 minutes after a commit you should be able to test.

**Comment by Vanuan** [comment]
:exploding_head:
