### ISSUE TITLE
error when `bim.unlink_object`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4951]
I think the error was introduced at revision: d2198568b2bae1cd1b5904aeabd8d996d6de6c98

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/7f4cbfe8-391a-4924-98a5-bdc1abda01f7

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240605
last_actions: 
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 927, "Name": null}}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 940, "Name": "W Shapes:W12X26:354981"}, "representation": {"cast_type": "entity_instance", "value": 930, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 930, "Name": null}}
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 940, "Name": "W Shapes:W12X26:354981"}, "pset": {"cast_type": "entity_instance", "value": 951, "Name": "Pset_ReinforcementBarPitchOfBeam"}}
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 940, "Name": "W Shapes:W12X26:354981"}, "pset": {"cast_type": "entity_instance", "value": 945, "Name": "Pset_BeamCommon"}}
# ifcopenshell.api: type.unassign_type
>>> {"related_objects": [{"cast_type": "entity_instance", "value": 940, "Name": "W Shapes:W12X26:354981"}]}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1058, "Name": null}}
# ifcopenshell.api: owner.add_application
>>> {"version": "0.0.240605", "application_full_name": "BlenderBIM Add-on", "application_identifier": "BlenderBIM"}
# ifcopenshell.api: material.unassign_material
>>> {"products": [{"cast_type": "entity_instance", "value": 940, "Name": "W Shapes:W12X26:354981"}]}
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 940, "Name": "W Shapes:W12X26:354981"}, "pset": {"cast_type": "entity_instance", "value": 948, "Name": "Pset_EnvironmentalImpactIndicators"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\root\operator.py", line 272, in _execute
    tool.Root.unlink_object(obj)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\root.py", line 318, in unlink_object
    blenderbim.core.style.unlink_style(tool.Ifc, tool.Style, obj=material_slot.material)
TypeError: unlink_style() got an unexpected keyword argument 'obj'

ifc: Project1.ifc
schema: IFC4
preprocessor_version: The EXPRESS Data Manager Version 5.02.0100.07 : 28 Aug 2013
originating_system: 20200210_1400(x64) - Exporter 20.2.12.1 - Alternate UI 20.2.12.1
```

**Comment by Moult** [comment]
Already fixed by @Andrej730 in https://github.com/IfcOpenShell/IfcOpenShell/commit/75f8e75a8e5f9e551494af8fcc18e518101d25d0

**Comment by theoryshaw** [comment]
cool.. haven't ventured into .8 yet.
