### ISSUE TITLE
[bug] Door Parametric Geometry editing when selecting an instance rather than a type

### ISSUE THREAD

**Issue by Vanuan** [IfcOpenShell/IfcOpenShell#4952]
When editing the parametric geometry of a door, specifically changing the Door operation or other parameters, and then clicking "Finish Editing", a RuntimeError occurs. The error suggests a failure in processing the shape of the door.

**Steps to Reproduce:**

1. Open a project with an existing door (or create a new door), see file attached.
2. Select the door.
3. Navigate to the Parametric Geometry panel.
4. Change the Door operation (e.g., from "SINGLE_SWING_RIGHT" to "SINGLE_SWING_LEFT") or modify other parameters.
5. Click "Finish Editing".

**Expected Behavior:**

The Door should update without errors with a note "Overriden from DoorType".

or

The error should be printed: use DoorType to edit door parameters.

or

The DoorType should update.

or

The Parametric Geometry panel should be read-only.

**Actual Behavior:**

A RuntimeError is thrown with the message "Failed to process shape".

**System Information:**
```
- OS: Linux #117-Ubuntu SMP PREEMPT Tue Apr 30 10:12:40 UTC 2024
- Python version: 3.11.7
- Blender version: 4.1.1
- BlenderBIM version: 0.7.9.240629
```
Additional Information:

- The issue seems to be related to the geometry processing of the door after parameter changes.
- Can't switch to Plan Curve2D representation after the error.
- Changing DoorType works.

```
Traceback (most recent call last):
  File "[ADDON_PATH]/bim/ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[ADDON_PATH]/bim/module/model/door.py", line 610, in _execute
    update_door_modifier_representation(context, obj)
  File "[ADDON_PATH]/bim/module/model/door.py", line 98, in update_door_modifier_representation
    tool.Model.replace_object_ifc_representation(plan_body, obj, plan_representation)
  File "[ADDON_PATH]/tool/model.py", line 764, in replace_object_ifc_representation
    geometry.switch_representation(
  File "[ADDON_PATH]/core/geometry.py", line 143, in switch_representation
    new_repr_data = geometry.import_representation(obj, representation, apply_openings=apply_openings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[ADDON_PATH]/tool/geometry.py", line 570, in import_representation
    shape = ifcopenshell.geom.create_shape(settings, element, representation)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[ADDON_PATH]/libs/site/packages/ifcopenshell/geom/main.py", line 400, in create_shape
    ifcopenshell_wrapper.create_shape(
  File "[ADDON_PATH]/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 4749, in create_shape
    return _ifcopenshell_wrapper.create_shape(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to process shape
```

[project0-openings.zip](https://github.com/user-attachments/files/16045811/project0-openings.zip)

**Comment by Moult** [comment]
I can't seem to recreate this? Got any more detailed instructions?

**Comment by Gorgious56** [comment]
Can't reproduce either with this sequence of operations. However I get error messages when I setup incoherent values eg negative lengths for some parameters. eg negative Transom Thickness
```
ifcopenshell\api\geometry\add_window_representation.py", line 153, in window_l_shape_check
    x_offset < th for th, x_offset in zip(lining_thickness, lining_to_panel_offset_x, strict=True)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not iterable
```

I think ideally the fields should be restricted with an update callback or the "finish editing" button should be grayed out if the shape can't be processed, with an helpful tooltip

**Comment by theoryshaw** [comment]
I can't reproduce this. If this is still an issue please reopen.
