### ISSUE TITLE
Bug - Work Calendar editing

### ISSUE THREAD

**Issue by john-rogers** [IfcOpenShell/IfcOpenShell#4957]
Following Sigma Dimensions' BIM 4D Crash Course. Upon creating Work Calendar and editing name from 'Unnamed' to 8-5 (or other) errors as below when clicking Tick to update name.

```
os: Linux
os_version: #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03)
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: 
blender_version: 4.1.1
blenderbim_version: 0.7.9.240627
last_actions: 
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 7296, "Name": null}}
# operator: BIM_OT_save_project
# operator: BIM_OT_add_work_calendar
# ifcopenshell.api: sequence.add_work_calendar
>>> {}
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcWorkCalendar", "predefined_type": "NOTDEFINED", "name": "Unnamed"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: project.assign_declaration
>>> {"definitions": [{"cast_type": "entity_instance", "value": 7299, "Name": "Unnamed"}], "relating_context": {"cast_type": "entity_instance", "value": 195, "Name": "Prj_Name"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 7296, "Name": null}}
# operator: BIM_OT_edit_work_calendar
# ifcopenshell.api: sequence.edit_work_calendar
>>> {"work_calendar": {"cast_type": "entity_instance", "value": 7299, "Name": "Unnamed"}, "attributes": "{'GlobalId': '2F3ljZpRHEEPG9VlOscNWv', 'Name': '8-5', 'Description': None, 'ObjectType': None, 'Identification': None, 'PredefinedType': 'NOTDEFINED'}"}
last_error: Traceback (most recent call last):
  File "/home/jr/.config/blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jr/.config/blender/4.1/scripts/addons/blenderbim/bim/module/sequence/operator.py", line 591, in _execute
    core.edit_work_calendar(
  File "/home/jr/.config/blender/4.1/scripts/addons/blenderbim/core/sequence.py", line 323, in edit_work_calendar
    sequence.load_task_properties()
  File "/home/jr/.config/blender/4.1/scripts/addons/blenderbim/tool/sequence.py", line 195, in load_task_properties
    task = tool.Ifc.get().by_id(item.ifc_definition_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jr/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 445, in by_id
    return self[id]
           ~~~~^^^^
  File "/home/jr/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 430, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jr/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 6528, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #662 not found

ifc: B_29May_ifcOpenShellTest2-IFC4X3.ifc
schema: IFC4X3
preprocessor_version: IfcOpenShell 0.0.0
originating_system: BlenderBIM 0.7.9.240627-a98cddf
```

**Comment by Moult** [comment]
I can't seem to recreate this. Is this the first error you received or did you receive errors prior to this that could be the root cause? Can you recreate this on a blank file or a file that you can share? (dion@thinkmoult.com if private)

**Comment by john-rogers** [comment]
Update: As above, attempting to rename from Unnamed to 8-5 creates error and doesn't allow name change. Closing and re-opening ifc file/project, the name change has been made, and new name (8-5) appears on re-opening.

Trying to add a Recurrence Type of Weekly by clicking + icon doesn't work/activate. Closing out of Editing mode, and then re-entering Editing allows changes to be made.

**Comment by john-rogers** [comment]
> I can't seem to recreate this. Is this the first error you received or did you receive errors prior to this that could be the root cause? Can you recreate this on a blank file or a file that you can share? ([dion@thinkmoult.com](mailto:dion@thinkmoult.com) if private)

will try now

**Comment by Moult** [comment]
Are you by any chance opening and saving .blend files? Load and save .ifc instead :)

**Comment by john-rogers** [comment]
pure .ifc, no .blend.

Just tried on a blank, new file, and it worked no problem.

Attached is the file that caused the crashes. It's only a learning file, so I'm not trying to recover/restore/mend it, but if it throws up issues for you it may have value....No i'm not....How to upload a .ifc to github for you?

**Comment by Moult** [comment]
Just rename to .txt or zip it and then you can upload it.

**Comment by john-rogers** [comment]
[B_29May_ifcOpenShellTest2-IFC4X3.txt](https://github.com/user-attachments/files/16047178/B_29May_ifcOpenShellTest2-IFC4X3.txt)

**Comment by Moult** [comment]
Still no luck. There must be something related to the tasks in the task tree, but I can't work it out. If you can recreate it, can you perhaps join https://osarch.org/chat and if we're both online we can share screen to debug further?

**Comment by john-rogers** [comment]
sure, i'll keep on experimenting with it, and join the chat if anything useful happens. And I just want to say a sincere thank you for everything you've contributed, Dion, it truly is exceptional.

**Comment by Moult** [comment]
Cheers, I'll also extend the debug log from the last 10 operations to be 20 instead so in the future hopefully we have a few more clues.

**Comment by Moult** [comment]
Closing as I still cannot recreate the issue with the attached file and no further output. I'm a little confused too because the latest message says crash, not error.

The bug isn't actually to do with work calendar editing, it's that somehow the task tree doesn't match the reality in IFC (i.e. the UIList in Blender points to non-existent STEP IDs). My best guess right now is that SigmaDimension's crash course use coding to mass edit stuff - which can cause sync errors but isn't our issue.
