### ISSUE TITLE
Blender BIM - Error message when trying to generate Gannt Chart 

### ISSUE THREAD

**Issue by DimitriosThe** [IfcOpenShell/IfcOpenShell#4972]
After reading a csv file (see attached zip ) and generating the tasks using csv4d2ifc module, the resulting file (in attached zip file) is imported in Blender BIM, hwere the schedule is visible with all relations and subtasks generated succesfully.  Unfortunatelly after utilising the Generate Gannt function in BlenderBIM I get the following error.

Python: Traceback (most recent call last):
  File "C:\Users\dimitrios.theodorou\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\sequence.py", line 1543, in generate_gantt_browser_chart
    pystache.render(t.read(), {"json_data": task_b64, "data": json.dumps(work_schedule.get_info())})
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type entity_instance is not JSON serializable

Could some one cast some light in the issue?

thank you in advance
[Ifc4D_imported_files.zip](https://github.com/user-attachments/files/16085699/Ifc4D_imported_files.zip)

**Comment by DimitriosThe** [comment]
Issue seems to be resolved in Bonsai 0.8
