### ISSUE TITLE
Error trying to import a schedule of rates as a library file.

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#5000]
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.7.9.240708
last_actions: 
# ifcopenshell.api: control.assign_control
>>> {"related_object": {"cast_type": "entity_instance", "value": 14588, "Name": "Beam"}, "relating_control": {"cast_type": "entity_instance", "value": 15021, "Name": "Single Lintols"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 15412, "Name": null}}
# ifcopenshell.api: control.assign_control
>>> {"related_object": {"cast_type": "entity_instance", "value": 14275, "Name": "Beam"}, "relating_control": {"cast_type": "entity_instance", "value": 15021, "Name": "Single Lintols"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 15412, "Name": null}}
# ifcopenshell.api: control.assign_control
>>> {"related_object": {"cast_type": "entity_instance", "value": 13780, "Name": "Beam"}, "relating_control": {"cast_type": "entity_instance", "value": 15021, "Name": "Single Lintols"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 15412, "Name": null}}
# operator: BIM_OT_disable_editing_cost_schedule
# operator: BIM_OT_save_project
# operator: BIM_OT_append_library_element
# ifcopenshell.api: project.append_asset
>>> {"library": "<ifcopenshell.file.file object at 0x000002504ECE7FD0>", "element": {"cast_type": "entity_instance", "value": 34794, "Name": "Scheduale of Rates"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 443, in _execute
    element = ifcopenshell.api.run(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 92, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 252, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\project\append_asset.py", line 125, in append_asset
    return usecase.execute()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\project\append_asset.py", line 150, in execute
    return self.append_cost_schedule()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\project\append_asset.py", line 180, in append_cost_schedule
    return self.add_element(self.settings["element"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\project\append_asset.py", line 235, in add_element
    new = self.file.add(element)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 492, in add
    result = entity_instance(self.wrapped_data.add(inst.wrapped_data, -1 if _id is None else _id), self)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 8307, in add
    return _ifcopenshell_wrapper.file_add(self, entity, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unabled to add instance from IFC4 schema to file with IFC4X3_ADD2 schema

ifc: 1bd house-240708.ifc
schema: IFC4X3
preprocessor_version: IfcOpenShell 0.0.0
originating_system: BlenderBIM 0.7.9.240708-ff662fd
```
![Skermskoot (142)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/21e6280e-4029-4003-886d-578df36ff3a2)
[1bd house-240708.txt](https://github.com/user-attachments/files/16157309/1bd.house-240708.txt)
[HFCC-Chrech Toilet.txt](https://github.com/user-attachments/files/16157382/HFCC-Chrech.Toilet.txt)

Attached is the Ifc Project file (1bd…) and (Toilet…) I would like to use the schedule of rates created in the Ifc Project (Toilet...) in the (1bd) but got the attached error message.
Please advise what I am doing wrong.
Once again thanks for your time and effort

**Comment by Moult** [comment]
:tada: HAPPY BUG 4000! :tada:
