### ISSUE TITLE
Saving problem 

### ISSUE THREAD

**Issue by Abdul00000007** [IfcOpenShell/IfcOpenShell#5003]
```
os: Windows
os_version: 10.0.22631
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
blender_version: 3.6.5
blenderbim_version: 0.0.240602
last_actions: 
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}], "relating_object": {"cast_type": "entity_instance", "value": 36, "Name": "My Building"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 30, "Name": "My Site"}], "relating_object": {"cast_type": "entity_instance", "value": 1, "Name": "My Project"}}
# operator: BIM_OT_save_project
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 36, "Name": "My Building"}], "relating_object": {"cast_type": "entity_instance", "value": 30, "Name": "My Site"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}], "relating_object": {"cast_type": "entity_instance", "value": 36, "Name": "My Building"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 30, "Name": "My Site"}], "relating_object": {"cast_type": "entity_instance", "value": 1, "Name": "My Project"}}
# operator: BIM_OT_save_project
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 36, "Name": "My Building"}], "relating_object": {"cast_type": "entity_instance", "value": 30, "Name": "My Site"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}], "relating_object": {"cast_type": "entity_instance", "value": 36, "Name": "My Building"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 30, "Name": "My Site"}], "relating_object": {"cast_type": "entity_instance", "value": 1, "Name": "My Project"}}
last_error: Traceback (most recent call last):
  File "C:\Users\bingo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\bingo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\project\operator.py", line 1209, in _execute
    bpy.ops.wm.save_mainfile(filepath=bpy.data.filepath)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Unable to pack file, source path 'C:\BM' not found
Error: Unable to pack file, source path 'D:\SSD02\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\materialiq5_full\textures\mq_WD020_DECIDUOUS-Oak-Dark_Diffuse_2048.jpg' not found
Error: Unable to pack file, source path 'D:\SSD02\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\materialiq5_full\textures\mq_WD020_DECIDUOUS-Oak-Dark_Normal_2048.jpg' not found
Error: Unable to pack file, source path 'C:\RM' not found


ifc: IFC .ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: BlenderBIM 0.0.240602-47704b1
```

**Comment by Andrej730** [comment]
@Abdul00000007  ?

**Comment by Moult** [comment]
It seems he removed the error message, I edited it and added it back in.

**Comment by Andrej730** [comment]
I believe it's not a bug and just an issue with a specific .blend file - some assets paths seems to be missing and Blender fails to pack them into .blend file.
