### ISSUE TITLE
TriangulatedFaceSet fails to create_shape in 0.8.0

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5020]
It's this `3NyYVfZO18$xTZQxfZPKzq` element:

[wall.ifc.txt](https://github.com/user-attachments/files/16244027/wall.ifc.txt)

```python
import ifcopenshell
import ifcopenshell.geom
ifc_file = ifcopenshell.open('/home/dion/wall.ifc')

settings = ifcopenshell.geom.settings()
shape = ifcopenshell.geom.create_shape(settings, ifc_file.by_id(59)) #59=IFCWALL('3NyYVfZO18$xTZQxfZPKzq',#11,'CLT 90','Generic Exterior Wall - Thickness as Drawn','CLT 90',#53,#58,$,$);
# runtime error
print(shape.verts)
```

```
Traceback (most recent call last):
  File "/home/dion/Projects/ifcopenshell/src/test.py", line 16, in <module>
    shape = ifcopenshell.geom.create_shape(settings, ifc_file.by_id(59)) #59=IFCWALL('3NyYVfZO18$xTZQxfZPKzq',#11,'CLT 90','Generic Exterior Wall - Thickness as Drawn','CLT 90',#53,#58,$,$);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dion/Projects/env/lib/python3.11/site-packages/ifcopenshell/geom/main.py", line 409, in create_shape
    ifcopenshell_wrapper.create_shape(
  File "/home/dion/Projects/env/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 4276, in create_shape
    return _ifcopenshell_wrapper.create_shape(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to process shape
```

**Comment by aothms** [comment]
Thanks, some issues originated from the newly introduced mapping.
