### ISSUE TITLE
Lattest unstable build does not print drawing.

### ISSUE THREAD

**Issue by SavuGust27** [IfcOpenShell/IfcOpenShell#5024]
Blender BIM buid: v0.7.10 
Blender version: 4.1.1
Description of whats happening:
When adding a parametric door or window, either from the demo library or created by the user, it does not print.
Error:
Python: Traceback (most recent call last):
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 265, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 505, in generate_linework
    [cache.remove(guid) for guid in invalidated_guids]
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 505, in <listcomp>
    [cache.remove(guid) for guid in invalidated_guids]
     ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'remove'

If i try to create a drawing again, it still does not print

Error:
Python: Traceback (most recent call last):
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 265, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 562, in generate_linework
    self.serialiser.finalize()
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4823, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: An unknown error occurred

I tried to understand what is going on, so i went ahead added a cube, assign it as an IFC.Element and create a plan/Body/PLAN_VIEW and chose trace outline. It prints out. If i then go and edit the plan/Body/PLAN_VIEW of that cube, say extrude only one vertex, go out of edit mode, save it, and try to print, it does not work. Ok, seems to be that if you edit a plan/Body/PLAN_VIEW it currently does not work, but if i once again go into edit mode, move that one vertex back to its original place, and try to print, it works.

My guess is that since the door and window creates parametric plan/Body/PLAN_VIEW thats why they dont let you print if they are in the view.

Also if i bring an asset from the library, say a generic sofa, it does print, but if i go and edit the representation, then it does not print.

Walls and other IfcElements that do not have a plan/Body/PLAN_VIEW do print fine

**Comment by Moult** [comment]
Can you help supply a test file? This might already be fixed now.

**Comment by manuvarkey** [comment]
> Can you help supply a test file? This might already be fixed now.

Error is being shown with latest build also. 
```

Python: Traceback (most recent call last):
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/blenderbim/bim/module/drawing/operator.py", line 268, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/blenderbim/bim/module/drawing/operator.py", line 565, in generate_linework
    self.serialiser.finalize()
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 3574, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: An unknown error occurred


```



IFC file which used to generate drawings without issue using stable builds and now producing error is attached.

[Karayatta House.zip](https://github.com/user-attachments/files/16427025/Karayatta.House.zip)
