### ISSUE TITLE
Can not edit annotation that use curves

### ISSUE THREAD

**Issue by SavuGust27** [IfcOpenShell/IfcOpenShell#5025]
Blender 4.1 and 4.2
Blender BIM: v0.7.10
Description of error:
Add a annotation that uses blender curves, like a leader or dimensions, save it, then try to edit it again, and it does not let you enter edit mode to change it

Error:
```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD
blender_version: 4.2.0
blenderbim_version: 0.7.10
last_actions: 
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 126, "Name": null}}
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 29, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/DIMENSION\") at 0x000001A094B5A408>", "geometry": "<bpy_struct, Curve(\"29/371\") at 0x000001A0A3AA6E08>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 376, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 362, "Name": "DIMENSION"}, "representation": {"cast_type": "entity_instance", "value": 371, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 371, "Name": null}}
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
last_error: Traceback (most recent call last):
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\bim\ifc.py", line 384, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\bim\module\geometry\operator.py", line 1689, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\bim\module\geometry\operator.py", line 1575, in execute
    return IfcStore.execute_ifc_operator(self, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\bim\module\geometry\operator.py", line 1654, in _execute
    tool.Geometry.apply_item_ids_as_vertex_groups(obj)
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\tool\geometry.py", line 185, in apply_item_ids_as_vertex_groups
    assert isinstance(mesh, bpy.types.Mesh)
AssertionError

ifc: CRASH TEXT.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.0.0
originating_system: BlenderBIM 0.7.10
```

There is a way to enter edit mode. 
Go to top left corner where you can see IFC object mode, change it to IFC edit mode, click on discart changes and you will enter edit mode. Not sure if it is the intended way, since we where used to hitting tab to edit our objects. Also Shift+E also does not work

**Comment by BIMvoice** [comment]
On current v0.8.0 the 0.7.10 hard crash is already gone: curve annotations (dimensions, leaders) enter edit mode again via item mode (Tab enters item mode, Tab again edits the geometry). The remaining risk was that the swept-disk-solid crash fix (#4813) used a blanket "decline all curves" guard, which would have re-broken editing your annotations. I've reconciled them in #8355: the guard now declines only non-annotation curves, so swept disk solids decline gracefully while dimension/leader annotations stay editable. Could you confirm editing works via Tab -> Tab on a recent build?
