### ISSUE TITLE
Cannot enable the latest build blenderbim-0.7.10.240717

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5027]
Here is the modified text with "user" replacing all instances of the specific user:

```
Read prefs: "C:\user\AppData\Roaming\Blender Foundation\Blender\4.1\config\userpref.blend"
addon_utils.disable: blenderbim not loaded
addon_utils.disable: blenderbim not loaded
Modules Installed (blenderbim) from 'C:\\user\\Downloads\\blenderbim-0.7.10.240717-py311-win.zip' into 'C:\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons'
Exception in module register(): C:\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 176, in register
    import blenderbim.bim
  File "C:\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\__init__.py", line 96, in <module>
    modules[name] = importlib.import_module(f"blenderbim.bim.module.{name}")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\light\__init__.py", line 20, in <module>
    from . import ui, prop, operator
  File "C:\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\light\ui.py", line 20, in <module>
    from blenderbim.bim.module.light.data import SolarData
ModuleNotFoundError: No module named 'blenderbim.bim.module.light.data'

Exception in module register(): C:\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 176, in register
    import blenderbim.bim
  File "C:\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\__init__.py", line 96, in <module>
    modules[name] = importlib.import_module(f"blenderbim.bim.module.{name}")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\light\__init__.py", line 20, in <module>
    from . import ui, prop, operator
  File "C:\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\light\ui.py", line 20, in <module>
    from blenderbim.bim.module.light.data import SolarData
ModuleNotFoundError: No module named 'blenderbim.bim.module.light.data'
```

**Comment by BIMvoice** [comment]
Same is valid also for yesterday build.
