### ISSUE TITLE
IFC Error - cannot handle incorrect serialisation of backslash

### ISSUE THREAD

**Issue by big-arch** [IfcOpenShell/IfcOpenShell#5028]
```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240602
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\Артур\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 691, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Артур\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 771, in execute
    ifc_importer.execute()
  File "C:\Users\Артур\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 271, in execute
    self.parse_native_elements()
  File "C:\Users\Артур\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 484, in parse_native_elements
    if self.is_native(element):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Артур\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 490, in is_native
    not element.Representation
        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Артур\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 179, in __getattr__
    return entity_instance.wrap_value(self.wrapped_data.get_argument(idx), self.wrapped_data.file)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Артур\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 5240, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unexpected '1' at offset 1,981,464
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109


ifc: osceshenie.ifc
schema: IFC4X2
preprocessor_version: GeometryGymIFC v0.1.1.0 by Geometry Gym Pty Ltd built 2024-07-12T14:03:06
originating_system: RbPipes v16.0.46.2
```

**Comment by Andrej730** [comment]
@big-arch hello! can you please share .ifc file to reproduce the issue?

**Comment by big-arch** [comment]
hi, ok
https://drive.google.com/file/d/1I4jIivubhs59g4tv_-hTvPVOjREP2lv-/view?usp=sharing

**Comment by aothms** [comment]
cc @GeometryGym

It looks to me that there are indeed syntax errors in this file that unfortunately ifcopenshell cannot recover from.

>  Within a string, a single reverse solidus `"\"` shall be encoded as two reverse solidi `"\\"`.

http://www.steptools.com/stds/step/IS_final_p21e3.html

```
#5696= IFCPIPESEGMENT('0WX$hlOcD5r_8F8woSvfgG',$,'\X2\0422\X0\\X2\0440\X0\\X2\0443\X0\\X2\0431\X0\\X2\0430\X0\ \X2\0420\X0\\X2\042D\X0\\X2\0414\X0\\X2\041F\X0\\X2\0410\X0\\X2\0419\X0\\X2\041F\X0\ 160\X2\0445\X0\11,8 S 450 SN32 F2\108 \X2\0422\X0\\X2\0423\X0\ 22.21.21-001-53842199-2020 \X2\0413\X0\\X2\041E\X0\\X2\0421\X0\\X2\0422\X0\ \X2\0420\X0\ \X2\041C\X0\\X2\042D\X0\\X2\041A\X0\ 61386.24-2014',$,'b8392d26-2c79-41b4-a2f9-12887b2da02a',#1433,#5742,$,$);
                                                                                                                                                                                                                                     ^    
```

*(scroll to the right)*

**Comment by PhamKhai26391** [comment]
I also encountered a similar error. 
If you can fix it, please help me

**Comment by Moult** [comment]
I think we should close this as it's an invalid file error.
