### ISSUE TITLE
TypeError: attribute 'Dimensions' for entity 'IFC4.IfcSIUnit' is expecting value of type 'DERIVED', got 'entity_instance'.

### ISSUE THREAD

**Issue by Licini** [IfcOpenShell/IfcOpenShell#5029]
This error can be reproduced running below script:

```python
import ifcopenshell

file = ifcopenshell.file(schema="IFC4")

IfcDimensionalExponents = file.create_entity("IfcDimensionalExponents")
IfcSIUnit = file.create_entity("IfcSIUnit", Dimensions=IfcDimensionalExponents)

```
```bash
Traceback (most recent call last):
  File "/Users/lichen7/WORK/compas_ifc/temp/unit_test.py", line 6, in <module>
    IfcSIUnit = file.create_entity("IfcSIUnit", Dimensions=IfcDimensionalExponents)
  File "/Users/lichen7/opt/anaconda3/envs/compas-dev/lib/python3.10/site-packages/ifcopenshell/file.py", line 379, in create_entity
    e[idx] = arg
  File "/Users/lichen7/opt/anaconda3/envs/compas-dev/lib/python3.10/site-packages/ifcopenshell/entity_instance.py", line 354, in __setitem__
    raise TypeError(
TypeError: attribute 'Dimensions' for entity 'IFC4.IfcSIUnit' is expecting value of type 'DERIVED', got 'entity_instance'.
```

AFAIK, in IFC2x3 `Dimensions` used to be a derived attribute, but now it became a regular one in IFC4
https://standards.buildingsmart.org/MVD/RELEASE/IFC4/ADD2_TC1/RV1_2/HTML/

Kindly let me know what could be the reason, appreciated!

**Comment by Licini** [comment]
Also, is this indeed a bug, is there a way to temporarily force set an attribute to bypass the check?

**Comment by aothms** [comment]
That's the confusing thing about Express that it allows marking an attribute as derived **in a subtype** and that's exactly what the `*` in the file signifies. Normal derived attributes are never part of the exchange.
