### ISSUE TITLE
Erro code-used Shit-D "alot" and Blender Crash

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#5038]
![Skermskoot (146)](https://github.com/user-attachments/assets/ed301cb7-5a72-43b6-a4a2-7e3e4133fe89)
```
os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.7.10.240715
last_actions: 
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\model\product.py", line 395, in _execute
    if tool.Model.update_thumbnail_for_element(element):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\model.py", line 803, in update_thumbnail_for_element
    tool.Profile.draw_image_for_ifc_profile(draw, profile, size)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\profile.py", line 40, in draw_image_for_ifc_profile
    shape = ifcopenshell.geom.create_shape(settings, profile)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 410, in create_shape
    settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None, geometry_library
AttributeError: 'NoneType' object has no attribute 'wrapped_data'

ifc: New-Wall240716.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.0.0
originating_system: BlenderBIM 0.7.10.240717
```
[New-Wall240716.txt](https://github.com/user-attachments/files/16303020/New-Wall240716.txt)

And I still can't get IfcAssembly working to group Ifc Elements. 
When I try to copy the bottom course of the curved wall by using Shit-D, G Z-85, and then go to the properties panel change the type to 220x100 NFP brick and then go the Geometry and Materials to change the material to NFP-Clay, Blender crashes.

**Comment by Ave-5D** [comment]
![Skermskoot (147)](https://github.com/user-attachments/assets/c3392301-e57c-40d8-916f-24a158ceb8c1)
I tried to change the Type

**Comment by Ave-5D** [comment]
```
os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.7.10.240715
last_actions: 
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 188292, "Name": "ElementAssembly.044"}, "pset": {"cast_type": "entity_instance", "value": 188301, "Name": "EPset_Parametric"}}
# ifcopenshell.api: material.unassign_material
>>> {"products": [{"cast_type": "entity_instance", "value": 188292, "Name": "ElementAssembly.044"}]}
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\model\product.py", line 395, in _execute
    if tool.Model.update_thumbnail_for_element(element):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\model.py", line 803, in update_thumbnail_for_element
    tool.Profile.draw_image_for_ifc_profile(draw, profile, size)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\profile.py", line 40, in draw_image_for_ifc_profile
    shape = ifcopenshell.geom.create_shape(settings, profile)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 410, in create_shape
    settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None, geometry_library
AttributeError: 'NoneType' object has no attribute 'wrapped_data'

ifc: New-Wall240716.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.0.0
originating_system: BlenderBIM 0.7.10.240715-83085ba
```
![Ske![Skermskoot (149)](https://github.com/user-attachments/assets/0b9460d8-586c-4dc8-ae5b-ebb75d145932)rmskoot (148)](https://github.com/user-attachments/assets/33156042-804d-4541-ac96-3006f73574a6)
![Skermskoot (149)](https://github.com/user-attachments/assets/0b9460d8-586c-4dc8-ae5b-ebb75d145932)

**Comment by theoryshaw** [comment]
There might be more specific BB related reasons, but I think in general, vanilla Blender is not very good at handling a lot of individual objects.  So that might be part of the problem.  Not sure. 
Could you model this with similar objects, and use a 'brick texture'?  I know it not as much fun, but would help performance.

**Comment by Ave-5D** [comment]
Hi Ryan

 

Thanks for the feedback, I used the individual bricks due to a lack of knowledge and wanted to create/see a feature wall.

I think the problem started when I used the “paintbrush” icon to apply Styles to elements because the material-style for some reason did not change the element’s colour.

 

Once again thanks for all the support.

**Comment by Moult** [comment]
> I think the problem started when I used the “paintbrush” icon to apply Styles to elements because the material-style for some reason did not change the element’s colour.

Can you elaborate on this? What icon is this? What exactly are you doing?

**Comment by Ave-5D** [comment]
Hi Dion

Thanks for your interest, I can’t remember exactly what I did but I used this paintbrush.

I hope it helps.

 

You and your team are busy with a industry revelation stay strong.

 

Thanks
