### ISSUE TITLE
Standalone Section Shader

### ISSUE THREAD

**Issue by hansnolte** [IfcOpenShell/IfcOpenShell#5051]
Hi,
is there a current Standalone Section Shader for Blender 4.x or a comparable tool?

This one from here doesn't work anymore
https://github.com/IfcOpenShell/IfcOpenShell/pull/2172

WITH ONLY SELECTED:
`File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 309, in execute
    SectionCutawayManager.add_section_plane(context)
  File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 135, in add_section_plane
    cls.create_section_override_node(obj, context)
  File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 225, in create_section_override_node
    links.new(cut_obj.outputs["Object"], section_compare.inputs[1])
                                         ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 1 out of range, size 0
Error: Python: Traceback (most recent call last):
  File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 309, in execute
    SectionCutawayManager.add_section_plane(context)
  File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 135, in add_section_plane
    cls.create_section_override_node(obj, context)
  File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 225, in create_section_override_node
    links.new(cut_obj.outputs["Object"], section_compare.inputs[1])
                                         ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 1 out of range, size 0`


WITHOUT ONLY SELECTED:
`IndexError: bpy_prop_collection[index]: index 1 out of range, size 0
Traceback (most recent call last):
  File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 309, in execute
    SectionCutawayManager.add_section_plane(context)
  File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 132, in add_section_plane
    cls.append_obj_to_section_override_node(obj)
  File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 240, in append_obj_to_section_override_node
    last_section_node = next(
                        ^^^^^
  File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 245, in <genexpr>
    and not n.inputs[0].links
            ~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0
Error: Python: Traceback (most recent call last):
  File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 240, in append_obj_to_section_override_node
    last_section_node = next(
                        ^^^^^
  File "E:\Blender\portable\scripts\addons\standalone_section_shader.py", line 245, in <genexpr>
    and not n.inputs[0].links
            ~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0`

Best regards
Hans

**Comment by Moult** [comment]
These changes were fixed in the main add-on but never maintained in the standalone shader so it should be just a matter of spotting the differences and copying over the fixes. Would you be interested in tackling this?

**Comment by hansnolte** [comment]
Hi Moult,

many thanks for your answer.

> Would you be interested in tackling this?

Sorry, I am a No-Coder.
But I can try, maybe I'll have a fit of genius (pretty unlikely) or I'll find someone who can program in Python (more likely).
I have blenderbim-240602-py311-win. 
What is the name of the file?

Best regards
Hans

**Comment by Gorgious56** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/74141bec73a27cfb656fb479c410e433d3bd83af/src/blenderbim/blenderbim/bim/operator.py#L406-L715

You can copy/paste these two operators in the text editor and run it, then enable developer extras in the preferences and in the viewport type F3 then Add Temporary Section Cutaway

**Comment by hansnolte** [comment]
Hi Gorgious56,

many thanks for your help.

Unfortunately the script does not work and I get an error message in Blender 4.2 and 4.3.
`Python:   File "\Text", line 244
    class BIM_OT_remove_section_plane(bpy.types.Operator): 
                                                           ^
IndentationError: unindent does not match any outer indentation level`

Best regards
Hans

**Comment by sboddy** [comment]
Hi @hansnolte Unfortunately it looks like this issue got a bit lost. Is this still something you need resolved? The error in your comment is down to indentation issues. Python requires _consistent_ indentation for correct code structure. All indents must have the same number of characters. Unfortunately editors are not consistent, with some using spaces, and some using tabs for indents. Some make tabs = 2 spaces, some 4. It's a mess that catches a lot of newbies out. You just have to match your changes to the indentation in the file you are changing. So force your editor to use spaces, and set indentation amount to match the file, i.e. 4.

If this is no longer important to you, please let us know and we can close the issue.

**Comment by hansnolte** [comment]
HI sboddy,

it has resolved itself.

Thank you for the demand.
Hans
