### ISSUE TITLE
ifc2sql recipe error

### ISSUE THREAD

**Issue by ppaawweeuu** [IfcOpenShell/IfcOpenShell#5052]
I try to use ifc2sql recipe:

![image](https://github.com/user-attachments/assets/dc7a04dd-af6a-4026-85f9-c29af7e9595b)

it returns error:
```
Python: Traceback (most recent call last):
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\patch\operator.py", line 94, in execute
    output = ifcpatch.execute(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcpatch\__init__.py", line 84, in execute
    patcher.patch()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcpatch\recipes\Ifc2Sql.py", line 133, in patch
    self.create_geometry()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcpatch\recipes\Ifc2Sql.py", line 225, in create_geometry
    m = json.dumps([int(m.name.split("-")[2]) for m in shape.geometry.materials])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcpatch\recipes\Ifc2Sql.py", line 225, in <listcomp>
    m = json.dumps([int(m.name.split("-")[2]) for m in shape.geometry.materials])
                        ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

I can see it from 2024.07.14, first [blenderbim-0.7.10](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.10) version.
Last version working seems to be 20240605. After that version I see a lot basic problems with loading bbim or UI visibility, so It is hard to say if that problem was present.
I use Blender 4.1.1

**Comment by Andrej730** [comment]
Thanks for the bug report, fixed!

**Comment by Moult** [comment]
> After that version I see a lot basic problems with loading bbim or UI visibility

Can you please help report these? We're starting to see the light at the end of these big changes so it would be good to see whether or not it's just us or everybody is also seeing it become more stable.

**Comment by ppaawweeuu** [comment]
> Can you please help report these?

Sure
