### ISSUE TITLE
Georeferencing with 'map_conversion' throws an error. 'coordinate_operation' (not documented) works.

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#5055]
In the attached class I have tried to perform a georeferencing with IfcOpenShell 0.7.10. The script has worked well so far. After updating to IfcOpenShell 0.7.10, the execution fails with the following error message.

```
Traceback (most recent call last):
  File "/Users/kuba/dev/projects/BIM4BIPV-playground/venv/lib/python3.11/site-packages/ifcopenshell/api/__init__.py", line 252, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: edit_georeferencing() got an unexpected keyword argument 'map_conversion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kuba/dev/projects/BIM4BIPV-playground/tester.py", line 48, in <module>
    bipv_element_assembler = Tester()
                             ^^^^^^^^
  File "/Users/kuba/dev/projects/BIM4BIPV-playground/tester.py", line 13, in __init__
    self.create_basic_ifc_project()
  File "/Users/kuba/dev/projects/BIM4BIPV-playground/tester.py", line 26, in create_basic_ifc_project
    ifcopenshell.api.run("georeference.edit_georeferencing", self.model,
  File "/Users/kuba/dev/projects/BIM4BIPV-playground/venv/lib/python3.11/site-packages/ifcopenshell/api/__init__.py", line 92, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kuba/dev/projects/BIM4BIPV-playground/venv/lib/python3.11/site-packages/ifcopenshell/api/__init__.py", line 265, in wrapper
    raise TypeError(msg) from e
TypeError: Incorrect function arguments provided for georeference.edit_georeferencing
edit_georeferencing() got an unexpected keyword argument 'map_conversion'. You specified args (<ifcopenshell.file.file object at 0x105cb0bd0>,) and settings {'projected_crs': {'Name': 'EPSG:3857'}, 'map_conversion': {'Eastings': 1451690.100408, 'Northings': 6073520.703743, 'OrthogonalHeight': 423.7, 'XAxisAbscissa': 0.7071067811865476, 'XAxisOrdinate': -0.7071067811865475, 'Scale': 1.0}}

Correct signature is (file: ifcopenshell.file.file, coordinate_operation: Optional[dict[str, Any]] = None, projected_crs: Optional[dict[str, Any]] = None) -> None
See help(ifcopenshell.api.georeference.edit_georeferencing) for documentation.

```

I can fix the error by changing `map_conversion={ ... }` to `coordinate_operation={ ... }`.

Unfortunately, I can't see why this has to be the case. The documentation in `src/ifcopenshell-python/ifcopenshell/api/georeference/edit_georeferencing.py` requires the use of `map_conversion`.

Here is my code:

```python
import os
import math

import ifcopenshell
import ifcopenshell.api
import ifcopenshell.util.placement


class Tester:

    def __init__(self):
        self.model = None
        self.create_basic_ifc_project()

    def create_basic_ifc_project(self):
        # create an empty model
        self.model = ifcopenshell.api.run("project.create_file")

        # create a project in it
        project = ifcopenshell.api.run("root.create_entity", self.model, ifc_class="IfcProject", name="My Project")

        # add Georeferencing through IfcProjectedCRS and IfcMapConversion entities
        # https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcProjectedCRS.htm
        # https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcMapConversion.htm
        ifcopenshell.api.run("georeference.add_georeferencing", self.model)
        ifcopenshell.api.run("georeference.edit_georeferencing", self.model,
                             projected_crs={"Name": "EPSG:3857"}, # aka WSG 84
                             map_conversion={
                                 "Eastings": 1451690.100408,
                                 "Northings": 6073520.703743,
                                 "OrthogonalHeight": 423.70,
                                 # the angle difference between project north and grid north.
                                 "XAxisAbscissa": math.cos(math.radians(-45)),
                                 "XAxisOrdinate": math.sin(math.radians(-45)),
                                 "Scale": 1.0
                             })


    def save_ifc_project(self, target_model_path):
        # save model as STP file
        self.model.write(target_model_path)


print("Current working dir: " + os.getcwd())
print("IfcOpenShell " + ifcopenshell.version)

tester = Tester()

```

**Comment by Moult** [comment]
The docs need updating. The name was changed to support ifc4x3 :) PR welcome
