### ISSUE TITLE
Python version issue

### ISSUE THREAD

**Issue by EdgarWesterhoven** [IfcOpenShell/IfcOpenShell#5076]
Just reinstalled Blender, and grabbed the latest blender bim addon that corresponds with my version of python. But get a version issue when installing in blender.

![image](https://github.com/user-attachments/assets/4616765e-54df-4053-9ed3-ba7170d7b48c)

**Comment by theoryshaw** [comment]
https://docs.blenderbim.org/devs/installation.html#unstable-installation

try and install `blenderbim_py311...` for Blender 4.2

**Comment by Moult** [comment]
Yep as described in the error message in your screenshot, you downloaded the wrong version. You probably downloaded the one with py310 instead of py311. Note the error message warning that you need to DISABLE, not uninstall to fix this once you've downloaded the right one.

Alternatively if you're unsure, download https://github.com/IfcOpenShell/IfcOpenShell/releases/download/blenderbim-0.7.11-alpha240724/blenderbim_py311-0.7.11-alpha240724-windows-x64.zip and then in your %appdata%/Blender Foundation/Blender/ rename your 4.2 folder to something else to make sure you have a clean install.

**Comment by EdgarWesterhoven** [comment]
Ok, I disabled and subsequently removed the package from "AppData\Roaming\Blender Foundation\Blender\4.2\extensions" on my HDD. Tried installing "blenderbim_py311-0.7.11-alpha240724-windows-x64.zip". But as I expected this gives an error about a version difference. 

------------------------------------------

os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
blender_version: 4.2.0
blenderbim_version: 0.7.11-alpha240724
blenderbim_commit_hash: 8b29e50
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\xxxxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ifcopenshell._ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\__init__.py", line 81, in <module>
    from . import ifcopenshell_wrapper
  File "C:\Users\xxxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 17, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_ifcopenshell_wrapper')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\__init__.py", line 226, in <module>
    import ifcopenshell.api
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\__init__.py", line 83, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.11'

binary_file_name: _ifcopenshell_wrapper.cp310-win_amd64.pyd
binary_python_version: 3.10

**Comment by EdgarWesterhoven** [comment]
Ok you can close it. 

I still do not understand why I am installing a P11 package when my system is on P10. Does the package come with it's own Python? 

Thanks for the help!!
