### ISSUE TITLE
Missing profiles for IfcMaterialProfiles

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#5101]
```
os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.7.10.240715
last_actions: 
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\model\product.py", line 395, in _execute
    if tool.Model.update_thumbnail_for_element(element):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\model.py", line 803, in update_thumbnail_for_element
    tool.Profile.draw_image_for_ifc_profile(draw, profile, size)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\profile.py", line 40, in draw_image_for_ifc_profile
    shape = ifcopenshell.geom.create_shape(settings, profile)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 410, in create_shape
    settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None, geometry_library
AttributeError: 'NoneType' object has no attribute 'wrapped_data'

ifc: AMPC-Wall 240724-low.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.0.0
originating_system: BlenderBIM 0.7.10.240715-83085ba
```
Attached is the text file, I tried to activate today’s build for Blender 4.1 but nothing happens.
I am finding it difficult to add a second circular base and get this error code.
I hope this is useful information
Kind regards
Big thanks in advance.
[AMPC-Wall 240724-low.txt](https://github.com/user-attachments/files/16417555/AMPC-Wall.240724-low.txt)

**Comment by Ave-5D** [comment]
The error happen when I select "Create Element" and click on a IfcSlab Type, as per the attached screen shot.
![Skermskoot (177)](https://github.com/user-attachments/assets/41c87193-c8a8-4084-97de-6f82d7d9d63e)

Thanks in advance

**Comment by Andrej730** [comment]
I added more restrictions to profile removal from UI in 1c7e7c5, so user won't make invalid IFC by removing profile and corrupting related material profiles or representations.
