### ISSUE TITLE
Add selected objects to the open model

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5110]
Hey guys,

Would be possible to build a feature where we can copy objects from a linked model into the open/loaded model?

There are situations when you want to do that for some reason. Any chance this is not very complicated to implement?

**Comment by BIMvoice** [comment]
I think actually using types from other models does most of this, so maybe not so relevant. Would love to hear some other opinions though.

**Comment by Andrej730** [comment]
> Would be possible to build a feature where we can copy objects from a linked model into the open/loaded model?

Isn't this already implemented (in Links section when you select some element from the linked model)?
![image](https://github.com/user-attachments/assets/6ea06577-cbd0-4d89-9bd5-a735b9dd772e)

**Comment by steverugi** [comment]
Hi @Andrej730  yes, but only one element at the time, correct?

**Comment by Andrej730** [comment]
> Hi @Andrej730 yes, but only one element at the time, correct?

Yes, since there is no multiselection for objects in the linked model.

**Comment by BIMvoice** [comment]
Does this work only for types (IfcElementType) or also for IfcElement?

**Comment by Andrej730** [comment]
> Does this work only for types (IfcElementType) or also for IfcElement?

It works only for IfcElements - you can't see the types from the linked model.

**Comment by BIMvoice** [comment]
> > Would be possible to build a feature where we can copy objects from a linked model into the open/loaded model?
> 
> Isn't this already implemented (in Links section when you select some element from the linked model)? ![image](https://private-user-images.githubusercontent.com/9417531/353731054-6ea06577-cbd0-4d89-9bd5-a735b9dd772e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1Nzc1ODYsIm5iZiI6MTcyMjU3NzI4NiwicGF0aCI6Ii85NDE3NTMxLzM1MzczMTA1NC02ZWEwNjU3Ny1jYmQwLTRkODktOWJkNS1hNzM1YjlkZDc3MmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDU0MTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFiODUzZmI5NGI0NTA2MDRlOGUxYjQ3NTFkNjRmMWEyZTE3ZDZhOGY2N2RmOGYwZGMzNWMyMGIzOWJjN2M3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0AuaQaeKRCPtWj4hMg8SUCMpp3OrB1U1qB7y7dR88R4)

I have some problems with this:

When I select any elements in the linked models (I tried more) more elements are selected. Then they don't show up as IFC elements... I tried to click on individual chunks, still the same.

![image](https://github.com/user-attachments/assets/2a7a659e-a66b-489f-8c66-c2016a7f5f14)

**Comment by Andrej730** [comment]
> When I select any elements in the linked models (I tried more) more elements are selected. Then they don't show up as IFC elements... I tried to click on individual chunks, still the same.

To operate on linked model use "Explore Tool" and "RMB" to query objects, then you'll be able to append queries objects.

**Comment by BIMvoice** [comment]
> > When I select any elements in the linked models (I tried more) more elements are selected. Then they don't show up as IFC elements... I tried to click on individual chunks, still the same.
> 
> To operate on linked model use "Explore Tool" and "RMB" to query objects, then you'll be able to append queries objects.

this is amazing, how come I did not hear about this earlier? :(

Problem is I got an error when I tried to bring in the pole highlighted in green.

I use Blender 4.2 with daily BBIM build from yesterday.

````
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 154 Stepping 4, GenuineIntel
blender_version: 4.2.0
blenderbim_version: 0.7.11-alpha240801
blenderbim_commit_hash: 788217c
last_actions: 
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_append_inspected_linked_element
# ifcopenshell.api: project.append_asset
>>> {"library": "<ifcopenshell.file.file object at 0x0000020FBCC9F810>", "element": {"cast_type": "entity_instance", "value": 297932, "Name": "UPH.002"}}
# operator: BIM_OT_append_inspected_linked_element
# ifcopenshell.api: project.append_asset
>>> {"library": "<ifcopenshell.file.file object at 0x0000020FBCC71910>", "element": {"cast_type": "entity_instance", "value": 298665, "Name": "UPH.003"}}
last_error: Traceback (most recent call last):
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\project\operator.py", line 1877, in _execute
    obj = tool.Ifc.get_object(element_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peco01\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\tool\ifc.py", line 115, in get_object
    return IfcStore.get_element(element.id())
                                ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

ifc: 12345_123456_1234567_RIB_0_0.ifc
schema: IFC4
preprocessor_version: The EXPRESS Data Manager Version 5.02.0100.07 : 28 Aug 2013
originating_system: 21.1.50.27 - Exporter 21.2.1.0 - Alternate UI 21.2.1.0
````
![image](https://github.com/user-attachments/assets/13b66f81-74c0-4678-90af-f59bf3403567)

**Comment by BIMvoice** [comment]
After @Moult commit it works! Thank you very much guys, you are all AMAZING!

**Comment by steverugi** [comment]
> > When I select any elements in the linked models (I tried more) more elements are selected. Then they don't show up as IFC elements... I tried to click on individual chunks, still the same.
> 
> To operate on linked model use "Explore Tool" and "RMB" to query objects, then you'll be able to append queries objects.

![image](https://github.com/user-attachments/assets/1e10dee2-1920-4689-a84c-eca0604f6419)

cool but in my simple case the wall is appended based on its own origin, did I do something wrong?

**Comment by steverugi** [comment]
> Potentially a bug? Can share the model?
Hi @Moult 
[dummystation.txt](https://github.com/user-attachments/files/16466787/dummystation.txt)
[dummyyard.txt](https://github.com/user-attachments/files/16466788/dummyyard.txt)
thanks

**Comment by BIMvoice** [comment]
I'm sad to report that this is not working again.

I get this error when I right click on an object while using the Explore Tool:

`Python: Traceback (most recent call last):
  File "/Users/petru/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/blenderbim/bim/module/project/operator.py", line 1845, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petru/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/blenderbim/bim/module/project/operator.py", line 1785, in execute
    self.db = sqlite3.connect(obj["db"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
`

I'm on a mac M1.

@Moult have any idea what happened? It was working fine yesterday, but on windows. I'm using the latest 3rd of August version.

**Comment by Moult** [comment]
@BIMvoice potentially you have deleted your .db file. Try relinking again with cache disabled. Your should see a .cache.blend, a .cache.json, and a .cache.db next to your .ifc file.

**Comment by BIMvoice** [comment]
> @BIMvoice potentially you have deleted your .db file. Try relinking again with cache disabled. Your should see a .cache.blend, a .cache.json, and a .cache.db next to your .ifc file.

You are right, all I had to do was to uncheck use cache and it work as expected. Thank you very much!

**Comment by Moult** [comment]
Reopening because we still need to investigate the wrong placement issue from @steverugi
