### ISSUE TITLE
Error when activating and running a drawing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5112]
file: https://hub.openingdesign.com/OpeningDesign/Restaurant_MPM/src/commit/bf4b15b787c3372d7174d6ca3b92a5f0d23040c3/Open/Models/BlenderBIM/Restaurant_MPM.ifc

When I activate `FLOOR PLAN - 1ST FLOOR`, get the following error...
```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\drawing\operator.py", line 1528, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\drawing\operator.py", line 1549, in execute
    core.sync_references(tool.Ifc, tool.Collector, tool.Drawing, drawing=tool.Ifc.get().by_id(self.drawing))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\core\drawing.py", line 461, in sync_references
    annotation = drawing_tool.generate_reference_annotation(drawing, reference_element, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\tool\drawing.py", line 1175, in generate_reference_annotation
    ensure_referenced_drawing_obj_exists(reference_element)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\tool\drawing.py", line 1167, in ensure_referenced_drawing_obj_exists
    cls.import_annotations_in_group(cls.get_drawing_group(drawing))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\tool\drawing.py", line 666, in import_annotations_in_group
    tool.Collector.assign(obj)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\tool\collector.py", line 89, in assign
    cls.link_to_collection_safe(obj, drawing_obj.BIMObjectProperties.collection)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\tool\collector.py", line 130, in link_to_collection_safe
    if collection.objects.find(obj_or_col.name) != -1:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'objects'


```

When i try and run the drawing, i get...

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\drawing\operator.py", line 268, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\drawing\operator.py", line 565, in generate_linework
    self.serialiser.finalize()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4828, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: An unknown error occurred

```

blenderbim_py311-0.7.11-alpha240731-windows-x64

**Comment by theoryshaw** [comment]
might be related to #5136 & #4924

**Comment by theoryshaw** [comment]
Fixed as of https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/bonsai-0.7.11-alpha240829 !
