### ISSUE TITLE
Error when opening file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5113]
Error when trying to open the following file:
https://hub.openingdesign.com/OpeningDesign/Rae_Living_Room_Ext/src/commit/06ae2f09ecb9d7d008cc6f7d6908e1a186405f48/Open/Models/BlenderBIM/Rae_Living_Room_Ext.ifc

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.2.0
blenderbim_version: 0.7.11-alpha240731
blenderbim_commit_hash: 6cb063e
last_actions: 
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
last_error: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\project\operator.py", line 745, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\project\operator.py", line 824, in execute
    ifc_importer.execute()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\import_ifc.py", line 244, in execute
    self.create_elements()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\import_ifc.py", line 630, in create_elements
    self.create_generic_elements(self.elements)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\import_ifc.py", line 646, in create_generic_elements
    products = self.create_products(elements, settings=settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\import_ifc.py", line 725, in create_products
    valid_file = iterator.initialize()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 2141, in initialize
    return _ifcopenshell_wrapper.Iterator_initialize(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unexpected topology
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: Rae_Living_Room_Ext_old.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: BlenderBIM 0.0.240605-cfd0ed6
```

**Comment by Moult** [comment]
There's a number of invalid things with this file, such as duplicate GlobalIds, multiple unit assignments, probably due to older versions of the BlenderBIM Add-on having glitches on appending and copying from other projects which we've since improved a lot on.

That said the actual thing causing the runtime error seems to be this line:

```
#2890502=IFCAXIS2PLACEMENT3D($,$,$);
```

Which is basically invalid, which you can fix by replacing with:

```
#2890502=IFCAXIS2PLACEMENT3D(#2927463,#2927464,#2927465);
```

However although it's invalid, it's interesting that it didn't have this runtime error in v0.7.0.

@aothms is this something you'd want to accommodate or should we just leave this as "this is invalid, user must fix"?

**Comment by Moult** [comment]
@theoryshaw here's your model cleaned up somewhat with the fix and duplicate GlobalIds removed: https://0x0.st/XViq.ifc.txt

**Comment by theoryshaw** [comment]
Thank you. :)

**Comment by aothms** [comment]
> @aothms is this something you'd want to accommodate or should we just leave this as "this is invalid, user must fix"?

I don't have strong opinions on this one. Ideally I guess we should just skip over the invalid placement instead of bailing out altogether. Let's keep the issue open. But won't be fixed for next week I guess.

**Comment by Andrej730** [comment]
But skipping them without knowing where they came from can hide the underlying issues (in Bonsai or other software that produced them) and lead to other harder to debug errors later on. So, I'd say may be it is okay to have this kind of issues loading invalid IFC.

**Comment by BIMvoice** [comment]
On current 0.8.x this file's exact trigger, `IFCAXIS2PLACEMENT3D($,$,$)`, no longer crashes. It now loads cleanly through the geometry iterator and `util.placement`, returning an identity placement, so the C++ kernel already tolerates the fully-null case that failed on 0.7.0.

While reproducing this I found a related null-placement case that still throws an opaque `TypeError` in `ifcopenshell.util.placement.get_axis2placement`: when `Axis` or `RefDirection` exists but its `DirectionRatios` is null. #8359 falls back to the schema default axes there, matching how a missing `Axis`/`RefDirection` is already handled. Happy to close this issue if the kernel behaviour is considered sufficient for the original case.
