### ISSUE TITLE
Blender 4.2 problem with installation BlenderBim 0.7.11-alpha240801

### ISSUE THREAD

**Issue by hydromac** [IfcOpenShell/IfcOpenShell#5119]
At the first time I installed BlenderBim version for Python 3.12, but after error I disabled them, uninstalled and installed for Python 3.11.  It's not helped I have still the same error as below. 

os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
blender_version: 4.2.0
blenderbim_version: 0.7.11-alpha240801
blenderbim_commit_hash: 6f6dc08
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\hydro\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ifcopenshell._ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hydro\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\__init__.py", line 81, in <module>
    from . import ifcopenshell_wrapper
  File "C:\Users\hydro\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 17, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hydro\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_ifcopenshell_wrapper')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hydro\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\__init__.py", line 226, in <module>
    import ifcopenshell.api
  File "C:\Users\hydro\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\__init__.py", line 83, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.11'

binary_file_name: _ifcopenshell_wrapper.cp312-win_amd64.pyd
binary_python_version: 3.12

![image](https://github.com/user-attachments/assets/89baa747-15a4-482f-a6e0-affb44b28e59)

**Comment by Moult** [comment]
Unfortunately once you install with the wrong python version, you are a little bit stuck and have to do a manual clean prior to reinstalling with the correct python version.

The easiest way to do this is to rename or delete `C:\Users\hydro\AppData\Roaming\Blender Foundation\Blender\4.2\` to start off with a fresh config.
