### ISSUE TITLE
[IfcPatchRecipe: ExtractElements] RuntimeError: NOTDEFINED does not name a valid item for IfcElementCompositionEnum

### ISSUE THREAD

**Issue by PahlawanJoey** [IfcOpenShell/IfcOpenShell#5125]
```
Traceback (most recent call last):
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\Objecten_Achterlaten 0.3_GAMMA_AR.py", line 60, in <module>
    ifc = ifcpatch.execute({
          ^^^^^^^^^^^^^^^^^^
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcpatch\__init__.py", line 85, in execute
    patcher.patch()
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcpatch\recipes\ExtractElements.py", line 67, in patch
    self.add_element(element)
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcpatch\recipes\ExtractElements.py", line 72, in add_element
    new_element = self.append_asset(element)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcpatch\recipes\ExtractElements.py", line 85, in append_asset
    return ifcopenshell.api.run(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcopenshell\api\__init__.py", line 92, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcopenshell\api\__init__.py", line 252, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcopenshell\api\project\append_asset.py", line 125, in append_asset
    return usecase.execute()
           ^^^^^^^^^^^^^^^^^
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcopenshell\api\project\append_asset.py", line 144, in execute
    return self.append_product()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcopenshell\api\project\append_asset.py", line 206, in append_product
    element = self.add_element(self.settings["element"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcopenshell\api\project\append_asset.py", line 235, in add_element
    new = self.file.add(element)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcopenshell\file.py", line 492, in add
    result = entity_instance(self.wrapped_data.add(inst.wrapped_data, -1 if _id is None else _id), self)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\PycharmProjects\Edit_IFC 3.12.2\venv\Lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 8312, in add
    return _ifcopenshell_wrapper.file_add(self, entity, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: NOTDEFINED does not name a valid item for IfcElementCompositionEnum
```

[Here's a link to the model](https://acc.autodesk.com/docs/share/projects/642e5b57-e9e6-482a-8028-7ce623c22982/files?shareId=82e0d330-a1ef-41a3-8e9d-bd7d941168cf) used with the patch recipe ExtactElements.
All packages in Python used are from the latest build: blenderbim-0.7.11-alpha240802 (unstable)

**Comment by aothms** [comment]
My guess is that when you run `python -m ifcopenshell.validate` on the model you'll get the same error. In other words it's an issue in the source model and when extracting that particular element it trips over the invalid enumeration. Maybe there should be an option to just try catch these kind of errors.

**Comment by Andrej730** [comment]
Indeed, all 2806 IfcBuildingElementProxies in this model have invalid value "NOTDEFINED" in attribute "CompositionType" therefore there is an issue when ifcpatch is trying to recreate this element with invalid value. This attribute is optional and you can set it to `None` instead to keep IFC valid.

**Comment by Andrej730** [comment]
Closing as this is a problem with the original ifc file.
