### ISSUE TITLE
error setting a property in quantity set

### ISSUE THREAD

**Issue by dapenamr** [IfcOpenShell/IfcOpenShell#5126]
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: AMD64 Family 23 Model 49 Stepping 0, AuthenticAMD
blender_version: 4.1.0
blenderbim_version: 0.0.240602
last_actions: 
# operator: BIM_OT_remove_pset
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 4673, "Name": "Bohrpfahl:Bohrpfahl:6085434"}, "pset": {"cast_type": "entity_instance", "value": 1181557, "Name": "My_Qto_Gross_Lenght"}}
# operator: BIM_OT_remove_pset
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 4673, "Name": "Bohrpfahl:Bohrpfahl:6085434"}, "pset": {"cast_type": "entity_instance", "value": 1181532, "Name": "My_Qto"}}
# operator: BIM_OT_add_qto
# operator: BIM_OT_copy_property_to_selection
# ifcopenshell.api: pset.add_qto
>>> {"product": {"cast_type": "entity_instance", "value": 4673, "Name": "Bohrpfahl:Bohrpfahl:6085434"}, "name": "My_Data_Test"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: pset.edit_qto
>>> {"qto": {"cast_type": "entity_instance", "value": 1181572, "Name": "My_Data_Test"}, "properties": "{'Length': 'Some Value'}"}
last_error: Traceback (most recent call last):
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 342, in __setitem__
    self.method_list[idx](self.wrapped_data, idx, entity_instance.unwrap_value(value))
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 5305, in setArgumentAsDouble
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsDouble(self, i, v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: in method 'entity_instance_setArgumentAsDouble', argument 3 of type 'double'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\pset\operator.py", line 237, in _execute
    core.copy_property_to_selection(
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\core\pset.py", line 30, in copy_property_to_selection
    ifc.run("pset.edit_qto", qto=ifc_pset, properties={prop_name: prop_value})
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\ifc.py", line 34, in run
    return ifcopenshell.api.run(command, IfcStore.get_file(), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 184, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 350, in wrapper
    raise e
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 344, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\pset\edit_qto.py", line 120, in edit_qto
    return usecase.execute()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\pset\edit_qto.py", line 132, in execute
    new_properties = self.add_new_properties()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\pset\edit_qto.py", line 171, in add_new_properties
    self.file.create_entity(
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 353, in create_entity
    e[idx] = arg
    ~^^^^^
  File "C:\Users\mriverodapen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 344, in __setitem__
    raise TypeError(
TypeError: attribute 'LengthValue' for entity 'IFC2X3.IfcQuantityLength' is expecting value of type 'DOUBLE', got 'str'.

ifc: 2408_Tunnel_Bremen_A281_2418+2419-Regelblock_BW2419.ifc
schema: IFC2X3
preprocessor_version: ODA SDAI 24.6
originating_system: Autodesk Revit 24.2.10.64 (DEU) - IFC 24.2.10.64
```

**Comment by Andrej730** [comment]
Hello1 Can you please share example to reproduce the issue?

**Comment by dapenamr** [comment]
[Sample-Issue_001.zip](https://github.com/user-attachments/files/16469648/Sample-Issue_001.zip)

Hello, sure.

**Comment by dapenamr** [comment]
1. I opened the model in Blender (Sample-Issue_001.zip)

3. I tried to follow the steps from this video (https://youtu.be/I3QuxuNdEVQ)

4. I clicked on an element and pressed several buttons in the following view.

![image](https://github.com/user-attachments/assets/a94522b6-0058-4734-b2a4-b15fde989f74)



5. The error occurred, and Blender closed.

**Comment by Andrej730** [comment]
@dapenamr 

> 5\. The error occurred, and Blender closed.

This issue crashed Blender?

Couldn't reproduce the problem in current BBIM version. Can you please try the to update BBIM and try again (note that it will require Blender 4.2)?

**Comment by dapenamr** [comment]
Yes, Blender crashed.

Ok, I'm going to update BBIM and Blender too.

Thank you for your time and quick response.

**Comment by Andrej730** [comment]
@dapenamr hi! is this issue still relevant?

**Comment by dapenamr** [comment]
Hi @Andrej730 , 
Although I installed Blender version 4.2, I haven't been able to test the IFC file in question again. It's better if you close the Issue, and if I encounter that issue again when testing, I will report it.
