### ISSUE TITLE
Error removing ifc elements

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#5128]
```
os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.7.10.240715
last_actions: 
# ifcopenshell.api: root.remove_product
>>> {"product": {"cast_type": "entity_instance", "value": 3508, "Name": "BuildingElementProxy"}}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 3508, "Name": "BuildingElementProxy"}, "representation": {"cast_type": "entity_instance", "value": 3520, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 3520, "Name": null}}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 3508, "Name": "BuildingElementProxy"}, "representation": {"cast_type": "entity_instance", "value": 3523, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 3523, "Name": null}}
# ifcopenshell.api: material.unassign_material
>>> {"products": [{"cast_type": "entity_instance", "value": 3508, "Name": "BuildingElementProxy"}]}
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 3508, "Name": "BuildingElementProxy"}, "pset": {"cast_type": "entity_instance", "value": 3517, "Name": "EPset_Parametric"}}
# ifcopenshell.api: type.unassign_type
>>> {"related_objects": [{"cast_type": "entity_instance", "value": 3508, "Name": "BuildingElementProxy"}]}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 85, "Name": null}}
# ifcopenshell.api: root.remove_product
>>> {"product": {"cast_type": "entity_instance", "value": 379, "Name": "My Site"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 757, in _execute
    tool.Geometry.delete_ifc_object(obj)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\geometry.py", line 128, in delete_ifc_object
    parent_collection.objects.link(child_object)
RuntimeError: Error: Object 'IfcSite/My Site.010' already in collection 'IfcProject/My Project'


ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell 0.0.0
originating_system: IfcOpenShell 0.0.0
```
Attached is the IFC file giving the error code, I wanted to delete all the elements and got this error code. I know it would straight forward just to start a new IFC Project but thought this error code might be of some value.
I imported the Type from another IFC project.

Once again thanks for your efforts.
[Statue base 240802.txt](https://github.com/user-attachments/files/16469612/Statue.base.240802.txt)

**Comment by Andrej730** [comment]
@Ave-5D 

How do I reproduce this?

This is what I tried and couldn't reproduce the issue (was testing on 240802 though):
1) Load project
2) Press "A" to select all elements
3) Press "X" and "OK"

**Comment by Ave-5D** [comment]
Hi Andrej

 

I highlighted all the elements and groupings in the “Scene Collection” panel and then pressed “X”, will try and get 240802 working.

 

Thanks for your time and effort.

 

Kind regards

Roel

**Comment by Andrej730** [comment]
@Ave-5D hi! Is this issue still relevant?

**Comment by Ave-5D** [comment]
Hi Andre, sorry I did not close it will do now
