### ISSUE TITLE
Enabling BBIM - ImportError: IfcOpenShell not built for 'windows\64bit\python3.10'

### ISSUE THREAD

**Issue by mzxprod** [IfcOpenShell/IfcOpenShell#5146]
```
os: Windows
os_version: 10.0.22621
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.0.240602
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _ifcopenshell_wrapper: Le module spécifié est introuvable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 81, in <module>
    from . import ifcopenshell_wrapper
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 17, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_ifcopenshell_wrapper')
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\__init__.py", line 96, in <module>
    import blenderbim.bim
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\handler.py", line 23, in <module>
    import ifcopenshell.api.owner.settings
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 83, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.10'
```

**Comment by Moult** [comment]
You'll need to install that version on Blender 4.1. We used to support older versions but we've recently dropped support due to big changes in Blender 4.2. In the next release at the end of this month we will only support Blender 4.2 and up.

**Comment by Andrej730** [comment]
Or you can download from here https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-240602 BBIM 0.0.240602 with python 3.10 that will be possible to run on Blender 4.0.

**Comment by Andrej730** [comment]
@mzxprod closing this for now, feel free to reopen if issue is not resolved for you.
