### ISSUE TITLE
Bugg BlenderBim | IFC Diff object has no attribute 'set_context_ids'

### ISSUE THREAD

**Issue by olemariussvendsen** [IfcOpenShell/IfcOpenShell#5156]
IFC files used:
https://we.tl/t-yCQtCekEBY

Using windows 10, blender 4.2, with py311-0.7.11-alpha240806-windows-x64.zip](http://py311-0.7.11-alpha240806-windows-x64.zip

The error code:

```
Starting import process :: 0.00
Loading file :: 0.00
Calculate unit scale :: 0.00
Process context filter :: 0.00
Calculate model offset :: 0.02
Predict dense mesh :: 0.09
Set units :: 0.00
Create project :: 0.01
Warning! Excessive voids were found and skipped for the following elements:
#117745=IfcWallStandardCase('0xEfFNHp1CmOfjFY1gBlYt',#18,'Basic Wall:318 - klimavegg:32164848',$,'Basic Wall:318 - klimavegg',#117701,#117744,'32164848')
#1032=IfcWallStandardCase('1sKdZm2bjApuBmrG95FZXJ',#18,'Basic Wall:318 - klimavegg:3934980',$,'Basic Wall:318 - klimavegg',#1020,#1031,'3934980')
Process element filter :: 0.09
Create styles :: 0.03
Parsing native elements :: 2.45
Done creating geometry
Create native elements :: 0.00
250 / 6113 (4% created, 6% preprocessed) elements processed in 0.53s ...
500 / 6113 (8% created, 12% preprocessed) elements processed in 0.11s ...
750 / 6113 (12% created, 18% preprocessed) elements processed in 0.16s ...
1000 / 6113 (16% created, 31% preprocessed) elements processed in 0.13s ...
1250 / 6113 (20% created, 49% preprocessed) elements processed in 0.19s ...
1500 / 6113 (25% created, 54% preprocessed) elements processed in 0.10s ...
1750 / 6113 (29% created, 56% preprocessed) elements processed in 0.12s ...
2000 / 6113 (33% created, 59% preprocessed) elements processed in 0.10s ...
2250 / 6113 (37% created, 62% preprocessed) elements processed in 0.08s ...
2500 / 6113 (41% created, 66% preprocessed) elements processed in 0.08s ...
2750 / 6113 (45% created, 71% preprocessed) elements processed in 0.09s ...
3000 / 6113 (49% created, 76% preprocessed) elements processed in 0.10s ...
3250 / 6113 (53% created, 81% preprocessed) elements processed in 0.10s ...
3500 / 6113 (57% created, 85% preprocessed) elements processed in 0.13s ...
3750 / 6113 (61% created, 93% preprocessed) elements processed in 0.12s ...
4000 / 6113 (65% created, 96% preprocessed) elements processed in 0.14s ...
4250 / 6113 (70% created, 98% preprocessed) elements processed in 0.16s ...
4500 / 6113 (74% created, 98% preprocessed) elements processed in 0.11s ...
4750 / 6113 (78% created, 98% preprocessed) elements processed in 0.12s ...
5000 / 6113 (82% created, 98% preprocessed) elements processed in 0.15s ...
5250 / 6113 (86% created, 98% preprocessed) elements processed in 0.15s ...
5500 / 6113 (90% created, 98% preprocessed) elements processed in 0.14s ...
5750 / 6113 (94% created, 99% preprocessed) elements processed in 0.13s ...
Done creating geometry
0 / 217 elements processed ...
Done creating geometry
Create elements :: 7.54
Create annotations :: 0.00
Create positioning elements :: 0.00
0 / 22 elements processed ...
Create spatial elements :: 0.15
Create structural items :: 0.00
Create element types :: 0.29
Place objects in collections :: 1.14
Add project to scene :: 0.14
Setting default context :: 0.01
Setup arrays :: 1.38
Import finished in 14.44 seconds
 - 10120 item(s) are in the old model
 - 6137 item(s) are in the new model
 - 1074 item(s) were added
 - 5057 item(s) were deleted
 - 5063 item(s) are common to both models
 - 0 item(s) had simple changes
 - 4867 item(s) are queued for a detailed geometry check
... processing old shapes ...
Traceback (most recent call last):
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\diff\operator.py", line 169, in execute
    ifc_diff.diff()
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcdiff.py", line 168, in diff
    old_shapes = self.summarise_shapes(self.old, potential_old_changes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcdiff.py", line 193, in summarise_shapes
    self.get_settings(ifc), ifc, multiprocessing.cpu_count(), include=elements
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcdiff.py", line 240, in get_settings
    settings.set_context_ids(body_contexts)
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\geom\main.py", line 217, in __getattr__
    raise AttributeError("'Settings' object has no attribute '%s'" % k)
AttributeError: 'Settings' object has no attribute 'set_context_ids'
 - 10120 item(s) are in the old model
 - 6137 item(s) are in the new model
 - 1074 item(s) were added
 - 5057 item(s) were deleted
 - 5063 item(s) are common to both models
 - 0 item(s) had simple changes
 - 4867 item(s) are queued for a detailed geometry check
... processing old shapes ...
Traceback (most recent call last):
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\diff\operator.py", line 169, in execute
    ifc_diff.diff()
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcdiff.py", line 168, in diff
    old_shapes = self.summarise_shapes(self.old, potential_old_changes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcdiff.py", line 193, in summarise_shapes
    self.get_settings(ifc), ifc, multiprocessing.cpu_count(), include=elements
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcdiff.py", line 240, in get_settings
    settings.set_context_ids(body_contexts)
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\geom\main.py", line 217, in __getattr__
    raise AttributeError("'Settings' object has no attribute '%s'" % k)
AttributeError: 'Settings' object has no attribute 'set_context_ids'
No MySQL support
```

**Comment by Andrej730** [comment]
Thanks for the bug report, issue is fixed.
