### ISSUE TITLE
Container Image aecgeeks/ifcopenshell:latest seems to have broken python package and IFCConvert binary

### ISSUE THREAD

**Issue by jonganej** [IfcOpenShell/IfcOpenShell#5168]
I wanted to quickly try out the Python API by downloading the container image as mentioned [in the documentation](https://docs.ifcopenshell.org/ifcopenshell-python/installation.html#docker) but running that seems to give me

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ifcopenshell/__init__.py", line 81, in <module>
    from . import ifcopenshell_wrapper
  File "/usr/lib/python3/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>
    from . import _ifcopenshell_wrapper
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
```

I then tried calling `IfcConvert` but that threw

```
IfcConvert: error while loading shared libraries: libhdf5_serial_cpp.so.103: cannot open shared object file: No such file or directory
```

Are there perhaps outdated dependencies on the docker image?

**Comment by aothms** [comment]
Thanks. I think the various ubuntu image version in this workflow ran out of sync. Let's see if my commits help in that regard.

**Comment by tymokvo** [comment]
Hello, also just ran into the same error. I also noticed that there only ever seems to be the `latest` tag pushed to [Docker Hub](https://hub.docker.com/r/aecgeeks/ifcopenshell/tags). Maybe publishing images tagged to match the git tags would help to have a fallback in the future?

Would be happy to contribute, if needed.

**Comment by aothms** [comment]
> Would be happy to contribute, if needed.

@tymokvo that would be amazing :)

> I also noticed that there only ever seems to be the latest tag ...

We discussed some of this here: https://github.com/IfcOpenShell/IfcOpenShell/issues/3927 I guess nobody really felt the urgency to properly apply and test this on dockerhub

See here how we use https://github.com/IfcOpenShell/IfcOpenShell/blob/df494a3defe1c06ac62db2c88c385702dea2c601/.github/workflows/ci-ifcconvert.yml#L61 `steps.version.outputs.version` for inspiration.

**Comment by tymokvo** [comment]
Let me know what you think of #5463 !
