### ISSUE TITLE
Error when working with Leaders.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5170]
I get the following error when
- duplicate an leader
- enter edit mode to move a vertice, and then exit. 

file: https://hub.openingdesign.com/OpeningDesign/Rae_Living_Room_Ext/src/commit/d7a47e2f61d47ce31addb8a35d008c317d81e5af/Open/Models/BlenderBIM/Rae_Living_Room_Ext.ifc

Might be related to #4487

`BlenderBIM Add-on vO.O-240605-cfdOed6`

https://github.com/user-attachments/assets/5fac8a8a-70b7-45e8-82ed-5e031cb6819f

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 358, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1758, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1662, in execute
    return IfcStore.execute_ifc_operator(self, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1667, in _execute
    bpy.ops.bim.update_representation(obj=obj.name, ifc_representation_class="")
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 326, in _execute
    self.update_obj_mesh_representation(context, obj)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 420, in update_obj_mesh_representation
    styles=tool.Geometry.get_styles(obj, only_assigned_to_faces=True),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\geometry.py", line 475, in get_styles
    for poly in obj.data.polygons:
                ^^^^^^^^^^^^^^^^^
AttributeError: 'Curve' object has no attribute 'polygons'
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109

```

**Comment by Andrej730** [comment]
Was part of #4843, we don't store ifc materials in blender materials anymore so materials for curve objects will be empty and issue won't occur.
