### ISSUE TITLE
entity instance of type 'IFC4.IfcMaterialLayer' has no attribute 'OwnerHistory'

### ISSUE THREAD

**Issue by HeshamB** [IfcOpenShell/IfcOpenShell#5182]
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240602
last_actions: 
# ifcopenshell.api: geometry.disconnect_path
>>> {"element": {"cast_type": "entity_instance", "value": 1222, "Name": "Wall"}, "connection_type": "ATEND"}
# ifcopenshell.api: geometry.add_axis_representation
>>> {"context": {"cast_type": "entity_instance", "value": 27, "Name": null}, "axis": "[Vector((0.0, 0.0)), Vector((4.873345375061035, 0.0))]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1222, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 1352, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 1352, "Name": null}}
# ifcopenshell.api: geometry.add_wall_representation
>>> {"context": {"cast_type": "entity_instance", "value": 15, "Name": null}, "length": "4.8733453143207806", "height": "3.0", "x_angle": "0", "offset": "0.0", "thickness": "0.2", "clippings": "[]", "booleans": "[]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1222, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 1362, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 1362, "Name": null}}
# operator: BIM_OT_override_object_delete
# ifcopenshell.api: root.remove_product
>>> {"product": {"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}}
# ifcopenshell.api: root.remove_product
>>> {"product": {"cast_type": "entity_instance", "value": 73, "Name": null}}
last_error: Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 589, in _execute
    tool.Geometry.delete_ifc_object(obj)
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\geometry.py", line 145, in delete_ifc_object
    ifcopenshell.api.run("root.remove_product", tool.Ifc.get(), product=element)
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 184, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 344, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\root\remove_product.py", line 231, in remove_product
    history = settings["product"].OwnerHistory
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 219, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcMaterialLayer' has no attribute 'OwnerHistory'

ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: IfcOpenShell v0.7.0-c7830e9e5
```

**Comment by Andrej730** [comment]
@HeshamB hello! can you please share a way to reproduce this issue? (probably will need .ifc file and lists of steps)

**Comment by Moult** [comment]
This isn't an .ifc file, from the log you can see it's never been saved and seems to be using a blank project.

A new demo project indeed has `#73=IFCMATERIALLAYER(#68,100.,$,$,$,$,$);` ... but how it manages to get fed into remove_product... I have no idea.

**Comment by Andrej730** [comment]
Closing as no idea if issue is still present.
