### ISSUE TITLE
error message after trying to open an ifc-file

### ISSUE THREAD

**Issue by don-matteo** [IfcOpenShell/IfcOpenShell#5183]
I also attached the ifc-file I tried to open in BlenderBIM, , erm, Bonsai ;-)
```
os: Darwin
os_version: Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64
python_version: 3.11.7
architecture: ('64bit', '')
machine: x86_64
processor: i386
blender_version: 4.2.0
blenderbim_version: 0.0.240602
last_actions: 
last_error: Traceback (most recent call last):
  File "/Users/matteoneustadt/Library/Application Support/Blender/4.2/scripts/addons/blenderbim/bim/module/project/operator.py", line 691, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "/Applications/Blender.app/Contents/Resources/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/matteoneustadt/Library/Application Support/Blender/4.2/scripts/addons/blenderbim/bim/module/project/operator.py", line 771, in execute
    ifc_importer.execute()
  File "/Users/matteoneustadt/Library/Application Support/Blender/4.2/scripts/addons/blenderbim/bim/import_ifc.py", line 269, in execute
    self.create_styles()
  File "/Users/matteoneustadt/Library/Application Support/Blender/4.2/scripts/addons/blenderbim/bim/import_ifc.py", line 1726, in create_styles
    styles.extend(styled_item.Styles)
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/matteoneustadt/Library/Application Support/Blender/4.2/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 179, in __getattr__
    return entity_instance.wrap_value(self.wrapped_data.get_argument(idx), self.wrapped_data.file)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matteoneustadt/Library/Application Support/Blender/4.2/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 4054, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unknown attribute type
Location: /Applications/Blender.app/Contents/Resources/4.2/scripts/modules/bpy/ops.py:109


ifc: 69-TIDE-IFC4x3_240815.ifc
schema: IFC4X3
preprocessor_version: Vectorworks Architect 2024 Update 6 (Build 765860) by Vectorworks, Inc.
originating_system: Macintosh
```
[69-TIDE-IFC4x3_240815.ifc.zip](https://github.com/user-attachments/files/16627110/69-TIDE-IFC4x3_240815.ifc.zip)

**Comment by don-matteo** [comment]
Which unstable version would you recommend to use? The latest one?

**Comment by Andrej730** [comment]
yes, the latest one.
