### ISSUE TITLE
missing files in PyPI builds

### ISSUE THREAD

**Issue by smr02** [IfcOpenShell/IfcOpenShell#5188]
```
pip install ifc5d
python -c "import ifc5d.qto"


Note: API not available due to missing dependencies: geometry.add_representation - No module named 'bpy'
Note: API not available due to missing dependencies: grid.create_axis_curve - No module named 'bpy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/smr/opt/anaconda3/envs/structural/lib/python3.10/site-packages/ifc5d/qto.py", line 35, in <module>
    with open(os.path.join(cwd, name + ".json"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/smr/opt/anaconda3/envs/structural/lib/python3.10/site-packages/ifc5d/IFC4QtoBaseQuantities.json'

```

**Comment by Andrej730** [comment]
@smr02 Thanks for the bug report, updated pypi builds for ifc5d (71aa30a), ifccityjson (3d2dfdf).

There is still an issue with missing .json files in ifcopenshell-python (f0077b9, missing files are in util/schema), will update it soon too.
