### ISSUE TITLE
AttributeError: 'Image' object has no attribute 'BIMMeshProperties'

### ISSUE THREAD

**Issue by rungutter** [IfcOpenShell/IfcOpenShell#5194]
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.7.11-alpha240814
bonsai_commit_hash: 795ebc0
last_actions: 
# operator: BIM_OT_save_project
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 39, "Name": "My Site"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 39, "Name": "My Site"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 45, "Name": "My Building"}}
# operator: BIM_OT_save_project
# operator: BIM_OT_save_project
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 39, "Name": "My Site"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, -0.0013117153430357575], [0.0, 1.0, 0.0, 0.006558577064424753], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 39, "Name": "My Site"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 45, "Name": "My Building"}}
last_error: Traceback (most recent call last):
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 1306, in _execute
    ifc_exporter.export()
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\export_ifc.py", line 50, in export
    self.sync_all_objects()
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\export_ifc.py", line 101, in sync_all_objects
    result = self.sync_object_placement(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\export_ifc.py", line 148, in sync_object_placement
    bpy.ops.bim.update_representation(obj=obj.name)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 369, in _execute
    self.update_obj_mesh_representation(context, obj)
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 410, in update_obj_mesh_representation
    old_representation = self.file.by_id(obj.data.BIMMeshProperties.ifc_definition_id)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Image' object has no attribute 'BIMMeshProperties'
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\bpy\ops.py:109


ifc: BIM-model-of-house.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.7.11-alpha240814
originating_system: Bonsai 0.7.11-alpha240814-795ebc0
```

**Comment by Andrej730** [comment]
@rungutter  Can you please share .ifc file to reproduce the issue?

**Comment by rungutter** [comment]
I've deleted the file, sorry. If it happens again with a new file, i will
share here
NC

- Sent on the go. Please excuse tpyos
