### ISSUE TITLE
ifcpatch TessellateElements not working

### ISSUE THREAD

**Issue by smr02** [IfcOpenShell/IfcOpenShell#5199]
ifcpatch TessellateElements returns a error. 
Attached my test.ifc file. But I didn't get it to work with any file. 

```python
import ifcpatch, ifcopenshell
import os

print("ifcopenshell version:", ifcopenshell.__version__)
print("ifcpatch version:    ", ifcpatch.__version__)

ifc_name_in = 'test.ifc'
ifc_file_path_in = os.path.expanduser(f'~/Desktop/{ifc_name_in}')

ifc_name_out = 'Tessellated.ifc'
ifc_file_path_out = os.path.expanduser(f'~/Desktop/{ifc_name_out}')

output = ifcpatch.execute({
    "input": ifc_file_path_in,
    "file": ifcopenshell.open(ifc_file_path_in),
    "recipe": "TessellateElements",
    "arguments": ['IfcBeam'],
})

ifcpatch.write(output, ifc_file_path_out)
```

```
ifcopenshell version: 0.7.10
ifcpatch version:     0.7.10
Note: API not available due to missing dependencies: geometry.add_representation - No module named 'bpy'
Note: API not available due to missing dependencies: grid.create_axis_curve - No module named 'bpy'
Traceback (most recent call last):
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/entity_instance.py", line 352, in __setitem__
    self.method_list[idx](self.wrapped_data, idx, entity_instance.unwrap_value(value))
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 6570, in setArgumentAsAggregateOfInt
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsAggregateOfInt(self, i, v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Attribute of type AGGREGATE OF INTEGER needs a python sequence of ints

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/smr/Desktop/test.py", line 13, in <module>
    output = ifcpatch.execute({
             ^^^^^^^^^^^^^^^^^^
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcpatch/__init__.py", line 84, in execute
    patcher.patch()
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcpatch/recipes/TessellateElements.py", line 115, in patch
    mesh = ifcopenshell.api.run(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/api/__init__.py", line 92, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/api/__init__.py", line 258, in wrapper
    raise e
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/api/__init__.py", line 252, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/api/geometry/add_mesh_representation.py", line 59, in add_mesh_representation
    return usecase.execute()
           ^^^^^^^^^^^^^^^^^
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/api/geometry/add_mesh_representation.py", line 66, in execute
    return self.create_mesh_representation()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/api/geometry/add_mesh_representation.py", line 71, in create_mesh_representation
    return self.create_polygonal_face_set()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/api/geometry/add_mesh_representation.py", line 96, in create_polygonal_face_set
    faces = [self.file.createIfcIndexedPolygonalFace([v + 1 for v in f]) for f in self.settings["faces"][i]]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/api/geometry/add_mesh_representation.py", line 96, in <listcomp>
    faces = [self.file.createIfcIndexedPolygonalFace([v + 1 for v in f]) for f in self.settings["faces"][i]]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/file.py", line 379, in create_entity
    e[idx] = arg
    ~^^^^^
  File "/Users/smr/opt/anaconda3/envs/Fcad/lib/python3.11/site-packages/ifcopenshell/entity_instance.py", line 354, in __setitem__
    raise TypeError(
TypeError: attribute 'CoordIndex' for entity 'IFC4.IfcIndexedPolygonalFace' is expecting value of type 'AGGREGATE OF INT', got 'list'.
```
[test.ifc.txt](https://github.com/user-attachments/files/16675689/test.ifc.txt)

**Comment by Andrej730** [comment]
@smr02 
Thanks for the bug report. Fixed by bad6931.
