### ISSUE TITLE
Bonsai: error encountered when using "Add>Roof" in Edit mode

### ISSUE THREAD

**Issue by rungutter** [IfcOpenShell/IfcOpenShell#5204]
Attempted to add a roof while in edit mode, using the top menu "Add>Roof." I've had no issues using this while in Object mode. Bug report below. screenshot and ifc/blend files attached
![image](https://github.com/user-attachments/assets/7e2c008a-8525-413f-b6c9-b4ed2b60fb0f)
[HealyHouse.zip](https://github.com/user-attachments/files/16683786/HealyHouse.zip)

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.7.11-alpha240814
bonsai_commit_hash: 795ebc0
last_actions: 
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 2439, "Name": "IfcRoof"}}
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 24, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcRoof/IfcRoof.002\") at 0x000001F240838F08>", "geometry": "<bpy_struct, Mesh(\"IfcRoof.002\") at 0x000001F24083B208>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None"}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 2446, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.assign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 2439, "Name": "IfcRoof"}, "representation": {"cast_type": "entity_instance", "value": 2446, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 2439, "Name": "IfcRoof"}}
# ifcopenshell.api: spatial.assign_container
>>> {"products": [{"cast_type": "entity_instance", "value": 2439, "Name": "IfcRoof"}], "relating_structure": {"cast_type": "entity_instance", "value": 1796, "Name": "SecdFloor"}}
# ifcopenshell.api: aggregate.unassign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 2439, "Name": "IfcRoof"}]}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 2076, "Name": null}}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 2439, "Name": "IfcRoof"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 2439, "Name": "IfcRoof"}}
last_error: Traceback (most recent call last):
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\roof.py", line 528, in _execute
    bpy.ops.object.select_all(action="DESELECT")
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.object.select_all.poll() failed, context is incorrect

ifc: HealyHouse.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.7.11-alpha240814
originating_system: Bonsai 0.7.11-alpha240814-795ebc0
```

**Comment by SavuGust27** [comment]
i think that because its not expected for one to add a roof in edit mode. at the end the error says that the context is incorrect, so it not intended to be used in edit mode.

**Comment by rungutter** [comment]
Sure, I agree it makes more sense to add in object mode. I'm just reporting what I encountered in my specific use case
