### ISSUE TITLE
Bonsai: BIM tool, unable to add wall

### ISSUE THREAD

**Issue by rungutter** [IfcOpenShell/IfcOpenShell#5205]
Attempted to use BIM tool to add a wall, as I have done multiple times already in this project. I set measurements and clicked "add", which returned the error below. Screenshot and ifc/blend files attached
![image](https://github.com/user-attachments/assets/a24463bf-4d0c-4daf-a4c7-a095ec56edcc)
[HealyHouse.zip](https://github.com/user-attachments/files/16683974/HealyHouse.zip)

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.7.11-alpha240814
bonsai_commit_hash: 795ebc0
last_actions: 
# operator: BIM_OT_finish_editing_roof
# ifcopenshell.api: pset.edit_pset
>>> {"pset": {"cast_type": "entity_instance", "value": 2463, "Name": "BBIM_Roof"}, "properties": "{'Data': IfcText('{\"roof_type\": \"HIP/GABLE ROOF\", \"generation_method\": \"ANGLE\", \"roof_thickness\": 0.32808399439014474, \"rafter_edge_angle\": 1.5707963705062866, \"angle\": 0.4642575681209564, \"percentage\": 50.07626724243164, \"path_data\": {\"edges\": [[0, 1], [1, 2], [2, 3], [3, 0]], \"verts\": [[-5.0, -0.5000000596046448, 0.0], [-5.0, 6.0, 0.0], [1.0000001192092896, 6.0, 0.0], [1.0000001192092896, -0.5000000596046448, 0.0]], \"gable_roof_angles\": [0.0, 1.5707963705062866, 0.0, 1.5707963705062866], \"gable_roof_separate_verts\": [0, 1, 0, 1]}}')}"}
# operator: BIM_OT_enable_editing_roof
# operator: BIM_OT_cancel_editing_roof
# operator: BIM_OT_enable_editing_roof
# operator: BIM_OT_finish_editing_roof
# ifcopenshell.api: pset.edit_pset
>>> {"pset": {"cast_type": "entity_instance", "value": 2463, "Name": "BBIM_Roof"}, "properties": "{'Data': IfcText('{\"roof_type\": \"HIP/GABLE ROOF\", \"generation_method\": \"ANGLE\", \"roof_thickness\": 0.32808399439014474, \"rafter_edge_angle\": 2.0420353412628174, \"angle\": 0.4642575681209564, \"percentage\": 50.07626724243164, \"path_data\": {\"edges\": [[0, 1], [1, 2], [2, 3], [3, 0]], \"verts\": [[-5.0, -0.5000000596046448, 0.0], [-5.0, 6.0, 0.0], [1.0000001192092896, 6.0, 0.0], [1.0000001192092896, -0.5000000596046448, 0.0]], \"gable_roof_angles\": [0.0, 1.5707963705062866, 0.0, 1.5707963705062866], \"gable_roof_separate_verts\": [0, 1, 0, 1]}}')}"}
# operator: BIM_OT_add_constr_type_instance
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_add_constr_type_instance
last_error: Traceback (most recent call last):
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\product.py", line 164, in _execute
    if self.generate_layered_element(ifc_class, relating_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\product.py", line 296, in generate_layered_element
    obj = wall.DumbWallGenerator(relating_type).generate()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\wall.py", line 814, in generate
    return self.derive_from_cursor()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\wall.py", line 958, in derive_from_cursor
    return self.create_wall()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\natec\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\wall.py", line 968, in create_wall
    if self.container_obj:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'DumbWallGenerator' object has no attribute 'container_obj'

ifc: HealyHouse.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.7.11-alpha240814
originating_system: Bonsai 0.7.11-alpha240814-795ebc0
```

**Comment by SavuGust27** [comment]
have you tried saving and clicking in reverting ifc project?

**Comment by rungutter** [comment]
Yes, I had to reload the project to move forward. Just reporting the issue.
