### ISSUE TITLE
Segfault on ifcRelVoidsElement in IfcGeom::Kernel::convert_openings

### ISSUE THREAD

**Issue by lenolib** [IfcOpenShell/IfcOpenShell#523]
I encountered an ifc file that produced a segfault with the stacktrace below. I've truncated the ifc-file down to a the first line which results in the segfault.

[supersmallfail-manualedit.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/2675798/supersmallfail-manualedit.ifc.txt)

Version: `IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev (OCC 6.8.0.oce-0.17)` commit `d78c9171`
```
#0  0x0000000000ada3b4 in TopoDS_Shape::ShapeType (this=0x7fffffffa9e0) at /usr/include/oce/TopoDS_Shape.lxx:137
#1  0x0000000000f18b11 in IfcGeom::Kernel::convert_openings (this=0x7fffffffccf0, entity=0x158d650, openings=..., 
    entity_shapes=std::vector of length 1, capacity 1 = {...}, entity_trsf=..., cut_shapes=std::vector of length 0, capacity 0)
    at /home/lennart/other_repos/ifcOpenShell/src/ifcgeom/IfcGeomFunctions.cpp:373
#2  0x0000000000f30a35 in IfcGeom::Kernel::create_brep_for_representation_and_product<double> (this=0x7fffffffccf0, settings=..., 
    representation=0x158d010, product=0x158d650) at /home/lennart/other_repos/ifcOpenShell/src/ifcgeom/IfcGeomFunctions.cpp:1321
#3  0x0000000000afbece in IfcGeom::Iterator<double>::create_shape_model_for_next_entity (this=0x7fffffffccf0)
    at /home/lennart/other_repos/ifcOpenShell/src/ifcconvert/../ifcconvert/../ifcgeom/IfcGeomIterator.h:473
#4  0x0000000000af06e4 in IfcGeom::Iterator<double>::create (this=0x7fffffffccf0)
    at /home/lennart/other_repos/ifcOpenShell/src/ifcconvert/../ifcconvert/../ifcgeom/IfcGeomIterator.h:653
#5  0x0000000000ae5923 in IfcGeom::Iterator<double>::initialize (this=0x7fffffffccf0)
    at /home/lennart/other_repos/ifcOpenShell/src/ifcconvert/../ifcconvert/../ifcgeom/IfcGeomIterator.h:281
#6  0x0000000000ad3f74 in main (argc=3, argv=0x7fffffffd1e8) at /home/lennart/other_repos/ifcOpenShell/src/ifcconvert/IfcConvert.cpp:619
```
Changing line 373 in `IfcGeomFunctions.cpp` to
`if (! entity_shape.IsNull() && entity_shape.ShapeType() == TopAbs_COMPSOLID) {`
(addition of `! entity_shape.IsNull() &&`) appears to "solve" the issue (at least produces no segfault).

**Comment by lenolib** [comment]
Using OCCT 7.3 does indeed seem to resolve the issue, as well as another encountered segfault.
