### ISSUE TITLE
Bonsai - 240827 - error when printing 2D representation of custom IfcWindow

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#5234]
Windows 10 on these versions:
![image](https://github.com/user-attachments/assets/53fd9e2f-ffbe-458c-b506-449e226b9811)

When printing the file without 2D representation it works:
![image](https://github.com/user-attachments/assets/f171f294-2956-4019-b354-8c10503c3e2f)

Adding the representation works:
![image](https://github.com/user-attachments/assets/1dff188f-00e1-49a3-a6a6-50d78da6839a)

But when printing with the 2D representation it produces this error:
Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 267, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 564, in generate_linework
    self.serialiser.finalize()
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4828, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: An unknown error occurred

Here is the test file with the 2D Rep added (remove the .txt):
[Window test + 2d rep.ifc.txt](https://github.com/user-attachments/files/16762319/Window.test.%2B.2d.rep.ifc.txt)

**Comment by theoryshaw** [comment]
might be related to https://github.com/IfcOpenShell/IfcOpenShell/issues/5136,  https://github.com/IfcOpenShell/IfcOpenShell/issues/4924, & #5112

**Comment by theoryshaw** [comment]
Fixed as of https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/bonsai-0.7.11-alpha240829 !
