### ISSUE TITLE
generated space but no reaction to Toglle Space visibility, with error message attached

### ISSUE THREAD

**Issue by JuantLB** [IfcOpenShell/IfcOpenShell#5240]
```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 11, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.7.11-alpha240828
bonsai_commit_hash: 64cba98
last_actions: 
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 1499, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.assign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1483, "Name": "Space0"}, "representation": {"cast_type": "entity_instance", "value": 1499, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1483, "Name": "Space0"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 1483, "Name": "Space0"}], "relating_object": {"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}}
# ifcopenshell.api: spatial.unassign_container
>>> {"products": "[]"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1477, "Name": null}}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 1483, "Name": "Space0"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1483, "Name": "Space0"}}
# operator: BIM_OT_spatial_hotkey
# operator: BIM_OT_spatial_hotkey
last_error: Traceback (most recent call last):
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\spatial\workspace.py", line 138, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\spatial\workspace.py", line 178, in hotkey_S_H
    bpy.ops.bim.toggle_hide_spaces()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\space.py", line 112, in execute
    core.toggle_hide_spaces(tool.Ifc, tool.Spatial)
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\spatial.py", line 247, in toggle_hide_spaces
    spatial.toggle_hide_spaces(spaces)
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 859, in toggle_hide_spaces
    if first_obj.hide_get() == False:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'hide_get'
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell 0.7.11-alpha240828
originating_system: IfcOpenShell 0.7.11-alpha240828
```

**Comment by Moult** [comment]
I'm trying to recreate this but not able to. Can you help provide more detailed steps / screenshare / sample file?

**Comment by Moult** [comment]
Bump @JuantLB

**Comment by Moult** [comment]
Closing, but please open again if we can recreate this.
