### ISSUE TITLE
Cannot create shape on booleaned rectangular pyramid (used for perspective view fustrums)

### ISSUE THREAD

**Issue by manuvarkey** [IfcOpenShell/IfcOpenShell#5241]
When adding a perspective Model View under drawings and enabling the view, following error is raised.

```
Python: Traceback (most recent call last):
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 1541, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 1568, in execute
    core.sync_references(tool.Ifc, tool.Collector, tool.Drawing, drawing=tool.Ifc.get().by_id(self.drawing))
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/core/drawing.py", line 466, in sync_references
    annotation = drawing_tool.generate_reference_annotation(drawing, reference_element, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/drawing.py", line 1159, in generate_reference_annotation
    return cls.generate_section_reference_annotation(drawing, reference_element, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/drawing.py", line 1301, in generate_section_reference_annotation
    bm = clip_to_camera_boundary(bm, bounds)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/drawing.py", line 1261, in clip_to_camera_boundary
    points = helper.clip_segment(bounds, points)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/helper.py", line 354, in clip_segment
    xmin, xmax, ymin, ymax, _, _ = bounds
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

When trying to activate a previously added perspective Model View, following error is raised.

```
Python: Traceback (most recent call last):
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 1541, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 1556, in execute
    core.activate_drawing_view(tool.Ifc, tool.Blender, tool.Drawing, drawing=drawing)
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/core/drawing.py", line 488, in activate_drawing_view
    camera = drawing_tool.import_drawing(drawing)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/drawing.py", line 696, in import_drawing
    camera = tool.Loader.create_camera(drawing, representation, shape)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manu/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/loader.py", line 694, in create_camera
    width = max(x) - min(x)
            ^^^^^^
ValueError: max() arg is an empty sequence

```

Model file:

https://github.com/user-attachments/files/16762216/Karayatta.House.zip

**Comment by Plae-Blue-Dot** [comment]
Can confirm same issue Windows 10
Blender 4,2
Bonsai 240829

**Comment by theoryshaw** [comment]
sames :)

**Comment by Moult** [comment]
First error is fixed, second is an OCC one.

@aothms perspective fustrums are represented using a CsgSolid which applies a half space solid boolean to a rectangular pyramid. In 0.7.0 create_shape would work, whereas 0.8.0 gives no vertices (no error either).

[untitled.ifc.txt](https://github.com/user-attachments/files/16826166/untitled.ifc.txt)

```python
import ifcopenshell
import ifcopenshell.geom

import ifcopenshell.ifcopenshell_wrapper as wrapper

wrapper.turn_on_detailed_logging()

ifc_file = ifcopenshell.open('/home/dion/untitled.ifc')
settings = ifcopenshell.geom.settings()
shape = ifcopenshell.geom.create_shape(settings, ifc_file.by_id(1441))
print(shape.verts) # empty on v0.8.0
```

**Comment by aothms** [comment]
> perspective fustrums are represented using a CsgSolid which applies a half space solid boolean to a rectangular pyramid

Sounds good to me, but I doubt this has ever worked. We never got perspective output out of the OCCT HLR working anyway I thought. Am I missing something?

> whereas 0.8.0 gives no vertices (no error either).

That needs to be fixed.

**Comment by Moult** [comment]
It didn't work in OCC (although FreeCAD got it working - they responded here: https://github.com/IfcOpenShell/IfcOpenShell/issues/3880 ) - but this issue is about giving no vertices. We use the vertices to recreate a Blender camera. Blender can then create a perspective raster or Freestyle vector render.

**Comment by aothms** [comment]
Right.. forgot to map the Position for the pyramid. So the halfspace was slicing away the full solid. That's why we didn't get an error.

**Comment by theoryshaw** [comment]
Do we need a new bot build for this commit to have an affect in BB?

**Comment by Andrej730** [comment]
> Do we need a new bot build for this commit to have an affect in BB?

We do, though it seems last bot build failed for Windows and Linux.

**Comment by aothms** [comment]
started a new one. (thought I already did, but apparently not, last build didn't fail btw, but needed to do some maintenance on the osx machines so last build I did only for mac)

**Comment by Andrej730** [comment]
> Unfortunately i still get the following error with `4.2.1 Bonsai vo.8.1-a1pha240911-9be392e`

IfcOpenBot build is not yet updated.

**Comment by theoryshaw** [comment]
> IfcOpenBot build is not yet updated.

How can you tell?...

I usually try to look for the following.  And if the commit is in release, i assume that release has the IfcOpenBot build. Is that not a correct assumption?

![image](https://github.com/user-attachments/assets/11d1e1fa-c16f-4cf9-9352-33e36ef01db5)

![image](https://github.com/user-attachments/assets/1c61cdb8-9469-4a2d-a5b6-51b47810c708)

**Comment by aothms** [comment]
https://github.com/IfcOpenBot/IfcOpenShell/commit/f5e02d141343fb3dbb88b49ac38b12ac8e5626e0#commitcomment-146594656

**Comment by Andrej730** [comment]
> Error after trying to activate the `RENDERING 1` drawing.

806975c - updated IOS build in Bonsai.

**Comment by theoryshaw** [comment]
Thanks!  confirmed this is fixed!
