### ISSUE TITLE
Error when `bim.activate_drawing`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5244]
When you activate the `FLOOR PLAN - 1ST FLOOR` drawing the first time, you get the following error, but if you active it again there's no error. 

file: https://hub.openingdesign.com/OpeningDesign/Restaurant_MPM/src/commit/d22202f0d33dd75c98577d8c5f85ee0256970673/Open/Models/BlenderBIM/Restaurant_MPM.ifc

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1546, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1573, in execute
    core.sync_references(tool.Ifc, tool.Collector, tool.Drawing, drawing=tool.Ifc.get().by_id(self.drawing))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\drawing.py", line 466, in sync_references
    annotation = drawing_tool.generate_reference_annotation(drawing, reference_element, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 1158, in generate_reference_annotation
    ensure_referenced_drawing_obj_exists(reference_element)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 1150, in ensure_referenced_drawing_obj_exists
    cls.import_annotations_in_group(cls.get_drawing_group(drawing))
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 683, in import_annotations_in_group
    tool.Collector.assign(obj)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\collector.py", line 101, in assign
    cls.link_to_collection_safe(obj, drawing_obj.BIMObjectProperties.collection)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\collector.py", line 142, in link_to_collection_safe
    if collection.objects.find(obj_or_col.name) != -1:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'objects'

```

**Comment by Moult** [comment]
This is actually really nice because it shows the simplification of the collection system is now able to reveal subtle bugs like this (able to have annotations both contained and visualised in a different container in the outliner).
