### ISSUE TITLE
Editing project IFC header raises error for some files

### ISSUE THREAD

**Issue by manuvarkey** [IfcOpenShell/IfcOpenShell#5246]
Following error is raised when the IFC header editing is activated for certain files.

![image](https://github.com/user-attachments/assets/03256aac-9490-465c-9210-3d0dda407dbe)

```
Python: Traceback (most recent call last):
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/project/operator.py", line 577, in execute
    author = self.file.wrapped_data.header.file_name.author
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 6047, in author
    return _ifcopenshell_wrapper.FileName_author(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Type held at index 2 is 5Blank and not St6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE

```

Model File:
https://github.com/user-attachments/files/16762216/Karayatta.House.zip

**Comment by Andrej730** [comment]
Related to #5118

**Comment by Moult** [comment]
Seems to be fixed now.
