### ISSUE TITLE
Not able to open the following file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5251]
Not able to open the following file

file: https://hub.openingdesign.com/OpeningDesign/2917_International_Ln/src/commit/f9aad067659c007f69db996656b98506fef6ee21/Open/Models/BlenderBIM/shower.ifc

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.0.0
bonsai_commit_hash: f3ab214
last_actions: 
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
last_error: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 751, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 832, in execute
    ifc_importer.execute()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 242, in execute
    self.create_native_elements()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 614, in create_native_elements
    mesh = self.create_native_faceted_brep(element, mesh_name, native_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 933, in create_native_faceted_brep
    self.convert_representation_item_faceted_brep(item)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 991, in convert_representation_item_faceted_brep
    return self.convert_representation_item_face_set(item, mesh["Outer"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 999, in convert_representation_item_face_set
    bounds = tuple(chain.from_iterable(f["Bounds"] for f in mesh["CfsFaces"] if len(f["Bounds"]) == 1))
                                                            ~~~~^^^^^^^^^^^^
TypeError: 'entity_instance' object is not subscriptable
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: shower.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: BlenderBIM 0.0.240605-cfd0ed6
```

**Comment by Andrej730** [comment]
Same issue as #5248

**Comment by theoryshaw** [comment]
This does not work yet with `bonsai-0.7.11-alpha240831 (unstable)`, on my side, anyway. 
I guess this assumes `bonsai-0.7.11-alpha240831 (unstable)` incorporates [the latest](https://github.com/IfcOpenBot/IfcOpenShell/commit/03935a91dae656a07285f9f25bbbd0add1fe83b7) bot build.  Is that correct?
Is there a way to determine if it does?

**Comment by theoryshaw** [comment]
Might be related. 
I can't open the following file either. 
https://hub.openingdesign.com/OpeningDesign/Rae_Living_Room_Ext/src/commit/27f77a183c34547ba73cbe72feccdb4c4833b8d3/Open/Models/BlenderBIM/Rae_Living_Room_Ext.ifc

bonsai-0.7.11-alpha240831 (unstable)

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.0.0
bonsai_commit_hash: 76ba394
last_actions: 
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
last_error: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 751, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 832, in execute
    ifc_importer.execute()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 244, in execute
    self.create_elements()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 630, in create_elements
    self.create_generic_elements(self.elements)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 646, in create_generic_elements
    products = self.create_products(elements, settings=settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 733, in create_products
    valid_file = iterator.initialize()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 2165, in initialize
    return _ifcopenshell_wrapper.Iterator_initialize(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unexpected topology
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: Rae_Living_Room_Ext_old.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-c7830e9e5
originating_system: BlenderBIM 0.0.240605-9a37460
```

**Comment by Andrej730** [comment]
> Is there a way to determine if it does?

All builds after https://github.com/IfcOpenShell/IfcOpenShell/commit/eed603bbcd38e59db4236e8974420f1d2e4a1132 have it.

> RuntimeError: Unexpected topology

It's a different error, same invalid ifc error as in #5113: `#2890502=IFCAXIS2PLACEMENT3D($,$,$);`

You can replace this line with:
```
#2890502=IFCAXIS2PLACEMENT3D(#2890503,$,$);
#2890503=IFCCARTESIANPOINT((0.,0.,0.));
```

**Comment by theoryshaw** [comment]
sorry about the placement question, i realized it was the same problem, as [this](https://github.com/IfcOpenShell/IfcOpenShell/issues/5113) one, so i deleted the question.  I thought i did if fast enough... but apparently not. :)
