### ISSUE TITLE
Cannot save as IFC

### ISSUE THREAD

**Issue by adrien-kaelin** [IfcOpenShell/IfcOpenShell#5253]
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.7.11-alpha240814
bonsai_commit_hash: 795ebc0
last_actions: 
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 386418, "Name": null}, "styles": [{"cast_type": "entity_instance", "value": 313836, "Name": "IFC Surface Style 10288"}], "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 54402, "Name": "267985"}, "representation": {"cast_type": "entity_instance", "value": 54399, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 54399, "Name": null}}
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 102, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcBuildingElementProxy/267986\") at 0x000001B9142FB920>", "geometry": "<bpy_struct, Mesh(\"102/54421\") at 0x000001B92A80AB20>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 54424, "Name": "267986"}}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 386438, "Name": null}, "styles": [{"cast_type": "entity_instance", "value": 313836, "Name": "IFC Surface Style 10288"}], "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 54424, "Name": "267986"}, "representation": {"cast_type": "entity_instance", "value": 54421, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 54421, "Name": null}}
# operator: BIM_OT_update_representation
last_error: Traceback (most recent call last):
  File "C:\Users\adkaelin\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adkaelin\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 1306, in _execute
    ifc_exporter.export()
  File "C:\Users\adkaelin\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\export_ifc.py", line 50, in export
    self.sync_all_objects()
  File "C:\Users\adkaelin\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\export_ifc.py", line 104, in sync_all_objects
    result = self.sync_object_material(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adkaelin\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\export_ifc.py", line 137, in sync_object_material
    bpy.ops.bim.update_representation(obj=obj.name)
  File "C:\BIM\Blender\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Erreur: Python : Traceback (most recent call last):
  File "C:\Users\adkaelin\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adkaelin\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 369, in _execute
    self.update_obj_mesh_representation(context, obj)
  File "C:\Users\adkaelin\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 411, in update_obj_mesh_representation
    context_of_items = old_representation.ContextOfItems
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adkaelin\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\entity_instance.py", line 238, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcIndexedPolygonalFace' has no attribute 'ContextOfItems'
Position : C:\BIM\Blender\4.2\scripts\modules\bpy\ops.py:109


ifc: CPAN-CHAUD-EXE-X-X-HTH-X-2hpL9IyXz8fuHFjhySk9ad.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.7.11-alpha240814
originating_system: Bonsai 0.7.11-alpha240814-795ebc0
```

**Comment by adrien-kaelin** [comment]
Hello,I found thé solution. I’ve previously saved the file as .blend. Sorry for my notification. Best regards Adrien KaelinLe 29 août 2024 à 17:32, Andrej ***@***.***> a écrit :﻿
@adrien-kaelin can you please share some example to reproduce this? Also, please check if IFC model is valid.
