### ISSUE TITLE
Error when trying to `bim.link_ifc` a file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5265]
When i try to `bim.link_ifc` [this](https://hub.openingdesign.com/OpeningDesign/Restaurant_MPM/src/commit/15212c01d74a74099d3cb870402363910bdde2a9/Open/Models/BlenderBIM/Restaurant_MPM.ifc) file, i get the following error...

bonsai-0.7.11-alpha240831 (unstable)

```
--------------------------------

DEBUG:BlenderGIS-2210.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:ImageIO Freeimage plugin available
INFO:xmlschema:Resource 'XMLSchema.xsd' is already loaded
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Construction Lines\__init__.py", line 40, in <module>
    from . import construction_lines28
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Construction Lines\construction_lines28.py", line 42, in <module>
    from . import cl_drawing as drw
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Construction Lines\cl_drawing.py", line 70, in <module>
    vert_out = gpu.types.GPUStageInterfaceInfo("cl_shader_interface")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: GPU API is not available in background mode
Processing C:/Users/Ryan Schultz/Desktop/Restaurant_MPM.ifc
Finished opening
Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 1254, in execute
    db = ifcpatch.execute(
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcpatch\__init__.py", line 80, in execute
    patcher.patch()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcpatch\recipes\ExtractPropertiesToSQLite.py", line 153, in patch
    for idx, item in enumerate(material.MaterialConstituents):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 1254, in execute
    db = ifcpatch.execute(
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcpatch\__init__.py", line 80, in execute
    patcher.patch()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcpatch\recipes\ExtractPropertiesToSQLite.py", line 153, in patch
    for idx, item in enumerate(material.MaterialConstituents):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "C:\Users\RYANSC~1\AppData\Local\Temp\tmpqa2bm2ro.py", line 9, in <module>
    run()
  File "C:\Users\RYANSC~1\AppData\Local\Temp\tmpqa2bm2ro.py", line 5, in run
    bpy.ops.bim.load_linked_project(filepath="C:/Users/Ryan Schultz/Desktop/Restaurant_MPM.ifc", false_origin="0,0,0")
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 1254, in execute
    db = ifcpatch.execute(
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcpatch\__init__.py", line 80, in execute
    patcher.patch()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcpatch\recipes\ExtractPropertiesToSQLite.py", line 153, in patch
    for idx, item in enumerate(material.MaterialConstituents):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109

An error occurred while processing your IFC.
Error processing IFC file "C:\Users\Ryan Schultz\Desktop\Restaurant_MPM.ifc" was critical and blend file either wasn't saved or wasn't updated. See logs above in system console for details.

```

**Comment by Moult** [comment]
Note that technically the file has invalid materials (material constituent sets with no materials within them)
