### ISSUE TITLE
Error when extending a wall to a roof

### ISSUE THREAD

**Issue by carlopav** [IfcOpenShell/IfcOpenShell#5273]
You can find the ifc file here. Rename it to ifc.

1    create a wall and a roof over it,
2    select the wall, then the roof
3    press Shift+E.
4    Then the roof and the wall mesh are in edit mode. Press tab to exit. 

ERROR: 

```
`os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
  operator: BIM_OT_override_mode_set_edit
  operator: BIM_OT_override_mode_set_edit
  operator: BIM_OT_load_type_thumbnails
  operator: BIM_OT_load_type_thumbnails
   operator: BIM_OT_load_type_thumbnails
   operator: BIM_OT_load_type_thumbnails
   operator: BIM_OT_hotkey
   operator: BIM_OT_enable_editing_roof_path
   operator: BIM_OT_override_mode_set_object
   operator: BIM_OT_edit_extrusion_profile
last_error: Traceback (most recent call last):
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 406, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1788, in _invoke
    bpy.ops.bim.edit_extrusion_profile()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\slab.py", line 665, in _execute
    if extrusion.Position:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Position'
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.0
originating_system: IfcOpenShell 0.8.0`
```

**Comment by carlopav** [comment]
[error.ifc.txt](https://github.com/user-attachments/files/16828994/error.ifc.txt)
