### ISSUE TITLE
Error when typing distance for polyline wall tool

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5274]
https://github.com/user-attachments/assets/a83f9d2a-261d-4d0d-90f2-b61c9b9306b2

```
Traceback (most recent call last):
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 503, in modal
    is_valid = self.recalculate_inputs(context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 347, in recalculate_inputs
    self.input_panel = PolylineDecorator.calculate_x_y_and_z(context)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/decorator.py", line 505, in calculate_x_y_and_z
    coords = rot_vector * distance + last_point
             ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
AttributeError: Vector addition: (float + Vector) invalid type for this operation
Error: Python: Traceback (most recent call last):
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 503, in modal
    is_valid = self.recalculate_inputs(context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 347, in recalculate_inputs
    self.input_panel = PolylineDecorator.calculate_x_y_and_z(context)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/decorator.py", line 505, in calculate_x_y_and_z
    coords = rot_vector * distance + last_point
             ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
AttributeError: Vector addition: (float + Vector) invalid type for this operation
```

**Comment by aothms** [comment]
Really cool UX though. Great work!
