### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Hauk-Lykke** [IfcOpenShell/IfcOpenShell#5286]
I tried installing on a just downloaded release of blender 4.2.1 LTS via the extensions portal. I got the following error report.

os: Windows
os_version: 10.0.22621
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\HALY\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.1.0_x64__ppwjx1n5r4v9t\Blender\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _ifcopenshell_wrapper: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HALY\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 61, in <module>
    from . import ifcopenshell_wrapper
  File "C:\Users\HALY\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 17, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HALY\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_ifcopenshell_wrapper')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.1.0_x64__ppwjx1n5r4v9t\Blender\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HALY\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\bonsai\__init__.py", line 225, in <module>
    import ifcopenshell.api
  File "C:\Users\HALY\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 69, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.11'

binary_file_name: _ifcopenshell_wrapper.cp311-win_amd64.pyd
binary_python_version: 3.11

Edit:
I tried downloading from the Bonsai website directly instead, then I got this:

![bilde](https://github.com/user-attachments/assets/c788cf70-f87c-45ff-abd7-8242c687926c)

**Comment by Moult** [comment]
It looks like you've perhaps migrated settings from an older version of Blender to 4.2. Can you please try with a fresh install? You can also delete `C:\Users\HALY\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blenderbim` manually.

**Comment by Hauk-Lykke** [comment]
Removing old junk did the trick, thank you! :-) Perhaps an error message stating just that would be nice?

**Comment by Moult** [comment]
There are lots of possible old sources we can't catch :)
