### ISSUE TITLE
error after `shift and click `bim.activate_drawing``

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5290]
Steps to reproduce...
1. open this file: https://hub.openingdesign.com/OpeningDesign/Restaurant_MPM/src/commit/15212c01d74a74099d3cb870402363910bdde2a9/Open/Models/BlenderBIM/Restaurant_MPM.ifc
2. select `SECTION - WEST - OVEN and RANGE` and hold shift and click `bim.activate_drawing`
3. then just click `bim.activate_drawing`

`4.2.1 Bonsai I-alpha240903-3675429`

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1800, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1815, in execute
    core.activate_drawing_view(tool.Ifc, tool.Blender, tool.Drawing, drawing=drawing)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\drawing.py", line 494, in activate_drawing_view
    drawing_tool.activate_drawing(camera)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 1837, in activate_drawing
    current_representation = tool.Geometry.get_active_representation(obj)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 363, in get_active_representation
    if obj.data and hasattr(obj.data, "BIMMeshProperties") and obj.data.BIMMeshProperties.ifc_definition_id:
       ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by Moult** [comment]
This fix looks suspicious. I'm reopening the bug to investigate.
