### ISSUE TITLE
Error: Object 'IfcSpace/0-2' can't be hidden because it is not in View Layer 'ViewLayer'!

### ISSUE THREAD

**Issue by JuantLB** [IfcOpenShell/IfcOpenShell#5309]
```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 11, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.8.1-alpha240904
bonsai_commit_hash: e1a5e73
last_actions: 
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_spatial_hotkey
# operator: BIM_OT_spatial_hotkey
# operator: BIM_OT_spatial_hotkey
last_error: Traceback (most recent call last):
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\spatial\workspace.py", line 138, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\spatial\workspace.py", line 178, in hotkey_S_H
    bpy.ops.bim.toggle_hide_spaces()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\space.py", line 112, in execute
    core.toggle_hide_spaces(tool.Ifc, tool.Spatial)
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\spatial.py", line 238, in toggle_hide_spaces
    spatial.toggle_hide_spaces(spaces)
  File "C:\Users\lesto\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 1119, in toggle_hide_spaces
    obj.hide_set(True)
RuntimeError: Error: Object 'IfcSpace/0-2' can't be hidden because it is not in View Layer 'ViewLayer'!
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: FM_ARC_DigitalHub_v1.ifc
schema: IFC4
preprocessor_version: The EXPRESS Data Manager Version 5.02.0100.07 : 28 Aug 2013
originating_system: 20190108_1515(x64) - Exporter 19.3.0.0 - Alternative Benutzeroberfläche 19.3.0.0
```

**Comment by falken10vdl** [comment]
@JuantLB could you please describe a little bit the context in which this error has happened. Is this still the case in layest Bonsai build?
