### ISSUE TITLE
Choose wall reference line (exterior, interior, center) for polyline tool

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#5326]

**Comment by theoryshaw** [comment]
Nice, would it make sense to use IfcMaterialLayerSetUsage's `OffsetFromReferenceLine` attribute, here?

**Comment by brunoperdigao** [comment]
I started to implement this, and I would like to confirm if this is the correct approach.
It basically changes the behavior of two attributes of the material layer set usage:
- Direction sense, which can be Positive or Negative. Basically, it tells to which direction of the axis the material layers will be created.
- Offset from reference line, which is the distance from the axis where the material layers should be created.
Those can be found here: https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcMaterialLayerSetUsage.htm

Based on the offset, I created a convention called `offset_type` with the values "exterior", "center", and "interior". This kind of setting is present in other software and might be useful to the users. Basically, what it does is to set the offset value based on the wall thickness. So, "center" means half a thickness, and "interior" means offset the whole thickness. This might also be useful for future implementation of the concepts of "core" and "finish" that it's also present in other software.

Here's a demo. You can see the values changing in the status bar below. The thicker part of the wall is the exterior:
![Image](https://github.com/user-attachments/assets/12563c45-fdf5-46c0-9317-5219ad7633a1)

**Comment by Moult** [comment]
This looks fantastic!

**Comment by brunoperdigao** [comment]
This is implemented here: b9c6508aa727684a149bc5fed89bf901e50e11da

**Comment by Moult** [comment]
I managed to trigger this:

```
Error: Python: Traceback (most recent call last):
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 386, in modal
    self.create_walls_from_polyline(context)
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 331, in create_walls_from_polyline
    DumbWallJoiner().join_V(wall2["obj"], wall1["obj"])
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 1185, in join_V
    self.recreate_wall(element2, wall2, axis2["reference"], axis2["reference"])
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 1203, in recreate_wall
    self.join(
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 1372, in join
    angle = tool.Cad.angle_edges(axis1["reference"], axis2["reference"], signed=True, degrees=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/cad.py", line 82, in angle_edges
    a = (edge1[1] - edge1[0]).angle_signed(edge2[1] - edge2[0])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Vector.angle_signed(other): zero length vectors have no valid angle
```

**Comment by Moult** [comment]
Also found this: draw two lines, press F, then press O, then RMB:


https://github.com/user-attachments/assets/cb20a9b2-972b-4a15-a5c9-3af4cfb42bf7

**Comment by theoryshaw** [comment]
what's the quick key for switching directionsense?

**Comment by brunoperdigao** [comment]
> Also found this: draw two lines, press F, then press O, then RMB:
> 2024-10-16.12-32-20.mp4

Maybe this is a different issue? I was able to reproduce like this:
-  Create two independent walls with the default config and type WAL300.
-  Change in Object Materials panel, individually for each wall, the direction sense to negative and the offset to -300.
- Then select the walls and shift+Y to join them.

**Comment by brunoperdigao** [comment]
At a first glance, I think the join V doesn't work with negative direction sense. It works when you `shift+F` to flip the wall after they are created, because `shift+F` doesn't change the direction sense, if I'm not mistaken. It just flips the start and the end of the axis.
I'll further investigate this latter. Both issues might be related to this.

**Comment by theoryshaw** [comment]
related perhaps: https://github.com/IfcOpenShell/IfcOpenShell/issues/6561
