### ISSUE TITLE
Error trying to attach 'space-tag' to ifcspace via 'bulk-tag':

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5350]
test file: 
[space tag.ifc.txt](https://github.com/user-attachments/files/16922612/space.tag.ifc.txt)

https://github.com/user-attachments/assets/1bbaa120-4f5e-459c-9b13-0350a78c49d2

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.0.0
bonsai_commit_hash: 83be26e
last_actions: 
# ifcopenshell.api: owner.create_owner_history
>>> {}
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 24, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/MY STOREY PLAN\") at 0x000002AC00845608>", "geometry": "<bpy_struct, Camera(\"24/1267\") at 0x000002ABF66CB108>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 1294, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1257, "Name": "MY STOREY PLAN"}, "representation": {"cast_type": "entity_instance", "value": 1267, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 1267, "Name": null}}
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 24, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/MY STOREY PLAN\") at 0x000002AC00845608>", "geometry": "<bpy_struct, Camera(\"24/1294\") at 0x000002ABF66CB108>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 1299, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1257, "Name": "MY STOREY PLAN"}, "representation": {"cast_type": "entity_instance", "value": 1294, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 1294, "Name": null}}
# operator: BIM_OT_annotation_hotkey
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcAnnotation", "predefined_type": "TEXT", "name": "SPACE-TAG"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: type.assign_type
>>> {"related_objects": [{"cast_type": "entity_instance", "value": 1316, "Name": "SPACE-TAG"}], "relating_type": {"cast_type": "entity_instance", "value": 206, "Name": "SPACE-TAG"}}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: type.map_type_representations
>>> {"related_object": {"cast_type": "entity_instance", "value": 1316, "Name": "SPACE-TAG"}, "relating_type": {"cast_type": "entity_instance", "value": 206, "Name": "SPACE-TAG"}}
# ifcopenshell.api: geometry.map_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 204, "Name": null}}
# ifcopenshell.api: geometry.assign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1316, "Name": "SPACE-TAG"}, "representation": {"cast_type": "entity_instance", "value": 1324, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1316, "Name": "SPACE-TAG"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 278, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 298, in hotkey_S_T
    create_annotation()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 184, in create_annotation
    create_annotation_occurrence(bpy.context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 171, in create_annotation_occurrence
    bonsai.core.type.assign_type(tool.Ifc, tool.Type, element=element, type=relating_type)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\type.py", line 39, in assign_type
    type_tool.change_object_data(obj, type_data, is_global=False)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\type.py", line 33, in change_object_data
    tool.Geometry.change_object_data(obj, data, is_global)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 55, in change_object_data
    obj.data = data
    ^^^^^^^^
TypeError: bpy_struct: item.attr = val: Object.data expected a Image type, not Mesh

ifc: space tag.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.0.0
originating_system: Bonsai 0.8.1-alpha240905-83be26e
```

**Comment by theoryshaw** [comment]
for what it's worth.  AI's fix...
And it seems to work.

```
    def change_object_data(cls, obj: bpy.types.Object, data: bpy.types.ID, is_global: bool = False) -> None:
        # Check if obj.data is None and handle accordingly
        if obj.data is None:
            print(f"Warning: {obj.name} has no initial data. Skipping data assignment.")
            return

        # Check if obj.data is compatible with the new data type
        if isinstance(obj.data, bpy.types.Mesh) and isinstance(data, bpy.types.Mesh):
            if is_global:
                cls.replace_object_data_globally(obj.data, data)
            else:
                obj.data = data
                print(f"Assigning data to object: {obj.name}")
                print(f"Current obj.data type: {type(obj.data)}, New data type: {type(data)}")
        else:
            raise TypeError(f"Incompatible data types: {type(obj.data)} expected, but got {type(data)}")
```
