### ISSUE TITLE
Bonsai error viewing Material Property Sets

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#5351]
If I select a material in Scene > Geometry and Materials > Materials, and select Material Property Sets, eg. the material in this attached file: [one-material.ifc.txt](https://github.com/user-attachments/files/16923695/one-material.ifc.txt)

I see this error:

```
Traceback (most recent call last):
  File "/usr/share/blender/4.0/scripts/addons/bonsai/bim/module/pset/ui.py", line 382, in draw
    MaterialPsetsData.load()
  File "/usr/share/blender/4.0/scripts/addons/bonsai/bim/module/pset/data.py", line 172, in load
    "psets": cls.psetqtos(tool.Ifc.get().by_id(ifc_definition_id)),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.0/scripts/addons/bonsai/bim/module/pset/data.py", line 57, in psetqtos
    pset_uses = ifcopenshell.util.element.get_elements_by_pset(pset)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/ifcopenshell/util/element.py", line 448, in get_elements_by_pset
    rels = pset.PropertyDefinitionOf if is_ifc2x3 else pset.DefinesOccurrence
                                                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/ifcopenshell/entity_instance.py", line 238, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcMaterialProperties' has no attribute 'DefinesOccurrence'
```

**Comment by Andrej730** [comment]
Fixed in e224bfd19f

**Comment by brunopostle** [comment]
Oops should have updated first

**Comment by brunopostle** [comment]
Spoke too soon, now I see this error (windows 0.8.1-alpha240909, I've removed and reinstalled Bonsai to be sure)

Traceback (most recent call last):
  File "C:\Users\bruno.postle.DRIVER\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\pset\ui.py", line 382, in draw
    MaterialPsetsData.load()
  File "C:\Users\bruno.postle.DRIVER\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\pset\data.py", line 173, in load
    "pset_name": cls.pset_name(),
                 ^^^^^^^^^^^^^^^
  File "C:\Users\bruno.postle.DRIVER\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\pset\data.py", line 185, in pset_name
    psets = bonsai.bim.schema.ifc.psetqto.get_applicable("IfcMaterial", category, pset_only=True)
            ^^^^^^^^^^^^^^^^^
AttributeError: module 'bonsai.bim' has no attribute 'schema'

**Comment by Andrej730** [comment]
> Spoke too soon, now I see this error (windows 0.8.1-alpha240909, I've removed and reinstalled Bonsai to be sure)

Couldn't reproduce this. Are there any other errors? 
Kind of confusing since if the import below succeeds there shouldn't be this error.
https://github.com/IfcOpenShell/IfcOpenShell/blob/680c73f15bf9b0ee96b97454b5954dc1c175a1f8/src/bonsai/bonsai/bim/module/pset/data.py#L24

@Moult can you please try to reproduce this?

**Comment by brunopostle** [comment]
Tried again and now working. There has been a Bonsai update since I tried this morning, but it doesn't look like this is the problem.

What I did both times: disable Bonsai, restart blender, remove Bonsai, restart blender, install Bonsai from the bottom of the Extensions list (the one at the top of the list is the one from the official Extension site).
