### ISSUE TITLE
Error when loading model

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5353]
I use the latest build, did not see this before, only with this model that I cannot share ofc.

```
text_color = <Color (r=0.1020, g=0.1020, b=0.1020)>
background_color = <bpy_float[4], ThemeWidgetColors.outline>
Starting import process :: 0.00
Loading file :: 0.00
Calculate unit scale :: 0.00
Process context filter :: 0.00
Calculate model offset :: 0.00
Predict dense mesh :: 0.00
Set units :: 0.00
Create project :: 0.01
Process element filter :: 0.00
Create styles :: 0.00
Parsing native elements :: 0.00
Done creating geometry
Create native elements :: 0.00
Done creating geometry
Create elements :: 8.19
Create annotations :: 0.00
Create positioning elements :: 0.00
0 / 9 elements processed ...
Create spatial elements :: 0.01
Create structural items :: 0.00
Create element types :: 0.00
Place objects in collections :: 0.01
Add project to scene :: 0.00
Setting default context :: 0.03
Setup arrays :: 0.01
Import finished in 8.30 seconds
Starting import process :: 0.00
Loading file :: 0.00
Calculate unit scale :: 0.00
Process context filter :: 0.00
Calculate model offset :: 0.00
Predict dense mesh :: 0.00
Set units :: 0.00
Create project :: 0.00
Process element filter :: 0.00
Create styles :: 0.00
Parsing native elements :: 0.02
Done creating geometry
Create native elements :: 0.00
Done creating geometry
Create elements :: 0.09
Create annotations :: 0.00
Create positioning elements :: 0.00
0 / 73 elements processed ...
Create spatial elements :: 0.07
Create structural items :: 0.00
Create element types :: 0.00
Place objects in collections :: 0.02
Add project to scene :: 0.00
Setting default context :: 0.03
Setup arrays :: 0.02
Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 812, in execute
    ifc_importer.execute()
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 272, in execute
    tool.Spatial.run_spatial_import_spatial_decomposition()
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 127, in run_spatial_import_spatial_decomposition
    return bonsai.core.spatial.import_spatial_decomposition(tool.Spatial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\spatial.py", line 119, in import_spatial_decomposition
    spatial.import_spatial_decomposition()
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 436, in import_spatial_decomposition
    cls.import_spatial_element(tool.Ifc.get().by_type("IfcProject")[0], 0)
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 463, in import_spatial_element
    cls.import_spatial_element(child, level_index + 1)
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 463, in import_spatial_element
    cls.import_spatial_element(child, level_index + 1)
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 458, in import_spatial_element
    children = sorted(children, key=dict(zip(children, tuple(zip(children_elevations, children_names)))).get)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
Error: Python: Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 812, in execute
    ifc_importer.execute()
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 272, in execute
    tool.Spatial.run_spatial_import_spatial_decomposition()
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 127, in run_spatial_import_spatial_decomposition
    return bonsai.core.spatial.import_spatial_decomposition(tool.Spatial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\spatial.py", line 119, in import_spatial_deError in bpy.app.handlers.load_post[7]:
Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 700, in load_handler
    self.finish_loading_project(context)
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 731, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 812, in execute
    ifc_importer.execute()
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 272, in execute
    tool.Spatial.run_spatial_import_spatial_decomposition()
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 127, in run_spatial_import_spatial_decomposition
    return bonsai.core.spatial.import_spatial_decomposition(tool.Spatial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\spatial.py", line 119, in import_spatial_decomposition
    spatial.import_spatial_decomposition()
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 436, in import_spatial_decomposition
    cls.import_spatial_element(tool.Ifc.get().by_type("IfcProject")[0], 0)
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 463, in import_spatial_element
    cls.import_spatial_element(child, level_index + 1)
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 463, in import_spatial_element
    cls.import_spatial_element(child, level_index + 1)
  File "C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 458, in import_spatial_element
    children = sorted(children, key=dict(zip(children, tuple(zip(children_elevations, children_names)))).get)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109

```

**Comment by Moult** [comment]
@manuvarkey can you take a look at this one?

**Comment by manuvarkey** [comment]
@Moult #5354 pull request raised to resolve issue
