### ISSUE TITLE
"Shift+L" clone openings for walls seemingly not available for IfcCovering elements

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5384]
as shown in @theoryshaw 's [video](https://www.dropbox.com/scl/fi/dvuijbsd7daywo0yqac7d/2024-02-15_06-21-48_blenderBlenderblender.mp4?rlkey=r8hchj11arvg20vwboh6f3lpr&dl=0) (2nd option at 0:45), there is a nice feature to clone an existing opening to be applied on another wall next to it.

the sequence in the video is
1. select the wall with the opening, press `Alt`+`O` to show it
2. select the adjacent wall **and** the opening
3. on the `N` menu > Tool a `Shift` + `L`  'Clone Opening' becomes available
4. click it to have a cloned (same size and location) opening on the other wall

unfortunately when I use it with an IfcCovering (which should probably be the most common usage) the `Shift`+`L` generates an error:

![image](https://github.com/user-attachments/assets/fa0c48b9-00ef-4485-b9bb-d2752d2e837c)

not such a big deal, the workaround is to just press `Shift`+`D` and snap the new opening in the same place, but I thought the 'clone' feature is kind of cool to have available for coverings too

thanks

**Comment by Ave-5D** [comment]
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.8.1-alpha240911
bonsai_commit_hash: 9be392e
last_actions: 
# ifcopenshell.api: void.add_opening
>>> {"opening": {"cast_type": "entity_instance", "value": 32333, "Name": "Opening"}, "element": {"cast_type": "entity_instance", "value": 33057, "Name": "25mm Plaster"}}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 32333, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[-0.9999999999999886, -1.5099580252808492e-07, 0.0, 6868.99995803833], [1.509958025280849e-07, -0.9999999999999887, 0.0, 5034.170150756836], [0.0, 0.0, 1.0, -4.999876022338867], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 32333, "Name": "Opening"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 32284, "Name": "SD 2100x1500"}}
# ifcopenshell.api: void.add_opening
>>> {"opening": {"cast_type": "entity_instance", "value": 32418, "Name": "Opening"}, "element": {"cast_type": "entity_instance", "value": 33057, "Name": "25mm Plaster"}}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 32418, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[-0.9999999999999886, -1.5099580252808492e-07, 0.0, 3079.000949859619], [1.509958025280849e-07, -0.9999999999999887, 0.0, 5034.170627593994], [0.0, 0.0, 1.0, -4.999876022338867], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 32418, "Name": "Opening"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 32371, "Name": "SD 2100x1500.001"}}
# operator: BIM_OT_override_object_duplicate_move
# ifcopenshell.api: root.copy_class
>>> {"product": {"cast_type": "entity_instance", "value": 33773, "Name": "Opening"}}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 33867, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: root.copy_class
>>> {"product": {"cast_type": "entity_instance", "value": 33803, "Name": "Opening"}}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 33897, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# operator: BIM_OT_edit_openings
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 33859, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[-1.0, -1.5099580252808664e-07, 0.0, 6.866031646728516], [1.5099580252808664e-07, -1.0, 0.0, 5.054913520812988], [0.0, 0.0, 1.0, -0.04750891029834747], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 33859, "Name": "Opening"}}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 33889, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[-1.0, -1.5099580252808664e-07, 0.0, 3.0760326385498047], [1.5099580252808664e-07, -1.0, 0.0, 5.0549139976501465], [0.0, 0.0, 1.0, -0.04750891029834747], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 33889, "Name": "Opening"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\opening.py", line 794, in _execute
    element = tool.Ifc.get_entity(obj)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\ifc.py", line 103, in get_entity
    props = obj.BIMObjectProperties
            ^^^^^^^^^^^^^^^^^^^^^^^
ReferenceError: StructRNA of type Object has been removed

ifc: 1bd240911.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha240911
originating_system: Bonsai 0.8.1-alpha240911-9be392e
```
Hi attached is my Ifc file, this is the error I got when trying to create openings usinf Shift D, for some reason when I add a new door or window and apply the opening it turns 180'. I tried the Aggregate method but it also got errors,
[1bd240911.txt](https://github.com/user-attachments/files/17019344/1bd240911.txt)

**Comment by steverugi** [comment]
@Ave-5D 
first thing first: you have double openings on your wall:

1. select the wall tool on the T (left side) menu
2. select the wall
3. select the Tool tab on the N (right side menu
4. click on Opening (Alt + O) to visualize them
5. open the panel in Geometry and Materials > Geometric Relationship > Voids to view the list (there are 4 but only 2 are needed)

![image](https://github.com/user-attachments/assets/938cbca6-7eba-4dc2-927d-9a86ecb2e6cb)

or just look at the Outliner panel, you find them too

![image](https://github.com/user-attachments/assets/38f6e492-4ee5-46cd-94bf-c71e8e406168)


the sequence to apply openings on your internal covering to have the following

![image](https://github.com/user-attachments/assets/3fec6f42-8bdb-4513-be2a-99eb72f78104)

are:

1. select the wall with the openings (delete the two in excess first)
2. click Alt+O or select the same from the N menu as indicated above to show the opening geometries

![image](https://github.com/user-attachments/assets/a86430cf-8d0b-4646-ab9e-40b6c3f5cc42)

3. select the two openings (they become light green)
4. press Shift+D to duplicate and snap them into the same position (use Ctrl key or activate snap vertex to help you)
5. with the duplicated opening selected hold the shift key and select the covering inside
6. go to the N panel (wall tool selected) look for the 'Apply Opening' icon and click it 

hope it helps

**Comment by Ave-5D** [comment]
Thanks Steverugi, once agian I learnt more about Blender and Bonsia, I tried your work around with Shift +D and this happened
![Skermskoot (186)](https://github.com/user-attachments/assets/1ed1aef0-7609-44fa-8c7f-c9a3dd1ba28f)
[1bd240918 Shift D.txt](https://github.com/user-attachments/files/17040836/1bd240918.Shift.D.txt)

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.8.1-alpha240917
bonsai_commit_hash: 53a6192
last_actions: 
# ifcopenshell.api: root.copy_class
>>> {"product": {"cast_type": "entity_instance", "value": 33803, "Name": "Opening"}}
# ifcopenshell.api: root.copy_class
>>> {"product": {"cast_type": "entity_instance", "value": 33773, "Name": "Opening"}}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 34074, "Name": null}, "styles": [{"cast_type": "entity_instance", "value": 126, "Name": "Red Clay"}], "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: root.copy_class
>>> {"product": {"cast_type": "entity_instance", "value": 33803, "Name": "Opening"}}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 34093, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: root.copy_class
>>> {"product": {"cast_type": "entity_instance", "value": 33773, "Name": "Opening"}}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 34123, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# operator: BIM_OT_add_opening
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcOpeningElement", "predefined_type": "OPENING", "name": "Opening"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 34146, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 7.928999423980713], [0.0, 1.0, 0.0, 4.802646636962891], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "True"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 34146, "Name": "Opening"}}
# operator: BIM_OT_add_opening
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcOpeningElement", "predefined_type": "OPENING", "name": "Opening"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 34153, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 7.928999423980713], [0.0, 1.0, 0.0, 4.802646636962891], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "True"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 34153, "Name": "Opening"}}
# operator: BIM_OT_save_project
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 33057, "Name": "25mm Plaster"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 7.928999423980713], [0.0, 1.0, 0.0, 4.802646636962891], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 33057, "Name": "25mm Plaster"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\void\operator.py", line 68, in _execute
    FilledOpeningGenerator().generate(obj2, obj1, target=obj2.matrix_world.translation)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\opening.py", line 152, in generate
    representation = self.generate_opening_from_filling(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\opening.py", line 339, in generate_opening_from_filling
    shape_builder.rectangle(size=opening_size),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\shape_builder.py", line 219, in rectangle
    return self.polyline(self.get_rectangle_coords(size, position), closed=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\shape_builder.py", line 198, in get_rectangle_coords
    position + size * id_matrix[non_empty_coords[0]],
                                ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

ifc: 1bd240911.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha240917
originating_system: Bonsai 0.8.1-alpha240917-53a6192
```

Attached is the error code and the file when I tried the "Aggregate" way.
![Skermskoot (185)](https://github.com/user-attachments/assets/0f304950-b566-46f6-9664-6fe78aded7d3)
[1bd240918.txt](https://github.com/user-attachments/files/17040636/1bd240918.txt)
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.8.1-alpha240917
bonsai_commit_hash: 53a6192
last_actions: 
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 33618, "Name": "2 coats PVA Paint"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 33057, "Name": "25mm Plaster"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 11200, "Name": "SD 2100x1500"}], "relating_object": {"cast_type": "entity_instance", "value": 34000, "Name": "South Wall"}}
# ifcopenshell.api: spatial.unassign_container
>>> {"products": [{"cast_type": "entity_instance", "value": 11200, "Name": "SD 2100x1500"}]}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 10624, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 34012, "Name": null}}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 11200, "Name": "SD 2100x1500"}, "matrix": {"cast_type": "ndarray", "value": [[-0.9999999999999886, -1.5099580252808495e-07, 0.0, 8149.00207519531], [1.5099580252808492e-07, -0.9999999999999887, 0.0, 5034.16967391968], [0.0, 0.0, 1.0, 2325.00028610229], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 11200, "Name": "SD 2100x1500"}}
# operator: BIM_OT_hotkey
# operator: BIM_OT_show_openings
# operator: BIM_OT_add_opening
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcOpeningElement", "predefined_type": "OPENING", "name": "Opening"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 34054, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[-1.0, -1.5099580252808664e-07, 0.0, 0.4444751739501953], [1.5099580252808664e-07, -1.0, 0.0, 5.034170627593994], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "True"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 34054, "Name": "Opening"}}
# operator: BIM_OT_add_opening
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcOpeningElement", "predefined_type": "OPENING", "name": "Opening"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 34061, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[-1.0, -1.5099580252808664e-07, 0.0, 0.4444751739501953], [1.5099580252808664e-07, -1.0, 0.0, 5.034170627593994], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "True"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 34061, "Name": "Opening"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\void\operator.py", line 68, in _execute
    FilledOpeningGenerator().generate(obj2, obj1, target=obj2.matrix_world.translation)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\opening.py", line 152, in generate
    representation = self.generate_opening_from_filling(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\opening.py", line 339, in generate_opening_from_filling
    shape_builder.rectangle(size=opening_size),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\shape_builder.py", line 219, in rectangle
    return self.polyline(self.get_rectangle_coords(size, position), closed=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\shape_builder.py", line 198, in get_rectangle_coords
    position + size * id_matrix[non_empty_coords[0]],
                                ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

ifc: 1bd240911.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha240917
originating_system: Bonsai 0.8.1-alpha240917-53a6192
```

I hope this info helps, and once agian thanks for all the efforts \0/

**Comment by steverugi** [comment]
unfortunately (for me) the error log doesn't mean much
but I noticed you still have 4 openings open

![image](https://github.com/user-attachments/assets/f75d49bd-bd77-443a-b02d-8f40ab798cb3)

I used your own model to show my previous post and the sequence therein indicated, all went well on my end, but you need to follow the steps to avoid error
or there might be something else of which I am not aware

**Comment by Ave-5D** [comment]
I used Shift+D (which creates the two additional openings) the only thing I did not do was the positioning, I did Shift+G+Z and kept the Z value as 0. 

I don’t know but I have a knack to create error messages :-/

Thanks, I will keep on trying maybe it is because I wanted to create the opening for two elements (IfcCoverType-25mm Plaster and IfcCoverType-Paint) in one action.

Thanks for your help.

**Comment by steverugi** [comment]
I think each element (unless you use aggregate) has to have its own opening
to be honest it's hard to decide which is the best procedure

I for instance do not particularly like the aggregate 

but maybe it is the appropriate method when multiple elements need to share the same opening, plus you have a solid advantage to handle repositioning of openings in one go

again
1. select the element with opening(s)
2. Alt+O to show them
3. select the shown openings, they become light green color
4. Shift+D to duplicate
5. snap the duplicates on the original ones to keep their position
6. with the duplicates still selected hold Shift and select the covering
7. apply opening
happy modeling

**Comment by Moult** [comment]
> I don’t know but I have a knack to create error messages :-/

Would it be worthwhile doing a screen recording or screenshare to see how you're using Bonsai? That would really help us figure out if you're doing something that is causing this many errors.

**Comment by Ave-5D** [comment]
Hi Dion, once agian thanks for your efforts.

It looks like to one error is when I don’t deselect the element after Shif+D (This only happens if there are two openings in an element) When I deselected the element with the existing openings and then applied the copied openings to one element it worked.

This is what happens when I want to apply the opening to two elements at once.
I tried to make a screen recording hope it works
![blender_FzGxAi5wGg](https://github.com/user-attachments/assets/5ffb8789-3288-413a-bdf3-99fdc5a10dbd)
[1bd240918 Shift D.txt](https://github.com/user-attachments/files/17049692/1bd240918.Shift.D.txt)


```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.8.1-alpha240917
bonsai_commit_hash: 53a6192
last_actions: 
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 34233, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[-0.9999999999999886, -1.5099580252808492e-07, 0.0, 3079.00094985962], [1.509958025280849e-07, -0.9999999999999887, 0.0, 5034.170627593994], [0.0, 0.0, 1.0, -4.99987602233887], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 34233, "Name": "Opening"}}
# operator: BIM_OT_edit_openings
# operator: BIM_OT_save_project
# operator: BIM_OT_save_project
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_save_project
# operator: BIM_OT_save_project
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_hotkey
# operator: BIM_OT_show_openings
# operator: BIM_OT_override_object_duplicate_move
# ifcopenshell.api: root.copy_class
>>> {"product": {"cast_type": "entity_instance", "value": 32593, "Name": "Opening"}}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 34287, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# operator: BIM_OT_add_opening
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcOpeningElement", "predefined_type": "OPENING", "name": "Opening"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 34310, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[-1.0, -1.5099580252808664e-07, 0.0, 0.4444746971130371], [1.5099580252808664e-07, -1.0, 0.0, 1.1274571418762207], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "True"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 34310, "Name": "Opening"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\void\operator.py", line 68, in _execute
    FilledOpeningGenerator().generate(obj2, obj1, target=obj2.matrix_world.translation)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\opening.py", line 152, in generate
    representation = self.generate_opening_from_filling(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\opening.py", line 339, in generate_opening_from_filling
    shape_builder.rectangle(size=opening_size),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\shape_builder.py", line 219, in rectangle
    return self.polyline(self.get_rectangle_coords(size, position), closed=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\shape_builder.py", line 198, in get_rectangle_coords
    position + size * id_matrix[non_empty_coords[0]],
                                ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range, 

ifc: 1bd240918.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha240917
originating_system: Bonsai 0.8.1-alpha240917-53a6192
```

**Comment by theoryshaw** [comment]
@Ave-5D 
This is my preferred way to apply an opening across multiple things.
That is, put all the wall layers in an aggregate, and then apply the opening to the aggregate...


https://github.com/user-attachments/assets/be4efd8d-b88e-4c33-9ed2-548a83bdcc8b

**Comment by Ave-5D** [comment]
Thanks for the video watched it a 100 times before I got it right. Kept on using the "Tick" botton.

![msedge_dEk1UrpSfs](https://github.com/user-attachments/assets/6dfe5690-6ff3-4d46-83cb-8855e8366645)

**Comment by steverugi** [comment]
Hi @theoryshaw 
> @Ave-5D This is my preferred way to apply an opening across multiple things. That is, put all the wall layers in an aggregate, and then apply the opening to the aggregate...
> 
could you be so kind to list the steps? I can't reproduce what you did in the video and it's driving me nuts

thanks

**Comment by theoryshaw** [comment]
Yes, those steps look correct to me. 

...

> what do you do at the beginning of the video? why 2 openings are showing and is it necessary to move the door?

for whatever reason you had (2) voids in that type, i just deleted the extraneous one when i started.

**Comment by falken10vdl** [comment]
@steverugi is the original error described at the beginning for cloning void in IfcCivering still happening?
Thanks!
