### ISSUE TITLE
Bonsai - Failed to process shape

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#5388]
After opening a pre-Bonsai .ifc I am getting the following error when activating a drawing. Gemoetry fails to be displayed in the viewport.

Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 612, in import_representation
    shape = ifcopenshell.geom.create_shape(settings, element, representation)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\geom\main.py", line 411, in create_shape
    ifcopenshell_wrapper.create_shape(
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 6075, in create_shape
    return _ifcopenshell_wrapper.create_shape(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to process shape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 615, in import_representation
    shape = ifcopenshell.geom.create_shape(settings, element, representation)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\geom\main.py", line 411, in create_shape
    ifcopenshell_wrapper.create_shape(
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 6075, in create_shape
    return _ifcopenshell_wrapper.create_shape(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to process shape

**Comment by Andrej730** [comment]
@ChubbyQuark hi! can you please share example .ifc file to reproduce the issue?

**Comment by Moult** [comment]
Closing due to inactivity, if you have teh file please reopen :)
