### ISSUE TITLE
Unexpected error when trying to start a project 

### ISSUE THREAD

**Issue by ElPeregrino10** [IfcOpenShell/IfcOpenShell#5389]
Using this add-on I get a lot of crashes, been suspecting that maybe is because of my device. This error appear when trying to make a wall from a poly line, then i tried to add a wall with shift + A and now I can't even do that.
Sorry if this is not a good bug report, is my first time reporting a bug.

```
os: Windows
os_version: 10.0.19041
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
blender_version: 4.2.1 LTS
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
# operator: BIM_OT_add_default_type
# operator: BIM_OT_add_type
last_error: Traceback (most recent call last):
  File "C:\Users\minar\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minar\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\product.py", line 117, in _execute
    bpy.ops.bim.add_type()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: No Model/Body/MODEL_VIEW context found.


ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.0
originating_system: IfcOpenShell 0.8.0
```

**Comment by Andrej730** [comment]
> Using this add-on I get a lot of crashes, been suspecting that maybe is because of my device.

Please report them, crashes are critical.


> This error appear when trying to make a wall from a poly line, then i tried to add a wall with shift + A and now I can't even do that.

You started new project in Bonsai or loaded some other project (probably the latter)? If this some other project - is it some customly generated IFC or it's coming exported from some software (would be nice to know what software has that issue with missing contexts)? 

There are some contexts that are generally available in IFC projects and Bonsai relies on them - you can add them in geometry contexts section.

![image](https://github.com/user-attachments/assets/bca0ef4b-7649-424f-8543-dc2c4a6a9c99)

Default contexts available in Bonsai project (might encounter similar errors later on if your project doesn't have them):
![image](https://github.com/user-attachments/assets/55997f7d-17ae-4dc5-a28d-d51dc9f4aeb8)
