### ISSUE TITLE
Error when i try `bim.append_inspected_linked_element()`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5415]
After linking the following file, I get the following error when i try `bim.append_inspected_linked_element()`

file: https://hub.openingdesign.com/OpeningDesign/OD_Library/src/commit/79aaab76ddf99fb97583f2b2e5430d77ef533813/BIM/OD_Revit_Template%20-%202024%20-%20IFC4%20Reference%20ARCH.ifc

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.8.1-alpha240911
bonsai_commit_hash: f5e02d1
last_actions: 
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 46, "Name": "My Building"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 46, "Name": "My Building"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 52, "Name": "My Storey"}], "relating_object": {"cast_type": "entity_instance", "value": 46, "Name": "My Building"}}
# ifcopenshell.api: spatial.unassign_container
>>> {"products": "[]"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 52, "Name": "My Storey"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 52, "Name": "My Storey"}}
# operator: BIM_OT_save_project
# operator: BIM_OT_append_inspected_linked_element
# ifcopenshell.api: project.append_asset
>>> {"library": "<ifcopenshell.file.file object at 0x0000024E976CA050>", "element": {"cast_type": "entity_instance", "value": 1259, "Name": "Window"}}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 180, "Name": "Window"}}
# ifcopenshell.api: project.append_asset
>>> {"library": "<ifcopenshell.file.file object at 0x0000024E976CA050>", "element": {"cast_type": "entity_instance", "value": 469, "Name": "WT01"}, "reuse_identities": "{676020: #181=IfcStyledItem(#133,(#184),'Frame'), 676024: #185=IfcStyledItem(#140,(#188),'Glass')}"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# operator: BIM_OT_save_project
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_append_inspected_linked_element
# operator: BIM_OT_append_inspected_linked_element
# operator: BIM_OT_append_inspected_linked_element
last_error: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 1858, in _execute
    ifc_file = ifcopenshell.open(queried_obj["ifc_filepath"])
                                 ~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'bpy_struct[key]: key "ifc_filepath" not found'

ifc: file doing the referencing.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha240911
originating_system: Bonsai 0.8.1-alpha240911-f5e02d1
```

**Comment by theoryshaw** [comment]
I get this error on some content, but not with others...

https://github.com/user-attachments/assets/139abdf9-7802-4a05-afc3-6b84d5a898bb

**Comment by theoryshaw** [comment]
I still get this error, unfortunately.

**Comment by Andrej730** [comment]
@theoryshaw 
1) same file, same element, same error?
2) are you sure you deleted the cache from previous attempts? (need to remove all .cache files next to the .ifc)
3) can you please try to append the same element from this file, does it fail too?
[link_fail.ifc.txt](https://github.com/user-attachments/files/17373528/link_fail.ifc.txt)
