### ISSUE TITLE
KeyError when importing PowerProject 16.0.02 file. Bonsai 0.8.0 13-08

### ISSUE THREAD

**Issue by PahlawanJoey** [IfcOpenShell/IfcOpenShell#5417]
Python: Traceback (most recent call last):
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\sequence\operator.py", line 727, in execute
    pp2ifc.execute()
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifc4d\pp2ifc.py", line 76, in execute
    ifcCreator.create_ifc()
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifc4d\common.py", line 36, in create_ifc
    self.create_calendars()
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifc4d\common.py", line 51, in create_calendars
    self.process_working_week(calendar["StandardWorkWeek"], calendar["ifc"])
  File "C:\Users\pahlawan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifc4d\common.py", line 62, in process_working_week
    weekday_component = [self.day_map[day["DayOfWeek"]]]
                         ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'Maandag'

**Comment by PahlawanJoey** [comment]
Changing keys to Dutch days of the week worked. Perhaps add note to add multiple language support.

**Comment by Andrej730** [comment]
@PahlawanJoey hi! Can you please share some example breaking powerproject file for tests?

**Comment by PahlawanJoey** [comment]
Can I contact you to share it in private?

**Comment by Moult** [comment]
Can you upload it here? https://forms.gle/F6qjJjtKoLLKZxUZ7

@aothms - what do you think about having a shared private file upload service (like above - it's a Google Forms that uploads to a private Google Drive folder) which then some IfcOpenShell devs have access to?

**Comment by PahlawanJoey** [comment]
Just uploaded.
