### ISSUE TITLE
After editing profile, extrusion shifts in space. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5434]
There's a strange behavior with window voids.  After editing the void profile, the void shifts in space. 

Best described via the video below.  

file: https://hub.openingdesign.com/OpeningDesign/Verona_3_Season_Porch/src/commit/c843e97879599fe0bea748804c2dadfc67edeced/Open/Models/BlenderBIM/Verona_3_Season_Porch.ifc

https://github.com/user-attachments/assets/d895ccea-ec5e-42ad-822f-744206e63c11

**Comment by theoryshaw** [comment]
weird shifting behavior happens with extrusions as well.. 

Same file. 

https://github.com/user-attachments/assets/1e20ca68-43fc-4fb9-a1dd-ba29a93b04f8

**Comment by theoryshaw** [comment]
from my tests, this seems to have been around for a couple months.  It does not happen in v0.7.0, however.

**Comment by theoryshaw** [comment]
Using, `Bonsai vo.8.1-alpha240921-9ea44fO` if i try to tab into that slab, i get the following error...


```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 406, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1736, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\ifc.py", line 255, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1649, in _execute
    operator()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1634, in <lambda>
    operator = lambda: bpy.ops.bim.hotkey(hotkey="S_E")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\workspace.py", line 831, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\workspace.py", line 936, in hotkey_S_E
    bpy.ops.bim.enable_editing_extrusion_profile()
  File "c:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\slab.py", line 562, in _execute
    tool.Model.import_profile(extrusion.SweptArea, obj=obj, position=position)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\model.py", line 275, in import_profile
    cls.import_rectangle(obj, position, profile)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\model.py", line 404, in import_rectangle
    p_position = Matrix(ifcopenshell.util.placement.get_axis2placement(profile.Position).tolist())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\placement.py", line 85, in get_axis2placement
    x.resize(3)
ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False
Location: c:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109
Location: c:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109
```

https://github.com/user-attachments/assets/52e985fe-a2dd-497c-ba7f-44941ac05ddc

**Comment by theoryshaw** [comment]
Don't know the ramifications, but if I comment out the following, the position of the profile doesn't change...

![image](https://github.com/user-attachments/assets/a87f7a56-a853-4ce5-a990-7d2db5ec7561)


A simple troubleshooting file: 
[extruding problem.ifc.txt](https://github.com/user-attachments/files/17084476/extruding.problem.ifc.txt)




https://github.com/user-attachments/assets/cfcce8f5-8aa1-4052-8dda-84c3ce51ba9a

**Comment by theoryshaw** [comment]
The other thing i noticed is that when `IFCARBITRARYCLOSEDPROFILEDEF` is a `IFCINDEXEDPOLYCURVE` it doesn't shift. 

But when the  `IFCARBITRARYCLOSEDPROFILEDEF` is a `IFCPOLYLINE` it does.

**Comment by theoryshaw** [comment]
Seems to have been fixed in the latest.
