### ISSUE TITLE
Error when trying to miter join two IfcPipeSegment objects based on IfcArbitraryProfileDef (not supported feature)

### ISSUE THREAD

**Issue by carlopav** [IfcOpenShell/IfcOpenShell#5450]
Hello,
when trying to miter join two IfcPipeSegment objects based on IfcArbitraryProfileDef, this error is raised:

`
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.8.1-alpha240922
bonsai_commit_hash: a053472
last_actions: 
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_hotkey
# operator: BIM_OT_fit_flow_segments
# operator: BIM_OT_mep_add_bend
last_error: Traceback (most recent call last):
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\workspace.py", line 831, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\workspace.py", line 1069, in hotkey_S_Y
    bpy.ops.bim.fit_flow_segments()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\mep.py", line 202, in _execute
    bpy.ops.bim.mep_add_bend()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: For now Only IfcRectangleProfileDef/IfcCircleProfileDef profiles supported for a bend, the segments are IfcArbitraryClosedProfileDef
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109

ifc: Ipotesi 01.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha240922
originating_system: Bonsai 0.8.1-alpha240922-a053472
`

I can read from the message that this is not yet supported, but then suddenly the _**Bonsai experienced an error :(**_ is displayed and I usually prefer in this situation to restart Blender. Could we differentiate between errors that should lead to a model refresh and features that are not yet supported that should not raise any particular alert?

**Comment by Arunarchitect** [comment]
![image](https://github.com/user-attachments/assets/207d98e1-e309-45f3-b558-bb59f8720852)
Needed feature, cant mitter the rain gutter

**Comment by Isaina** [comment]
Can merge this in main
