### ISSUE TITLE
Error when loading Ifc file ('NoneType' object has no attribute 'BIMMeshProperties')

### ISSUE THREAD

**Issue by carlopav** [IfcOpenShell/IfcOpenShell#5455]
Following error when loading Ifc File with 2024.09.22 windows build, that was loaded correctly with last june release:
```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.8.1-alpha240922
bonsai_commit_hash: a053472
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 752, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 835, in execute
    ifc_importer.execute()
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 254, in execute
    self.create_elements()
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 638, in create_elements
    self.create_generic_elements(self.elements)
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 654, in create_generic_elements
    products = self.create_products(elements, settings=settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 765, in create_products
    self.create_product(product, shape)
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 888, in create_product
    tool.Loader.link_mesh(shape, mesh)
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\loader.py", line 94, in link_mesh
    mesh.BIMMeshProperties.ifc_definition_id = int(geometry.id.split("-")[0])
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'BIMMeshProperties'
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: AC26GEO.CID-IFC4X3.ifc
schema: IFC4X3
preprocessor_version: IfcOpenShell 0.8.0
originating_system: IfcOpenShell 0.8.0
```

File is shared via IfcOpenShell Issues - Share private files
AC26GEO.CID.ifc

**Comment by Andrej730** [comment]
Not sure what it was but seems to be fixed in the current version.
