### ISSUE TITLE
Error on entering edition of a mesh based item

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5460]
Steps to reproduce :
1- Brand new ifc project file
2- Add cube
3- Set the cube to an IfcActuator occurrence
4- Enter edit mode with TAB shortcut
5- Error
6- Object gets hidden, and its location and rotation transforms are locked. The state in the top right is changed to "IFC Item Mode" so I assume this new thing is the culprit and it will be fixed soon :p

Error :

```
Error: Python: Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\site-packages\bonsai\bim\ifc.py", line 406, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\site-packages\bonsai\bim\module\geometry\operator.py", line 1590, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\site-packages\bonsai\tool\ifc.py", line 255, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\site-packages\bonsai\bim\module\geometry\operator.py", line 1596, in _execute
    self.handle_single_object(context, context.active_object)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\site-packages\bonsai\bim\module\geometry\operator.py", line 1631, in handle_single_object
    bpy.ops.bim.import_representation_items()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\site-packages\bonsai\bim\module\geometry\operator.py", line 2307, in _execute
    for item_id in set(obj.data["ios_item_ids"]):
                       ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'bpy_struct[key]: key "ios_item_ids" not found'
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\bpy\ops.py:109
```

**Comment by Moult** [comment]
Yes, the plan is to consolidate the (at least 3) many ways to create new IFC elements into a single consistent way. I haven't yet decided whether to completely remove the "Assign IFC Object" panel (superseded by the new "Add Element" menu item in Shift-A - admittedly it's a bit hard to discover the secret option if you have an existing object selected, better redesign it to be explicit), or to keep the panel but have it exactly duplicate the new "Add Element".
