### ISSUE TITLE
Running drawings with `Linework Mode: Freestyle`, throws error. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5472]
Running drawings with `Linework Mode: Freestyle`, throws error. 

`bonsai_py311-0.8.1-alpha240924-windows-x64`

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 274, in execute
    linework_svg = self.generate_freestyle_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 597, in generate_freestyle_linework
    context.scene.svg_export.use_svg_export = True
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'svg_export'
```

**Comment by theoryshaw** [comment]
sorry, that was it.  It didn't throw an error last time, so was thrown off. :)

**Comment by Moult** [comment]
Let's keep this open so we know to add a check / alert.

**Comment by brunopostle** [comment]
Bonsai depends on Freestyle and Sun Position extensions, Homemaker depends on Bonsai, ifcsverchock and Topologic depend on sverchock and Bonsai, etc.. but there doesn't seem to be any dependency mechanism.
