### ISSUE TITLE
Error when bulk printing drawing if there is custom scaling on ortography view

### ISSUE THREAD

**Issue by Slackking1** [IfcOpenShell/IfcOpenShell#5478]
Tested on 
- Bonsai 0.8.0 + blender 4.2.2 mac
- bonsai 0.8.0 + blender 4.2.1 windows

Reproduce
- Create orthography drawing with custom scale
- Create plan view or something else (in my case i had 5)
- Bulk print, eg. SHIFT+click on create drawing

NOTE: i tested it the other way around. eg. custom scale on plan view and standard scale on orthography view, here everything works fine.

ERROR:
Python: Traceback (most recent call last):
  File "/Users/danielbo/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 217, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbo/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 232, in execute
    bpy.ops.bim.activate_drawing(drawing=drawing_id, camera_view_point=False)
  File "/Applications/Blender.app/Contents/Resources/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/danielbo/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 1820, in execute
    core.sync_references(tool.Ifc, tool.Collector, tool.Drawing, drawing=tool.Ifc.get().by_id(self.drawing))
  File "/Users/danielbo/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/core/drawing.py", line 466, in sync_references
    annotation = drawing_tool.generate_reference_annotation(drawing, reference_element, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbo/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/drawing.py", line 1159, in generate_reference_annotation
    return cls.generate_section_reference_annotation(drawing, reference_element, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbo/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/drawing.py", line 1243, in generate_section_reference_annotation
    bounds = helper.ortho_view_frame(camera.data) if camera.data.type == "ORTHO" else None
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbo/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/helper.py", line 337, in ortho_view_frame
    scale = parse_diagram_scale(camera)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielbo/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/helper.py", line 313, in parse_diagram_scale
    _, fraction = camera.BIMCameraProperties.custom_diagram_scale.split("|")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BIMCameraProperties' object has no attribute 'custom_diagram_scale'
Location: /Applications/Blender.app/Contents/Resources/4.2/scripts/modules/bpy/ops.py:109

**Comment by BIMvoice** [comment]
This is already fixed on current v0.8.0. The custom scale UI was reworked in commit 73a3cc2cc, replacing the single custom_diagram_scale property with custom_scale_numerator and custom_scale_denominator, but parse_diagram_scale in helper.py kept reading the removed custom_diagram_scale attribute. So any bulk print or create drawing over an ortho camera set to a custom scale crashed with AttributeError, while non custom scales did not hit that branch, matching your note that it only failed with a custom scale. helper.py now reads the new numerator and denominator properties.

Verified live on Blender 5.1.2: the reported path runs with no error on current code, and running the old line still reproduces the exact AttributeError. @Slackking1, updating to a current 0.8.0 build fixes it.

**Comment by BIMvoice** [comment]
Closing, already confirmed fixed on current v0.8.0 above.

Generated with the assistance of an AI coding tool.
