### ISSUE TITLE
Regression - missing support for editing curve representations

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#5488]
Windows 10 
with these versions:
![image](https://github.com/user-attachments/assets/8ccdcd38-8fcb-4703-aa1b-c8d6f1bbef91)

When attempting to edit a line of any time with the annotation tool we get this error:

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
blender_version: 4.2.2 LTS
bonsai_version: 0.8.1-alpha240925
bonsai_commit_hash: a124e04
last_actions: 
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 15, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/MY STOREY PLAN\") at 0x00000257A40E3908>", "geometry": "<bpy_struct, Camera(\"15/1534\") at 0x000002579EF1F108>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 1539, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1497, "Name": "MY STOREY PLAN"}, "representation": {"cast_type": "entity_instance", "value": 1534, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 1534, "Name": null}}
# ifcopenshell.api: pset.edit_pset
>>> {"pset": {"cast_type": "entity_instance", "value": 1511, "Name": "EPset_Drawing"}, "properties": "{'HumanScale': '1:20', 'Scale': '1/20'}"}
# operator: BIM_OT_annotation_hotkey
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcAnnotation", "predefined_type": "LINEWORK", "name": "STRONG"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 1572, "Name": "STRONG"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.6893366575241089], [0.0, 1.0, 0.0, -0.6843479871749878], [0.0, 0.0, 1.0, 0.6000000238418579], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1572, "Name": "STRONG"}}
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 29, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/STRONG\") at 0x00000257A3EC4108>", "geometry": "<bpy_struct, Mesh(\"LINEWORK\") at 0x00000257A4531608>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "", "profile_set_usage": "None"}
# ifcopenshell.api: geometry.assign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1572, "Name": "STRONG"}, "representation": {"cast_type": "entity_instance", "value": 1581, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1572, "Name": "STRONG"}}
# ifcopenshell.api: type.assign_type
>>> {"related_objects": [{"cast_type": "entity_instance", "value": 1572, "Name": "STRONG"}], "relating_type": {"cast_type": "entity_instance", "value": 93, "Name": "STRONG"}}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: group.assign_group
>>> {"group": {"cast_type": "entity_instance", "value": 1509, "Name": "MY STOREY PLAN"}, "products": [{"cast_type": "entity_instance", "value": 1572, "Name": "STRONG"}]}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1510, "Name": null}}
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_import_representation_items
last_error: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 406, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1590, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\ifc.py", line 255, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1596, in _execute
    self.handle_single_object(context, context.active_object)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1631, in handle_single_object
    bpy.ops.bim.import_representation_items()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 2309, in _execute
    for item_id in set(obj.data["ios_item_ids"]):
                       ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'bpy_struct[key]: key "ios_item_ids" not found'
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\bpy\ops.py:109


ifc: Line edit test.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha240925
originating_system: Bonsai 0.8.1-alpha240925-a124e04
```

It happens on any Ifc file but See attached Ifc to test:
[Line edit test - Copy.ifc.txt](https://github.com/user-attachments/files/17131253/Line.edit.test.-.Copy.ifc.txt)

**Comment by Moult** [comment]
Yes sorry the new item editing mode is still very much a WIP and doesn't support edges yet. Ping @aothms - how easy is it to add edges item IDs? If not, we can fall back to the way we did it in the past (i.e. don't distinguish between separate items).

**Comment by Plae-Blue-Dot** [comment]
No stress, I will just fall back for now, the last version that worked seems to be:
![image](https://github.com/user-attachments/assets/bb96c600-80ee-42b0-94ca-edaa865f43d3)
alpha240921

**Comment by Slackking1** [comment]
@Plae-Blue-Dot how do you make the fallback? Asking since drawing in 0.8.0 doesn't work with tags, and latest unstable doesn't work with dimensions etc. 

If you point me enough in the right direction, I will try to add it to the dev documentation. For other noobs like me ;)

**Comment by Andrej730** [comment]
> how do you make the fallback? Asking since drawing in 0.8.0 doesn't work with tags, and latest unstable doesn't work with dimensions etc.
> 
> If you point me enough in the right direction, I will try to add it to the dev documentation. For other noobs like me ;)

Uninstall Bonsai and install some previous version from the releases - https://github.com/IfcOpenShell/IfcOpenShell/releases

**Comment by Plae-Blue-Dot** [comment]
@Slackking1 It's as @Andrej730 says, just Uninstall Bonsai and install the older version alpha240921

**Comment by Slackking1** [comment]
Thanks :) it was the uninstall and reinstall into the repo i never got my head around.
I've added a tip in the documentation to hopefully clarify this, i did try to find the answer there before asking here ;) 
#5501

**Comment by Plae-Blue-Dot** [comment]
Ok as an update using:
![image](https://github.com/user-attachments/assets/206494b5-326d-4841-b79f-521b7db269fa)

The default line types all still give the same error (which means you cannot edit them)
![image](https://github.com/user-attachments/assets/7c533ae8-dda4-499f-b5dd-9bb991a6ed24)


The 'Untyped' line does not give the error, (Which means you can edit them)
![image](https://github.com/user-attachments/assets/78963363-4b9a-4dd5-beab-63fd107efbd5)

As a workaround you can create an untyped line and then change the line type to one of the defaults and it will still be editable without an error
![image](https://github.com/user-attachments/assets/9680f1ab-7692-48c4-a742-8f37077366a1)

![image](https://github.com/user-attachments/assets/716a62b8-3fec-4c8f-a91e-43f1a3df4c08)


It seems like this is close to being fixed
Is it possible to have the default line types act in the same way as the default 'Untyped' line type?
I'm not sure what the core difference between them is at this point

Ifc file example attached:
[New line test - Copy.ifc.txt](https://github.com/user-attachments/files/17360576/New.line.test.-.Copy.ifc.txt)

**Comment by theoryshaw** [comment]
This one seems fixed on my end!

**Comment by theoryshaw** [comment]
whoops, i was mistaken, forgot i checked out a commit in the past.

**Comment by theoryshaw** [comment]
@Plae-Blue-Dot does this seem fixed on you end? 

The only hiccup, i see is if you duplicate a dimension line, the IfcIndexedPolyCurve changes to an IfcGeometricCurveSet, which doesn't seem editable. 

https://github.com/user-attachments/assets/91ee7d28-96e0-446c-a3c1-d16aff092f2b

**Comment by Plae-Blue-Dot** [comment]
Yes most of it works except for duplicating a dimension line:
![image](https://github.com/user-attachments/assets/2f4d2f00-ae07-4e10-a3b5-58120deafec8)

You can create, edit and duplicate all the line types now
![image](https://github.com/user-attachments/assets/a0296360-44f4-44e3-9cc2-2d58c4b8372e)


It seems to take 7 steps to edit a line now
1) select the line
2) tab in
3) select the line again
4) tab in
5) select the thing you want to edit
6) start editing
7) tab out to save the edit

And the line doesnt automatically preview immediately when you tab out:
![image](https://github.com/user-attachments/assets/25026951-fb38-44f8-9c5f-23de63b67de3)


previously it took 5 steps: 
1) select the line
2) tab in
3) select the thing you want to edit
4) start editing
5) tab out to save the edit

But maybe this should be a different issue hahah, it does seem a bit more stable now?

**Comment by Plae-Blue-Dot** [comment]
OK so tried using it with other projects and it is still giving the same issues with all line types, just not with this example file I'll find another paired down one to include

**Comment by Plae-Blue-Dot** [comment]
![Image](https://github.com/user-attachments/assets/c2483105-15ed-4863-9778-a86a05cc2bc5)

Tested it out with the new build, working perfectly!

![Image](https://github.com/user-attachments/assets/c485b568-e802-4a6e-b3db-40dd7339f7f6)

Thank you so so much @Moult
