### ISSUE TITLE
Error CSV Cost Schedule Import

### ISSUE THREAD

**Issue by JuergenMo** [IfcOpenShell/IfcOpenShell#5492]
I'm working on the course "BIM 5D - COSTING - Crash Course - BlenderBIM" of Sigma dimension, i imported his file than export it and try to import this file but recieve the following error.

```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 166 Stepping 0, GenuineIntel
blender_version: 4.2.2 LTS
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 247990, "Name": null}}
# ifcopenshell.api: cost.add_cost_value
>>> {"parent": {"cast_type": "entity_instance", "value": 248000, "Name": "Building"}}
# operator: BIM_OT_generate_global_id
# operator: BIM_OT_generate_global_id
# operator: BIM_OT_disable_editing_cost_schedule
# operator: BIM_OT_disable_editing_cost_schedule
# operator: BIM_OT_enable_editing_cost_items
# operator: BIM_OT_disable_editing_cost_schedule
# operator: BIM_OT_import_cost_schedule_csv
# operator: BIM_OT_import_cost_schedule_csv
last_error: Traceback (most recent call last):
  File "C:\Users\jmoog\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmoog\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\cost\operator.py", line 522, in _execute
    core.import_cost_schedule_csv(tool.Cost, self.filepath, self.is_schedule_of_rates)
  File "C:\Users\jmoog\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\cost.py", line 311, in import_cost_schedule_csv
    cost.import_cost_schedule_csv(file_path, is_schedule_of_rates)
  File "C:\Users\jmoog\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\cost.py", line 527, in import_cost_schedule_csv
    csv2ifc.execute()
  File "C:\Users\jmoog\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifc5d\csv2ifc.py", line 41, in execute
    self.parse_csv()
  File "C:\Users\jmoog\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifc5d\csv2ifc.py", line 74, in parse_csv
    cost_data = self.get_row_cost_data(row)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmoog\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifc5d\csv2ifc.py", line 83, in get_row_cost_data
    name = row[self.headers["Name"]]
               ~~~~~~~~~~~~^^^^^^^^
KeyError: 'Name'

ifc: 4D.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-9cc1f5f0e
originating_system: BlenderBIM 0.0.230906-ef87f0f
```

**Comment by JuergenMo** [comment]
[Issue.zip](https://github.com/user-attachments/files/17165949/Issue.zip)

Here the files, the *rates.csv* is the original file from the course, this i can import in bonsai, the File "CSV Import.csv" was the exported file. the same issue i have if i make a schedule in bonsai on my own and export it and try to import this file to an other ifc. I try this on different computers with the same result/error.

**Comment by JuergenMo** [comment]
The exported file looks completely different to the original.

**Comment by steverugi** [comment]
Hi @JuergenMo 
the exported file cannot be re-imported back in Bonsai
it has a slightly different column structure, see mine (tested) attached

Also, the exported file used 0 as starting Hierarchy level, I changed it to 1 and the others accordingly and now it works

please advise and let me know if you have other issues regarding quantities
cheers

[BoQ.txt](https://github.com/user-attachments/files/17173520/BoQ.txt)

**Comment by Andrej730** [comment]
Thanks for reporting this, sorry it took so long to realize what the issue was.

Issue is fixed and I've updated readme, it now has some details about the file format - https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifc5d/README.md

To summarize the changes that were needed for import-export consistency:
1. Previously for import 'Hierarchy' column was used which actually was index but was named 'Hierarchy'. In old import files 'Hierarchy' should be renamed to 'Index'.
2. Previous 'Description' column is no longer supported and should be renamed to 'Name'. Currently there is a workaround that automatically interprets 'Description' column as 'Name' but it may be soon deprecated.
3. Indices in 'Index' column should start from 1, not 0. Currently there's also a backport fix that allows 0 indices, but it also may be soon deprecated.

What to do with old files:
1. If you have .csv previously exported from Bonsai - just rename 'Description' -> 'Name'. If indices start from 0, add 1 to all of them. But for now file should work even without those changes.
2. If you have .csv that wasn't exported from Bonsai but was still used for cost schedule import - rename 'Hierarchy' with 'Index', otherwise it won't load and that should be it.


CC @Ave-5D

**Comment by steverugi** [comment]
@Andrej730 
thanks but how does the script work without reference to the cost schedule?
please advise

**Comment by Andrej730** [comment]
@steverugi which one?

See the documentation.
https://github.com/IfcOpenShell/IfcOpenShell/blob/85d8fa49ab1a03f4fdd972f64973fb80ea3a4fa4/src/ifc5d/ifc5d/csv2ifc.py#L82
https://github.com/IfcOpenShell/IfcOpenShell/blob/85d8fa49ab1a03f4fdd972f64973fb80ea3a4fa4/src/ifc5d/ifc5d/ifc5Dspreadsheet.py#L269

**Comment by steverugi** [comment]
Oh OK it exports as many cost schedule there are available in the model, thanks!

**Comment by steverugi** [comment]
@Andrej730 for your information the import csv is sort of OK but it uses the index column values as rate

**Comment by steverugi** [comment]
actually it just fills a value = 2 as cost item value..

.csv import file

![Image](https://github.com/user-attachments/assets/db4fefa3-5400-4914-9a91-54ab3c25a5cc)

BoQ output in Bonsai

![Image](https://github.com/user-attachments/assets/9e80bee6-2f84-40f2-970b-d5a00ef6bcae)

The export spreadsheet as .csv produces columns that are not needed (Id, Hierarchy, Index, Children) 

![Image](https://github.com/user-attachments/assets/9ea6cc2d-d71d-449e-b191-20b93bab8809)

thanks

**Comment by Ave-5D** [comment]
@steverugi , "The export spreadsheet as .csv produces columns that are not needed (Id, Hierarchy, Index, Children)" are these columns not required to ensure that the csv file can be imported back into Bonsai without adding columns? 
I could be totaly wrong, 

As a Bonsai user I just want to export the csv file edit values or add lines and then import again or import the csv file into another Bonsai model to edit within Bonsai.

**Comment by steverugi** [comment]
@Ave-5D I don't think you can import the exported file back into Bonsai, well you can now (just tried) without generating an error but it imports it as schedule of rate

BoQ test n Bonsai from .csv import (values are wrong):

![Image](https://github.com/user-attachments/assets/b5265a78-f1a9-4455-8fbe-3a87dc088305)

Exported file from BoQ

![Image](https://github.com/user-attachments/assets/a13efbf1-de84-4e74-924e-ae5109d29a13)

Re-imported the same exported file back in Bonsai (As schedule of rates without quantities)

![Image](https://github.com/user-attachments/assets/1e4af269-49d9-4c5e-ad6f-39f0f1f598f7)


my initial idea of a "roundtrip" file was to have a .csv with the query column to create a BoQ with automatic extraction of quantities, in case of an update of the same .csv the BoQ needs to be closed and deleted, and the edited .csv imported again

cheers

**Comment by steverugi** [comment]
in my pov there are these tables at the moment:
1. an "importer" .csv file where by using unit and query a BoQ can be created with quantities extracted per query statement
2. an "importer2" .csv file where a schedule of rates can be imported and used to (manually) feed cost items' values (rates) in the BoQ
3. an "exported" .csv file (or .ods/excel) where Bonsai's BoQ is exported to (the one I commented about the extra columns)

I am not sure I fully understand the actual change recently performed by @Andrej730, if not some change of column name

looking forward to getting this right

thanks

**Comment by steverugi** [comment]
@Ave-5D please see my comments in [https://github.com/IfcOpenShell/IfcOpenShell/issues/6570](https://github.com/IfcOpenShell/IfcOpenShell/issues/6570) on the sync feature, thanks

**Comment by maxfb87** [comment]
> in my pov there are these tables at the moment:
> 1. an "importer" .csv file where by using unit and query a BoQ can be created with quantities extracted per query statement
> 2. an "importer2" .csv file where a schedule of rates can be imported and used to (manually) feed cost items' values (rates) in the BoQ
> 3. an "exported" .csv file (or .ods/excel) where Bonsai's BoQ is exported to (the one I commented about the extra columns)
> 
> I am not sure I fully understand the actual change recently performed by @Andrej730, if not some change of column name
> 
> looking forward to getting this right
> 
> thanks

I agree with that

**Comment by Andrej730** [comment]
You're right, the hierarchy columns wasn't the only problem and deeper changes were required. But now exporting .csv and importing it should be supported and the bugs you've mentioned above are addressed (e.g. bunch of other columns like Id, Index, etc were interpreted as cost values at import).

Took me a bit to wrap my head around csv structure and I've tried to describe it in [readme](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifc5d/README.md#columns-description), please submit PRs if you have any ideas how to make it even more clear.

Basically here's a general outline:
1. There are basic fields required in both import and export
2. Some additional BoQ fields. Some of them are exportable ('Quantity'), some are not and can be only added later ('Property', 'Query').
3. Some additional export fields that are exported just for informational purposes, they're not used for import.

The caveat with group 1 is that format allows expressing cost values in 2 ways:
a) 'Value' column - overall cost value for an item. Not exported, can be only added afterwards by the user.
b) If 'Value' column is not present, then all other columns that are not mentioned above interpreted as cost value categories.

**Comment by steverugi** [comment]
@Andrej730 
Thanks for the update, much better now, you are a star!

What I still find a bit odd is the need to export it to a .csv for publishing purposes (which is fine) and bringing the .csv back to Bonsai but without the element assignments.
I have a BoQ with quantities from elements in the model, I consider crucial maintaining that relation in my cost schedule for obvious reasons.

Importing back a barebone cost schedule to Bonsai doesn't strike me as a very productive feature, by it's my point of view of course
Conversely, Property and Query columns indirectly keep that assignments alive and, as @maxfb87 is also supporting, a "sync" button will keep that for any possible editing.

Thanks again for your support

**Comment by maxfb87** [comment]
Reference #6570

**Comment by Ave-5D** [comment]
Thank you, the update looks \0/
