### ISSUE TITLE
If I tab into a leader, and tab out I get the following error. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5499]
If I tab into a leader, and tab out I get the following error. 

file: https://hub.openingdesign.com/OpeningDesign/Restaurant_MPM/src/commit/bab8e0d4035262d5af7b0998419004c6d31562a7/Open/Models/BlenderBIM/Restaurant_MPM.ifc

https://github.com/user-attachments/assets/7ea62904-4535-4d57-8af2-eaaeb0993350

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.0.0
bonsai_commit_hash: d581174
last_actions: 
# ifcopenshell.api: geometry.assign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 3990494, "Name": "TEXT_LEADER"}, "representation": {"cast_type": "entity_instance", "value": 3990503, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 3990494, "Name": "TEXT_LEADER"}}
# ifcopenshell.api: group.assign_group
>>> {"group": {"cast_type": "entity_instance", "value": 3314862, "Name": "ELEVATION - NORTH"}, "products": [{"cast_type": "entity_instance", "value": 3990494, "Name": "TEXT_LEADER"}]}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 3314864, "Name": null}}
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 28, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/TEXT_LEADER.112\") at 0x00000148854EEB08>", "geometry": "<bpy_struct, Curve(\"28/3990503\") at 0x000001485B591608>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "IfcGeometricCurveSet/IfcTextLiteral", "profile_set_usage": "None", "text_literal": {"cast_type": "entity_instance", "value": 3990509, "Name": null}}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 3990514, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 3990494, "Name": "TEXT_LEADER"}, "representation": {"cast_type": "entity_instance", "value": 3990503, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 3990503, "Name": null}}
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_import_representation_items
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_import_representation_items
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_import_representation_items
last_error: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 406, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1614, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\ifc.py", line 255, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1620, in _execute
    self.handle_single_object(context, context.active_object)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1655, in handle_single_object
    bpy.ops.bim.import_representation_items()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 2342, in _execute
    item_ids = data["ios_item_ids"] if "ios_item_ids" in data else data["ios_edges_item_ids"]
                                                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'bpy_struct[key]: key "ios_edges_item_ids" not found'
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: Restaurant_MPM_old.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.0.0
originating_system: Bonsai 0.8.1-alpha240905-5616367
```

**Comment by Plae-Blue-Dot** [comment]
Is this the same error:
https://github.com/IfcOpenShell/IfcOpenShell/issues/5488 ?

It should not be present on older version of Bonsai like Bonsai 0.8.1-alpha240905-5616367 though

**Comment by theoryshaw** [comment]
Yes, i think it might.

**Comment by Andrej730** [comment]
Closing as #5488 is indeed the main issue.
