### ISSUE TITLE
Bonsai daily unstable installation requires the computer to restart

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5508]
When I want an updated daily installation of Bonsai using raw.githubusercontent.com I need to restart the computer every time.

This is the screenshot of the message:

![Screenshot 2024-09-28 082241](https://github.com/user-attachments/assets/b120da0d-7282-47a0-87e5-fc48ec15ca0b)

Windows10 - Blender 4.2.1LTS

thanks

**Comment by Gorgious56** [comment]
This has been happening to me too, but I'm not sure it's a fault on Bonsai's side, as I recall having this problem with other extensions. My immediate solution was to manually find the culprit files and set some kind of administratof privileges on it (right click > Windows prompt). It's weird because I have full admin privileges on my station, no other files than those .pyd have this problem. It's happening since migrating to Blender 4.2. I assume it's a windows only problem.

**Comment by steverugi** [comment]
> This has been happening to me too, but I'm not sure it's a fault on Bonsai's side, as I recall having this problem with other extensions. My immediate solution was to manually find the culprit files and set some kind of administratof privileges on it (right click > Windows prompt). It's weird because I have full admin privileges on my station, no other files than those .pyd have this problem. It's happening since migrating to Blender 4.2. I assume it's a windows only problem.

thank you @Gorgious56 

please what do you mean by right click > Windows prompt? cheers


![image](https://github.com/user-attachments/assets/8e11b4be-99c1-49f9-8d39-910274422d2e)

**Comment by Andrej730** [comment]
> When I want an updated daily installation of Bonsai using raw.githubusercontent.com I need to restart the computer every time.

Are you sure just restarting Blender doesn't help? (need to make sure there are no Blender instances running - including Bonsai Web UI server window).

**Comment by steverugi** [comment]
Hi @Andrej730 
> Are you sure just restarting Blender doesn't help? (need to make sure there are no Blender instances running - including Bonsai Web UI server window).
> 
tried everything, including restarting Blender only, at the moment I went back to 240906, and will continute manual installation when needed
> It's not about the privileges - Windows has this thing that you cannot remove the binary if it's currently loaded by the program. In Blender 4.2.1 they've added a mechanism that prevents this issue, see https://projects.blender.org/blender/blender/issues/125049 but appareantly there is still an edge case that still occurs for some users.

OK, thanks

**Comment by Gorgious56** [comment]
Good to know, thanks. Maybe that was another error, because mine was similar but Windows definitely asked me for admin privileges.

**Comment by steverugi** [comment]
thanks @Andrej730 will try tomorrow from the office, cheers

**Comment by Gorgious56** [comment]
Sorry for the noise, I was in fact mistaken, the problem I encountered was the *module.dist-info* in the blender installation /4.2/python/lib-site-packages that were misbehaving, not the .pyd files. Cheers

**Comment by Andrej730** [comment]
@steverugi any updates?

**Comment by steverugi** [comment]
Hi @Andrej730 

![image](https://github.com/user-attachments/assets/32e1ada3-aaa0-4b00-a0df-0d69e94608fe)

it is somehow better, after the message I only need to restart Blender not the computer as before, thanks for asking

**Comment by Andrej730** [comment]
> it is somehow better, after the message I only need to restart Blender not the computer as before, thanks for asking

@steverugi What Blender version? Can you please attach the full error as a text?

**Comment by steverugi** [comment]
it's 4.2.3 / 241113 (just updated)
to reproduce it I need to do it tomorrow when update it again, cheers

**Comment by Gorgious56** [comment]
It happens to me to every time I update Bonsai, FWIW, Blender 4.2.1. No need to restart computer but I do need to reload Blender, which is expected when updating an addon.

```
Failed to remove: (<built-in function unlink>, 'C:\\Users\\ \\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\.local\\lib\\python3.11\\site-packages\\ifcopenshell\\_ifcopenshell_wrapper.cp311-win_amd64.pyd', (<class 'PermissionError'>, PermissionError(13, 'Accès refusé'), <traceback object at 0x000001B8A8A9B940>))
Failed to remove: (<built-in function rmdir>, 'C:\\Users\\ \\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\.local\\lib\\python3.11\\site-packages\\ifcopenshell', (<class 'OSError'>, OSError(41, 'Le répertoire n’est pas vide'), <traceback object at 0x000001B8A8A9B940>))
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1345, in modal
    self.exec_command_finish(canceled)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2839, in exec_command_finish
    _extensions_repo_refresh_on_change(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1018, in _extensions_repo_refresh_on_change
    _extensions_repo_sync_wheels(repo_cache_store, extensions_enabled)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1008, in _extensions_repo_sync_wheels
    addon_utils._extension_sync_wheels(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\addon_utils.py", line 1312, in _extension_sync_wheels
    apply_action(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\_bpy_internal\extensions\wheel_manager.py", line 428, in apply_action
    _zipfile_extractall_safe(zip_fh, local_dir_site_packages, local_dir)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\_bpy_internal\extensions\wheel_manager.py", line 222, in _zipfile_extractall_safe
    zip_fh.extract(member, path_restrict)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\zipfile.py", line 1664, in extract
    return self._extract_member(member, path, pwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\zipfile.py", line 1735, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ \\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\.local\\lib\\python3.11\\site-packages\\ifcopenshell\\_ifcopenshell_wrapper.cp311-win_amd64.pyd'
Error: Python: Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\_bpy_internal\extensions\wheel_manager.py", line 428, in apply_action
    _zipfile_extractall_safe(zip_fh, local_dir_site_packages, local_dir)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\_bpy_internal\extensions\wheel_manager.py", line 222, in _zipfile_extractall_safe
    zip_fh.extract(member, path_restrict)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\zipfile.py", line 1664, in extract
    return self._extract_member(member, path, pwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\zipfile.py", line 1735, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ \\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\.local\\lib\\python3.11\\site-packages\\ifcopenshell\\_ifcopenshell_wrapper.cp311-win_amd64.pyd'

```

**Comment by Andrej730** [comment]
> it's 4.2.3 / 241113 (just updated)
> to reproduce it I need to do it tomorrow when update it again, cheers

@Gorgious56 @steverugi

Can you please try to uninstall it and install yesterday's version from the archive below and try to update it?
Note that it's not the same archive as available in the releases, it has a manually added fix for Blender 4.3.
https://drive.google.com/file/d/1keY7rH22MZUx1qqM2DdqpOlAK1Qtmet-/view?usp=sharing

Can you also install Blender 4.3 (available on https://builder.blender.org/download/daily/) and try to setup unstable extension, yesterday's version from the acrhive above and try to update?

Blender is about to release Blender 4.3, maybe the issue is resovled there or we can try to report it and maybe it will get resolved.

**Comment by steverugi** [comment]
OK but I can only do it during the weekend, thanks

**Comment by Andrej730** [comment]
Is this still an issue?

**Comment by steverugi** [comment]
Hi @Andrej730 
Manual installation
1. download the latest 250104
2. open Blender/Bonsai > uninstall previous Bonsai > close  Blender
3. open Blender > install Bonsai from disk > close it
4. open Blender/Bonsai > All OK

no need to restart the computer, many thanks
will try to do it from a repository soon, cheers

**Comment by theoryshaw** [comment]
For what it's worth, i got the same error when trying to update via the [Unstable Installation](https://docs-unstable.bonsaibim.org/guides/development/installation.html#unstable-installation).

![Image](https://github.com/user-attachments/assets/0a4bf81a-b3ec-4310-91dc-cfbf46857caf)

blender 4.2

It seems, after restarting blender again, that it was still installed however. 

```

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\_bpy_internal\extensions\wheel_manager.py", line 428, in apply_action
    _zipfile_extractall_safe(zip_fh, local_dir_site_packages, local_dir)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\_bpy_internal\extensions\wheel_manager.py", line 222, in _zipfile_extractall_safe
    zip_fh.extract(member, path_restrict)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\zipfile.py", line 1664, in extract
    return self._extract_member(member, path, pwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\zipfile.py", line 1735, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Ryan Schultz\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\.local\\lib\\python3.11\\site-packages\\ifcopenshell\\_ifcopenshell_wrapper.cp311-win_amd64.pyd'
```

**Comment by steverugi** [comment]
Yes, for me too, it has now become an  automatic procedure 
every time I want to update an unstable version I restart the computer first
Thanks

**Comment by Andrej730** [comment]
@theoryshaw @steverugi 
Can you please try it on the latest version of Blender to see if issue is still present?
If it is we need to report it to Blender to get it fixed.

**Comment by steverugi** [comment]
Hi @Andrej730 
I am using the latest stable version of Blender 4.3.2
Bonsai unstable via disk installs OK and works once the process is completed, when I close and open it back again it doesn't show anything in the right panel
The "solution" is to restart the computer before installing it, and all works OK
Thanks

**Comment by Andrej730** [comment]
@steverugi 
Can you please try to reproduce it on fresh Blender installation and describe your steps exactly?
To get fresh Blender environment you can rename `4.3` folder in `C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender` - then Blender will load with default preferences, no addons installed.

**Comment by steverugi** [comment]
@Andrej730 
I can only do it over the weekend, thanks

**Comment by falken10vdl** [comment]
Is this still a problem with newest versions? Or can be closed ?

**Comment by Andrej730** [comment]
Ping.

**Comment by steverugi** [comment]
Hi @Andrej730 
for me it's ok to use the uninstall bonsai > reset computer > install bonsai from disk, I do it once a week so no big deal 
I also have a linux laptop and it works well with the automatic update, especially the loading bar is very useful
we can close the Issue I think, thanks again

**Comment by Andrej730** [comment]
But there shouldn't be a need to restart the computer. If there's still some error that requires computer restart to be resolved, we should investigate it - the need to restart the computer on update would be very unapparent and confusing for the most users.

**Comment by steverugi** [comment]
@Andrej730 
in my case there is

I just used the `https://raw.githubusercontent.com/IfcOpenShell/bonsai_unstable_repo/main/index.json` repository and followed the required steps

it loads bonsai and 'looks' OK, unfortunately the right hand side panel is empty (the "Create Project" one)
I close and reopen Bonsai and the "BIM" tag is there but no usual UI, just vanilla Blender

so I restarted the computer and repeated the same, now it's OK
maybe it's a windows 10 thing? I don't have any error, sorry I wish I could be more helpful with my feedback

**Comment by Andrej730** [comment]
> it loads bonsai and 'looks' OK, unfortunately the right hand side panel is empty (the "Create Project" one)

In theory there should be errors in logs in system console (Window - Toggle System Console) to give us clues on what happened.

> I close and reopen Bonsai and the "BIM" tag is there but no usual UI, just vanilla Blender

What's the "BIM tag"? You mean BIM workspace?

![Image](https://github.com/user-attachments/assets/3000ff22-8169-4103-85c1-672d0bb19802)

If there's BIM workspace, then it means Bonsai was actually installed and tried to register during Blender launch and failed. But there should be errors logs in system console for this case. But errors that appear right after update (before Blender restart) are more important as they should indicate the root cause of this.
