### ISSUE TITLE
Error: Convert OpenCascade to IFC

### ISSUE THREAD

**Issue by smr02** [IfcOpenShell/IfcOpenShell#5511]
The following code from the documentation gives an Error: 

https://github.com/IfcOpenShell/IfcOpenShell/blob/5129d2016ed4556054b170a9a027cd64302b0bd8/src/ifcopenshell-python/docs/ifcopenshell-python/geometry_creation.rst?plain=1#L583-L603

```
Traceback (most recent call last):
  File "/home/smr/Github/structural/test.py", line 20, in <module>
    product_definition = ifcopenshell.geom.serialise("IFC2X3", building_shell)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smr/miniconda3/envs/py_occ/lib/python3.12/site-packages/ifcopenshell/geom/main.py", line 498, in _
    string_or_shape = utils.serialize_shape(string_or_shape)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smr/miniconda3/envs/py_occ/lib/python3.12/site-packages/ifcopenshell/geom/occ_utils.py", line 228, in serialize_shape
    return shapes.WriteToString()
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BRepTools_ShapeSet' object has no attribute 'WriteToString'
```

**Comment by aothms** [comment]
Which version of pythonOpencascade? 

What does `print(dir(BRepTools.BRepTools_ShapeSet()))` tell us?

**Comment by smr02** [comment]
```
pythonocc-core            7.8.1           all_h0638c4f_200    conda-forge
```


```
>>> from OCC.Core import BRepTools
>>> print(dir(BRepTools.BRepTools_ShapeSet()))
['Add', 'AddGeometry', 'AddShapes', 'ChangeLocations', 'Check', 'Clear', 'Dump', 'DumpExtent', 'DumpGeometry', 'DumpPolygon3D', 'DumpPolygonOnTriangulation', 'DumpTriangulation', 'FormatNb', 'Index', 'IsWithNormals', 'IsWithTriangles', 'Locations', 'NbShapes', 'Read', 'ReadGeometry', 'ReadPolygon3D', 'ReadPolygonOnTriangulation', 'ReadTriangulation', 'SetFormatNb', 'SetWithNormals', 'SetWithTriangles', 'Shape', 'Write', 'WriteGeometry', 'WritePolygon3D', 'WritePolygonOnTriangulation', 'WriteTriangulation', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy__', '__weakref__', 'this', 'thisown']
>>> 
```

**Comment by aothms** [comment]
I think you just need to call shapes.Write() instead of shapes.WriteToString(). Do you want to send in a Pull Request with hasattr() or try/catch? would be appreciated.

Even better I think would be to use `OCC.Core.BRepTools.breptools.Write(shp)` because this usage of BRepTools_ShapeSet I think is not fully correct and might miss the outermost transformation iirc, but I don't seem to be able to find a way to specify the version number (2) when using `OCC.Core.BRepTools.breptools.Write(shp)`.

**Comment by smr02** [comment]
when i use `shapes.Write()`, 
```
product_definition = ifcopenshell.geom.serialise("IFC2X3", building_shell, False) 
```
runs fine. 
However, 
```
product_definition = model.add(product_definition) 
```
returns 
```
Segmentation fault (core dumped)
```

**Comment by smr02** [comment]
I've created a new conda environment. Now it seems to work! Not sure what the problem was.
