### ISSUE TITLE
Tabbing into the void, produces an error

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5526]
Tabbing into the void, produces an error

file: https://hub.openingdesign.com/OpeningDesign/Verona_3_Season_Porch/src/commit/43190496e77c392dc27e7f5a94098063fe4b6d99/Open/Models/BlenderBIM/Verona_3_Season_Porch.ifc

https://github.com/user-attachments/assets/95c4901c-3450-4af0-9484-008f4800783c

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 406, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1861, in _invoke
    self.edit_representation_item(context.active_object)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1964, in edit_representation_item
    tool.Geometry.reload_representation(bpy.context.scene.BIMGeometryProperties.representation_obj)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 1071, in reload_representation
    meshes_to_objects = {(obj := tool.Ifc.get_object(element)).data: obj for element in elements}
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 1071, in <dictcomp>
    meshes_to_objects = {(obj := tool.Ifc.get_object(element)).data: obj for element in elements}
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

```

**Comment by theoryshaw** [comment]
Band name: Tabbing into the Void

**Comment by Gorgious56** [comment]
I can replicate, however I don't think it has to do with tabbing into the void, if the mesh is selected when tabbing the error still appears.

**Comment by theoryshaw** [comment]
Yeah, this happening a lot with these windows, in this project.

**Comment by theoryshaw** [comment]
for what it's worth, i'm able to edit the void extrusion in 060524, just not the latest in 0.8.0.
