### ISSUE TITLE
build_all.py on Fedora 29 - - - Stop at Building python-2.7.12

### ISSUE THREAD

**Issue by paullee0** [IfcOpenShell/IfcOpenShell#554]
The script works on Fedora27 with an issue fixed at #480 

Attempt to build on Fedora 29 and it stop at Building python-2.7.12...

Any idea?  Thanks!
```

Fetching python-2.7.12...   
Configuring python-2.7.12...
Building python-2.7.12...   
----------------------------------------------------------------------
../Parser/pgen.c: In function ‘compile_atom’:
../Parser/pgen.c:282:9: warning: variable ‘i’ set but not used [-Wunused-but-set-variable]
     int i;
         ^
In file included from ../Include/Python.h:81,
                 from ../Objects/classobject.c:4:
../Objects/classobject.c: In function ‘PyMethod_New’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Objects/classobject.c:2259:9: note: in expansion of macro ‘PyObject_INIT’
         PyObject_INIT(im, &PyMethod_Type);
         ^~~~~~~~~~~~~
In file included from ../Include/Python.h:81,
                 from ../Objects/complexobject.c:8:
../Objects/complexobject.c: In function ‘PyComplex_FromCComplex’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Objects/complexobject.c:242:5: note: in expansion of macro ‘PyObject_INIT’
     PyObject_INIT(op, &PyComplex_Type);
     ^~~~~~~~~~~~~
In file included from ../Include/Python.h:81,
                 from ../Objects/floatobject.c:7:
../Objects/floatobject.c: In function ‘PyFloat_FromDouble’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Objects/floatobject.c:152:5: note: in expansion of macro ‘PyObject_INIT’
     PyObject_INIT(op, &PyFloat_Type);
     ^~~~~~~~~~~~~
In file included from ../Include/Python.h:81,
                 from ../Objects/intobject.c:4:
../Objects/intobject.c: In function ‘PyInt_FromLong’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Objects/intobject.c:110:5: note: in expansion of macro ‘PyObject_INIT’
     PyObject_INIT(v, &PyInt_Type);
     ^~~~~~~~~~~~~
../Objects/intobject.c: In function ‘_PyInt_Init’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Objects/intobject.c:1469:9: note: in expansion of macro ‘PyObject_INIT’
         PyObject_INIT(v, &PyInt_Type);
         ^~~~~~~~~~~~~
In file included from ../Include/Python.h:78,
                 from ../Objects/listobject.c:3:
../Objects/listobject.c: In function ‘list_resize’:
../Include/pymem.h:110:34: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  (type *) PyMem_REALLOC((p), (n) * sizeof(type)) )
                                  ^
../Include/pymem.h:77:21: note: in definition of macro ‘PyMem_REALLOC’
     : realloc((p), (n) ? (n) : 1))
                     ^
../Objects/listobject.c:62:9: note: in expansion of macro ‘PyMem_RESIZE’
         PyMem_RESIZE(items, PyObject *, new_allocated);
         ^~~~~~~~~~~~
../Objects/listobject.c: In function ‘list_ass_subscript’:
../Objects/listobject.c:2644:41: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
                 PyMem_MALLOC(slicelength*sizeof(PyObject*));
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Objects/listobject.c:2725:41: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
                 PyMem_MALLOC(slicelength*sizeof(PyObject*));
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
In file included from ../Include/Python.h:78,
                 from ../Objects/dictobject.c:10:
../Objects/dictobject.c: In function ‘dictresize’:
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Objects/dictobject.c:643:20: note: in expansion of macro ‘PyMem_NEW’
         newtable = PyMem_NEW(PyDictEntry, newsize);
                    ^~~~~~~~~
In file included from ../Include/Python.h:81,
                 from ../Objects/methodobject.c:4:
../Objects/methodobject.c: In function ‘PyCFunction_NewEx’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Objects/methodobject.c:23:9: note: in expansion of macro ‘PyObject_INIT’
         PyObject_INIT(op, &PyCFunction_Type);
         ^~~~~~~~~~~~~
In file included from ../Include/Python.h:78,
                 from ../Objects/setobject.c:7:
../Objects/setobject.c: In function ‘set_table_resize’:
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Objects/setobject.c:316:20: note: in expansion of macro ‘PyMem_NEW’
         newtable = PyMem_NEW(setentry, newsize);
                    ^~~~~~~~~
In file included from ../Include/Python.h:81,
                 from ../Objects/stringobject.c:5:
../Objects/stringobject.c: In function ‘PyString_FromStringAndSize’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Include/objimpl.h:166:29: note: in expansion of macro ‘PyObject_INIT’
     ( Py_SIZE(op) = (size), PyObject_INIT((op), (typeobj)) )
                             ^~~~~~~~~~~~~
../Objects/stringobject.c:91:5: note: in expansion of macro ‘PyObject_INIT_VAR’
     PyObject_INIT_VAR(op, &PyString_Type, size);
     ^~~~~~~~~~~~~~~~~
../Objects/stringobject.c: In function ‘PyString_FromString’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Include/objimpl.h:166:29: note: in expansion of macro ‘PyObject_INIT’
     ( Py_SIZE(op) = (size), PyObject_INIT((op), (typeobj)) )
                             ^~~~~~~~~~~~~
../Objects/stringobject.c:146:5: note: in expansion of macro ‘PyObject_INIT_VAR’
     PyObject_INIT_VAR(op, &PyString_Type, size);
     ^~~~~~~~~~~~~~~~~
In file included from ../Include/Python.h:78,
                 from ../Objects/structseq.c:4:
../Objects/structseq.c: In function ‘PyStructSequence_InitType’:
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Objects/structseq.c:504:15: note: in expansion of macro ‘PyMem_NEW’
     members = PyMem_NEW(PyMemberDef, n_members-n_unnamed_members+1);
               ^~~~~~~~~
../Objects/stringobject.c: In function ‘string_concat’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Include/objimpl.h:166:29: note: in expansion of macro ‘PyObject_INIT’
     ( Py_SIZE(op) = (size), PyObject_INIT((op), (typeobj)) )
                             ^~~~~~~~~~~~~
../Objects/stringobject.c:1064:5: note: in expansion of macro ‘PyObject_INIT_VAR’
     PyObject_INIT_VAR(op, &PyString_Type, size);
     ^~~~~~~~~~~~~~~~~
../Objects/stringobject.c: In function ‘string_repeat’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Include/objimpl.h:166:29: note: in expansion of macro ‘PyObject_INIT’
     ( Py_SIZE(op) = (size), PyObject_INIT((op), (typeobj)) )
                             ^~~~~~~~~~~~~
../Objects/stringobject.c:1106:5: note: in expansion of macro ‘PyObject_INIT_VAR’
     PyObject_INIT_VAR(op, &PyString_Type, size);
     ^~~~~~~~~~~~~~~~~
../Objects/structseq.c: In function ‘structseq_repr’:
../Objects/structseq.c:257:5: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
     strncpy(pbuf, typ->tp_name, len);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Objects/structseq.c:255:11: note: length computed here
     len = strlen(typ->tp_name) > TYPE_MAXSIZE ? TYPE_MAXSIZE :
           ^~~~~~~~~~~~~~~~~~~~
In file included from ../Include/Python.h:81,
                 from ../Objects/typeobject.c:3:
../Objects/typeobject.c: In function ‘PyType_GenericAlloc’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Objects/typeobject.c:794:9: note: in expansion of macro ‘PyObject_INIT’
         PyObject_INIT(obj, type);
         ^~~~~~~~~~~~~
In file included from ../Include/Python.h:78,
                 from ../Objects/typeobject.c:3:
../Objects/typeobject.c: In function ‘pmerge’:
../Objects/typeobject.c:1510:44: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
     remain = (int *)PyMem_MALLOC(SIZEOF_INT*to_merge_size);
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
In file included from ../Include/Python.h:81,
                 from ../Objects/unicodeobject.c:43:
../Objects/unicodeobject.c: In function ‘_PyUnicode_New’:
../Include/objimpl.h:164:66: warning: right-hand operand of comma expression has no effect [-Wunused-value]
     ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../Objects/unicodeobject.c:350:9: note: in expansion of macro ‘PyObject_INIT’
         PyObject_INIT(unicode, &PyUnicode_Type);
         ^~~~~~~~~~~~~
In file included from ../Include/Python.h:78,
                 from ../Python/bltinmodule.c:3:
../Python/bltinmodule.c: In function ‘builtin_map’:
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Python/bltinmodule.c:975:17: note: in expansion of macro ‘PyMem_NEW’
     if ((seqs = PyMem_NEW(sequence, n)) == NULL) {
                 ^~~~~~~~~
In file included from ../Include/Python.h:78,
                 from ../Python/getargs.c:4:
../Python/getargs.c: In function ‘convertsimple’:
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Python/getargs.c:1122:27: note: in expansion of macro ‘PyMem_NEW’
                 *buffer = PyMem_NEW(char, size + 1);
                           ^~~~~~~~~
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Python/getargs.c:1170:23: note: in expansion of macro ‘PyMem_NEW’
             *buffer = PyMem_NEW(char, size + 1);
                       ^~~~~~~~~
In file included from ../Include/Python.h:78,
                 from ../Python/import.c:4:
../Python/import.c: In function ‘_PyImport_Init’:
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Python/import.c:165:15: note: in expansion of macro ‘PyMem_NEW’
     filetab = PyMem_NEW(struct filedescr, countD + countS + 1);
               ^~~~~~~~~
../Python/import.c: In function ‘PyImport_ExtendInittab’:
../Include/pymem.h:110:34: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  (type *) PyMem_REALLOC((p), (n) * sizeof(type)) )
                                  ^
../Include/pymem.h:77:21: note: in definition of macro ‘PyMem_REALLOC’
     : realloc((p), (n) ? (n) : 1))
                     ^
../Python/import.c:3469:5: note: in expansion of macro ‘PyMem_RESIZE’
     PyMem_RESIZE(p, struct _inittab, i+n+1);
     ^~~~~~~~~~~~
In file included from ../Include/Python.h:78,
                 from ../Python/marshal.c:9:
../Python/marshal.c: In function ‘r_object’:
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Python/marshal.c:854:18: note: in expansion of macro ‘PyMem_NEW’
         buffer = PyMem_NEW(char, n);
                  ^~~~~~~~~
../Python/random.c:290:1: warning: ‘dev_urandom_close’ defined but not used [-Wunused-function]
 dev_urandom_close(void)
 ^~~~~~~~~~~~~~~~~
../Python/random.c:198:1: warning: ‘dev_urandom_python’ defined but not used [-Wunused-function]
 dev_urandom_python(char *buffer, Py_ssize_t size)
 ^~~~~~~~~~~~~~~~~~
../Python/random.c:167:1: warning: ‘dev_urandom_noraise’ defined but not used [-Wunused-function]
 dev_urandom_noraise(unsigned char *buffer, Py_ssize_t size)
 ^~~~~~~~~~~~~~~~~~~
../Python/marshal.c: In function ‘PyMarshal_WriteLongToFile’:
../Python/marshal.c:65:35: warning: ‘wf.ptr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                       else if ((p)->ptr != (p)->end) *(p)->ptr++ = (c); \
                                   ^~
../Python/marshal.c:65:47: warning: ‘wf.end’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                       else if ((p)->ptr != (p)->end) *(p)->ptr++ = (c); \
                                               ^~
../Python/marshal.c:72:10: warning: ‘wf.str’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (p->str == NULL)
         ~^~~~~
../Python/pystrtod.c: In function ‘format_float_short’:
../Python/pystrtod.c:1007:13: warning: ‘strncpy’ output truncated before terminating nul copying 3 bytes from a string of the same length [-Wstringop-truncation]
             strncpy(p, "ERR", 3);
             ^~~~~~~~~~~~~~~~~~~~
../Modules/getpath.c: In function ‘calculate_path’:
../Modules/getpath.c:491:17: warning: ‘strncpy’ output may be truncated copying 4096 bytes from a string of length 4096 [-Wstringop-truncation]
                 strncpy(argv0_path, tmpbuffer, MAXPATHLEN);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../Include/Python.h:78,
                 from ../Modules/posixmodule.c:28:
../Modules/posixmodule.c: In function ‘posix_execv’:
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Modules/posixmodule.c:3199:16: note: in expansion of macro ‘PyMem_NEW’
     argvlist = PyMem_NEW(char *, argc+1);
                ^~~~~~~~~
../Modules/posixmodule.c: In function ‘posix_execve’:
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Modules/posixmodule.c:3275:16: note: in expansion of macro ‘PyMem_NEW’
     argvlist = PyMem_NEW(char *, argc+1);
                ^~~~~~~~~
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Modules/posixmodule.c:3296:15: note: in expansion of macro ‘PyMem_NEW’
     envlist = PyMem_NEW(char *, i + 1);
               ^~~~~~~~~
../Include/pymem.h:97:30: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  ( (type *) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
../Include/pymem.h:75:15: note: in definition of macro ‘PyMem_MALLOC’
     : malloc((n) ? (n) : 1))
               ^
../Modules/posixmodule.c:3338:13: note: in expansion of macro ‘PyMem_NEW’
         p = PyMem_NEW(char, len);
             ^~~~~~~~~
In function ‘read_directory’,
    inlined from ‘zipimporter_init’ at ../Modules/zipimport.c:129:21:
../Modules/zipimport.c:841:9: warning: ‘strncpy’ output may be truncated copying between 0 and 4095 bytes from a string of length 4100 [-Wstringop-truncation]
         strncpy(path + length + 1, name, MAXPATHLEN - length - 1);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Modules/_math.c:25:21: warning: ‘zero’ defined but not used [-Wunused-const-variable=]
 static const double zero = 0.0;
                     ^~~~
../Python/ast.c: In function ‘ast_for_print_stmt’:
../Python/ast.c:2285:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if (!dest)
         ^~
../Python/ast.c:2287:13: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
             start = 4;
             ^~~~~
../Python/compile.c: In function ‘_Py_Mangle’:
../Python/compile.c:236:5: warning: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
     strncpy(buffer+1, p, plen);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
../Python/compile.c:222:12: note: length computed here
     plen = strlen(p);
            ^~~~~~~~~
/usr/bin/ld: libpython2.7.a(posixmodule.o): in function `posix_tmpnam':
/run/media/paullee/Data_40G_EXT3/Temp_Download/IfcOpenShell/IfcOpenShell-master/build/Linux/x86_64/build/Python-2.7.12/build/../Modules/posixmodule.c:7631: warning: the use of `tmpnam_r' is dangerous, better use `mkstemp'
/usr/bin/ld: libpython2.7.a(posixmodule.o): in function `posix_tempnam':
/run/media/paullee/Data_40G_EXT3/Temp_Download/IfcOpenShell/IfcOpenShell-master/build/Linux/x86_64/build/Python-2.7.12/build/../Modules/posixmodule.c:7578: warning: the use of `tempnam' is dangerous, better use `mkstemp'
/bin/sh: line 5: 11268 Segmentation fault      (core dumped) ./python -E -S -m sysconfig --generate-posix-vars
make: *** [Makefile:544: pybuilddir.txt] Error 1

----------------------------------------------------------------------
Traceback (most recent call last):
  File "./build-all.py", line 515, in <module>
    build_dependency("python-%s%s" % (PYTHON_VERSION,abi_tag), "autoconf", PYTHON_CONFIGURE_ARGS + [unicode_conf], "http://www.python.org/ftp/python/%s/" % (PYTHON_VERSION,), "Python-%s.tgz" % (PYTHON_VERSION,))
  File "./build-all.py", line 378, in build_dependency
    __check_call__([make, "-j%s" % (IFCOS_NUM_BUILD_PROCS,)], cwd=extract_build_dir)
  File "./build-all.py", line 230, in __check_call__
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `make -j5` returned exit code 2
[paullee@localhost nix]$ 

```

**Comment by aothms** [comment]
What if you change 2.7.12 to 2.7.16 (released today accidentally!) ?

The python versions are a bit outdated anyway and probably need to include a 3.7.x, but that's another concern.

**Comment by paullee0** [comment]
Thanks, however, other errors now ... just capture last few tens of lines below..
```

/run/media/paullee/Data_40G_EXT3/Temp_Download/IfcOpenShell/IfcOpenShell-master/build/Linux/x86_64/install/boost-1.59.0/boost/function/function_template.hpp:727:7:   required from ‘boost::function1<R, T1>::function1(Functor, typename boost::enable_if_c<(! boost::is_integral<Functor>::value), int>::type) [with Functor = std::_Bind<bool (IfcGeom::entity_filter::*(const IfcGeom::entity_filter*, std::_Placeholder<1>))(Ifc2x3::IfcProduct*) const>; R = bool; T0 = Ifc2x3::IfcProduct*; typename boost::enable_if_c<(! boost::is_integral<Functor>::value), int>::type = int]’
/run/media/paullee/Data_40G_EXT3/Temp_Download/IfcOpenShell/IfcOpenShell-master/build/Linux/x86_64/install/boost-1.59.0/boost/function/function_template.hpp:1073:16:   required from ‘boost::function<R(T0)>::function(Functor, typename boost::enable_if_c<(! boost::is_integral<Functor>::value), int>::type) [with Functor = std::_Bind<bool (IfcGeom::entity_filter::*(const IfcGeom::entity_filter*, std::_Placeholder<1>))(Ifc2x3::IfcProduct*) const>; R = bool; T0 = Ifc2x3::IfcProduct*; typename boost::enable_if_c<(! boost::is_integral<Functor>::value), int>::type = int]’
/run/media/paullee/Data_40G_EXT3/Temp_Download/IfcOpenShell/IfcOpenShell-master/src/ifcconvert/../ifcconvert/../ifcgeom/../ifcgeom/IfcGeomFilter.h:287:101:   required from here
/run/media/paullee/Data_40G_EXT3/Temp_Download/IfcOpenShell/IfcOpenShell-master/build/Linux/x86_64/install/boost-1.59.0/boost/function/function_base.hpp:308:54: warning: placement new constructing an object of type ‘boost::detail::function::functor_manager_common<std::_Bind<bool (IfcGeom::entity_filter::*(const IfcGeom::entity_filter*, std::_Placeholder<1>))(Ifc2x3::IfcProduct*) const> >::functor_type’ {aka ‘std::_Bind<bool (IfcGeom::entity_filter::*(const IfcGeom::entity_filter*, std::_Placeholder<1>))(Ifc2x3::IfcProduct*) const>’} and size ‘24’ in a region of type ‘char’ and size ‘1’ [-Wplacement-new=]
/usr/bin/ld: /run/media/paullee/Data_40G_EXT3/Temp_Download/IfcOpenShell/IfcOpenShell-master/build/Linux/x86_64/install/occt-7.3.0/lib/libTKBool.a(BRepFill_ShapeLaw.cxx.o)(.debug_ranges+0xe98e000081b8): reloc against `.text._ZN28GeomFill_HArray1OfSectionLawD0Ev': error 4
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/IfcGeomServer.dir/build.make:242: IfcGeomServer] Error 1
make[1]: *** [CMakeFiles/Makefile2:144: CMakeFiles/IfcGeomServer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: /run/media/paullee/Data_40G_EXT3/Temp_Download/IfcOpenShell/IfcOpenShell-master/build/Linux/x86_64/install/occt-7.3.0/lib/libTKBool.a(BRepFill_ShapeLaw.cxx.o)(.debug_ranges+0xe98e000081b8): reloc against `.text._ZN28GeomFill_HArray1OfSectionLawD0Ev': error 4
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/IfcConvert.dir/build.make:398: IfcConvert] Error 1
make[1]: *** [CMakeFiles/Makefile2:69: CMakeFiles/IfcConvert.dir/all] Error 2
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
make[2]: *** [examples/CMakeFiles/IfcOpenHouse.dir/build.make:233: examples/IfcOpenHouse] Error 1
make[2]: *** Deleting file 'examples/IfcOpenHouse'
make[1]: *** [CMakeFiles/Makefile2:279: examples/CMakeFiles/IfcOpenHouse.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

----------------------------------------------------------------------
Traceback (most recent call last):
  File "./build-all.py", line 565, in <module>
    __check_call__([make, "-j%s" % (IFCOS_NUM_BUILD_PROCS,)], cwd=executables_dir)
  File "./build-all.py", line 235, in __check_call__
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `make -j5` returned exit code 2

```

**Comment by paullee0** [comment]
Another attempt... 

```

Fetching boost-1.59.0...   
Download '/run/media/paullee/Data_40G_EXT3/Temp_Download/IfcOpenShell/IfcOpenShell-master/build/Linux/x86_64/build/boost_1_59_0.tar.bz2' already exists, assuming it's an undamaged download and that it has been extracted if possible, skipping

Configuring boost-1.59.0...
Traceback (most recent call last):
  File "./build-all.py", line 526, in <module>
    build_dependency("boost-%s" % (BOOST_VERSION,), mode="bjam", build_tool_args=["--stagedir=%s/install/boost-%s" % (DEPS_DIR, BOOST_VERSION), "--with-system", "--with-program_options", "--with-regex", "--with-thread", "--with-date_time", "--with-iostreams", "link=static"]+BOOST_ADDRESS_MODEL+list(map(str_concat("cxxflags"), CXXFLAGS.strip().split(' '))) + list(map(str_concat("linkflags"), LDFLAGS.strip().split(' '))) + ["stage", "-s", "NO_BZIP2=1"], download_url="http://downloads.sourceforge.net/project/boost/boost/%s/" % (BOOST_VERSION,), download_name="boost_%s.tar.bz2" % (BOOST_VERSION_UNDERSCORE,))
  File "./build-all.py", line 389, in build_dependency
    __check_call__([bash, "./bootstrap.sh"], cwd=extract_dir)
  File "./build-all.py", line 235, in __check_call__
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `bash ./bootstrap.sh` returned exit code 1
```
```

----------------------------------------------------------------------
./bootstrap.sh: line 196: ./tools/build/src/engine/build.sh: No such file or directory

----------------------------------------------------------------------



```

**Comment by paullee0** [comment]
OK, it seems I remove everything in ./build and start over again and it now build.

Thanks!

**Comment by aothms** [comment]
With still a change from 2.7.12 to 2.7.16? Pull Request would be great in that case.

**Comment by paullee0** [comment]
Yes, 2.7.12 to 2.7.16.

Would it then break on other platform?

**Comment by aothms** [comment]
> Would it then break on other platform?

No, I don't think so. I have a lot of faith in the Python devs.

**Comment by paullee0** [comment]
Thanks, done #558

**Comment by Moult** [comment]
Seems fixed, so closing.
