### ISSUE TITLE
Allow ProjectLibre XML files to be imported into Bonsai

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5556]
As a free software it could be useful to allow ProjectLibre XML export files (compatible with MS Project) to be imported in Bonsai, especially for small scale projects it could be a viable solution.

Thanks

**Comment by sboddy** [comment]
ProjectLibre haven't released an update to their desktop app in nearly 4 years, nor any commits to the repository. They appear to have pivoted to paid cloud-only closed source SaaS. They don't _seem_ to have any pricing info on the site either, nor does there seem to be a community edition. All a bit opaque.

https://www.openproject.org/ on the other hand, can be self hosted, has a community edition, plus paid supported licensing. Open Source in github. Frequent releases. It has clear, open pricing up front. The documentation and API docs are freely available and extensive. It already has several integrations with other projects. It even talks about BIM/BCF, which in my very limited understanding, might be kinda useful to Bonsai? About the only "ding" on them I can see is that they don't use github for issues. Instead you have to register on their community portal to use their own dogfooded project software to report issues, although not to view and browse them.

I have no skin in the game, I just think OpenProject is a better fit based on what I've seen so far.

**Comment by steverugi** [comment]
thanks for your input, I tried to access it in the past but, as you pointed out, is not a real (despite its name) open software, much less a free one. 
I'd guess Bonsai's 4D is not massivily urgent in the development chain, perhaps a bit more advanced interface within it would do the job for a small scale project

**Comment by steverugi** [comment]
Regardless of import capabilities in Bonsai I think it would be a good start to export to .xml and import the work schedule back in Bonsai.
I tried with a simple work schedule (both .ifc and .xml attached), exported it as MS Project.xml and import it back and it generated an error


[PoWtest.xml.txt](https://github.com/user-attachments/files/19774334/PoWtest.xml.txt)

[PoWtest.ifc.txt](https://github.com/user-attachments/files/19774359/PoWtest.ifc.txt)


![Image](https://github.com/user-attachments/assets/df6b0161-50cb-44ee-a933-02684b1b0d97)

thanks

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.11
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
blender_version: 4.4.0
bonsai_version: 0.8.2-alpha250414
bonsai_commit_hash: b59e5b0
bonsai_commit_date: 2025-04-14T18:59:47+05:00
last_actions: 
# ifcopenshell.api: sequence.add_task_time
>>> {"task": {"cast_type": "entity_instance", "value": 71, "Name": "task1"}}
# ifcopenshell.api: sequence.edit_task_time
>>> {"task_time": {"cast_type": "entity_instance", "value": 74, "Name": null}, "attributes": "{'ScheduleStart': datetime.datetime(2025, 5, 1, 0, 0)}"}
# ifcopenshell.api: sequence.edit_task_time
>>> {"task_time": {"cast_type": "entity_instance", "value": 74, "Name": null}, "attributes": "{'ScheduleDuration': datetime.timedelta(days=5)}"}
# ifcopenshell.api: sequence.cascade_schedule
>>> {"task": {"cast_type": "entity_instance", "value": 71, "Name": "task1"}}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# operator: BIM_OT_assign_predecessor
# ifcopenshell.api: sequence.assign_sequence
>>> {"relating_process": {"cast_type": "entity_instance", "value": 71, "Name": "task1"}, "related_process": {"cast_type": "entity_instance", "value": 73, "Name": "task2"}}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: sequence.cascade_schedule
>>> {"task": {"cast_type": "entity_instance", "value": 71, "Name": "task1"}}
# operator: BIM_OT_enable_editing_task_time
# ifcopenshell.api: sequence.add_task_time
>>> {"task": {"cast_type": "entity_instance", "value": 73, "Name": "task2"}}
# operator: BIM_OT_edit_task_time
# ifcopenshell.api: sequence.edit_task_time
>>> {"task_time": {"cast_type": "entity_instance", "value": 79, "Name": null}, "attributes": "{'Name': None, 'DataOrigin': None, 'UserDefinedDataOrigin': None, 'DurationType': None, 'ScheduleDuration': None, 'ScheduleStart': None, 'ScheduleFinish': None, 'EarlyStart': None, 'EarlyFinish': None, 'LateStart': None, 'LateFinish': None, 'FreeFloat': None, 'TotalFloat': None, 'IsCritical': None, 'StatusTime': None, 'ActualDuration': None, 'ActualStart': None, 'ActualFinish': None, 'RemainingTime': None, 'Completion': None}"}
# ifcopenshell.api: sequence.edit_task_time
>>> {"task_time": {"cast_type": "entity_instance", "value": 79, "Name": null}, "attributes": "{'ScheduleDuration': datetime.timedelta(days=2)}"}
# ifcopenshell.api: sequence.cascade_schedule
>>> {"task": {"cast_type": "entity_instance", "value": 73, "Name": "task2"}}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# operator: BIM_OT_save_project
# operator: BIM_OT_import_msp
last_error: Traceback (most recent call last):
  File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 458, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\sequence\operator.py", line 794, in _execute
    msp2ifc.execute()
  File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\.local\lib\python3.11\site-packages\ifc4d\msp2ifc.py", line 42, in execute
    self.parse_xml()
  File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\.local\lib\python3.11\site-packages\ifc4d\msp2ifc.py", line 54, in parse_xml
    self.parse_task_xml(project)
  File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\.local\lib\python3.11\site-packages\ifc4d\msp2ifc.py", line 80, in parse_task_xml
    wbs_id = task.find("pr:WBS", self.ns).text
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

ifc: PoWtest.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.2-alpha250414
originating_system: Bonsai 0.8.2-alpha250414-b59e5b0
```

**Comment by BIMvoice** [comment]
This should work today. ProjectLibre exports MS-Project-compatible XML, and Bonsai has both directions of that format on current `v0.8.0`: `Import MSP` (`bim.import_msp`, "Import provided .xml MSP file", backed by `ifc4d.msp2ifc.MSP2Ifc`) and `Export MSP` (`ifc4d.ifc2msp.Ifc2Msp`) — which also covers the export-then-reimport round trip from the last comment. Worth a try with a ProjectLibre-exported XML; if PL's dialect trips the importer somewhere, that concrete failure would make a good focused issue. Otherwise this can be closed as available.

**Comment by steverugi** [comment]
@BIMvoice  Export from Bonsai to xml can open in ProjectLibre
not possible to import xlm files in Bonsai, not even the same one exported from Bonsai itself

thanks

**Comment by BIMvoice** [comment]
@steverugi thanks for the retest — you found a real bug, and your 2025 attachment let me pin it down. The importer (`MSP2Ifc`) required XML elements on every task (`WBS`, `Duration`, `Start`, `Finish`, `Priority`, `CalendarUID`) that Bonsai's own exporter never writes on summary tasks, so any Bonsai-exported schedule crashed on reimport with `AttributeError` — exactly what you saw, and your `PoWtest.xml` reproduces it on the first task.

Fixed in #8285: those elements are now optional. Verified with your file — it imports cleanly (Project, task1, task2 with correct dates, P5D/P2D durations, and the task1→task2 predecessor link) — plus a full export→reimport round trip. Once that merges into a daily build, `Import MSP` should work both for Bonsai round trips and for ProjectLibre's sparser XML, which is what this issue originally asked for.

**Comment by steverugi** [comment]
thanks, I am going to test it as soon as merged, much appreciated
