### ISSUE TITLE
Use prop_with_search when searching external styles

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5569]
Would be nice to use `prop_with_search` when searching external styles...

I tried
`prop_with_search(layout, self, "data_block", text="")`
but got the following error. 

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\operator.py", line 897, in invoke
    items = get_enum_items(self.data, self.prop_name, context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\helper.py", line 269, in get_enum_items
    prop = data.__annotations__[prop_name]
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BIM_OT_browse_external_style' object has no attribute '__annotations__'

```

![image](https://github.com/user-attachments/assets/65b0d84a-3462-479a-a8e0-2a036b77e13d)

**Comment by theoryshaw** [comment]
Thanks @Andrej730,  I wouldn't have gotten this in a million years. :)
