### ISSUE TITLE
Selecting some objects takes a noticeable amount of time when the BIM Object Information panel is open

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5581]
![Animation3](https://github.com/user-attachments/assets/fe62e7db-bfbf-47fa-bcea-a6ef719cf4d6)

When the object information panel is open, selecting objects takes noticeably more time than when the Project Overview panel is open (as an example). I guess because the entity information needs to be populated, but it can be slightly annoying when navigating a project, and it makes it look like the responsiveness is not optimal.

Can anything be done to throttle the querying of information, or maybe delay populating the fields until after the item is selected to at least give a feedback to the user that the item was correctly selected ? Or maybe add a cache system so that selecting an item twice re-uses some of the information, or only re-fetch it if it has been modified.

**Comment by Gorgious56** [comment]
I just tested on a brand new ifc project, created a few IfcActuator elements and the hiccups occur so I don't think project size matters much to the problem

**Comment by Andrej730** [comment]
I've tried 1024 actuators and I don't know if I see it or not 😅
[1024_actuators.ifc.txt](https://github.com/user-attachments/files/17394882/1024_actuators.ifc.txt)

Left Blender is the way last build works, right - with `active_object_callback` code commented out.

https://github.com/user-attachments/assets/88f9fa74-137a-4db0-a279-f54ee8356d88

**Comment by Gorgious56** [comment]
Thanks for testing this out. It doesn't look like it depends on the number of objects. A better comparison would be with the Object information panel open and another with the project info panel open. It's a hiccup, not really too bad of a lag, I don't know if it's in the dozens of ms or hundred of ms. Maybe it's just my OCD or my computer (Windows / Server) configuration that does this.

**Comment by Moult** [comment]
Late to the party, but @Gorgious56 is it possible to share your original file?

**Comment by Gorgious56** [comment]
Hey @Moult ! I think the original problem is now fixed, somehow. At least I don't think there is a noticeable difference between object or material subpanel vs any other subpanel. There is still a hiccup problem when dealing with many objects and especially with objects with dense geometry, but I don't think it has to do specifically with Bonsai. 

After further testing I think it's a Blender related thing when there is a lot of geometry in the scene. The key thing here I think is that I have a lot of vanilla Blender objects which have a lot of geometry in the scene. If I open the ifc file on a brand new blender instance there is no hiccup. 

If anything has to be done on bonsai's side I would look into active_object_callback. When disabling Bonsai I got these errors in the console when clicking on objects. Note it's trying to refresh UI data even when my properties editor is not showing the Scene context.

```
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\handler.py", line 97, in active_object_callback
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\handler.py", line 225, in refresh_ui_data
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 115, in get_document_props
AttributeError: 'Scene' object has no attribute 'DocProperties'
File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\handler.py", line 96, in active_object_callback
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\handler.py", line 97, in active_object_callback
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\handler.py", line 225, in refresh_ui_data
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 115, in get_document_props
AttributeError: 'Scene' object has no attribute 'DocProperties'
File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\handler.py", line 96, in active_object_callback
```

I'm OK with this issue being closed for the time being, since original problem seems to be fixed and the current problem is most likely on Blender's side.

**Comment by BIMvoice** [comment]
Housekeeping: per the author's own last comment the original problem (selection lag with the Object Information panel open) is fixed, and the remaining hiccup with dense geometry was traced to Blender itself rather than Bonsai. Safe to close as resolved.
