### ISSUE TITLE
ifcopenshell duplicating representation material styles

### ISSUE THREAD

**Issue by RVRKU** [IfcOpenShell/IfcOpenShell#5583]
Hi, Fresh install of Blender, 
cannot open the project (275 MB) crash every time. 
Any ideas?
Thanks
RVRKU

```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 751, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 832, in execute
    ifc_importer.execute()
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 250, in execute
    self.create_spatial_elements()
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 625, in create_spatial_elements
    self.create_generic_elements(self.spatial_elements, unselectable=True)
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 646, in create_generic_elements
    products = self.create_products(elements, settings=settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 757, in create_products
    self.create_product(product, shape)
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 888, in create_product
    self.material_creator.create(element, obj, mesh)
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 78, in create
    self.assign_material_slots_to_faces()
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 150, in assign_material_slots_to_faces
    slot_index = len(self.mesh.materials) - 1
                 ^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: error return without exception set
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: ICB CMNP 241016.ifc
schema: IFC4
preprocessor_version: The EXPRESS Data Manager Version 5.02.0100.09 : 18 Aug 2016
originating_system: IFC file generated by GRAPHISOFT ARCHICAD 25.0.0 FRA FULL Macintosh version (IFC add-on version: 7000 FRA FULL).
```

**Comment by Andrej730** [comment]
@RVRKU can you please share the ifc file for debugging? Also please try the latest version of Bonsai from the releases - https://github.com/IfcOpenShell/IfcOpenShell/releases

If it's private you can share it using https://docs.google.com/forms/d/1CVVw98Sb5GDZZb4NYjdCrg3JLpREzSSes2Xgq0Bt5I0/edit?ts=66ebc4dc - only ifcopenshell developers will have access to it.

**Comment by RVRKU** [comment]
@Andrej730 , I can not share it. the seize is greater than what GGdocs allows. 
the seize of the file is 275Mb  IFC 4.

**Comment by Andrej730** [comment]
@RVRKU oh, okay. Can you send it to my email? It's andrej730@icloud.com

**Comment by Andrej730** [comment]
Got the file, never seen this error before! This obscure error actually means that object end up having 70k materials instead when Blender limit is 32k materials for 1 mesh. [Reported it to Blender](https://projects.blender.org/blender/blender/issues/129155) but that really only indicates to some other issue.

The real issue is that some representation with 70k items end up having 70k materials though there only 39 of them are unique.
I was able to reproduce this issue in a different project.

On the latest commit the script below outputs `[100, 217] 2 materials`. But if I use latest build from IfcOpenBot https://github.com/IfcOpenBot/IfcOpenShell/commit/fdf4749dd77078075dc2eef869e00eb7f2177606 I get `[100, 217, 100] 3 materials`. So issue seems to be fixed (probably in 189bcd5) and we just need to update ifcopenshell build in Bonsai. @aothms can you please start a new build?

[cube.ifc.txt](https://github.com/user-attachments/files/17413045/cube.ifc.txt)

```python
import ifcopenshell
import ifcopenshell.geom

ifc_file = ifcopenshell.open(r"cube.ifc")
element = ifc_file.by_guid("1AGUJxNbH5jRisNaWQIp7a")
print('finished loading')

settings = ifcopenshell.geom.settings()
settings.set("apply-default-materials", False)

shape = ifcopenshell.geom.create_shape(settings, element)
materials = shape.geometry.materials
print([m.instance_id() for m in materials])
print(len(materials), 'materials')
```

**Comment by aothms** [comment]
@Andrej730 spot on. coincidently this was recently fixed. build on its way

**Comment by RVRKU** [comment]
@Andrej730, @aothms, Thanks a lot for the work.

**Comment by Andrej730** [comment]
Issue is fixed, you can try the latest Bonsai build in the releases - https://github.com/IfcOpenShell/IfcOpenShell/releases
