### ISSUE TITLE
Error after tabbing into parametric roof

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5585]
If I tab into the following roof, i get the following error, when trying to tab out...

file: https://hub.openingdesign.com/OpeningDesign/Lake_Kegonsa_Renovation/src/commit/c4c44b3a80d904953a6c2b4222085447c83417af/Open/Models/BlenderBIM/Lake_Kegonsa_Renovation.ifc

might be related to #5577 and #5451

Not sure why some many representations are breaking in this file. 
@chopinregis, any clues? 

https://github.com/user-attachments/assets/758ce64c-4fee-4774-9892-2206bd04d96b

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 406, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1913, in _invoke
    bpy.ops.bim.finish_editing_roof_path()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\roof.py", line 766, in _execute
    update_roof_modifier_bmesh(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\roof.py", line 435, in update_roof_modifier_bmesh
    props = obj.BIMRoofProperties
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Context' object has no attribute 'BIMRoofProperties'
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109

```

**Comment by Andrej730** [comment]
No, it's a different bug I created just today ☺️
