### ISSUE TITLE
Error duplicating IfcCoverType in Wall Tool

### ISSUE THREAD

**Issue by chopinregis** [IfcOpenShell/IfcOpenShell#5591]
When selecting and object type for duplication in the Object Meta data panel window, it cases an error. 

![Snipaste_2024-10-17_13-29-33](https://github.com/user-attachments/assets/36dd4dc1-0b36-41b9-af19-2a8712a6da14)

![Snipaste_2024-10-17_13-29-59](https://github.com/user-attachments/assets/da26b374-9ead-4f5e-b780-48d1b8aaeab9)

````
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
blender_version: 4.2.2 LTS
bonsai_version: 0.8.1-alpha241017
bonsai_commit_hash: 0e5008d
last_actions: 
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 3856268, "Name": "NORTH SECTION"}, "representation": {"cast_type": "entity_instance", "value": 3878199, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 3878199, "Name": null}}
# operator: BIM_OT_change_extrusion_depth
# ifcopenshell.api: geometry.add_axis_representation
>>> {"context": {"cast_type": "entity_instance", "value": 35, "Name": null}, "axis": "[Vector((-5.750884156441316e-06, -2.179825969506055e-06)), Vector((3.873117446899414, -3.395660314708948e-06))]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 3517909, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 3517969, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 3517969, "Name": null}}
# ifcopenshell.api: geometry.add_wall_representation
>>> {"context": {"cast_type": "entity_instance", "value": 24, "Name": null}, "length": "3.8731232066671257", "height": "2.41279673576355", "x_angle": "0", "offset": "0.0", "thickness": "0.12065010597705846", "clippings": "[]", "booleans": "[]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 3517909, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 3517979, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 3517979, "Name": null}}
# operator: BIM_OT_change_extrusion_depth
# ifcopenshell.api: geometry.add_axis_representation
>>> {"context": {"cast_type": "entity_instance", "value": 35, "Name": null}, "axis": "[Vector((-1.751814124872908e-06, 5.153031452209689e-06)), Vector((0.3809949457645416, 5.095503183838446e-06))]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 3863071, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 3863115, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 3863115, "Name": null}}
# ifcopenshell.api: geometry.add_wall_representation
>>> {"context": {"cast_type": "entity_instance", "value": 24, "Name": null}, "length": "0.3809966989071331", "height": "2.41279673576355", "x_angle": "0", "offset": "0.0", "thickness": "0.031576061367988704", "clippings": "[]", "booleans": "[]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 3863071, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 3863118, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 3863118, "Name": null}}
# operator: BIM_OT_save_project
# operator: BIM_OT_duplicate_type
# ifcopenshell.api: root.copy_class
>>> {"product": {"cast_type": "entity_instance", "value": 3856552, "Name": "CEILING 6 1/8 - D5/8-J5.5 - INSULATION"}}
# operator: BIM_OT_load_type_thumbnails
last_error: Traceback (most recent call last):
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\regis\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\type\operator.py", line 318, in _execute
    context.scene.BIMModelProperties.ifc_class = new.is_a()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "IfcCoveringType" not found in ('IfcWallType')

ifc: Lake_Kegonsa_Renovation.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha241017
originating_system: Bonsai 0.8.1-alpha241017-0e5008d
````

**Comment by theoryshaw** [comment]
i get this error too.
