### ISSUE TITLE
Error after 'remesh' and 'triangulate' modifiers

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5600]
If i use the 'remesh' and then 'triangulate' modifiers and then apply them, followed by a 'manually save representation', i get the following error when i try to tab into the geometry. 

file: https://hub.openingdesign.com/OpeningDesign/Lake_Kegonsa_Renovation/src/commit/7882e1709ff98ba56ff215685228c379951f663e/Open/Models/BlenderBIM/Lake_Kegonsa_Renovation.ifc

https://github.com/user-attachments/assets/bd03c2c4-7705-4af0-a290-a0b57bb5afcf

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 406, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1736, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\ifc.py", line 255, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1675, in _execute
    tool.Geometry.apply_item_ids_as_vertex_groups(obj)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 257, in apply_item_ids_as_vertex_groups
    vertices_by_item_ids[item_id].extend(polygon_verts[i].tolist())
                                         ~~~~~~~~~~~~~^^^
IndexError: index 1200 is out of bounds for axis 0 with size 1200

```

**Comment by theoryshaw** [comment]
Sorry, this seems fixed.  Forgot i was on 9/21.
