### ISSUE TITLE
Gantt diagram not working properly

### ISSUE THREAD

**Issue by Breogan10** [IfcOpenShell/IfcOpenShell#5617]
I'm trying to use (&test) the BONSAI 4D capabilities, focusing on Gantt diagram capabilities.

To do that, I'm using a test project (attached), and I've made several observations:
[20241021 Gantt_error.zip](https://github.com/user-attachments/files/17457265/20241021.Gantt_error.zip)

1. The generated Gantt in web UI looks really fine! It looks also fine generating it using latest BlenderBim version. But...
2. Baseline feature does not work as expected. The task sequence is lost while creating the baseline, rendering it useless.
3. Completion values (included as data in IfcTaskTime for each Task) are not shown in Gantt diagram. I've checked the java code, and I've found that there is an option to show a "completion" column; but it doesn't work. It's a pity because in bonsai web UI I've found that editing the values in the completion column, results in a very nice diagram!!! (althoug you can't save the changes).
4. No possibility to edit the format (the possibility of adding a logo would be great!). I've found that editing .svg drawings using Inkscape is quite straightforward; I expect that something similiar for this gantt diagrams is not possible, but would be fantastic!.
5. Exporting (to P6.xml) seems to work fine (please find attached the exported file), but when importing back, I've got this error:

Python: Traceback (most recent call last):
  File "C:\Users\_\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\sequence\operator.py", line 675, in execute
    p62ifc.execute()
  File "C:\Users\_\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifc4d\p62ifc.py", line 69, in execute
    self.parse_xml()
  File "C:\Users\_\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifc4d\p62ifc.py", line 98, in parse_xml
    self.parse_activity_xml(project)
  File "C:\Users\_\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifc4d\p62ifc.py", line 187, in parse_activity_xml
    "CalendarObjectId": activity.find("pr:CalendarObjectId", self.ns).text,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by theoryshaw** [comment]
@Ziad-I Can you confirm this is a bug? I have a feeling there's not many around that have their head into this?

**Comment by Ziad-I** [comment]
Hey @theoryshaw sorry for taking so long to reply, was quite busy the last month.
from my understanding regarding the points in the issue, I am not sure 2 and 5 since I am not very familiar with that part of the codebase (though they do sound like bugs).

for 3, it shouldn't be a bug,  it is more likely that the task completion is not being saved after edits due to it not being mapped in here
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/bonsai/bonsai/tool/web.py#L56
since we need to map the JavaScript package task attribute names to IFC task attributes names.

I am not sure about 4 since the current JavaScript package (JSGantt) we use for gantt charts is abit old, and is not really suitable for editing the chart. so we would need to find a better one, or do some workarounds.
