### ISSUE TITLE
IfcMaterial Custom Pset (IFC 4) doesn't work

### ISSUE THREAD

**Issue by MagdaKladz** [IfcOpenShell/IfcOpenShell#5647]
I'm trying to add custom property set to IfcMaterial (in Material Set Property Sets) but when I'm saving it - it doesn't work and my property set dissapears.

![image](https://github.com/user-attachments/assets/f7ce9938-ee82-4d6a-a111-2ef6076e1449)

And when I click on + in Custom Pset in Material Set Item Property Sets it shows this error:

````
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.8.1-alpha241026
bonsai_commit_hash: fc57a7b
last_actions: 
# ifcopenshell.api: pset.edit_pset
>>> {"pset": {"cast_type": "entity_instance", "value": 82665, "Name": "ggg"}, "name": "ggg", "properties": "{}", "pset_template": "None"}
# operator: BIM_OT_disable_pset_editing
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 1816, "Name": "MOS_Stained monolithic structural concrete (SLABS)"}, "pset": {"cast_type": "entity_instance", "value": 82665, "Name": "ggg"}}
# operator: BIM_OT_add_pset
# operator: BIM_OT_toggle_pset_expansion
# operator: BIM_OT_toggle_pset_expansion
# operator: BIM_OT_toggle_pset_expansion
# operator: BIM_OT_add_pset
# operator: BIM_OT_edit_pset
# ifcopenshell.api: pset.add_pset
>>> {"product": {"cast_type": "entity_instance", "value": 1816, "Name": "MOS_Stained monolithic structural concrete (SLABS)"}, "name": "My_Data"}
# ifcopenshell.api: pset.edit_pset
>>> {"pset": {"cast_type": "entity_instance", "value": 82666, "Name": "My_Data"}, "name": "My_Data", "properties": "{}", "pset_template": "None"}
# operator: BIM_OT_disable_pset_editing
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 1816, "Name": "MOS_Stained monolithic structural concrete (SLABS)"}, "pset": {"cast_type": "entity_instance", "value": 82666, "Name": "My_Data"}}
# operator: BIM_OT_add_pset
# operator: BIM_OT_add_pset
# operator: BIM_OT_edit_pset
# ifcopenshell.api: pset.add_pset
>>> {"product": {"cast_type": "entity_instance", "value": 1816, "Name": "MOS_Stained monolithic structural concrete (SLABS)"}, "name": "My_Data"}
# ifcopenshell.api: pset.edit_pset
>>> {"pset": {"cast_type": "entity_instance", "value": 82667, "Name": "My_Data"}, "name": "My_Data", "properties": "{'h': 2, 'MyProperty': 'Some Value'}", "pset_template": "None"}
# operator: BIM_OT_disable_pset_editing
# operator: BIM_OT_add_pset
last_error: Traceback (most recent call last):
  File "C:\Users\mkrolikowska\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 418, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mkrolikowska\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\pset\operator.py", line 191, in _execute
    core.add_pset(tool.Ifc, tool.Pset, tool.Blender, obj_name=self.obj, obj_type=self.obj_type)
  File "C:\Users\mkrolikowska\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\pset.py", line 57, in add_pset
    elements = [ifc.get().by_id(blender.get_obj_ifc_definition_id(obj_name, obj_type))]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mkrolikowska\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\file.py", line 482, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\mkrolikowska\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\file.py", line 467, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mkrolikowska\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 8871, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #0 not found

ifc: Project_UW_Faculty_of_Psychology_2024_09_12_IFC 4.ifc
schema: IFC4
preprocessor_version: ODA SDAI 24.6
originating_system: Autodesk Revit 24.2.0.63 (ENG) - IFC 24.2.0.49
````

**Comment by Andrej730** [comment]
@MagdaKladz Hi! Thanks for the bug report. This UI wasn't intended for IfcMaterials, only for material sets (material profiles, layers, etc). Now it's hidden for non-ifcmaterials and there is a button to quickly open object's material in Materials UI, see 4c93270adc740d70c0a5afb1efb3636f436bd9de.
