### ISSUE TITLE
ifcclash not working

### ISSUE THREAD

**Issue by ThisIsMonta** [IfcOpenShell/IfcOpenShell#5662]
Hello,
I followed the [ifcclash docs](https://docs.ifcopenshell.org/ifcclash.html) and tried to run it but nothing seems to work.

Can you guys provide more information to run it ?

**Comment by ThisIsMonta** [comment]
@Andrej730 

First i tried running the plugin via `python -m ifcclash ./clash_set.json`

And the set was : 

```
[
    {
        "name": "Clash Test 1",
        "a": [
            {
                "file": "./files/clash_test/test.ifc"
            }
        ],
        "b": [
            {
                "file": "./files/clash_test/test.ifc",
                "selector": "IfcWall",
                "mode": "i"
            }
        ]
    }
]
```

But i got this error : 

> Note: API not available due to missing dependencies: geometry.add_door_representation - No module named 'mathutils'
> Note: API not available due to missing dependencies: geometry.add_railing_representation - No module named 'mathutils'
> Note: API not available due to missing dependencies: geometry.add_representation - No module named 'bpy'
> Note: API not available due to missing dependencies: geometry.add_window_representation - No module named 'mathutils'
> Note: API not available due to missing dependencies: grid.create_axis_curve - No module named 'mathutils'
> Traceback (most recent call last):
>   File "FILES_PATH\.pyenv\pyenv-win\versions\3.10.0\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None,
>   File "FILES_PATH\.pyenv\pyenv-win\versions\3.10.0\lib\runpy.py", line 86, in _run_code exec(code, run_globals)
>   File "FILES_PATH\Ifc convert\ifcclash\ifcclash\__main__.py", line 25, in <module>from .ifcclash import Clasher, ClashSettings
>   File "FILES_PATH\Ifc convert\ifcclash\ifcclash\ifcclash.py", line 31, in <module> from typing import Optional, Literal, TypedDict, NotRequired
> ImportError: cannot import name 'NotRequired' from 'typing' (FILES_PATH\.pyenv\pyenv-win\versions\3.10.0\lib\typing.py)

Then I tried to run the code provided in the documentation.

![image](https://github.com/user-attachments/assets/166bd95b-3656-4c67-954f-9fa99f3a793d)

Which is :

```
import sys
import json
import logging
import ifcclash

settings = ClashSettings()
settings.output = "output.json"
settings.logger = logging.getLogger("Clash")
settings.logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.DEBUG)
settings.logger.addHandler(handler)
ifc_clasher = Clasher(settings)
with open(args.input, "r") as clash_sets_file:
    ifc_clasher.clash_sets = json.loads(clash_sets_file.read())
ifc_clasher.clash()
ifc_clasher.export()
```

And the issue persists.

**Comment by Andrej730** [comment]
> ImportError: cannot import name 'NotRequired' from 'typing' (FILES_PATH.pyenv\pyenv-win\versions\3.10.0\lib\typing.py)

@ThisIsMonta  Can you please try now, after the latest commit? Update is not yet on `pip`, so you'll need to use files from this repository. You'll also need to install `typing-extensions` with `pip install typing-extensions`.

**Comment by Andrej730** [comment]
@ThisIsMonta Hi! Any updates?

**Comment by ThisIsMonta** [comment]
@Andrej730 been busy working on other stuff, i'll check that today and tell you ASAP
