### ISSUE TITLE
IfcMaterialDefinitionRepresentions not being applied - colors aren't used in Blender

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#5687]
I'm trying to understand how to apply style information in my model. Specifically, I'm trying to assign different colors to different parts of the model. I'm using the same IFC coding for all elements of the model, but the color is only applied to the concrete elements.

The beams are green, but the rebar, stirrups, and strands are all grey when they should be different colors.

What am I doing wrong?
[PGSuper1.ifc.txt](https://github.com/user-attachments/files/17621312/PGSuper1.ifc.txt)
![image](https://github.com/user-attachments/assets/a6f3eb7a-e78d-42c1-8fde-ad413ef56db6)

**Comment by theoryshaw** [comment]
I think you have the general idea.  It seems like the style is applied to the material, and the material is applied to the object.  This is how i like doing it.

I did however, run into an error when i tried to apply the style directly to the geometry, which you can also do, but not necessarily recommended.  So i think there's some deeper issue with this particular model.  Defer to others. 


https://github.com/user-attachments/assets/0cdbeb12-3838-4308-aa84-59d2f25c12f4




```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 2316, in _execute
    tool.Geometry.reload_representation(obj)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 1119, in reload_representation
    cls._reload_representation(obj)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 1132, in _reload_representation
    bonsai.core.geometry.switch_representation(
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\geometry.py", line 138, in switch_representation
    geometry.reimport_element_representations(obj, representation, apply_openings=apply_openings)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 749, in reimport_element_representations
    cls.change_object_data(obj, mesh, is_global=False)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 64, in change_object_data
    obj.data = data
    ^^^^^^^^
TypeError: bpy_struct: item.attr = val: Object.data expected a Curve type, not Mesh
```

**Comment by theoryshaw** [comment]
also noticed there's multiple materials with the same name.  You might want to run the following utility to consolidate these....

![image](https://github.com/user-attachments/assets/810dd271-6fdf-46dd-8d1d-4af9e1030e59)

![image](https://github.com/user-attachments/assets/476074e6-d43f-4a9f-b303-1eec700d700b)

**Comment by RickBrice** [comment]
Thanks for the feedback.

I'll be the first to admit that the model is trash - I'm trying to learn how to export models via my prestressed concrete bridge design program, written in C++. There are a lot of duplicate shapes and materials. The rebar in the model are just hard coded shapes for testing.

**Comment by aothms** [comment]
If I use IfcConvert the rebars come in as blue.

`IfcConvert PGSuper1.ifc.txt -yv PGSuper1.ifc.dae` (import .dae file in Blender)

![afbeelding](https://github.com/user-attachments/assets/e9aad1b8-9953-406f-9c53-e20fe73fbc96)

**Comment by RickBrice** [comment]
The light blue bars are very interesting. They are modeled as a unit length bar in the IfcReinforcingBarType and then scaled by its desired length in the IfcCartesianTransformationOperator3D. When imported directly in Bonsai, the bar length is scaled, but for dae, it looks like the bar diameter is scaled.

**Comment by Andrej730** [comment]
Regarding strands, stirrups and rebars - I guess it's Bonsai issue with loading styles for curves... I knew this day will come 😅

> TypeError: bpy_struct: item.attr = val: Object.data expected a Curve type, not Mesh

Seems we have an error switching representation from mesh to curve and vice versa.
