### ISSUE TITLE
Error when exporting COBIe

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5702]
Any idea what's happening here?

```
Starting import process :: 0.00
Loading file :: 0.00
Calculate unit scale :: 0.00
Process context filter :: 0.00
Calculate model offset :: 0.01
Set units :: 0.00
Create project :: 0.05
Process element filter :: 0.03
Create styles :: 0.01
Parsing native elements :: 0.00
Done creating geometry
Create native elements :: 0.00
250 / 2620 (10% created, 100% preprocessed) elements processed in 0.10s ...
Done creating geometry
250 / 2190 (11% created, 31% preprocessed) elements processed in 0.36s ...
500 / 2190 (23% created, 80% preprocessed) elements processed in 0.18s ...
750 / 2190 (34% created, 100% preprocessed) elements processed in 0.12s ...
1000 / 2190 (46% created, 100% preprocessed) elements processed in 0.09s ...
1250 / 2190 (57% created, 100% preprocessed) elements processed in 0.10s ...
1500 / 2190 (68% created, 100% preprocessed) elements processed in 0.08s ...
1750 / 2190 (80% created, 100% preprocessed) elements processed in 0.08s ...
2000 / 2190 (91% created, 100% preprocessed) elements processed in 0.08s ...
2250 / 2190 (103% created, 100% preprocessed) elements processed in 0.09s ...
2500 / 2190 (114% created, 100% preprocessed) elements processed in 0.12s ...
2750 / 2190 (126% created, 100% preprocessed) elements processed in 0.09s ...
3000 / 2190 (137% created, 100% preprocessed) elements processed in 0.10s ...
3250 / 2190 (148% created, 100% preprocessed) elements processed in 0.14s ...
Done creating geometry
0 / 34 elements processed ...
Create elements :: 1.89
Create annotations :: 0.00
Create positioning elements :: 0.00
250 / 275 (91% created, 100% preprocessed) elements processed in 0.20s ...
Done creating geometry
0 / 6 elements processed ...
Create spatial elements :: 0.23
Create structural items :: 0.00
Create element types :: 0.11
Place objects in collections :: 0.30
Setup arrays :: 0.06
Lock objects scales :: 0.03
Add project to scene :: 0.00
Setting default context :: 0.00
Import finished in 3.61 seconds
Traceback (most recent call last):
  File "python3.11\site-packages\bonsai\bim\module\fm\operator.py", line 72, in execute
    parser.parse(ifc_file)
  File "python3.11\site-packages\ifcfm\_init_.py", line 65, in parse
    for element in category_config["get_category_elements"](ifc_file):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11\site-packages\ifcfm\cobie24.py", line 214, in get_attributes
    category = get_category(pset)
               ^^^^^^^^^^^^^^^^^^
  File "python3.11\site-packages\ifcfm\cobie24.py", line 954, in get_category
    references = list(ifcopenshell.util.classification.get_references(element))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11\site-packages\ifcopenshell\util\classification.py", line 31, in get_references
    element_type = ifcopenshell.util.element.get_type(element)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11\site-packages\ifcopenshell\util\element.py", line 524, in get_type
    if is_defined_by := element.IsDefinedBy:  # IFC2X3
                        ^^^^^^^^^^^^^^^^^^^
  File "python3.11\site-packages\ifcopenshell\entity_instance.py", line 238, in…
```

**Comment by Andrej730** [comment]
Fixed in 36bd89b
