### ISSUE TITLE
Bonsai - Feature Request - generate slabs from walls (And to fix coverings for the same feature)

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#5703]
Using these versions:
![image](https://github.com/user-attachments/assets/4e7b2ae6-5dc7-4b25-ab43-5be6aab8dc6c)
![image](https://github.com/user-attachments/assets/1cd9a76a-b2c9-451b-a7c1-1a1e92676907)

At the moment when creating a slab you need to draw the profile of the slab
![image](https://github.com/user-attachments/assets/2aae65b3-441c-49b2-aa25-c84c52b67d9b)

It would be amazing if you could select the walls and have a "generate slab from walls feature"

This kind of function exists with the space tool's "Generate spaces from walls" & "Generate spaces from cursor" (Which is even better)

If that would be possible with the slab tool that would make drawing slabs for complicated floor plans from minutes to 2 clicks.

And to fix the same feature request for horizontal coverings (for floor finishes and ceilings)
Attempting to use the features:
![image](https://github.com/user-attachments/assets/fde54c3b-a5f7-48e0-aa50-70fe73e8d227)

Gives this error:

Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\covering.py", line 124, in _execute
    core.add_instance_ceiling_coverings_from_walls(tool.Root, tool.Spatial, tool.Covering)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\core\covering.py", line 192, in add_instance_ceiling_coverings_from_walls
    spatial.assign_swept_area_outer_curve_from_2d_vertices(obj, vertices=points)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\tool\spatial.py", line 1083, in assign_swept_area_outer_curve_from_2d_vertices
    area = extrusion.SweptArea
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'SweptArea'

Even though it does sometimes create the ceiling:
![image](https://github.com/user-attachments/assets/3312fd48-eaae-493d-8367-5d743c948306)

**Comment by brunoperdigao** [comment]
@Plae-Blue-Dot I implemented your request in this commit: https://github.com/IfcOpenShell/IfcOpenShell/commit/40f1055ac38abe77f948e7e71e46a8982adcf844
Let me know if you find any issues.

About the other issue with the Covering Tool, I wasn't able to reproduce. Could you provide more details?

**Comment by Plae-Blue-Dot** [comment]
Bruno amazing! Thankyou so much, I will try it out when the new build updates

As of this version: 
![image](https://github.com/user-attachments/assets/0de382fc-2822-4713-a5ee-429d7f0b341a)

Using: Blender 4.3.2
on Ubuntu linux

The 'add ceiling from walls' seems to work:
![image](https://github.com/user-attachments/assets/40e2b21c-d21e-465c-a23b-4acbfc52fdba)

But the 'add ceiling from cursor; seems to create an empty ceiling:
![image](https://github.com/user-attachments/assets/a152ead9-ac5d-4758-bcba-7231e0d94b7a)

I have attached an ifc to test out: (just change the .txt to .ifc)


[Ceilings from walls.ifc.txt](https://github.com/user-attachments/files/18215446/Ceilings.from.walls.ifc.txt)

**Comment by theoryshaw** [comment]
Very cool. 

Possible for it to hold up against a 'split'...


https://github.com/user-attachments/assets/b94b505f-9048-4bb9-a6ad-36cc1a75d2a2

**Comment by theoryshaw** [comment]
It appears the 'order' of which walls are joined has an affect

[20241221 - slab from walls - Copy.ifc.txt](https://github.com/user-attachments/files/18219358/20241221.-.slab.from.walls.-.Copy.ifc.txt)

https://github.com/user-attachments/assets/125552f7-fff9-4581-85a5-b727372157f2

**Comment by brunoperdigao** [comment]
@theoryshaw Let me know if those issues were fixed in the latest commits
