### ISSUE TITLE
IFCPROPERTYENUMERATEDVALUE without EnumerationReference breaks Pset editing 

### ISSUE THREAD

**Issue by pistepilvi** [IfcOpenShell/IfcOpenShell#5707]
I would like to edit a file (created by a third party) that contains IFCPROPERTYENUMERATEDVALUE statements like this:
```
#5216=IFCPROPERTYENUMERATEDVALUE('Status',$,(IFCLABEL('EXISTING')),$);
```
So the fourth parameter (EnumerationReference) is not set. However, Ifcopenshell.validate.validate results in just two errors about the OWNERHISTORY statement, with no errors appearing regarding IFCPROPERTYENUMERATEDVALUE. 

In BonsaiBIM's GUI, clicking the edit button for the Pset in Scene/Object Information/Instance results in the following error message:
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blenderbim\bim\module\pset\operator.py", line 103, in execute
    self.load_from_pset_data(pset)
  File "C:\Users\ xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blenderbim\bim\module\pset\operator.py", line 216, in load_from_pset_data
    metadata.set_value(prop.EnumerationReference.EnumerationValues[0].wrappedValue)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'EnumerationValues'
```

I get the same error message when trying to modify this parameter using Python as follows:

`>>> ifcopenshell.api.run("pset.edit_pset", model, pset=psbyid, properties={"Status": enumvalB})`

So update_existing_prop_enum tries to assign a None value to a parameter that does not necessarily exist (even if in the ideal world it should): `prop.EnumerationReference.EnumerationValues = None`

Should this method perhaps just check if this property exists before trying to set it?
I'll be happy to privately share an example file.

**Comment by Andrej730** [comment]
@pistepilvi 
Thanks for the bug report. It seems it also wasn't ready for enumerationvalues to be `None`. Will be fixed in the next commit.

**Comment by pistepilvi** [comment]
I can confirm that from the GUI, there are no more error messages and I can delete the property from the property set, that's great! :)

However, when trying to change the value using Python I run into another issue now:
```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\agr\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\api\__init__.py", line 92, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\agr\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\api\__init__.py", line 252, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\agr\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\api\pset\edit_pset.py", line 166, in edit_pset
    return usecase.execute()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\agr\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\api\pset\edit_pset.py", line 176, in execute
    existing_props = self.update_existing_properties()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\agr\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\api\pset\edit_pset.py", line 225, in update_existing_properties
    prop = self.update_existing_prop_enum(prop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\agr\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\api\pset\edit_pset.py", line 264, in update_existing_prop_enum
    if not value.EnumerationReference.EnumerationValues:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'EnumerationValues'
```

The script that triggered this is as follows:

```
import ifcopenshell
model =  ifcopenshell.open("F:\testfile.ifc")

# get two objects and their IFCPROPERTYENUMERATEDVALUE properties
objA = model.by_guid('2zsBIoTpvBjB5ByrWN5k8v')
propsetA = model.by_id(5234)
enumA = propsetA[4][4]

objB = model.by_guid('2NC90Q3qv5LA3Vzmp5HXm3')
propsetB = model.by_id(645)
enumB = propsetB[4][4]

# assign the property from one object to the other
ifcopenshell.api.run("pset.edit_pset", model, pset=propsetA, properties={"Status": enumB})
```

**Comment by Andrej730** [comment]
Thanks, fixed.
