### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'edges' due to numerical precision issue when loading an IFC file produce with IfcOpenShell 0.8.0

### ISSUE THREAD

**Issue by swiss-knight** [IfcOpenShell/IfcOpenShell#5723]
Hello,

I have this IFC file produced by IfcOpenShell 0.8.0 that I cannot load into Blender 4.2.2 LTS with Bonsai 0.8.0 installed on Ubuntu 22.04.5
```
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition[DesignTransferView]'),'2;1');
FILE_NAME('/dev/null','2024-11-08T15:46:22+01:00',(),(),'IfcOpenShell 0.8.0','IfcOpenShell 0.8.0','Nobody');
FILE_SCHEMA(('IFC4X3_ADD2'));
ENDSEC;
DATA;
#1=IFCCARTESIANPOINTLIST3D(((95.9245096827,80.5057933244,606.5802161905),(95.6946779997,80.7223389999,606.8609259648),(95.4514791341,80.9514791339,607.0864397582),(95.056697085,81.3234397981,607.2816720911),(95.056697085,81.3234397983,607.2816720911),(94.004518332,82.3147946715,607.3710399305)),$);
#2=IFCINDEXEDPOLYCURVE(#1,$,$);
#3=IFCSWEPTDISKSOLID(#2,0.32,$,$,$);
#4=IFCPROJECT('1$sB2lufD5_wFUAvyg6p7r',$,'my_ifc',$,$,$,$,(#12),#7);
#5=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#6=IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
#7=IFCUNITASSIGNMENT((#5,#6));
#8=IFCCARTESIANPOINT((0.,0.,0.));
#9=IFCDIRECTION((0.,0.,1.));
#10=IFCDIRECTION((1.,0.,0.));
#11=IFCAXIS2PLACEMENT3D(#8,#9,#10);
#12=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#11,$);
#13=IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Body','Model',*,*,*,*,#12,$,.MODEL_VIEW.,$);
#14=IFCPIPESEGMENT('1g3QQ9H9TEbeevATUAUPsv',$,$,$,$,#19,#21,$,$);
#15=IFCCARTESIANPOINT((0.,0.,0.));
#16=IFCDIRECTION((0.,0.,1.));
#17=IFCDIRECTION((1.,0.,0.));
#18=IFCAXIS2PLACEMENT3D(#15,#16,#17);
#19=IFCLOCALPLACEMENT($,#18);
#20=IFCSHAPEREPRESENTATION(#13,'Body','AdvancedSweptSolid',(#3));
#21=IFCPRODUCTDEFINITIONSHAPE($,$,(#20));
ENDSEC;
END-ISO-10303-21;
```

The error log shown is as follow:

```
os: Linux
os_version: #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: x86_64
blender_version: 4.2.2 LTS
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
# operator: BIM_OT_save_project
last_error: Traceback (most recent call last):
  File "/home/me/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/project/operator.py", line 751, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "/home/me/Downloads/blender-4.2.2/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/me/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/project/operator.py", line 832, in execute
    ifc_importer.execute()
  File "/home/me/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/import_ifc.py", line 242, in execute
    self.create_native_elements()
  File "/home/me/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/import_ifc.py", line 612, in create_native_elements
    mesh = self.create_native_swept_disk_solid(element, mesh_name, native_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/import_ifc.py", line 1093, in create_native_swept_disk_solid
    e = geometry.edges
        ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'edges'
Location: /home/me/Downloads/blender-4.2.2/4.2/scripts/modules/bpy/ops.py:109


ifc: test.ifc
schema: IFC4X3
preprocessor_version: IfcOpenShell 0.8.0
originating_system: IfcOpenShell 0.8.0
```
But if I round the coordinates one digit less (from 10 to 9 digits precision), it works:
```
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition[DesignTransferView]'),'2;1');
FILE_NAME('/dev/null','2024-11-08T15:53:34+01:00',(),(),'IfcOpenShell 0.8.0','IfcOpenShell 0.8.0','Nobody');
FILE_SCHEMA(('IFC4X3_ADD2'));
ENDSEC;
DATA;
#1=IFCCARTESIANPOINTLIST3D(((95.924509683,80.505793324,606.580216191),(95.694678,80.722339,606.860925965),(95.451479134,80.951479134,607.086439758),(95.056697085,81.323439798,607.281672091),(95.056697085,81.323439798,607.281672091),(94.004518332,82.314794672,607.37103993)),$);
#2=IFCINDEXEDPOLYCURVE(#1,$,$);
#3=IFCSWEPTDISKSOLID(#2,0.32,$,$,$);
#4=IFCPROJECT('17jEFOV699iB4cWgD3MHia',$,'my_ifc',$,$,$,$,(#12),#7);
#5=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#6=IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
#7=IFCUNITASSIGNMENT((#5,#6));
#8=IFCCARTESIANPOINT((0.,0.,0.));
#9=IFCDIRECTION((0.,0.,1.));
#10=IFCDIRECTION((1.,0.,0.));
#11=IFCAXIS2PLACEMENT3D(#8,#9,#10);
#12=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#11,$);
#13=IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Body','Model',*,*,*,*,#12,$,.MODEL_VIEW.,$);
#14=IFCPIPESEGMENT('2Zokn3US19rORlApG0Zj0n',$,$,$,$,#19,#21,$,$);
#15=IFCCARTESIANPOINT((0.,0.,0.));
#16=IFCDIRECTION((0.,0.,1.));
#17=IFCDIRECTION((1.,0.,0.));
#18=IFCAXIS2PLACEMENT3D(#15,#16,#17);
#19=IFCLOCALPLACEMENT($,#18);
#20=IFCSHAPEREPRESENTATION(#13,'Body','AdvancedSweptSolid',(#3));
#21=IFCPRODUCTDEFINITIONSHAPE($,$,(#20));
ENDSEC;
END-ISO-10303-21;
```

![image](https://github.com/user-attachments/assets/5f1d1eac-3b6b-42d1-b62a-ad3103185ea3)

What is the maximum numerical precision allowed by Bonsai and IfcOpenShell?

And can we globally set it in IfcOpenShell to suit specific needs?

Also, the error message displayed in Blender when trying to load the IFC file should maybe say something more accurate about that... because it's a currently bit obscure and unrelated.

PS:

The button "How Can I Fix This?" is not working:

![image](https://github.com/user-attachments/assets/64dbfd8a-ed36-4682-b646-ce3499c20382)

Thanks a lot!

**Comment by Andrej730** [comment]
@swiss-knight Couldn't reproduce this. Please try the latest build from the releases https://github.com/IfcOpenShell/IfcOpenShell/releases

> What is the maximum numerical precision allowed by Bonsai and IfcOpenShell?
> And can we globally set it in IfcOpenShell to suit specific needs?

No idea what's the exact maximum precision for Bonsi - I guess it hits the float precision used by Blender, which is float32.
You can adjust IfcOpenShell precision in `IfcGeometricRepresentationContext`.

**Comment by sboddy** [comment]
Hey @swiss-knight, this is a little prod to see if you tried this with the latest release as requested by Andrej?

In my more recent Bonsai I'm having no problem loading either version of the IFC files, unrounded or rounded, without immediate error. However, nothing useful appears. No swept object resembling your pipe.

Or maybe you have worked around this already, and this issue can be closed?

**Comment by sboddy** [comment]
Closing due to lack of response for more than 2 months. Please reopen if still an issue.

**Comment by sboddy** [comment]
Huh. I must have used the wrong button and accidentally not closed the issue. Oops.
