### ISSUE TITLE
Bonsai unstable build installation issue - os.rename(filepath_local_pkg_temp, filepath_local_pkg) Acess is denied

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5741]
Please watch [this video](https://komododecks.com/recordings/qzLnlY6FBdtib0zNUfTw) to understand what is happening under the unstable installation. 

This used to work in one go before.

This is the log from the session I recorded.

```
DROP URL: https://github.com/IfcOpenShell/IfcOpenShell/releases/download/bonsai-0.8.1-alpha2411122106/bonsai_py311-0.8.1-alpha241112-windows-x64.zip?repository=https://raw.githubusercontent.com/IfcOpenShell/bonsai_unstable_repo/main/index.json&blender_version_min=4.2.0&platforms=windows-x64
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\cli\blender_ext.py", line 5181, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\cli\blender_ext.py", line 5174, in main
    result = args.func(args)
             ^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\cli\blender_ext.py", line 4853, in <lambda>
    func=lambda args: subcmd_client.install_packages(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\cli\blender_ext.py", line 3999, in install_packages
    if not subcmd_client._install_package_from_file_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\cli\blender_ext.py", line 3721, in _install_package_from_file_impl
    os.rename(filepath_local_pkg_temp, filepath_local_pkg)
PermissionError: [WinError 5] Ingen tilgang: 'C:\\Users\\peco01\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\raw_githubusercontent_com\\bonsai@' -> 'C:\\Users\\peco01\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\raw_githubusercontent_com\\bonsai'
Package should have been installed but not found: bonsai
```

**Comment by Andrej730** [comment]
02:20 - [See documentation](https://docs.bonsaibim.org/guides/development/installation.html#unstable-installation). It's not supposed to be installed after first drag'n'drop, it should only setup a repository. Then you can either drag'n'drop it again for installation or find it in "Available" section, not "Installed". If it used to work with just 1 drag'n'drop, it means you already had repository set up.

Couldn't reproduce this myself but I've created a bug report to Blender - https://projects.blender.org/blender/blender/issues/130211. @BIMvoice can you please subscribe to that bug report on Blender website? As I cannot reproduce the issue, they may ask for additional information from someone who can reproduce it.

**Comment by BIMvoice** [comment]
This makes sense now @Andrej730 . Thank you very much for this!

About bug on Blender, I don't have a user yet so I cannot subscribe to that right now.

**Comment by Andrej730** [comment]
> About bug on Blender, I don't have a user yet so I cannot subscribe to that right now.

Sure, it will require blender.org registration.

**Comment by BIMvoice** [comment]
Feel free to let me know if they need something more. You can also share that video with them if it's helpful.

Question about drag and drop: so if you did not install Bonsai yet, will you see 2 Bonsai in the Available tab? 1 coming from blender extensions and one from the unstable build? Or will it be only the unstable one?

**Comment by Andrej730** [comment]
> Question about drag and drop: so if you did not install Bonsai yet, will you see 2 Bonsai in the Available tab? 1 coming from blender extensions and one from the unstable build? Or will it be only the unstable one?

Typically, it's 2 Bonsai. In theory it could be just 1 from unstable repo if blender extensions repo wasn't updated for some reason.

**Comment by BIMvoice** [comment]
I'll check that out and let you know.

**Comment by BIMvoice** [comment]
> > Question about drag and drop: so if you did not install Bonsai yet, will you see 2 Bonsai in the Available tab? 1 coming from blender extensions and one from the unstable build? Or will it be only the unstable one?
> 
> Typically, it's 2 Bonsai. In theory it could be just 1 from unstable repo if blender extensions repo wasn't updated for some reason.

You were right, this is how it shows up after the first drag and drop:

![image](https://github.com/user-attachments/assets/c4c2e9f8-70f3-4bcc-8c8a-23676d25a386)

**Comment by BIMvoice** [comment]
This has also been fixed a long time ago, thank you @Andrej730 !
