### ISSUE TITLE
ifcopenshell.api.georeference.edit_georeferencing.py: crs = file.by_type("IfcProjectedCRS")[0] -> "IndexError: list index out of range" when creating a new IFC file

### ISSUE THREAD

**Issue by swiss-knight** [IfcOpenShell/IfcOpenShell#5745]
Hello,

I'm creating an IFC file from scratch using `ifcopenshell` 0.8.0 in a native Python 3.11 console on Debian 12 (outside Blender).
I wish I could georeference my model.
Based on the current [`api/georeference/edit_georeferencing`](https://docs.ifcopenshell.org/autoapi/ifcopenshell/api/georeference/edit_georeferencing/index.html) official documentation, the following `ifcopenshell 0.8.0` code is throwing an error:
```py
import ifcopenshell
import ifcopenshell.api.georeference
import ifcopenshell.api.project

model = ifcopenshell.api.project.create_file("IFC4X3_ADD2")

ifcopenshell.api.georeference.add_georeferencing(model)
ifcopenshell.api.georeference.edit_georeferencing(model, projected_crs={"Name": "EPSG:2056"})
```
Error:
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/ifcopenshell/api/__init__.py", line 252, in wrapper
    result = usecase(*args, **settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ifcopenshell/api/georeference/edit_georeferencing.py", line 107, in edit_georeferencing
    crs = file.by_type("IfcProjectedCRS")[0]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
Raised by this call in `edit_georeferencing.py`: https://github.com/IfcOpenShell/IfcOpenShell/blob/e74adcbba3ec86a9e831fc5bc83c092560f9253d/src/ifcopenshell-python/ifcopenshell/api/georeference/edit_georeferencing.py#L107

indeed, `model.by_type("IfcProjectedCRS")` returns an empty list `[]` in the current case, i.e. when creating a new IFC file.

Is there anything I can do for the moment to fix this?

Thanks!

**Comment by aothms** [comment]
As you can see in the `add_georeferencing` call, it simply returns when there is no geometric context present in the file.

https://github.com/IfcOpenShell/IfcOpenShell/blob/243e974866c3cbb9e1ddc2de6af8323eaea702a8/src/ifcopenshell-python/ifcopenshell/api/georeference/add_georeferencing.py#L73-L74

Contributions welcome to make this a bit more smooth. Like `warnings.warn(...)`, add something to the docs, etc. :)

With a little bit more complete file the API calls will probably work as expected:

https://github.com/IfcOpenShell/IfcOpenShell/blob/243e974866c3cbb9e1ddc2de6af8323eaea702a8/src/ifcopenshell-python/docs/ifcopenshell-python/geometry_creation.rst?plain=1#L301-L310
