### ISSUE TITLE
Extending or regenerating wall - RuntimeError: Instance # 707 not found

### ISSUE THREAD

**Issue by marwiss** [IfcOpenShell/IfcOpenShell#5758]
I created a wall. I rotated the wall a few times and now I want to extend it.

When I press extend - shift E - I get "RuntimeError: Instance # 707 not found".

The data-block of the wall has ID 15/707.001.

<img width="1339" alt="wall" src="https://github.com/user-attachments/assets/2b19450b-905b-453c-8040-b132c5fd3a88">

Error message:

```
os: Windows
python_version: 3.11.7
blender_version: 4.2.3 LTS
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
# operator: BIM_OT_hotkey
# operator: BIM_OT_recalculate_wall
# operator: BIM_OT_hotkey
# operator: BIM_OT_recalculate_wall
# operator: BIM_OT_hotkey
# operator: BIM_OT_recalculate_wall
# operator: BIM_OT_hotkey
# ifcopenshell.api: geometry.disconnect_path
>>> {"element": {"cast_type": "entity_instance", "value": 307, "Name": "Wall"}, "connection_type": "ATSTART"}
# operator: BIM_OT_hotkey
# ifcopenshell.api: geometry.disconnect_path
>>> {"element": {"cast_type": "entity_instance", "value": 307, "Name": "Wall"}, "connection_type": "ATSTART"}
last_error: Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\workspace.py", line 889, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\workspace.py", line 981, in hotkey_S_E
    core.extend_walls(
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\model.py", line 38, in extend_walls
    joiner.join_E(obj, target)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\wall.py", line 1312, in join_E
    self.recreate_wall(element1, wall1, axis, body)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\wall.py", line 1384, in recreate_wall
    extrusion_data = self.get_extrusion_data(tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\file.py", line 463, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\file.py", line 448, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 8269, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #707 not found

schema: IFC4
preprocessor_version: IfcOpenShell 0.8.0
originating_system: Bonsai 0.8.0
```

**Comment by marwiss** [comment]
I created a new wall ... and soon I get the same error message again with the new wall, when I try to extend it.

```
os: Windows
blender_version: 4.2.3 LTS
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
# ifcopenshell.api: owner.create_owner_history
>>> {}
# operator: BIM_OT_hotkey
# ifcopenshell.api: geometry.connect_path
>>> {"related_element": {"cast_type": "entity_instance", "value": 994, "Name": "Wall"}, "relating_element": {"cast_type": "entity_instance", "value": 1106, "Name": "Wall"}, "relating_connection": "ATPATH", "related_connection": "ATEND", "description": "BUTT"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# operator: BIM_OT_hotkey
# ifcopenshell.api: geometry.disconnect_path
>>> {"element": {"cast_type": "entity_instance", "value": 1106, "Name": "Wall"}, "connection_type": "ATSTART"}
# operator: BIM_OT_hotkey
# operator: BIM_OT_recalculate_wall
# operator: BIM_OT_hotkey
# operator: BIM_OT_recalculate_wall
last_error: Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\workspace.py", line 889, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\workspace.py", line 1044, in hotkey_S_G
    bpy.ops.bim.recalculate_wall()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\wall.py", line 153, in _execute
    DumbWallRecalculator().recalculate(context.selected_objects)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\wall.py", line 666, in recalculate
    joiner.recreate_wall(element, wall)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\wall.py", line 1384, in recreate_wall
    extrusion_data = self.get_extrusion_data(tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\file.py", line 463, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\file.py", line 448, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 8269, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #1,247 not found
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


schema: IFC4
preprocessor_version: IfcOpenShell 0.8.0
originating_system: Bonsai 0.8.0
```

**Comment by theoryshaw** [comment]
Did you use 'undo' at any step along the way. 
Undo is temperamental, at times. :)

**Comment by marwiss** [comment]
Could be the reason. I was redoing the walls without pressing undo and I got no errors.

**Comment by theoryshaw** [comment]
If you can, try and list out the exact steps, so we can replicate the scenario.

**Comment by BIMvoice** [comment]
This reproduces as fixed on current v0.8.0. I recreated the reported sequence headlessly (create a wall, rotate it several times while each rotation goes through the same recreate_wall path as BIM_OT_recalculate_wall, then extend the wall repeatedly like Shift+E), and every representation lookup and extend call succeeded with no RuntimeError. The crash came from the old `DumbWallRecalculator.recreate_wall` in `wall.py`, which called `get_extrusion_data(tool.Ifc.get().by_id(obj.data.BIMMeshProperties.ifc_definition_id))`, a second by_id lookup of the mesh's cached representation id that could go stale after repeated regenerations, raising "Instance #N not found." That path no longer exists. `tool.Model.recreate_wall` in `bonsai/tool/model.py` now rebuilds the wall directly from the IFC element via `ifcopenshell.api.geometry.regenerate_wall_representation`, then switches the object's representation, so there is no stale id re-lookup left to fail. Verified against a current Bonsai build (0.8.6a260706) whose recreate_wall and extend functions are byte identical to the worktree v0.8.0 source. Safe to close. This was verified with the assistance of an AI tool.

**Comment by BIMvoice** [comment]
Closing, already confirmed fixed on current v0.8.0 above (the old stale-representation-id lookup path this crashed in no longer exists).

Generated with the assistance of an AI coding tool.
