### ISSUE TITLE
Error removing drawing that has no drawing group

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#5761]
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.2.3 LTS
bonsai_version: 0.8.1-alpha241114
bonsai_commit_hash: 229e2da
last_actions: 
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_drawings
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 15, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/FOUNDATION PLAN\") at 0x000001FE84778808>", "geometry": "<bpy_struct, Camera(\"15/55163\") at 0x000001FE84689008>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 55172, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 55038, "Name": "FOUNDATION PLAN"}, "representation": {"cast_type": "entity_instance", "value": 55163, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 55163, "Name": null}}
# operator: BIM_OT_remove_drawing
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 2147, in _execute
    core.remove_drawing(tool.Ifc, tool.Drawing, drawing=drawing)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\drawing.py", line 350, in remove_drawing
    information = drawing_tool.get_reference_document(drawing_tool.get_drawing_document(drawing))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 1755, in get_reference_document
    return reference.ReferencedDocument
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ReferencedDocument'

ifc: Simple 1 bed 241116rev1.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha240912
originating_system: Bonsai 0.8.1-alpha240912-21cfd03
```
Attached is the IFC model, 
Please advise where I am making an error.
Thanks for your support and efforts
[Simple 1 bed 241115.txt](https://github.com/user-attachments/files/17796784/Simple.1.bed.241115.txt)
![blender_jHc3UHdDH5](https://github.com/user-attachments/assets/e742272a-2b06-4411-bb68-26300dda48a3)

**Comment by Andrej730** [comment]
@Ave-5D 

It's hard to tell what happened but this drawing is corrupted. Usually drawings have a drawing group that contains all the annotations including the drawing annotation, this file is missing drawing group for `PLAN_VIEW` drawing. Haven't deleted drawing group manually?

![image](https://github.com/user-attachments/assets/a9c7a849-a25b-4f9a-99c2-cc881ab52e99)

You can try to create a new DRAWING group, assign 'IfcAnnotation/PLAN_VIEW' drawing annotation to it and reload ifc file but no idea what else may have been corrupted.
![image](https://github.com/user-attachments/assets/5476221c-1211-4b29-abf1-62ec537fa386)

**Comment by Ave-5D** [comment]
Hi Andre
Thanks for the feedback. No, I did not manually delete a group, never knew that a drawing is a Group 😊.
Now, I tried to assign to a new Group, but it is above my grade level don't know if this is the right place to create a group. As per the attached screen shot only Pset I can add is Custom Pset. (after creating some groups and subgroups, I tried to create a new group and the Pset option disappeared)

![blender_pIuPfbWWt5](https://github.com/user-attachments/assets/3f5de4a3-5ad5-4904-94c4-1147cb72ca2c)

Attached is a second error message I received with the same file when I created a section drawing and wanted to edit the dimension annotation. (Don't know how complex or if I don't know the function yet, it would be good to see to which assigned element the dimension is linked, IfcSlab/IfcCover/IfcWall....)

 ```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.2.3 LTS
bonsai_version: 0.8.1-alpha241119
bonsai_commit_hash: 213b6ed
last_actions: 
# operator: BIM_OT_add_annotation
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcAnnotation", "predefined_type": "DIMENSION", "name": "DIMENSION"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 55743, "Name": "DIMENSION"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.3956880569458008], [0.0, 3.422854177870249e-08, -0.9999999403953552, 2.999999761581421], [0.0, 0.9999999403953552, 3.422854177870249e-08, -0.8799996972084045], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 55743, "Name": "DIMENSION"}}
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 18, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/DIMENSION.003\") at 0x000001CE9C880808>", "geometry": "<bpy_struct, Curve(\"DIMENSION.006\") at 0x000001CEA74EF408>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "", "profile_set_usage": "None"}
# ifcopenshell.api: geometry.assign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 55743, "Name": "DIMENSION"}, "representation": {"cast_type": "entity_instance", "value": 55752, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 55743, "Name": "DIMENSION"}}
# ifcopenshell.api: group.assign_group
>>> {"group": {"cast_type": "entity_instance", "value": 55536, "Name": "NORTH SECTION"}, "products": [{"cast_type": "entity_instance", "value": 55743, "Name": "DIMENSION"}]}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 55538, "Name": null}}
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 18, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/DIMENSION.003\") at 0x000001CE9C880808>", "geometry": "<bpy_struct, Curve(\"18/55752\") at 0x000001CEA7A07408>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 55757, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 55743, "Name": "DIMENSION"}, "representation": {"cast_type": "entity_instance", "value": 55752, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 55752, "Name": null}}
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_import_representation_items
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 441, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1802, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\ifc.py", line 291, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1808, in _execute
    self.handle_single_object(context, context.active_object)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1845, in handle_single_object
    bpy.ops.bim.import_representation_items()
  File "D:\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 2564, in _execute
    item_ids = data["ios_item_ids"] if "ios_item_ids" in data else data["ios_edges_item_ids"]
                                                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'bpy_struct[key]: key "ios_edges_item_ids" not found'
Location: D:\4.2\scripts\modules\bpy\ops.py:109


ifc: Simple 1 bed 241118.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha241119
originating_system: Bonsai 0.8.1-alpha241119-213b6ed
```
Hope this helps

**Comment by theoryshaw** [comment]
this last error is probably related to: https://github.com/IfcOpenShell/IfcOpenShell/issues/5488

**Comment by Andrej730** [comment]
> Now, I tried to assign to a new Group, but it is above my grade level don't know if this is the right place to create a group. As per the attached screen shot only Pset I can add is Custom Pset. (after creating some groups and subgroups, I tried to create a new group and the Pset option disappeared)

Group assignment is available in Object Information.

![image](https://github.com/user-attachments/assets/1356fbcd-3fcb-410f-8437-7be97c01b2c0)

> Attached is a second error message I received with the same file when I created a section drawing and wanted to edit the dimension annotation

It's indeed a different error that Ryan mentioned above.

> Don't know how complex or if I don't know the function yet, it would be good to see to which assigned element the dimension is linked, IfcSlab/IfcCover/IfcWall...

You can assign product to an annotation, select annotation and see "Product Assignment" section.

**Comment by Ave-5D** [comment]
Could not get the Group thing working.
Removed the drawing by getting the ID and deleting it in the text file. (The power of IFC) 
Thanks for your efforts

**Comment by Andrej730** [comment]
Okay, closing this for now. Please report if you find any more details about this issue.

**Comment by Ave-5D** [comment]
Thanks will do
