### ISSUE TITLE
Error at running geom.app

### ISSUE THREAD

**Issue by Noranius** [IfcOpenShell/IfcOpenShell#577]
I tried to run geom.app from ifcOpenShell 0.5 binary from the website with the following short python script
`import ifcopenshell.geom.app
ifcopenshell.geom.app.application().start()`

This results in the following error

> Traceback (most recent call last):
  File "C:\ifcOpenShell\ifcOpenShell_0.5\ifcopenshell\__init__.py", line 45, in <module>
    from . import ifcopenshell_wrapper
  File "C:\ifcOpenShell\ifcOpenShell_0.5\ifcopenshell\ifcopenshell_wrapper.py", line 28, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
  File "C:\ifcOpenShell\ifcOpenShell_0.5\ifcopenshell\ifcopenshell_wrapper.py", line 24, in swig_import_helper
    _mod = imp.load_module('_ifcopenshell_wrapper', fp, pathname, description)
  File "C:\Python\Python-3.7.3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python\Python-3.7.3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: %1 ist keine zulässige Win32-Anwendung.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Q:/B-ITD-Research/Doktoranden/Intern/Artus/Softwaretests/ifcOpenShell/source/ifcViewer.py", line 1, in <module>
    import ifcopenshell.geom.app
  File "C:\ifcOpenShell\ifcOpenShell_0.5\ifcopenshell\__init__.py", line 52, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.7'

**Comment by aothms** [comment]
~~~
ImportError: DLL load failed: %1 ist keine zulässige Win32-Anwendung. (is no valid win32 application)
~~~

Seems to suggest that you're mixing 32/64 bit applications. Is that a possibility?

**Comment by Noranius** [comment]
I just write the example code to run the app within python (see starting post). Python is 64 bit. I should my try 32 bit.

**Comment by aothms** [comment]
> I just write the example code to run the app within python (see starting post). Python is 64 bit. I should my try 32 bit.

Don't entirely understand. You can always try a more recent build whether that helps https://github.com/IfcOpenBot/IfcOpenShell/commit/bf1623975c6451baf3e2a1af9f32e9306d235b3f#commitcomment-32346507

**Comment by Noranius** [comment]
I used the example code from the top to run the app. However, I used the 64 bit distribution of Python. I'll try the 32 bit distibution for the test.

**Comment by Noranius** [comment]
OK. I tried the code from my first post with Python 32 bit but got the same exception.

**Comment by aothms** [comment]
* Ok, can you then exactly describe which modules you installed and how. 

* Did you try with https://github.com/IfcOpenBot/IfcOpenShell/commit/bf1623975c6451baf3e2a1af9f32e9306d235b3f#commitcomment-32346507

* What is this `ifcopenshell_init.py` file mentioned in the tracebacks?

**Comment by Noranius** [comment]
> But what is the exact contents then of that directory?

See first picture

> But that's not __init__.py not ifcopenshell_init.py. How did that file get renamed, am I missing something?

I heaven't changed the name or content of it. It's just the file which i got from the website (http://www.ifcopenshell.org/python.html)

![DirectoryContent](https://user-images.githubusercontent.com/29037766/57686818-9155a280-763a-11e9-9e03-daa21fd8f2be.JPG)

**Comment by aothms** [comment]
> But that's not __init__.py not ifcopenshell_init.py. How did that file get renamed, am I missing something?

Thanks for the screenshot. Ok, perhaps that is then a github formatting issue.

Just to let you know, the recent builds do include a Python 3.7 version now: https://github.com/IfcOpenBot/IfcOpenShell/commit/c61bc29f0646430c207050ed5b62a6a216628159

Are you just using the Python versions downloaded from the website? Is there anything particular about your setup? Are you sure the 32/64bit matches your ifcopenshell download and Python interpreter?

**Comment by Noranius** [comment]
> Are you just using the Python versions downloaded from the website?

Yes

> Is there anything particular about your setup?

I changed nothing in python or IfcOpenShell. I only use pyCharm as IDE (64 bit).

>  Are you sure the 32/64bit matches your ifcopenshell download and Python interpreter?

Yes, I tried the same code with 32 and 64 bit. Last thing could be a problem related to the IDE.

**Comment by aothms** [comment]
> Last thing could be a problem related to the IDE.

So just to be sure, is the IDE actually using the interpreter you expect? What's the output of the script below, and does that match your expectations?

~~~
import os
import sys
if hasattr(os, 'uname'):
    platform_system = os.uname()[0].lower()
else:
    platform_system = 'windows'

if sys.maxsize == (1 << 31) - 1:
    platform_architecture = '32bit'
else:
    platform_architecture = '64bit'

python_version_tuple = tuple(sys.version.split(' ')[0].split('.'))
print(os.path.join(platform_system, platform_architecture, 'python%s.%s' % python_version_tuple[:2]))
~~~

Is the ifcopenshell module perhaps imported from another location then we expect? What's the output of the script below, and does that match your expectations?

~~~
import imp
imp.find_module("ifcopenshell")
~~~

**Comment by Noranius** [comment]
using python 3.7:
```
C:\Python\Python-3.7.3\python.exe C:/Users/[username]/Documents/Softwaretests/ifcOpenShell/source/ifcViewer.py
windows\64bit\python3.7

Process finished with exit code 0
```

using python from IFCOpenShell
```
Q:\B-ITD-Research\Softwaretests\ifcOpenShell\venv\Scripts\python.exe C:/Users/[username]/Documents/Softwaretests/ifcOpenShell/source/ifcViewer.py
windows\64bit\python3.5

Process finished with exit code 0
```

using python 3.7 32bit
```
"C:\Program Files (x86)\Python37-32\python.exe" C:/Users/[username]/Documents/Softwaretests/ifcOpenShell/source/ifcViewer.py
windows\32bit\python3.7

Process finished with exit code 0

```

Last idea was to use python 3.5 32 bit. However i got another error:
```
Traceback (most recent call last):
  File "C:/Users/ripo9018/Documents/Softwaretests/ifcOpenShell/source/ifcViewer.py", line 1, in <module>
    import ifcopenshell.geom.app
  File "C:\ifcOpenShell\ifcOpenShell_0.5\ifcopenshell\geom\app.py", line 9, in <module>
    import OCC.AIS
ImportError: No module named 'OCC'
```

Istalling OCC leads to several necessary packages. Shouldn't the viewer run out of the box with python 3.5?

**Comment by aothms** [comment]
> Istalling OCC leads to several necessary packages. Shouldn't the viewer run out of the box with python 3.5?

No it depends on PythonOCC and PyQt for the UI and 3D visulization.

**Comment by BIMvoice** [comment]
The question was answered in-thread in 2019 and the answer still holds on `v0.8.0`: the viewer (`ifcopenshell/geom/app.py`) still exists and still requires PythonOCC and PyQt as optional dependencies — it does not run out of the box by design. Safe to close as answered.

**Comment by BIMvoice** [comment]
Closing per the note above: this was a setup/dependency question, answered in-thread back in 2019 (the geom.app viewer requires PythonOCC and PyQt as optional dependencies, it isn't meant to run out of the box) and confirmed still accurate on current code. It's been two weeks since that note with no objection. Reopen if you're still hitting this on a current build.

This comment was written with AI assistance.
