### ISSUE TITLE
BIMGeometryProperties mode enum error when attempting to enter Edit mode via Tab key

### ISSUE THREAD

**Issue by RichardWhitfield** [IfcOpenShell/IfcOpenShell#5771]
## Issue Description
When attempting to enter Edit mode through the Bonsai interface, the following error occurs:
```python
TypeError: bpy_struct: item.attr = val: enum "EDIT" not found in ('OBJECT')
Error: Python: Traceback (most recent call last):
  File "C:\Users\richard\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 406, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\richard\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1694, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\richard\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1578, in execute
    return IfcStore.execute_ifc_operator(self, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\richard\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\richard\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 1678, in _execute
    context.scene.BIMGeometryProperties.mode = "EDIT"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "EDIT" not found in ('OBJECT')
```

## Environment
* Bonsai Version: 0.8.0
* Blender Version: 4.2.1
* Operating System: Windows 11 Version 23H2 (OS Build 22635.4510)

## Steps to reproduce
1. Open Blender with Bonsai
2. Select the object
3. Press Tab

## Expected Behaviour
The object should enter Edit mode, allowing for geometry modifications

## Actual Behaviour
An error is thrown indicating that 'EDIT' is not a valid enum value, despite debug output showing that:
* The object is correctly identified as editable
* The object type (MESH) is in the supported types
* The mode list should include both 'OBJECT' and 'EDIT' modes

Debug output:
```
Checking editability for object: IfcBuildingElementProxy/None
Object type: MESH
Supported types: ('MESH', 'CURVE', 'SURFACE', 'META', 'FONT', 'LATTICE', 'ARMATURE')
IFC element: #3114=IfcBuildingElementProxy('26jV3kz7wW_W00000000dU',#11,$,$,$,#16,#3115,$,$)
Usage type: None
Object is editable
```

## Additional Notes
* The `ViewportData.mode()` method correctly includes both 'OBJECT' and 'EDIT' modes in its return value
* The error appears to be a synchronisation issue between Blender's mode state and Bonsai's property system
* The object is correctly identified as editable through all validation checks

## Related Code
The error originates in the geometry operator's execute method:
``` Python
if context.active_object:
    if tool.Blender.toggle_edit_mode(context) == {"CANCELLED"}:
        return {"CANCELLED"}
    context.scene.BIMGeometryProperties.is_changing_mode = True
    if context.scene.BIMGeometryProperties.mode != "EDIT":
        context.scene.BIMGeometryProperties.mode = "EDIT"  # Error occurs here
    context.scene.BIMGeometryProperties.is_changing_mode = False
    return {"FINISHED"}
```
This operation is being managed by the IFC transaction system:
``` Python
@staticmethod
def execute_ifc_operator(operator: bpy.types.Operator, context: bpy.types.Context, is_invoke=False):
    # Transaction management code
    try:
        if is_invoke:
            result = getattr(operator, "_invoke")(context, None)
        else:
            result = getattr(operator, "_execute")(context)
    except:
        bonsai.last_error = traceback.format_exc()
        raise
    # Transaction completion code
```
The error occurs within a transaction, suggesting that the mode property's enum values might not be properly synchronised during the transaction lifecycle.

**Comment by Andrej730** [comment]
@RichardWhitfield
1) Try the latest build from the releases https://github.com/IfcOpenShell/IfcOpenShell/releases/
2) If the issue persist please share a specific .ifc file to reproduce the issue.

**Comment by Moult** [comment]
A lot of this stuff has been fixed since. Closing unless a file is provided to replicate.
