### ISSUE TITLE
2D representation of custom door type

### ISSUE THREAD

**Issue by fjieikkdddsll** [IfcOpenShell/IfcOpenShell#5793]
When working with a door type, I can create the plan view by adding Plan/Body/Plan_View and selecting "trace outline". After it is created if I switch to the tesselation view and then back to the plan view, the plan view disappears.
I also have the issue that ctrl+J shortcut doesn't work for plan view objects. It works fine on the model view though. Selecting join or ifc join from the menus works for plan view objects.
(I am using Bonsai v 0.8.0)

**Comment by theoryshaw** [comment]
Yes, this seems like an error. I can replicate.

**Comment by Andrej730** [comment]
@fjieikkdddsll can you please share an example? Can you please try using the latest build from releases? https://github.com/IfcOpenShell/IfcOpenShell/releases

Can't reproduce it:
https://github.com/user-attachments/assets/96b57942-dff4-4268-890a-92b66f5c4a52

**Comment by theoryshaw** [comment]
For me, the error is in using 'join'.

**Comment by Andrej730** [comment]
> For me, the error is in using 'join'.

"join is not supported" or some other error?

**Comment by theoryshaw** [comment]
Join used to work at one point. https://community.osarch.org/discussion/comment/19502/#Comment_19502

**Comment by fjieikkdddsll** [comment]
I updated to version 0.8.1 - alpha241125 and switching between the plan view and model tesselation view works as expected. 

Ctrl+J doesn't work as expected on plan view objects. IFC Join from the F3 menu also doesn't work - there is no error - the objects simply remain separate. However, this may not matter as the plan view object seems to be a different type of obejct - ifcindexedpolycurve? - which I will have to figure out how to use to create the plan view I want.

A couple of strange things:

sometimes changing the view on one object affects the view of other objects.

I joined a plane to the plan view, clicked "manually save representation" and then made a copy using shift+d. Now I get different behavior on the original and the copy when tabbing into the plan view objects.

I also get an error if I delete the plan view from the object. And if I add the plan view back (after the error) I get unexpected results (a partial view of the object).

[custom ifc door test.zip](https://github.com/user-attachments/files/17908211/custom.ifc.door.test.zip)


```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD
blender_version: 4.2.3 LTS
bonsai_version: 0.8.1-alpha241125
bonsai_commit_hash: e6f8ef9

last_actions: 
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_switch_representation
# operator: BIM_OT_remove_representation
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 75, "Name": "Cube"}, "representation": {"cast_type": "entity_instance", "value": 193, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 193, "Name": null}}
last_error: Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 366, in _execute
    core.remove_representation(
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\core\geometry.py", line 180, in remove_representation
    geometry.delete_data(data)
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 109, in delete_data
    bpy.data.meshes.remove(data)
ReferenceError: StructRNA of type Mesh has been removed

ifc: custom ifc door test.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha241125
originating_system: Bonsai 0.8.1-alpha241125-e6f8ef9
```

**Comment by fjieikkdddsll** [comment]
I also meant to say that when I joined the mesh plane to the plan view I used the standard blender "Join" from the right click menu.

**Comment by Andrej730** [comment]
> IFC Join from the F3 menu also doesn't work - there is no error - the objects simply remain separate.

> I joined a plane to the plan view, clicked "manually save representation" and then made a copy using shift+d. Now I get different behavior on the original and the copy when tabbing into the plan view objects.

Need an .ifc example.

> sometimes changing the view on one object affects the view of other objects.

That's intended - objects of the same type all suppose to share the same active context.

> I also get an error if I delete the plan view from the object. And if I add the plan view back (after the error) I get unexpected results (a partial view of the object).

Same as #5776

**Comment by Andrej730** [comment]
I've added support for joining IfcGeometricCurveSet that use polycurves, perhaps this should help.

**Comment by fjieikkdddsll** [comment]
I attached an ifc file to my last post. Did it not work? It won't let me attach an ifc file so I had to zip it.

I can try to attach again here.  
[custom.ifc.door.test.zip](https://github.com/user-attachments/files/17940862/custom.ifc.door.test.zip)

The file contains 3 door types - they are all on top of each other at the origin. 

One called "cube" which I deleted the plan view and then re-added it and it now displays incorrectly.

The other 2 have plan views that have been joined as mentioned in my previous post. The were responding differently when attempting to edit the plan views, but in the latest bonsai release (today 241127) they act as expected.

The other odd behavior was if they are all set to show the plan view, then I change IfcDoorType/Cube to tesselation view, the IfcDoorType/Door changes at the same time - even though it is a separate door type.

**Comment by theoryshaw** [comment]
@fjieikkdddsll is this still an issue for you?
