### ISSUE TITLE
Activate Bonsai - ImportError: IfcOpenShell not built for 'windows\64bit\python3.11'

### ISSUE THREAD

**Issue by RevitHusa** [IfcOpenShell/IfcOpenShell#5801]
```python
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
blender_version: 4.2.3 LTS
bonsai_version: 0.8.1-alpha241118
bonsai_commit_hash: 362c5a1
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\husam\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ifcopenshell._ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\husam\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\__init__.py", line 84, in <module>
    from . import ifcopenshell_wrapper
  File "C:\Users\husam\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 17, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\husam\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_ifcopenshell_wrapper')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\husam\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\bonsai\__init__.py", line 225, in <module>
    import ifcopenshell.api
  File "C:\Users\husam\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\__init__.py", line 86, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.11'

binary_file_name: _ifcopenshell_wrapper.cp312-win_amd64.pyd
binary_python_version: 3.12
```

**Comment by Andrej730** [comment]
@RevitHusa Hi! You've downloaded a wrong archive and installed Bonsai for Python 3.12 instead of Python 3.11. Uninstall Bonsai and try to install version for Python 3.11.
