### ISSUE TITLE
Newline code throws an exception generating drawing if newline_at is None

### ISSUE THREAD

**Issue by sboddy** [IfcOpenShell/IfcOpenShell#5802]
@theoryshaw 

As per title: https://github.com/IfcOpenShell/IfcOpenShell/blame/e6f8ef992e56e746a1916fa33186cbcededd561c/src/bonsai/bonsai/bim/module/drawing/svgwriter.py#L1409-L1409C7
 This line is too permissive. It lets the following line call the function with newline_at set to None. Causes an exception and prevents drawings working.

Better:
`if isinstance(newline_at, int) and newline_at > 0:`

Exception:
```
Traceback (most recent call last):
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 244, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 307, in execute
    annotation_svg = self.generate_annotation(context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 1380, in generate_annotation
    self.svg_writer.create_blank_svg(svg_path).draw_annotations(annotations, precision, decimal_places).save()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/svgwriter.py", line 210, in draw_annotations
    self.draw_text_annotation(obj, obj.location)
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/svgwriter.py", line 848, in draw_text_annotation
    text_tags = self.create_text_tag(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/svgwriter.py", line 1410, in create_text_tag
    text = helper.add_newline_between_words(text, newline_at)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/helper.py", line 433, in add_newline_between_words
    end = start + newline_at
          ~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by theoryshaw** [comment]
Thank you kindly!
