### ISSUE TITLE
Drawing with underlay gives cache path error if the project is in a network folder

### ISSUE THREAD

**Issue by FabioPiccinini** [IfcOpenShell/IfcOpenShell#5803]
If the project is in a network folder, at some point during the drawing creation the cache file "drawingname-underlay.png" is saved in the wrong folder:

"\\path\to\the\project\path\to\the\project\drawings\cache\drawingname-underlay.png"

Due to the path length this could also lead to the impossibility to save the cache file.

I don't remember if even when the cache file is saved it still can't be found later because of the wrong path.

**Comment by Andrej730** [comment]
@FabioPiccinini can you please share the error traceback?

**Comment by FabioPiccinini** [comment]
Sure.


```
New cache was created.
Initialize drawing generation process 0.07040750002488494
\\ServerGeoFly\ServerGT\GeoTeam\01_CLIENTI\__TERREMOTO 2016\CURIA\23_002_T  santa maddalena paterno\03_Rilievi\07_Blender\ServerGeoFly\ServerGT\GeoTeam\01_CLIENTI\__TERREMOTO 2016\CURIA\23_002_T  santa maddalena paterno\03_Rilievi\07_Blender\drawings\cache\Sezione A-underlay.png: No such file or directory
Error: Render error (No such file or directory) cannot save: '\\ServerGeoFly\ServerGT\GeoTeam\01_CLIENTI\__TERREMOTO 2016\CURIA\23_002_T  santa maddalena paterno\03_Rilievi\07_Blender\ServerGeoFly\ServerGT\GeoTeam\01_CLIENTI\__TERREMOTO 2016\CURIA\23_002_T  santa maddalena paterno\03_Rilievi\07_Blender\drawings\cache\Sezione A-underlay.png'
OpenGL Render failed to write '\\ServerGeoFly\ServerGT\GeoTeam\01_CLIENTI\__TERREMOTO 2016\CURIA\23_002_T  santa maddalena paterno\03_Rilievi\07_Blender\ServerGeoFly\ServerGT\GeoTeam\01_CLIENTI\__TERREMOTO 2016\CURIA\23_002_T  santa maddalena paterno\03_Rilievi\07_Blender\drawings\cache\Sezione A-underlay.png'
Generate underlay 2.4244278001133353
sync 0.0013449001125991344
Processing body context 2.09989957511425e-06
Processing body context 0.019858399871736765
Processing annotation context 0.015495700063183904
Processing annotation context 0.0002267998643219471
Finalizing 0.00020590005442500114
Generate linework 0.07577739981934428
Generate annotation 0.02591800014488399
Combine SVG layers 0.08370550000108778
Drawing generation process 2.68100620014593
Traceback (most recent call last):
  File "C:\Users\Fly01\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 244, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fly01\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 310, in execute
    svg_path = self.combine_svgs(context, underlay_svg, linework_svg, annotation_svg)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fly01\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 348, in combine_svgs
    shutil.copyfile(os.path.splitext(underlay)[0] + ".png", os.path.splitext(svg_path)[0] + "-underlay.png")
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\python\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '\\\\ServerGeoFly\\ServerGT\\GeoTeam\\01_CLIENTI\\__TERREMOTO 2016\\CURIA\\23_002_T  santa maddalena paterno\\03_Rilievi\\07_Blender\\drawings\\cache\\Sezione A-underlay.png'
Error: Python: Traceback (most recent call last):
  File "C:\Users\Fly01\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 310, in execute
    svg_path = self.combine_svgs(context, underlay_svg, linework_svg, annotation_svg)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fly01\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 348, in combine_svgs
    shutil.copyfile(os.path.splitext(underlay)[0] + ".png", os.path.splitext(svg_path)[0] + "-underlay.png")
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\python\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '\\\\ServerGeoFly\\ServerGT\\GeoTeam\\01_CLIENTI\\__TERREMOTO 2016\\CURIA\\23_002_T  santa maddalena paterno\\03_Rilievi\\07_Blender\\drawings\\cache\\Sezione A-underlay.png'
```

**Comment by Andrej730** [comment]
Thank you, fixed.

**Comment by FabioPiccinini** [comment]
Thank you so much for fixing it so quickly!
