### ISSUE TITLE
Error loading project in Bonsai - TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5807]
Will send file privately via google docs form

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.0.0
bonsai_commit_hash: 4f6e258
last_actions: 
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1232, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 2804, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 2804, "Name": null}}
# ifcopenshell.api: geometry.add_wall_representation
>>> {"context": {"cast_type": "entity_instance", "value": 24, "Name": null}, "length": "8.985800668135308", "height": "3.5056709940248485", "x_angle": "0", "offset": "0.0", "thickness": "0.33654998221099364", "clippings": "[{'type': 'IfcBooleanClippingResult', 'operand_type': 'IfcHalfSpaceSolid', 'matrix': Matrix(((1.0, 0.0, 0.0, 0.0),\n        (0.0, 0.9999604225158691, 0.008901065215468407, 0.0),\n        (0.0, -0.008901065215468407, 0.9999604225158691, 3.5056710243225098),\n        (0.0, 0.0, 0.0, 1.0)))}]", "booleans": "[]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1232, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 2821, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 2821, "Name": null}}
# ifcopenshell.api: geometry.add_axis_representation
>>> {"context": {"cast_type": "entity_instance", "value": 36, "Name": null}, "axis": "[Vector((0.0, 0.0)), Vector((4.876800060272217, 0.0))]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 2161, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 2824, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 2824, "Name": null}}
# ifcopenshell.api: geometry.add_wall_representation
>>> {"context": {"cast_type": "entity_instance", "value": 24, "Name": null}, "length": "4.876800009172795", "height": "3.0000000000000004", "x_angle": "0", "offset": "0.0", "thickness": "0.33654998221099364", "clippings": "[]", "booleans": "[]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 2161, "Name": "Wall"}, "representation": {"cast_type": "entity_instance", "value": 2834, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 2834, "Name": null}}
# operator: BIM_OT_reorder_material_set_item
# ifcopenshell.api: material.reorder_set_item
>>> {"material_set": {"cast_type": "entity_instance", "value": 405, "Name": null}, "old_index": "0", "new_index": "1"}
# operator: BIM_OT_reorder_material_set_item
# ifcopenshell.api: material.reorder_set_item
>>> {"material_set": {"cast_type": "entity_instance", "value": 405, "Name": null}, "old_index": "2", "new_index": "1"}
# operator: BIM_OT_edit_assigned_material
# ifcopenshell.api: material.edit_assigned_material
>>> {"element": {"cast_type": "entity_instance", "value": 405, "Name": null}, "attributes": "{'LayerSetName': None, 'Description': None}"}
# ifcopenshell.api: material.edit_layer_usage
>>> {"usage": {"cast_type": "entity_instance", "value": 2235, "Name": null}, "attributes": "{'LayerSetDirection': 'AXIS2', 'DirectionSense': 'POSITIVE', 'OffsetFromReferenceLine': 0.0, 'ReferenceExtent': None}"}
# operator: BIM_OT_save_project
# operator: BIM_OT_load_type_thumbnails
last_error: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 797, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 882, in execute
    ifc_importer.execute()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 258, in execute
    self.lock_scales()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 1195, in lock_scales
    voided_elements = tool.Aggregate.get_parts_recursively(element)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\aggregate.py", line 83, in get_parts_recursively
    queue.update(new_parts := set(ifcopenshell.util.element.get_parts(element)))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\element.py", line 1185, in get_parts
    objects.extend(rel.RelatedObjects)
TypeError: 'NoneType' object is not iterable
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: 24-1102 Dietrich Residence LVL Roofs.ifc
schema: IFC4
preprocessor_version: 
originating_system: cadwork version 30.0 build 559
```

**Comment by Andrej730** [comment]
It's invalid IFC file. `rel.RelatedObjects` is not optional and cannot be `None`.
Any ideas what's the source of the file?

**Comment by theoryshaw** [comment]
File is exported out of [CADwork. ](https://cadwork.ca/en/)
