### ISSUE TITLE
Error searching with GlobalId

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5808]
I thought this worked at one point...
![image](https://github.com/user-attachments/assets/1268b452-f03e-491e-91db-03dbb52251d7)

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\search\operator.py", line 167, in execute
    results = ifcopenshell.util.selector.filter_elements(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\selector.py", line 455, in filter_elements
    transformer.transform(filter_elements_grammar.parse(query))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\lark\lark.py", line 655, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\lark\parser_frontends.py", line 104, in parse
    return self.parser.parse(stream, chosen_start, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\lark\parsers\earley.py", line 288, in parse
    raise UnexpectedEOF(expected_terminals, state=frozenset(i.s for i in to_scan))
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: 
	* DOT

```

Had to do this instead. 

![image](https://github.com/user-attachments/assets/ed541d67-ebea-4b66-aa82-79c9470d5fbb)

**Comment by Andrej730** [comment]
It seems to fail with this specific guid.

**Comment by Andrej730** [comment]
This guid is invalid (starts with "k"), see https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcGloballyUniqueId.htm.
