### ISSUE TITLE
IfcWall edited in "Edit mode" does not persist its changed representation.

### ISSUE THREAD

**Issue by marwiss** [IfcOpenShell/IfcOpenShell#5816]
I create a wall using the wall tool.

Then I edit the a blender object of the wall in "Edit mode".

(I select the two triangular faces in one end of the wall and drag it 12 cm to east: G - Y - 0.124)

Then I go back to "Object mode".

I select the edited wall object.

Then I press "Manually Save Representation" under "Debug" in "Quality and Coordination".

Then I save the IFC file.

Finally I reopen the IFC file.

The wall is still back in its original position. The representation did not change.

Maybe I am doing something wrong.

I expected this to work.

How can I persist edits to the geometry of IfcObjects otherwise?

**Comment by marwiss** [comment]
<img width="528" alt="walld" src="https://github.com/user-attachments/assets/f1e6c0df-7ab7-462f-a78a-909c8ca45089">

**Comment by marwiss** [comment]
I tried to press the same button "Manually Save Representation" under "Geometry and Materials". Same problem. Changes to the wall is not persisted when saving and reloading the IFC.

Then I tried to add a new representation by.

1. Editing the wall.
2. Then adding a new representation under Representations - Model - +-button. Choosing "Full representation".

This resulted in error:

```

blender_version: 4.2.3 LTS
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_add_representation
# operator: BIM_OT_add_representation
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 2918, "Name": "B\u00e4rande innerv\u00e4gg 4"}, "matrix": {"cast_type": "ndarray", "value": [[-1.0, -8.662515256219194e-07, 0.0, 6.6519951820373535], [8.662515256219194e-07, -1.0, 0.0, 12.793996810913086], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 2918, "Name": "B\u00e4rande innerv\u00e4gg 4"}}
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 14, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcWall/B\u00e4rande innerv\u00e4gg 4\") at 0x000001C6DDC49D08>", "geometry": "<bpy_struct, Mesh(\"15/9142\") at 0x000001C6DDC48108>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.assign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 2918, "Name": "B\u00e4rande innerv\u00e4gg 4"}, "representation": {"cast_type": "entity_instance", "value": 9162, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 2918, "Name": "B\u00e4rande innerv\u00e4gg 4"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 230, in _execute
    bpy.data.meshes.remove(data)
                           ^^^^
UnboundLocalError: cannot access local variable 'data' where it is not associated with a value

ifc: renovering.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.0
originating_system: Bonsai 0.8.0
```

**Comment by marwiss** [comment]
It worked finally.

I reopened the IFC. Edited the wall in "Edit mode". Then I pressed "Convert to Tesselation" (I think this did the job, because new representations were added).

Then I pressed "Manually save representation" (I don't know if this is necessary).

After saving the IFC and reopening the IFC the manually edited changes to the wall persisted.

**Comment by marwiss** [comment]
I close with comment above.
