### ISSUE TITLE
Cgal indefinetely processing or crashing processing a shape

### ISSUE THREAD

**Issue by fjieikkdddsll** [IfcOpenShell/IfcOpenShell#5820]
Can anyone help troubleshoot this file? I can't open it. Here is the contents of the console when trying to open it:  
[Error bonsai_py311-0.8.1-alpha241127-windows-x64.txt](https://github.com/user-attachments/files/17940920/Error.bonsai_py311-0.8.1-alpha241127-windows-x64.txt)

And here is a zip of the ifc file: 
[HFH Burien Bldg 4-IFC4X3.zip](https://github.com/user-attachments/files/17940921/HFH.Burien.Bldg.4-IFC4X3.zip)

I was experimenting with custom windows. I created the geometry in a blend file and then appended them to the ifc file and created ifc window types from the geometry.

I had done this several times, fixing small issues that I discovered after creating the ifc windows. The last time, I had added a few windows to walls when I realized there was something else I wanted to fix. I deleted all the windows and the window types from the ifc file. I fixed the issues in the blend file and when I tried to reopen the ifc file, it would not open. The first time, the error said something like "unknown file type" or something similar but now blender freezes and the error is as in the above text file.

Thanks for looking.

```python
Error in bpy.app.handlers.load_post[1]:
TypeError: tutorial_popup_handler() takes 0 positional arguments but 2 were given
Starting import process :: 0.00
Loading file :: 0.00
Calculate unit scale :: 0.00
Process context filter :: 0.00
Calculate model offset :: 0.02
Set units :: 0.09
Create project :: 0.00
Process element filter :: 0.01
Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\operator.py", line 426, in execute
    tool.Blender.copy_node_graph(material, db["data_block"])
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 343, in copy_node_graph
    temp_override = cls.get_shader_editor_context()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 327, in get_shader_editor_context
    if space.tree_type == "ShaderNodeTree":
       ^^^^^^^^^^^^^^^
AttributeError: 'SpaceView3D' object has no attribute 'tree_type'. Did you mean: 'rna_type'?
Error: Python: Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\operator.py", line 426, in execute
    tool.Blender.copy_node_graph(material, db["data_block"])
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 343, in copy_node_graph
    temp_override = cls.get_shader_editor_context()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 327, in get_shader_editor_context
    if space.tree_type == "ShaderNodeTree":
       ^^^^^^^^^^^^^^^
AttributeError: 'SpaceView3D' object has no attribute 'tree_type'. Did you mean: 'rna_type'?
Location: D:\Documents D\BIM Projects\blender for bim\4.2\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\prop.py", line 273, in update_shading_style
    tool.Style.switch_shading(blender_material, self.active_style_type)
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\style.py", line 624, in switch_shading
    raise error
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\style.py", line 620, in switch_shading
    bpy.ops.bim.activate_external_style(material_name=blender_material.name)
  File "D:\Documents D\BIM Projects\blender for bim\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\operator.py", line 426, in execute
    tool.Blender.copy_node_graph(material, db["data_block"])
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 343, in copy_node_graph
    temp_override = cls.get_shader_editor_context()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 327, in get_shader_editor_context
    if space.tree_type == "ShaderNodeTree":
       ^^^^^^^^^^^^^^^
AttributeError: 'SpaceView3D' object has no attribute 'tree_type'. Did you mean: 'rna_type'?
Location: D:\Documents D\BIM Projects\blender for bim\4.2\scripts\modules\bpy\ops.py:109

File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\prop.py", line 268, in update_shading_style
Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\operator.py", line 426, in execute
    tool.Blender.copy_node_graph(material, db["data_block"])
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 343, in copy_node_graph
    temp_override = cls.get_shader_editor_context()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 327, in get_shader_editor_context
    if space.tree_type == "ShaderNodeTree":
       ^^^^^^^^^^^^^^^
AttributeError: 'SpaceView3D' object has no attribute 'tree_type'. Did you mean: 'rna_type'?
Error: Python: Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\operator.py", line 426, in execute
    tool.Blender.copy_node_graph(material, db["data_block"])
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 343, in copy_node_graph
    temp_override = cls.get_shader_editor_context()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 327, in get_shader_editor_context
    if space.tree_type == "ShaderNodeTree":
       ^^^^^^^^^^^^^^^
AttributeError: 'SpaceView3D' object has no attribute 'tree_type'. Did you mean: 'rna_type'?
Location: D:\Documents D\BIM Projects\blender for bim\4.2\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\prop.py", line 273, in update_shading_style
    tool.Style.switch_shading(blender_material, self.active_style_type)
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\style.py", line 624, in switch_shading
    raise error
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\style.py", line 620, in switch_shading
    bpy.ops.bim.activate_external_style(material_name=blender_material.name)
  File "D:\Documents D\BIM Projects\blender for bim\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\operator.py", line 426, in execute
    tool.Blender.copy_node_graph(material, db["data_block"])
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 343, in copy_node_graph
    temp_override = cls.get_shader_editor_context()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 327, in get_shader_editor_context
    if space.tree_type == "ShaderNodeTree":
       ^^^^^^^^^^^^^^^
AttributeError: 'SpaceView3D' object has no attribute 'tree_type'. Did you mean: 'rna_type'?
Location: D:\Documents D\BIM Projects\blender for bim\4.2\scripts\modules\bpy\ops.py:109

File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\prop.py", line 268, in update_shading_style
Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\operator.py", line 426, in execute
    tool.Blender.copy_node_graph(material, db["data_block"])
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 343, in copy_node_graph
    temp_override = cls.get_shader_editor_context()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 327, in get_shader_editor_context
    if space.tree_type == "ShaderNodeTree":
       ^^^^^^^^^^^^^^^
AttributeError: 'SpaceView3D' object has no attribute 'tree_type'. Did you mean: 'rna_type'?
Error: Python: Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\operator.py", line 426, in execute
    tool.Blender.copy_node_graph(material, db["data_block"])
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 343, in copy_node_graph
    temp_override = cls.get_shader_editor_context()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 327, in get_shader_editor_context
    if space.tree_type == "ShaderNodeTree":
       ^^^^^^^^^^^^^^^
AttributeError: 'SpaceView3D' object has no attribute 'tree_type'. Did you mean: 'rna_type'?
Location: D:\Documents D\BIM Projects\blender for bim\4.2\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\prop.py", line 273, in update_shading_style
    tool.Style.switch_shading(blender_material, self.active_style_type)
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\style.py", line 624, in switch_shading
    raise error
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\style.py", line 620, in switch_shading
    bpy.ops.bim.activate_external_style(material_name=blender_material.name)
  File "D:\Documents D\BIM Projects\blender for bim\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\operator.py", line 426, in execute
    tool.Blender.copy_node_graph(material, db["data_block"])
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 343, in copy_node_graph
    temp_override = cls.get_shader_editor_context()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 327, in get_shader_editor_context
    if space.tree_type == "ShaderNodeTree":
       ^^^^^^^^^^^^^^^
AttributeError: 'SpaceView3D' object has no attribute 'tree_type'. Did you mean: 'rna_type'?
Location: D:\Documents D\BIM Projects\blender for bim\4.2\scripts\modules\bpy\ops.py:109

File "D:\Documents D\BIM Projects\blender for bim\portable\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\style\prop.py", line 268, in update_shading_style
WARNING. Unsupported reflectance method "None" on style {'id': 42091, 'type': 'IfcSurfaceStyleRendering', 'SurfaceColour': (0.800000011920929, 0.800000011920929, 0.800000011920929), 'Transparency': 0.0, 'DiffuseColour': ('IfcColourRgb', (0.800000011920929, 0.800000011920929, 0.800000011920929)), 'TransmissionColour': None, 'DiffuseTransmissionColour': None, 'ReflectionColour': None, 'SpecularColour': None, 'SpecularHighlight': None, 'ReflectanceMethod': None}
WARNING. Unsupported reflectance method "None" on style {'id': 42101, 'type': 'IfcSurfaceStyleRendering', 'SurfaceColour': (0.800000011920929, 0.800000011920929, 0.800000011920929), 'Transparency': 0.0, 'DiffuseColour': ('IfcColourRgb', (0.800000011920929, 0.800000011920929, 0.800000011920929)), 'TransmissionColour': None, 'DiffuseTransmissionColour': None, 'ReflectionColour': None, 'SpecularColour': None, 'SpecularHighlight': None, 'ReflectanceMethod': None}
WARNING. Unsupported reflectance method "None" on style {'id': 42136, 'type': 'IfcSurfaceStyleRendering', 'SurfaceColour': (0.800000011920929, 0.800000011920929, 0.800000011920929), 'Transparency': 0.0, 'DiffuseColour': ('IfcColourRgb', (0.800000011920929, 0.800000011920929, 0.800000011920929)), 'TransmissionColour': None, 'DiffuseTransmissionColour': None, 'ReflectionColour': None, 'SpecularColour': None, 'SpecularHighlight': None, 'ReflectanceMethod': None}
WARNING. Unsupported reflectance method "None" on style {'id': 42369, 'type': 'IfcSurfaceStyleRendering', 'SurfaceColour': (0.800000011920929, 0.800000011920929, 0.800000011920929), 'Transparency': 0.0, 'DiffuseColour': ('IfcColourRgb', (0.800000011920929, 0.800000011920929, 0.800000011920929)), 'TransmissionColour': None, 'DiffuseTransmissionColour': None, 'ReflectionColour': None, 'SpecularColour': None, 'SpecularHighlight': None, 'ReflectanceMethod': None}
Create styles :: 0.12
Parsing native elements :: 0.00
Done creating geometry
Create native elements :: 0.00
250 / 336 (74% created, 78% preprocessed) elements processed in 0.19s ...
Done creating geometry
Create elements :: 0.27
Done creating geometry
Create annotations :: 0.03
Create positioning elements :: 0.01
0 / 6 elements processed ...
Create spatial elements :: 0.00
Create structural items :: 0.00
intersection not inside
```

**Comment by Andrej730** [comment]
Was able to narrow it down to the following snippet. @aothms can you please take a look?

```python
import ifcopenshell
import ifcopenshell.geom.main
import ifcopenshell.ifcopenshell_wrapper as W

ifc_file = ifcopenshell.open(r"HFH Burien Bldg 4-IFC4X3.ifc")
assert isinstance(ifc_file, ifcopenshell.file)
settings = ifcopenshell.geom.settings()
settings.set('apply-default-materials', False)
settings.set("context-ids", (24,))

rep = ifc_file.by_id(55003)
print(settings)

# W.turn_on_detailed_logging()

ifcopenshell.geom.create_shape(settings, rep, geometry_library="opencascade")
print('opencascade finished')

# ifcopenshell.geom.create_shape(settings, rep, geometry_library="cgal")
# print('never printed due to crash')

# Prints 'intersection not inside' and freezing.
shape = ifcopenshell.geom.create_shape(settings, rep, geometry_library="hybrid-cgal-simple-opencascade")
```

**Comment by aothms** [comment]
Thanks @Andrej730 should be fixed with latest commit

**Comment by Moult** [comment]
Confirming fixed
