### ISSUE TITLE
Error when validating open model

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5830]
Here is the error:

```
Python: Traceback (most recent call last):
  File "/Users/petru/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/validate.py", line 495, in validate
    assert_valid(attr_type, val, schema, attr=attr)
  File "/Users/petru/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/validate.py", line 249, in assert_valid
    or not all(assert_valid(ty, v, schema, attr=attr) for v in val)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petru/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/validate.py", line 249, in <genexpr>
    or not all(assert_valid(ty, v, schema, attr=attr) for v in val)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petru/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/validate.py", line 247, in assert_valid
    len(val) < b1
    ^^^^^^^^
TypeError: object of type 'int' has no len()
```

Blender 4.3 with daily Bonsai build.

**Comment by aothms** [comment]
Should be fixed. Note that the model is invalid there, but the validator should handle that gracefully.

**Comment by BIMvoice** [comment]
> Should be fixed. Note that the model is invalid there, but the validator should handle that gracefully.

Thank you Thomas for the swift fix. Why do you say the model is invalid? :)

**Comment by aothms** [comment]
Where a collection of values is expected, a single value is provided.
That's why the validator complained about the value not having a length.

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op zo 1 dec 2024 07:54 schreef Petru Conduraru ***@***.***>:
