### ISSUE TITLE
IfcAdvancedBrep

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#586]
Just tried to import these exapmles in FreeCAD with IfcOpenShell 0.5.

https://github.com/buildingSMART/IfcDoc/tree/master/IfcKit/examples/advanced-geometric-shape

No shape was returned. Before I gone start to debug this in FreeCADs ifc-importer I just wanted to generally ask if IfcOpenShell 0.5 should return a brep for them?

bernd

**Comment by aothms** [comment]
If and only if IfcOpenShell 0.5 was compiled for IFC4. I think the cube ought to work, but I also remember people complaining the edge orientations are not entirely correct on that one.

**Comment by berndhahnebach** [comment]
Are there more examples around of IfcAdvancedBrep around?

Which software is able to write this veometric entity?

**Comment by berndhahnebach** [comment]
Cool, I will give it a try and report back.

**Comment by berndhahnebach** [comment]
Just to be sure: These are IFC2x3 builds ... https://github.com/IfcOpenBot/IfcOpenShell/commit/bf16239

**Comment by aothms** [comment]
Not sure about the software. The automated builds are 2x3. You can check in
python with something like ifcopenshell.schema_identifier I had been
planning to provide both build versions, but with 0.6 in a usable state,
it's just not worth the effort.

Op do 16 mei 2019 08:55 schreef Bernd Hahnebach <notifications@github.com>:

**Comment by berndhahnebach** [comment]
great ... I seam to know what is needed and what will be the next steps ... 

![screen](https://user-images.githubusercontent.com/6129869/57836952-16b78f00-77c2-11e9-95a8-c810c81e9b97.jpg)

**Comment by berndhahnebach** [comment]
Success with the cube one ... :-) 

![Screenshot_20190528_234703](https://user-images.githubusercontent.com/6129869/58670310-dff38400-833e-11e9-90e3-4be98b4a0ef2.png)

**Comment by berndhahnebach** [comment]
But no success with the basin-advanced-brep.ifc ( https://github.com/buildingSMART/IfcDoc/blob/master/IfcKit/examples/advanced-geometric-shape/basin-advanced-brep.ifc ) but this is strange any way because there is no entity to import. I just tried the IFCSHAPEREPRESENTATION directly by 

```
>>> 
>>> p = f.by_id(615)
>>> p
#615=IfcShapeRepresentation(#5,'Body','SolidModel',(#612))
>>> cr = ifcopenshell.geom.create_shape(settings, p)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ifcopenshell/geom/main.py", line 170, in create_shape
    repr.wrapped_data if repr is not None else None
  File "/usr/lib/python3/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 499, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process representation item
>>> 
```

**Comment by berndhahnebach** [comment]
out of 10 examples exported from Allplan, this is what I get ... 

![Screenshot_20190531_010638](https://user-images.githubusercontent.com/6129869/58670750-7e341980-8340-11e9-8562-ba9824d6250b.png)

**Comment by berndhahnebach** [comment]
I get the same error as for the buildingsmart bassin

```
>>>
>>> p8 = f.by_id(4488)
>>> cr = ifcopenshell.geom.create_shape(settings, p8)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ifcopenshell/geom/main.py", line 170, in create_shape
    repr.wrapped_data if repr is not None else None
  File "/usr/lib/python3/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 499, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process shape
>>> 

```

**Comment by aothms** [comment]
> but this is strange any way because there is no entity to import. I just tried the IFCSHAPEREPRESENTATION directly by

There is a IfcSanitaryTerminal:

https://github.com/buildingSMART/IfcDoc/blob/master/IfcKit/examples/advanced-geometric-shape/basin-advanced-brep.ifc#L52

It's not a IfcBuildingElement, but by_type('IfcElement') should work.

I'll have a look at the basin

**Comment by Moult** [comment]
+1 that I get the same results as @berndhahnebach

**Comment by Moult** [comment]
Just bumping this thread from the activity here: https://forums.buildingsmart.org/t/dwg-sat-solids-conversion-to-ifc/1970

Revit also produces a lot of IfcAdvancedBreps when it does an IFC4 export ... is there any activity on this bug?

**Comment by berndhahnebach** [comment]
AFAIK Allplan will export them in Release 2020 (which just has been released, but it will take a few month until it is on my computer) too. Would be good if we could get this working in ifcOpenShell and thus in FreeCAD and blender :-)

If needed I would install Alplan 2020 just to provide more examples. 

related topic on FreeCAD forum: https://forum.freecadweb.org/viewtopic.php?f=23&t=40378&p=344485#p344485

**Comment by aothms** [comment]
> I get the same error as for the buildingsmart bassin

The basin appears to be invalid? Latest version of IfcConvert will complain with a better error message

~~~
[Error] {0dOOwKTsn8I8gwbP3LM1Yz} Token (#50,#51,#52,#53,#50,#51,#52,#54,#55,#56,#57,#54,#55,#56,#58,#59,#60,#61,#58,#59,#60,#62,#63,#64,#65,#62,#63,#64) at 3133 invalid nested aggregate
~~~

**Comment by berndhahnebach** [comment]
Does this mean one of the less available official IfcAdvancedBrep examples is a brocken ifc?

**Comment by aothms** [comment]
@berndhahnebach I think so, second opinion welcome

**Comment by hlg** [comment]
I am not so sure. Looking at the error message I see an aggregation of 28 entities.

    Token (#50,#51,#52,#53,#50,#51,#52,#54,#55,#56,#57,#54,#55,#56,#58,#59,#60,#61,#58,#59,#60,#62,#63,#64,#65,#62,#63,#64)

However, looking at the example IFC file itself, I can not find any similar structure. Given that the error message appears during parsing of [this file](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/annex/annex-e/basin-advanced-brep.ifc), it is not clear to me where this token should come from. There is, however an aggregation of 4 aggregations of 7 entities, for instance:

    #572= IFCBSPLINESURFACEWITHKNOTS(...((#573,#574,#575,#576,#573,#574,#575),(#577,#578,#579,#580,#577,#578,#579),(#581,#582,#583,#584,#581,#582,#583),(#585,#586,#587,#588,#585,#586,#587)),...)

I also gave some attention to other representation items, comparing the present data structures to the schema and did not find any obvious invalidity.

I wonder if something goes wrong before the parser comes to this place, that is there is some disregarded edge case during tokenization.

**Comment by aothms** [comment]
Thanks @hlg I was indeed looking at the wrong file..

There were two issues how IfcOpenShell treats the original file.

~~~
#510= IFCBSPLINECURVEWITHKNOTS(3,(#511,#512,#513,#514,#511,#512,#513),.UNSPECIFIED.,.T.,.T.,(1,1,1,1,1,1,1,1,1,1,1),(-7.0,-6.0,-5.0,-4.0,-3.0,-2.0,-1.0,0.0,1.0,2.0,3.0),.UNSPECIFIED.);
~~~

`#510` is said to be a ClosedCurve. I had interpreted this as it means the bspline curve is periodic, which has an implication on the amount of control points vs multiplicities and degree. This number does not line up in that case. If I treat the bspline curve as non-period, the amount of control points does line up. So I guess my interpretation was incorrect, something closed can still be not periodic.

But even then if you look at the the edge referencing the curve:

~~~
#515= IFCEDGECURVE(#505,#505,#510,.T.);
~~~

it is bounded by the same vertex twice. Again not really sure what the standard says in this case. Since non-finite extent is not supported, I guess it's safe to detect the curve is closed and if the vertices are close enough, use the entire curve for the edge.

With a1253b004d66406ecc457c46cedd1adf0b86fca7 at least something shows up now.

**Comment by aothms** [comment]
The outer face is missing because OCCT fails to triangulate it. The meshing is one of the last bits of OCCT that are like black magic to me...

![afbeelding](https://user-images.githubusercontent.com/1096535/68218054-00a5c100-ffe4-11e9-9b0a-7f52cdf835f5.png)

**Comment by hlg** [comment]
That same start and end vertex caught my attention as well. Indeed the standard explicitly mentions that "The same vertex can be used for both `EdgeStart` and `EdgeEnd`". Seems It becomes much clearer now.

Apparently with the first interpretation you barked up the wrong tree. The standard says the `ClosedCurve` attribute is informational only. Thus it should not impact interpretation and then the only way to model a closed curve is by repetition of the control points as done here. Even though the bspline may be closed geometrically, the edge of the curved surface does not form a closed loop along this spline topologically. Instead it runs around the one spline, along a straight line towards the other spline, around that second spline and back along the line in opposite direction.

    #504= IFCVERTEXPOINT(#500);
    #505= IFCVERTEXPOINT(#501);
    #508= IFCPOLYLINE((#500,#501));
    #509= IFCEDGECURVE(#504,#505,#508,.T.);
    #510= IFCBSPLINECURVEWITHKNOTS(...);
    #515= IFCEDGECURVE(#505,#505,#510,.T.);
    #523= IFCBSPLINECURVEWITHKNOTS(...);
    #524= IFCEDGECURVE(#504,#504,#523,.T.);
    #542= IFCORIENTEDEDGE(*,*,#509,.T.);
    #543= IFCORIENTEDEDGE(*,*,#515,.T.);
    #544= IFCORIENTEDEDGE(*,*,#509,.F.);
    #545= IFCORIENTEDEDGE(*,*,#524,.T.);
    #546= IFCEDGELOOP((#542,#543,#544,#545));

Seems like there is [another way to model `IfcAdvancedFace` with periodic surfaces](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcadvancedface.htm) without using the seam line and with two loops as facebounds instead, none of them being outer bounds. Not sure why the example does not use `IfcSeamCurve` as suggested in the `IfcAdvancedFace` documentation but also not sure if that would make it easier.

Weired that the tringulation fails, since it should have the same structure as the other surface.

**Comment by aothms** [comment]
> Weired that the tringulation fails, since it should have the same structure as the other surface.

It does, I'll report to OCCT I guess. It's still likely something I'm doing wrong though.

Open CASCADE actually needs the face to be bounded both in the U and the V direction, even for periodic surfaces. So it should be actually better this way.

Seam curves and Surface/P-curves are added in Add2 and I think all of the examples are from before.

Thanks for having a look, really appreciated!

**Comment by berndhahnebach** [comment]
Which ifcos do I need to take to test again 0.6 or 0.7?

bernd

**Comment by aothms** [comment]
This is committed to the v0.6.0 branch, not available yet as a precompiled build

**Comment by aothms** [comment]
> Weired that the tringulation fails, since it should have the same structure as the other surface.

Turns out to be something that more elaborate occt shape fix can't fix. Ideally I'd like to understand a bit better what the issue was, but I'll leave it up to occt then :)

c89d2689869cedd4e5d21f27e718c59c3eaf065d

**Comment by berndhahnebach** [comment]
> This is committed to the v0.6.0 branch, not available yet as a precompiled build

nevermind. For myself I use linux and can compile myself. The precompiled we only use for packaging FreeCAD for download.

**Comment by berndhahnebach** [comment]
Here a few exports from Allplan some work some not. 

`
>>> 
>>> import ifcopenshell
>>> 
>>> # from importIFC
... from ifcopenshell import geom
>>> settings = ifcopenshell.geom.settings()
>>> settings.set(settings.USE_BREP_DATA,True)
>>> settings.set(settings.SEW_SHELLS,True)
>>> settings.set(settings.USE_WORLD_COORDS,True)
>>> 
>>> ifcfile = '/home/hugo/.FreeCAD/Mod/IFCToolBox/More_IfcAdvancedBrep.ifc'
>>> 
>>> f = ifcopenshell.open(ifcfile)
>>> proxies = f.by_type('IfcBuildingElementProxy')
>>> 
>>> for p in proxies:
...     try:
...         cr = ifcopenshell.geom.create_shape(settings, p)
...         print(' GOOD shape from IFCOS for {}'.format(p.id()))
...     except:
...         print(' NO shape from IFCOS for {}'.format(p.id()))
... 
 GOOD shape from IFCOS for 490
 GOOD shape from IFCOS for 3662
 GOOD shape from IFCOS for 3779
 NO shape from IFCOS for 3850
 NO shape from IFCOS for 3989
 NO shape from IFCOS for 4144
 NO shape from IFCOS for 4297
 NO shape from IFCOS for 4488
>>> 
`

[More_IfcAdvancedBrep.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/3821072/More_IfcAdvancedBrep.ifc.zip)

**Comment by elrapha** [comment]
I have the same issue using python 3.6 locally. I get a similar error @berndhahnebach 

```
Traceback (most recent call last):
  File "/home/user/Desktop/ifc.py", line 39, in <module>
    shape = ifcopenshell.geom.create_shape(settings, inst=product)
  File "/home/user/anaconda3/lib/python3.6/site-packages/ifcopenshell/geom/main.py", line 164, in create_shape
    repr.wrapped_data if repr is not None else None
  File "/home/user/anaconda3/lib/python3.6/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 497, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process shape
```

However...the following project runs perfectly without problems but it uses python 3.7. So far the python version is the only difference between this docker image setup and my local setup
https://github.com/tpaviot/pythonocc-binderhub

**Comment by aothms** [comment]
Yeah advanced brep is definately work in progress still.

> However...the following project runs perfectly without problems but it uses python 3.7. So far the python version is the only difference between this docker image setup and my local setup

That's very odd though. There isn't anything specific in IfcOpenShell related to python versions. Does `print(ifcopenshell.get_log())` give you anything meaningful as to why processing shape fails. Could also be allocation failure (out of memory) although I guess that's unlikely.

**Comment by aothms** [comment]
For 3850, I'm not so sure this is correct in IFC:

I think this is literally the same edge backwards, so you get a face without area and it is filtered:

~~~
#40=IFCCIRCLE(#39,2.6571185856253);
#41=IFCEDGECURVE(#33,#35,#40,.T.);
#42=IFCORIENTEDEDGE(*,*,#41,.F.);
#43=IFCORIENTEDEDGE(*,*,#41,.T.);
#44=IFCEDGELOOP((#42,#43));
~~~

The same for 3989 but then with bspline curves

For 4144 there are a couple of vertex-edge projections that fail because the distance is above the model tolerance. These are properly logged now. If I change model precision to `1.e-2` quite a few succeed now.

[4488.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/4780831/4488.ifc.txt)

**Comment by aothms** [comment]
There are a couple more here btw https://github.com/buildingSMART/Sample-Test-Files/tree/master/IFC%204.0/NURBS/Bentley%20Building%20Designer/Faces

**Comment by hlg** [comment]
> For 3850, I'm not so sure this is correct in IFC:

I think it is, because the geometry of that face is a spherical surface.

I assume for that topology (a bounded spherical surface) you would determine which part of the sphere is the interesting one by virtue of the bounding loop orientation. In this case where the loop is "collapsed", it may be assumed you want the non-empty part, hence the whole sphere? The edge is kind of an artificial seam again.

![20200615_advancedbrep-spherical-s](https://user-images.githubusercontent.com/356986/84674820-bbf3e800-af2b-11ea-8ff0-633102541ed1.png)

**Comment by aothms** [comment]
> I think it is, because the geometry of that face is a spherical surface.

D'oh I completely missed that. Thanks for proofreading.

> it may be assumed you want the non-empty part, hence the whole sphere?

The mass of the face is on the left-hand side of the curve. 

> That is, each loop runs counter-clockwise around the face when viewed from above

https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/schema/ifctopologyresource/lexical/ifcface.htm

But the left-hand side is not really well-defined with two identical reversed edges.

What OCCT needs anyway is 4 edges. Two edges at the poles that are degenerate in 3D space, but span [0 2pi] in the U range, so that the full parametric rectangle of the sphere is enclosed. I think OCCT should be able to infer these on import, but I'll have to look into this. 

> The problem: Face on a periodical surface is limited by wires which make a full trip around the surface. These wires are closed in 3d but not closed in parametric space of the surface. This is not valid in Open CASCADE. The solution: Shape Healing fixes this face by inserting seam edge which combines two open wires and thus closes the parametric space. Note that internal wires are processed correctly.

https://www.opencascade.com/doc/occt-7.2.0/overview/html/occt_user_guides__shape_healing.html

I assume this is a solved problem in the world of STEP...

**Comment by aothms** [comment]
@jmirtsch was kind enough to test, while his importer in Rhino does import the sphere, it also considers the face bound invalid and then fall backs to the entire spherical surface.

![200617 import](https://user-images.githubusercontent.com/1096535/84884070-8ec14a00-b091-11ea-8436-3b235523e283.png)

**Comment by aothms** [comment]
![afbeelding](https://user-images.githubusercontent.com/1096535/84886876-49068080-b095-11ea-9513-acaf38c78050.png)

https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/schema/ifcgeometricmodelresource/lexical/ifcadvancedbrep.htm

Actually the advanced brep docs page also suggests a much more elaborate schema to exchange this. I think we can forget about 3850. For these kind of periodic surfaces we simply need the parametric 2d curves to be unambiguous I guess.

Not saying it can't be fixed, but let's aim for more complete exchanges with pcurves first.

**Comment by hlg** [comment]
Yes, indeed. In this case you would probably require an `IfcSeamCurve` in instead of `IfcIntersectionCurve`. I mentioned that before for the basin example where the official sample does not adhere to this.

>In case of closed faces with periodic surfaces, such as cylindrical or spherical surfaces, the following applies:
> 
>- the edges of the closed surface, in case of a cylindrical surface the upper and lower cap, refer to the same instance of IfcVertexPoint twice,
>-  no IfcFaceOuterBound is provided, or the IfcFaceOuterBound is constructed using an IfcSeamCurve at the periodic end of the underlying closed surface, in case of a cylindrical surface at 0./360. degree.

([IfcAdvancedFace documentation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/schema/ifctopologyresource/lexical/ifcadvancedface.htm))

I edited the sample in case to use the IfcSeamCurve in case anyone wants to play around with it. Maybe OCCT can deal with those seam curves? Not sure though whether this is fully valid, particularly whether the degenerated edges need to be included in the seam or not: [More-IfcAdvancedBrep-3850-seamcurve.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/4792481/More-IfcAdvancedBrep-3850-seamcurve.ifc.txt)

**Comment by aothms** [comment]
Thanks @hlg Couple quesions/comments (really not so sure anymore):

IfcSeamCurve.Curve3D is now the full circle. Should this be a trimmed curve that matches extent of the pcurves, which are bounded? To me it's strange that only the 2d is bounded now and 3d not.  I guess this is also the case in the IFC standards diagram, but maybe then I would prefer IfcLine instead of IfcPolyline. This is an honest question.

I think you forgot to include the IfcSeamCurve in the IfcEdgeCurve which still references the circle.

I'm also not so sure about the parametric polylines having discontinuities, i.e. 3 points. I think we should have an IfcEdgeLoop with four continuous edges. Two of which degenerate in 3D. Two of which the seam curve with opposing orientation.

I will also try to serialize a Circle constructed by OCCT to IFC as well and see if we can correlate that to your manually crafted example.

> Just saying that it would probably be ok to forget about this case, because I don't exactly see a reason to use advanced BREP for a sphere.

Well, yes and no, IfcSphere is a IfcCsgPrimitive3D and probably not part of Reference View? What alternatives do we have? We would have the same issue when exchanging part of a Sphere surface that it includes the poles. Question mark?

**Comment by berndhahnebach** [comment]
Come back to this ... Since http://viewer.ifcopenshell.org exist it is very easy to test ifc and ifcopenshell. Exported three simple geometries from Allplan, A cone, a cylinder and a sphere. Allplan itself does import the exported geometries. IfcOpenShell can read the cylinder and the cone but has problems with the sphere. I wonder if it is Allplan or IfcOpenShell problem. 

cheers bernd

remove .txt
[IfcAdvanceFace_cone_cylinder_sphere .ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/5186885/IfcAdvanceFace_cone_cylinder_sphere.ifc.txt)

**Comment by aothms** [comment]
Thanks @berndhahnebach 

>  I wonder if it is Allplan or IfcOpenShell problem.

The truth is in the middle. Allplan could do more (export the parametric curve definitions to make surface not ambiguous). IfcOpenShell could do more to detect degenerate situation and use full sphere.

> How long is the link valid?

Indefinite currently. But this probably needs to change due to regulations and safety etc.

**Comment by berndhahnebach** [comment]
Thanks Thomas for the informations.

How do I make a IfcAdvancedFace geometry out of a brep curved geometry by Python? I may create some with IfcOpenShell and send them to the Allplan Devs.

cheers bernd

**Comment by berndhahnebach** [comment]
> How do I make a IfcAdvancedFace geometry out of a brep curved geometry by Python? I may create some with IfcOpenShell and send them to the Allplan Devs.


anyone how has some information in this regard?

**Comment by aothms** [comment]
Did you try ifcopenshell.geom.serialize() with schema = IFC4 or higher and
advanced =true? It won't be perfect in every case, but it's a start.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op wo 27 jan. 2021 14:13 schreef Bernd Hahnebach <notifications@github.com>:

**Comment by berndhahnebach** [comment]
just gave this another try ... 

Attached some free form bodies exported from Allplan 2022-1-10 ... and a pic of Allplan CAD

[free_form_bodies_Allplan_2022-1-10.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11146350/free_form_bodies_Allplan_2022-1-10.ifc.txt)

![grafik](https://user-images.githubusercontent.com/6129869/229734297-e73acb78-686c-4dd4-9e80-1199949f2df4.png)

**Comment by berndhahnebach** [comment]
Here is how it looks in view.ifcopenshell ... FreeCAD which is based on IfcOpenShell does the same ... 

![grafik](https://user-images.githubusercontent.com/6129869/229734616-6e6484cb-21bb-44f3-bbe1-e91fed409ffb.png)


![grafik](https://user-images.githubusercontent.com/6129869/229735057-ce1b8c16-0dc9-42a4-8acd-5e4b7ba31fc7.png)

**Comment by berndhahnebach** [comment]
my favorite comercial free viewer BIMCollabZoom does a good job as well, but has problems too ...

![grafik](https://user-images.githubusercontent.com/6129869/229735644-9397472c-7974-48f3-b3a0-6197971b07c4.png)

**Comment by berndhahnebach** [comment]
Solibri, probably the most expensive viewer out there does a really bad job on free form bodies ... 

![grafik](https://user-images.githubusercontent.com/6129869/229736996-b7553d31-8c4e-4787-8d36-c6e760d8f7f7.png)

**Comment by berndhahnebach** [comment]
interesting point ... even Allplan can not import all Shapes it has exported ... 

![grafik](https://user-images.githubusercontent.com/6129869/229743630-6d4a8d8f-74aa-498e-91bd-9ed24375024a.png)

**Comment by berndhahnebach** [comment]
started a topic as osarch too ... https://community.osarch.org/discussion/1415/

**Comment by BIMvoice** [comment]
Status check on everything named in this thread, tested on current v0.8.0 with the official files and the 2023 Allplan attachments:

| File | Result |
|---|---|
| cube-advanced-brep | converts (1432v/2860f) |
| basin-advanced-brep | converts, all 5 faces present, the 2019 triangulation failure is gone |
| basin-faceted-brep | converts |
| Allplan Frustum/Cone/Cylinder/Arc/Turned Cuboid/Cuboid/Elliptic Cone | all convert |
| Allplan Sphere | failed (dead `IfcSphericalSurface` mapping stub); fixed in #8853 |
| Allplan Ellipsoid | still fails: rational BSpline surface with a pole-to-pole degenerate seam, the same class as the original basin bug but with no primitive shortcut available; needs generic seam handling in the face builder or an upstream OCCT fix |

So the originally-reported files are fixed by the geometry-pipeline evolution since 2019, the Sphere is fixed by #8853, and the Ellipsoid remains as the one genuine residual. @aothms your call whether that residual keeps this issue open or deserves a fresh, narrower ticket.
