### ISSUE TITLE
Wall Shift+A gives error if no type is selected

### ISSUE THREAD

**Issue by carlopav** [IfcOpenShell/IfcOpenShell#5863]
Easy one. Steps to reproduce
- create a new project;
- select the wall tool;
- press Shift+A
- error: 

````
os: Windows
os_version: 10.0.22631
python_version: 3.11.9
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
blender_version: 4.3.0
bonsai_version: 0.0.0
bonsai_commit_hash: ce6a508
last_actions: 
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcBuildingStorey", "predefined_type": "None", "name": "My Storey"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 43, "Name": "My Storey"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 43, "Name": "My Storey"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 31, "Name": "My Site"}], "relating_object": {"cast_type": "entity_instance", "value": 1, "Name": "My Project"}}
# ifcopenshell.api: spatial.unassign_container
>>> {"products": "[]"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 31, "Name": "My Site"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 31, "Name": "My Site"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 37, "Name": "My Building"}], "relating_object": {"cast_type": "entity_instance", "value": 31, "Name": "My Site"}}
# ifcopenshell.api: spatial.unassign_container
>>> {"products": "[]"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 37, "Name": "My Building"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 37, "Name": "My Building"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 43, "Name": "My Storey"}], "relating_object": {"cast_type": "entity_instance", "value": 37, "Name": "My Building"}}
# ifcopenshell.api: spatial.unassign_container
>>> {"products": "[]"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 43, "Name": "My Storey"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 43, "Name": "My Storey"}}
# operator: BIM_OT_hotkey
last_error: Traceback (most recent call last):
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\workspace.py", line 935, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\carlo\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\workspace.py", line 957, in hotkey_S_A
    props.relating_type_id = relating_type_id
    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: expected a string enum, not NoneType

ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell 0.0.0
originating_system: IfcOpenShell 0.0.0
````

the hotkey_S_A class function in workspace.py module does not check if relating_type_id is null (line 956). I could submit a commit but i'm not sure about how i am supposed to handle those checks.

**Comment by carlopav** [comment]
thanks!
