### ISSUE TITLE
error saving dxf linework to ifc

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5870]
[20241211 - error saving dxf linework to ifc.zip](https://github.com/user-attachments/files/18105088/20241211.-.error.saving.dxf.linework.to.ifc.zip)

https://github.com/user-attachments/assets/b761c307-9dee-446c-9c7c-0248ec91e75a

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\root\operator.py", line 226, in _execute
    representation = tool.Geometry.export_mesh_to_tessellation(obj, ifc_context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 1732, in export_mesh_to_tessellation
    material_index = mesh.polygons[0].material_index
                     ~~~~~~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

```

**Comment by Gorgious56** [comment]
I got the same error a few days ago on a mesh, so I don't think it has to do with dxf or line meshes specifically. I narrowed it down to some corrupted geometry (vertex, edge or face) as I separated geometry recursively and tried adding Ifc data to it but didn't have the time to investigate further.

**Comment by Gorgious56** [comment]
I'm reopening because I'm having the same error but for another reason, but I think it's the same underyling bug. I'm trying to assign an IFC class to a Blender object. I noticed there is a stray vertex that is not tied to any edge or face :

![image](https://github.com/user-attachments/assets/da5117b4-1cda-4508-9fa1-a69e50c8ec54)

It also happens if there is a stray edge

![image](https://github.com/user-attachments/assets/2a061495-28ec-4756-a60d-ecf444b43388)


```
Error: Python: Traceback (most recent call last):
  File "C:\Users\nhild\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\root\operator.py", line 226, in _execute
    representation = tool.Geometry.export_mesh_to_tessellation(obj, ifc_context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 1732, in export_mesh_to_tessellation
    material_index = mesh.polygons[0].material_index
                     ~~~~~~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0
```
