### ISSUE TITLE
Tabbing in, creates too many representation items. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5874]
Tabbing in, creates too many representation items. 

file: https://hub.openingdesign.com/OpeningDesign/Restaurant_MPM/src/commit/8b9b619ce6d70035daf0c9144e3b1da868402e3e/Open/Models/BlenderBIM/Restaurant_MPM.ifc

https://github.com/user-attachments/assets/509ce8af-024f-4915-adda-beced4b4fcb5

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 441, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 2009, in _invoke
    self.edit_representation_item(context.active_object)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\geometry\operator.py", line 2159, in edit_representation_item
    new = tool.Model.export_curves(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\model.py", line 149, in export_curves
    result = cls.auto_detect_curves(obj, obj.data, position)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\model.py", line 1840, in auto_detect_curves
    loop_verts.append(edge.other_vert(loop_verts[-1]))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BMEdge.other_vert(vert): BMVert expected, not 'NoneType'

```

**Comment by theoryshaw** [comment]
Having looked back, it appears this multitude of representation items was always there--just not noticeable in the editing UI before bonsai-0.8.1-alpha240921
To 'fix' these, is there a quick way to flatten all these items to (1) representation item?

**Comment by theoryshaw** [comment]
...or if accommodating the ability to [edit multiple items at on time](https://community.osarch.org/discussion/2594/moving-annotations-in-bulk), that would work too, and maybe better.
