### ISSUE TITLE
Unintentionally deleting all my layouts

### ISSUE THREAD

**Issue by sboddy** [IfcOpenShell/IfcOpenShell#5881]
Oh boy, I'm glad I use git to save my layouts, because it just saved me a ton of rework.

I was stripping my main file down to a minimal example to demonstrate another issue. I saved it in the same folder as the main file. As part of minimising the file I deleted the sheets in the demo file. This deleted the on-disk layout file. It is perhaps logical when thought about, but definitely was not intended.

Issue was discovered later when I tried to generate a sheet from the still intact main working file:
```
Error: Python: Traceback (most recent call last):
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 1773, in _execute
    sheet_builder.update_sheet_drawing_sizes(sheet)
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/sheeter.py", line 143, in update_sheet_drawing_sizes
    layout_tree = ET.parse(layout_path)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/blender/5561/4.2/python/lib/python3.11/xml/etree/ElementTree.py", line 1218, in parse
    tree.parse(source, parser)
  File "/snap/blender/5561/4.2/python/lib/python3.11/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/steve/Documents/Blender/BonsaiBIM/XXXXXXXXXXXXX/layouts/EX01 - Existing Site Plan.svg'
```
Perhaps actively deleting the on-disk file should be rethought? As far as I can tell, only the layouts were affected, but I'm still a basic user of Bonsai, so I may have missed other potential risks.
```
os: Linux
os_version: #136-Ubuntu SMP Wed Nov 6 10:38:22 UTC 2024
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: x86_64
blender_version: 4.2.4 LTS
bonsai_version: 0.8.1-alpha241201
bonsai_commit_hash: 1ecf722
last_actions: <snip - not relevant>
last_error: None
ifc: XXXXXXXXXXXXXX.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha241201
originating_system: Bonsai 0.8.1-alpha241201-1ecf722
```

**Comment by sboddy** [comment]
Can you upload an example problem file here (just give it a .txt extension) or alternatively (if you haven't already):

> Private files can be uploaded to https://ifcopenshell.org/upload.html - only viewed by core developers and will be deleted afterwards. Please submit your report first then upload private files afterwards.

**Comment by sboddy** [comment]
Still happens as of `bonsai_version: 0.8.3-alpha250619`

Perhaps a warning whenever an ifc is saved to a folder that already contains another ifc?

**Comment by BIMvoice** [comment]
@sboddy root-caused: layout SVGs are stored at a path derived only from the layouts folder plus the sheet's identification/name, resolved relative to the IFC file's directory. Two separate IFC files saved in the same folder that share a sheet identification/name resolve to and physically share the same on-disk file, so deleting a sheet in one can delete a layout the other still needs, with no undo. A confirmation warning (already proposed in #8425) is the fix on the deletion side, since safely detecting a foreign, unopened IFC file sharing the same path isn't something that can be done without opening and parsing every other file in the folder on each deletion. I also added a follow-up so opening a sheet whose layout is already missing reports a clean error instead of crashing, since that's the traceback you originally hit.

Generated with the assistance of an AI coding tool.
