### ISSUE TITLE
Bonsai - materials error -> cannot open drawing anymore

### ISSUE THREAD

**Issue by jes-r** [IfcOpenShell/IfcOpenShell#5883]
Hi, 

The file provided gives me the error below when I try to open "Begane Grond Hal" drawing. 

```
Python: Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1791, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1806, in execute
    core.activate_drawing_view(tool.Ifc, tool.Blender, tool.Drawing, drawing=drawing)
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\drawing.py", line 489, in activate_drawing_view
    drawing_tool.import_annotations_in_group(drawing_tool.get_drawing_group(drawing))
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 681, in import_annotations_in_group
    ifc_importer.create_generic_elements(elements)
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 646, in create_generic_elements
    products = self.create_products(elements, settings=settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 757, in create_products
    self.create_product(product, shape)
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 888, in create_product
    self.material_creator.create(element, obj, mesh)
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 77, in create
    self.load_texture_maps()
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 104, in load_texture_maps
    for style_or_material_id in self.mesh["ios_materials"]:
                                ~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'bpy_struct[key]: key "ios_materials" not found'
```

I don't know how to fix it and I don't know what to do...
[Error materials - Copy.ifc.txt](https://github.com/user-attachments/files/18166315/Error.materials.-.Copy.ifc.txt)

Might be related to the 200 unused Unnamed materials i can't delete either as they are used by something I don't know.

Any help would be greatly appreciated!!

**Comment by jes-r** [comment]
I kinda fixed / got around it!

I got similar problems before, where the view wouldn't open.


Most times saving and reloading the IFC file worked (though taking a long time), but in some very few cases (2-3 times this year) I found out that duplicating the view and deleting the old one resolves the error. This was the case here too.

It seems an array didn't get through properly, maybe that was the problem, but that doesn't really use materials so I don't know.


Maybe keep this open for the real solution / for the multiple undeletable materials part?

**Comment by Andrej730** [comment]
@jes-r are you sure you're using latest version of Bonsai (from Github releases - https://github.com/IfcOpenShell/IfcOpenShell/releases/)? 
Couldn't reproduce the issue - opened the file and activated the drawing "Begane Grond Hal" without any errors.

**Comment by Moult** [comment]
I can confirm that this was a bug on the last stable release but since has been fixed. Closing.
