### ISSUE TITLE
Blender crash on door creation

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [IfcOpenShell/IfcOpenShell#5888]
Hi,

Following #5884, I have tried to add new door but blender crash, see attachment, and following logs:

```
Successfully loaded existing cache: fee6b412ecc0e579867aa62e5b418395.h5.
Export finished in 0.01 seconds
Starting export
Export finished in 0.01 seconds
Info: IFC Project "room1.ifc"  Saved
New cache was created.
Traceback (most recent call last):
  File "/home/esteban/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/geometry/ui.py", line 130, in draw
    RepresentationsData.load()
  File "/home/esteban/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/geometry/data.py", line 108, in load
    cls.data["shape_aspects"] = cls.shape_aspects()
                                ^^^^^^^^^^^^^^^^^^^
  File "/home/esteban/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/geometry/data.py", line 170, in shape_aspects
    base_representation = tool.Ifc.get().by_id(active_representation_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esteban/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/file.py", line 484, in by_id
    return self[id]
           ~~~~^^^^
  File "/home/esteban/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/file.py", line 469, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esteban/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 6770, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #0 not found
Writing: /tmp/blender.crash.txt
```

[blender.crash.txt](https://github.com/user-attachments/files/18188674/blender.crash.txt)

**Comment by Andrej730** [comment]
@EstebanDugueperoux2 Hi! Please describe the exact steps to reproduce the crash.

**Comment by EstebanDugueperoux2** [comment]
Hi @Andrej730, I think this occurs when doing many undo.
I follows https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/bonsai/docs/tutorials/project0.rst until step 3.
I add some opening randomly with "Door Tool" (Quick Create IfcDoorType) do several undo (Ctrl+Z) and blender crash.

**Comment by steverugi** [comment]
@EstebanDugueperoux2 
please try these clips I posted on OSArch
[link](https://community.osarch.org/discussion/2688/how-to-make-a-void-in-a-roof-or-a-sloped-wall)

scroll down until you find this:

![image](https://github.com/user-attachments/assets/946dcd5e-fd26-4e2c-9228-7f9fe7eb99f2)


**you need an updated version of Bonsai to follow through**

In case go to  [this page](https://github.com/IfcOpenShell/IfcOpenShell/releases) to install it

hope it helps

**Comment by Moult** [comment]
Bump- any chance of recreating this reliably and/or submitting the full debug log that shows events before the error? Are you using .blend files or .ifc files (preferred)?

As it stands this is unfortunately not enough data to go on.

**Comment by EstebanDugueperoux2** [comment]
Hi Moult, Steverugi,

Thanks Steverugi for your tutorial.

I have attached a screencast, at the end I do several undo until blender crash.

https://github.com/user-attachments/assets/69172c92-6850-418a-9c6f-330d66d5be4b

Regards.

**Comment by Moult** [comment]
I can't recreate this crash unfortunately. I've followed your steps exactly. Can you try with no other add-ons installed? It seems Sverchok has an error (but I don't know if it's related or if it's fatal).

Can anybody else try to recreate this? Ping @Andrej730 @theoryshaw @Gorgious56 @brunoperdigao ?

**Comment by Andrej730** [comment]
Couldn't reproduce this on Windows.

**Comment by Gorgious56** [comment]
Please update blender to V4.3.2 https://www.blender.org/download/

**Comment by brunoperdigao** [comment]
Weird... I was able to reproduce this using blender 4.3.2 on both Windows and Linux. It seems to happen whenever I undo after adding doors or windows to a wall. It doesn't happen if I manually add an opening though. Anything else I should try?

**Comment by EstebanDugueperoux2** [comment]
Hi,

I have uninstalled Sverchok on my blender 4.3.1 and reproduce the bug.
Reproduced also with a fresh blender 4.3.2 and also after having deleted ~/.config/blender/ and installed unstable bonsai from https://github.com/IfcOpenShell/bonsai_unstable_repo.

Reading https://docs.blender.org/api/current/info_gotcha.html#help-my-script-crashes-blender, and trying to debug bonsai addon using https://docs-unstable.bonsaibim.org/guides/development/debugging.html
I have following stack:

Warning: extensions.blender.org: [Errno 2] No such file or directory: '/home/esteban/.config/blender/4.3/extensions/raw_githubusercontent_com/bonsai/extensions/blender_org'
Warning: User Default: [Errno 2] No such file or directory: '/home/esteban/.config/blender/4.3/extensions/raw_githubusercontent_com/bonsai/extensions/user_default'
Error in bpy.app.handlers.undo_post[0]:
Traceback (most recent call last):
  File "/home/esteban/.config/blender/4.3/extensions/raw_githubusercontent_com/bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/handler.py", line 226, in undo_post
    IfcStore.undo(until_key=bpy.context.scene.BIMProperties.last_transaction)
  File "/home/esteban/.config/blender/4.3/extensions/raw_githubusercontent_com/bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/ifc.py", line 497, in undo
    transaction["rollback"](transaction["data"])
  File "/home/esteban/.config/blender/4.3/extensions/raw_githubusercontent_com/bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/ifc.py", line 288, in rollback_link_element
    del IfcStore.id_map[data["id"]]
        ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 151
Writing: /tmp/blender.crash.txt

Regards.

**Comment by Moult** [comment]
@brunoperdigao @EstebanDugueperoux2 can you still recreate this? (note a few things just changed in regards to door generation which might affect this)

@brunoperdigao if you can still recreate this, perhaps we can screenshare to debug together?

**Comment by EstebanDugueperoux2** [comment]
Hi @Moult,

Blender doesn't crash anymore on undo of door creation, but crash after on undo of wall creation.

Regards.

**Comment by Moult** [comment]
How about window creation?

**Comment by EstebanDugueperoux2** [comment]
I don't got bug with window, only with door :

https://github.com/user-attachments/assets/a5cfd27d-4333-4296-a5f3-c0b7b6672424

Regards.

**Comment by Moult** [comment]
I still can't recreate the crash, but I can recreate the undo error. Undo errors and crashes do correlate, so hopefully the fix means something.

I'm not entirely sure whether the daily unstable build catches to-the-minute updates, so maybe wait until tomorrow and test again.

**Comment by EstebanDugueperoux2** [comment]
Hi,

I have updated now to 0.8.2-alpha250216 but it crashes always.
I'll try again next week.

Regards

**Comment by Moult** [comment]
OK, hopefully we've figured it out. @brunoperdigao and I had quite a long session trying out different things until @brunoperdigao found a reliable way to recreate the crash:

 1. New blank project
 2. Quick create wall type
 3. Draw single wall
 4. Quick create door type
 5. Add single door... and this is important, press ESC to finish drawing doors. Don't press RMB.
 6. Ctrl Z a couple times.
 7. Crash :)

The difference is that RMB sends the {"FINISH"} value which completes the IFC operator and adds a Blender undo step, whereas ESC sends a {"CANCELLED"} value, does not complete the IFC operator, and does not add a Blender undo step. Commit 645298e now handles these situations in modals.

**Comment by EstebanDugueperoux2** [comment]
Hi,

What is RMB? Is it the Enter button.
It seems to have no coherency between tool on the key to indicate the end of editing.
When using slab or wall tools, I use Esc or Enter to finish the editing but with Door tool it seems I must use Enter and Esc.

Regards.

**Comment by steverugi** [comment]
RMB = right mouse button

**Comment by EstebanDugueperoux2** [comment]
Thanks all for your help, as I have no more blender crash on this use case, I close this ticket.
I'll open another ticket for another bug encountered.
