### ISSUE TITLE
Bonsai v0.8.1-alpha241220 - cannot edit any 2d linetypes except Untyped

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#5897]
Blender 4.3.2
Bonsai v0.8.1-alpha241220
Ubuntu linux 

I believe I have posted this issue in the past but can't find it, so if it is a duplicate apologies
Essentially it is impossible to edit 2d lines in the latest Bonsai, which is a major issue for drawings.

With every file:

In a drawing
Add a dashed line
select the line and tab into edit mode:

gives this error:

```
os: Linux
os_version: #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024
python_version: 3.11.9
architecture: ('64bit', 'ELF')
machine: x86_64
processor: x86_64
blender_version: 4.3.2
bonsai_version: 0.8.1-alpha241220
bonsai_commit_hash: 40f1055
last_actions: 
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1665, "Name": "MY STOREY PLAN"}}
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 15, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/MY STOREY PLAN\") at 0x705a9372b308>", "geometry": "<bpy_struct, Camera(\"15/1702.001\") at 0x705a93239908>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 1712, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1665, "Name": "MY STOREY PLAN"}, "representation": {"cast_type": "entity_instance", "value": 1702, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 1702, "Name": null}}
# operator: BIM_OT_annotation_hotkey
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcAnnotation", "predefined_type": "LINEWORK", "name": "DASHED"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 1713, "Name": "DASHED"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, -6.097445011138916], [0.0, 1.0, 0.0, 3.566152572631836], [0.0, 0.0, 1.0, 0.6000000238418579], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1713, "Name": "DASHED"}}
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 29, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcAnnotation/DASHED\") at 0x705ab6920b08>", "geometry": "<bpy_struct, Mesh(\"LINEWORK\") at 0x705a90162e08>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "", "profile_set_usage": "None"}
# ifcopenshell.api: geometry.assign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 1713, "Name": "DASHED"}, "representation": {"cast_type": "entity_instance", "value": 1722, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1713, "Name": "DASHED"}}
# ifcopenshell.api: type.assign_type
>>> {"related_objects": [{"cast_type": "entity_instance", "value": 1713, "Name": "DASHED"}], "relating_type": {"cast_type": "entity_instance", "value": 78, "Name": "DASHED"}}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: group.assign_group
>>> {"group": {"cast_type": "entity_instance", "value": 1677, "Name": "MY STOREY PLAN"}, "products": [{"cast_type": "entity_instance", "value": 1713, "Name": "DASHED"}]}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1678, "Name": null}}
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_override_mode_set_edit
# operator: BIM_OT_import_representation_items
last_error: Traceback (most recent call last):
  File "/home/work/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/ifc.py", line 441, in execute_ifc_operator
    result = getattr(operator, "_invoke")(context, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/geometry/operator.py", line 1867, in _invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/tool/ifc.py", line 291, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/home/work/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/geometry/operator.py", line 1873, in _execute
    self.handle_single_object(context, context.active_object)
  File "/home/work/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/geometry/operator.py", line 1910, in handle_single_object
    bpy.ops.bim.import_representation_items()
  File "/snap/blender/5673/4.3/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/work/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/geometry/operator.py", line 2632, in _execute
    item_ids = data["ios_item_ids"] if "ios_item_ids" in data else data["ios_edges_item_ids"]
                                                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'bpy_struct[key]: key "ios_edges_item_ids" not found'
Location: /snap/blender/5673/4.3/scripts/modules/bpy/ops.py:109


ifc: Dash line test.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha241220
originating_system: Bonsai 0.8.1-alpha241220-40f1055
```

This issue is apparent with these line types:
![image](https://github.com/user-attachments/assets/49d5c8f7-4cd2-41b4-9bc6-c846130ae67f)

Essentially all line types except Untyped line

**Comment by Plae-Blue-Dot** [comment]
A workaround is to add a linetype as untyped and then classify it's type later, this does not work on existing classified types

I'm not sure if this has anything to do with it, but the untyped line type adds the line open in edit mode when it is added, and all the other line types get added opening in object mode

**Comment by sboddy** [comment]
Another workaround is to create the line as an annotation, then don't use the Tab key. Instead use the mode drop down to switch between Object and Edit mode. It has been working for me.

**Comment by theoryshaw** [comment]
+1

**Comment by theoryshaw** [comment]
Related: https://github.com/IfcOpenShell/IfcOpenShell/issues/5488
