### ISSUE TITLE
Error editing material style

### ISSUE THREAD

**Issue by aslejo0395** [IfcOpenShell/IfcOpenShell#5907]
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.9
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
blender_version: 4.3.0
bonsai_version: 0.8.1-alpha241223
bonsai_commit_hash: 6b0b798
last_actions: 
# operator: BIM_OT_edit_material_style
# ifcopenshell.api: style.assign_material_style
>>> {"material": {"cast_type": "entity_instance", "value": 206, "Name": "Wood"}, "style": {"cast_type": "entity_instance", "value": 966, "Name": "Wood"}, "context": {"cast_type": "entity_instance", "value": 15, "Name": null}}
last_error: Traceback (most recent call last):
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\material\operator.py", line 841, in _execute
    tool.Material.update_elements_using_material(material)
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\tool\material.py", line 296, in update_elements_using_material
    tool.Geometry.reload_representation(objects)
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 1155, in reload_representation
    representation = tool.Geometry.get_active_representation(obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 465, in get_active_representation
    if obj.data and hasattr(obj.data, "BIMMeshProperties") and obj.data.BIMMeshProperties.ifc_definition_id:
       ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

ifc: BonsaiFullDemo_01.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha241223
originating_system: Bonsai 0.8.1-alpha241223-6b0b798
```

**Comment by Andrej730** [comment]
@aslejo0395 Hi! Please provide a file and material name you were editing to reproduce the issue. 
It seems for some reason in your case one of the elements that use material don't have a corresponding Blender object leading to this issue, need to know what kind of object it is to fix the issue.

**Comment by Andrej730** [comment]
@aslejo0395 ping

**Comment by BIMvoice** [comment]
I think old issues where the creator is not providing more info/not following should be closed. If this is still an issue they can create another one next time they try, or there is also a chance this has been fixed already.

**Comment by aslejo0395** [comment]
Good morning
I haven't been able to replicate the error after an update. So, I think it was fix or it was on my part.

Thank you for your help.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
