### ISSUE TITLE
ifcsverchok - can't run

### ISSUE THREAD

**Issue by ppaawweeuu** [IfcOpenShell/IfcOpenShell#5913]
I can't launch ifcsverchok addon. Can you give me some advice?
I use blender 4.3.1, bonsai 0.8.1 alpha241230, sverchok 1.2.0
(I have the same problem using blender 4.2, bonsai 0.8...)
Console:
```
- Addon sverchok is not installed.
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\modules\addon_utils.py", line 428, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\ifcsverchok\__init__.py", line 74, in <module>
    ensure_addons_are_enabled("bonsai", "sverchok")
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\ifcsverchok\__init__.py", line 71, in ensure_addons_are_enabled
    raise Exception("Some issues were found trying to enable IFC Sverchok:\n" + "\n".join(errors))
Exception: Some issues were found trying to enable IFC Sverchok:
- Addon sverchok is not installed.
```

Screen. I have bonsai and sverchok installed.

![image](https://github.com/user-attachments/assets/3beab5ac-8f6f-4bd5-b9b8-08699b070fa9)

**Comment by ppaawweeuu** [comment]
I tested sverchok from:
Releases / [ifcsverchok-0.8.1.241028](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/ifcsverchok-0.8.1.241028)
Releases / [ifcsverchok-0.8.1](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/ifcsverchok-0.8.1)
the same result, error: "Addon sverchok is not installed"

I found creepy workaround. I turned off ensure test by manually editing `__init__.py` file, in sverchok directory, before installing. I added hashes in lines below:
```
#def ensure_addons_are_enabled(*addon_names: str) -> None:
#    errors = []
#    for addon_name in addon_names:
#        try:
#            module = get_blender_addon_package_by_name(addon_name)
#            # `__addon_enabled__` is not present if addon wasn't enabled before
#            if not getattr(module, "__addon_enabled__", False):
#                errors.append(f"- Addon {addon_name} appears to be disabled, it should be enabled before IFC Sverchok.")
#        except ModuleNotFoundError:
#            errors.append(f"- Addon {addon_name} is not installed.")

#    if errors:
#        raise Exception("Some issues were found trying to enable IFC Sverchok:\n" + "\n".join(errors))


#ensure_addons_are_enabled("bonsai", "sverchok")
```
It worked. It seems I can use ifcsverchok now. I tested few node setups, looks fine.
I suspect that my sverchok somehow is not "sverchok" which ensure test trying to find. I don't know how to verify it.
I was able to open and edit example file from ifcsverchok [folder](https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.8.0/src/ifcsverchok/example_files)

![image](https://github.com/user-attachments/assets/753b6e57-3bdc-4ee8-bcfa-801829432903)

**Comment by Andrej730** [comment]
I assume it's one of those cases when sverchok is installed by some other name besides "sverchok", will address in the next commit.

![image](https://github.com/user-attachments/assets/1830e73d-6e37-4384-8e56-4890b3abb160)
