### ISSUE TITLE
ifcpatch migrate: cannot migrate IfcAnnotationFillAreaOccurrence

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#5917]
## Issue description
Currently migrate recipe fails when you encounter an `IfcAnnotationFillAreaOccurrence`:
```python
Python: Traceback (most recent call last):
  File "C:\Users\Cyril\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\schema.py", line 279, in migrate_class
    new_element = new_file.create_entity(element.is_a())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cyril\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\ifcopenshell\file.py", line 352, in create_entity
    e = entity_instance((self.schema_identifier, type), self)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cyril\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\ifcopenshell\entity_instance.py", line 154, in __init__
    e = ifcopenshell_wrapper.new_IfcBaseClass(*e)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cyril\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 9574, in new_IfcBaseClass
    return _ifcopenshell_wrapper.new_IfcBaseClass(schema_identifier, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Entity with name 'IfcAnnotationFillAreaOccurrence' not found in schema 'IFC4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cyril\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\schema.py", line 286, in migrate_class
    new_element = new_file.create_entity(self.class_2x3_to_4[element.is_a()])
                                         ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'IfcAnnotationFillAreaOccurrence'
```

This case was encountered with a file coming from ArchiCAD.

## Workaround
use a script to remove `IfcAnnotationFillAreaOccurrence`:
```python
from pathlib import Path
import ifcopenshell

ifc_path = Path("./your_ifc_file_path.ifczip")
model = ifcopenshell.open(ifc_path)

for element in model.by_type("IfcAnnotationFillAreaOccurrence"):
    try:
        model.remove(element)
    except AttributeError:
        continue

model.write(ifc_path)
```

## How to fix ?
* [IfcAnnotationFillAreaOccurrence](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcpresentationdefinitionresource/lexical/ifcannotationfillareaoccurrence.htm) does exist in IFC2X3 but not in IFC4
* Support is not planned in ifcopenshell: https://github.com/IfcOpenShell/IfcOpenShell/issues/59

So should we just delete it an warn user about it ?

**Comment by aothms** [comment]
Should it just be converted to its supertype `IfcStyledItem`?
