### ISSUE TITLE
Build under macOS 10.14.5 fails

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#608]
Tried to build, but got only

```
This script fetches and builds IfcOpenShell and its dependencies

Script configuration:


* Target Architecture    = x86_64
 - Whether 32-bit (i686) or 64-bit (x86_64) will be built.
* USE_OCCT               = True
 - Compiling against official Open Cascade
* Dependency Directory   = /Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9
 - The directory where IfcOpenShell dependencies are installed.
* Build Config Type      = RelWithDebInfo
 - The used build configuration type for the dependencies.
   Defaults to RelWithDebInfo if not specified.
* IFCOS_NUM_BUILD_PROCS  = 5
 - How many compiler processes may be run in parallel.

Building: pcre python libxml2 swig json boost occ IfcParse OpenCOLLADA IfcGeom IfcGeomServer IfcOpenShell-Python IfcConvert
using command log file '/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/logs/20190606.log'
Collecting dependencies:
Found existing cmake-3.4.1, skipping
Found existing pcre-8.39, skipping
Found existing swig, skipping
Fetching occt-7.3.0p3...   
directory '/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/build/occt' exists, skipping cloning
----------------------------------------------------------------------
error: pathspec 'V7_3_0p3' did not match any file(s) known to git

----------------------------------------------------------------------
Traceback (most recent call last):
  File "./build-all.py", line 532, in <module>
    revision="V" + OCCT_VERSION.replace('.', '_')
  File "./build-all.py", line 359, in build_dependency
    git_clone(download_url, target_dir=os.path.join(build_dir, download_name), revision=revision)
  File "./build-all.py", line 323, in git_clone
    run([git, "checkout", revision], cwd=target_dir)
  File "./build-all.py", line 281, in run
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `git checkout V7_3_0p3` returned exit code 1

```

BTW The build works if the dependencies are already loaded locally.

**Comment by aothms** [comment]
Yes, this is a bit of an oversight in the build script currently. It found your existing `occt` clone, made at a time you ran the build script at which that branch did not exist yet. The build script does not pull. Simplest is to do a quick `rm -r /Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/build/occt`

~~~
directory '/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/build/occt' exists, skipping cloning
~~~

**Comment by aothms** [comment]
Edit: it seems this is actually done correctly in the windows build script so should probably be done on nix as well. If you have time feel free to submit a Pull Request.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/nix/build-all.py#L290

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/win/build-deps.cmd#L458

**Comment by atibaut** [comment]
I will submit a Pull Request for that.

**Comment by kurb70** [comment]
Because it has not been tracked for so long, the issue can be considered obsolete.
