### ISSUE TITLE
*nix build script build-all.py doesn't work with Python 3.7.3

### ISSUE THREAD

**Issue by atibaut** [IfcOpenShell/IfcOpenShell#634]
When building the branch 0.6.0 with Python 3.7.3 using the build-all.py following error is raised:

```
$ **python3 --version**
Python 3.7.3
$ **python3 build-all.py**
Traceback (most recent call last):
  File "build-all.py", line 158, in <module>
    DEPS_DIR = os.path.realpath(os.path.join(*path))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
**TypeError: Can't mix strings and bytes in path components**
```

I will create Pull Request for that.

**Comment by atibaut** [comment]
Pull Request #633 created.

**Comment by FreakTheMighty** [comment]
@atibaut I'm using branch `v0.6.0` and trying to build with python `3.6.9`. I'm hitting a similar error, any thoughts?

```python
Traceback (most recent call last):
  File "./build-all.py", line 758, in <module>
    os.environ["PYTHON_LIBRARY_BASENAME"]=os.path.basename(PYTHON_LIBRARY)
  File "/usr/lib/python3.6/os.py", line 674, in __setitem__
    value = self.encodevalue(value)
  File "/usr/lib/python3.6/os.py", line 744, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bytes
```
