### ISSUE TITLE
*nix build script build-all.py swig error

### ISSUE THREAD

**Issue by atibaut** [IfcOpenShell/IfcOpenShell#636]
I use the Python script build-all.py to build IfcOpenShell on Mac OS X 10.14.5.
Both commands
`python build-all.py` (Python 2.7.10) and `python3 build-all.py` (Python 3.7.3) stop with the following error:

```
Herango:nix andrejt$ python3 build-all.py
This script fetches and builds IfcOpenShell and its dependencies

Script configuration:
* Target Architecture    = b'x86_64'
 - Whether 32-bit (i686) or 64-bit (x86_64) will be built.
* USE_OCCT               = True
 - Compiling against official Open Cascade
* Dependency Directory   = /Users/andrejt/Research/repositories/git/IfcOpenShell/build/Darwin/x86_64
 - The directory where IfcOpenShell dependencies are installed.
* Build Config Type      = RelWithDebInfo
 - The used build configuration type for the dependencies.
   Defaults to RelWithDebInfo if not specified.
* IFCOS_NUM_BUILD_PROCS  = 9
 - How many compiler processes may be run in parallel.

Building: swig pcre json boost occ libxml2 python IfcParse OpenCOLLADA IfcGeom IfcGeomServer IfcOpenShell-Python IfcConvert
using command log file '/Users/andrejt/Research/repositories/git/IfcOpenShell/build/Darwin/x86_64/logs/20190627.log'
Collecting dependencies:
Found existing cmake-3.14.5, skipping
Downloading pcre-8.43...   
Configuring pcre-8.43...
Building pcre-8.43...   
Installing pcre-8.43... 
Installed pcre-8.43     

Checking swig...   
cloning 'https://github.com/swig/swig.git' into '/Users/andrejt/Research/repositories/git/IfcOpenShell/build/Darwin/x86_64/build/swig'
Configuring swig...
Building swig...   
----------------------------------------------------------------------
b'../../Tools/config/ylwrap: line 174: 89305 Abort trap: 6           "$prog" "$@" "$input"
make[1]: *** [CParse/parser.c] Error 134
make: *** [source] Error 2
make: *** Waiting for unfinished jobs....'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build-all.py", line 545, in <module>
    revision="rel-{SWIG_VERSION}".format(**locals())
  File "build-all.py", line 439, in build_dependency
    run([make, "-j%s" % (IFCOS_NUM_BUILD_PROCS,)], cwd=extract_build_dir)
  File "build-all.py", line 310, in run
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `make -j9` returned exit code 2
```

Can you help?

**Comment by aothms** [comment]
Not sure. Probably report this at the swig issue tracker if you can
replicate this easily without the ifcopenshell build script. Otherwise just
take swig from e.g homebrew. It's just an executable used during the build,
so the compiler settings do not need to be unified with the other
dependencies.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op do 27 jun. 2019 10:01 schreef Andrej Tibaut <notifications@github.com>:

**Comment by atibaut** [comment]
@aothms yes, I have reported that as an issue in the SWIG project (https://github.com/swig/swig/issues/1564) but it seems that main developers there are not as active as here ;-) 
I will try with the separate manual swig installation and will report back here.

**Comment by atibaut** [comment]
Great, the issue https://github.com/swig/swig/issues/1564 is moving forward and I was able to reproduce the problem by just building swig separately. Let's hope we get solution from the swig developers.
