### ISSUE TITLE
0.7 branch - Build under macOS 10.14.6 fails

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#667]
I gave it another try ;)

```
kubasMBPr:nix $ ./build-all.py 
This script fetches and builds IfcOpenShell and its dependencies

Script configuration:


* Target Architecture    = x86_64
 - Whether 32-bit (i686) or 64-bit (x86_64) will be built.
* USE_OCCT               = True
 - Compiling against official Open Cascade
* Dependency Directory   = /Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9
 - The directory where IfcOpenShell dependencies are installed.
* Build Config Type      = RelWithDebInfo
 - The used build configuration type for the dependencies.
   Defaults to RelWithDebInfo if not specified.
* IFCOS_NUM_BUILD_PROCS  = 5
 - How many compiler processes may be run in parallel.

Building: pcre libxml2 swig python json cgal boost occ voxel IfcParse OpenCOLLADA IfcGeom IfcGeomServer IfcOpenShell-Python IfcConvert
using command log file '/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/logs/20190908.log'
Collecting dependencies:
Found existing cmake-3.4.1, skipping
Found existing pcre-8.41, skipping
Found existing swig, skipping
Found existing occt-7.3.0p3, skipping
Found existing libxml2-2.9.9, skipping
Found existing OpenCOLLADA, skipping
Found existing python-3.7.3, skipping
Found existing boost-1.69.0, skipping
Found existing gmp-6.1.2, skipping
Found existing mpfr-3.1.5, skipping
Found existing cgal-4.13, skipping
Fetching voxel...   
Checking voxel...   
directory '/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/build/voxel' already cloned. Pulling latest changes.
Configuring voxel...
Building voxel...   
----------------------------------------------------------------------
/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/build/voxel/polyfill.cpp:246:12: warning: expression result unused [-Wunused-value]
        auto u = (q, p).cross(r);
                  ^
1 warning generated.
/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/build/voxel/storage.cpp:27:7: warning: equality comparison result unused [-Wunused-comparison]
                                1 == 1;
                                ~~^~~~
1 warning generated.
In file included from /Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/build/voxel/voxec.cpp:4:
/Users/kuba/dev/projects-bim/IfcOpenShell/build/Darwin/x86_64/10.9/build/voxel/voxec.h:964:3: warning: delete called on 'voxel_operation' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
                delete op;
                ^
ld: unknown option: --start-group
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test_covering] Error 1
make[1]: *** [CMakeFiles/test_covering.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
ld: unknown option: --start-group
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test_collapse] Error 1
make[1]: *** [CMakeFiles/test_collapse.dir/all] Error 2
ld: unknown option: --start-group
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test_boolean] Error 1
make[1]: *** [CMakeFiles/test_boolean.dir/all] Error 2
ld: unknown option: --start-group
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test_box_surface] Error 1
make[1]: *** [CMakeFiles/test_box_surface.dir/all] Error 2
1 warning generated.
make: *** [all] Error 2

----------------------------------------------------------------------
Traceback (most recent call last):
  File "./build-all.py", line 696, in <module>
    revision="master"
  File "./build-all.py", line 432, in build_dependency
    run([make, "-j%s" % (IFCOS_NUM_BUILD_PROCS,)], cwd=extract_build_dir)
  File "./build-all.py", line 302, in run
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `make -j5` returned exit code 2
```

**Comment by aothms** [comment]
Yes thanks. v0.7.0 is a bit experimental. I also noticed to my big surprise that the OSX linker does not support `--start-group` https://github.com/opensourceBIM/voxelization_toolkit/blob/master/CMakeLists.txt#L47 It'll need to be changed like this https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/cmake/CMakeLists.txt#L277 The same issue exists in the IfcOpenShell v0.7.0 CMakeLists

My advise would be to stick to v0.6.0 for now, but helping resolve these issues would obviously be much appreciated too!

**Comment by kurb70** [comment]
Thank you very much.

**Comment by CyrilWaechter** [comment]
@kurb70 This issue should probably be closed now. At least that ifcopenshell has a ci build on mac.

**Comment by kurb70** [comment]
Yes I agree. 🙂
