### ISSUE TITLE
How do I set lists in ifcopenshell.file.wrapped_data.header?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#747]
Potentially a bug? Potentially I have no idea how to do this properly in Python?

```
>>> f.wrapped_data.header.file_name.author
('$owner', '$email')

>>> f.wrapped_data.header.file_name.author = ('foo', 'bar')
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\moud308\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\ifcopenshell\ifcopenshell_wrapper.py", line 1056, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, FileName, name, value)
  File "C:\Users\moud308\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\ifcopenshell\ifcopenshell_wrapper.py", line 71, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "C:\Users\moud308\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\ifcopenshell\ifcopenshell_wrapper.py", line 60, in _swig_setattr_nondynamic
    return method(self, value)
  File "C:\Users\moud308\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\ifcopenshell\ifcopenshell_wrapper.py", line 1087, in author
    return _ifcopenshell_wrapper.FileName_author(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'FileName_author'.
  Possible C/C++ prototypes are:
    IfcParse::FileName::author() const
    IfcParse::FileName::author(std::vector< std::string > const &)
```

**Comment by shutterfreak** [comment]
I think the method to set `FileName::author` is not exposed in Python (nor are any other methods for setting any other IFC header attributes).

You can check this by using Python with the command-line. The Python interpreter supports tab completion. You can also use `dir()` to list all attributes in a Python object.

**Comment by Moult** [comment]
@shutterfreak I think you are correct, that there is no way to do it in Python - that's why I opened this bug :)

**Comment by Krande** [comment]
Hi, sorry for reviving this old thing:) 

I just ran into the same issue. Is there any progress on this or alternative workarounds?


Best Regards
Kristoffer

**Comment by aothms** [comment]
Sorry, lost track of this. https://github.com/IfcOpenShell/IfcOpenShell/commit/55b63410bd3ab87a73f89360bf903b23e5622405 should fix it, hopefully not at the expense of other stuff.

**Comment by Moult** [comment]
Confirming as fixed! Thanks so much!
