### ISSUE TITLE
Problem open sample IFC file with python

### ISSUE THREAD

**Issue by y5wang** [IfcOpenShell/IfcOpenShell#824]
I cannot even open the sample IFC file with `ifcopenshell.open()` with Python. My environment is:

- Windows 10 Pro 64bit
- Anaconda3
- Using Anaconda Python 3.7

To reproduce:
```
$ conda create -n ifc python=3.7
$ conda activate ifc
$ conda install -c conda-forge -c oce -c dlr-sc -c ifcopenshell ifcopenshell
$ wget wget ftp://ftp.dds.no/pub/ifc/Munkerud/Munkerud_hus6_BE.zip
$ unzip Munkerud_hus6_BE.zip
```
Here is the output when trying to open the IFC file in Python:
```
(ifc) PS D:\Sandbox\IFC> ls


    Directory: D:\Sandbox\IFC


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       2020-04-02   5:46 PM        4006246 Munkerud_hus6_BE.ifc

(ifc) PS D:\Sandbox\IFC> python
Python 3.7.7 (default, Mar 23 2020, 23:19:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> ifc_file = ifcopenshell.open('Munkerud_hus6_BE.ifc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Languages\Anaconda3\envs\ifc\lib\site-packages\ifcopenshell\__init__.py", line 67, in open
    raise IOError("Unable to open file for reading")
OSError: Unable to open file for reading
>>>
```

Any help is appreciated.

**Comment by Moult** [comment]
The code looks valid to me. Is another program locking the IFC file somehow, or not having permissions to access it? What is the file encoding?

**Comment by y5wang** [comment]
@Moult Thanks for the reply. 

No, there is no other program locking the IFC file which was just downloaded using the link provided in the README (BTW, the link http://projects.buildingsmartalliance.org/files/?artifact_id=4278 is not working). The same symptom happens on Ubuntu 18.04 as well as macOS Catalina:

```
(conda-env-ifc) [~]$ ls -la *.ifc
-rw-rw-rw-  1 yang  staff  4006246 14 Apr  2004 Munkerud_hus6_BE.ifc
(conda-env-ifc) [~]$ python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> ifc_file = ifcopenshell.open('Munkerud_hus6_BE.ifc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yang/anaconda3/envs/conda-env-ifc/lib/python3.7/site-packages/ifcopenshell/__init__.py", line 67, in open
    raise IOError("Unable to open file for reading")
OSError: Unable to open file for reading
>>> 
```

**Comment by Jesusbill** [comment]
Hi, it could be the file, try with this [IfcOpenHouse.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4431725/IfcOpenHouse.zip)
I reproduced your steps exactly in my Windows machine. I could not download the `Munkerud_hus6_BE` file but I tried with this old file and it does open it

````
(ifc) PS C:\Users\jesusbill> python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:22:21) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> ifc_file = ifcopenshell.open('IfcOpenHouse.ifc')
>>>
```

**Comment by y5wang** [comment]
Thanks @Jesusbill. Looks like it is the file. Now I can at least open it without the error. Here is the output from macOS:
```
(conda-env-ifc) [~]$ ls -la IfcOpenHouse.ifc 
-rw-rw-r--@ 1 yang  staff  103718 30 Oct  2015 IfcOpenHouse.ifc
(conda-env-ifc) [~]$ python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> ifc_file = ifcopenshell.open('IfcOpenHouse.ifc')
>>> 
```

Thanks again. The link to download `Munkerud_hus6_BE.ifc` is in the main README:
```
wget ftp://ftp.dds.no/pub/ifc/Munkerud/Munkerud_hus6_BE.zip
```

**Comment by Jesusbill** [comment]
> Thanks @Jesusbill. Looks like it is the file. Now I can at least open it without the error. Here is the output from macOS:

Sounds good, glad to hear it

> Thanks again. The link to download Munkerud_hus6_BE.ifc is in the main README:

Yes, for some reason I cannot succeed downloading it. I get this message

```
(base) PS C:\Users\jesusbill> wget ftp://ftp.dds.no/pub/ifc/Munkerud/Munkerud_hus6_BE.zip


StatusCode        : 0
StatusDescription :
Content           : {80, 75, 3, 4...}
RawContent        :
                    PK........dw?0"<U;g..f!=.....Munkerud_hus6_BE.ifc?\?n?:????~..-??Gc?G????Pl%q?S-;M?..9????S?I?>?&)
                    R?d?,5E?Wbs?!????G??hp?<??.?????s..?p?~9?t??v.?F???3?7????????.?.????hz??\M.??}?8]^??7??Q?1??O?{..{
                    ...
Headers           : {}
RawContentLength  : 728561
```

**Comment by y5wang** [comment]
@Jesusbill Thanks for the reply. The download seems OK for me on PowerShell 6.2.2:
```
PowerShell 6.2.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\Users\Yang Wang> cd \Tmp
PS C:\Tmp> wget ftp://ftp.dds.no/pub/ifc/Munkerud/Munkerud_hus6_BE.zip
--2020-04-05 12:01:07--  ftp://ftp.dds.no/pub/ifc/Munkerud/Munkerud_hus6_BE.zip
           => 'Munkerud_hus6_BE.zip'
Resolving ftp.dds.no (ftp.dds.no)... 217.68.104.163
Connecting to ftp.dds.no (ftp.dds.no)|217.68.104.163|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/ifc/Munkerud ... done.
==> SIZE Munkerud_hus6_BE.zip ... 728561
==> PASV ... done.    ==> RETR Munkerud_hus6_BE.zip ... done.
Length: 728561 (711K) (unauthoritative)

Munkerud_hus6_BE.zip          100%[=================================================>] 711.49K   461KB/s    in 1.5s

2020-04-05 12:01:10 (461 KB/s) - 'Munkerud_hus6_BE.zip' saved [728561]

PS C:\Tmp>
```
It looks like this file is of 2X2_FINAL instead of 2X3.

**Comment by Moult** [comment]
If you change it to read "2X3" instead of "2X2_FINAL", then IfcOpenShell will attempt to read it :)

**Comment by y5wang** [comment]
@Moult Perfect. It works after I change it to "2X3". Thanks. 

The error message can be a bit more informative. :)

Cheers.
