### ISSUE TITLE
Module OCC.AIS not found in app.py

### ISSUE THREAD

**Issue by GuillaumeQr** [IfcOpenShell/IfcOpenShell#847]
Hello there

I am trying to display some IFC files with IfcOpenShell but I'm facing some troubles. When I try to run the file app.py I have the error: 
```
Exception has occurred: ModuleNotFoundError
No module named 'OCC.AIS'
```
I'm working on Python 3.7.7 64 bit. I successfully installed PythonOCC package (pythonocc-core=7.4.0beta2). But when I check the site-package repository of my python environment, I can't find any AIS folder.
How couldI fix this error? Is there any update of IfcOpenShell?

**Comment by didi-ux** [comment]
Try checking the subfolder 'Core' within 'OCC'. The AIS module should be in there.
OCC.Core.AIS

**Comment by GuillaumeQr** [comment]
Thank you for your answer. But when I change OCC.AIS to OCC.Core.AIS I get other errors.

`Traceback (most recent call last):
  File "C:\Users\33674\Anaconda3\envs\newenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\33674\Anaconda3\envs\newenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\33674\.vscode\extensions\ms-python.python-2020.4.76186\pythonFiles\lib\python\debugpy\wheels\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\33674\.vscode\extensions\ms-python.python-2020.4.76186\pythonFiles\lib\python\debugpy\wheels\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\33674\.vscode\extensions\ms-python.python-2020.4.76186\pythonFiles\lib\python\debugpy\wheels\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Users\33674\Anaconda3\envs\newenv\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\33674\Anaconda3\envs\newenv\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\33674\Anaconda3\envs\newenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\33674\Anaconda3\envs\newenv\Lib\site-packages\ifcopenshell\geom\app.py", line 11, in <module>
    import OCC.Core.AIS
  File "C:\Users\33674\Anaconda3\envs\newenv\lib\site-packages\OCC\Core\AIS.py", line 18, in <module>
    from . import _AIS
ImportError: DLL load failed: La procédure spécifiée est introuvable.`

It seems that I'm missing some elements even if I didn't get any warnings during the installation.

**Comment by GuillaumeQr** [comment]
And I have also some troubles wth geom. When I try to use geom space, the space is not found even if I can see it with my auto complete tool 
`>>> import ifcopenshell
>>> settings = ifcopenshell.geom.settings()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ifcopenshell' has no attribute 'geom'`

**Comment by GuillaumeQr** [comment]
> And I have also some troubles wth geom. When I try to use geom space, the space is not found even if I can see it with my auto complete tool
> 
> ```
> import ifcopenshell
> settings = ifcopenshell.geom.settings()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: module 'ifcopenshell' has no attribute 'geom'
> ```

This is solved with: import ifcopenshell.geom

It seems that the version of IfcOpenShell is not compatible with this version of PythonOCC. I have errors at every import of PythonOCC. For the modules in OCC.Core it can be solved in replacing `import OCC.module` by `import OCC.Core`
But for other I just can't figure out how to solve this error. For instance I can't access the module SimpleGui: OCC.Display.SimpleGui. I always get the error: DLL load failed: `The specified module could not be found`

**Comment by civilx64** [comment]
I ran into this recently as well.  As suspected, the fix is to use an older version of PythonOCC.  I installed pythonocc-core=0.18.2 via conda from the CadQuery channel.

**Comment by aothms** [comment]
Yes, most of the code base is compatible with the newer versions of PythonOCC, just not the app I think. Should be fixed, this basically has already been addressed here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/geom/occ_utils.py#L31

**Comment by BIMvoice** [comment]
Housekeeping: @aothms said in 2020 this should be fixed with the pythonocc compatibility update, and there has been no follow-up in six years. The `geom.app` viewer utility also requires an optional pythonocc install that has moved on several major versions since. Safe to close as fixed/stale.

**Comment by BIMvoice** [comment]
Closing per the note above — aothms confirmed back in 2020 this was addressed via the pythonocc compatibility layer, and there's been no follow-up in six years. The `geom.app` viewer is an optional-dependency utility that has moved through several major pythonocc versions since; this specific import-path mismatch no longer applies to current setups. Reopen with your current pythonocc/ifcopenshell versions if you're still hitting this.

This comment was written with AI assistance.
