### ISSUE TITLE
BlenderBim 200621 on win10, not installing?

### ISSUE THREAD

**Issue by lalberts** [IfcOpenShell/IfcOpenShell#907]
Hello,
thanks a lot for your efforts.
Have a trouble with the BlenderBIM Add-On on 2.83LTS and ver0.0.200621 of BlenderBIM.zip

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\alberts\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\__init__.py", line 24, in <module>
    from .bim import *
  File "C:\Users\alberts\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\__init__.py", line 8, in <module>
    from . import ui, prop, operator
  File "C:\Users\alberts\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 10, in <module>
    from . import import_ifc
  File "C:\Users\alberts\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 3, in <module>
    import ifcopenshell.util.selector
ModuleNotFoundError: No module named 'ifcopenshell.util'

Need to change something in my Win10 setup?
Thanks
lukas

**Comment by Moult** [comment]
@lalberts it is likely that you have a much older installation of the BlenderBIM Add-on still lying around. In older versions, it was not fully contained in a single package, so even when you press the "remove" button in the Blender add-on preferences, it will not fully remove. This causes problems like this in upgrades. In newer versions, this has been fixed, so you should no longer run into this issue in the future.

Go into `C:\Users\alberts\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\` and clear our anything that doesn't belong to an add-on you have installed (especially delete anything called `ifcopenshell`), and then install the BlenderBIM Add-on fresh.

**Comment by lalberts** [comment]
That was it.. 

Thanks Dion.
