### ISSUE TITLE
Blender fails to import IFC 2X3 "line 89, in execute ifc_importer.execute()"

### ISSUE THREAD

**Issue by DuncanLithgow** [IfcOpenShell/IfcOpenShell#932]
Getting this when trying to import an IFC 2X3 file from Revit. Get in touch and I'll send you the file.

Blender 2.82, BlenderBIM Addon 200722, Ubuntu Linux

Traceback (most recent call last):
  File "/home/duncan/.config/blender/2.82/scripts/addons/blenderbim/bim/operator.py", line 89, in execute
    ifc_importer.execute()
  File "/home/duncan/.config/blender/2.82/scripts/addons/blenderbim/bim/import_ifc.py", line 347, in execute
    self.create_products()
  File "/home/duncan/.config/blender/2.82/scripts/addons/blenderbim/bim/import_ifc.py", line 769, in create_products
    self.create_product(self.file.by_id(shape.guid), shape)
  File "/home/duncan/.config/blender/2.82/scripts/addons/blenderbim/bim/import_ifc.py", line 817, in create_product
    self.material_creator.create(element, obj, mesh)
  File "/home/duncan/.config/blender/2.82/scripts/addons/blenderbim/bim/import_ifc.py", line 53, in create
    self.assign_material_slots_to_faces(obj, self.mesh)
  File "/home/duncan/.config/blender/2.82/scripts/addons/blenderbim/bim/import_ifc.py", line 121, in assign_material_slots_to_faces
    material_index = [(material_to_slot[mat_id] if mat_id != 999999
  File "/home/duncan/.config/blender/2.82/scripts/addons/blenderbim/bim/import_ifc.py", line 121, in <listcomp>
    material_index = [(material_to_slot[mat_id] if mat_id != 999999
KeyError: -1

location: <unknown location>:-1

**Comment by Moult** [comment]
Can you send the file to dion@thinkmoult.com?

I tried picking on IRC but didn't get a response :)

**Comment by DuncanLithgow** [comment]
MOLIO-model_RVT.ifc
<https://drive.google.com/file/d/1h-jzS_rf0kqsovNOQ3LxHd4agdgh7yFd/view?usp=drive_web>
Here's the file. It's the companion to this guide:
https://anvisninger.molio.dk/Gratis-vaerktojer/buildingSMART/IFC_Export_Guide_EN

**Comment by Moult** [comment]
@aothms what does a value of `-1` mean in `geometry.material_ids`?

@DuncanLithgow fixed, I think, depending on @aothms 's answer :) It imports now, though.
