### ISSUE TITLE
Blender fails to import IFC2X3 "...\import_ifc.py", line 118, ...."

### ISSUE THREAD

**Issue by KoertNL** [IfcOpenShell/IfcOpenShell#936]
Blender 2.83.3, BlenderBIM Add-on v0.0.200722, Windows 10 Pro

The IFC import is interrupted and I receive an error message.
The file is an IFC2X3 file from Revit.
Get in touch and I will send you the IFC file.

Traceback (most recent call last):
  File "C:\Users\koert\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 89, in execute
    ifc_importer.execute()
  File "C:\Users\koert\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 347, in execute
    self.create_products()
  File "C:\Users\koert\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 769, in create_products
    self.create_product(self.file.by_id(shape.guid), shape)
  File "C:\Users\koert\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 817, in create_product
    self.material_creator.create(element, obj, mesh)
  File "C:\Users\koert\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 53, in create
    self.assign_material_slots_to_faces(obj, self.mesh)
  File "C:\Users\koert\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 118, in assign_material_slots_to_faces
    material_to_slot[i] = slots.index(material)
ValueError: 'NLRS_g2_baksteen_wf_210x100x50_10mm_voeg_halfsteens_rood_genuan' is not in list

location: <unknown location>:-1

**Comment by Moult** [comment]
@KoertNL  thanks for the bug report! Can you please send your IFC to dion@thinkmoult.com ?

**Comment by KoertNL** [comment]
The IFC file has been sent to dion@thinkmoult.com.

**Comment by Moult** [comment]
@KoertNL thank you! It has been fixed! You are free to apply the fix yourself (just edit the source code based on the link above) if you don't want to wait for the next release.

**Comment by KoertNL** [comment]
Changed the source code based on the link and I can import the IFC file. 
Thank you for the quick response.
