### ISSUE TITLE
BlenderBIM: Exception on "Cut section" with variables in text

### ISSUE THREAD

**Issue by JanFilipec** [IfcOpenShell/IfcOpenShell#957]
I'm on Blender 2.83.5, BlenderBIM 0.0.200810. I'm trying to export object with linked text and variables and get the following exception:

Traceback (most recent call last):
  File "C:\Users\JA\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 2163, in execute
    ifc_cutter.cut()
  File "C:\Users\JA\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\cut_ifc.py", line 189, in cut
    self.get_template_variables()
  File "C:\Users\JA\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\cut_ifc.py", line 247, in get_template_variables
    text_obj_data = self.get_text_variables(text_obj)
  File "C:\Users\JA\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\cut_ifc.py", line 273, in get_text_variables
    variable_value = self.ifc_attribute_extractor.get_element_key(element, variable.prop_key)
AttributeError: type object 'IfcAttributeExtractor' has no attribute 'get_element_key'

location: <unknown location>:-1

Am I doing something wrong?

**Comment by JanFilipec** [comment]
![Text variable](https://user-images.githubusercontent.com/67052298/91301592-76faf600-e7a5-11ea-9c0d-4893a54a7566.JPG)

**Comment by Moult** [comment]
It was fixed 14 days ago. Sorry :)

https://github.com/IfcOpenShell/IfcOpenShell/commit/cee53689aab993a8b39a738f21d94eb0f80a9bd7#diff-77bf85efaaf32c7aa867d928404a8a53
