### ISSUE TITLE
BlenderBIM: Reload IFC file

### ISSUE THREAD

**Issue by e3i6** [IfcOpenShell/IfcOpenShell#961]
Hello,

I get an error when trying to reload a modified version of the same project. I'm using Blender 2.83 and BlenderBIM version 0.0.200621. Or I don't know how to use it.

There are a lot of progress being done to this add-on: Thank you and keep up the good work!

Blender error:
```
Traceback (most recent call last):
  File "C:\Users\user23\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 2626, in execute
    self.reimport_ifc(context)
  File "C:\Users\user23\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 2650, in reimport_ifc
    ifc_importer.execute()
  File "C:\Users\user23\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 313, in execute
    self.add_project_to_scene()
  File "C:\Users\user23\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 1029, in add_project_to_scene
    bpy.context.scene.collection.children.link(self.project['blender'])
RuntimeError: Error: Collection 'IfcProject/0001' already in collection 'Master Collection'


location: <unknown location>:-1
```

**Comment by Moult** [comment]
Can you provide your file for debugging? If it is private, feel free to send to dion@thinkmoult.com

**Comment by Moult** [comment]
By the way, v0.0.200621 is quite old, I would highly recommend upgrading to the latest version. The BlenderBIM Add-on code moves quite fast.

**Comment by e3i6** [comment]
Hum... I have two versions in folder, yesterday's and one of late July... I have installed the wrong one.  Will check that out on Monday and will let you know. Sorry for any inconvenience.

**Comment by e3i6** [comment]
Hello again,

I has used version 0.0.200829 downloaded today and I have the same error.

For a remainder:
1. I import a IFC file (exported by Revit 2021 (import successful)
2. I change the linked file target Scene Properties: System Stup: IFC File (from Test BlenderBIM.ifc to Test BlenderBIM2.ifc)
3. Checked RELOAD icon and got:
```
Traceback (most recent call last):
  File "C:\Users\eric.imboden\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 2989, in execute
    self.reimport_ifc(context)
  File "C:\Users\eric.imboden\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 3013, in reimport_ifc
    ifc_importer.execute()
  File "C:\Users\eric.imboden\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 354, in execute
    self.create_products()
  File "C:\Users\eric.imboden\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 802, in create_products
    self.create_product(self.file.by_id(shape.guid), shape)
  File "C:\Users\eric.imboden\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 858, in create_product
    self.add_defines_by_type_relation(element, obj)
  File "C:\Users\eric.imboden\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 1312, in add_defines_by_type_relation
    obj.BIMObjectProperties.relating_type = self.type_products[related_type.GlobalId]
KeyError: '0110Cd2uHDK966axsNCLyn'

location: <unknown location>:-1

```

I also test without step 2: same issue.

I prepared two dummy files so you can reproduce this bug.
[IFC-DummyFiles.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5149382/IFC-DummyFiles.zip)

I hope this is useful.
