### ISSUE TITLE
IfcOpeningElement without representation casuses import error

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#973]
I came across this error when trying to import a file. This is the line in question (in Vim, I used `188516012go` to jump to the correct location in the file):

```
#6274360= IFCOPENINGELEMENT('1k1jC1pfPACALY9kAEa3zC',#42,'Basic Wall:Wall_Brickwork_110BR:4860502',$,'Opening',#6274359,$,$);
```

I think this is due to the missing representation. I _think_ representations are mandatory for IfcOpeningElements although the spec isn't 100% explicit on the fact.

IFC file comes from Revit 2020.

If it is indeed invalid, can we treat this as a non-fatal issue and skip the opening?

```
Traceback (most recent call last):
  File "/home/dion/.config/blender/2.90/scripts/addons/blenderbim/bim/operator.py", line 119, in execute
    ifc_importer.execute()
  File "/home/dion/.config/blender/2.90/scripts/addons/blenderbim/bim/import_ifc.py", line 352, in execute
    self.create_products()
  File "/home/dion/.config/blender/2.90/scripts/addons/blenderbim/bim/import_ifc.py", line 782, in create_products
    valid_file = iterator.initialize()
  File "/home/dion/.config/blender/2.90/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 559, in initialize
    return _ifcopenshell_wrapper.iterator_double_precision_initialize(self)
RuntimeError: Token $ at 188,516,012 invalid instance name
```

**Comment by Moult** [comment]
Bump?

**Comment by BIMvoice** [comment]
Resolved on the current `v0.8.0`, and along the lines you suggested (skip the opening rather than fail). An `IfcOpeningElement` without a representation, voiding a wall that does have one, no longer crashes the iterator.

Verified: a wall with a body representation, voided via `IfcRelVoidsElement` by an opening that has no representation, produces geometry cleanly:

```python
create_shape(settings, wall)   # OK, 8 vertices
```

The representation-less opening is simply not subtracted (there is nothing to subtract), instead of taking down `iterator.initialize()`. Safe to close.
