### ISSUE TITLE
BlenderBIM: Possible to change the path of the 'data' folder?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#976]
Possible to change the path of the 'data' folder?

That is, change the path ```AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\data``` to somewhere else?

Helpful, obviously, for project specific documentation that you can save to a repo.

**Comment by Moult** [comment]
Yes, in theory, it can be done here - however, I think there were one or two places in the code where I do not correctly read the user-defined parameter... so keep a very close eye out for bugs if you do change it. I expect there to be bugs.

![image](https://user-images.githubusercontent.com/88302/92287459-2d509f00-ef4d-11ea-98f8-8a8307062010.png)

**Comment by theoryshaw** [comment]
once such bug after trying to create a sheet...

```
Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 2224, in execute
    svg_writer.write()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\svgwriter.py", line 55, in write
    self.add_stylesheet()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\svgwriter.py", line 73, in add_stylesheet
    with open('{}styles/{}.css'.format(self.ifc_cutter.data_dir, self.ifc_cutter.vector_style), 'r') as stylesheet:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Dropbox\\GitHub\\OD_Library\\BIM\\BlenderBIM\\datastyles/default.css'

location: <unknown location>:-1


```

**Comment by theoryshaw** [comment]
another one.. 

```
Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 2223, in execute
    ifc_cutter.cut()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\cut_ifc.py", line 197, in cut
    self.get_product_shapes()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\cut_ifc.py", line 336, in get_product_shapes
    with open(shape_pickle, 'wb') as shape_file:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Dropbox\\GitHub\\OD_Library\\BIM\\BlenderBIM\\data\\OD_BlenderBIM_Template.blend\\cache\\shapes\\OD_BlenderBIM_Template.blend.ifc.pickle'

location: <unknown location>:-1


```

**Comment by Moult** [comment]
@theoryshaw when you change the data_dir, for now, you need to copy over all relevant default settings. The easiest way to do this is to copy the entire default data dir to a new location prior to changing.

I am slowly cleaning up the data_dir to make it leaner, which would make it easier to switch to an almost blank folder. Hope it makes sense.

**Comment by theoryshaw** [comment]
I did, I ended up copying everything in the data directory over to the new location.

**Comment by Moult** [comment]
`D:\\Dropbox\\GitHub\\OD_Library\\BIM\\BlenderBIM\\datastyles/default.css` - looks like it has a missing "/" after data - try add that.
